import type { ProductionCaseVerificationRecord } from "./scenarioProductionVerification";

export const europeanPoliticalFeministModernismVerificationRecords = [
  {
    scenarioId: "scenario_cleo_from_5_to_7_1962",
    status: "verified",
    verifiedAt: "2026-07-20",
    summary: "The case's near-real-time Paris route, feminist transformation, black-and-white location image, colour tarot prologue, chaptered editing, documentary observation and Michel Legrand song structure are supported by Varda, BFI, Criterion and MoMA materials.",
    sources: [
      {
        title: "Cléo from 5 to 7",
        publisher: "The Criterion Collection",
        url: "https://www.criterion.com/films/244-cleo-from-5-to-7",
        sourceKind: "archive_feature",
        supports: ["overall", "screenplay", "cinematography", "editing", "sound"],
        note: "Criterion records the near-real-time structure, Paris setting, vivid vérité and melodrama mixture, 1.66:1 presentation, principal craft credits and Varda-supervised restoration materials."
      },
      {
        title: "Cléo from 5 to 7: Passionate Time",
        publisher: "The Criterion Collection",
        url: "https://www.criterion.com/current/posts/499-cleo-from-5-to-7-passionate-time",
        sourceKind: "archive_feature",
        supports: ["overall", "screenplay", "cinematography", "editing"],
        note: "Adrian Martin explains how the film reconstructs real time through active photography and editing rather than a single take, joining fiction to cinéma-vérité immediacy."
      },
      {
        title: "Seven facets of Agnès Varda",
        publisher: "British Film Institute",
        url: "https://www.bfi.org.uk/sight-and-sound/features/seven-facets-agnes-varda",
        sourceKind: "film_institute",
        supports: ["overall", "screenplay", "cinematography"],
        note: "The BFI places the film in the Left Bank New Wave, documents the June-July 1961 Paris location shoot, black-and-white body, colour opening, feminist gaze and Algerian War context."
      },
      {
        title: "Agnès Varda retrospective",
        publisher: "Museum of Modern Art",
        url: "https://www.moma.org/interactives/exhibitions/1997/varda/",
        sourceKind: "film_institute",
        supports: ["overall", "screenplay", "cinematography"],
        note: "MoMA describes Varda's combination of narrative and reality, everyday women's lives, artisanal production practice and the international attention generated by Cléo from 5 to 7."
      }
    ]
  },
  {
    scenarioId: "scenario_the_conformist_1970",
    status: "verified",
    verifiedAt: "2026-07-20",
    summary: "The case's Moravia adaptation, fractured flashback structure, Fascist architecture, Scarfiotti design, Storaro colour-and-shadow system, moving camera and Delerue score are supported by BFI, ASC, MoMA and Film at Lincoln Center sources.",
    sources: [
      {
        title: "The Conformist",
        publisher: "British Film Institute",
        url: "https://www.bfi.org.uk/film/7f8c297d-0a54-5c9a-a2bb-5fa59b50a66b/the-conformist",
        sourceKind: "film_institute",
        supports: ["overall", "screenplay", "cinematography", "editing", "sound"],
        note: "BFI documents the complex flashback structure, Mussolini-era political psychology, Ferdinando Scarfiotti's period design, Vittorio Storaro's dynamic photography and principal production credits."
      },
      {
        title: "Shadows of the Psyche: The Conformist",
        publisher: "American Cinematographer",
        url: "https://theasc.com/articles/shadows-of-the-psyche-the-conformist",
        sourceKind: "trade_feature",
        supports: ["overall", "cinematography"],
        note: "Storaro and ASC cinematographers detail the director-DP collaboration, visual cage of sharp light and shadow, architecture, moving compositions, limited arc-light resources and striped-dress lighting accident."
      },
      {
        title: "Bernardo Bertolucci retrospective",
        publisher: "Museum of Modern Art",
        url: "https://www.moma.org/calendar/film/1112",
        sourceKind: "film_institute",
        supports: ["overall", "cinematography", "sound"],
        note: "MoMA records the international production's retrospective context and new prints with sound and colour corrections overseen by Bertolucci's cinematography collaborators, including Storaro."
      },
      {
        title: "The Conformist",
        publisher: "Film at Lincoln Center",
        url: "https://www.filmlinc.org/films/the-conformist/",
        sourceKind: "film_institute",
        supports: ["overall", "screenplay", "cinematography", "sound"],
        note: "Film at Lincoln Center confirms the Moravia adaptation, 35mm colour presentation, Fascist political framework, Storaro cinematography, Georges Delerue score and Cinecittà print provenance."
      }
    ]
  },
  {
    scenarioId: "scenario_jeanne_dielman_23_quai_du_commerce_1080_bruxelles_1975",
    status: "verified",
    verifiedAt: "2026-07-20",
    summary: "The case's three-day routine, complete domestic labour, fixed frontal camera, measured duration, direct household sound, controlled colour and CINEMATEK restoration are supported by BFI, Criterion, MoMA and Belgian archive partnerships.",
    sources: [
      {
        title: "Jeanne Dielman, 23 Quai du Commerce, 1080 Bruxelles",
        publisher: "British Film Institute",
        url: "https://www.bfi.org.uk/film/00638537-48d0-5522-9502-4e5ba0166194/jeanne-dielman-23-quai-du-commerce-1080-bruxelles",
        sourceKind: "film_institute",
        supports: ["overall", "screenplay", "cinematography", "editing", "sound"],
        note: "BFI documents the three-day domestic structure, extended time, fixed camera position, feminist avant-garde context and the conversion of routine work into the film's formal system."
      },
      {
        title: "Chantal Akerman film catalogue acquired by BFI Distribution",
        publisher: "British Film Institute",
        url: "https://www.bfi.org.uk/news/chantal-akerman-film-catalogue-acquired-bfi-distribution",
        sourceKind: "film_institute",
        supports: ["overall", "cinematography", "editing"],
        note: "The BFI documents the Fondation Chantal Akerman and CINEMATEK partnership, Akerman's New York experimental influences, the production's financing and its continuing restoration and distribution history."
      },
      {
        title: "A Matter of Time: Jeanne Dielman, 23, quai du Commerce, 1080 Bruxelles",
        publisher: "The Criterion Collection",
        url: "https://www.criterion.com/current/posts/1215-a-matter-of-time-jeanne-dielman-23-quai-du-commerce-1080-bruxelles",
        sourceKind: "archive_feature",
        supports: ["overall", "screenplay", "cinematography", "editing", "sound"],
        note: "Criterion's essay analyses long stark takes, literal duration, repeated household tasks, concrete women's work, gesture, direct sound and the gradual disturbance of predictable order."
      },
      {
        title: "Jeanne Dielman restoration presentation",
        publisher: "Museum of Modern Art",
        url: "https://www.moma.org/calendar/events/1509",
        sourceKind: "archive_feature",
        supports: ["overall", "cinematography", "editing"],
        note: "MoMA documents the 35mm colour negative, careful colour scheme, digital restoration by Belgium's Cinémathèque Royale and the participation of cinematographer Babette Mangolte in the preservation presentation."
      }
    ]
  },
  {
    scenarioId: "scenario_beau_travail_1999",
    status: "verified",
    verifiedAt: "2026-07-20",
    summary: "The case's Billy Budd adaptation, Djibouti locations, choreographed Legion routines, fragmented memory, Agnès Godard photography, Nelly Quettier editing and music-led body system are supported by Criterion and extensive BFI interviews and institutional analysis.",
    sources: [
      {
        title: "Beau travail",
        publisher: "The Criterion Collection",
        url: "https://www.criterion.com/films/29646-beau-travail",
        sourceKind: "archive_feature",
        supports: ["overall", "screenplay", "cinematography", "editing", "sound"],
        note: "Criterion records the Billy Budd adaptation, Djibouti setting, 1.66:1 colour presentation, Godard cinematography, Quettier editing, Montet choreography, design, costume, sound and music credits."
      },
      {
        title: "Desire is violence: Claire Denis on Beau Travail",
        publisher: "British Film Institute",
        url: "https://www.bfi.org.uk/sight-and-sound/interviews/claire-denis-beau-travail-michel-subor-denis-lavant-gregoire-colin-french-foreign-legion-djibouti",
        sourceKind: "filmmaker_interview",
        supports: ["overall", "screenplay", "cinematography", "editing", "sound"],
        note: "Denis discusses casting, recurring collaborators, Djibouti, the Legion, music, editing rhythm, Agnès Godard's image practice and the security and exploration enabled by a long-term creative team."
      },
      {
        title: "Beau Travail",
        publisher: "BFI Sight and Sound",
        url: "https://old.bfi.org.uk/sightandsound/review/302",
        sourceKind: "film_institute",
        supports: ["overall", "screenplay", "cinematography", "editing", "sound"],
        note: "The BFI record confirms the French coproduction structure and principal screenplay, cinematography, editing, art direction and music departments behind the film's location-and-body system."
      },
      {
        title: "Blood and sand: what makes Beau Travail great",
        publisher: "BFI Sight and Sound",
        url: "https://www.bfi.org.uk/sight-and-sound/features/beau-travail-1998-claire-denis-greatest-films-poll",
        sourceKind: "film_institute",
        supports: ["overall", "cinematography", "editing", "sound"],
        note: "The BFI analysis connects the near-defunct colonial outpost, female-authored view of military masculinity, Godard's images, Quettier's rhythmic assembly and the film's bodily and political perspective."
      }
    ]
  }
] as const satisfies readonly ProductionCaseVerificationRecord[];
