import assert from "node:assert/strict";
import test from "node:test";

import { chapterEighteenColdWarExpansionDefinitions } from "./chapterEighteenColdWarExpansion.js";

test("Chapter 18 materializes Cold War as a source-first transnational monochrome production case", () => {
  assert.equal(chapterEighteenColdWarExpansionDefinitions.length, 1);
  const film = chapterEighteenColdWarExpansionDefinitions[0];
  assert.equal(film.id, "scenario_cold_war_2018");
  assert.equal(film.title, "Cold War");
  assert.equal(film.originalTitle, "Zimna wojna");
  assert.equal(film.year, 2018);
  assert.equal(film.runtimeMins, 90);
  assert.deepEqual(film.directors, ["Paweł Pawlikowski"]);
  assert.ok(film.scenarioType.includes("transnational_poland_uk_france") && film.scenarioType.includes("alexa_xt"));
  assert.ok(film.scenarioType.includes("arriraw_opengate") && film.scenarioType.includes("color_to_monochrome") && film.scenarioType.includes("4_3"));
  assert.ok(film.scenarioType.includes("32mm") && film.scenarioType.includes("six_month_prep") && film.scenarioType.includes("30_day_recce"));
  assert.ok(film.premise.includes("BFI anchors a 90-minute") && film.premise.includes("88m25s") && film.premise.includes("Cannes record lists 84 minutes"));
  assert.ok(film.premise.includes("Polish/French/UK co-production") && film.premise.includes("Polish Film Institute") && film.premise.includes("Film4") && film.premise.includes("BFI National Lottery"));
  assert.ok(film.premise.includes("roughly 150 versions") && film.premise.includes("music functioning as a third character"));
  assert.ok(film.premise.includes("six months of preparation") && film.premise.includes("about thirty recce days") && film.premise.includes("January-to-August 2017"));
  assert.ok(film.premise.includes("weather") && film.premise.includes("folk-ensemble breaks"));
  assert.ok(film.premise.includes("Poland, Croatia and Paris") && film.premise.includes("Paris interiors recreated in Poland"));
  assert.ok(film.premise.includes("35mm look") && film.premise.includes("ARRI Alexa XT") && film.premise.includes("desaturated in post"));
  assert.ok(film.premise.includes("ARRIRAW 3.4K Open Gate") && film.premise.includes("Codex XR") && film.premise.includes("DI Factory"));
  assert.ok(film.premise.includes("ARRI/Zeiss Ultra Primes") && film.premise.includes("32mm preference") && film.premise.includes("Angénieux Optimo"));
  assert.ok(film.premise.includes("Poland scenes favor wider 28/32/40mm") && film.premise.includes("Paris tends toward longer 50/65mm"));
  assert.ok(film.premise.includes("mostly single-camera") && film.premise.includes("two cameras for Mazurek Ensemble"));
  assert.ok(film.premise.includes("about 70 percent") && film.premise.includes("generated in post"));
  assert.ok(film.premise.includes("Maciej Pawłowski") && film.premise.includes("Mirosław Makowski"));
  assert.ok(film.premise.includes("exact total budget") && film.premise.includes("complete financing shares") && film.premise.includes("full lens-by-shot map"));
  assert.ok(film.premise.includes("exact LUT transforms") && film.premise.includes("production-sound hardware") && film.premise.includes("final mix topology"));
  assert.ok(film.requiredChoicesSeed.screenplay.includes("elliptical_anti_biopic") && film.requiredChoicesSeed.screenplay.includes("moving_script"));
  assert.ok(film.requiredChoicesSeed.camera.includes("alexa_xt") && film.requiredChoicesSeed.camera.includes("arriraw_3_4k_opengate"));
  assert.ok(film.requiredChoicesSeed.camera.includes("32mm_majority") && film.requiredChoicesSeed.camera.includes("poland_paris_lens_shift"));
  assert.ok(film.requiredChoicesSeed.editing.includes("jaroslaw_kaminski") && film.requiredChoicesSeed.editing.includes("black_screen_timing"));
  assert.ok(film.requiredChoicesSeed.sound.includes("selective_sound_world") && film.requiredChoicesSeed.sound.includes("final_mix_hardware_unknown"));
  assert.ok(film.learningGoals.some((goal) => goal.includes("90-minute") && goal.includes("88m25s") && goal.includes("84-minute")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Polish/French/UK co-production") && goal.includes("financing percentages")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("roughly 150 versions") && goal.includes("immutable shooting script")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("music as a third character") && goal.includes("historical period")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("six months of prep") && goal.includes("thirty recce days")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("January-to-August 2017") && goal.includes("weather") && goal.includes("folk-ensemble availability")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Paris interiors") && goal.includes("recreated in Poland")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("35mm-versus-Alexa tests") && goal.includes("photochemical reference")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("ARRI Alexa XT") && goal.includes("ARRIRAW 3.4K Open Gate")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("shot in color") && goal.includes("monitored in black-and-white") && goal.includes("desaturated in post")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("DI Factory") && goal.includes("grading software")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Academy/4:3 frame") && goal.includes("portrait/double-portrait")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("32mm") && goal.includes("majority focal length")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("28/32/40mm") && goal.includes("Polish image strategy")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("50/65mm") && goal.includes("Paris strategy")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("two day/night LUTs") && goal.includes("LUT math")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("most of the film used one camera") && goal.includes("Mazurek")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("East/West Berlin") && goal.includes("70-percent-generated-in-post")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Jarosław Kamiński") && goal.includes("black-screen duration")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Maciej Pawłowski") && goal.includes("Mirosław Makowski")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("uncertainty register") && goal.includes("music-rights fees")));
  assert.ok(film.phases.find((phase) => phase.id === "runtime_versions")?.player_task.includes("90 minutes"));
  assert.ok(film.phases.find((phase) => phase.id === "coproduction_map")?.player_task.includes("financing shares"));
  assert.ok(film.phases.find((phase) => phase.id === "prep_lock")?.player_task.includes("six months"));
  assert.ok(film.phases.find((phase) => phase.id === "recce_lock")?.player_task.includes("thirty recce days"));
  assert.ok(film.phases.find((phase) => phase.id === "camera_capture")?.player_task.includes("ARRIRAW 3.4K Open Gate"));
  assert.ok(film.phases.find((phase) => phase.id === "monochrome_pipeline")?.player_task.includes("color capture"));
  assert.ok(film.phases.find((phase) => phase.id === "prime_strategy")?.player_task.includes("32mm"));
  assert.ok(film.phases.find((phase) => phase.id === "paris_lens_shift")?.player_task.includes("50/65mm"));
  assert.ok(film.phases.find((phase) => phase.id === "berlin_vfx")?.player_task.includes("70-percent"));
  assert.ok(film.phases.find((phase) => phase.id === "black_screen_timing")?.player_task.includes("cinema screen"));
  assert.ok(film.phases.find((phase) => phase.id === "uncertainty_register")?.player_task.includes("music fees"));
  assert.ok(film.learningGoals.length >= 60);
  assert.ok(film.phases.length >= 35);
});