import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterEighteenUnknownPleasuresExpansionDefinitions = [
  {
    id: "scenario_unknown_pleasures_2002",
    title: "Unknown Pleasures",
    originalTitle: "Ren xiao yao",
    year: 2002,
    titleType: "Movie",
    runtimeMins: 113,
    directors: ["Jia Zhangke"],
    genres: ["Drama"],
    sourceId: "cannes_unknown_pleasures_2002",
    sourceUrl: "https://www.festival-cannes.com/en/f/ren-xiao-yao/",
    scenarioType: "china_japan_france_south_korea_dv_datong_public_space_long_take_digital_color_celluloid_transfer_independent_production_2002",
    premise: "Build Unknown Pleasures as Chapter 18's next P1 production case about early-2000s digital-video authorship, fast low-footprint production, public-space observation, long-take performance, image-texture design, color work and transfer to celluloid. Festival de Cannes records Ren Xiao Yao / Unknown Pleasures as a 2002 Japan/France/South Korea/China production running 113 minutes, directed and written by Jia Zhangke, photographed by Lik Wai Yu, edited by Keung Chow and designed by Jiang Dong Liang. The case treats those institutional credits as the release-and-authorship baseline rather than inferring a complete financing ledger from country labels. Jia's later account of the film's digital turn establishes that DV was not chosen only because it was inexpensive: after the commissioned digital short In Public, he and Yu Lik-wai explored the medium's own visual character, its ability to work close to actors, to remain less obtrusive in public spaces and to capture unexpected events. Senses of Cinema records Jia's statement that Unknown Pleasures was shot in only nineteen days under tight finances, a schedule that made the production system itself part of the film's historical significance. BFI's early-digital history further documents the low social status of digital video in China at the time and Jia's decision to treat that supposedly amateur format as a creative tool. The image strategy must remain precise rather than romanticized. Jia later described Yu Lik-wai modifying the digital camera's resolution because an overly clean image felt artificial, and he repeatedly emphasized searching for a specifically digital texture instead of imitating celluloid. The same source tradition also records limits: digital video handled bright exteriors poorly enough that the filmmakers reduced some exterior work, so DV flexibility did not erase exposure, color, dynamic-range or texture problems. Public-space access is likewise a production affordance, not proof that every scene was documentary or unscripted. The UCLA open monograph reproduces Jia's account that Unknown Pleasures underwent digital color adjustment, was then transferred to celluloid, and received further color manipulation during development, including a cold-toned photographic treatment. That sequence must be taught as a hybrid digital-origin/photochemical finishing path: digital acquisition and digital color work first, then film transfer and further photochemical adjustment. Current 35mm archival exhibition records confirm that a celluloid exhibition object exists, but they do not by themselves establish the exact original film-out hardware, stock, lab or printing chain, so those details remain unknown unless separately sourced. The film's long takes, fixed or tracking observation, sparse coverage and ambient public-space texture create editorial and performance consequences: Chow Keung's editing must shape duration and transitions without being reduced to a claim that digital video simply eliminates editing. Liang Jingdong's production design must be kept distinct from the real Datong locations; the film can use found industrial and urban environments while still making authored choices about objects, signage, costumes, interiors and performance zones. Sound is treated conservatively: the current high-confidence source set establishes songs, karaoke, broadcast-media presence and public-space ambience at the level of the finished film, but does not securely establish microphones, recorders, ADR, Foley or final-mix procedures, so the production exercise must leave those equipment and workflow details unknown. The player should be able to trace one Datong public-space scene from location access, script/performance intention and unobtrusive DV camera placement through long-take blocking, available-light risk, texture/resolution decisions, ambient-media capture boundaries, editorial duration, digital color adjustment, transfer to celluloid and final photochemical color refinement while separating documented craft facts from interpretation, restoration or later critical reception.",
    requiredChoicesSeed: {
      screenplay: ["datong_present_tense", "youth_drift_structure", "public_space_scene_map", "pop_media_integration", "script_improvisation_boundary"],
      camera: ["digital_video_origin", "small_camera_public_space", "long_take_blocking", "resolution_texture_choice", "bright_exterior_limit", "available_light_boundary", "celluloid_transfer_boundary"],
      editing: ["duration_rhythm", "sparse_coverage", "public_space_continuity", "unexpected_event_selection", "digital_color_handoff", "film_transfer_handoff"],
      sound: ["public_space_ambience", "karaoke_broadcast_boundary", "music_dialogue_separation", "unknown_microphone_boundary", "unknown_adr_foley_boundary", "final_mix_unknowns"],
      themes: ["film_history", "2002", "unknown_pleasures", "ren_xiao_yao", "jia_zhangke", "yu_lik_wai", "chow_keung", "liang_jingdong", "datong", "digital_video", "dv", "public_space", "long_take", "small_crew", "nineteen_day_shoot", "in_public", "available_light", "bright_exterior_limit", "digital_texture", "resolution_modification", "digital_color", "celluloid_transfer", "photochemical_color_adjustment", "china", "japan", "france", "south_korea", "113_minutes"],
    },
    learningGoals: [
      "Explain Unknown Pleasures as an early-2000s digital-video production system rather than a generic low-budget aesthetic.",
      "Identify Jia Zhangke as director and screenwriter from the Cannes record.",
      "Identify Yu Lik-wai as cinematographer, Chow Keung as editor and Liang Jingdong as production designer from the Cannes record.",
      "Preserve the Cannes 2002, 113-minute and Japan/France/South Korea/China metadata without converting country labels into invented financing shares.",
      "Explain how In Public functioned as a practical and aesthetic precursor to Unknown Pleasures' digital production.",
      "Record the nineteen-day shoot as documented production chronology rather than an abstract symbol of speed.",
      "Explain why Jia rejected the idea that DV mattered only because it was cheaper than film.",
      "Explain how a small digital camera could reduce social visibility in public spaces and change the behavior of people around the camera.",
      "Distinguish unobtrusive observation from documentary status: a fiction scene can use real public space without becoming unscripted nonfiction.",
      "Explain how DV proximity could change actor-camera intimacy and performance scale.",
      "Explain how DV mobility made unexpected environmental events easier to incorporate when they aligned with the scene.",
      "Use Jia's highway/thunderstorm example as a title-specific case of production flexibility rather than a universal digital rule.",
      "Explain why digital flexibility did not remove exposure, color or highlight limitations.",
      "Record that bright exterior limitations were problematic enough to reduce some exterior work.",
      "Explain why Yu Lik-wai and Jia treated digital texture as an authored image property rather than an error to hide.",
      "Record Jia's later account that an overly clean digital image could feel artificial for this project.",
      "Explain resolution modification as a deliberate texture decision without inventing undocumented numeric settings.",
      "Distinguish digital resolution, compression, exposure and color response as separate image variables.",
      "Explain how long takes shift pressure toward blocking, performance duration, camera timing and location control.",
      "Explain how sparse coverage increases the consequence of camera placement and actor movement.",
      "Explain why long takes do not eliminate editing: Chow Keung still shapes sequence order, duration, transitions and narrative rhythm.",
      "Separate public-space continuity from studio continuity, including uncontrolled pedestrians, traffic, signage and changing light.",
      "Explain how Liang Jingdong's production design can operate within found Datong locations rather than requiring fully constructed sets.",
      "Distinguish found environment, placed object, costume, signage and actor blocking as separate production-design layers.",
      "Explain how pop songs, karaoke, television and advertising can function as diegetic media without proving any particular production-sound setup.",
      "Keep microphones, recorders, radio systems, ADR, Foley and final-mix procedures unknown unless a source establishes them.",
      "Separate finished-film sound analysis from production-sound evidence.",
      "Explain the documented digital color-adjustment stage as post-production work on a digital-origin image.",
      "Explain the subsequent transfer to celluloid as a distinct finishing stage rather than proof that principal photography was on film.",
      "Explain the additional color manipulation during film development as a separate photochemical decision after digital grading.",
      "Preserve Jia's cold-color treatment account without pretending it specifies every lab parameter or print stock.",
      "Distinguish original production finishing from later archival exhibition and restoration formats.",
      "Use current 35mm screening records only to establish the existence of a celluloid exhibition element, not the exact original film-out hardware.",
      "Explain why the film belongs beside 28 Days Later and Russian Ark in digital-convergence history while keeping their camera systems and production ambitions distinct.",
      "Compare Unknown Pleasures with Yi Yi: both use sustained duration and urban space, but their capture formats and production histories differ sharply.",
      "Compare Unknown Pleasures with Inland Empire: both value rough digital texture, but their industrial contexts, camera practices and narrative structures are not interchangeable.",
      "Explain how the film's production model relates to Jia's position outside China's mainstream studio system without reducing every creative choice to censorship evasion.",
      "Separate the film's social themes from technical evidence about how the image and sound were produced.",
      "Separate contemporary production testimony from later critical labels such as Sixth Generation, realism or digital revolution.",
      "Reject claims that Unknown Pleasures invented digital feature production, guerrilla filmmaking, long takes, public-space shooting or digital-to-film transfer.",
      "Reject the inference that a small camera automatically means a one-person crew, no lighting, no permissions or no post-production.",
      "Audit every claim about budget, camera model, lens, frame rate, sound equipment, film-out device, lab, stock and release print independently from what the cited sources actually establish.",
    ],
    phases: [
      { id: "evidence_map", label: "Map the evidence hierarchy", player_task: "Separate Cannes institutional credits, Jia interviews, BFI digital-history reporting, the UCLA monograph and later exhibition records before turning any statement into production fact." },
      { id: "release_record", label: "Lock the release record", player_task: "Record 2002, 113 minutes, Jia Zhangke and the Cannes country set without treating the metadata as a complete financing ledger." },
      { id: "crew_map", label: "Map the core authorship", player_task: "Keep Jia Zhangke, Yu Lik-wai, Chow Keung and Liang Jingdong in their documented roles before assigning production decisions." },
      { id: "in_public_precursor", label: "Trace the digital precursor", player_task: "Use In Public to explain why Datong, digital video and public-space observation became linked without pretending the feature was simply an expanded documentary short." },
      { id: "nineteen_day_schedule", label: "Budget nineteen days", player_task: "Build a shoot plan around the documented nineteen-day schedule and show what must be simplified, prioritized or left flexible." },
      { id: "dv_intent", label: "Define the DV intent", player_task: "Write an image brief that treats digital video as its own medium rather than a cheap imitation of 35mm." },
      { id: "public_space_access", label: "Plan public-space access", player_task: "Choose camera footprint, crew positions and actor zones so the production can work in active Datong spaces without assuming legal or logistical constraints disappear." },
      { id: "camera_social_visibility", label: "Manage camera visibility", player_task: "Test how a small camera changes bystander behavior and protect the boundary between unobtrusive fiction production and documentary capture." },
      { id: "actor_proximity", label: "Set actor-camera proximity", player_task: "Use the reduced camera footprint to work close to performers while preserving eyelines, focus, blocking and emotional distance." },
      { id: "long_take_blocking", label: "Block the long take", player_task: "Rehearse actor movement, camera timing and background activity for sustained duration before relying on coverage." },
      { id: "sparse_coverage", label: "Protect sparse coverage", player_task: "Identify which dramatic beats require alternate angles and which can safely live inside one sustained setup." },
      { id: "unexpected_event_rule", label: "Define spontaneity rules", player_task: "Set a rule for when an unexpected event may enter the scene because it supports the dramatic intention rather than merely because DV can keep recording." },
      { id: "weather_opportunity", label: "Capture environmental opportunity", player_task: "Use the documented storm example to model rapid response while keeping safety, continuity and story intention ahead of novelty." },
      { id: "bright_exterior_limit", label: "Stress-test bright exteriors", player_task: "Identify exterior conditions where the digital image fails the desired color or contrast and choose to reframe, reschedule or reduce the scene instead of pretending the camera has unlimited latitude." },
      { id: "available_light_boundary", label: "Audit available light", player_task: "Separate what the source establishes about small-camera flexibility from any unsupported claim that the production used no lighting equipment." },
      { id: "resolution_texture", label: "Shape digital texture", player_task: "Treat resolution as an authored texture variable while leaving undocumented numeric settings unknown." },
      { id: "color_response", label: "Map color response", player_task: "Track where digital color characteristics support the film and where they create problems that must move into post-production." },
      { id: "production_design_found_space", label: "Design within found space", player_task: "Separate Liang Jingdong's authored objects, signage and performance zones from the existing industrial and urban architecture of Datong." },
      { id: "pop_media_props", label: "Place media culture", player_task: "Coordinate televisions, karaoke, advertising and popular music as visible or audible story objects without confusing representation analysis with technical sound evidence." },
      { id: "ambient_sound_boundary", label: "Map ambient sound cautiously", player_task: "Mark desired public-space ambience while leaving microphone, recorder and track-count choices unknown unless separately documented." },
      { id: "music_dialogue_boundary", label: "Separate media and dialogue", player_task: "Plan how songs, television, karaoke and dialogue coexist without inventing ADR, playback or final-mix procedures." },
      { id: "editorial_duration", label: "Edit duration", player_task: "Give Chow Keung explicit responsibility for shot duration, sequence order and transitions even when individual scenes use long takes." },
      { id: "continuity_public_space", label: "Audit uncontrolled continuity", player_task: "Track pedestrians, vehicles, light, signage and background activity across takes so public-space realism does not create accidental continuity failures." },
      { id: "digital_color_pass", label: "Run the digital color pass", player_task: "Adjust the digital-origin image for the intended texture and palette before any transfer to celluloid." },
      { id: "celluloid_transfer", label: "Protect the transfer boundary", player_task: "Treat transfer to film as a later finishing step and reject any wording that rewrites principal photography as photochemical." },
      { id: "photochemical_color_pass", label: "Refine color on film", player_task: "Model Jia's documented second color-adjustment stage during development while leaving unsourced lab hardware and stock details unspecified." },
      { id: "cold_tone_audit", label: "Audit the cold-tone treatment", player_task: "Use Jia's account of a colder photographic treatment as a title-specific finishing choice, not a generic recipe for digital cinema." },
      { id: "exhibition_object_boundary", label: "Separate later exhibition", player_task: "Use archival 35mm screening records to confirm a celluloid exhibition object without turning later holdings into proof of every original finishing detail." },
      { id: "comparison_audit", label: "Compare digital systems", player_task: "Compare Unknown Pleasures with Russian Ark, 28 Days Later, Yi Yi and Inland Empire through concrete capture, access, duration and post-production constraints rather than one analog-versus-digital binary." },
      { id: "industrial_context", label: "Map independent production context", player_task: "Place the film outside mainstream Chinese studio production while keeping censorship, financing, distribution and aesthetics as related but distinct questions." },
      { id: "novelty_audit", label: "Audit novelty claims", player_task: "Reject unsourced first-ever claims about DV, long takes, guerrilla access, public-space fiction or digital-to-film finishing." },
      { id: "unknowns_register", label: "Register technical unknowns", player_task: "Keep camera model, lenses, exact frame rate, sound equipment, film-out hardware, lab, stock and print chain unknown unless a source explicitly establishes them." },
    ],
  },
] as const;

export function mergeChapterEighteenUnknownPleasuresExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterEighteenUnknownPleasuresExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, "Ren Xiao Yao"].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_eighteen_unknown_pleasures_verified",
      source: { list_id: "manual_chapter_eighteen_unknown_pleasures_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
