import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterNineteenDunePartTwoExpansionDefinitions = [
  {
    id: "scenario_dune_part_two_2024",
    title: "Dune: Part Two",
    originalTitle: "Dune: Part Two",
    aliases: ["Dune Part Two", "Dune 2", "Dune: Part 2"],
    year: 2024,
    titleType: "Movie",
    runtimeMins: 167,
    directors: ["Denis Villeneuve"],
    genres: ["Science Fiction", "Adventure", "Drama", "Action"],
    sourceId: "asc_dune_part_two_2025",
    sourceUrl: "https://theasc.com/article/expanding-view-dune-part-two/",
    scenarioType: "award_priority_oscar_sound_visual_effects_bafta_sound_special_visual_effects_denis_villeneuve_greig_fraser_patrice_vermette_jacqueline_west_joe_walker_hans_zimmer_richard_king_gareth_john_paul_lambert_gerd_nefzer_alexa_65_alexa_lf_mini_lf_imax_143_190_239_moviecam_ironglass_optica_elite_infrared_87c_giedi_prime_unreal_camera_planning_digital_capture_35mm_film_out_scan_back_budapest_jordan_abu_dhabi_brion_tomb_practical_plate_first_worm_gimbal_spice_crawler_sound_field_recording_2024",
    premise: "Build Dune: Part Two as Chapter 19's next award-priority production case because the Academy records 2025 wins for Sound and Visual Effects, while BAFTA records wins for Sound and Special Visual Effects. Those awards establish priority and reception, not production workflow. BBFC records the UK 2D cinema, ScreenX and 2D IMAX versions at 166 minutes 45 seconds, so the playable record rounds the cinema master to 167 minutes. BBFC separately records a physical-media/VOD version at 165 minutes 35 seconds; the locked case therefore preserves version provenance rather than claiming every cinema, IMAX, ScreenX, streaming and physical-media master is frame-identical. Production designer Patrice Vermette's direct interview provides a bounded schedule: three months of soft prep from November 2021 through January 2022, Budapest pre-production from February through July 2022, shooting continuing until December 2022, and some production-design post work from January through May 2023. This is a department-level production chronology, not a complete call-sheet or payroll ledger. Vermette also records Budapest as the production base, with work in Jordan and Abu Dhabi plus the Brion cemetery in Italy for the Emperor's world; the sequel deliberately used different locations and all-new sets rather than simply recycling Part One geography. American Cinematographer documents Greig Fraser's decision to shoot Part Two entirely for IMAX 1.43:1 while protecting 1.90:1 for digital IMAX and 2.39:1 for traditional theatrical/home presentation. The main camera was the ARRI Rental ALEXA 65, supplemented by ALEXA LF and Mini LF bodies. Fraser's lens strategy was deliberately plural rather than one package: ARRI Rental Moviecam lenses, his Optica Elite primes and IronGlass rehoused Soviet-era optics were selected according to sequence and story needs, with Moviecams favored for the sandworm ride and arena/infrared work and softer IronGlass/Optica Elite choices used more often for desert/Paul material. Fraser separately states that Part Two did not use anamorphic lenses as its primary language, unlike portions of Part One. Giedi Prime required a production-wide infrared commitment rather than a monochrome grade alone. ASC records ALEXA LF and Mini LF bodies with the IR-cut filter removed and an 87C filter blocking visible light so the sensor recorded infrared; the resulting image was further desaturated in post. Jacqueline West's direct costume interview shows why this was cross-departmental: fabrics that appeared black to the eye could photograph white in IR, forcing camera tests and material changes. The case therefore treats IR photography, costume response, VFX/DI transition and final monochrome presentation as linked but distinct production problems. ASC also documents a camera-department Unreal Engine workflow. Virtual-cinematography technician Tamás Papp used drone scouting and location photography to build precise 3D environments so Fraser's department could study sun position, camera movement, lighting and location geometry before shooting. This is locked as camera/previsualization and technical-record evidence; it does not prove that Unreal Engine was the final renderer for the film's VFX. Fraser's direct Filmmaker interview confirms that Part Two repeated the first film's film-out/scan-back process: digitally captured material was output to film and rescanned into the digital workflow, while the sequel also had a 15-perf 70mm film output version. FotoKem independently lists Dune: Part Two among projects using its SHIFT analog-intermediate process, and British Cinematographer records the production working with FotoKem to transfer to 35mm negative and scan back on a Scanity scanner. The locked case therefore distinguishes digital acquisition, analog intermediate texture and final film exhibition; it does not infer that every digital and 70mm delivery passed through an identical intermediate path. Production design remained physical and globally distributed. Vermette's interviews document Budapest, Jordan, Abu Dhabi and Italy; the Art Directors Guild records the Arrakeen Residency War Room as built on Stage 6 at Origo Studios in Budapest. These anchors prove substantial built-environment work without converting every visible environment into a practical set. VFX supervisor Paul Lambert explicitly describes the opposite simplification as equally wrong: the production aimed to begin from photographed plates and practical references whenever possible, then augment them. For the sandworm ride, the art department and special-effects team built a physical section of worm on a gimbal that could change angle and orientation toward the sun, while a dedicated worm unit worked under strict sunlight conditions. Lambert records a month in Jordan and another month in the UAE for expanded desert production relative to Part One. For spice-crawler action in the UAE, the production built roads and concrete plates in the desert to support cranes and tractors; individual crawler legs could be represented by tractors carrying art-department legs to create physically correct moving shadows around performers. DNEG identifies itself as the lead VFX partner, but the locked evidence does not assign every VFX shot or task to DNEG or claim that photographed plates eliminated fully digital work. The practical/digital rule is therefore sequence-specific: plates, gimbals, tractors, built elements, stunts, sunlight and CG were coordinated to preserve believable light and scale. Sound follows the same physical-reference logic. Supervising sound editor/sound designer Richard King documents extensive field recording of different sands, machinery and wind, including microphones buried in sand and large objects dragged across or through it. For sandworms, King deliberately emphasized interaction with the environment, mass, grit and wind rather than relying on creature vocalization as the dominant design. He also states that ornithopters, thumpers and shield sounds were rebuilt or adapted from elements developed for Part One rather than simply lifted unchanged. The Oscar/BAFTA-winning sound team includes Gareth John, Richard King, Ron Bartlett and Doug Hemphill, but awards credits do not by themselves establish each person's complete production/post task ledger. Editor Joe Walker describes managing a large ensemble and using the release delay associated with industry labor strikes to continue refining storylines; he also emphasizes dense collaboration with sound and Hans Zimmer. The locked case treats the strike-delayed release as a Chapter 19 institutional context, not as proof of a specific edit decision. Zimmer's direct interview documents a score designed away from conventional European-orchestra assumptions, including purpose-built instruments and Loire Cotler's voice as a through-line; he continued writing after Part One rather than starting Part Two from a blank musical slate. Score development remains distinct from production sound, sound editorial and final re-recording. The historical lesson is not simply that Dune: Part Two was an IMAX blockbuster with Oscar-winning effects. It is that a 2020s studio feature coordinated all-new international locations and sets, large-format digital acquisition protected for several aspect ratios, sequence-specific vintage optics, irreversible infrared capture, camera-department Unreal planning, an analog film-out/scan-back intermediate, practical desert engineering, plate-first VFX logic, distributed digital effects, material-sensitive costumes, field-recorded sound, long-form editorial refinement and purpose-built music while keeping exhibition versions and production layers distinct. The locked evidence does not establish a complete production budget or financing/ownership/recoupment waterfall, exact full principal-photography day count, every unit/call sheet/weather delay, complete crew/payroll/safety ledger, every camera serial/lens/filter/ND/exposure/shot assignment, all Unreal scenes/assets/versioning, every infrared test and DI matte, complete film-out stock/recorder/scanner/LUT/grade settings, every set/prop/location build, all stunt/SFX mechanisms, complete VFX shot/vendor/task allocation, every production-sound track and ADR/Foley/effects/mix stem, full edit project/version history, complete score session/orchestration/musician ledger, or every IMAX/70mm/DCP/HDR/SDR/VOD/streaming/physical-media/territory delivery master. Those remain explicit unresolved boundaries.",
    requiredChoicesSeed: {
      screenplay: ["award_priority_not_workflow_evidence", "bbfc_166m45_cinema_runtime", "version_provenance_boundary", "strike_delay_context_not_edit_proof", "budget_finance_unresolved"],
      camera: ["alexa_65_main_camera", "alexa_lf_mini_lf_support", "imax_143_protect_190_239", "moviecam_ironglass_optica_elite", "infrared_87c_giedi_prime", "unreal_camera_planning_only", "digital_to_35mm_film_out_scan_back", "full_camera_di_ledger_unresolved"],
      editing: ["joe_walker_ensemble_structure", "release_delay_refinement_context", "sound_music_picture_collaboration", "multi_format_version_boundary", "full_edit_revision_ledger_unresolved"],
      sound: ["richard_king_sand_field_recording", "sandworm_environment_mass_not_roar", "rebuilt_ornithopter_thumper_shield_elements", "zimmer_custom_instrument_score", "full_production_sound_adr_mix_music_ledgers_unresolved"],
      themes: ["film_history", "2024", "dune_part_two", "large_format_digital", "imax", "infrared", "analog_intermediate", "practical_vfx_integration", "chapter19"]
    },
    learningGoals: [
      "Explain why the 2025 Sound and Visual Effects Oscars justify award-priority selection without proving workflow.",
      "Use BAFTA's Sound and Special Visual Effects wins as reception evidence rather than a production-method source.",
      "Identify Denis Villeneuve as director and keep award evidence separate from direct craft evidence.",
      "Use BBFC's 166m45s cinema record to round the playable runtime to 167 minutes.",
      "Keep BBFC's 165m35s physical-media/VOD version separate from the cinema master.",
      "Reject the claim that every 2D, IMAX, ScreenX, VOD and physical-media version is frame-identical.",
      "Use Vermette's November 2021-January 2022 soft-prep period as a bounded production-design chronology.",
      "Use February-July 2022 as the documented Budapest pre-production window from Vermette's direct account.",
      "Use shooting through December 2022 as a bounded schedule anchor without inventing an exact day count.",
      "Keep January-May 2023 as Vermette's department-level post involvement rather than a whole-film post calendar.",
      "Identify Budapest as the production base and Jordan, Abu Dhabi and Italy as documented production geographies.",
      "Explain why new locations and all-new sets were used to avoid visual repetition from Part One.",
      "Identify the Brion cemetery in Italy as a documented location for the Emperor's world.",
      "Identify the Arrakeen Residency War Room as a documented Stage 6 Origo Studios build.",
      "Avoid converting every visible environment into a claim of full practical construction.",
      "Identify Greig Fraser as cinematographer.",
      "Explain the decision to shoot Part Two entirely for IMAX 1.43:1.",
      "Keep 1.90:1 digital IMAX and 2.39:1 traditional/home protection as distinct framing requirements.",
      "Identify ARRI Rental ALEXA 65 as the main camera.",
      "Identify ALEXA LF and Mini LF as supplementary bodies rather than replacing the ALEXA 65 claim.",
      "Identify ARRI Rental Moviecam lenses as a documented lens family.",
      "Identify IronGlass rehoused Soviet-era lenses as another documented lens family.",
      "Identify Optica Elite primes as a documented softer/character lens option.",
      "Explain why lens choice varied by sequence and story need rather than one universal package.",
      "Associate Moviecam optics with the worm ride and arena/IR work without turning that into a per-shot lens ledger.",
      "Associate IronGlass and Optica Elite more strongly with desert/Paul material without claiming exclusivity.",
      "Explain Fraser's statement that Part Two did not rely on anamorphic lenses as its primary language.",
      "Identify Giedi Prime's monochrome look as originating in infrared capture rather than grading alone.",
      "Explain removal of the IR-cut filter and use of an 87C filter as documented capture choices.",
      "Explain why the IR image was further desaturated in post without erasing the in-camera commitment.",
      "Explain why infrared response forced Jacqueline West's costume team to camera-test fabrics.",
      "Recognize that two visually black fabrics can photograph differently under infrared capture.",
      "Keep full costume-fabric test and continuity ledgers unresolved.",
      "Identify Tamás Papp as the virtual-cinematography technician documented by ASC.",
      "Explain how drone scans/photos fed precise 3D location environments for camera planning.",
      "Use Unreal Engine as a camera/previsualization and lighting-planning tool in the locked evidence.",
      "Reject the unsupported inference that Unreal Engine was the film's universal final VFX renderer.",
      "Explain how sun-position studies can reduce location uncertainty without proving a quantified cost saving.",
      "Explain why technical set/location records support reshoots, pickups and continuity planning.",
      "Identify the repeated digital-capture to film-out to scan-back process as an analog-intermediate workflow.",
      "Keep digital acquisition distinct from the analog intermediate used for texture.",
      "Use FotoKem SHIFT as supporting evidence for analog intermediate practice on Dune: Part Two.",
      "Identify 35mm negative and Scanity scan-back as documented elements without inventing every laboratory setting.",
      "Keep the 15-perf 70mm film output as a separate exhibition/delivery branch.",
      "Reject the claim that every digital and film presentation passed through an identical chain.",
      "Identify Patrice Vermette as production designer and Gerd Nefzer as special-effects supervisor.",
      "Identify Paul Lambert as production VFX supervisor.",
      "Explain Lambert's plate-first comparison rule as a realism/reference strategy rather than a no-CG policy.",
      "Describe the physical worm section on a gimbal as one sandworm-riding production component.",
      "Explain how orienting the gimbal toward the sun linked practical performance to downstream VFX lighting.",
      "Identify the dedicated worm unit and sunlight dependency as documented production constraints.",
      "Use Lambert's month in Jordan and month in the UAE as bounded desert-unit anchors.",
      "Explain why roads and concrete plates were built in the UAE for cranes and tractors.",
      "Explain the tractor-plus-art-department-leg method for creating moving spice-crawler shadows around performers.",
      "Keep photographed practical elements distinct from digital crawler/environment completion.",
      "Identify DNEG as lead VFX partner without assigning every VFX shot or vendor task to DNEG.",
      "Reject the claim that plate-first methodology means there were no fully digital shots.",
      "Identify Richard King as supervising sound editor/sound designer.",
      "Explain why multiple kinds and textures of sand required differentiated field recordings.",
      "Describe buried microphones and large objects dragged through sand as documented sound-acquisition methods.",
      "Explain the sandworm design emphasis on environmental interaction, mass, grit and wind rather than creature roar.",
      "Explain why ornithopter, thumper and shield elements were rebuilt/adapted instead of simply reused unchanged.",
      "Name Gareth John, Richard King, Ron Bartlett and Doug Hemphill as the Oscar/BAFTA-winning sound team without inventing a full task ledger.",
      "Identify Joe Walker as editor and distinguish editorial evidence from release-history evidence.",
      "Use the labor-strike release delay as Chapter 19 institutional context, not proof of a particular cut.",
      "Explain Walker's emphasis on dense picture/sound/music collaboration for theatrical scale.",
      "Identify Hans Zimmer as composer.",
      "Explain Zimmer's effort to avoid conventional orchestral assumptions through purpose-built instruments.",
      "Identify Loire Cotler's voice as a documented musical through-line.",
      "Explain Zimmer's continued writing after Part One as continuity of musical development rather than simple score reuse.",
      "Keep score development distinct from production sound, sound editorial and re-recording.",
      "Keep the exact production budget, financing, ownership, participation and recoupment waterfall unresolved.",
      "Keep exact principal-photography day count, call sheets, unit schedules, weather and payroll unresolved.",
      "Keep every camera serial, lens/filter/exposure assignment and infrared test unresolved.",
      "Keep complete Unreal scenes/assets, film-out settings, LUTs, scans and DI revisions unresolved.",
      "Keep every set, prop, SFX mechanism, stunt setup, VFX shot and vendor allocation unresolved.",
      "Keep every production-sound track, ADR line, Foley cue, sound effect, premix and final stem unresolved.",
      "Keep the full edit project/version history and score-session/orchestration ledger unresolved.",
      "Keep every IMAX, 70mm, DCP, HDR, SDR, VOD, streaming, physical-media and territory delivery master unresolved.",
      "Close the case only when awards, runtime provenance, schedule, locations/sets, camera/format, IR, Unreal planning, analog intermediate, practical/VFX integration, sound, edit, music and unresolved boundaries agree."
    ],
    phases: [
      { id: "award_priority", label: "Lock award priority", player_task: "Use Oscar and BAFTA results to prioritize Dune: Part Two without treating awards as workflow evidence." },
      { id: "runtime_boundary", label: "Freeze cinema runtime", player_task: "Use BBFC's 166m45s cinema version for the playable record while preserving the shorter home version." },
      { id: "version_provenance", label: "Separate release masters", player_task: "Keep cinema, IMAX, ScreenX, VOD and physical-media version evidence distinct." },
      { id: "soft_prep", label: "Map soft prep", player_task: "Anchor Vermette's November 2021-January 2022 soft-prep period without turning it into a full production calendar." },
      { id: "preproduction", label: "Map Budapest pre-production", player_task: "Use the February-July 2022 production-design pre-production window." },
      { id: "shoot_window", label: "Bound principal photography", player_task: "Use shooting through December 2022 without inventing a complete day count." },
      { id: "post_window", label: "Bound design post", player_task: "Keep Vermette's January-May 2023 post involvement department-specific." },
      { id: "production_geography", label: "Map production geography", player_task: "Coordinate Budapest, Jordan, Abu Dhabi and Italy as distinct production environments." },
      { id: "new_sets", label: "Avoid Part One repetition", player_task: "Treat the sequel's all-new sets and different locations as deliberate production design." },
      { id: "brion_location", label: "Use Brion cemetery", player_task: "Integrate the Carlo Scarpa location into the Emperor-world design without claiming it represents every Kaitain set." },
      { id: "origo_build", label: "Build the war room", player_task: "Use the Stage 6 Origo Studios war-room build as a bounded physical-set anchor." },
      { id: "imax_frame", label: "Compose for IMAX", player_task: "Use 1.43:1 as the primary tall-frame production target while protecting 1.90 and 2.39." },
      { id: "camera_package", label: "Choose large-format digital bodies", player_task: "Use ALEXA 65 with LF/Mini LF support rather than collapsing the package to one sensor." },
      { id: "lens_palette", label: "Build a sequence-specific lens palette", player_task: "Use Moviecam, IronGlass and Optica Elite optics according to story/sequence needs." },
      { id: "infrared_capture", label: "Commit to infrared", player_task: "Remove IR filtering and use 87C filtration for Giedi Prime rather than simulating the look only in post." },
      { id: "infrared_costume_tests", label: "Test materials in IR", player_task: "Camera-test fabrics and change materials when infrared response breaks intended costume values." },
      { id: "infrared_post", label: "Finish the IR transition", player_task: "Coordinate captured IR with VFX/DI desaturation and transitions without pretending the grade created the source image." },
      { id: "unreal_camera_planning", label: "Plan in Unreal", player_task: "Use location-derived 3D environments for sun, camera and lighting studies without calling Unreal the final renderer." },
      { id: "technical_record", label: "Document sets and lighting", player_task: "Maintain technical records that can support continuity, pickups and future rebuilds." },
      { id: "analog_intermediate", label: "Run film-out and scan-back", player_task: "Pass digital acquisition through the documented analog intermediate while keeping acquisition and exhibition formats distinct." },
      { id: "delivery_branch", label: "Protect 70mm as a separate branch", player_task: "Treat the 15-perf 70mm output as a delivery/exhibition path rather than the original capture format." },
      { id: "plate_first_vfx", label: "Start from photographed reference", player_task: "Use plates and practical reference to anchor lighting/contrast while retaining digital augmentation." },
      { id: "worm_gimbal", label: "Build the worm-riding base", player_task: "Coordinate performer, gimbal, sunlight and VFX reference for the sandworm ride." },
      { id: "worm_unit", label: "Schedule the worm unit", player_task: "Protect sunny-day requirements and desert-unit logistics for worm material." },
      { id: "spice_crawler", label: "Engineer crawler interaction", player_task: "Use roads, concrete plates, cranes, tractors and practical leg proxies to generate believable performer shadows." },
      { id: "vfx_vendor_boundary", label: "Separate lead partner from complete vendor ledger", player_task: "Recognize DNEG's lead role without inventing every shot allocation." },
      { id: "sand_sound", label: "Record the desert", player_task: "Build differentiated sand and wind libraries from field and controlled recordings." },
      { id: "worm_sound", label: "Design mass without a roar", player_task: "Use environmental interaction, grit and wind to communicate worm scale." },
      { id: "legacy_sound_elements", label: "Rebuild inherited sound language", player_task: "Adapt ornithopter, thumper and shield elements from Part One rather than lifting them unchanged." },
      { id: "ensemble_edit", label: "Shape the ensemble", player_task: "Use Joe Walker's editorial process to balance large-cast storylines without inventing an unseen revision ledger." },
      { id: "labor_delay_context", label: "Record labor-strike context", player_task: "Keep the delayed release as institutional context and avoid converting it into unsupported edit causality." },
      { id: "score_design", label: "Extend the musical world", player_task: "Use custom instruments and voice-led continuity while keeping score separate from sound design." },
      { id: "uncertainty_register", label: "Freeze unresolved ledgers", player_task: "Keep finance, schedule, camera, DI, set, VFX, sound, edit, music and delivery ledgers explicitly unresolved." },
      { id: "production_verification", label: "Close Dune: Part Two production audit", player_task: "Verify awards, versions, chronology, geography, camera/IR/Unreal, analog intermediate, physical/VFX, sound, edit, music and uncertainty boundaries before canonical promotion." }
    ]
  }
] as const;

export function mergeChapterNineteenDunePartTwoExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterNineteenDunePartTwoExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_nineteen_dune_part_two_verified",
      source: { list_id: "manual_chapter_nineteen_dune_part_two_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
