import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterEighteenIdaExpansionDefinitions = [
  {
    id: "scenario_ida_2013",
    title: "Ida",
    originalTitle: "Ida",
    aliases: [],
    year: 2013,
    titleType: "Movie",
    runtimeMins: 80,
    directors: ["Paweł Pawlikowski"],
    genres: ["Drama"],
    sourceId: "opus_ida_2013",
    sourceUrl: "https://opusfilm.com/films/feature-films/ida",
    scenarioType: "poland_denmark_public_coproduction_lodz_location_alexa_4x3_ultra_prime_arriraw_codex_color_capture_black_white_di_static_composition_negative_space_2013",
    premise: "Build Ida as a source-first Chapter 18 Production Case about how a Poland-Denmark art-cinema co-production used contemporary digital acquisition and post-production to construct an austere early-1960s monochrome world. Opus Film identifies the film as a Poland-Denmark 2013 production by Opus Film and Phoenix Film Investment, directed by Paweł Pawlikowski, written by Pawlikowski and Rebecca Lenkiewicz, photographed by Łukasz Żal and Ryszard Lenczewski, designed by Marcel Sławiński and Katarzyna Sobańska-Strzałkowska, costumed by Aleksandra Staszko, and produced by Eric Abraham, Piotr Dzięcioł and Ewa Puszczyńska. The producer-linked UK press book anchors an 80-minute version and documents Phoenix Film and Opus Film in association with Portobello Pictures, in co-production with Phoenix Film Poland and Canal+ Poland, with support from the Polish Film Institute, Eurimages, the Danish Film Institute and the City of Łódź; it also credits Jarosław Kamiński as editor, Claus Lynge as supervising sound editor and re-recording mixer, DI Factory for digital post, Michał Herman for grading, Ministi Film for sound post and Toya Studios for playback recording. The Danish Film Institute independently describes Ida as an Opus/Phoenix co-production and explains that the Danish partnership developed creatively and financially from 2009, with DFI and Eurimages support and Danish sound-post participation. Cinematography documentation based on detailed discussion with Żal records an ARRI ALEXA 4:3 camera, ARRI/Zeiss Ultra Prime lenses supplied by Panavision Poland, color capture recorded as ARRIRAW to Codex, and conversion to black-and-white in post on Nucoda at DI Factory in Warsaw. Sources label the exhibition frame both 1.33:1 and 1.37:1; the case therefore treats the verified fact as an Academy-like 4:3 composition strategy and preserves the exact 1.33-versus-1.37 label as version/documentation variance rather than inventing a single sensor crop or delivery raster. Pawlikowski repeatedly describes black-and-white as a deliberate abstraction from literal period realism and 4:3 as a constraint that favors portraits, double portraits, limited fields of vision and vertical composition. His unusual headroom and negative-space strategy grew from testing how that format could carry place and landscape without reverting to conventional widescreen framing. Contemporary accounts also document that longtime collaborator Ryszard Lenczewski established much of the visual preparation but became ill very early in production, after which camera operator Łukasz Żal stepped up as director of photography and photographed most of the film; the case preserves their shared cinematography credit without turning the handoff into an authorship competition. Detailed scene-lighting documentation with Żal supports a preference for simple, motivated and naturalistic source logic, while also proving that specific scenes used substantial controlled units including 6K lamps, a 1.2K, a 575W source, Kino Flo fill, Octodome, bounce, negative fill, smoke and Dedolights. Those fixtures remain scene-specific examples rather than unsupported film-wide recipes. FilmPolski and the Łódź UNESCO City of Film record extensive Łódź and regional location work, making period texture, access, uncontrolled modern detail and location continuity production problems rather than mere backdrop. The player must coordinate financing and institutional obligations, stripped-back script development, nonprofessional lead casting, DP handoff continuity, location selection, static and near-static mise-en-scène, 4:3 negative-space composition, color-on-set/monochrome-in-post monitoring, ARRIRAW/Codex data custody, restrained lighting, production design, costume and makeup continuity, editorial economy, jazz/playback recording and sound-post handoffs while refusing unsupported exact budget totals, exact shooting-day counts, exact ALEXA submodel beyond the documented 4:3 ALEXA description, complete focal-length maps, per-shot exposure values, a universal fixture list, exact Codex hardware submodel, exact Nucoda version, detailed production-sound recorder/microphone chain, exact grain recipe, or an invented technical resolution of the 1.33:1 versus 1.37:1 documentation variance.",
    requiredChoicesSeed: {
      screenplay: ["stripped_back_structure", "1962_setting", "identity_history_balance", "single_angle_economy", "non_expository_storytelling"],
      camera: ["alexa_4x3", "ultra_primes", "arriraw_codex", "static_composition", "negative_space", "aspect_ratio_variance_boundary", "dp_handoff_continuity"],
      editing: ["jaroslaw_kaminski", "single_angle_scene_logic", "elliptical_structure", "color_to_bw_di_handoff", "di_factory", "nucoda_boundary", "grain_recipe_unknowns"],
      sound: ["claus_lynge", "ministi_film", "toya_playback", "jazz_world", "silence_and_offscreen_space", "production_sound_equipment_unknowns"],
      themes: ["film_history", "2013", "ida", "pawel_pawlikowski", "lukasz_zal", "ryszard_lenczewski", "poland_denmark", "public_coproduction", "lodz", "alexa", "4x3", "1_33_1", "1_37_1", "black_white_post", "ultra_prime", "arriraw", "codex", "nucoda", "static_camera", "negative_space", "period_abstraction", "location_realism"]
    },
    learningGoals: [
      "Explain Ida as a coordinated writing, financing, location, performance, camera, design, post, editorial and sound system rather than only as an example of beautiful black-and-white cinematography.",
      "Use the producer-linked 80-minute version as the canonical runtime anchor while preserving shorter or longer catalogue runtimes as version metadata rather than silently normalizing them.",
      "Identify Paweł Pawlikowski as director and co-writer with Rebecca Lenkiewicz and separate directing authorship from the responsibilities of cinematography, design, editing, sound and production.",
      "Identify Opus Film and Phoenix Film as the central Poland-Denmark production partnership documented by producer and film-institute sources.",
      "Identify Portobello Pictures, Phoenix Film Poland and Canal+ Poland as documented association or co-production partners without collapsing them into one generic financier role.",
      "Separate Polish Film Institute, Eurimages, Danish Film Institute and City of Łódź support as distinct institutional layers with different production implications.",
      "Explain why a Polish-language period film could depend on transnational European development and public-support structures while remaining grounded in a predominantly Polish production world.",
      "Explain how the project evolved from an earlier, more plot-driven conception toward a stripped-back 1962 story whose production method depended on omission and precision.",
      "Treat the 1962 setting as a design, location, costume, prop, sound and performance coordination problem rather than as a generic monochrome look.",
      "Explain Pawlikowski's decision for black-and-white as an abstraction from literal realism and personal-memory strategy rather than proof that the film was captured by a monochrome sensor.",
      "Identify that Ida was captured in color and converted to black-and-white in digital post-production.",
      "Identify an ARRI ALEXA 4:3 camera as the documented acquisition platform while keeping an unsupported exact body/submodel outside the verified layer.",
      "Identify ARRI/Zeiss Ultra Prime lenses as a documented lens family supplied through Panavision Poland without inventing a complete focal-length inventory or shot-by-shot lens map.",
      "Identify ARRIRAW-to-Codex recording as the documented digital-negative path while keeping the exact Codex hardware model and media configuration unresolved.",
      "Identify DI Factory in Warsaw as the documented digital-post facility and Nucoda as the documented black-and-white finishing environment.",
      "Keep the exact Nucoda version, node structure, grain plug-in, output transforms and mastering settings unresolved unless title-specific records establish them.",
      "Distinguish color sensor capture from monochrome monitoring, grading and delivery decisions so that the player does not conflate acquisition with final appearance.",
      "Preserve the 1.33:1 versus 1.37:1 source-label variance and describe the production strategy as Academy-like 4:3 unless a particular delivery version is being specified.",
      "Explain why 4:3 favors portraits and double portraits while constraining horizontal landscape coverage.",
      "Explain how Pawlikowski and the cinematography team used vertical framing, high headroom and negative space to make the constrained frame carry architecture, landscape and absence.",
      "Treat unusual headroom as a deliberate compositional system developed through testing rather than as accidental bad framing.",
      "Explain how a limited field of vision can increase offscreen implication and force production design, blocking and sound to carry information outside the frame.",
      "Explain Pawlikowski's preference for handling scenes from one strong angle as a production choice that changes blocking, rehearsal, coverage, continuity and editorial options.",
      "Distinguish the film's predominantly static or near-static visual grammar from an absolute no-movement rule that would erase documented exceptions.",
      "Identify Ryszard Lenczewski and Łukasz Żal as the shared credited cinematographers and preserve both contributions in the verified record.",
      "Explain that Lenczewski performed substantial visual preparation before illness forced an early production handoff.",
      "Explain how Żal's move from camera operator to director of photography required continuity of visual principles while allowing active reframing and problem solving on set.",
      "Keep the exact calendar day of the DP handoff lower-confidence unless a primary production record fixes it unambiguously.",
      "Explain why thousands of preparatory still photographs and location observation can function as cinematography research without being equivalent to final shot lists.",
      "Use Łódź and regional location records as evidence that period authenticity depended on finding controllable textures, streets, interiors, religious spaces and rural environments.",
      "Explain why contemporary intrusions, signage, vehicles, surfaces, power access and public control become practical risks when present-day locations stand in for 1962.",
      "Identify Marcel Sławiński and Katarzyna Sobańska-Strzałkowska as documented production-design/scenography leads.",
      "Identify Aleksandra Staszko as costume designer and keep unverified fabric, sourcing and ageing recipes outside the locked layer.",
      "Identify Anna Niuta Kieszczyńska and Tomasz Sielecki as documented make-up credits while avoiding unsupported product or prosthetic claims.",
      "Explain why black-and-white finishing changes design and wardrobe testing: colors must be evaluated for tonal separation rather than assumed to reproduce by hue.",
      "Explain why the camera, design and costume departments need shared grayscale tests when final color relationships will be discarded.",
      "Explain Żal's stated preference for simple, motivated and natural-light logic without misdescribing the production as available-light-only.",
      "Use the documented kitchen and chapel setups as scene-specific evidence that a visually simple result can require multiple controlled fixtures, diffusion, bounce, smoke and negative fill.",
      "Keep the documented 6K, 1.2K, 575W, Kino Flo, Octodome and Dedolight examples as scene-specific evidence tied to the scenes for which they are actually described.",
      "Explain how a motivated single-source illusion can be constructed from several units while still reading as natural window, fire or practical light.",
      "Distinguish lighting intention from exact exposure: fixture identity does not prove stop, EI, shutter, filtration or dimmer level for every shot.",
      "Explain how smoke, bounce and negative fill can shape grayscale separation without treating them as universal rules across the whole film.",
      "Explain why a nonprofessional lead performer increases the value of clear blocking, restrained coverage and an on-set environment that supports concentration rather than technical spectacle.",
      "Separate casting history from performance claims: Agata Trzebuchowska's lack of prior acting experience is production context, not a license to generalize about nonprofessional actors.",
      "Identify Jarosław Kamiński as editor and explain how limited coverage transfers more responsibility to pre-shoot blocking and shot duration while still leaving editorial rhythm consequential.",
      "Explain how elliptical storytelling and removal of explanatory material require confidence that image, performance and sound can carry omitted information.",
      "Identify DI Factory's post role and Michał Herman's grading credit as documented post-production ownership.",
      "Identify Stage 2 computer-effects credits without inflating a restrained film into a VFX-led production case.",
      "Identify Claus Lynge as supervising sound editor and re-recording mixer and Ministi Film as the documented sound-post facility.",
      "Identify Toya Studios as a documented playback-recording layer and keep playback capture distinct from production dialogue recording and final rerecording.",
      "Explain why jazz, pop songs, religious sound, room tone and silence must be treated as different narrative and production sound layers.",
      "Keep exact production microphones, recorders, track layouts, ADR systems and final mix format unresolved unless stronger title-specific evidence is recovered.",
      "Explain how Danish co-production participation included sound-post capabilities rather than treating the Denmark credit as financing-only.",
      "Distinguish awards and later reception from production evidence: cinematography prizes validate reception but do not prove a camera model, lens or lighting setup.",
      "Maintain an uncertainty register for exact budget, shooting days, ALEXA submodel, complete focal-length set, shot-lens allocation, exposure values, Codex model, exact monochrome/grain recipe, production-sound equipment and delivery raster.",
      "Explain Ida's Chapter 18 significance as evidence that digital convergence could enable radical formal restraint and historically inflected monochrome rather than only greater spectacle or mobility.",
      "Contrast Ida's modern digital-negative workflow with its intentionally old-looking frame and tonal world so technological newness is not confused with visible futurism.",
      "Build a closing production audit that checks co-production provenance, 80-minute versioning, 4:3 label variance, DP handoff, location control, ARRIRAW/Codex custody, grayscale design testing, scene-specific lighting evidence, DI ownership, editorial lineage and sound-post provenance before verification."
    ],
    phases: [
      { id: "evidence_hierarchy", label: "Map the Ida evidence hierarchy", player_task: "Separate producer and film-institute records, Pawlikowski/Żal/Lenczewski testimony, detailed scene-lighting documentation and later catalogue metadata before promoting technical claims." },
      { id: "released_version", label: "Lock the 80-minute production anchor", player_task: "Use the producer-linked 80-minute version while recording 79/82-minute catalogue variants as version differences rather than production contradictions." },
      { id: "coproduction_map", label: "Map Poland-Denmark production", player_task: "Assign Opus, Phoenix, Portobello, Phoenix Film Poland and Canal+ Poland their documented production or association roles without flattening the structure." },
      { id: "support_layers", label: "Separate public-support layers", player_task: "Track Polish Film Institute, Eurimages, Danish Film Institute and City of Łódź support as distinct institutional dependencies." },
      { id: "script_reduction", label: "Convert script reduction into production grammar", player_task: "Translate the stripped-back 1962 screenplay into scene plans that rely on image, behavior, sound and omission instead of explanatory coverage." },
      { id: "period_world", label: "Build the 1962 world", player_task: "Coordinate locations, design, costume, props, vehicles, signage, surfaces and sound so the period is controlled without pretending monochrome alone creates authenticity." },
      { id: "location_research", label: "Audit Łódź and regional locations", player_task: "Use documented city and regional locations as production evidence and flag modern intrusions, access, power, weather and crowd-control risks." },
      { id: "casting_method", label: "Protect the nonprofessional lead workflow", player_task: "Build rehearsal and set procedures around a first-time lead performer without stereotyping nonprofessional performance or sacrificing precision." },
      { id: "dp_handoff", label: "Manage the cinematography handoff", player_task: "Preserve Lenczewski's preparatory visual logic while enabling Żal to assume DP responsibility early in production and solve scenes collaboratively." },
      { id: "still_research", label: "Use preparatory still photography", player_task: "Treat location and mood photographs as research inputs that guide framing and light rather than immutable shot-list commands." },
      { id: "aspect_ratio", label: "Lock the Academy-like 4:3 strategy", player_task: "Compose for the documented 4:3 image while recording 1.33:1 and 1.37:1 labels as source/version variance instead of inventing one universal raster." },
      { id: "negative_space", label: "Design vertical negative space", player_task: "Use high headroom, low subject placement and off-center framing purposefully while preserving legibility, eyelines and production-design control." },
      { id: "single_angle", label: "Stage scenes for one strong angle", player_task: "Rehearse blocking and performance so many scenes can work from a single primary camera position without relying on conventional coverage." },
      { id: "movement_boundary", label: "Keep movement exceptional", player_task: "Treat static or near-static framing as the dominant grammar while allowing documented movement where the film deliberately breaks its pattern." },
      { id: "alexa_4x3", label: "Configure ALEXA 4:3 acquisition", player_task: "Use the documented ALEXA 4:3 platform but leave exact body/submodel, firmware and sensor-mode implementation unresolved unless stronger production records establish them." },
      { id: "ultra_primes", label: "Build the Ultra Prime package", player_task: "Use the documented ARRI/Zeiss Ultra Prime family while keeping complete focal-length inventory and shot assignments provisional." },
      { id: "arriraw_codex", label: "Protect ARRIRAW/Codex custody", player_task: "Track camera originals, checksums, media rotation and handoff through the documented ARRIRAW-to-Codex path without inventing a Codex hardware model." },
      { id: "color_capture", label: "Monitor color for monochrome intent", player_task: "Capture the documented color signal while evaluating grayscale separation and protecting enough source information for the black-and-white finish." },
      { id: "grayscale_tests", label: "Coordinate grayscale design tests", player_task: "Test costume, skin, walls, props and locations for tonal separation so colors that differ by hue do not collapse unexpectedly after monochrome conversion." },
      { id: "naturalistic_light", label: "Build motivated light", player_task: "Favor simple natural or single-source logic while allowing controlled units whenever the location needs direction, contrast or continuity." },
      { id: "kitchen_day", label: "Reconstruct the documented kitchen daylight logic", player_task: "Use the verified multi-unit example to create a convincing window-led image while keeping 6K, 1.2K, 575W and Kino Flo evidence tied to that setup." },
      { id: "chapel_day", label: "Reconstruct the chapel source logic", player_task: "Use the documented diffused 6Ks, negative fill and Dedolight accents to understand how an apparently simple natural image was controlled." },
      { id: "kitchen_night", label: "Build the documented night-interior logic", player_task: "Use the documented Octodome, bounce and fire-source example as a scene-specific exercise in motivated grayscale lighting." },
      { id: "lighting_boundaries", label: "Separate fixture evidence from exposure claims", player_task: "Do not infer universal EI, stop, shutter, filtration, dimmer levels or fixture positions from the documented scene examples." },
      { id: "production_design", label: "Coordinate scenography and camera", player_task: "Give Sławiński and Sobańska-Strzałkowska's design layer control over textures, geometry and period detail that must survive severe framing and monochrome conversion." },
      { id: "costume_makeup", label: "Test costume and make-up tonally", player_task: "Coordinate Staszko, Kieszczyńska and Sielecki credits through grayscale tests while refusing unsupported fabric, product or ageing recipes." },
      { id: "editorial_economy", label: "Assemble limited coverage", player_task: "Let Jarosław Kamiński shape ellipsis and duration from intentionally constrained coverage without pretending editing became irrelevant." },
      { id: "di_factory", label: "Handoff to DI Factory", player_task: "Preserve camera-original provenance through the documented DI Factory workflow and give grading ownership a clear handoff." },
      { id: "bw_nucoda", label: "Create the black-and-white finish", player_task: "Use the documented Nucoda finishing environment to build monochrome contrast while keeping exact software version, node graph and grain recipe unresolved." },
      { id: "effects_boundary", label: "Bound computer-effects work", player_task: "Track documented Stage 2 computer-effects ownership without recasting Ida as an effects-driven production." },
      { id: "sound_post", label: "Map Danish sound-post ownership", player_task: "Coordinate Claus Lynge, Ministi Film and additional sound-post credits while keeping production-recording hardware separate and unresolved." },
      { id: "playback_music", label: "Separate playback and music layers", player_task: "Use Toya Studios playback documentation and credited musicians to distinguish on-set playback, performed jazz, score, licensed music and final mix." },
      { id: "offscreen_sound", label: "Use sound beyond the 4:3 frame", player_task: "Design room tone, religious ambience, traffic, music and silence so the restricted image can imply a larger world without unnecessary visual coverage." },
      { id: "unknowns_register", label: "Maintain the Ida unknowns register", player_task: "Track exact budget, shooting days, ALEXA submodel, full lens map, exposure values, Codex model, DI/grain recipe, production-sound equipment and delivery-raster specifics explicitly." },
      { id: "chapter18_position", label: "Position Ida in digital convergence", player_task: "Explain how contemporary digital capture and post enabled an image designed to feel formally restrained, temporally displaced and non-spectacular." },
      { id: "delivery_review", label: "Audit the complete Ida production system", player_task: "Verify production provenance, runtime versioning, 4:3 label variance, DP handoff, locations, design, ARRIRAW/Codex custody, lighting boundaries, DI conversion, editing and sound-post evidence before closure." }
    ]
  }
] as const;

export function mergeChapterEighteenIdaExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterEighteenIdaExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_eighteen_ida_verified",
      source: { list_id: "manual_chapter_eighteen_ida_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
