import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterNineteenTheZoneOfInterestExpansionDefinitions = [
  {
    id: "scenario_the_zone_of_interest_2023",
    title: "The Zone of Interest",
    originalTitle: "The Zone of Interest",
    aliases: ["Zone of Interest"],
    year: 2023,
    titleType: "Movie",
    runtimeMins: 106,
    directors: ["Jonathan Glazer"],
    genres: ["Drama", "History"],
    sourceId: "cannes_the_zone_of_interest_2023",
    sourceUrl: "https://www.festival-cannes.com/en/f/the-zone-of-interest/",
    scenarioType: "award_priority_auteur_festival_jonathan_glazer_a24_film4_access_entertainment_jw_films_extreme_emotions_auschwitz_oswiecim_reconstructed_hoss_house_multi_camera_observational_system_up_to_ten_cameras_sony_venice_rialto_leitz_m_0_8_hidden_cameras_hidden_microphones_remote_focus_hardwired_playback_crew_bunker_available_practical_light_iso_3200_flir_thermal_camera_1k_ai_upscale_two_year_edit_paul_watts_johnnie_burn_600_page_sound_bible_tarn_willers_wireless_plant_mics_mica_levi_naturalistic_baselight_grade_2023",
    premise: "Build The Zone of Interest as Chapter 19's award-priority auteur/festival production case by treating Jonathan Glazer's film as a production system designed to remove conventional filmmaking presence from the actors' environment while relocating much of the film's historical violence into sound. Festival de Cannes records the film at 106 minutes and awarded it the 2023 Grand Prix and CST Award for Best Artist-Technician; the Academy later awarded it International Feature Film and Sound. Awards establish reception and significance, but they do not by themselves prove production method. The locked production evidence comes from direct craft testimony and institutional records. Cannes identifies Jonathan Glazer as director/screenwriter, Lukasz Zal as cinematographer, Chris Oddy as production designer, Paul Watts as editor, Mica Levi as composer and Johnnie Burn as sound lead; A24, Film4, Access Entertainment, JW Films and Extreme Emotions are documented production partners. Current locked sources do not establish one audited final negative cost, complete financing percentages, recoupment waterfall, total crew count or full shooting-day ledger, so those figures remain unresolved. The central production decision was to build an observational arena rather than operate a conventional set. Glazer and Zal reconstructed the Hoss family house and garden close to Auschwitz using historical research and production design led by Chris Oddy, then integrated a hardwired network of fixed and partially hidden cameras into walls, floors, ceilings and bushes. British Cinematographer records Glazer's intent to use as many as ten cameras, though individual scenes could use fewer, with simultaneous playback and remote focus routed to a separate crew position. Cameras were removed from the actors' awareness as much as possible; the active room could contain performers while director, cinematography, focus and video teams watched remotely. This is not evidence of an uncontrolled documentary shoot. Camera positions, geometry, cabling, monitoring and focus infrastructure were heavily preplanned so that performances could unfold with less visible intervention. The principal image system used Sony VENICE with Rialto camera extension and compact Leitz M 0.8 lenses. Zal describes a crisp, contemporary 21st-century look rather than a simulated vintage image. The system's small remote heads and high-sensitivity operation supported hidden placement and practical-light exposure. He cites ISO 3200 use with ordinary low-wattage bulbs, candles and oil lamps. The case therefore separates low-light capability from a claim of 'no lighting': available and practical sources were deliberately selected and shaped through production design, weather, time of day and camera testing even when conventional film fixtures were minimized. Day and night LUTs were developed after testing the reconstructed house under changing natural conditions. Geometric, straight-line framing and deliberately unattractive domestic color/texture were part of the historical-distance strategy rather than aesthetic polish. The nighttime scenes of a Polish girl leaving food for prisoners use a different capture system entirely: a FLIR thermal-imaging military camera supplied through ARRI Rental. Zal describes the camera as reading temperature rather than ordinary visible-light exposure, operating at roughly 1K resolution and requiring substantial testing, altered workflow, different focus/playback logic and later AI-assisted upscaling. Those passages therefore must not be generalized to the film's principal Sony VENICE capture. The thermal footage is a sequence-specific production solution chosen because the filmmakers wanted to depict darkness without conventional movie-light tropes while keeping the film's broader rule of examining the past through contemporary technology. Production design was inseparable from the camera method. Oddy describes repeated visits to the real Hoss house beginning in 2018 and a responsibility to reconstruct the domestic world faithfully in geographic relation to the camp. Historical photographs and architectural research informed the replica, while the replica itself had to function technically as a wired multi-camera machine. Walls, floors and ceilings needed pathways for camera, focus, playback and sound infrastructure without revealing that infrastructure to performers. The house was therefore simultaneously historical reconstruction, performance environment and camera-control apparatus. The sound method forms a second film layered against the visible domestic one. Johnnie Burn and Glazer repeatedly describe The Zone of Interest as two films: the ordinary family world that is seen and heard in the house, and the atrocity over the wall that is heard but not shown. Burn spent months researching Auschwitz archives, witness testimony, descriptions, languages, machinery and geography before building a roughly 600-page sound reference document. His team then recorded source material across real locations in Europe rather than treating the camp sound as generic horror ambience. The aim was historical and spatial plausibility: gunshot distance, industrial machinery, prisoners' voices, dogs, trains, clogs on gravel and the crematoria's mechanical presence all needed to behave as if located beyond the wall. Burn's approach rejects the idea that off-screen sound can be an abstract emotional layer detached from evidence. The visible domestic soundtrack also required an unconventional production-sound system because the crew could not stand inside the live house. Production mixer Tarn Willers describes radio microphones on performers and plant microphones distributed through house and garden, with receivers and monitoring outside the performance space. The actors could move between rooms and garden without boom operators entering. Some takes could run for long periods, including extended improvised or semi-improvised behavior, so RF reliability and environmental coverage became production constraints. The sound department was not merely collecting clean dialogue; domestic footsteps, pots, room tone, children, doors and movement had to make the house sound physically inhabited before the camp soundtrack was layered in post. Editing was correspondingly unusual. Paul Watts describes whole events captured by up to ten cameras rather than by conventional master-medium-close coverage. The multi-camera system generated many simultaneous versions of the same temporal event, giving editorial unusual control over viewpoint while preserving continuous performance. British Cinematographer reports an edit extending for almost two years. Watts also states that picture, VFX, sound design and music were developed concurrently rather than in a simple lock-picture-then-handoff chain. Burn and Mica Levi's work could reshape picture decisions while continuing editorial changes reshaped sound and music. This is an iterative post system, not evidence that every department worked without milestones. The grade followed the same anti-romantic principle as photography. Colorist Gareth Bishop describes preserving available/practical-light realism, avoiding conventional face shaping, vignettes and keyframed beautification in almost all scenes, and using Baselight sharpening to reinforce a crisp contemporary image rather than adding a nostalgic filmic patina. Matching simultaneous cameras became a technical challenge, but the goal was consistency without turning the image into stylized period nostalgia. The historical lesson is therefore organizational as much as aesthetic. Glazer's production deliberately moved authorial control from visible on-set intervention into preproduction architecture: historical research, replica construction, hidden camera placement, hardwired control, remote focus, practical-light testing, wireless/plant-mic coverage and an enormous historically researched off-screen sound build. That architecture allowed performers more behavioral continuity while preserving very tight control over where and how their lives were observed. The film's Grand Prix and two Oscars make it a high-priority modern case, but its educational value lies in the production method: absence in the room required more planning outside the room, and omission in the image required more evidence and craft in the sound. The player must keep uncertainty boundaries explicit. Current locked sources do not establish an audited total budget, full financing structure, exact complete shooting schedule, exact camera count on every scene, full lens-per-shot ledger, complete lighting inventory, every cabling/control specification, exact thermal-camera model configuration, full editorial software/storage/version history, complete VFX vendor/shot ledger, every production-sound frequency/channel assignment, all field-recording locations, final stem architecture, exact mix-stage routing, full music-session documentation or distribution recoupment.",
    requiredChoicesSeed: {
      screenplay: ["glazer_adaptation", "domestic_visible_camp_audible", "award_context_not_workflow_evidence", "budget_unresolved_boundary", "historical_research_boundary"],
      camera: ["sony_venice", "rialto_extension", "leitz_m_08", "up_to_ten_cameras", "hidden_hardwired_network", "remote_focus_playback", "iso_3200_practical_light", "flir_thermal_sequence", "day_night_luts"],
      editing: ["simultaneous_event_coverage", "multi_camera_calibration", "nearly_two_year_edit", "paul_watts", "picture_sound_vfx_music_iteration", "naturalistic_baselight_grade"],
      sound: ["johnnie_burn_sound_bible", "two_films_sound_concept", "tarn_willers_wireless", "plant_mics", "no_boom_live_house", "historical_field_recording", "camp_industrial_rumble"],
      themes: ["film_history", "2023", "the_zone_of_interest", "award_priority", "auteur_festival", "observational_multicamera", "offscreen_sound", "historical_reconstruction", "chapter19"]
    },
    learningGoals: [
      "Explain why The Zone of Interest is prioritized by major awards rather than lane rotation alone.",
      "Identify the Cannes Grand Prix and later Academy International Feature and Sound wins as reception context, not production-method evidence.",
      "Identify Jonathan Glazer as director and screenwriter.",
      "Use Cannes' 106-minute runtime record.",
      "Identify Lukasz Zal as cinematographer, Chris Oddy as production designer, Paul Watts as editor, Mica Levi as composer and Johnnie Burn as sound lead.",
      "Identify A24, Film4, Access Entertainment, JW Films and Extreme Emotions within the documented production structure.",
      "Keep audited final negative cost, financing percentages and recoupment unresolved.",
      "Explain the reconstructed Hoss house as both historical set and technical capture machine.",
      "Explain why proximity to Auschwitz geography mattered to production design and sound spatiality.",
      "Explain historical photographs and site research as production-design evidence inputs.",
      "Explain the hidden-camera method as highly planned rather than uncontrolled documentary capture.",
      "Preserve 'up to ten cameras' rather than claiming every scene used ten cameras.",
      "Explain simultaneous playback as a requirement of the multi-camera system.",
      "Explain hardwired camera control and remote focus as infrastructure that enabled a crew-free performance room.",
      "Explain why walls, floors and ceilings had to carry hidden cabling routes.",
      "Explain the separate monitoring bunker/container as an organizational consequence of removing crew from the house.",
      "Identify Sony VENICE as the principal documented camera family.",
      "Identify Rialto extension as a documented way to reduce camera-head intrusion.",
      "Identify compact Leitz M 0.8 lenses as part of the documented hidden-camera package.",
      "Explain the crisp 21st-century image goal rather than a fabricated vintage look.",
      "Explain ISO 3200 use as part of a practical-light strategy, not proof that the film used no lighting decisions.",
      "Identify low-wattage bulbs, candles and oil lamps as documented practical sources.",
      "Explain day/night LUT testing as a response to changing natural light in the house.",
      "Explain geometric straight-line framing as part of the observational distance.",
      "Explain why deliberately unattractive domestic color/texture can be a production-design choice.",
      "Identify the FLIR thermal-imaging system as a separate sequence-specific camera technology.",
      "Explain why thermal imaging reads heat rather than ordinary visible-light exposure.",
      "Preserve the roughly 1K thermal source resolution and later AI-assisted upscale as documented constraints.",
      "Reject the claim that the whole film was shot with thermal cameras.",
      "Explain the thermal sequences as a solution to darkness without conventional movie-light tropes.",
      "Explain the visible family film and the audible camp film as two deliberately constructed layers.",
      "Identify Johnnie Burn's months of archival and witness-testimony research.",
      "Preserve the roughly 600-page sound bible as a documented research artifact.",
      "Explain why camp sound required geographic and historical plausibility rather than generic horror ambience.",
      "Explain field recording across Europe as a strategy for credible acoustic material.",
      "Explain why gunshot distance, industrial machinery and voices had to be spatially related to the reconstructed house.",
      "Explain the constant industrial rumble as a designed representation of the camp's machinery rather than a literal single source recording.",
      "Identify Tarn Willers as production mixer.",
      "Explain radio microphones on actors as necessary when boom operators could not enter the live house.",
      "Explain plant microphones through house and garden as environmental coverage rather than dialogue-only capture.",
      "Explain RF reliability as a production constraint when takes could run for extended periods.",
      "Explain why domestic footsteps, pots, doors and room tone mattered before camp sound was added.",
      "Explain long behavioral takes as a performance method enabled by hidden capture infrastructure.",
      "Identify Paul Watts as editor.",
      "Explain simultaneous event coverage as different from conventional master-medium-close coverage.",
      "Explain how up to ten camera angles create editorial calibration without breaking performance continuity.",
      "Preserve the nearly two-year edit as documented scale without inventing a complete version ledger.",
      "Explain picture, VFX, sound and music as overlapping post processes rather than a simple sequential handoff.",
      "Identify Gareth Bishop as colorist in the documented finishing testimony.",
      "Explain the naturalistic grade as avoidance of conventional face shaping, vignettes and nostalgic period stylization.",
      "Explain Baselight sharpening as part of the crisp contemporary image strategy.",
      "Explain multi-camera matching as a finishing problem created by simultaneous capture.",
      "Reject the idea that removing crew from the room reduced production complexity overall.",
      "Explain how authorial control shifted from visible intervention to preplanned infrastructure.",
      "Explain omission in the image as requiring greater precision in off-screen sound construction.",
      "Separate major awards from evidence about camera, sound, edit and production design workflows.",
      "Keep exact per-scene camera count, full lens ledger, complete lighting package and full cable/control topology unresolved.",
      "Keep exact thermal-camera configuration, full VFX ledger and complete editorial software/storage history unresolved.",
      "Keep complete wireless-frequency plan, field-recording location ledger, stem architecture and music-session documentation unresolved.",
      "Close the production case only when awards context, historical reconstruction, multi-camera capture, sound research, editorial structure and uncertainty boundaries agree."
    ],
    phases: [
      { id: "award_priority", label: "Lock award-priority selection", player_task: "Use Grand Prix and Academy wins to justify case priority, while keeping awards separate from workflow evidence." },
      { id: "evidence_hierarchy", label: "Build the evidence hierarchy", player_task: "Separate Cannes/Academy records from direct cinematography, production-design, edit and sound testimony." },
      { id: "finance_boundary", label: "Freeze unresolved finance", player_task: "Do not canonicalize budget or financing percentages not established by locked authoritative sources." },
      { id: "site_research", label: "Research the real Hoss geography", player_task: "Use site visits, historical photographs and Auschwitz geography to anchor the reconstructed domestic world." },
      { id: "house_reconstruction", label: "Reconstruct the house", player_task: "Build a historically plausible Hoss home and garden while preserving its relation to the camp wall." },
      { id: "technical_architecture", label: "Turn the set into capture infrastructure", player_task: "Design walls, floors and ceilings around hidden camera, focus, playback and sound routes." },
      { id: "camera_network", label: "Plan up to ten cameras", player_task: "Choose simultaneous camera positions for whole events without claiming that every scene uses the maximum count." },
      { id: "remote_control", label: "Move control outside the room", player_task: "Route monitoring and focus to the separate crew position so performers can occupy the house without visible crew." },
      { id: "venice_rialto", label: "Build the VENICE/Rialto package", player_task: "Use compact remote heads where hidden placement and sharp full-frame coverage require them." },
      { id: "leitz_package", label: "Choose compact lenses", player_task: "Use the documented Leitz M 0.8 family where size and observational sharpness support hidden placement." },
      { id: "practical_light", label: "Expose practical sources", player_task: "Work with bulbs, candles, oil lamps and available daylight while protecting exposure at the documented high-sensitivity settings." },
      { id: "weather_time", label: "Schedule around natural conditions", player_task: "Treat weather and time of day as lighting-department variables rather than uncontrolled accidents." },
      { id: "day_night_luts", label: "Test day and night LUTs", player_task: "Build transforms from camera tests in the actual reconstructed spaces rather than inventing a generic period LUT." },
      { id: "geometry", label: "Protect geometric framing", player_task: "Keep straight lines and observational distance consistent across simultaneous camera positions." },
      { id: "thermal_test", label: "Engineer the thermal sequences", player_task: "Test FLIR heat imaging, playback and focus as a separate capture system with different assumptions from visible-light cinematography." },
      { id: "thermal_upscale", label: "Protect the low-resolution thermal pipeline", player_task: "Plan the roughly 1K source and later upscale without presenting it as the principal film format." },
      { id: "crew_absence", label: "Remove visible filmmaking presence", player_task: "Clear the live house of camera and boom crews once the hidden infrastructure is ready." },
      { id: "wireless_sound", label: "Build wireless actor coverage", player_task: "Use performer radio mics because conventional boom coverage is incompatible with the live-house rule." },
      { id: "plant_mics", label: "Plant the environment", player_task: "Place microphones through rooms and garden so footsteps, objects and movement remain credible across long takes." },
      { id: "rf_reliability", label: "Protect RF continuity", player_task: "Treat dropout prevention as a critical production requirement when actors can move across the full house and garden." },
      { id: "domestic_track", label: "Complete the visible film's sound", player_task: "Build the domestic acoustic world before allowing camp horror to dominate editorial judgments." },
      { id: "sound_research", label: "Build the Auschwitz sound bible", player_task: "Research archives, witness testimony, machinery, languages and geography before constructing the off-screen camp." },
      { id: "field_recording", label: "Record credible source material", player_task: "Gather real acoustic material in appropriate spaces rather than relying only on generic libraries." },
      { id: "camp_spatiality", label: "Map sound beyond the wall", player_task: "Place voices, gunshots and machinery according to historical geography and distance from the house." },
      { id: "industrial_rumble", label: "Design the machine of death", player_task: "Build the continuous industrial presence as a composite sound design while preserving its historical function." },
      { id: "long_take_performance", label: "Protect behavioral continuity", player_task: "Let actors inhabit scenes for extended periods while hidden systems capture multiple views simultaneously." },
      { id: "multi_camera_edit", label: "Unpack simultaneous events", player_task: "Choose among concurrent angles without pretending the material was shot as conventional coverage." },
      { id: "edit_duration", label: "Sustain the long editorial process", player_task: "Use the nearly two-year edit to test viewpoint, duration and omission without inventing unsupported version counts." },
      { id: "iterative_post", label: "Keep post departments in dialogue", player_task: "Let picture, VFX, sound design and music inform each other before final lock while retaining formal checkpoints." },
      { id: "naturalistic_grade", label: "Grade without beautification", player_task: "Match simultaneous cameras and preserve practical-light realism without routine face shaping or nostalgic period treatment." },
      { id: "sharpness", label: "Protect the crisp contemporary image", player_task: "Use finishing sharpness deliberately while removing artifacts where the treatment breaks the image." },
      { id: "anti_documentary_myth", label: "Reject the uncontrolled-documentary myth", player_task: "Show that apparent observational freedom depends on extensive preplanned technical control." },
      { id: "anti_award_myth", label: "Reject award-as-evidence shortcuts", player_task: "Use awards to establish significance, never to infer undocumented production methods." },
      { id: "uncertainty_audit", label: "Audit unresolved technical ledgers", player_task: "Keep unsupported budget, camera-per-scene, lighting, thermal, edit-storage, VFX, RF and mix-chain details outside canonical truth." },
      { id: "production_verification", label: "Close Production Verification", player_task: "Close only when awards context, historical reconstruction, hidden multi-camera capture, researched sound, editorial method and uncertainty boundaries agree." }
    ]
  }
] as const;

export function mergeChapterNineteenTheZoneOfInterestExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterNineteenTheZoneOfInterestExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_nineteen_the_zone_of_interest_verified",
      source: { list_id: "manual_chapter_nineteen_the_zone_of_interest_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
