import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterNineteenAllQuietOnTheWesternFrontExpansionDefinitions = [
  {
    id: "scenario_all_quiet_on_the_western_front_2022",
    title: "All Quiet on the Western Front",
    originalTitle: "Im Westen nichts Neues",
    aliases: ["All Quiet on the Western Front", "Im Westen nichts Neues"],
    year: 2022,
    titleType: "Movie",
    runtimeMins: 147,
    directors: ["Edward Berger"],
    genres: ["Drama", "War"],
    sourceId: "arri_all_quiet_on_the_western_front_2022",
    sourceUrl: "https://www.arri.com/news-en/arri-cameras-lenses-and-lighting-shine-behind-2023-oscar-winners/shot-on-arri-equipment-and-serviced-by-arri-rental-all-quiet-on-312722",
    scenarioType: "award_priority_bafta_best_film_german_czech_european_large_scale_war_production_edward_berger_james_friend_alexa65_alexa_mini_lf_dna_prime65s_arri_rental_prague_hexatron_large_format_location_trenches_battlefield_practical_effects_hundreds_extras_costume_breakdown_mud_continuity_viktor_prasil_wild_tracks_40gb_multichannel_frank_kruse_markus_stemler_subjective_sound_sven_budelmann_documentary_editing_volker_bertelmann_score_practical_digital_vfx_2022",
    premise: "Build All Quiet on the Western Front as Chapter 19's next award-priority production case because BAFTA records it as the 2023 Best Film winner, while keeping that award strictly separate from evidence about how the film was made. The case treats Edward Berger's 2022 adaptation as a German-led, Czech-based large-scale physical war production for Netflix in which camera engineering, battlefield construction, practical effects, costume/makeup continuity, performance logistics, production sound, editorial restraint and selective digital augmentation work as one system. BBFC classifies the original 2D cinema version at 147 minutes 15 seconds and later lists a 148-minute-48-second VOD version, so the playable case uses 147 minutes while preserving the version/runtime difference rather than forcing a false single runtime. ARRI documents James Friend ASC BSC shooting mainly with ALEXA 65 and ALEXA Mini LF cameras, using DNA and Prime 65 S lenses, with ARRI Orbiter and SkyPanel lighting and ARRI Rental support in Prague. Friend describes the ALEXA 65 not only as a vista camera but as a format that became immersive inside confined trenches; ARRI also documents the HEXATRON all-terrain crane vehicle as part of the camera-support system. The format lesson is therefore not 'large format equals wide landscapes': the production used scale, proximity, mobile support and confined-space movement together. Netflix's making-of record documents a battlefield/trench layout that production designer Christian Goldbeck and Berger planned for roughly two months before construction and shooting. That environment was not passive scenery. Trenches, shell holes, mud, weather, extras, practical effects, camera movement and performer safety had to be designed together because action unfolded continuously through the same physical geography. Netflix also documents a pre-shoot bootcamp led through the stunt department so performers learned to run, fall, handle rifles and machine guns and move under roughly 15 kilograms of uniform and weapons. Hundreds of extras amplified the physical-production problem rather than merely filling frames. Costume designer Lisy Christl describes maintaining around twenty versions of Paul Baeumer's uniform across progressive states of damage and dirt, while the production made roughly 800 to 900 costumes for extras. Makeup and hair designer Heike Merker describes breaking characters down scene by scene and treating mud, blood, cold, injury and exhaustion as continuity states rather than one generic 'dirty soldier' look. Those departments therefore form a continuity-control system tied directly to editorial chronology. Production sound began before post. Frank Kruse describes contacting production sound mixer Viktor Prasil before photography because COVID restrictions made later access uncertain and because crowds, vehicles, weapons, tanks, flamethrowers and battlefield action would be difficult or impossible to recreate faithfully later. Prasil's production workflow used Aaton Cantar X3, Sound Devices 688 and MixPre-10 II and Sony PCM-D50 recorders, DPA 6061/4061 lavaliers, Schoeps and Sennheiser boom/effects microphones and a Holophone H3-D for multichannel capture. He and the team embedded radio microphones into helmets, created rubber-soled boot solutions to reduce unwanted metal-spike noise, built sound-absorbing control for rain/interior problems and captured more than 40 GB of edited wild-track material in mono, stereo and five-channel forms. Kruse separately estimates eight-plus hours of wild tracks. These are overlapping descriptions of the same unusually deep production-sound strategy, not contradictory exact totals that need artificial reconciliation. The sound team then used production recordings as a base layer rather than discarding location sound and rebuilding everything from scratch. Frank Kruse and Markus Stemler describe an explicitly subjective approach: battlefield sound had to remain emotionally aligned with Paul, and technical historical accuracy could be subordinated when necessary to the psychological experience of weapons such as tanks. That does not mean the soundtrack ignored research. Kruse studied period descriptions and reconstruction evidence, while Stemler and the Foley team combined authentic production elements with designed layers. Original uniforms were made available to Foley. Tank sequences used captured vehicle material plus additional metal resonance and designed weight. The image-effects philosophy followed a similar practical-first but not practical-only rule. VFX supervisor Frank Petzold describes using digital work for background aircraft and other extensions while preserving photographed elements whenever possible; for the tank crossing a trench, foreground and tank passes were photographed separately and combined, with digital corrections where necessary. Current locked sources therefore support a practical/digital integration model, not a claim of zero CGI and not an invented complete VFX shot ledger. Editor Sven Budelmann describes an editorial goal of documentary-like realism and observational distance rather than action-film triumphalism. The first ten to fifteen minutes establish a tonal contract combining beauty and violence; later rhythm remains controlled instead of escalating through conventional heroic montage. Budelmann also describes collaboration with composer Volker Bertelmann after a strong early cut existed. Bertelmann's raw harmonium-centered score was developed against a soundtrack already rich with machine, cloth, breath, mud and weapon textures. Kruse describes tuning and reshaping sound-design elements when they conflicted with Bertelmann's material, making score and effects complementary rather than redundant. The case therefore treats editorial, sound and music as an iterative relationship rather than three sealed departments. The award record is historically significant: BAFTA documents seven wins including Best Film, Director, Cinematography, Original Score and Sound. Those awards justify priority and reception context only; workflow claims remain tied to ARRI, Netflix, direct craft interviews and production-facing trade documentation. Current locked sources do not establish a single audited final negative cost, complete financing waterfall, exact total shooting-day count, exhaustive crew census, full camera serial/body allocation, every lens-to-shot mapping, complete lighting and grip inventory, complete stunt/special-effects safety paperwork, full costume-piece census beyond documented examples, full makeup/prosthetic ledger, complete VFX vendor/shot ledger, complete edit-system/version history, exact full production-sound channel map for every scene, complete ADR/Foley/premix/stem architecture, full score-session ledger or distribution recoupment. Those remain explicit unresolved boundaries.",
    requiredChoicesSeed: {
      screenplay: ["award_priority_not_workflow_evidence", "remarque_adaptation", "bbfc_147_cinema_runtime_boundary", "vod_runtime_variance", "budget_finance_unresolved"],
      camera: ["alexa_65_principal", "alexa_mini_lf", "dna_lenses", "prime_65_s", "arri_rental_prague", "hexatron_all_terrain_crane", "large_format_confined_trenches", "orbiter_skypanel", "physical_battlefield_geography"],
      editing: ["sven_budelmann_documentary_realism", "first_ten_fifteen_minutes_tonal_contract", "observational_distance", "score_after_strong_early_cut", "sound_music_complementarity", "edit_system_unresolved"],
      sound: ["viktor_prasil_production_sound", "preplanned_wild_tracks", "forty_gb_audio_material", "helmet_radio_mics", "rubber_soled_boot_solution", "subjective_battlefield_sound", "production_sound_as_base_layer", "full_sound_chain_unresolved"],
      themes: ["film_history", "2022", "all_quiet_on_the_western_front", "bafta_best_film", "german_cinema", "czech_location_production", "large_scale_physical_production", "practical_digital_integration", "chapter19"]
    },
    learningGoals: [
      "Explain why the 2023 BAFTA Best Film win justifies award-priority selection without proving production workflow.",
      "Identify Edward Berger as director and separate award evidence from craft testimony.",
      "Preserve the BBFC 147m15s cinema version and later 148m48s VOD version as a documented version boundary.",
      "Use 147 minutes as the rounded playable cinema runtime without erasing the VOD variance.",
      "Identify James Friend ASC BSC as cinematographer.",
      "Identify ALEXA 65 as a principal documented camera system.",
      "Identify ALEXA Mini LF as the second documented principal camera system.",
      "Identify DNA lenses in the documented package.",
      "Identify Prime 65 S lenses in the documented package.",
      "Explain ARRI Rental Prague as part of the camera, lighting and grip support system.",
      "Identify ARRI Orbiter and SkyPanel as documented lighting tools without inventing a complete lighting ledger.",
      "Explain why Friend used large format inside trenches rather than only for distant vistas.",
      "Identify HEXATRON as an all-terrain camera-positioning tool used by the production.",
      "Explain the battlefield as a camera-support and movement problem, not only a production-design backdrop.",
      "Identify Christian Goldbeck as production designer.",
      "Explain the roughly two-month battlefield/trench layout planning documented by Netflix.",
      "Explain trench spacing and scene geography as preproduction decisions tied to later blocking and camera movement.",
      "Explain why shell holes, mud, weather and practical effects had to be coordinated with physical geography.",
      "Explain performer bootcamp as production preparation rather than promotional trivia.",
      "Preserve the roughly 15-kilogram documented burden of uniform and weapons as a performance/stunt constraint.",
      "Explain how large groups of extras change safety, blocking, costume and camera logistics.",
      "Identify Lisy Christl as costume designer.",
      "Preserve the roughly twenty Paul-uniform states documented by Netflix.",
      "Preserve the roughly 800-to-900 extra costumes as a scale indicator rather than a complete wardrobe census.",
      "Explain costume distress as chronology and continuity control.",
      "Identify Heike Merker as makeup and hair department head in the locked craft record.",
      "Explain scene-by-scene mud, blood, cold and injury breakdowns as makeup continuity.",
      "Reject a single generic 'mud look' as an adequate description of the makeup process.",
      "Explain why physical distress continuity must agree with editorial chronology.",
      "Identify Viktor Prasil as production sound mixer.",
      "Explain why sound planning began before photography because battlefield material would be hard to recreate later.",
      "Identify Aaton Cantar X3 among the documented production sound recorders.",
      "Identify Sound Devices 688 and MixPre-10 II among the documented production sound recorders.",
      "Identify DPA 6061/4061 lavaliers as documented body microphones.",
      "Identify Schoeps and Sennheiser microphones as documented boom/effects tools without inventing per-shot assignments.",
      "Explain radio microphones inside helmets as a response to battlefield dialogue constraints.",
      "Explain the rubber-soled boot solution as acoustic problem-solving during production.",
      "Explain portable sound absorption and rain-control measures as part of production sound preparation.",
      "Preserve the more-than-40-GB edited audio record as a documented sound-material scale marker.",
      "Preserve Kruse's eight-plus-hours wild-track description as overlapping evidence rather than forcing an exact conversion to the 40-GB figure.",
      "Explain wild tracks of crowds, vehicles, weapons and battlefield action as production assets for post.",
      "Identify Frank Kruse as supervising sound editor/sound designer in the locked record.",
      "Identify Markus Stemler as sound designer.",
      "Explain subjective sound as alignment with Paul's experience rather than a rejection of research.",
      "Explain why tank sound combined production recordings with designed metal weight and resonance.",
      "Explain original uniforms in Foley as a material bridge between production and post.",
      "Explain production sound as a base layer rather than material automatically replaced in post.",
      "Identify Frank Petzold as production VFX supervisor in the locked source record.",
      "Explain background aircraft as a documented example of digital augmentation.",
      "Explain the tank-over-trench shot as photographed foreground/tank passes combined with digital corrections.",
      "Reject both 'everything was practical' and 'the battlefield was mostly CGI' as unsupported absolutes.",
      "Keep the complete VFX vendor and shot ledger unresolved.",
      "Identify Sven Budelmann as editor.",
      "Explain documentary-like realism and observational distance as editorial goals.",
      "Explain the first ten-to-fifteen minutes as the film's tonal contract in Budelmann's account.",
      "Explain why the later edit does not simply accelerate into conventional heroic war montage.",
      "Identify Volker Bertelmann as composer.",
      "Explain the score's raw harmonium-centered language as part of the film's industrial war-machine texture.",
      "Explain sound-design retuning around the score as evidence of an iterative mix between music and effects.",
      "Keep audited budget, financing waterfall, exact shoot-day total and exhaustive crew census unresolved.",
      "Keep full camera serial allocation, lens-to-shot map and complete lighting/grip package unresolved.",
      "Keep full stunt, special-effects, costume, makeup and prosthetic ledgers unresolved beyond documented examples.",
      "Keep complete edit software/version history, ADR/Foley/premix/stem routing and score-session ledger unresolved.",
      "Close the case only when award priority, version boundary, large-format capture, battlefield geography, performance/costume continuity, sound, VFX, edit and music evidence agree."
    ],
    phases: [
      { id: "award_priority", label: "Lock BAFTA Best Film priority", player_task: "Use the 2023 BAFTA Best Film win to justify case order while keeping award evidence separate from production method." },
      { id: "evidence_hierarchy", label: "Map the evidence hierarchy", player_task: "Separate BAFTA and BBFC institutional records from ARRI, Netflix and direct craft testimony." },
      { id: "runtime_boundary", label: "Freeze the cinema runtime", player_task: "Use the 147-minute cinema version while preserving the later VOD runtime variance." },
      { id: "finance_boundary", label: "Freeze unresolved finance", player_task: "Do not invent a final negative cost, financing waterfall or recoupment model." },
      { id: "large_format_package", label: "Build the large-format package", player_task: "Combine ALEXA 65 and ALEXA Mini LF with the documented DNA and Prime 65 S lens families." },
      { id: "confined_large_format", label: "Move large format into trenches", player_task: "Use ALEXA 65 proximity and movement inside confined trenches rather than reserving it for vistas." },
      { id: "camera_support", label: "Engineer battlefield camera support", player_task: "Use ARRI Rental and HEXATRON support to move heavy imaging systems through difficult terrain." },
      { id: "lighting_support", label: "Map documented ARRI lighting", player_task: "Use Orbiter and SkyPanel evidence without pretending the complete lighting plot is known." },
      { id: "battlefield_layout", label: "Design the battlefield geography", player_task: "Treat trench layout, spacing and shell-hole geography as preproduction systems for blocking and camera movement." },
      { id: "mud_weather", label: "Plan mud and weather interaction", player_task: "Coordinate ground conditions, performers, camera access and effects instead of treating mud as surface decoration." },
      { id: "bootcamp", label: "Prepare battlefield performance", player_task: "Train performers to move, fall and handle weapons under realistic costume and gear loads." },
      { id: "extras", label: "Scale the battlefield population", player_task: "Coordinate hundreds of extras across blocking, costume, safety and sound needs." },
      { id: "costume_states", label: "Track costume chronology", player_task: "Manage multiple distress states for Paul and large quantities of extra costumes as continuity data." },
      { id: "makeup_states", label: "Track physical deterioration", player_task: "Break mud, blood, wounds, cold and exhaustion down scene by scene." },
      { id: "sound_preproduction", label: "Plan sound before the shoot", player_task: "Identify battlefield sounds that must be captured during photography because later recreation would be limited." },
      { id: "production_recorders", label: "Build the production sound kit", player_task: "Use the documented recorder and microphone families without inventing a channel-by-channel scene ledger." },
      { id: "helmet_mics", label: "Protect dialogue in helmets", player_task: "Use embedded radio microphones to preserve close character sound amid battlefield action." },
      { id: "boot_noise", label: "Control metal boot noise", player_task: "Apply the rubber-sole workaround while preserving the visible period costume." },
      { id: "wild_tracks", label: "Capture irreplaceable wild tracks", player_task: "Record crowds, vehicles, weapons, tanks and flamethrowers while the physical production exists." },
      { id: "sound_handoff", label: "Hand production sound into post", player_task: "Treat the large wild-track library as a core post-production resource rather than scratch reference." },
      { id: "subjective_sound", label: "Design Paul's battlefield perspective", player_task: "Balance research and emotional subjectivity instead of pursuing literalism at the expense of viewpoint." },
      { id: "tank_sound", label: "Give tanks psychological weight", player_task: "Combine production recordings with designed metal resonance and mass." },
      { id: "foley_materials", label: "Carry production materials into Foley", player_task: "Use original uniforms and material references to preserve tactile continuity." },
      { id: "practical_effects", label: "Preserve photographed battlefield effects", player_task: "Capture as much physical action and atmospheric interaction as feasible before digital augmentation." },
      { id: "vfx_integration", label: "Integrate selective VFX", player_task: "Use background extensions, A/B plates and corrections without inventing a total VFX ledger." },
      { id: "tank_plate", label: "Build the trench-crossing composite", player_task: "Combine photographed foreground and tank passes and reserve digital work for necessary integration/correction." },
      { id: "editorial_tone", label: "Establish the editorial contract", player_task: "Use the opening ten-to-fifteen minutes to define documentary-like distance, beauty and violence." },
      { id: "observational_editing", label: "Protect observational distance", player_task: "Avoid turning battle coverage into triumphal action grammar when the production thesis is anti-war." },
      { id: "score_entry", label: "Bring score into the developed cut", player_task: "Let Bertelmann respond to an already articulated picture-and-sound world." },
      { id: "sound_music_balance", label: "Separate sound and music functions", player_task: "Retune or remove overlapping material so effects and harmonium do not duplicate the same dramatic job." },
      { id: "uncertainty_audit", label: "Audit unresolved ledgers", player_task: "Keep unsupported budget, scheduling, camera-allocation, stunt, VFX, edit-system and sound-routing details outside canonical truth." },
      { id: "production_verification", label: "Close Production Verification", player_task: "Close only when award priority, runtime version, large-format capture, battlefield construction, continuity, sound, VFX, edit, music and uncertainty boundaries agree." }
    ]
  }
] as const;

export function mergeChapterNineteenAllQuietOnTheWesternFrontExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterNineteenAllQuietOnTheWesternFrontExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_nineteen_all_quiet_on_the_western_front_verified",
      source: { list_id: "manual_chapter_nineteen_all_quiet_on_the_western_front_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
