import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterEighteenOldboyExpansionDefinitions = [
  {
    id: "scenario_oldboy_2003",
    title: "Oldboy",
    originalTitle: "Oldeuboi",
    year: 2003,
    titleType: "Movie",
    runtimeMins: 119,
    directors: ["Park Chan-wook"],
    genres: ["Thriller"],
    sourceId: "cannes_oldboy_2003",
    sourceUrl: "https://www.festival-cannes.com/en/f/old-boy/",
    scenarioType: "south_korea_photochemical_negative_bleach_bypass_storyboarded_action_corridor_long_take_production_design_sound_post_2003",
    premise: "Build Oldboy as Chapter 18's next P1 Production Case by treating its celebrated style as a coordinated 2003 production system rather than as a collection of later-famous images. Festival de Cannes records Old Boy as a South Korean 2003 production running 119 minutes, directed by Park Chan-wook, written by Hwang Jo-yoon, Im Joon-hyung and Park, photographed by Chung Chung-hoon, designed by Seong-Hee Yoo, scored under Cho Young-wuk and edited by Kim Sang-bum. The Korean Film Council record gives a 120-minute running time, a Korean release date of 21 November 2003, Eggfilm and ShowEast as production companies, Cineclick Asia as international sales and no co-production flag. BFI Southbank programme notes for the remastered exhibition list 121 minutes. Those three runtimes are not normalized into one invented master: the playable case uses the Cannes 119-minute festival record as its runtime field while preserving 120 minutes as the KOFIC release-database value and 121 minutes as a later BFI remastered exhibition value. BFI's compiled credits also expand the working crew beyond the festival card: Kim Sang-bum and Kim Jae-bum are listed as editors, Park Hyun-won for lighting, Ryu/Yoo Seong-hie for art direction, Cho Sang-kyung for costumes, Son Chong-hee for make-up/hair, Lee Yong-gi for colour timing, Koala Production for opticals, Lee Sung-jin for sound design, Lee Seong-chul as sound supervisor, Lee Sang-wook as production sound mixer, Lee Eun-joo as boom operator, Han Myung-hwan for sound editing and ADR, Park Joon-oh for sound effects supervision and Foley, Song Yoon-jae for sound effects and Foley recording, and Yang Gil-young as martial-arts director. The corridor fight must be taught as a production decision with a traceable pre-production pivot. In a 2005 LA Weekly interview, Park says his original storyboards contained almost one hundred shots and an X-ray-style homage; during production he saw that the long master shot created for later editing was beautiful and chose to build the sequence around it instead. He says the production shot the long take seventeen times over three days, and that Choi Min-sik's visible exhaustion was real rather than merely performed. Park's Sight and Sound account adds the creative boundary: he abandoned the planned X-ray trick and other references, kept the fight in a single take, gave the fighters long sticks with a medieval-battle association, and wanted the violence to feel brutal, repetitive and even a little boring rather than like a detachable dance number. This does not mean Oldboy is generally an unedited film. Park separately praises abrupt, visible cutting elsewhere in the picture, so the Production Case must contrast the corridor's sustained take with sequences in which editorial discontinuity is an authored effect. The same source-first discipline applies to production design. Park describes the private prison as deliberately hotel-like: thick blankets and fancy wallpaper can become more claustrophobic than bare bars, while Woo-jin's penthouse uses exposed concrete and water to create an intentionally cold high-tower environment. Production designer Ryu Seong-hie's later interview explains that Oldboy required balancing realism and fantasy, that the team was operating under meaningful budget pressure, and that the penthouse's unfamiliar stone surfaces, minimal furniture, long narrow water feature and green light emerged partly because conventional luxury dressing was financially out of reach. The design should therefore be modeled as creative problem-solving under resource limits, not as evidence that the production had unlimited art-department money. Image finishing is equally specific. In his 20th-anniversary RogerEbert.com interview, Park says Oldboy was developed using physical bleach bypass on the film negatives rather than a present-day digital color correction workflow; he describes the resulting image as grainy, high-contrast and low-saturation, and says bold primary colors were tested in pre-production so that bleach bypass would transform them into strange, unfamiliar tones rather than wash them into unintended monotony. This establishes a photochemical negative and a tested bleach-bypass look, but it does not by itself establish the exact camera body, lens set, stock number, laboratory, exposure index or printing-light values, so those remain unknown unless a source separately proves them. The sound and music model is unusually well documented for a Chapter 18 case. BFI credits production sound, boom, ADR, Foley, sound effects, sound design and supervision as distinct functions, while KOFIC's feature on Korean film music explains Cho Young-wuk's role as a music director working with multiple composers and describes Oldboy's score as combining electronic material, synths and strings. The player should therefore keep production sound, editorial sound, ADR, Foley, effects and score as separate pipelines instead of collapsing everything into 'sound design'. The existence of New Zealand line-production and art-direction credits is preserved as evidence of an additional unit, but the exercise does not assign specific scenes to that unit unless a source establishes them. Visual effects and special-effects departments are also credited, so the corridor long take is not used to infer that the entire film or even every element inside that shot was effect-free. The case ultimately asks the player to carry a scene from script and storyboard through art direction, lighting, stunt choreography, camera movement, sustained performance, production sound, editorial strategy, photochemical finishing and music while keeping festival runtime, domestic release runtime, remastered exhibition runtime, later reputation and production evidence in separate provenance layers.",
    requiredChoicesSeed: {
      screenplay: ["revenge_information_structure", "manga_adaptation_boundary", "flashback_ambiguity", "red_herring_design", "violence_consequence", "runtime_version_boundary"],
      camera: ["photochemical_negative_origin", "bleach_bypass_tests", "corridor_master_take", "storyboard_to_long_take_pivot", "camera_movement_choreography", "lighting_department_boundary", "unknown_camera_stock_boundary"],
      editing: ["single_take_exception", "abrupt_visible_cutting", "flashback_transition", "coverage_master_boundary", "location_editing_handoff", "opticals_boundary", "runtime_versioning"],
      sound: ["production_sound_mixer", "boom_operation", "sound_editing", "adr_pipeline", "foley_pipeline", "sound_effects_supervision", "music_supervision_multi_composer"],
      themes: ["film_history", "2003", "oldboy", "oldeuboi", "park_chan_wook", "chung_chung_hoon", "ryu_seong_hie", "kim_sang_bum", "cho_young_wuk", "south_korea", "showeast", "eggfilm", "cineclick_asia", "119_minutes_cannes", "120_minutes_kofic", "121_minutes_bfi_remaster", "corridor_long_take", "seventeen_takes", "three_day_corridor", "storyboards", "stunt_choreography", "martial_arts_direction", "production_design", "bleach_bypass", "film_negative", "photochemical_finishing", "sound_post", "adr", "foley", "new_zealand_unit"],
    },
    learningGoals: [
      "Explain Oldboy as a coordinated 2003 production system rather than as a bundle of iconic scenes.",
      "Identify Park Chan-wook as director and co-screenwriter from the Cannes record.",
      "Identify Hwang Jo-yoon and Im Joon-hyung as the other Cannes-credited screenwriters.",
      "Identify Chung Chung-hoon as cinematographer and Kim Sang-bum as a Cannes-credited editor.",
      "Connect Seong-Hee Yoo in the Cannes record with the production designer commonly romanized as Ryu Seong-hie without treating romanization variance as two people.",
      "Preserve Cannes 119 minutes, KOFIC 120 minutes and BFI remastered 121 minutes as separate version or exhibition records.",
      "Use 119 minutes as the playable festival-runtime anchor without claiming it is the only valid duration.",
      "Record KOFIC's 21 November 2003 South Korean release date separately from the 2004 Cannes competition appearance.",
      "Identify Eggfilm and ShowEast as KOFIC-listed production companies and Cineclick Asia as international sales.",
      "Keep KOFIC's no-co-production flag separate from later international distribution and festival circulation.",
      "Explain how a manga source can inform adaptation history without letting the Production Case invent undocumented draft-by-draft changes.",
      "Explain Park's use of flashback ambiguity as a directing and editorial strategy rather than a claim that every remembered event is unreliable.",
      "Explain how red herrings can be planted structurally when an audience is expected to solve a mystery while watching.",
      "Record that the corridor fight was initially storyboarded as almost one hundred shots.",
      "Explain the corridor long master as material originally available for later editing before Park chose to keep the sustained take.",
      "Record Park's statement that the corridor take was shot seventeen times over three days.",
      "Treat Choi Min-sik's visible corridor exhaustion as documented production reality while avoiding unsafe claims about injury or medical risk.",
      "Explain why one sustained action take increases dependence on choreography, performer endurance, focus, lighting, camera movement and background timing.",
      "Keep martial-arts direction by Yang Gil-young distinct from Park's directing and Chung's cinematography responsibilities.",
      "Explain how the long sticks and distant side-on presentation make the fight read as attritional battle rather than polished dance.",
      "Reject the inference that the corridor's single take means Oldboy generally avoids editing.",
      "Explain Park's preference for abrupt visible cuts elsewhere as an authored contrast with the corridor sequence.",
      "Distinguish master-shot coverage, editorial coverage and the final decision to retain a long take.",
      "Explain how hotel-like blankets and wallpaper can make the prison set more claustrophobic than conventional bars.",
      "Explain the penthouse's exposed concrete and water as authored production-design motifs rather than documentary evidence of a real wealthy residence.",
      "Use Ryu Seong-hie's budget account to explain how stone, minimal furniture, a narrow water feature and green light emerged through resource-constrained design.",
      "Separate production-design ambition from production budget size.",
      "Identify Cho Sang-kyung's costume credit and Son Chong-hee's make-up/hair credit without inventing undocumented fabrication workflows.",
      "Explain that BFI's New Zealand crew credits establish an additional production unit but not, by themselves, the exact scenes photographed there.",
      "Identify Park Hyun-won's lighting credit and keep it separate from unsupported claims about fixture packages or lighting ratios.",
      "Explain Park's statement that Oldboy used physical bleach bypass on film negatives.",
      "Explain how bleach-bypass tests in pre-production let bold primary colors be chosen for the way they would transform photochemically.",
      "Describe the documented bleach-bypass result as grainy, high-contrast and low-saturation without converting those adjectives into invented sensitometric measurements.",
      "Distinguish photochemical color timing and optical work from present-day digital remastering.",
      "Keep exact camera body, lens set, stock number, laboratory, exposure index and printer-light data unknown unless directly sourced.",
      "Explain why a photochemical negative workflow does not mean every effect in the finished film was practical.",
      "Keep credited visual-effects and special-effects departments visible even when a sequence is famous for in-camera choreography.",
      "Identify Lee Sang-wook as production sound mixer and Lee Eun-joo as boom operator from BFI's compiled credits.",
      "Identify Lee Sung-jin as sound designer and Lee Seong-chul as sound supervisor.",
      "Identify Han Myung-hwan's sound-editing and ADR roles and Park Joon-oh's sound-effects/Foley roles.",
      "Explain production sound, ADR, Foley, sound effects and sound design as separate handoffs rather than synonyms.",
      "Explain Cho Young-wuk's music-supervision model as distinct from the composers who created specific musical material.",
      "Record KOFIC's description of electronic, synth and string elements without pretending that every cue uses all three.",
      "Separate score production from sound-effects and dialogue pipelines.",
      "Explain how visible production choices can become later stylistic signatures without using later influence as evidence for how they were originally made.",
      "Separate the 2004 Cannes Grand Prix and later canonical reputation from 2003 production evidence.",
      "Reject claims that Oldboy invented corridor long takes, bleach bypass, revenge cinema, stylized Korean genre filmmaking or manga adaptation.",
      "Audit every claim about camera, lens, stock, lab, budget, schedule, VFX technique, stunt safety, sound equipment and location against a title-specific source before promoting it to production fact.",
    ],
    phases: [
      { id: "evidence_hierarchy", label: "Map the evidence hierarchy", player_task: "Separate Cannes metadata, KOFIC release/production records, BFI compiled credits, Park interviews, Ryu Seong-hie's design testimony and later remaster discussion before turning any detail into production fact." },
      { id: "runtime_versions", label: "Lock runtime provenance", player_task: "Record Cannes 119, KOFIC 120 and BFI remastered 121 minutes as separate records and choose 119 only as the canonical playable anchor." },
      { id: "production_company_map", label: "Map production ownership", player_task: "Keep Eggfilm, ShowEast, Cineclick Asia, producers, domestic release and international sales in separate institutional fields." },
      { id: "screenplay_authorship", label: "Map screenplay authorship", player_task: "Preserve Hwang Jo-yoon, Im Joon-hyung and Park Chan-wook as screenplay credits before discussing adaptation choices." },
      { id: "adaptation_boundary", label: "Protect the adaptation boundary", player_task: "Use the manga source as historical context without inventing undocumented draft changes or attributing every film idea to the manga." },
      { id: "flashback_design", label: "Design flashback ambiguity", player_task: "Plan remembered scenes so their subjectivity is legible without turning ambiguity into continuity confusion." },
      { id: "red_herring_map", label: "Plant red herrings", player_task: "Map what the audience is allowed to suspect at each stage while preserving the eventual causal reveal." },
      { id: "corridor_storyboard", label: "Audit the corridor storyboard", player_task: "Start from Park's almost-one-hundred-shot storyboard plan and identify what coverage the production expected before the long-take pivot." },
      { id: "corridor_master", label: "Evaluate the long master", player_task: "Treat the sustained corridor master as edit-capable coverage first, then justify the production decision to retain it as the sequence." },
      { id: "corridor_rehearsal", label: "Rehearse corridor choreography", player_task: "Coordinate performer marks, stunt beats, camera travel, prop weapons, focus and reset requirements before attempting the take." },
      { id: "corridor_endurance", label: "Plan performer endurance", player_task: "Use the documented seventeen takes over three days to build rest and reset logic without inventing injuries or unsafe working conditions." },
      { id: "martial_arts_handoff", label: "Map martial-arts direction", player_task: "Give Yang Gil-young's choreography role its own responsibility boundary beside director, cinematographer and performers." },
      { id: "single_take_exception", label: "Protect the single-take exception", player_task: "Keep the corridor's unbroken structure from becoming a false rule that the rest of Oldboy avoids cutting." },
      { id: "abrupt_editing", label: "Design visible cutting", player_task: "Build one non-corridor sequence where abrupt edits are intentionally legible rather than smoothed into generic continuity." },
      { id: "prison_design", label: "Build the hotel-prison", player_task: "Use blankets, wallpaper, repeated furniture and controlled spatial cues to create claustrophobia without defaulting to bars-and-concrete prison imagery." },
      { id: "penthouse_budget", label: "Solve the penthouse under constraint", player_task: "Model Ryu Seong-hie's budget problem and produce an unfamiliar wealthy space from stone, minimal furniture, water and light rather than expensive rented luxury dressing." },
      { id: "water_motif", label: "Coordinate water motifs", player_task: "Keep water features, mural imagery and story symbolism tied to art-direction decisions without confusing symbolism with production evidence." },
      { id: "costume_makeup", label: "Map costume and make-up", player_task: "Give costume, make-up/hair and special make-up separate deliverables while leaving unsourced fabrication specifics open." },
      { id: "lighting_department", label: "Map lighting responsibility", player_task: "Use Park Hyun-won's lighting credit as a real department boundary without inventing lamps, ratios or stock-specific exposure recipes." },
      { id: "bleach_bypass_tests", label: "Test bleach bypass", player_task: "Run pre-production color tests that model Park's documented concern that faint colors could collapse while bold primaries produce unfamiliar transformed tones." },
      { id: "negative_finish", label: "Protect the film-negative boundary", player_task: "Treat physical bleach bypass on film negatives as documented while keeping camera body, lenses, stock number and lab unknown." },
      { id: "colour_timing", label: "Map colour timing", player_task: "Place Lee Yong-gi's color-timing role after photography and distinguish it from modern digital remastering." },
      { id: "opticals_handoff", label: "Map opticals", player_task: "Keep Koala Production's optical work distinct from color timing and from unspecified visual-effects tasks." },
      { id: "vfx_sfx_boundary", label: "Separate VFX and special effects", player_task: "Use the credited visual-effects and special-effects teams without declaring any specific shot practical or digital unless a source proves it." },
      { id: "production_sound", label: "Capture production sound", player_task: "Map Lee Sang-wook and Lee Eun-joo's production-sound and boom responsibilities before dialogue moves into post." },
      { id: "sound_editing", label: "Edit the soundtrack", player_task: "Give Han Myung-hwan a sound-editing handoff that remains separate from ADR, Foley and final supervision." },
      { id: "adr_pipeline", label: "Plan ADR", player_task: "Treat ADR as a credited post-production process without inventing which lines were replaced or why." },
      { id: "foley_pipeline", label: "Build Foley", player_task: "Map Park Joon-oh and Song Yoon-jae's Foley roles and keep performed effects distinct from production sound and library effects." },
      { id: "sound_design_supervision", label: "Supervise sound design", player_task: "Coordinate Lee Sung-jin's sound design with Lee Seong-chul's supervision without collapsing department roles." },
      { id: "music_supervision", label: "Map the score pipeline", player_task: "Model Cho Young-wuk as music supervisor/director working with multiple composers and keep electronic, synth and string materials cue-specific." },
      { id: "new_zealand_unit", label: "Register the New Zealand unit", player_task: "Record BFI's New Zealand line-production, unit-management and art-direction credits without assigning unsourced scenes to the unit." },
      { id: "version_exhibition_boundary", label: "Separate remaster from original", player_task: "Keep the BFI 121-minute digital remaster and Park's remaster comments downstream from the original 2003 production record." },
      { id: "legacy_boundary", label: "Separate legacy from production", player_task: "Treat Cannes recognition and later hallway influence as reception history, not evidence that a production choice was technically unprecedented." },
      { id: "unknowns_register", label: "Register technical unknowns", player_task: "Keep exact camera body, lens set, film stock, lab, exposure index, printer lights, budget total, sound equipment and shot-specific VFX methods unknown unless separately sourced." },
    ],
  },
] as const;

export function mergeChapterEighteenOldboyExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterEighteenOldboyExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, "Old Boy", "Ol-deu Bo-ee"].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_eighteen_oldboy_verified",
      source: { list_id: "manual_chapter_eighteen_oldboy_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
