import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterEighteenPansLabyrinthExpansionDefinitions = [
  {
    id: "scenario_pans_labyrinth_2006",
    title: "Pan's Labyrinth",
    originalTitle: "El laberinto del fauno",
    aliases: ["El Laberinto del Fauno", "Pan's Labyrinth"],
    year: 2006,
    titleType: "Movie",
    runtimeMins: 112,
    directors: ["Guillermo del Toro"],
    genres: ["Drama", "Fantasy", "War"],
    sourceId: "bfi_pans_labyrinth_2006",
    sourceUrl: "https://www.bfi.org.uk/film/80a5c68c-6519-56a5-b38c-0d246f6e278b/pans-labyrinth",
    scenarioType: "spain_mexico_usa_35mm_day_for_night_practical_creature_makeup_animatronics_selective_vfx_2k_di_production_design_2006",
    premise: "Build Pan's Labyrinth as a source-first Chapter 18 Production Case about a 2006 Spain/Mexico/USA production whose fantasy and historical worlds were coordinated through 35mm cinematography, deliberately opposed production-design geometries, practical creature makeup and animatronics, selective digital intervention, sound design and a 2K digital intermediate rather than through one monolithic fantasy-effects pipeline. BFI and AFI record Guillermo del Toro as writer-director, Guillermo Navarro as cinematographer, Eugenio Caballero as production designer, Bernat Vilaplana as editor, Javier Navarrete as composer, and a 112-minute runtime; AFI also preserves Tequila Gang, Esperanto Filmoj and Estudios Picasso as production companies. American Cinematographer's title-specific 'Fear and Fantasy' account documents Navarro's use of his Moviecam Compact and an Arriflex 435 ES with Zeiss Ultra Prime and Variable Prime lenses, Kodak Vision2 200T 5217, Vision2 500T 5218 and Vision 250D 5246 stocks, extensive day-for-night work, intentional three-to-four-stop underexposure in selected situations, and a lighting strategy that often relied on bounced light or small sources hidden through set walls. Those details are treated as shot- and condition-specific tools, not a claim that every exterior was day-for-night, every shot was underexposed by the same amount or every set used the same lens. Eugenio Caballero's production-design testimony describes a strict shape grammar: the authoritarian real world favors straight lines, angles and overscaled furniture that diminishes Ofelia, while the fantasy world uses curves and organic forms. Caballero also describes practical construction constraints, including the Pale Man dining-room fireplace problem, the decision to use a pine forest whose visual aggression changed the scripted landscape, and artificial moss added because the chosen pines did not naturally provide the desired mossy texture. Guillermo del Toro's DGA account preserves the production philosophy that physical sets and actor-facing practical reality should be used wherever possible, with CG reserved for problems better solved digitally rather than treated as the default. Doug Jones' production interviews and DDT Efectos Especiales/SFX reporting establish the creature-performance boundary: the Faun and Pale Man existed as demanding physical makeup/costume performances, with long application times and restricted visibility/mobility, while selected lower-leg removals and other enhancements were completed digitally. CafeFX visual-effects supervisor Everett Burrell describes a roughly five-month collaboration in Madrid and a workflow built around detailed del Toro storyboards, practical photography and selective digital extension rather than replacing the production wholesale. The finished film therefore belongs to digital convergence not because it abandoned photochemical production, but because 35mm negative, practical sets, prosthetic creatures, animatronics, compositing and a 2K DI are interdependent. The player must coordinate one sequence from evidence hierarchy, historical/fantasy design rules and physical set access through film-stock choice, day-for-night or stage lighting, creature performance, production sound, editing, VFX cleanup/enhancement, DI finishing and exhibition while keeping awards, later restoration changes, universal lens claims, unsupported shot counts and speculative creature mechanics outside the production-fact layer.",
    requiredChoicesSeed: {
      screenplay: ["historical_fantasy_duality", "fascism_boundary", "fairytale_tasks", "ambiguity_without_solution", "runtime_version_boundary", "storyboard_previsualization"],
      camera: ["35mm_negative", "moviecam_compact", "arriflex_435_es", "ultra_prime_variable_prime", "kodak_5217_5218_5246", "day_for_night", "selective_underexposure", "bounce_light", "hidden_set_sources", "2k_di_boundary"],
      editing: ["parallel_world_contamination", "performance_effects_handoff", "vfx_cleanup_boundary", "fantasy_reality_match", "runtime_versioning", "storyboard_to_cut"],
      sound: ["production_sound", "creature_vocal_layer", "supervising_sound_design", "foley_effects", "music_boundary", "re_recording_boundary"],
      themes: ["film_history", "2006", "pans_labyrinth", "el_laberinto_del_fauno", "guillermo_del_toro", "guillermo_navarro", "spain", "mexico", "usa", "35mm", "moviecam_compact", "arriflex_435_es", "ultra_prime", "variable_prime", "kodak_5217", "kodak_5218", "kodak_5246", "day_for_night", "eugenio_caballero", "ddt_efectos_especiales", "cafefx", "practical_creatures", "selective_cg", "2k_di"],
    },
    learningGoals: [
      "Explain Pan's Labyrinth as a 2006 production system rather than only as a dark-fantasy text.",
      "Identify Guillermo del Toro as writer-director from BFI and AFI records.",
      "Preserve BFI's Spain/Mexico/USA production geography without collapsing the film into one national industry.",
      "Use BFI and AFI's 112-minute record as the playable runtime anchor while keeping longer public runtime records as version provenance.",
      "Identify Tequila Gang, Esperanto Filmoj and Estudios Picasso as AFI-recorded production companies without treating them as interchangeable departments.",
      "Identify Guillermo Navarro as cinematographer, Eugenio Caballero as production designer and Bernat Vilaplana as editor from institutional records.",
      "Explain why the real and fantasy worlds were designed with distinct but increasingly contaminating visual systems.",
      "Describe Caballero's straight-line and angular grammar for authoritarian reality without claiming every real-world object is rectilinear.",
      "Describe the curved and organic fantasy-world grammar without treating curves as proof that a shot is objectively supernatural.",
      "Explain why overscaled furniture and architecture can make Ofelia physically smaller inside the frame.",
      "Record the pine-forest location decision and artificial moss solution as title-specific production-design interventions.",
      "Use the Pale Man fireplace problem to explain why a visually successful set can still fail if ventilation and practical operation are not solved.",
      "Identify Moviecam Compact and Arriflex 435 ES as American Cinematographer-documented camera bodies without claiming equal use in every sequence.",
      "Identify Zeiss Ultra Prime and Variable Prime lenses as documented lens families without inventing a shot-by-shot focal-length map.",
      "Identify Kodak Vision2 200T 5217, Vision2 500T 5218 and Vision 250D 5246 as documented stocks.",
      "Explain why multiple film stocks are an exposure and look-management system rather than evidence of inconsistent cinematography.",
      "Explain the title-specific use of day-for-night while rejecting the claim that every exterior night was photographed that way.",
      "Record intentional three-to-four-stop underexposure as a selected American Cinematographer-documented strategy rather than a universal exposure recipe.",
      "Explain how retaining sunlight-like qualities inside day-for-night can create an uncanny rather than strictly naturalistic night.",
      "Explain why awkward fantasy-set geometry forced lighting positions to be designed with construction and camera access in mind.",
      "Describe bounced light as a major strategy without claiming that all illumination was indirect.",
      "Describe small sources hidden through set walls as a practical solution without inventing undocumented fixture models or wattages.",
      "Separate capture on 35mm negative from the later 2K digital intermediate.",
      "Reject the inference that a 2K DI means principal photography was digital.",
      "Explain del Toro's set-oriented practical-effects preference as a production philosophy rather than a ban on CG.",
      "Identify Doug Jones' Faun and Pale Man work as physical creature performances requiring prosthetic/costume endurance.",
      "Explain how five- or six-hour makeup transformations affect call times, actor stamina and shooting-day design.",
      "Keep practical makeup, animatronic facial movement and performer body language as separate but synchronized departments.",
      "Explain that selected lower-leg or body corrections could be digital without making the full creature synthetic.",
      "Identify DDT Efectos Especiales as a central creature/makeup-effects collaborator without assigning unsupported tasks to individual artists.",
      "Identify CafeFX as a major visual-effects collaborator and production partner from title-specific VFX reporting.",
      "Record the roughly five-month Madrid VFX collaboration without converting that duration into the entire film's post-production schedule.",
      "Explain why detailed del Toro storyboards could coordinate practical photography and VFX handoffs without eliminating on-set problem solving.",
      "Keep CafeFX's work separate from practical creature effects and from other effects vendors unless a source explicitly joins their responsibilities.",
      "Explain why selective digital enhancement can preserve the physical reality actors experienced on set.",
      "Identify Javier Navarrete as composer while keeping score, production sound, sound design, effects editing and re-recording as separate layers.",
      "Treat creature vocals and designed effects as authored sound work rather than evidence that creature performance was generated in post.",
      "Explain how offscreen sound can connect the historical and fantasy spaces without requiring visual effects.",
      "Identify Bernat Vilaplana's editorial role and keep cutting decisions distinct from storyboard design, camera execution and VFX compositing.",
      "Explain how the two visual worlds can move toward each other through color, shape and cutting without asserting a single objectively correct interpretation of the fantasy.",
      "Separate the Academy Awards for cinematography, art direction and makeup from evidence about how the film was originally produced.",
      "Reject claims that Pan's Labyrinth invented practical creature work, day-for-night, digital intermediates, fairy-tale cinema or fantasy/historical crosscutting.",
      "Keep the 2016/2017-era home-video color changes separate from the 2006 theatrical production and 2K DI record.",
      "Audit every claim about exact camera serials, per-shot focal lengths, filter packages, shutter angles, laboratory scan settings, microphone/recorder models, total VFX shot count and final release-print details against title-specific evidence before promoting it to production fact.",
      "Explain why the film is historically useful as a digital-convergence case precisely because photochemical capture, practical fabrication, animatronics, digital cleanup/compositing and DI finishing coexist.",
      "Build a production plan that protects child-performer time, creature-makeup time, set access, effects handoffs and continuity without treating any one department as subordinate to spectacle.",
      "Distinguish production design's physical storytelling from cinematography's light/frame decisions while modeling the two as a coordinated visual system.",
      "Connect evidence uncertainty to production choices: when a source does not establish a technical parameter, keep it unknown rather than filling the gap with a plausible industry default.",
    ],
    phases: [
      { id: "evidence_hierarchy", label: "Map the evidence hierarchy", player_task: "Separate BFI/AFI credits, American Cinematographer craft reporting, del Toro/Caballero/Jones testimony and VFX trade reporting before converting details into production facts." },
      { id: "runtime_versions", label: "Lock runtime provenance", player_task: "Use the institutional 112-minute record as the playable anchor while retaining longer public runtimes as version provenance." },
      { id: "production_network", label: "Map the production network", player_task: "Separate Mexico/Spain/USA production companies, departments, creature shops and VFX vendors rather than flattening them into one unit." },
      { id: "world_design_rules", label: "Define the two visual worlds", player_task: "Write explicit shape, scale and texture rules for authoritarian reality and fantasy before sets or camera plans are finalized." },
      { id: "world_contamination", label: "Plan visual contamination", player_task: "Choose where color, geometry and rhythm begin crossing between worlds without resolving whether fantasy is objectively real." },
      { id: "forest_location", label: "Adapt the forest location", player_task: "Use the pine forest's vertical aggression and add only documented artificial moss interventions needed for the intended world." },
      { id: "set_scale", label: "Control scale around Ofelia", player_task: "Use overscaled furnishings and architecture selectively to make Ofelia feel constrained without turning every prop into a giant object." },
      { id: "pale_man_set", label: "Engineer the Pale Man room", player_task: "Coordinate curved architecture, camera access, practical fire and ventilation before approving the set for photography." },
      { id: "camera_package", label: "Map the 35mm camera package", player_task: "Track Moviecam Compact, Arriflex 435 ES, Ultra Prime and Variable Prime use while keeping unsupported body/lens pairings open." },
      { id: "stock_strategy", label: "Choose among the three stocks", player_task: "Assign 5217, 5218 or 5246 by documented exposure/look needs without inventing a universal stock per story world." },
      { id: "day_for_night", label: "Design day-for-night", player_task: "Choose when real daylight should be transformed into night and preserve the documented uncanny sunlight quality where dramatically useful." },
      { id: "underexposure_boundary", label: "Control underexposure", player_task: "Use the documented three-to-four-stop strategy only where justified and protect negative detail through tests rather than copying a blanket recipe." },
      { id: "fantasy_set_lighting", label: "Light awkward fantasy geometry", player_task: "Find bounce positions and concealed source paths that preserve curved sets without blocking actors or camera movement." },
      { id: "hidden_sources", label: "Integrate concealed lights", player_task: "Coordinate construction holes and hidden sources with art direction, electrics and safety while leaving undocumented fixture specifications unknown." },
      { id: "storyboard_handoff", label: "Translate storyboards to production", player_task: "Use del Toro's detailed boards as shared intent while allowing camera, effects and performance teams to solve physical constraints on set." },
      { id: "faun_makeup_call", label: "Schedule the Faun transformation", player_task: "Build call times around multi-hour prosthetic application, performer recovery and the limited number of productive hours after makeup is complete." },
      { id: "faun_performance", label: "Synchronize creature performance", player_task: "Coordinate Doug Jones' body and lower-face performance with practical facial mechanisms and later digital cleanup." },
      { id: "pale_man_makeup", label: "Stage the Pale Man", player_task: "Protect visibility, movement and safety constraints created by the eyeless head design and body prosthetics before choreographing action." },
      { id: "practical_cg_boundary", label: "Choose practical versus digital", player_task: "Keep the creature physically present for actors where possible and reserve digital work for cleanup, enhancement or motions better solved in post." },
      { id: "ddt_handoff", label: "Map creature-shop responsibility", player_task: "Separate sculpting, prosthetic application, animatronic operation and performer needs without inventing undocumented individual assignments." },
      { id: "cafefx_handoff", label: "Map the VFX vendor handoff", player_task: "Send storyboard intent, plates, practical-reference photography and cleanup requirements to CafeFX without assuming every fantasy shot is theirs." },
      { id: "vfx_plate_discipline", label: "Protect usable VFX plates", player_task: "Capture clean and reference material only where needed and keep practical interactive light/performance in the hero photography." },
      { id: "child_performer_plan", label: "Protect child-performer time", player_task: "Sequence coverage, creature work and reset-heavy effects so Ofelia's performance time is not consumed by avoidable technical delays." },
      { id: "production_sound", label: "Capture production sound", player_task: "Plan dialogue and movement recording around prosthetics, set machinery and practical effects while leaving unsupported hardware models unknown." },
      { id: "creature_sound", label: "Design creature sound", player_task: "Build vocal and effects layers that support the physical performance without erasing the timing established on set." },
      { id: "editing_worlds", label: "Cut between worlds", player_task: "Use Bernat Vilaplana's editorial layer to manage transitions, task structure and world contamination rather than relying on visual effects alone." },
      { id: "selective_cleanup", label: "Perform digital cleanup", player_task: "Remove or alter only documented practical limitations such as selected lower-leg geometry while preserving texture and contact from the plate." },
      { id: "compositing", label: "Composite fantasy elements", player_task: "Match grain, exposure, depth and motion to 35mm plates and avoid a generic clean-CG surface." },
      { id: "di_finish", label: "Finish the 2K DI", player_task: "Carry 35mm-origin material through the 2K digital intermediate while preserving capture provenance and keeping later home-video changes separate." },
      { id: "sound_post", label: "Build final sound post", player_task: "Keep dialogue, effects, Foley, creature layers, music and re-recording as inspectable handoffs rather than one undifferentiated soundtrack task." },
      { id: "version_boundary", label: "Separate production from later versions", player_task: "Keep awards, later color revisions, restorations and home-video mastering downstream from the 2006 production evidence." },
      { id: "unknowns_register", label: "Register technical unknowns", player_task: "Leave exact filters, shutter angles, per-shot lenses, laboratory scan settings, sound hardware, total VFX count and release-print details unknown unless a title-specific source establishes them." },
    ],
  },
] as const;

export function mergeChapterEighteenPansLabyrinthExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterEighteenPansLabyrinthExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_eighteen_pans_labyrinth_verified",
      source: { list_id: "manual_chapter_eighteen_pans_labyrinth_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}