import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterNineteenTheSubstanceExpansionDefinitions = [
  {
    id: "scenario_the_substance_2024",
    title: "The Substance",
    originalTitle: "The Substance",
    aliases: ["The Substance"],
    year: 2024,
    titleType: "Movie",
    runtimeMins: 140,
    directors: ["Coralie Fargeat"],
    genres: ["Drama", "Horror", "Science Fiction"],
    sourceId: "cannes_the_substance_2024",
    sourceUrl: "https://www.festival-cannes.com/en/f/the-substance/",
    scenarioType: "independent_low_mid_budget_coralie_fargeat_working_title_blacksmith_a_good_story_france_studio_production_practical_prosthetics_body_horror_pierre_olivier_persin_pop_fx_11_month_prep_15_person_team_silicone_foam_latex_puppets_noid_vfx_practical_digital_hybrid_benjamin_kracun_alexa_mini_lf_canon_k35_leitz_thalia_cooke_macro_arri_macro_softdrop_not_led_239_lux_lut_fluorescent_substance_lut_studios_depinay_long_shoot_performance_prosthetic_time_premiere_pro_300_hours_230_sequences_coralie_fargeat_jerome_eltabet_valentin_feron_raffertie_sound_music_blur_paris_post_2024",
    premise: "Build The Substance as Chapter 19's independent/low-to-mid-budget body-effects case by treating Coralie Fargeat's 2024 feature as a deliberately bespoke production system in which a long French studio shoot, performer-intensive prosthetic transformation, practical puppetry, selective creature VFX, spherical digital cinematography, extreme close-up design, sound-led editing and a late electronic score are coordinated around physical bodily impact. Festival de Cannes records a 140-minute 2024 feature produced across the United Kingdom, United States and France, written and directed by Coralie Fargeat, photographed by Benjamin Kracun, designed by Stanislas Reydellet, edited by Fargeat, Jerome Eltabet and Valentin Feron, scored by Raffertie and mixed/edited through a French sound team. The film's press kit identifies Working Title, Blacksmith and A Good Story as production companies and records Film France/CNC support through the French Tax Rebate for International Production. These records establish companies, territories and support structure, but current locked sources do not establish an audited final negative cost, exact financing percentages, department allocations, cashflow terms or recoupment waterfall. No circulating budget estimate is promoted to canonical fact. Fargeat describes the movie as a custom-built production that resisted ordinary manufacturing norms. She shot in France and completed post in Paris. Direct and craft reporting describes a shoot longer than 100 days; a later colorist account gives 111 shooting days. The case therefore treats the production as a long-duration shoot and preserves source/count-convention boundaries rather than turning one later count into an unsupported universal schedule ledger. The physical-effects system is the central production constraint. Special makeup effects designer Pierre-Olivier Persin says his roughly 15-person team worked for about 11 months with Fargeat. The production largely favored physical prosthetics, silicone work, suits and puppets so performers and camera could interact with transformations on set. That practical-first preference is not a no-CGI rule. Persin explains that the final Blob/Blub was built as a silicone puppet moved physically on set while Demi Moore's live facial performance was later integrated digitally; Noid Studio states that its artists produced more than 40 creature shots, combining practical and digital effects. The correct lesson is therefore practical-digital integration: VFX extends, replaces or recombines elements where physical methods reach performance, movement or compositing limits. Persin's Gollum stage also demonstrates performer/body-double modularity. He describes three physical implementations across Demi Moore, a very thin performer and a stunt double, with editing moving among them according to facial performance, body shape and action requirements. Monstro Elisasue required months of design exploration, including physical maquettes and digital design tools, before the final physical suit/creature workflow was chosen. Backstage reporting records silicone as a dominant material across the production while the large Monstro suit used foam latex, which created maintenance problems once saturated with the climax's large blood effects. Performer time is therefore a budget and scheduling variable even without a published total cost: some Demi Moore applications took many hours, and prosthetic durability, cleaning, drying, reset time, doubles and stunt continuity had to be scheduled around camera work. Cinematographer Benjamin Kracun BSC built the image system around seeing these effects very close rather than hiding them. He tested cameras and lenses at RVZ in Paris and abandoned an initial anamorphic idea because Fargeat's heavily storyboarded effects sequences depended on extreme proximity and close-up geometry. He chose an ARRI ALEXA Mini LF with vintage Canon K35 spherical lenses because skin rendition, falloff and the LF sensor supported a microscopic view of flesh while remaining natural enough for prosthetics. For exceptional proximity he used a Leitz Thalia 24mm capable of very close focus, a Cooke 90mm Macro, an ARRI Macro 200mm and diopters. The package is therefore a layered spherical/macro system, not one lens family used identically for every shot. The film's press kit records a 2.39:1 final aspect ratio and DCP/5.1 delivery. Kracun's lighting and background choices also reject a simple 'new technology is better' assumption. Elisabeth's apartment required a large panoramic exterior beyond the window. Kracun tested LED-screen logic but rejected it because cost, reflection behavior and hard-light interaction worked against the desired image; he chose a softdrop backdrop instead. The result is a contemporary studio film using a deliberately older physical background method where it better serves light and texture. The bathroom's clinically bright transformation environment mixed tungsten quality with LED flexibility because the production needed rapid night/day changes while still exposing veins, skin color and prosthetic detail. Complete fixture quantities, dimming networks, power distribution and lighting ratios remain unresolved. Color management was designed before photography because prosthetics, fluorescent liquid and saturated color could not be left to finishing alone. Kracun worked with Lux in Paris on a strong show LUT that cost significant effective exposure, and a separate LUT was created for the fluorescent Substance liquid because the prop only fluoresced under UV illumination. Later colorist Fabien Pascal describes Lux working with Fargeat and Kracun from testing through final grade, using on-set LUTs and metadata to preserve decisions. This is a preproduction-to-post color pipeline, not a generic 'fix it in DI' workflow. Production design and directing are organized as symbolic studio space rather than literal Los Angeles geography. Fargeat describes the setting as deliberately nonspecific and mental: corridors, bathroom, TV studio and apartment function as psychological spaces. American Cinematographer reports her desire to shoot at Studios d'Epinay and describes the film's Los Angeles as an imagined construction. This matters because controlled studio space supports prosthetic resets, repeated close-up choreography, blood effects, background control and the stylized perspective geometry central to the film. Current locked evidence does not establish a complete stage-by-stage occupancy calendar, full set-build drawings, exact square footage, scenic-material quantities or art-department costs. Fargeat's directing method is unusually previsualized but not reducible to storyboards alone. The effects sequences were heavily storyboarded, and she describes cutting key sequences herself during the shoot so she could test the intended sensory grammar before photography ended. Because the film has comparatively little dialogue, image duration, bodily sound, inserts and rhythmic repetition carry narrative functions that dialogue often carries in conventional drama. The editorial system therefore begins during photography. Cannes credits Fargeat, Jerome Eltabet and Valentin Feron as editors. Eltabet describes a four-handed exchange with Fargeat and an artisanal, experimental process in Adobe Premiere Pro; Adobe records more than 300 hours of footage across roughly 230 sequences. Eltabet organized selected takes and favorite moments directly in timelines, while Fargeat retained strong first-pass control over key transformation, fight and climax sequences. Later collaboration used fresh editorial eyes to control overall balance in a film whose near-silent stretches depend on precise image/sound duration. Fargeat describes the post process as highly iterative because early cuts lacked final sound and VFX, making it difficult for others to experience the intended film until layers returned. Post remained in Paris and extended for a long period; current locked reporting describes roughly a year and a half of editing/post iteration but does not provide a complete version count, storage architecture, assistant-editor staffing ledger, proxy/online specification or exact lock chronology. Sound is not downstream decoration. Cannes/press-kit records Emmanuelle Villard on production sound, Valerie Deloof and Victor Fleurant in sound editing and Stephane Thiebaut/Victor Praud in re-recording. Eltabet says sound design was fundamental to editing the largely dialogue-light movie, and Premiere Pro was used to shape temporary/working sound with picture. Composer Raffertie joined in January 2024 with a Cannes target only months away. He describes Fargeat selecting an electronic language from his reel, then separating Elisabeth's more organic/nostalgic sonic identity from Sue's synthetic/hyperreal one. A recurring sound became the sonic identity of 'the Substance' itself. Raffertie also emphasizes that the score deliberately blurs into sound design, so the final soundtrack should not be taught as cleanly separated music and effects silos. Exact microphone models, production recorder, Foley stage, ADR log, stem layout, mix-stage routing, loudness targets, score session roster and plugin/synth chain remain unresolved unless directly documented. The finished production demonstrates constrained scale rather than small ambition. Long shooting time and performer effects labor substitute for some forms of industrial scale; a studio-built mental Los Angeles substitutes for location realism; practical prosthetics and puppets create contact and texture while VFX solves selected transformation limits; a digital LF camera and vintage spherical glass protect skin/prosthetic detail; and editing, sound and score operate as one sensory timing system. The player must keep uncertainty boundaries visible: current locked sources do not establish an audited final budget, financing waterfall, complete day-by-day schedule, total crew size, full camera-body inventory, exact lens-per-shot log, complete lighting package, total practical-effects asset count, complete VFX shot/vendor ledger beyond Noid's documented creature work, blood quantity ledger, full production-design drawings, editorial version/storage history, complete production-sound/Foley/ADR/mix chain, score-session roster or distribution recoupment.",
    requiredChoicesSeed: {
      screenplay: ["fargeat_writer_director", "minimal_dialogue_visual_structure", "custom_production_model", "budget_unresolved_boundary", "practical_digital_not_binary"],
      camera: ["alexa_mini_lf", "canon_k35_spherical", "thalia_24_close_focus", "cooke_90_macro", "arri_macro_200", "239_delivery", "softdrop_not_led", "prosthetic_show_lut", "fluorescent_liquid_lut"],
      editing: ["fargeat_on_set_key_sequence_edit", "eltabet_four_handed_edit", "300_plus_hours", "230_sequences", "premiere_pro", "sound_led_rhythm", "long_iterative_post"],
      sound: ["villard_production_sound", "deloof_sound_edit", "raffertie_january_2024", "elisabeth_organic_sue_synthetic", "substance_sound_motif", "music_sound_blur", "full_sound_chain_unresolved"],
      themes: ["film_history", "2024", "the_substance", "independent_low_mid_budget", "body_horror", "practical_prosthetics", "practical_digital_hybrid", "performance_effects_scheduling", "chapter19"]
    },
    learningGoals: [
      "Explain The Substance as Chapter 19's independent/low-to-mid-budget production-system case after Sentimental Value.",
      "Identify Coralie Fargeat as writer and director.",
      "Use Cannes' 140-minute record as the canonical runtime.",
      "Identify the United Kingdom, United States and France as the Cannes production territories.",
      "Identify Working Title, Blacksmith and A Good Story as the press-kit production companies.",
      "Identify Film France/CNC tax-rebate support without treating it as the whole financing plan.",
      "Keep audited final negative cost, financing percentages, cashflow and recoupment unresolved.",
      "Explain Fargeat's custom-built production model as a deliberate departure from standard manufacturing routines.",
      "Keep the shoot as longer than 100 days while recognizing a later colorist-side 111-day count.",
      "Explain why a long shoot can be a resource strategy when prosthetic application, resets and specialized inserts consume time.",
      "Identify Pierre-Olivier Persin as special makeup effects designer.",
      "Identify roughly 15 people and about 11 months as Persin's documented prosthetic-team/preparation scale.",
      "Explain practical-first effects as a production preference rather than a no-CGI rule.",
      "Explain silicone prosthetics and puppets as tools for physical interaction, texture and camera contact.",
      "Explain the Blub/Blob as a physical silicone puppet combined with live performance and later VFX.",
      "Explain the Gollum stage as a modular performer/double/stunt system rather than one performer doing every physical requirement.",
      "Explain Monstro Elisasue as months of design exploration across maquettes, digital design and physical suit work.",
      "Identify foam latex as the documented Monstro suit material and explain why large blood effects created durability/maintenance problems.",
      "Treat long prosthetic applications as performer-time and scheduling costs.",
      "Identify Noid Studio's documented contribution of more than 40 creature shots.",
      "Explain Noid's role as extending practical effects where movement, face replacement, animation or compositing required digital work.",
      "Reject a simplistic practical-effects-versus-CGI interpretation of the film.",
      "Identify Benjamin Kracun BSC as cinematographer.",
      "Explain why initial anamorphic interest was abandoned for spherical close-up requirements.",
      "Identify ARRI ALEXA Mini LF as the documented principal camera platform.",
      "Identify vintage Canon K35 lenses as the principal spherical lens family.",
      "Explain skin and prosthetic rendition as a camera/lens-selection criterion.",
      "Identify Leitz Thalia 24mm close-focus, Cooke 90mm Macro, ARRI Macro 200mm and diopters as specialized proximity tools.",
      "Use 2.39:1 as the press-kit delivery aspect ratio.",
      "Explain Elisabeth's apartment softdrop as a deliberate alternative to LED-screen virtual production.",
      "Explain why reflection, cost and hard-light interaction made LED less suitable for the apartment background.",
      "Explain the bathroom's tungsten-plus-LED approach as a balance between light quality and rapid night/day control.",
      "Keep full lighting fixture inventory, ratios, dimming and power distribution unresolved.",
      "Explain why prosthetic and fluorescent-liquid tests required color-pipeline decisions before photography.",
      "Identify Lux in Paris as the documented LUT/final-color collaborator.",
      "Explain the strong show LUT as an exposure-costing creative transform rather than a neutral monitoring LUT.",
      "Explain the dedicated fluorescent-liquid LUT and UV dependency as a prop-camera-color coordination problem.",
      "Explain Fargeat's mental/nonliteral Los Angeles as a production-design strategy.",
      "Identify Studios d'Epinay as a documented core studio ambition/base in cinematography reporting.",
      "Explain corridor, bathroom and TV spaces as symbolic controlled environments rather than documentary location realism.",
      "Keep complete stage occupancy, set drawings, scenic quantities and art-department cost unresolved.",
      "Explain heavy storyboarding of effects sequences as cross-department coordination rather than proof every editorial decision was predetermined.",
      "Explain Fargeat's on-set editing of key effects sequences as feedback between shooting and post.",
      "Identify Coralie Fargeat, Jerome Eltabet and Valentin Feron as the Cannes-credited editors.",
      "Explain Fargeat and Eltabet's four-handed editorial exchange.",
      "Identify Adobe Premiere Pro as the documented NLE.",
      "Preserve the documented scale of more than 300 hours of footage and roughly 230 sequences.",
      "Explain why a dialogue-light film makes sound and image duration primary editorial structure.",
      "Explain post as highly iterative because early cuts lacked final sound and VFX.",
      "Keep complete version count, storage architecture, assistant-editor ledger and exact lock chronology unresolved.",
      "Identify Emmanuelle Villard, Valerie Deloof, Victor Fleurant, Stephane Thiebaut and Victor Praud within the documented sound credits.",
      "Identify Raffertie as composer.",
      "Explain Raffertie's January 2024 start and compressed path toward the May Cannes target.",
      "Explain Elisabeth's more organic/nostalgic and Sue's more synthetic/hyperreal musical identities.",
      "Explain the recurring Substance motif as an example of score functioning like sound design.",
      "Explain why score and sound effects deliberately blur rather than occupy cleanly separated silos.",
      "Keep microphone, recorder, Foley, ADR, stem, mix-stage, synth/plugin and score-session details unresolved without direct evidence.",
      "Separate Cannes/Academy reception from evidence of production method.",
      "Close the case only when financing boundaries, performer/prosthetic labor, practical-digital integration, camera/color, studio design, editing and sound/music agree."
    ],
    phases: [
      { id: "evidence_hierarchy", label: "Map The Substance evidence hierarchy", player_task: "Separate Cannes/press-kit institutional records from direct craft testimony and later awards reporting before promoting workflow claims." },
      { id: "finance_boundary", label: "Freeze financial uncertainty", player_task: "Record production companies and Film France/CNC support without inventing a final budget, financing shares or recoupment waterfall." },
      { id: "custom_model", label: "Define the bespoke production model", player_task: "Plan a longer, smaller-footprint production around prosthetic time, inserts and controlled studio work rather than assuming a conventional schedule template." },
      { id: "prosthetic_prep", label: "Fund long prosthetic development", player_task: "Give the special makeup team months to sculpt, mold, test, revise and duplicate transformation stages before principal photography." },
      { id: "performer_time", label: "Schedule application time", player_task: "Treat multi-hour prosthetic applications, removal, performer fatigue and skin care as production resources rather than invisible makeup time." },
      { id: "gollum_modularity", label: "Split Gollum performance tasks", player_task: "Choose Demi Moore, a body performer or stunt double shot by shot according to face, silhouette and action requirements while preserving continuity." },
      { id: "monstro_design", label: "Iterate Monstro", player_task: "Use maquettes and digital/physical design tests to solve mass, movement, performer access and camera readability before final fabrication." },
      { id: "blood_durability", label: "Engineer blood-resistant effects", player_task: "Anticipate how foam latex, silicone, adhesives, costumes, floors and reset crews behave under repeated large-volume blood effects." },
      { id: "vfx_boundary", label: "Define practical-digital handoffs", player_task: "Identify which physical creature elements remain in camera and which facial, motion or compositing limits require VFX support." },
      { id: "camera_tests", label: "Test prosthetics under camera", player_task: "Compare camera/lens systems against skin, seams, veins, gloss and close-focus behavior before locking the package." },
      { id: "spherical_choice", label: "Choose spherical over anamorphic", player_task: "Protect the storyboarded extreme close-up language and prosthetic geometry rather than preserving an initial format preference." },
      { id: "principal_package", label: "Lock Mini LF and K35", player_task: "Use the documented ALEXA Mini LF/Canon K35 combination as the principal clean-but-vintage skin/prosthetic image system." },
      { id: "macro_package", label: "Build the macro toolkit", player_task: "Assign the Thalia 24, Cooke 90 Macro, ARRI Macro 200 and diopters to proximity problems instead of forcing one lens family across all scales." },
      { id: "apartment_background", label: "Choose softdrop over LED", player_task: "Reject an LED wall when reflection, hard-light behavior, cost and desired romance favor a physical backdrop." },
      { id: "bathroom_light", label: "Light the clinical bathroom", player_task: "Combine tungsten quality and LED speed while preserving veins, flesh color and prosthetic detail across day/night states." },
      { id: "prosthetic_lut", label: "Build a prosthetic-aware show LUT", player_task: "Test how the strong creative LUT changes exposure and material detail before shooting irreversible effects work." },
      { id: "substance_lut", label: "Calibrate the fluorescent liquid", player_task: "Coordinate prop fluorescence, UV illumination, camera response and a dedicated LUT so the Substance reads consistently." },
      { id: "studio_geography", label: "Construct a mental Los Angeles", player_task: "Use controlled corridors, bathroom, apartment and TV spaces as symbolic geography rather than spending resources on literal LA continuity." },
      { id: "storyboard_effects", label: "Storyboard effects grammar", player_task: "Preplan transformation inserts, point-of-view geometry and blood choreography tightly enough for prosthetics, camera, SFX and VFX to share one shot logic." },
      { id: "on_set_edit", label: "Cut key sequences during photography", player_task: "Assemble transformation/fight/climax material early so missing inserts, durations and effect transitions can still be corrected while shooting." },
      { id: "selects_system", label: "Organize massive footage", player_task: "Use a timeline/selects method that preserves first instincts across more than 300 hours of material instead of relying only on later memory." },
      { id: "sequence_scale", label: "Track 230-sequence structure", player_task: "Maintain sequence-level ownership and status through a large editorial structure whose dialogue-light sections depend on precise rhythm." },
      { id: "sound_in_edit", label: "Cut with working sound", player_task: "Develop effects and sonic rhythm early because silence, bodily noises and impact cues carry story information before the final mix exists." },
      { id: "vfx_in_edit", label: "Iterate VFX against picture", player_task: "Use representative creature work to judge timing without assuming digital replacement should erase successful physical performance." },
      { id: "post_paris", label: "Run long Paris post", player_task: "Protect the director-led edit through an extended iterative post while keeping version and storage details auditable rather than guessed." },
      { id: "production_sound", label: "Preserve production-sound evidence", player_task: "Keep credited production sound distinct from later sound editing even though the full recorder/microphone chain is unresolved." },
      { id: "sound_design", label: "Build bodily sonic language", player_task: "Use sound editorial to make injections, flesh, impacts, breathing and transformations function as structural events rather than decorative gore." },
      { id: "score_start", label: "Bring Raffertie in late but fast", player_task: "Use the January-to-Cannes window to establish a compact musical vocabulary instead of attempting an undocumented long pre-score process." },
      { id: "dual_music_worlds", label: "Separate Elisabeth and Sue sonically", player_task: "Shape organic/nostalgic versus synthetic/hyperreal identities while allowing them to collide as the bodies and narrative collapse." },
      { id: "substance_motif", label: "Turn the product into a sound", player_task: "Use a recurring motif that can function simultaneously as score, effect and narrative signal." },
      { id: "mix_blur", label: "Blur music and sound deliberately", player_task: "Design transitions so the audience cannot always classify a sonic event as score or effect while still keeping departmental credits accurate." },
      { id: "uncertainty_register", label: "Maintain unresolved technical fields", player_task: "Keep budget, financing, complete schedule, lighting, VFX ledger, blood quantities, edit storage and sound/score chains explicitly unresolved where direct evidence stops." },
      { id: "anti_practical_myth", label: "Audit the practical-effects myth", player_task: "Reject any claim that the film proves practical effects are inherently superior or that its final creatures contain no CGI." },
      { id: "anti_budget_myth", label: "Audit the budget narrative", player_task: "Do not turn the film's resourceful look or long schedule into an unsourced exact-budget claim." },
      { id: "production_verification", label: "Close Production Verification", player_task: "Close only when permanent sources, full Film Study and playable choices agree on practical/digital boundaries, camera/color, editorial sound structure and unresolved evidence." }
    ]
  }
] as const;

export function mergeChapterNineteenTheSubstanceExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterNineteenTheSubstanceExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_nineteen_the_substance_verified",
      source: { list_id: "manual_chapter_nineteen_the_substance_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
