import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterEighteenParasiteExpansionDefinitions = [
  {
    id: "scenario_parasite_2019",
    title: "Parasite",
    originalTitle: "Gisaengchung",
    year: 2019,
    titleType: "Movie",
    runtimeMins: 132,
    directors: ["Bong Joon-ho"],
    genres: ["Drama", "Thriller", "Comedy"],
    sourceId: "festival_cannes_parasite_2019",
    sourceUrl: "https://www.festival-cannes.com/en/f/gisaengchung/",
    scenarioType: "south_korean_class_thriller_alexa65_prime_dna_controlled_set_lighting_vertical_production_design_storyboard_no_coverage_editorial_atmos_2019",
    premise: "Build Parasite as Chapter 18's 2019 South Korean production case about how screenplay geometry, purpose-built spaces, large-format digital cinematography, controlled lighting, storyboard-led shooting, editorial precision and Dolby Atmos sound were coordinated around class movement rather than added as isolated craft flourishes. The Cannes record establishes Bong Joon-ho as director, Bong and Han Jin-won as screenwriters, Hong Kyung-pyo as cinematographer, Lee Ha-jun as production designer, Yang Jin-mo as editor, Choi Tae-young as sound lead, Jung Jae-il as composer and a 132-minute Cannes presentation. KOFIC separately catalogs the Korean release at 131 minutes and identifies Barunson E&A as production company and CJ Entertainment as international sales; preserve that one-minute metadata discrepancy instead of silently forcing the records to agree. ARRI documents Hong's use of the ALEXA 65 with Prime DNA lenses. That large-format package is evidence about capture, not a claim that sensor size created the film's class meaning by itself. ARRI's lighting account says the production installed or produced almost all major visual elements on controlled sets and used SkyPanels across major locations, allowing direction and amount of light to be planned alongside architecture. Treat the 97 percent figure as ARRI's practitioner account of controllability, not a universal measure of how much of the movie was artificial. Production designer Lee Ha-jun explains that the Park house was designed for blocking and camera needs rather than as a normally inhabitable building: the first floor and garden were built outside in Jeonju, while upper or hidden spaces were completed separately on stage. The Kim semi-basement and surrounding neighborhood were also constructed, with the flood environment designed to be inundated, drained, cleaned and redressed. Lee's interviews repeatedly foreground verticality, window access, garden geometry, stairs and the relation between camera position and character movement. Keep symbolism and production logistics separate: a staircase can carry class meaning while still needing safe dimensions, sightlines, drainage, lighting access and repeatable blocking. Editor Yang Jin-mo describes a production in which Bong's script and storyboards pre-shaped many cuts and the director generally avoided conventional coverage and even master shots. That constraint did not remove editorial authorship: Yang selected timing and performance, stitched different takes when a planned continuous move needed refinement, created jump cuts to tighten action and discovered new cross-cutting in the flood/basement material. Editorial therefore works inside a highly planned shooting system while still solving problems not predetermined on paper. Yang also describes temp effects and sound notes being built in editorial and handed onward, so do not confuse low-quality temp tracks with final sound assets. Ralph Tae-young Choi's sound account places dialogue, effects, backgrounds, ADR and Foley work at Live Tone Studios after picture editing, followed by pre-dub and a Dolby Atmos final mix. Bong emphasized the distinct doors of the Park house, while the rain/flood progression and location-specific acoustic detail helped articulate movement between social spaces. Sound metaphor is an authored design choice grounded in recorded, edited and mixed material; it is not proof that a door sound has one fixed interpretation. The case should leave the player able to trace a scene from script and storyboard through set geometry, camera and lighting, performance, editorial, temp sound, sound edit, premix and Atmos final while distinguishing documented production fact from thematic interpretation, festival reception and later awards.",
    requiredChoicesSeed: {
      screenplay: ["family_infiltration_structure", "three_household_escalation", "class_space_causality", "genre_shift_without_reset", "vertical_motif_boundaries"],
      camera: ["alexa65_prime_dna_package", "blocking_first_set_geometry", "window_sunlight_control", "stairs_and_depth_staging", "large_format_without_determinism", "flood_set_camera_safety"],
      editing: ["storyboard_led_assembly", "no_coverage_contingency", "performance_timing", "stitched_take_repair", "flood_basement_crosscut", "temp_sound_notes"],
      sound: ["park_house_door_motifs", "rain_flood_escalation", "location_acoustic_contrast", "adr_foley_boundaries", "predub_handoff", "dolby_atmos_final_mix"],
      themes: ["film_history", "2019", "parasite", "gisaengchung", "bong_joon_ho", "han_jin_won", "hong_kyung_pyo", "lee_ha_jun", "yang_jin_mo", "choi_tae_young", "jung_jae_il", "barunson_e_and_a", "cj_entertainment", "south_korean_cinema", "alexa_65", "prime_dna", "skypanel", "production_design", "verticality", "semi_basement", "park_house", "blocking", "storyboards", "no_coverage", "editorial_timing", "temp_sound", "foley", "dolby_atmos", "runtime_discrepancy"],
    },
    learningGoals: [
      "Explain Parasite as a coordinated production system rather than a collection of award-winning departments.",
      "Identify Bong Joon-ho as director and Bong Joon-ho with Han Jin-won as credited screenwriters.",
      "Identify Hong Kyung-pyo, Lee Ha-jun, Yang Jin-mo, Choi Tae-young and Jung Jae-il in their credited craft roles.",
      "Separate Barunson E&A's production role from CJ Entertainment's sales/distribution role in the KOFIC record.",
      "Preserve the documented 132-minute Cannes record beside KOFIC's 131-minute catalog entry instead of inventing certainty.",
      "Explain why a runtime discrepancy is a provenance problem to document, not a reason to discard one source.",
      "Identify the ALEXA 65 and Prime DNA package without claiming large format automatically creates prestige or meaning.",
      "Explain how sensor and lens choices interact with composition, depth, blocking and lighting rather than determining them alone.",
      "Describe ARRI's account of highly controlled installed production elements without turning its 97 percent figure into an absolute ontology of the finished film.",
      "Explain how SkyPanel lighting supported repeatable control across major constructed locations.",
      "Distinguish available natural sunlight from deliberately controlled or supplemented set lighting.",
      "Explain why the Park house was designed as a filming environment around camera, blocking and narrative sightlines rather than as ordinary architecture.",
      "Map the Park garden and first-floor build separately from stage-built upper or hidden spaces.",
      "Describe the Kim neighborhood as a constructed environment rather than assuming every exterior-looking detail was a found location.",
      "Explain why the semi-basement flood required a set that could be inundated, drained, cleaned and reset.",
      "Treat stairs, windows, garden levels and underground rooms as both physical production problems and possible thematic structures.",
      "Avoid claiming that verticality has only one symbolic meaning when production sources primarily document design intent and logistics.",
      "Explain how Lee Ha-jun used modeling and spatial planning to coordinate movement and camera positions before construction.",
      "Distinguish production-design realism from documentary location authenticity.",
      "Explain why custom dressing, aging and salvaged material can create lived-in texture without making a set literally old housing.",
      "Describe Bong's storyboard-heavy preparation as a constraint on coverage rather than a guarantee that every final cut was predetermined.",
      "Explain Yang Jin-mo's role in selecting performance and timing inside a tightly planned shooting method.",
      "Describe how separate takes can be stitched to repair timing in a shot designed to appear continuous.",
      "Explain why the absence of conventional coverage raises the cost of missed performance or timing choices.",
      "Describe the flood/basement cross-cut as an editorial discovery rather than a shot plan that existed unchanged from production.",
      "Explain how jump cuts can remove procedural time while preserving the essential action beat.",
      "Distinguish on-set or assembly editing from final editorial refinement.",
      "Describe temp sound effects as editorial communication assets rather than final-quality sound evidence.",
      "Trace sound notes from editorial into later specialist sound work without claiming the editor performed the final mix.",
      "Identify Live Tone Studios as the documented site of post sound work in Choi's account.",
      "Distinguish dialogue edit, effects edit, backgrounds, ADR, Foley, pre-dub and final mix as separate sound tasks.",
      "Identify the final mix as Dolby Atmos without claiming the format itself creates narrative clarity.",
      "Explain how Park-house door sounds were differentiated as recurring designed events rather than generic library cues.",
      "Describe rain and flood escalation as a layered sound-and-picture progression rather than a single recorded ambience track.",
      "Explain how acoustic contrast can help distinguish social spaces while remaining an authored interpretation.",
      "Keep Jung Jae-il's score distinct from effects, ambience, dialogue and Foley during editorial and mixing decisions.",
      "Explain how production design, camera, lighting and editing cooperate to preserve sightlines during concealment and revelation scenes.",
      "Audit claims about class symbolism separately from claims about how a set, lens, light or cut was physically produced.",
      "Keep Cannes awards and later Academy recognition downstream from evidence about production practice.",
      "Compare Parasite with Roma: both coordinate digital capture and class-conscious spatial design, but their camera, monochrome/color and production-space strategies differ.",
      "Compare Parasite with Spider-Verse: both treat production systems as designable, but one reshapes constructed live-action space while the other reshapes a CG animation pipeline.",
      "Compare Parasite with A Separation: both build tension from domestic space and performance, while their industrial context and technical production systems remain distinct.",
      "Use source hierarchy to separate official equipment records, practitioner interviews, festival metadata, trade reporting and interpretive criticism.",
      "Reject unsupported claims that Parasite invented vertical class symbolism, large-format digital cinematography, no-coverage shooting, constructed flood sets or Dolby Atmos storytelling.",
    ],
    phases: [
      { id: "evidence_map", label: "Map the evidence hierarchy", player_task: "Separate Cannes and KOFIC metadata, ARRI equipment records, practitioner interviews, trade reporting and later reception before production claims enter the brief." },
      { id: "runtime_provenance", label: "Record the runtime discrepancy", player_task: "Keep Cannes' 132-minute listing beside KOFIC's 131-minute listing with source labels instead of silently normalizing the records." },
      { id: "script_space_map", label: "Map story into space", player_task: "Translate the three-household escalation into rooms, stairs, thresholds, hiding places and movement paths before deciding how sets must support the screenplay." },
      { id: "verticality_boundary", label: "Separate motif from mechanism", player_task: "Track vertical movement as an interpretive motif while separately documenting the physical stairs, grades, windows and underground spaces that make the movement shootable." },
      { id: "park_house_blocking", label: "Design the Park house for blocking", player_task: "Lay out living room, garden, stairs and sightlines so entrances, concealment and observation work for performers and camera rather than copying an existing residence." },
      { id: "park_house_build", label: "Split the house build", player_task: "Plan the outdoor first-floor/garden build separately from stage-built upper or hidden spaces and maintain screen-space continuity across them." },
      { id: "kim_neighborhood_build", label: "Build the semi-basement world", player_task: "Construct the Kim apartment and surrounding neighborhood with controlled windows, alleys, dressing and camera access rather than treating apparent street realism as proof of a found location." },
      { id: "flood_engineering", label: "Engineer the flood set", player_task: "Specify water control, drainage, reset, electrical safety, dressing replacement and performer/camera access before the flood sequence is scheduled." },
      { id: "surface_history", label: "Age the environment", player_task: "Use salvaged and distressed materials to create accumulated lived-in history while documenting which textures are built, found or modified." },
      { id: "camera_package", label: "Lock the large-format package", player_task: "Record ALEXA 65 and Prime DNA as the documented capture package, then test focal length and distance choices without turning format size into an aesthetic shortcut." },
      { id: "blocking_camera_test", label: "Test camera against architecture", player_task: "Rehearse performer movement and camera positions inside the planned geometry so walls, windows and furniture preserve the required compositions and sightlines." },
      { id: "window_light_plan", label: "Plan window exposure", player_task: "Coordinate garden orientation, window size, sun position and controllable fixtures so exterior brightness and interior faces remain repeatable across the schedule." },
      { id: "skypanel_control", label: "Build controllable light", player_task: "Use tunable fixtures where documented to control direction, level and color while keeping natural and artificial sources separately logged." },
      { id: "storyboard_lock", label: "Translate boards into coverage needs", player_task: "Mark the storyboarded shots that carry essential story information and identify where the no-coverage strategy leaves no conventional editorial fallback." },
      { id: "performance_rehearsal", label: "Protect performance inside precision", player_task: "Rehearse complex entrances, concealments and reactions so technical blocking does not flatten character timing." },
      { id: "no_coverage_risk", label: "Budget no-coverage risk", player_task: "Identify shots where a failed pan, reaction or timing beat would be expensive to repair because no master or alternate coverage exists." },
      { id: "assembly_edit", label: "Assemble during production", player_task: "Review incoming material against the planned structure early enough to flag missing beats without pretending the assembly is the final edit." },
      { id: "stitched_take_repair", label: "Repair a continuous shot", player_task: "When a planned move works in parts but not as one take, test a concealed stitch while checking performance continuity, camera motion and sound handoff." },
      { id: "jump_cut_compression", label: "Compress procedural action", player_task: "Use jump cuts only where they preserve the essential causal information while tightening a repetitive action sequence." },
      { id: "flood_crosscut", label: "Discover cross-cut structure", player_task: "Test alternate ordering between flood and basement material to find a stronger transition without claiming the final relationship was predetermined on set." },
      { id: "temp_sound_build", label: "Build editorial temp sound", player_task: "Place low-resolution effects and ambience for rhythm and communication, label them as temporary and preserve notes for the specialist sound handoff." },
      { id: "picture_lock_handoff", label: "Hand off picture and notes", player_task: "Deliver picture, turnover data and director/editor sound notes so dialogue, effects, backgrounds, ADR and Foley teams can trace editorial intent." },
      { id: "door_sound_design", label: "Differentiate thresholds", player_task: "Design the Park gate, front door, interior sliding doors and hidden-room access as distinct sonic events tied to their materials and narrative function." },
      { id: "rain_flood_sound", label: "Escalate rain into flood", player_task: "Layer rain, thunder, water movement, interiors and music so intensity changes with geography and story rather than relying on one continuous ambience file." },
      { id: "adr_foley", label: "Separate ADR and Foley", player_task: "Replace or supplement dialogue where needed and record performed object/body sounds separately, maintaining provenance for each final element." },
      { id: "predub", label: "Prepare the pre-dub", player_task: "Balance dialogue, effects, backgrounds, Foley and music into manageable stems before the final immersive mix." },
      { id: "atmos_mix", label: "Complete the Atmos mix", player_task: "Use Dolby Atmos placement where it supports perspective and transitions while protecting dialogue intelligibility and fold-down compatibility." },
      { id: "score_effect_balance", label: "Balance score and effects", player_task: "Coordinate Jung Jae-il's score with rain, doors, dialogue and action effects so musical intensity does not erase spatial information." },
      { id: "release_metadata", label: "Lock release provenance", player_task: "Store Cannes and KOFIC runtime, country, credits and company metadata as separately attributable records rather than a blended unsourced fact." },
      { id: "method_audit", label: "Audit production versus interpretation", player_task: "Review every technical and symbolic claim, preserving what practitioners document and downgrading conclusions supported only by awards, criticism or retrospective enthusiasm." },
    ],
  },
] as const;

export function mergeChapterEighteenParasiteExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterEighteenParasiteExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_eighteen_parasite_verified",
      source: { list_id: "manual_chapter_eighteen_parasite_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
