import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterEighteenTwentyEightDaysLaterExpansionDefinitions = [
  {
    id: "scenario_28_days_later_2002",
    title: "28 Days Later",
    originalTitle: "28 Days Later...",
    year: 2002,
    titleType: "Movie",
    runtimeMins: 113,
    directors: ["Danny Boyle"],
    genres: ["Horror", "Science Fiction", "Thriller"],
    sourceId: "bfi_28_days_later_2002",
    sourceUrl: "https://www.bfi.org.uk/film/bd4cc955-a617-5a8b-b164-aed26d582552/28-days-later",
    scenarioType: "uk_usa_minidv_canon_xl1_multi_camera_london_location_digital_post_filmout_horror_production_2002",
    premise: "Build 28 Days Later as Chapter 18's next P1 production case about the deliberate use of low-resolution digital video, ultra-short urban access windows, multi-camera location logistics, optical/electronic image constraints, post-production upconversion and grading, editorial aggression, production design, sound labor and 35mm theatrical film-out. The British Film Institute records the 2002 United Kingdom/USA feature as directed by Danny Boyle, produced by Andrew Macdonald, written by Alex Garland and running 113 minutes. BFI programme credits identify Anthony Dod Mantle as director of photography, Chris Gill as editor, Mark Tildesley as production designer, John Murphy as composer, Glenn Freemantle as sound designer, John Rodda as sound recordist, Clare St. John as post-production supervisor, Clear as special visual-effects provider and Moving Picture Company as digital lab. American Cinematographer's production account establishes that the filmmakers chose MiniDV partly because conventional 35mm production in London would have forced them to lose expensive location scenes; the small cameras could be placed and reset rapidly during tiny traffic-control windows around Piccadilly Circus, Westminster Bridge and the Docklands. Those early-morning sequences sometimes used as many as eight Canon XL1 cameras at once, with Dod Mantle placing and framing them while camera operators, the gaffer and producer Andrew Macdonald helped cover angles against a constantly changing sunrise. In preproduction, Dod Mantle and MPC tested the PAL Canon XL1 and selected a 4x3 acquisition workflow matted for 16x9 in Frame Movie Mode, while higher-resolving Canon EC 6-40mm and EJ 50-150mm lenses were mounted via Optex adapters. The production exposed the camera as a specific imaging system rather than pretending consumer DV was transparent: Dod Mantle worked wide open with ND, underexposed one to two stops, used graduated filters for skies, shot replacement sky plates when necessary, composed around pixel-prone high-contrast backgrounds and used altered materials such as deformed plastic for optical texture. Day-for-night scenes required deliberate lighting and design coordination; ASC documents large HMIs through diffusion, post-darkening of some material and Mark Tildesley's repainting of a stairwell several stops darker to support the effect. The infected were not simply made frantic by handheld camera: Dod Mantle deliberately avoided excessive movement in the climax and instead used a fast shutter on close views of infected motion while relying on more controlled dolly work elsewhere. The post path must remain exact. Clear upconverted the footage to 125 D-1 tapes and handled visual effects; after editing and conforming, seven D-1 masters went to MPC, where Dod Mantle and colorist Jean-Clement Sorret spent almost a month in tape-to-tape grading. The graded material was captured to disk, treated on Linux Shake, enhanced and interpolated with MPC's FilmTel process to 2K, reframed slightly from 16x9 to 1.85:1 and recorded to Kodak Vision Color Intermediate 5242 via Arrilaser. Technicolor London created the answer print on Fuji HiCon 3519D, and Deluxe made release prints on Kodak Vision 2383. That chain makes the case a digital-origin production with a film-out and 35mm theatrical print workflow, not a film-origin production and not a modern file-based digital-intermediate pipeline. Later Danny Boyle testimony confirms that Chris Gill's editing responded directly to the high-shutter DV texture and used rapid cutting as part of the film's energy, but editing remains its own authorship layer rather than an automatic consequence of the camera format. BFI credits separately document the sound chain—Glenn Freemantle, John Rodda, dialogue editing, ADR, Foley and re-recording personnel—so the case can name the departments without inventing microphones, recorders, track counts or mix decisions not established by those sources. Keep all boundaries explicit: MiniDV enabled access but did not make the production effortless; upconversion and 2K interpolation did not create original image detail that the XL1 never captured; visual-effects cleanup did not convert every frame into CGI; digital-origin photography and 35mm release prints are separate facts; high shutter is not synonymous with handheld chaos; and the film's later influence on horror culture is a reception claim, not production evidence. The player should be able to trace one deserted-London setup from permissions and traffic control through multi-camera placement, rising-light exposure, MiniDV image limits, lens/adaptor choices, sound and crowd control, editorial selection, D-1 conform, MPC grade, 2K enhancement, Arrilaser film-out and theatrical print while preserving the uncertainty and evidence level of every claim.",
    requiredChoicesSeed: {
      screenplay: ["deserted_london_priority", "location_access_tradeoff", "infection_action_grammar", "character_survival_arc", "scene_information_map"],
      camera: ["pal_canon_xl1_minidv", "frame_movie_mode", "eight_camera_london_plan", "canon_ec_ej_optex", "nd_underexposure_strategy", "fast_shutter_infected", "filmout_boundary"],
      editing: ["high_shutter_cutting", "multi_camera_selects", "location_window_coverage", "d1_conform", "pace_contrast", "effects_handoff"],
      sound: ["production_sound_credit_map", "glenn_freemantle_sound_design", "john_rodda_recordist", "adr_foley_dialogue_roles", "music_sound_boundary", "unknown_equipment_boundary"],
      themes: ["film_history", "2002", "28_days_later", "danny_boyle", "alex_garland", "andrew_macdonald", "anthony_dod_mantle", "chris_gill", "mark_tildesley", "john_murphy", "glenn_freemantle", "minidv", "canon_xl1", "frame_movie_mode", "canon_ec", "canon_ej", "optex_adapter", "multi_camera", "deserted_london", "traffic_control", "day_for_night", "fast_shutter", "clear_ltd", "d1", "mpc", "jean_clement_sorret", "linux_shake", "filmtel", "2k_interpolation", "arrilaser", "kodak_5242", "fuji_3519d", "kodak_2383", "digital_origin", "film_out", "uk", "usa", "113_minutes"],
    },
    learningGoals: [
      "Explain 28 Days Later as a digital-origin production and access strategy rather than a generic claim that cheap cameras automatically democratize filmmaking.",
      "Identify Danny Boyle as director, Andrew Macdonald as producer and Alex Garland as screenwriter from the BFI record.",
      "Identify Anthony Dod Mantle as director of photography, Chris Gill as editor and Mark Tildesley as production designer from the BFI credits.",
      "Identify John Murphy as composer and keep music distinct from production sound and sound design.",
      "Identify Glenn Freemantle as sound designer and John Rodda as sound recordist without inventing their equipment package.",
      "Preserve the BFI's 2002, United Kingdom/USA and 113-minute release metadata without treating it as a financing ledger.",
      "Explain why the filmmakers judged conventional 35mm production too slow and expensive for some London location ambitions.",
      "Explain how MiniDV's small camera bodies reduced setup footprint and made very short traffic-control windows usable.",
      "Record that deserted-London material sometimes used as many as eight Canon XL1 cameras at once.",
      "Explain why six-to-eight simultaneous operators created exposure, framing, communication and rising-sun coordination problems rather than simply multiplying coverage for free.",
      "Identify the PAL Canon XL1 as the documented principal MiniDV camera system in the ASC production account.",
      "Explain the tested 4x3 acquisition with a 16x9 matte and Frame Movie Mode without mislabeling it as native progressive 16x9 HD capture.",
      "Identify Canon EC 6-40mm and EJ 50-150mm lenses and Optex adapters as documented parts of the camera package.",
      "Keep video-camera focal-length behavior and 35mm-equivalent assumptions separate unless a source explicitly provides the conversion.",
      "Explain why Dod Mantle used ND filters and a wide-open approach to reduce the XL1's deep-focus appearance.",
      "Explain why one-to-two-stop underexposure was a title-specific strategy for preserving information and mood, not a universal DV rule.",
      "Explain why graduated filters and separately photographed sky plates addressed the XL1's limited highlight latitude.",
      "Explain how high-contrast architectural lines could produce distracting pixel structure in wide DV backgrounds and therefore influenced composition.",
      "Describe the use of burnt or deformed plastic as an in-camera optical-texture choice rather than a post-production filter preset.",
      "Explain the day-for-night strategy as a coordinated lighting, exposure, design and post problem rather than a single color-grade trick.",
      "Use the repainted stairwell as a documented example of Mark Tildesley's design department changing a location to help the photographic exposure strategy.",
      "Use the tunnel sequence to connect large HMIs, hidden smaller fixtures, practical debris and shadow choreography without generalizing that lighting setup to the whole film.",
      "Explain why the infected's movement was often intensified with fast shutter while the climax deliberately avoided constant frenetic camera motion.",
      "Distinguish high-shutter motion rendering from handheld instability, frame rate and editorial speed.",
      "Explain how Chris Gill's editing could respond to the brittle high-shutter texture while remaining an authored selection and timing process.",
      "Separate multi-camera capture from editorial assembly: more angles create selection work, synchronization and continuity decisions rather than a finished sequence automatically.",
      "Identify Clear Ltd.'s upconversion to 125 D-1 tapes and visual-effects role as a post-production handoff after MiniDV acquisition.",
      "Explain that D-1 4:2:2 upconversion does not restore spatial or chroma detail that the original MiniDV recording never contained.",
      "Record that seven D-1 masters were delivered to MPC after editing and conforming.",
      "Identify Jean-Clement Sorret as the MPC colorist in the ASC account and record the roughly month-long tape-to-tape grading period.",
      "Explain the Linux Shake treatment and MPC FilmTel enhancement/interpolation as post-processing of a low-resolution source rather than original 2K capture.",
      "Explain the slight reframing from 16x9 to 1.85:1 as an exhibition/finishing decision rather than proof of the camera's native aspect ratio.",
      "Identify the Arrilaser recording to Kodak Vision Color Intermediate 5242 as the film-out stage.",
      "Identify Technicolor London's Fuji HiCon 3519D answer print and Deluxe's Kodak Vision 2383 release prints as distinct photochemical release stages.",
      "Distinguish a digital-origin/film-out pipeline from both film-origin digital intermediate and modern file-based digital cinema distribution.",
      "Use BFI credits to map dialogue editing, ADR, Foley, sound design, recordist and re-recording roles without inventing undocumented workflow details.",
      "Keep John Murphy's score separate from Glenn Freemantle's sound-design responsibilities and from John Rodda's production-recording credit.",
      "Explain why location permissions, traffic holds, police coordination and public disruption are production constraints that camera choice cannot eliminate.",
      "Explain why a low-cost camera choice can coexist with substantial lighting, post, lab and release-print work.",
      "Compare 28 Days Later with Russian Ark: both are early-2000s digital-origin cases, but their camera systems, temporal structures and post-production problems are fundamentally different.",
      "Compare 28 Days Later with Collateral: both exploit digital sensitivity and urban night/location access, but MiniDV XL1 and Viper/F900 systems represent different technical generations and image goals.",
      "Compare 28 Days Later with Inland Empire: both use deliberately rough digital imaging, but their camera practices, production structures and post pipelines are not interchangeable.",
      "Reject claims that 28 Days Later invented digital feature cinematography, multi-camera city shooting, fast-shutter action, zombie cinema or digital-to-film recording.",
      "Separate contemporary production reporting from later franchise mythology and influence claims.",
      "Audit every novelty, budget, influence, genre and technical-first claim independently from the documented camera, post, sound and location facts.",
    ],
    phases: [
      { id: "evidence_map", label: "Map the evidence hierarchy", player_task: "Separate BFI institutional credits, the American Cinematographer production account, BFI programme credits and later Danny Boyle/Chris Gill testimony before converting any statement into a production fact." },
      { id: "release_record", label: "Lock the release record", player_task: "Record 2002, 113 minutes, Danny Boyle, Andrew Macdonald and Alex Garland without using later franchise success as production evidence." },
      { id: "crew_map", label: "Map the core departments", player_task: "Keep Anthony Dod Mantle, Chris Gill, Mark Tildesley, John Murphy, Glenn Freemantle and John Rodda in their documented departmental roles." },
      { id: "location_access_problem", label: "Define the access problem", player_task: "Translate deserted-London ambitions into permissions, traffic holds, setup footprint, operator count and rising-light constraints before choosing a camera." },
      { id: "minidv_format", label: "Lock the MiniDV format", player_task: "Record PAL Canon XL1 MiniDV as the documented acquisition system and reject any shorthand that turns it into HD or native 2K capture." },
      { id: "frame_mode", label: "Protect the frame-mode boundary", player_task: "Map 4x3 acquisition, 16x9 matte and Frame Movie Mode as documented camera settings without inventing a native widescreen progressive sensor mode." },
      { id: "lens_adapter", label: "Build the lens package", player_task: "Assign Canon EC 6-40mm and EJ 50-150mm optics through Optex adapters while leaving shot-specific focal lengths unknown unless sourced." },
      { id: "eight_camera_plan", label: "Plan eight-camera London coverage", player_task: "Place multiple XL1 bodies around a traffic-controlled location, assign operators and protect eyelines, exposure and safe public boundaries within a tiny capture window." },
      { id: "rising_sun_exposure", label: "Chase the rising sun", player_task: "Coordinate T-stop changes across several camera positions as dawn changes exposure instead of assuming every angle can share one static setting." },
      { id: "nd_depth_strategy", label: "Shape DV depth", player_task: "Use ND and wide apertures as a title-specific response to the XL1's deep-focus tendency while protecting focus and highlight risk." },
      { id: "underexposure_strategy", label: "Protect low-end information", player_task: "Model Dod Mantle's one-to-two-stop underexposure as a deliberate compromise and flag where noise, crushed blacks or later grading may fail." },
      { id: "sky_protection", label: "Protect the sky", player_task: "Use grads and separately exposed sky plates when highlight latitude cannot hold the sky, then label any replacement as post work rather than original capture." },
      { id: "background_aliasing", label: "Audit digital backgrounds", player_task: "Inspect hard architectural lines and wide backgrounds for distracting pixel structure before locking camera position." },
      { id: "optical_texture", label: "Build optical texture", player_task: "Separate in-camera texture from digital grading by documenting when deformed or burnt plastic is placed physically in the image path." },
      { id: "day_for_night", label: "Design day for night", player_task: "Coordinate HMI fill, diffusion, exposure reduction, window control and later darkening without pretending the grade can rescue any daylight plate." },
      { id: "stairwell_design", label: "Rebuild the stairwell tonally", player_task: "Use the documented repainting of the location to show how production design can alter reflectance and exposure before the camera rolls." },
      { id: "tunnel_light", label: "Stage the tunnel", player_task: "Map 18K HMIs, hidden smaller fixtures, debris and growing shadows as one sequence-specific lighting system." },
      { id: "infected_shutter", label: "Set infected motion grammar", player_task: "Use fast shutter for selected infected close shots and keep shutter angle, frame rate, camera movement and editorial speed as separate variables." },
      { id: "controlled_camera", label: "Resist automatic handheld chaos", player_task: "Choose dolly or restrained camera movement when the scene already supplies panic, preserving Dod Mantle's documented distinction between motion rendering and camera agitation." },
      { id: "multi_camera_edit", label: "Assemble multi-camera coverage", player_task: "Sync and evaluate simultaneous London angles for geography, continuity and emotional emphasis rather than treating eight cameras as eight equally useful shots." },
      { id: "high_shutter_edit", label: "Cut the brittle image", player_task: "Use Chris Gill's documented affinity for the high-shutter texture to test rapid cutting while preserving pauses and longer tension where the scene needs them." },
      { id: "sound_credit_map", label: "Map the sound departments", player_task: "Separate production recording, sound design, dialogue editing, ADR, Foley, re-recording and music according to BFI credits before making workflow claims." },
      { id: "sound_unknowns", label: "Respect sound unknowns", player_task: "Leave microphones, recorders, channel counts and exact mix decisions unknown unless separately sourced." },
      { id: "clear_upconvert", label: "Handoff to Clear", player_task: "Track MiniDV material into the documented 125 D-1 tapes and mark visual-effects work separately from the original camera signal." },
      { id: "d1_conform", label: "Conform the D-1 masters", player_task: "Carry the edited program into seven D-1 masters without claiming the 4:2:2 container reconstructs lost MiniDV chroma detail." },
      { id: "mpc_grade", label: "Grade at MPC", player_task: "Model the roughly month-long tape-to-tape grade with Jean-Clement Sorret as a finishing stage after editorial conform." },
      { id: "shake_filmtel", label: "Enhance and interpolate", player_task: "Document Linux Shake and FilmTel processing as enhancement of the source toward 2K film-out, not as evidence that principal photography was 2K." },
      { id: "aspect_handoff", label: "Finish to 1.85", player_task: "Track the 16x9 image through the slight enlargement to 1.85:1 and keep capture matte, finish frame and theatrical print as separate geometry decisions." },
      { id: "arrilaser_filmout", label: "Record to intermediate stock", player_task: "Track the 2K files through Arrilaser recording onto Kodak Vision Color Intermediate 5242 as the explicit digital-to-film boundary." },
      { id: "answer_release_print", label: "Build the theatrical print chain", player_task: "Separate Technicolor London's Fuji HiCon 3519D answer print from Deluxe's Kodak Vision 2383 release prints." },
      { id: "method_audit", label: "Audit production versus legacy", player_task: "Review every access, budget, digital-first, horror-influence and technology claim against whether it comes from production reporting, institutional credits or later reception." },
      { id: "comparison_audit", label: "Compare without flattening", player_task: "Compare Russian Ark, Collateral and Inland Empire through camera generation, location logic, post pipeline and editorial structure instead of treating them as one early-digital style." },
    ],
  },
] as const;

export function mergeChapterEighteenTwentyEightDaysLaterExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterEighteenTwentyEightDaysLaterExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, "28 Days Later..."] .map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_eighteen_28_days_later_verified",
      source: { list_id: "manual_chapter_eighteen_28_days_later_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
