import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterEighteenApocalyptoExpansionDefinitions = [
  {
    id: "scenario_apocalypto_2006",
    title: "Apocalypto",
    originalTitle: "Apocalypto",
    aliases: ["Mel Gibson's Apocalypto"],
    year: 2006,
    titleType: "Movie",
    runtimeMins: 138,
    directors: ["Mel Gibson"],
    genres: ["Adventure", "Drama", "Action"],
    sourceId: "bfi_apocalypto_2006",
    sourceUrl: "https://www.bfi.org.uk/film/ad7b0aef-86b2-5a0f-82ea-96f49806ee99/apocalypto",
    scenarioType: "usa_mexico_panavision_genesis_digital_jungle_low_light_practical_city_miniature_crowd_replication_vfx_colorstream_2006",
    premise: "Build Apocalypto as a source-first Chapter 18 Production Case about a 2006 US production executed largely on location in Mexico, where an early Panavision Genesis digital-cinema workflow had to survive heat, humidity, jungle, water, low light, long running action and a large practical/Miniature/VFX city pipeline. BFI and AFI record a 138-minute film directed by Mel Gibson and written by Gibson and Farhad Safinia, with Dean Semler as cinematographer, Tom Sanders as production designer, John Wright as editor and James Horner as composer; AFI records the language as Yucatec Maya and Icon Distribution as production company. American Society of Cinematographers historical documentation identifies Apocalypto as primarily photographed on the Panavision Genesis and as the first digitally photographed feature nominated for an ASC Award. Dean Semler's title-specific accounts describe using Genesis cameras in extreme Mexican heat and humidity, exploiting low-light sensitivity for firelit night work and fading jungle daylight, and using shutter/gain selectively rather than as a universal recipe. Los Angeles Times production reporting records three Genesis cameras, 50-minute HDCAM recording tapes and EFilm ColorStream monitoring that let Semler preview a color-corrected target; those details are treated as this production's documented workflow, not generic rules for every Genesis feature. The same reporting describes greens crews clearing and softening short jungle runways for barefoot performers and moving cameras, then restoring foliage between takes, making terrain preparation part of camera, stunt and performer safety. VFX supervisor Ted Rae's production account documents a deliberate practical-first city strategy: Tom Sanders' art department built major live-action sets and then a roughly 60-by-80-foot city miniature used for background extensions; selected wide crowd views were assembled from repeated passes of costumed extras, including a documented setup with roughly 650 extras, while miniature, matte-paint and compositing work expanded the city without making it a wholly synthetic environment. Production-design and costume reporting also records severe weather damage, rebuilding and reuse of a fallen tree in the village set, plus Mexican costume artisans producing feather, jewelry and material solutions. Historical consultant Richard D. Hansen's involvement and the production's archaeological research are preserved as evidence of research workflow only: they do not convert a dramatized, contested representation of Maya history into archaeological fact. The player must coordinate one sequence from evidence hierarchy, language/performance and historical-research boundaries through jungle logistics, Genesis exposure, camera mobility, practical city design, costume/makeup throughput, crowd passes, miniature/VFX integration, sound, editing, color finishing and exhibition while keeping unsupported sensor settings, per-shot lens maps, exact VFX totals, universal historical claims and later reception outside the production-fact layer.",
    requiredChoicesSeed: {
      screenplay: ["survival_chase_structure", "yucatec_maya_language_boundary", "historical_research_not_accuracy_proof", "runtime_version_boundary", "environmental_storytelling", "violence_safety_boundary"],
      camera: ["panavision_genesis_primary", "three_camera_workflow", "hdelectronic_recording", "low_light_firelight", "selective_shutter_gain", "jungle_runway_camera_access", "water_heat_humidity", "colorstream_monitoring", "practical_miniature_vfx_boundary"],
      editing: ["chase_geography", "multi_camera_continuity", "crowd_pass_composite_handoff", "miniature_background_handoff", "performance_action_safety", "runtime_versioning"],
      sound: ["yucatec_dialogue_capture", "jungle_environment", "action_foley_effects", "sound_editing_boundary", "sound_mixing_boundary", "music_boundary"],
      themes: ["film_history", "2006", "apocalypto", "mel_gibson", "dean_semler", "tom_sanders", "john_wright", "james_horner", "panavision_genesis", "digital_cinematography", "mexico", "veracruz", "jungle", "firelight", "hdecam", "efilm_colorstream", "practical_city", "miniature_city", "crowd_replication", "ted_rae", "costume_artisans", "historical_research_boundary"],
    },
    learningGoals: [
      "Explain Apocalypto as a 2006 production system rather than only as a survival narrative or historical spectacle.",
      "Identify Mel Gibson as director and Gibson with Farhad Safinia as writers from BFI and AFI records.",
      "Use BFI and AFI's 138-minute record as the playable runtime anchor while keeping alternate public runtimes as version provenance.",
      "Identify Dean Semler as cinematographer, Tom Sanders as production designer and John Wright as editor from institutional records.",
      "Identify James Horner as composer while keeping score distinct from production sound, sound editing and sound mixing.",
      "Preserve AFI's Yucatec Maya language record as a production constraint affecting performance, dialogue coaching and sound capture.",
      "Treat historical consultants and archaeological research as evidence of production process, not automatic proof of historical accuracy.",
      "Explain why dramatized chronology, ritual, costume and social representation require independent historical verification outside a production-method case.",
      "Identify Panavision Genesis as the primary digital acquisition system from ASC and Semler sources.",
      "Explain why Apocalypto matters to digital-cinematography history without claiming it was the first digitally photographed feature.",
      "Record the ASC historical distinction that it became the first digitally shot feature nominated for an ASC Award without converting an award nomination into proof of every technical detail.",
      "Explain how a Super-35-style digital cinema system could preserve familiar lensing and camera-operation practices while changing recording and monitoring workflows.",
      "Record three Genesis cameras as a title-specific production detail without assuming three-camera coverage for every setup.",
      "Record 50-minute HDCAM tapes and the large tape volume as title-specific recording evidence without generalizing it to later file-based digital cinema.",
      "Explain EFilm ColorStream monitoring as a way to preview a color-corrected target while keeping on-set monitoring distinct from final grading.",
      "Explain why immediate digital review changes exposure confidence, continuity checks and production feedback without removing the need for cinematographic judgment.",
      "Describe Semler's use of Genesis low-light capability for firelit night work without claiming every night scene used firelight alone.",
      "Describe selective shutter and gain adjustments as scene-specific tools rather than a universal action-look recipe.",
      "Explain how low-light digital capture extended usable jungle shooting time while keeping changing daylight continuity under control.",
      "Model extreme heat and humidity as camera reliability, power, media and crew-health constraints rather than mere atmosphere.",
      "Model water and waterfall work as housing, condensation, access and safety problems before treating them as spectacle.",
      "Explain why barefoot running through jungle terrain requires greens, art, stunt, camera and performer departments to coordinate the ground itself.",
      "Record the documented clearing and softening of short jungle runways as a repeatable production operation rather than evidence that the whole forest floor was altered.",
      "Explain why restoring foliage between takes is both continuity work and an attempt to preserve the visual density of the jungle.",
      "Identify Tom Sanders' practical city/set work as the foreground physical anchor for later extensions.",
      "Explain why the city was designed not to announce itself through one exposition shot but to remain embedded in action and cutting.",
      "Record the roughly 60-by-80-foot city miniature as a title-specific VFX/production-design bridge without claiming every city background used it.",
      "Explain how an art-department-built miniature can preserve design continuity better than handing an entire city to an isolated postproduction team.",
      "Describe selected crowd replication as repeated live-action passes of costumed extras rather than a default all-CG crowd solution.",
      "Use the documented roughly 650-extra multi-pass setup as an example without converting it into the film's total cast or daily background count.",
      "Explain why changing sun position matters when multiple crowd passes must later coexist in one composite.",
      "Explain why a production might accept additional rotoscoping to avoid greenscreen setup time or inconsistent lighting across crowd passes.",
      "Keep live-action set, miniature, matte-paint, crowd element and final composite as separate inspectable layers.",
      "Explain how severe weather can force rebuilds and redesign rather than merely delaying photography.",
      "Use the fallen-tree village-set adaptation as an example of production design absorbing an uncontrolled event into the built world.",
      "Describe Mayes C. Rubeo's use of Mexican costume professionals and artisans as a production-resource network rather than a claim of ethnographic authenticity.",
      "Explain how lighter or cheaper substitute materials can reproduce an intended screen appearance while protecting performers and budget.",
      "Separate costume construction, prosthetic makeup, body decoration and performance endurance as different production responsibilities.",
      "Use the Academy's makeup, sound-editing and sound-mixing nominations only as downstream reception evidence and credit confirmation, not proof of how each effect was made.",
      "Keep Yucatec dialogue, jungle ambience, action effects, Foley, score, sound editing and re-recording as distinct sound layers.",
      "Identify John Wright's editorial responsibility while keeping camera, stunt, VFX and sound decisions as separate handoffs into the cut.",
      "Explain how chase geography depends on eyelines, terrain continuity, screen direction, pace and safe repeatability across many locations.",
      "Explain why a multi-camera digital workflow can increase coverage while also increasing media management, matching and editorial complexity.",
      "Reject unsupported claims about exact per-shot focal lengths, lens serials, ISO/EI values, shutter angles, gain values, filters, codecs, sensor settings or color transforms unless title-specific evidence establishes them.",
      "Reject unsupported claims about the film-wide number of VFX shots, digital doubles, CG crowd agents or exact miniature usage unless a source establishes them.",
      "Reject the inference that practical foreground sets make every background practical, or that digital compositing makes the city primarily synthetic.",
      "Explain why Apocalypto is historically useful as a transitional digital case: digital acquisition, familiar camera craft, practical construction, miniature photography and compositing are interdependent.",
      "Build a production plan that protects performers, extras, camera crew and equipment under jungle heat, water, mud, barefoot running and long makeup/costume preparation.",
      "Connect evidence uncertainty to production choices: when a title-specific source does not establish a parameter, keep it unknown rather than filling the gap with a plausible industry default.",
      "Distinguish production-history analysis from moral, political and archaeological evaluation while leaving room for those separate analyses elsewhere in the Film Study.",
    ],
    phases: [
      { id: "evidence_hierarchy", label: "Map the evidence hierarchy", player_task: "Separate BFI/AFI credits, ASC/Semler camera evidence, Ted Rae VFX testimony, production-design/costume reporting and later reception before converting details into production facts." },
      { id: "historical_boundary", label: "Set the historical boundary", player_task: "Record research and consultant participation as production process while flagging dramatized Maya history for independent archaeological and historiographic review." },
      { id: "runtime_language", label: "Lock runtime and language", player_task: "Use the institutional 138-minute and Yucatec Maya records as production anchors while preserving alternate versions separately." },
      { id: "production_network", label: "Map the production network", player_task: "Separate direction, cinematography, production design, costume, makeup, VFX, editorial, sound and music responsibilities before scheduling handoffs." },
      { id: "jungle_scout", label: "Audit jungle terrain", player_task: "Map heat, humidity, mud, water, vegetation density, barefoot routes, camera paths, reset zones and emergency access before blocking action." },
      { id: "runway_preparation", label: "Prepare running lanes", player_task: "Coordinate greens, stunts, camera and performers to soften and clear only the terrain needed for safe repeatable running and moving-camera work." },
      { id: "foliage_reset", label: "Reset the jungle", player_task: "Restore vines and leaves after takes so safety modifications do not flatten the visual continuity of the forest." },
      { id: "genesis_package", label: "Configure the Genesis package", player_task: "Plan the documented Genesis-centered acquisition system and three-camera capacity without assuming every scene needs simultaneous multi-camera coverage." },
      { id: "recording_media", label: "Plan HDCAM recording", player_task: "Treat 50-minute HDCAM tapes as finite production media requiring labeling, verification, turnover and backup discipline." },
      { id: "colorstream_monitoring", label: "Build the monitoring path", player_task: "Use the documented EFilm ColorStream preview path to communicate an intended corrected image without confusing it with final grading." },
      { id: "low_light_tests", label: "Test jungle low light", player_task: "Test fading daylight and firelit conditions before choosing gain or shutter changes and keep undocumented numeric settings open." },
      { id: "firelight_night", label: "Stage firelit night", player_task: "Exploit documented low-light capability where appropriate while protecting faces, continuity, flame safety and the difference between source light and exposure strategy." },
      { id: "shutter_gain_boundary", label: "Control shutter and gain", player_task: "Use Semler's documented selective changes for motion or fading light only after testing; do not impose one setting across the chase." },
      { id: "heat_humidity", label: "Protect cameras in climate", player_task: "Build heat, humidity, power, condensation and media-handling checks into the camera day instead of assuming electronics are invulnerable." },
      { id: "waterfall_housing", label: "Engineer water work", player_task: "Coordinate housing, temperature change, lens fogging, rigging and rescue access before committing camera and performer to waterfall or river setups." },
      { id: "village_resilience", label: "Plan resilient practical sets", player_task: "Design drainage, repair capacity and continuity protocols so storms, flooding or fallen vegetation can be absorbed without losing the production world." },
      { id: "city_foreground", label: "Build the practical city anchor", player_task: "Use Sanders' principal physical sets as performer-facing foreground geography and define exactly where extensions begin." },
      { id: "city_reveal", label: "Keep the city inside action", player_task: "Plan coverage so scale is accumulated through movement and cutting rather than relying on one effects-heavy reveal." },
      { id: "miniature_city", label: "Photograph the city miniature", player_task: "Use the documented large miniature for selected backgrounds, matching camera data, light direction, atmosphere and perspective to live-action plates." },
      { id: "crowd_pass_plan", label: "Design crowd replication", player_task: "Break selected wide crowds into repeatable live-action passes with explicit group positions, timing and wardrobe continuity before photography begins." },
      { id: "sun_match", label: "Protect multi-pass sunlight", player_task: "Schedule crowd passes tightly enough that sun direction and shadow length remain compositable, especially under near-overhead tropical light." },
      { id: "roto_vs_greenscreen", label: "Choose extraction strategy", player_task: "Balance greenscreen setup time against later rotoscoping and lighting consistency instead of assuming chroma key is always cheaper or cleaner." },
      { id: "costume_artisans", label: "Scale costume fabrication", player_task: "Coordinate Mexican costume professionals and specialist artisans so hero and background looks can be repeated, repaired and tracked across a large cast." },
      { id: "material_substitution", label: "Choose screen-safe materials", player_task: "Use substitute jewelry or adornment materials where documented visual goals, weight, availability or cost require them, and preserve the distinction from archaeological originals." },
      { id: "makeup_throughput", label: "Schedule makeup throughput", player_task: "Plan early calls, stations, continuity records and performer recovery for elaborate body decoration and prosthetic work without deriving exact daily counts from isolated reports." },
      { id: "action_continuity", label: "Protect chase geography", player_task: "Track screen direction, terrain, sweat, mud, wounds, props and costume damage across repeated action setups and multiple cameras." },
      { id: "production_sound", label: "Capture Yucatec dialogue", player_task: "Plan intelligible dialogue and wild tracks around jungle noise, movement, water and large crowds while leaving unsupported recorder and microphone models unknown." },
      { id: "sound_post", label: "Build the action sound layers", player_task: "Keep dialogue, ambience, Foley, designed effects, sound editing, score and re-recording as separate inspectable handoffs." },
      { id: "editing", label: "Assemble the chase", player_task: "Use John Wright's editorial layer to preserve geography, acceleration and performance while reconciling multi-camera material and VFX-dependent shots." },
      { id: "vfx_composite", label: "Composite city and crowds", player_task: "Combine practical foreground, live-action crowd passes, miniature backgrounds and matte/composite work without erasing the provenance of each element." },
      { id: "color_finish", label: "Carry the look to final", player_task: "Use the on-set corrected preview as intent evidence, then treat final color finishing as a later controlled stage rather than assuming monitor appearance equals release master." },
      { id: "reception_boundary", label: "Separate reception from production", player_task: "Keep ASC and Academy nominations downstream from production evidence: useful for historical reception and credits, not as substitutes for craft documentation." },
      { id: "unknowns_register", label: "Register technical unknowns", player_task: "Leave per-shot lenses, exact EI/ISO, filters, shutter/gain values, codecs, total VFX count, digital-double use and final mastering parameters unknown unless title-specific evidence establishes them." },
    ],
  },
] as const;

export function mergeChapterEighteenApocalyptoExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterEighteenApocalyptoExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_eighteen_apocalypto_verified",
      source: { list_id: "manual_chapter_eighteen_apocalypto_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
