import assert from "node:assert/strict";
import test from "node:test";

import { chapterEighteenGetOutExpansionDefinitions } from "./chapterEighteenGetOutExpansion.js";

test("Chapter 18 materializes Get Out as a source-first low-budget social-horror production case", () => {
  assert.equal(chapterEighteenGetOutExpansionDefinitions.length, 1);
  const film = chapterEighteenGetOutExpansionDefinitions[0];
  assert.equal(film.id, "scenario_get_out_2017");
  assert.equal(film.year, 2017);
  assert.equal(film.runtimeMins, 103);
  assert.deepEqual(film.directors, ["Jordan Peele"]);
  assert.ok(film.scenarioType.includes("blumhouse_low_budget_social_horror") && film.scenarioType.includes("23_day") && film.scenarioType.includes("alexa_mini"));
  assert.ok(film.scenarioType.includes("angeniuex") && film.scenarioType.includes("prores4444") && film.scenarioType.includes("sunken_place"));
  assert.ok(film.premise.includes("BFI and AFI") && film.premise.includes("103-minute") && film.premise.includes("104- or 105-minute"));
  assert.ok(film.premise.includes("23-day") && film.premise.includes("California") && film.premise.includes("Alabama"));
  assert.ok(film.premise.includes("practical real locations") && film.premise.includes("civic center") && film.premise.includes("200-fps"));
  assert.ok(film.premise.includes("ARRI Alexa Mini") && film.premise.includes("3.2K ProRes 4444") && film.premise.includes("standard 2K cinema finish"));
  assert.ok(film.premise.includes("two cameras on literally every setup") && film.premise.includes("Angénieux compact zoom"));
  assert.ok(film.premise.includes("four production LUTs") && film.premise.includes("MAX Menace Arm"));
  assert.ok(film.premise.includes("Gregory Plotkin") && film.premise.includes("negative space") && film.premise.includes("alternate endings"));
  assert.ok(film.premise.includes("Michael Abels") && film.premise.includes("gospel horror") && film.premise.includes("Swahili"));
  assert.ok(film.premise.includes("exact department budgets") && film.premise.includes("universal exposure settings") && film.premise.includes("wire-rig geometry"));
  assert.ok(film.premise.includes("production-sound recorder/microphone packages") && film.premise.includes("final DI node trees"));
  assert.ok(film.requiredChoicesSeed.screenplay.includes("social_horror_authorship"));
  assert.ok(film.requiredChoicesSeed.camera.includes("alexa_mini") && film.requiredChoicesSeed.camera.includes("3_2k_prores4444"));
  assert.ok(film.requiredChoicesSeed.camera.includes("exact_lens_map_bounded"));
  assert.ok(film.requiredChoicesSeed.editing.includes("negative_space") && film.requiredChoicesSeed.editing.includes("alternate_endings"));
  assert.ok(film.requiredChoicesSeed.sound.includes("gospel_horror") && film.requiredChoicesSeed.sound.includes("production_sound_hardware_unknown"));
  assert.ok(film.learningGoals.some((goal) => goal.includes("103-minute") && goal.includes("104- and 105-minute")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("23-day principal-photography schedule")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("intended California shoot") && goal.includes("Alabama")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("filming geography") && goal.includes("story geography")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("MAX Menace Arm") && goal.includes("universal lighting recipe")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("ARRI Alexa Mini") && goal.includes("cramped practical interiors")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("3.2K ProRes 4444") && goal.includes("2K cinema finish")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Angénieux compact zooms") && goal.includes("complete prime/zoom inventory")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("two cameras on literally every setup")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("four documented LUT categories")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("trailer grades") && goal.includes("final DI")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("civic center") && goal.includes("stage")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("200-fps Alexa Mini") && goal.includes("wire suspension")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Gregory Plotkin") && goal.includes("horror/comedy timing")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("negative space") && goal.includes("discomfort")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Avid") && goal.includes("Sunken Place resizing")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("alternate-ending") && goal.includes("version-control")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("test-screening response") && goal.includes("mechanically dictated")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Rusty Smith") && goal.includes("production designer")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Michael Abels") && goal.includes("feature-film scoring")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("'gospel horror'") && goal.includes("documented conceptual response")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Swahili choral warning material") && goal.includes("Chris")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("5.1-oriented score delivery") && goal.includes("final dub stem map")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("production sound mixer hardware") && goal.includes("unresolved")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("uncertainty register") && goal.includes("test-screening score history")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("closing production audit") && goal.includes("Sunken Place practical/VFX handoff")));
  assert.ok(film.phases.find((phase) => phase.id === "runtime_version")?.player_task.includes("103 minutes"));
  assert.ok(film.phases.find((phase) => phase.id === "schedule_lock")?.player_task.includes("23 principal-photography days"));
  assert.ok(film.phases.find((phase) => phase.id === "camera_package")?.player_task.includes("ARRI Alexa Mini"));
  assert.ok(film.phases.find((phase) => phase.id === "recording_format")?.player_task.includes("3.2K ProRes 4444"));
  assert.ok(film.phases.find((phase) => phase.id === "lut_package")?.player_task.includes("city") && film.phases.find((phase) => phase.id === "lut_package")?.player_task.includes("estate-night"));
  assert.ok(film.phases.find((phase) => phase.id === "sunken_place_practical")?.player_task.includes("200-fps"));
  assert.ok(film.phases.find((phase) => phase.id === "ending_versions")?.player_task.includes("Rod-rescue"));
  assert.ok(film.phases.find((phase) => phase.id === "sound_unknowns")?.player_task.includes("microphones"));
  assert.ok(film.phases.find((phase) => phase.id === "uncertainty_register")?.player_task.includes("wire geometry"));
  assert.ok(film.learningGoals.length >= 60);
  assert.ok(film.phases.length >= 38);
});