import assert from "node:assert/strict";
import test from "node:test";

import { chapterEighteenHolyMotorsExpansionDefinitions } from "./chapterEighteenHolyMotorsExpansion.js";

test("Chapter 18 materializes Holy Motors as a source-first fast digital Paris performance-transformation case", () => {
  assert.equal(chapterEighteenHolyMotorsExpansionDefinitions.length, 1);
  const film = chapterEighteenHolyMotorsExpansionDefinitions[0];
  assert.equal(film.id, "scenario_holy_motors_2012");
  assert.equal(film.year, 2012);
  assert.equal(film.runtimeMins, 115);
  assert.deepEqual(film.directors, ["Leos Carax"]);
  assert.ok(film.scenarioType.includes("low_budget") && film.scenarioType.includes("paris") && film.scenarioType.includes("red_epic"));
  assert.ok(film.scenarioType.includes("motion_capture") && film.scenarioType.includes("datamoshing") && film.scenarioType.includes("vfx"));
  assert.ok(film.premise.includes("Pierre Grise Production") && film.premise.includes("Pandora Film") && film.premise.includes("WDR-Arte"));
  assert.ok(film.premise.includes("EU MEDIA programme") && film.premise.includes("Medienboard Berlin-Brandenburg"));
  assert.ok(film.premise.includes("inexpensive film quickly in France") && film.premise.includes("pre-selected actor"));
  assert.ok(film.premise.includes("Paris, little money, digital, Denis Lavant and no dailies"));
  assert.ok(film.premise.includes("RED Epic") && film.premise.includes("nocturnal") && film.premise.includes("low-light"));
  assert.ok(film.premise.includes("640 ISO night") && film.premise.includes("800 ISO day") && film.premise.includes("attributed testimony"));
  assert.ok(film.premise.includes("Angénieux 25-250 HR") && film.premise.includes("exact prime set") && film.premise.includes("shot-to-lens allocation"));
  assert.ok(film.premise.includes("stretch limousine") && film.premise.includes("mobile dressing room") && film.premise.includes("continuity hub"));
  assert.ok(film.premise.includes("Bernard Floch") && film.premise.includes("Jean-Christophe Spadaccini") && film.premise.includes("Denis Gastou"));
  assert.ok(film.premise.includes("Diane Sorin") && film.premise.includes("Jacques Perconte") && film.premise.includes("Olivier Marci"));
  assert.ok(film.premise.includes("Thierry Delobel") && film.premise.includes("Alexandre Bon") && film.premise.includes("Bérengère Dominguez"));
  assert.ok(film.premise.includes("undocumented motion-capture hardware") && film.premise.includes("undocumented VFX software"));
  assert.ok(film.requiredChoicesSeed.camera.includes("red_epic"));
  assert.ok(film.requiredChoicesSeed.camera.includes("prime_set_unknowns"));
  assert.ok(film.requiredChoicesSeed.editing.includes("codec_media_unknowns"));
  assert.ok(film.requiredChoicesSeed.sound.includes("sound_equipment_unknowns"));
  assert.ok(film.learningGoals.some((goal) => goal.includes("115-minute") && goal.includes("2012 competition")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("inexpensive film") && goal.includes("pre-selected actor")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("no-dailies") && goal.includes("technical QC")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("RED Epic") && goal.includes("submodel")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("640 ISO night") && goal.includes("800 ISO day") && goal.includes("attributed")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Angénieux 25-250 HR") && goal.includes("individual shots")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("exact Zeiss prime package") && goal.includes("lower-confidence")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("stretch limousine") && goal.includes("mobile dressing room")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Bernard Floch") && goal.includes("Jean-Christophe Spadaccini")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("motion-capture appointment") && goal.includes("entire film")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Jacques Perconte") && goal.includes("datamoshing")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Thierry Delobel") && goal.includes("Alexandre Bon") && goal.includes("Bérengère Dominguez")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("motion capture") && goal.includes("conventional VFX") && goal.includes("datamoshing")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("exact budget") && goal.includes("RED submodel") && goal.includes("motion-capture hardware")));
  assert.ok(film.phases.find((phase) => phase.id === "constraint_brief")?.player_task.includes("inexpensive"));
  assert.ok(film.phases.find((phase) => phase.id === "red_epic")?.player_task.includes("RED Epic"));
  assert.ok(film.phases.find((phase) => phase.id === "no_dailies")?.player_task.includes("technical QC"));
  assert.ok(film.phases.find((phase) => phase.id === "mocap_stage")?.player_task.includes("marked body performance"));
  assert.ok(film.phases.find((phase) => phase.id === "datamoshing")?.player_task.includes("Jacques Perconte"));
  assert.ok(film.phases.find((phase) => phase.id === "unknowns_register")?.player_task.includes("RED submodel"));
  assert.ok(film.learningGoals.length >= 50);
  assert.ok(film.phases.length >= 30);
});
