import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterEighteenCacheExpansionDefinitions = [
  {
    id: "scenario_cache_2005",
    title: "Caché",
    originalTitle: "Caché",
    aliases: ["Cache", "Hidden"],
    year: 2005,
    titleType: "Movie",
    runtimeMins: 117,
    directors: ["Michael Haneke"],
    genres: ["Drama", "Mystery", "Thriller"],
    sourceId: "cannes_cache_2005",
    sourceUrl: "https://www.festival-cannes.com/en/f/cache/",
    scenarioType: "france_austria_germany_italy_hd_video_surveillance_image_parity_static_long_take_reflective_lighting_filmout_2005",
    premise: "Build Caché as a source-first Chapter 18 Production Case about a 2005 European production in which acquisition format, surveillance imagery, camera placement and post-production are deliberately inseparable from the story's uncertainty about who is looking. Festival de Cannes records Michael Haneke's film as a 117-minute France/Austria/Germany/Italy production and preserves the festival production-company network; Les Films du Losange separately lists Les Films du Losange, Wega Film, Bavaria Film and BIM Distribuzione as producers with Arte France Cinéma, France 3 Cinéma and ORF Film/Fernseh-Abkommen as coproducers. The distributor record gives 1h55, while Cannes and Austrian Films give 117 minutes, so runtime is preserved as version/exhibition provenance rather than silently normalized. Christian Berger's production testimony in American Cinematographer explains that the film initially tested a film/digital mixture but moved to all-digital acquisition because the surveillance tapes and narrative reality needed to be visually indistinguishable. Berger identifies Sony HDW-750 and HDW-F900 cameras with Zeiss DigiPrimes, 16:9 capture, and a later record to 35mm with a 1.85 hard matte. This technical choice is not treated as frictionless progress: Berger reports repeated camera failures, focus/viewfinder problems and six camera bodies cycling through production, while a later interview describes the HD shoot as technically punishing. American Cinematographer records five weeks of shooting in Paris and four in Vienna; Éclair made video safety copies, Listo Film and Video handled color correction and the final transfer to 35mm, and selected 35mm prints were generated during production to assess electronic image problems. Berger also describes digital grading on a da Vinci 2K with a Sony monitor. The finished image system therefore belongs to early-2000s digital convergence: HD acquisition, monitor-based grading, laboratory film-out and theatrical 35mm exhibition all coexist. BFI Sight and Sound identifies Caché as Haneke's first use of high-definition video and explains why identical image quality between threatening tapes and narrative scenes makes image provenance unstable for the viewer. The film's long, usually static wide and medium-wide shots are production choices rather than proof that every scene is surveillance footage. Berger's CRLS reflected-light system is also a documented part of the case: American Cinematographer describes a low connected load, reflector-based control and two projectors for the recurring house exterior. BFI programme notes preserve a larger department map including Christian Berger, gaffers Walter Stöger and Olivier Neveu, visual-effects supervisor Geoffrey Kleindorfer, editors Michael Hudecek and Nadine Muse, French and Austrian art directors Emmanuel de Chauvigny and Christoph Kanter, costume designer Lisy Christl, colour timing by Franz Rabl, colourist Willi Willinger, Listo-Film, Éclair and CinePostproduktion Geyer laboratories, production sound recordist Jean-Paul Mugel, re-recording mixer Jean-Pierre LaForce and sound effects by Pascal Chauvin. These credits establish differentiated production and post departments without licensing invented equipment or shot-specific effects methods. The player must therefore coordinate a scene from script and exact camera position through HD capture, reflected lighting, performance, production sound, editing, color correction, film-out and exhibition while keeping narrative interpretation, festival awards and later critical canon status outside the production-evidence layer.",
    requiredChoicesSeed: {
      screenplay: ["surveillance_without_solution", "image_provenance_ambiguity", "colonial_memory_boundary", "offscreen_information", "withheld_explanation", "runtime_version_boundary"],
      camera: ["hd_acquisition", "sony_hdw_750_f900", "zeiss_digiprime", "six_camera_reliability", "static_wide_frame", "surveillance_reality_parity", "crls_reflected_light", "filmout_boundary"],
      editing: ["long_take_duration", "tape_playback_reveal", "replay_rewind_boundary", "editorial_withholding", "filmout_post_handoff", "runtime_versioning"],
      sound: ["production_sound", "re_recording", "sound_effects", "distant_ambience", "offscreen_voice", "music_absence_boundary"],
      themes: ["film_history", "2005", "cache", "hidden", "michael_haneke", "christian_berger", "france", "austria", "germany", "italy", "117_minutes_cannes", "115_minutes_distributor", "high_definition_video", "sony_hdw_750", "sony_hdw_f900", "zeiss_digiprime", "static_long_take", "surveillance_image", "crls", "paris", "vienna", "da_vinci_2k", "35mm_filmout", "eclair", "listo_film", "sound_post"],
    },
    learningGoals: [
      "Explain Caché as a 2005 digital-convergence production system rather than only as a surveillance-themed story.",
      "Identify Michael Haneke as writer-director from the Cannes record.",
      "Preserve Cannes' France/Austria/Germany/Italy production geography without collapsing it into a single-country label.",
      "Use Cannes' 117-minute record as the playable runtime anchor while preserving the distributor's 1h55 record as separate provenance.",
      "Identify Les Films du Losange, Wega Film, Bavaria Film and BIM Distribuzione as the distributor-listed producer network.",
      "Keep Arte France Cinéma, France 3 Cinéma and ORF coproduction roles distinct from distribution and international sales.",
      "Explain why Haneke and Berger wanted threatening videotapes and narrative reality to share the same image quality.",
      "Record Berger's account that a mixed film/digital approach was tested and rejected for the desired image parity.",
      "Identify Sony HDW-750 and HDW-F900 cameras as the American Cinematographer-documented acquisition bodies.",
      "Identify Zeiss DigiPrimes as the documented lens family without generalizing that every focal length was equally available.",
      "Explain that the picture was captured 16:9 and later recorded to 35mm with a 1.85 hard matte.",
      "Separate HD acquisition from 35mm exhibition so neither is mislabeled as the sole production format.",
      "Record the five-week Paris and four-week Vienna production schedule documented by Berger.",
      "Explain why early HD infrastructure created reliability, focus and viewfinder problems during production.",
      "Record that six camera bodies were used as equipment failed without converting that fact into a claim that six cameras photographed scenes simultaneously.",
      "Explain how camera unreliability creates continuity, testing, backup and schedule responsibilities.",
      "Distinguish long static framing from an inference that every static shot is diegetic surveillance footage.",
      "Explain why the opening image can change ontological status without changing photographic texture.",
      "Use BFI's analysis to distinguish image provenance from image quality.",
      "Explain how long wide and medium-wide shots shift tension toward blocking, duration and offscreen expectation.",
      "Treat camera placement as a narrative decision with measurable spatial consequences.",
      "Explain Berger's CRLS as a reflected-light system rather than conventional direct fixture placement at every subject.",
      "Record the low connected electrical load described for Caché without turning it into a universal property of all CRLS shoots.",
      "Explain the documented use of two projectors for the recurring house exterior while avoiding invented fixture maps for other scenes.",
      "Keep gaffer, cinematographer and director responsibilities distinct inside the lighting workflow.",
      "Identify Éclair's video-safety role separately from Listo Film and Video's color-correction and final film-transfer work.",
      "Explain why selected 35mm prints were made during production to evaluate electronic image problems.",
      "Record the da Vinci 2K grading environment and Sony monitoring as a documented post-production step.",
      "Treat monitor-to-film correspondence as a calibration and judgment problem rather than an automatic conversion.",
      "Identify Franz Rabl's colour-timing credit and Willi Willinger's colourist credit from BFI's compiled production notes.",
      "Keep Listo-Film, Éclair and CinePostproduktion Geyer laboratory credits distinct where their exact task boundaries differ.",
      "Identify Michael Hudecek and Nadine Muse as editors and keep additional editing credits separate.",
      "Explain how replay, rewind and playback can reveal diegetic tape status through editing rather than picture-quality differences.",
      "Model withholding as an editorial and directing strategy without inventing a solved identity for the tape-maker.",
      "Identify Emmanuel de Chauvigny and Christoph Kanter as the France/Austria art-direction leads in BFI's compiled credits.",
      "Identify Lisy Christl as costume designer without inventing undocumented wardrobe-fabrication procedures.",
      "Recognize that visual-effects and special-effects departments are credited even though the film avoids spectacle-led presentation.",
      "Reject the inference that a restrained visual style means there was no VFX or special-effects work.",
      "Identify Jean-Paul Mugel as production sound recordist and Jean-Pierre LaForce as re-recording mixer.",
      "Keep production sound, re-recording and Pascal Chauvin's sound-effects work as separate handoffs.",
      "Explain how distant traffic, birds, room tone and offscreen voices can carry tension without a conventional thriller score.",
      "Keep the absence or restraint of non-diegetic music separate from the claim that the film has no designed soundtrack.",
      "Separate story-world surveillance technology from the actual production camera system.",
      "Separate 2005 Cannes Best Director recognition from evidence about how the film was photographed or finished.",
      "Reject claims that Caché invented surveillance cinema, digital features, static long takes, self-reflexive video or film-out workflows.",
      "Audit every claim about exact recording codec, tape stock, camera menu settings, focal length per shot, sound recorder, microphone, VFX technique and laboratory calibration against a title-specific source before promoting it to production fact.",
      "Explain why Caché is historically useful as an early HD feature precisely because its digital workflow was difficult rather than frictionless.",
      "Connect technical uncertainty, production backup strategy and aesthetic intention without treating equipment failure as artistic intent.",
    ],
    phases: [
      { id: "evidence_hierarchy", label: "Map the evidence hierarchy", player_task: "Separate Cannes metadata, distributor production records, Berger craft testimony, BFI formal analysis and later reception before converting details into production facts." },
      { id: "runtime_versions", label: "Lock runtime provenance", player_task: "Keep Cannes/Austrian Films 117 minutes separate from Les Films du Losange's 1h55 record and use 117 only as the canonical playable anchor." },
      { id: "coproduction_map", label: "Map the European production network", player_task: "Separate producers, coproducers, national production labels, laboratories and distributors rather than treating the four-country production as one undifferentiated company." },
      { id: "surveillance_premise", label: "Protect the unsolved surveillance premise", player_task: "Build the threat around received images without inventing a production-authorized solution to who records or sends the tapes." },
      { id: "image_parity_test", label: "Test image parity", player_task: "Recreate the production problem that led Berger and Haneke from a mixed film/digital test to all-digital acquisition so tape and reality could share texture." },
      { id: "camera_package", label: "Map the HD camera package", player_task: "Track the documented HDW-750/F900 and DigiPrime package while leaving unsupported codec, deck and menu-setting claims open." },
      { id: "camera_reliability", label: "Plan equipment redundancy", player_task: "Use Berger's six-body failure history to create backup, test and replacement procedures without claiming six-camera simultaneous coverage." },
      { id: "static_frame", label: "Design a static wide frame", player_task: "Choose a camera position whose duration and offscreen space remain dramatically active even when little moves inside the frame." },
      { id: "tape_reality_boundary", label: "Blur image provenance", player_task: "Make tape and narrative imagery photographically equivalent, then let playback context rather than degraded texture reveal their status." },
      { id: "blocking_duration", label: "Block for duration", player_task: "Stage entrances, exits, pauses and distant background action so a long unmoving shot remains precise rather than inert." },
      { id: "crls_plan", label: "Build reflected-light logic", player_task: "Model Berger's CRLS as projector-plus-reflector control and keep fixture claims limited to documented examples." },
      { id: "house_exterior_light", label: "Light the recurring house exterior", player_task: "Use the documented two-projector example to coordinate foreground house and distant buildings without inventing a full lighting diagram." },
      { id: "gaffer_handoff", label: "Map lighting responsibility", player_task: "Separate Berger's image/CRLS design from gaffer implementation and director framing requirements." },
      { id: "paris_schedule", label: "Plan Paris production", player_task: "Use the documented five-week Paris block to schedule locations, company moves and exterior continuity." },
      { id: "vienna_schedule", label: "Plan Vienna production", player_task: "Use the documented four-week Vienna block and keep production geography distinct from story geography." },
      { id: "production_sound", label: "Capture production sound", player_task: "Give Jean-Paul Mugel's production-sound function its own deliverables and leave exact recorder/microphone models unknown." },
      { id: "offscreen_sound", label: "Design offscreen tension", player_task: "Build distant ambience, room tone and unseen activity so sound extends static frames beyond their visible borders." },
      { id: "editing_playback", label: "Reveal playback editorially", player_task: "Use rewind, replay and cuts to monitoring contexts to change the status of an image without changing its acquisition texture." },
      { id: "editorial_withholding", label: "Preserve uncertainty", player_task: "Cut information so causal ambiguity remains intentional without becoming an accidental continuity error." },
      { id: "art_direction", label: "Map dual art-direction teams", player_task: "Separate France and Austria art-direction responsibilities and avoid inventing which uncredited room or street each team built or dressed." },
      { id: "costume_continuity", label: "Track costume continuity", player_task: "Use Lisy Christl's credited department to support chronological and playback continuity without inventing fabrication specifics." },
      { id: "vfx_boundary", label: "Keep effects visible in the workflow", player_task: "Preserve credited VFX/special-effects departments while refusing unsupported shot-level technique claims." },
      { id: "video_safeties", label: "Create video safety copies", player_task: "Map Éclair's documented video-safety role as a separate custody step." },
      { id: "diagnostic_prints", label: "Evaluate 35mm test prints", player_task: "Use selected 35mm prints to assess moiré, interference, contour and focus problems before final delivery." },
      { id: "digital_grade", label: "Grade the HD image", player_task: "Model the da Vinci 2K/Sony-monitor grading step and explicitly track monitor-to-film uncertainty." },
      { id: "filmout", label: "Transfer to 35mm", player_task: "Carry the graded HD master into Listo's documented final 35mm transfer with the 1.85 hard-matte exhibition boundary intact." },
      { id: "lab_roles", label: "Map laboratory roles", player_task: "Keep Éclair, Listo-Film and CinePostproduktion Geyer credits distinct unless a source explicitly assigns the same operation to more than one facility." },
      { id: "re_recording", label: "Build the final sound mix", player_task: "Keep Jean-Pierre LaForce's re-recording role distinct from location recording and effects creation." },
      { id: "sound_effects", label: "Design restrained effects", player_task: "Treat Pascal Chauvin's effects work as authored sound craft even when the soundtrack avoids spectacle." },
      { id: "version_provenance", label: "Separate production from reception", player_task: "Keep festival awards, later criticism and distribution runtimes downstream from production evidence." },
      { id: "unknowns_register", label: "Register technical unknowns", player_task: "Keep exact recording codec, tape stock, per-shot focal lengths, camera settings, sound equipment, shot-specific VFX and laboratory calibration values unknown unless title-specific evidence establishes them." },
    ],
  },
] as const;

export function mergeChapterEighteenCacheExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterEighteenCacheExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_eighteen_cache_verified",
      source: { list_id: "manual_chapter_eighteen_cache_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
