import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterNineteenKPopDemonHuntersExpansionDefinitions = [
  {
    id: "scenario_kpop_demon_hunters_2025",
    title: "KPop Demon Hunters",
    originalTitle: "KPop Demon Hunters",
    aliases: ["KPop Demon Hunters", "K-Pop Demon Hunters"],
    year: 2025,
    titleType: "Movie",
    runtimeMins: 100,
    directors: ["Maggie Kang", "Chris Appelhans"],
    genres: ["Animation", "Action", "Fantasy", "Music"],
    sourceId: "sony_kpop_demon_hunters_spa_imageworks_2026",
    sourceUrl: "https://www.sony.com/en/SonyInfo/technology/stories/entries/kpop_demon_hunters/",
    scenarioType: "award_priority_oscar_animated_feature_original_song_maggie_kang_chris_appelhans_michelle_wong_spa_imageworks_josh_beveridge_mingjue_helen_chen_nathan_schauf_unreal_engine_rough_layout_chibi_face_motion_blur_spheres_hand_keyed_animation_no_full_mocap_kdrama_lighting_anime_exaggeration_seoul_visualization_avid_media_composer_music_first_edit_global_kpop_song_pipeline_2025",
    premise: "Build KPop Demon Hunters as Chapter 19's next award-priority production case because the Academy records 2026 Oscar wins for Best Animated Feature and Best Original Song for Golden. Awards establish priority and reception, not the production workflow. BBFC records the original Netflix VOD/streaming version at 99 minutes 37 seconds, so the playable record rounds to 100 minutes. BBFC separately records a 95m29s sing-along cinema event, a 100-minute sing-along VOD version and a later 96-minute physical-media/VOD master; those are version-provenance records and must not be collapsed into one frame-identical master. Netflix identifies Maggie Kang and Chris Appelhans as directors and the film as produced in partnership with Sony Pictures Animation. Sony's direct SPA/Imageworks technology account describes a production model in which SPA explored story, character and visual design while Sony Pictures Imageworks translated those ambitions into geometry, animation and rendering systems. The core visual challenge was to combine anime-style graphic exaggeration, K-drama-like photographic softness/glamour and the physical expressiveness of live-action dance without allowing one system to erase the others. Animation director Josh Beveridge documents a custom Chibi Face system: interchangeable facial features, blend-shapes and meshes could be swapped and displaced beyond realistic facial geometry to reproduce 2D/manga expressive language inside a 3D character pipeline. The same direct Sony account documents Motion-Blur Spheres, a localized control system that allowed animators to determine where motion blur appeared so characters could stay crisp against extremely soft lighting. The team rejected full motion capture as the default dance solution and instead retained hand-keyed animation so performance timing and stylized poses remained artist-controlled; live-action dance informed movement, but the locked evidence does not support calling the feature a mocap-driven production. Sony also documents a major layout change: SPA's Sandbox team and Imageworks integrated Unreal Engine into pre-production and Rough Layout so directors could explore lighting, choreography, scale, lenses and camera moves interactively rather than waiting for overnight renders. On this film the real-time workflow was used to scout Seoul lighting, plan the bathhouse action and populate/visualize Jamsil Olympic Stadium. This evidence is bounded to visualization, lighting exploration and Rough Layout; it does not prove Unreal Engine was the final renderer for every shot. Production designer Mingjue Helen Chen and animation director Beveridge describe a K-drama-influenced soft-lighting strategy that exposed rather than hid animation problems, alongside deliberately tertiary color palettes rather than simple primary-color coding. The Honmoon, weapons, demon-world magenta and character wardrobes were designed as narrative systems. Chen documents Korean-tradition references such as norigae and character-specific color nuance, while character designer Ami Thompson describes weapons as iridescent, flowing visualizations of musical energy. Beveridge states the costume-design effort included roughly 200-300 drawings across the film and 23 costume changes for Rumi alone; those figures are design-scale anchors, not a complete costume asset inventory. The music pipeline was equally structural. Netflix's direct interviews document years of cross-continental collaboration among the filmmakers, executive producer Michelle Wong, THEBLACKLABEL and other songwriters/producers, including weekly meetings spanning Korea, New York, Los Angeles and Bangkok. The song team had to satisfy two simultaneous constraints: songs had to function as authentic, commercially credible K-pop and also carry character, exposition and plot. Golden began from a seven-page filmmakers' memo that mapped dramatic requirements before songwriting. This makes music a story-development and editorial dependency, not a post-production layer added after picture lock. Editor Nathan Schauf describes the animated editorial process in Avid Media Composer beginning with storyboard JPEGs, temp dialogue, SFX and music, then replacing/stacking those stages with Layout, Animation and Lighting as shots matured. Because music timing was structural, visual or audio changes could trigger corresponding CG or music changes. Schauf also documents heavy use of Media Composer multicam grouping and AAF handoff to Pro Tools. This evidence establishes Avid-centered editorial workflow and Pro Tools interchange, but not a complete edit-revision or final mix-session ledger. Sound and music sources further document a five-year making process, seven principal songs, extensive vocal production, music editing/mixing and a score by Marcelo Zarvos. Netflix interviews show Ian Eisendrath serving as a central music-production bridge while THEBLACKLABEL and other writers worked across continents. Direct composer reporting describes a six-week score window late in production, with some sequences still represented by animatics or incomplete shots but with stable timing; the score was first built against the film and then selectively integrated with song themes such as Golden. Sound designer Michael Babcock's direct account describes a rhythm-and-pitch discipline in which effects were checked against musical tonality and timing, and song stems were adapted for theatrical/Atmos treatment. The locked case treats that as an unusually integrated music/sound-design workflow rather than claiming every effect was literally musical or every master shared one mastering chain. The historical lesson is therefore not simply that KPop Demon Hunters is stylized CG animation or a successful soundtrack film. It is that a streaming-era animated feature joined Sony Pictures Animation's development/design culture to Imageworks engineering, custom facial and blur controls, hand-keyed performance, Unreal-based real-time layout/previs, K-drama-inspired lighting, Korean cultural/fashion references, storyboard-first Avid editorial and an international song-production system in which chart-ready K-pop and narrative structure were developed together. The locked evidence does not establish a complete production budget or financing/recoupment waterfall, exact full development calendar, complete staffing/outsourcing census, every storyboard/layout/animation/lighting revision, final renderer and render-farm ledger, full modeling/rigging/hair/cloth/effects software stack, every Unreal asset or shot, every Chibi/blur override, complete costume/prop/environment asset inventory, every voice-recording session, every song demo/version/stem/right, complete score-session and orchestration ledger, all editorial project revisions, full dialogue/Foley/effects/Atmos/mastering chain, every color-management/render/delivery setting or every Netflix/cinema/sing-along/physical-media territory master. Those remain explicit unresolved boundaries.",
    requiredChoicesSeed: {
      screenplay: ["award_priority_not_workflow_evidence", "bbfc_original_99m37_runtime", "version_provenance_boundary", "music_story_development", "budget_finance_unresolved"],
      camera: ["unreal_rough_layout_previs_only", "interactive_lens_camera_exploration", "kdrama_soft_lighting", "motion_blur_spheres", "final_renderer_unresolved"],
      editing: ["storyboard_first_avid_media_composer", "layout_animation_lighting_replacement_tracks", "music_timing_dependency", "multicam_grouping", "aaf_to_pro_tools", "full_edit_revision_ledger_unresolved"],
      sound: ["global_kpop_song_pipeline", "golden_seven_page_memo", "ian_eisendrath_music_bridge", "six_week_zarvos_score", "rhythm_pitch_sound_design", "full_music_mix_rights_ledgers_unresolved"],
      themes: ["film_history", "2025", "kpop_demon_hunters", "animation", "unreal_layout", "stylized_cg", "music_pipeline", "chapter19"]
    },
    learningGoals: [
      "Explain why the 2026 Animated Feature and Original Song Oscars justify award-priority selection without proving workflow.",
      "Identify Maggie Kang and Chris Appelhans as directors and keep award evidence separate from craft evidence.",
      "Use BBFC's original 99m37s Netflix record to round the playable runtime to 100 minutes.",
      "Keep the 95m29s cinema sing-along, 100-minute VOD sing-along and later 96-minute home master as separate version records.",
      "Reject the claim that every Netflix, sing-along, cinema and home version is frame-identical.",
      "Identify Sony Pictures Animation and Sony Pictures Imageworks as distinct but collaborating production entities.",
      "Explain SPA's pre-production role in story, character and visual exploration.",
      "Explain Imageworks' role in translating visual goals into geometry, animation and rendering systems.",
      "Describe the visual problem of combining anime graphic exaggeration with photographic K-drama softness.",
      "Explain why live-action dance influence does not make the film a motion-capture production.",
      "Identify hand-keyed animation as the documented performance strategy instead of full mocap.",
      "Describe the Chibi Face system as interchangeable facial features, blend-shapes and meshes.",
      "Explain how Chibi Face could intentionally break realistic facial geometry for camera-specific expression.",
      "Explain why a 3D asset may contain intentionally 2D-looking expressive states.",
      "Identify Motion-Blur Spheres as a localized blur-control system.",
      "Explain how localized blur can keep characters crisp against soft photographic lighting.",
      "Keep the complete facial-rig node graph and every per-shot override unresolved.",
      "Identify Unreal Engine as a pre-production/Rough Layout tool in the locked evidence.",
      "Reject the unsupported inference that Unreal Engine was the final renderer for every shot.",
      "Explain how real-time layout let directors test scale, lenses, lighting and camera moves earlier.",
      "Explain why earlier interactive decisions can reduce downstream rework without proving an exact cost saving.",
      "Identify Seoul lighting exploration as a documented Unreal/Sandbox use.",
      "Identify the bathhouse action as a documented choreography/previs use.",
      "Identify Jamsil Olympic Stadium crowd visualization as a documented real-time planning use.",
      "Explain the shift from linear Rough Layout handoff toward a more iterative real-time workflow.",
      "Identify Mingjue Helen Chen as production designer.",
      "Explain the tertiary-color philosophy rather than simple primary character coding.",
      "Explain why K-drama-inspired soft lighting exposed animation imperfections rather than hiding them.",
      "Map demon magenta, Honmoon iridescence and wardrobe color as narrative design systems.",
      "Identify Korean norigae references as part of character-specific costume language.",
      "Explain the weapon designs as visualized musical/spiritual energy rather than literal historical reproductions.",
      "Use the 200-300 costume drawings as a design-scale anchor, not a complete asset count.",
      "Use Rumi's 23 costume changes as a continuity/design anchor without inferring every character's wardrobe count.",
      "Explain why fashion variety increases modeling, surfacing, rigging and continuity obligations in CG animation.",
      "Keep the full asset, hair, cloth and costume simulation ledger unresolved.",
      "Explain why the songs had to work simultaneously as narrative scenes and credible K-pop tracks.",
      "Identify the weekly cross-continental music meetings spanning Korea, New York, Los Angeles and Bangkok.",
      "Explain how distributed music collaboration belongs to Chapter 19's remote/global production history.",
      "Identify THEBLACKLABEL as one major music-production collaborator without assigning every song solely to it.",
      "Identify Ian Eisendrath as a central music-production/vocal-production bridge in the documented pipeline.",
      "Explain Golden's seven-page filmmakers' memo as a story requirement document before songwriting.",
      "Explain why mapping verse/chorus dramatic functions makes songwriting part of screenplay/story development.",
      "Keep every demo, lyric revision, producer split, master right and publishing agreement unresolved.",
      "Identify Nathan Schauf as lead editor.",
      "Describe the Avid Media Composer process beginning with storyboard JPEGs and temp audio.",
      "Explain how approved storyboard cuts receive Layout, Animation and Lighting as progressively mature picture layers.",
      "Explain why music timing can require changes to CG or music rather than allowing picture and songs to evolve independently.",
      "Identify Media Composer multicam grouping as a documented organization/speed tool.",
      "Identify AAF as the documented handoff path from Media Composer to Pro Tools.",
      "Keep the complete edit revision history and exact track architecture unresolved.",
      "Use the five-year making reference as a broad production-duration anchor without inventing a day-by-day schedule.",
      "Identify seven principal songs in the documented music-production account.",
      "Explain why vocal production, song production, score, music editing and music mixing are distinct responsibilities.",
      "Identify Marcelo Zarvos as score composer.",
      "Use the reported six-week score window as a late-production anchor without inferring picture was fully finished.",
      "Explain how scoring against animatics or incomplete shots can work when editorial timing is sufficiently stable.",
      "Explain the selective reuse of song themes inside the score as narrative integration rather than simple soundtrack placement.",
      "Explain Michael Babcock's rhythm-and-pitch checks as a sound-design organizing principle.",
      "Explain why adapting song material for Atmos/theatrical use is a mix/delivery problem separate from songwriting.",
      "Keep the complete dialogue, Foley, effects, Atmos object, stem and mastering chain unresolved.",
      "Keep the full production budget, financing, ownership, participation and recoupment waterfall unresolved.",
      "Keep the complete staffing, vendor and outsourcing census unresolved.",
      "Keep every storyboard, layout, animation, lighting, FX and render revision unresolved.",
      "Keep the complete final renderer, render farm, color-management and delivery configuration unresolved.",
      "Keep every Netflix, cinema, sing-along, VOD and physical-media territory master unresolved.",
      "Close the case only when awards, runtime provenance, SPA/Imageworks collaboration, stylized animation systems, Unreal layout, design, editorial, songs, score, sound and unresolved boundaries agree."
    ],
    phases: [
      { id: "award_priority", label: "Lock award priority", player_task: "Use the 2026 Oscars to prioritize the case without treating awards as production evidence." },
      { id: "runtime_boundary", label: "Freeze runtime provenance", player_task: "Use the 99m37s original Netflix version for the playable record while preserving later/sing-along variants." },
      { id: "studio_roles", label: "Separate SPA and Imageworks", player_task: "Keep development/design and downstream engineering/animation roles distinct." },
      { id: "aesthetic_problem", label: "Define the mixed visual language", player_task: "Join anime exaggeration, K-drama photographic softness and dance expressiveness without flattening them into one style label." },
      { id: "hand_keyed_performance", label: "Choose artist-controlled animation", player_task: "Use hand-keyed performance rather than treating dance as full-motion-capture output." },
      { id: "chibi_face", label: "Build Chibi Face states", player_task: "Design interchangeable exaggerated facial states that can break realistic geometry when required by the shot." },
      { id: "blur_control", label: "Localize motion blur", player_task: "Use Motion-Blur Spheres to protect graphic character readability under soft lighting." },
      { id: "unreal_boundary", label: "Bound Unreal's role", player_task: "Use Unreal for pre-production and Rough Layout without claiming it as the final renderer." },
      { id: "real_time_layout", label: "Iterate layout in real time", player_task: "Test lenses, scale, cameras and light interactively before downstream animation." },
      { id: "seoul_scout", label: "Scout Seoul lighting", player_task: "Use real-time visualization to communicate city lighting intent." },
      { id: "bathhouse_previs", label: "Previsualize the bathhouse fight", player_task: "Resolve choreography, camera and spatial problems before final animation." },
      { id: "stadium_scale", label: "Validate stadium scale", player_task: "Use visualization to plan Jamsil Olympic Stadium and crowd scale." },
      { id: "palette_system", label: "Design tertiary palettes", player_task: "Avoid simple primary-color character coding and preserve nuanced color relationships." },
      { id: "kdrama_lighting", label: "Light with photographic softness", player_task: "Use soft K-drama-inspired lighting while maintaining animation quality under exposed conditions." },
      { id: "korean_design_references", label: "Integrate Korean references", player_task: "Use norigae, weapon and visual research as design sources without turning them into literal reconstruction claims." },
      { id: "wardrobe_scale", label: "Manage fashion continuity", player_task: "Plan the unusually large wardrobe-design burden across characters and performances." },
      { id: "music_story_map", label: "Map songs to story", player_task: "Define character and plot functions before treating songs as standalone releases." },
      { id: "global_music_collaboration", label: "Coordinate global song teams", player_task: "Align filmmakers and music collaborators across weekly cross-continental sessions." },
      { id: "golden_memo", label: "Specify Golden", player_task: "Translate the seven-page dramatic brief into song structure without inventing undocumented drafts." },
      { id: "storyboard_edit", label: "Cut the storyboard movie", player_task: "Build timing in Avid from storyboard images, temp dialogue, SFX and music." },
      { id: "layout_replace", label: "Replace storyboard with Layout", player_task: "Advance shots while preserving editorial timing and note history." },
      { id: "animation_replace", label: "Replace Layout with Animation", player_task: "Evaluate performance and music synchronization as animation matures." },
      { id: "lighting_replace", label: "Integrate Lighting", player_task: "Cut final-lighting stages into the editorial timeline without assuming every shot is final simultaneously." },
      { id: "music_revision_dependency", label: "Coordinate picture and music changes", player_task: "Treat a timing change as a shared CG/music editorial problem." },
      { id: "avid_multicam", label: "Organize alternate material", player_task: "Use multicam grouping as the documented editorial organization tool." },
      { id: "pro_tools_handoff", label: "Hand off audio by AAF", player_task: "Move the developed soundtrack structure into Pro Tools for further finishing." },
      { id: "score_window", label: "Build the late score", player_task: "Use the six-week score window against stable timing while some animation remains unfinished." },
      { id: "song_score_integration", label: "Integrate song themes into score", player_task: "Reuse musical ideas where story requires them rather than blanket-scoring every sequence." },
      { id: "sound_rhythm_pitch", label: "Tune sound to musical logic", player_task: "Check effects for rhythm and pitch relationships without claiming every effect is tonal music." },
      { id: "versioning", label: "Protect version differences", player_task: "Keep Netflix, sing-along, cinema and home masters distinct in the production record." },
      { id: "uncertainty_register", label: "Freeze unresolved ledgers", player_task: "Keep budget, staffing, software, render, edit, music, sound and delivery ledgers explicitly unresolved." },
      { id: "production_verification", label: "Close KPop Demon Hunters production audit", player_task: "Verify runtime provenance, studio roles, animation systems, Unreal layout, design, editorial, music, sound and unresolved boundaries before canonical promotion." }
    ]
  }
] as const;

export function mergeChapterNineteenKPopDemonHuntersExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterNineteenKPopDemonHuntersExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_nineteen_kpop_demon_hunters_verified",
      source: { list_id: "manual_chapter_nineteen_kpop_demon_hunters_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
