import assert from "node:assert/strict";
import test from "node:test";

import { chapterEighteenIdaExpansionDefinitions } from "./chapterEighteenIdaExpansion.js";

test("Chapter 18 materializes Ida as a source-first digital monochrome 4:3 Poland-Denmark production case", () => {
  assert.equal(chapterEighteenIdaExpansionDefinitions.length, 1);
  const film = chapterEighteenIdaExpansionDefinitions[0];
  assert.equal(film.id, "scenario_ida_2013");
  assert.equal(film.year, 2013);
  assert.equal(film.runtimeMins, 80);
  assert.deepEqual(film.directors, ["Paweł Pawlikowski"]);
  assert.ok(film.scenarioType.includes("poland_denmark") && film.scenarioType.includes("public_coproduction") && film.scenarioType.includes("lodz_location"));
  assert.ok(film.scenarioType.includes("alexa_4x3") && film.scenarioType.includes("ultra_prime") && film.scenarioType.includes("arriraw_codex"));
  assert.ok(film.scenarioType.includes("color_capture") && film.scenarioType.includes("black_white_di") && film.scenarioType.includes("negative_space"));
  assert.ok(film.premise.includes("Opus Film") && film.premise.includes("Phoenix Film Investment"));
  assert.ok(film.premise.includes("Portobello Pictures") && film.premise.includes("Canal+ Poland"));
  assert.ok(film.premise.includes("Polish Film Institute") && film.premise.includes("Eurimages") && film.premise.includes("Danish Film Institute") && film.premise.includes("City of Łódź"));
  assert.ok(film.premise.includes("80-minute") && film.premise.includes("Jarosław Kamiński") && film.premise.includes("Claus Lynge"));
  assert.ok(film.premise.includes("ARRI ALEXA 4:3") && film.premise.includes("ARRI/Zeiss Ultra Prime") && film.premise.includes("Panavision Poland"));
  assert.ok(film.premise.includes("ARRIRAW to Codex") && film.premise.includes("Nucoda") && film.premise.includes("DI Factory"));
  assert.ok(film.premise.includes("1.33:1") && film.premise.includes("1.37:1") && film.premise.includes("version/documentation variance"));
  assert.ok(film.premise.includes("Ryszard Lenczewski") && film.premise.includes("Łukasz Żal") && film.premise.includes("photographed most of the film"));
  assert.ok(film.premise.includes("6K lamps") && film.premise.includes("Octodome") && film.premise.includes("scene-specific"));
  assert.ok(film.premise.includes("FilmPolski") && film.premise.includes("Łódź UNESCO City of Film"));
  assert.ok(film.premise.includes("exact budget totals") && film.premise.includes("exact shooting-day counts") && film.premise.includes("exact ALEXA submodel"));
  assert.ok(film.premise.includes("complete focal-length maps") && film.premise.includes("exact Codex hardware submodel") && film.premise.includes("exact grain recipe"));
  assert.ok(film.requiredChoicesSeed.camera.includes("alexa_4x3"));
  assert.ok(film.requiredChoicesSeed.camera.includes("aspect_ratio_variance_boundary"));
  assert.ok(film.requiredChoicesSeed.editing.includes("color_to_bw_di_handoff"));
  assert.ok(film.requiredChoicesSeed.sound.includes("production_sound_equipment_unknowns"));
  assert.ok(film.learningGoals.some((goal) => goal.includes("80-minute") && goal.includes("version metadata")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Opus Film") && goal.includes("Phoenix Film")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Polish Film Institute") && goal.includes("Eurimages") && goal.includes("City of Łódź")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("captured in color") && goal.includes("black-and-white")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("ARRI ALEXA 4:3") && goal.includes("submodel")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Ultra Prime") && goal.includes("shot-by-shot lens map")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("ARRIRAW-to-Codex") && goal.includes("Codex hardware model")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("DI Factory") && goal.includes("Nucoda")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("1.33:1") && goal.includes("1.37:1") && goal.includes("variance")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("high headroom") && goal.includes("negative space")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Ryszard Lenczewski") && goal.includes("Łukasz Żal")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Lenczewski") && goal.includes("illness") && goal.includes("handoff")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("6K") && goal.includes("Octodome") && goal.includes("scene-specific")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Jarosław Kamiński") && goal.includes("limited coverage")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Claus Lynge") && goal.includes("Ministi Film")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Toya Studios") && goal.includes("playback")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("exact budget") && goal.includes("ALEXA submodel") && goal.includes("delivery raster")));
  assert.ok(film.phases.find((phase) => phase.id === "released_version")?.player_task.includes("80-minute"));
  assert.ok(film.phases.find((phase) => phase.id === "dp_handoff")?.player_task.includes("Lenczewski") && film.phases.find((phase) => phase.id === "dp_handoff")?.player_task.includes("Żal"));
  assert.ok(film.phases.find((phase) => phase.id === "aspect_ratio")?.player_task.includes("1.33:1") && film.phases.find((phase) => phase.id === "aspect_ratio")?.player_task.includes("1.37:1"));
  assert.ok(film.phases.find((phase) => phase.id === "arriraw_codex")?.player_task.includes("Codex"));
  assert.ok(film.phases.find((phase) => phase.id === "bw_nucoda")?.player_task.includes("Nucoda"));
  assert.ok(film.phases.find((phase) => phase.id === "lighting_boundaries")?.player_task.includes("EI") && film.phases.find((phase) => phase.id === "lighting_boundaries")?.player_task.includes("shutter"));
  assert.ok(film.phases.find((phase) => phase.id === "unknowns_register")?.player_task.includes("ALEXA submodel") && film.phases.find((phase) => phase.id === "unknowns_register")?.player_task.includes("Codex model"));
  assert.ok(film.learningGoals.length >= 50);
  assert.ok(film.phases.length >= 30);
});
