import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterNineteenSiratExpansionDefinitions = [
  {
    id: "scenario_sirat_2025",
    title: "Sirāt",
    originalTitle: "Sirāt",
    aliases: ["Sirat", "Sirât"],
    year: 2025,
    titleType: "Movie",
    runtimeMins: 114,
    directors: ["Óliver Laxe"],
    genres: ["Drama", "Adventure"],
    sourceId: "kodak_sirat_super_16_2026",
    sourceUrl: "https://www.kodak.com/en/motion/blog-post/sirat/",
    scenarioType: "award_priority_cannes_jury_prize_oscar_international_feature_sound_nominee_oliver_laxe_mauro_herce_santiago_fillol_super_16_arriflex_416_ultra_prime_kodak_vision3_250d_7207_500t_7219_spain_morocco_location_production_available_light_hmi_vortex_skypanel_titan_black_arm_camera_car_2k_scan_transperfect_cube_grade_laia_ateca_cristobal_fernandez_amanda_villavieja_laia_casanovas_yasmina_praderas_kangding_ray_pre_shoot_music_documentary_adjacent_rave_authenticity_2025",
    premise: "Build Sirāt as Chapter 19's next award-priority auteur/festival production case because Festival de Cannes records the film as the 2025 Jury Prize winner ex aequo, while the Academy records 2026 nominations for Spain in International Feature Film and for Amanda Villavieja, Laia Casanovas and Yasmina Praderas in Sound. Those awards establish selection and reception priority, not production workflow. Runtime provenance is explicitly versioned rather than flattened: Cannes lists the festival film at 120 minutes, while BBFC records the UK 2D cinema version at 114 minutes 12 seconds and a later physical-media/VOD version at 114 minutes 23 seconds. The playable record therefore rounds the BBFC cinema master to 114 minutes and preserves the Cannes/BBFC discrepancy as an unresolved version-history question rather than declaring one universal runtime. Cannes credits Óliver Laxe as director and co-writer with Santiago Fillol, Mauro Herce as cinematographer, Laia Ateca as production designer, Cristóbal Fernández as editor, Kangding Ray as composer and Laia Casanovas in sound. Kodak's direct interview with Herce gives the most detailed physical-production record. It reports a €6.5 million budget, but the locked case treats that as a published production figure rather than a complete financing, ownership, subsidy, sales, distribution or recoupment ledger. Principal photography took place between May and June 2024. Funding requirements meant part of the feature had to be shot in Spain: approximately one month around Rambla de Barrachina and in Teruel and Zaragoza, followed by four weeks around Errachidia and Erfoud in Morocco. This proves a two-country location-production structure and continuity problem, not a complete day-by-day call-sheet or location-permit ledger. Herce explains that Morocco supplied locations easily while Spanish terrain had to match Moroccan geography, and that scenes around the river crossing, mountain road, rain ascent and accident were photographed out of story order across the two countries. The production therefore had to solve geographic continuity through framing, sun position, art direction, editing and selective post work. Herce and Laxe initially wanted 35mm anamorphic, but cost, logistics and the risk of fragile optics in remote dusty terrain pushed the production toward Super 16. That is a production-risk decision, not evidence that Super 16 was a compromise in artistic quality: Herce explicitly valued the smaller, lighter, more maneuverable package and the textural relationship between 16mm film, hard desert light and landscape. Kodak documents ARRIFLEX 416 16mm cameras, ARRI Zeiss Ultra Prime lenses and 1.85:1 framing. KODAK VISION3 250D 7207 was used for day exteriors and some interiors, while VISION3 500T 7219 covered night sequences. Film processing and 2K scans were done at TransPerfect Media, formerly Hiventy, in Paris; final color grading was done at Cube in Barcelona by Rafa Marmodoro. Herce states that no push or pull processing was used. Those facts establish a photochemical-negative-to-digital-scan-and-grade pipeline, not the complete camera report, negative inventory, lab timing, backup, conform, mastering or archive ledger. Herce operated the main camera with Javi Barbero on focus, Rachid Talidi on Steadicam, Alfredo Arcos leading grips, Pep Zueras as gaffer and Diego Romero on second-unit camera. Camera movement was deliberately restrained compared with conventional action coverage: long takes and sober framing were used for much of the desert journey, while Steadicam or handheld covered movement such as the minefield, tripod work handled panning dialogue scenes, a three-axis Black Arm on a simple wheeled rig supported travelling shots, a camera car with a three-axis arm covered driving and a telescopic crane was used for the train sequence. These are documented tools and roles, not a per-shot equipment map. Day exteriors relied primarily on available hard sunlight, managed through scheduling the sun and using bounce, diffusion and negative fill for continuity. Night work used elevated HMIs for broad moon-like illumination with Creamsource Vortex, ARRI SkyPanel and Astera Titan units near performers, plus upgraded vehicle bulbs. The case therefore keeps natural-light strategy, fixture-assisted night lighting and final color work as distinct layers. Physical conditions materially affected production. Kodak records temperatures around 45°C in Morocco, pervasive dust, aging vehicles requiring repeated repairs and a quarry accident sequence that required a road to be cut specifically for vehicle movement and camera orientation. That accident sequence used green screens for background replacements and could initially cover only about a 90-degree angle, requiring morning/afternoon reorientation. A sandstorm in the finale was captured opportunistically rather than fully controlled. Film Comment adds a second direct Laxe account: he insisted the trucks travel fast enough to produce the desired kinetic impression, lenses broke, sequences had to be repeated, shooting days were lost and sandstorms stressed equipment. The locked record therefore treats physical risk, breakdowns, reshoots and opportunistic documentary-like capture as production evidence while leaving the complete stunt, vehicle-maintenance, safety, insurance and lost-day ledger unresolved. Production design is not reduced to generic desert authenticity. Cannes credits Laia Ateca, and later reporting describes collaboration with real free-party communities and a deliberately monumental speaker wall. The film's opening rave uses documentary-adjacent participation and real subcultural knowledge, but Sirāt remains scripted fiction; the case must not convert community participation into a claim that the film is documentary. Sound and music are unusually structural. Dolby's direct panel identifies production sound mixer Amanda Villavieja, sound designer/supervising sound editor Laia Casanovas and re-recording mixer Yasmina Praderas and describes the goal as an immersive, visceral theatrical experience, with Dolby Atmos available in supported venues. The Academy's Sound nomination confirms the credited team but does not establish undocumented equipment or session details. Laxe describes sound as bodily and ceremonial rather than merely supportive. Kangding Ray's direct interviews establish that music entered extremely early: he and Laxe worked for well over a year before photography, a large majority of the score existed before the shoot, and later picture editing refined rather than originated the musical architecture. The film contains an unusually large quantity of music for its runtime, with the score moving from rave/techno intensity toward more ethereal and ambient states. This means score development, diegetic rave playback, production sound, sound design and re-recording must remain separate evidence layers even when the finished mix deliberately blurs their perceptual borders. Cristóbal Fernández is the credited editor, but the available source set does not justify inventing a complete NLE, project architecture, assistant-editor workflow, exact cut history or turnover ledger. The historical lesson is not simply that Sirāt was shot on 16mm in the desert. It is that a contemporary transnational European festival film used a small photochemical camera package as a risk-management and aesthetic tool, matched Spain to Morocco across nonchronological location work, integrated old vehicles and difficult terrain, combined available-light realism with carefully placed night fixtures, allowed real weather and rave culture to enter a scripted fiction, used selective green-screen replacement without becoming a VFX-led production, and treated music and sound as pre-production structural systems rather than downstream polish. The locked evidence does not establish the complete finance/subsidy/co-production/recoupment waterfall, every contract and permit, exact shooting-day count, complete crew/payroll/safety/insurance records, full location and vehicle ledger, every camera body/lens/filter/magazine/stock roll/exposure/processing record, all stunt and vehicle-driving handoffs, every lighting fixture and power plan, complete negative/scan/conform/color/mastering chain, full VFX shot/vendor/task census, all editorial revisions and turnovers, complete production-sound/microphone/ambisonic/ADR/Foley/stem details, every score cue/session/synth/source/licensing record, or the exact relationship among Cannes 120-minute, BBFC 114m12 cinema and 114m23 home masters. Those remain explicit unresolved boundaries.",
    requiredChoicesSeed: {
      screenplay: ["award_priority_not_workflow_evidence", "runtime_version_discrepancy_120_vs_114", "spain_morocco_geographic_continuity", "scripted_fiction_documentary_adjacent_boundary", "finance_ledger_unresolved"],
      camera: ["super16_arriflex_416", "ultra_prime_185", "vision3_250d_7207", "vision3_500t_7219", "available_light_day", "hmi_vortex_skypanel_titan_night", "black_arm_camera_car_crane", "2k_scan_transperfect_cube_grade", "full_camera_negative_ledger_unresolved"],
      editing: ["cristobal_fernandez_credit", "cross_country_nonchronological_continuity", "music_precedes_picture_edit", "edit_ledger_unresolved"],
      sound: ["amanda_villavieja_production_sound", "laia_casanovas_sound_design", "yasmina_praderas_rerecording", "dolby_atmos_available", "kangding_ray_pre_shoot_score", "diegetic_music_sound_design_boundary", "full_audio_ledger_unresolved"],
      themes: ["film_history", "2025", "sirāt", "festival_cinema", "super16", "location_risk", "transnational_production", "rave_culture", "sound_music_structure", "chapter19"]
    },
    learningGoals: [
      "Explain why the 2025 Cannes Jury Prize establishes award priority without proving production workflow.",
      "Identify Sirāt as Spain's 2026 International Feature Oscar nominee without treating that nomination as production evidence.",
      "Identify Amanda Villavieja, Laia Casanovas and Yasmina Praderas as the Academy-nominated Sound team.",
      "Use BBFC's 114m12s cinema master to round the playable runtime to 114 minutes.",
      "Preserve BBFC's later 114m23s home master as a separate version record.",
      "Preserve Cannes's 120-minute listing as an unresolved institutional runtime discrepancy.",
      "Identify Óliver Laxe as director and co-writer with Santiago Fillol.",
      "Identify Mauro Herce as cinematographer.",
      "Identify Laia Ateca as production designer.",
      "Identify Cristóbal Fernández as editor.",
      "Identify Kangding Ray as composer.",
      "Use Kodak's €6.5m figure as a published budget figure without inventing a financing waterfall.",
      "Place principal photography between May and June 2024.",
      "Describe approximately one month of Spanish photography and four weeks of Moroccan photography.",
      "Identify Rambla de Barrachina, Teruel and Zaragoza as documented Spanish production areas.",
      "Identify Errachidia and Erfoud as documented Moroccan production areas.",
      "Explain why Spanish landscapes had to match Moroccan geography for continuity.",
      "Explain why nonchronological cross-country photography created a continuity problem for camera, art direction and edit.",
      "Explain the abandoned 35mm-anamorphic preference as a cost/logistics/risk decision.",
      "Explain why Super 16's smaller and lighter package mattered in remote desert production.",
      "Identify ARRIFLEX 416 as the documented camera platform.",
      "Identify ARRI Zeiss Ultra Primes as the documented lens family.",
      "Identify 1.85:1 as the documented framing ratio.",
      "Identify KODAK VISION3 250D 7207 for day exteriors and selected interiors.",
      "Identify KODAK VISION3 500T 7219 for night photography.",
      "Explain why 250D and 500T were selected partly for compatible grain/texture behavior.",
      "Identify TransPerfect Media in Paris as the processing and 2K scan facility.",
      "Identify Cube in Barcelona and Rafa Marmodoro as the documented final grading context.",
      "Recognize that the published account states no push/pull processing was used.",
      "Keep the full negative inventory, lab timing and archive ledger unresolved.",
      "Explain sober long-take coverage as a deliberate alternative to multi-angle action coverage.",
      "Identify Steadicam and handheld as documented movement strategies.",
      "Identify tripod panning as a documented dialogue/blocking strategy.",
      "Identify the three-axis Black Arm wheeled rig as a travelling-shot tool.",
      "Identify a three-axis camera-car arm as a driving-shot tool.",
      "Identify a telescopic crane as the documented train-sequence tool.",
      "Explain why these devices do not establish a complete per-shot camera map.",
      "Explain day exteriors as primarily available-light work organized around sun position.",
      "Identify bounce, diffusion and negative fill as daylight-continuity controls.",
      "Identify elevated HMIs as broad night illumination.",
      "Identify Creamsource Vortex, ARRI SkyPanel and Astera Titan fixtures near performers.",
      "Explain upgraded vehicle bulbs as an in-world lighting contribution.",
      "Keep natural light, fixture lighting and color grading as distinct evidence layers.",
      "Recognize Morocco's approximately 45°C heat and pervasive dust as production constraints.",
      "Explain why old vehicles required ongoing repair and schedule resilience.",
      "Explain the quarry road construction as physical production infrastructure for the accident sequence.",
      "Identify selective green screens as documented background-replacement tools for the quarry sequence.",
      "Reject the claim that Sirāt was broadly a green-screen production.",
      "Explain the roughly 90-degree coverage constraint and morning/afternoon reorientation for the quarry sequence.",
      "Treat the finale sandstorm as opportunistic real-weather capture rather than a fully controlled effect.",
      "Use Laxe's report of broken lenses and repeated sequences as evidence of physical-production risk.",
      "Keep exact lost days, damaged equipment inventory and insurance claims unresolved.",
      "Explain why real free-party participation can create documentary-like texture inside scripted fiction.",
      "Reject the claim that community participation makes Sirāt a documentary.",
      "Explain the monumental speaker wall as part of the production-design/rave-authenticity system.",
      "Identify Amanda Villavieja's production-sound role separately from sound design.",
      "Identify Laia Casanovas's sound-design/supervising role separately from re-recording.",
      "Identify Yasmina Praderas's re-recording role separately from production capture.",
      "Use Dolby Atmos as a supported exhibition/mix context without inventing every delivery master.",
      "Explain Laxe's bodily/ceremonial sound goal as an aesthetic intention rather than an equipment specification.",
      "Explain why Kangding Ray's score entering before photography changes the normal picture-then-score chronology.",
      "Recognize that a majority of the music existed before the shoot while later picture work refined the score.",
      "Keep diegetic rave playback, score, production sound, sound design and final mix distinct.",
      "Explain why sound and music can blur perceptually while remaining separate production systems.",
      "Keep the complete editorial software, project, assistant and turnover ledger unresolved.",
      "Keep the complete VFX shot/vendor/task census unresolved.",
      "Keep the complete stunt, vehicle-maintenance, safety and insurance ledger unresolved.",
      "Keep the complete finance, subsidy, sales, distribution and recoupment ledger unresolved.",
      "Keep the complete production-sound, ADR, Foley, stem and mastering ledger unresolved.",
      "Close the case only when award priority, runtime provenance, transnational location production, Super 16 capture, lighting, physical risk, selective post, editing, sound, music and uncertainty boundaries agree."
    ],
    phases: [
      { id: "award_priority", label: "Lock festival priority", player_task: "Use Cannes Jury Prize and Oscar nominations for priority, not as workflow proof." },
      { id: "runtime_versions", label: "Version the runtime", player_task: "Keep Cannes 120, BBFC 114m12 cinema and 114m23 home records distinct." },
      { id: "finance_boundary", label: "Bound the budget", player_task: "Use the published €6.5m figure without inventing financing or recoupment." },
      { id: "two_country_plan", label: "Plan Spain and Morocco", player_task: "Build a two-country location schedule around funding and geography." },
      { id: "continuity_geography", label: "Match landscapes", player_task: "Make Spanish terrain continue Moroccan geography across nonchronological shooting." },
      { id: "format_choice", label: "Choose Super 16", player_task: "Trade 35mm anamorphic preference for a smaller, more resilient desert package." },
      { id: "camera_package", label: "Build the 416 package", player_task: "Use ARRIFLEX 416 bodies and Ultra Primes for a mobile 1.85 production." },
      { id: "day_stock", label: "Load 250D", player_task: "Use VISION3 250D 7207 for day exteriors and selected interiors." },
      { id: "night_stock", label: "Load 500T", player_task: "Use VISION3 500T 7219 for night work while maintaining textural continuity." },
      { id: "daylight", label: "Schedule the sun", player_task: "Build day continuity around sun position, bounce, diffusion and negative fill." },
      { id: "night_light", label: "Create moon-scale night light", player_task: "Place HMIs high and supplement actors with Vortex, SkyPanel and Titan fixtures." },
      { id: "vehicle_practicals", label: "Strengthen vehicle light", player_task: "Upgrade in-world bulbs without confusing practicals with full night lighting." },
      { id: "long_take_language", label: "Restrain coverage", player_task: "Favor sober long takes over default multi-angle action cutting." },
      { id: "steadicam_handheld", label: "Move through bodies and terrain", player_task: "Use Steadicam or handheld where the geography demands embodied movement." },
      { id: "black_arm", label: "Track travelling action", player_task: "Use the three-axis Black Arm wheeled rig for selected moving shots." },
      { id: "camera_car", label: "Shoot the road", player_task: "Use the three-axis camera-car arm for driving material." },
      { id: "train_crane", label: "Extend the camera", player_task: "Use a telescopic crane for the train sequence." },
      { id: "heat_dust", label: "Protect crew and equipment", player_task: "Plan for extreme heat, dust and limited replacement access." },
      { id: "vehicle_repair", label: "Maintain aging vehicles", player_task: "Treat breakdowns and repair time as production risk rather than narrative abstraction." },
      { id: "quarry_road", label: "Build physical access", player_task: "Cut the quarry road required for vehicle movement and camera orientation." },
      { id: "selective_greenscreen", label: "Extend the quarry", player_task: "Use green-screen background replacement only where physical geography cannot deliver the shot." },
      { id: "coverage_constraint", label: "Work inside 90 degrees", player_task: "Reorient production through the day instead of pretending the location offers unrestricted coverage." },
      { id: "weather_opportunity", label: "Capture the sandstorm", player_task: "React to real weather when it strengthens the scene and remains safe to photograph." },
      { id: "lens_damage", label: "Recover from equipment loss", player_task: "Repeat required sequences after lens damage without hiding the schedule cost." },
      { id: "rave_authenticity", label: "Work with free-party culture", player_task: "Build the rave from lived subcultural knowledge without turning scripted fiction into documentary." },
      { id: "speaker_wall", label: "Design bodily scale", player_task: "Use production design to make the speaker system a physical environment." },
      { id: "lab_scan", label: "Process and scan", player_task: "Move exposed 16mm through Paris processing and 2K scanning with provenance intact." },
      { id: "grade", label: "Grade the scanned negative", player_task: "Finish color at Cube without inventing undocumented transforms or mastering settings." },
      { id: "music_preproduction", label: "Compose before shooting", player_task: "Let Kangding Ray's music shape production before picture exists." },
      { id: "rave_playback", label: "Separate diegetic music", player_task: "Track what performers hear on set separately from score and final sound design." },
      { id: "production_sound", label: "Capture location sound", player_task: "Keep Amanda Villavieja's production sound layer distinct from later editorial." },
      { id: "sound_design", label: "Build visceral sound", player_task: "Use Laia Casanovas's sound design to connect desert, machines, bodies and music." },
      { id: "rerecording", label: "Shape the final mix", player_task: "Keep Yasmina Praderas's re-recording work distinct from source capture and score." },
      { id: "atmos", label: "Deliver immersive exhibition", player_task: "Use Dolby Atmos where supported without assuming every master is identical." },
      { id: "edit_structure", label: "Assemble cross-country continuity", player_task: "Use Cristóbal Fernández's editorial layer to reconcile geography, performance, music and risk." },
      { id: "versioning", label: "Protect master provenance", player_task: "Keep festival, cinema and home versions separate until their exact lineage is documented." },
      { id: "uncertainty_register", label: "Freeze unresolved ledgers", player_task: "Keep finance, permits, safety, camera, negative, edit, VFX, audio and delivery unknowns explicit." },
      { id: "production_verification", label: "Close Sirāt production audit", player_task: "Verify awards, runtime provenance, location production, Super 16, lighting, risk, post, edit, sound, music and unresolved boundaries before canonical promotion." }
    ]
  }
] as const;

export function mergeChapterNineteenSiratExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterNineteenSiratExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_nineteen_sirat_verified",
      source: { list_id: "manual_chapter_nineteen_sirat_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
