import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterEighteenYiYiExpansionDefinitions = [
  {
    id: "scenario_yi_yi_2000",
    title: "Yi Yi",
    originalTitle: "Yi Yi",
    year: 2000,
    titleType: "Movie",
    runtimeMins: 173,
    directors: ["Edward Yang"],
    genres: ["Drama"],
    sourceId: "criterion_yi_yi_2000",
    sourceUrl: "https://www.criterion.com/films/781-yi-yi",
    scenarioType: "taiwan_japan_family_drama_35mm_architectural_framing_reflections_long_take_multilingual_sound_transnational_production_2000",
    premise: "Build Yi Yi as Chapter 18's first P1 production case about how Edward Yang's family drama coordinates 35mm photography, architecture, reflective surfaces, ensemble blocking, patient editorial duration and multilingual urban sound without reducing the film to a single stylistic trademark. Criterion records the film as a 2000 Taiwan production at 173 minutes and credits Edward Yang as director, Shinya Kawai and Naoko Tsukeda as producers, Yang Wei-han for photography, Lee Lung-yue for lighting, Chen Po-wen for editing, Tu Duu-chih for sound, Kaili Peng for music and production design, and Wang Cheng-kai as art director. New Zealand International Film Festival separately records the production as Japan/Taiwan, 173 minutes and 35mm, with Atom Films, Pony Canyon and Omega Project among the production companies. Keep the transnational production record separate from later distribution and restoration labels. Criterion's formal analysis of Yi Yi foregrounds framing, reflections, rear projection and superimposition. Treat those observations as evidence about visible cinematic construction, not as a claim that every reflective image was achieved with the same technique or that analysis of the finished film substitutes for a production interview. The practical problem is repeatability: glass, mirrors, windows and layered depth change exposure, unwanted reflections, camera visibility, eyelines and background action, so camera, lighting, production design and blocking must be coordinated before a shot is treated as simple observational realism. Static or patient framing does not mean passive production. Long-duration ensemble shots require precise entrances, exits, focus, performance timing, background continuity and sound perspective because editorial rescue coverage may be limited. The film's urban interiors and exteriors also create a sound problem: dialogue, traffic, room tone, music, offscreen action and multilingual speech must remain intelligible while preserving a sense of lived space. Credit Tu Duu-chih for sound without inventing undocumented microphone, recorder or ADR procedures. The current Criterion edition preserves the original theatrical 2.0 surround soundtrack and an alternate 5.0 presentation; Cannes Classics 2025 states that the 4K restoration was digitized from the original 35mm acetate negative and that sound was digitized from a Hi8 source stored in Taiwan, with sound restoration by Tu Duu-chih and restoration/color supervision by Kaili Peng. Those preservation records prove surviving source elements and restoration stewardship, not the exact on-set recording format of 1999-2000. Likewise, the 2025/2026 4K restoration must not be projected backward as evidence of an original digital intermediate. The case should leave the player able to trace a scene from script and architecture through 35mm camera position, lighting, reflections, ensemble blocking, performance duration, edit decisions, production sound perspective and later preservation provenance while separating documented production fact, finished-film analysis, restoration evidence and thematic interpretation.",
    requiredChoicesSeed: {
      screenplay: ["family_parallel_structure", "wedding_to_funeral_arc", "cross_generation_information", "offscreen_knowledge_boundaries", "everyday_event_accumulation"],
      camera: ["35mm_capture_provenance", "architectural_frame_plan", "reflection_visibility_control", "window_exposure_balance", "ensemble_depth_blocking", "static_frame_not_passive"],
      editing: ["long_duration_performance", "parallel_family_threads", "limited_rescue_coverage", "transition_information_control", "offscreen_event_respect", "runtime_pacing_map"],
      sound: ["multilingual_dialogue_priority", "urban_room_tone", "offscreen_space_cues", "traffic_music_balance", "production_sound_unknowns", "restoration_source_boundary"],
      themes: ["film_history", "2000", "yi_yi", "edward_yang", "yang_wei_han", "lee_lung_yue", "chen_po_wen", "tu_duu_chih", "kaili_peng", "wang_cheng_kai", "shinya_kawai", "naoko_tsukeda", "taiwan", "japan", "new_taiwan_cinema", "35mm", "1_85_1", "reflections", "glass", "rear_projection", "superimposition", "architectural_framing", "ensemble_blocking", "long_takes", "multilingual_sound", "urban_space", "173_minutes", "restoration_provenance"],
    },
    learningGoals: [
      "Explain Yi Yi as a coordinated production system rather than a collection of elegant static compositions.",
      "Identify Edward Yang as writer-director while keeping producer, camera, lighting, design, editorial and sound authorship visible.",
      "Identify Shinya Kawai and Naoko Tsukeda as credited producers in the Criterion record.",
      "Identify Yang Wei-han as cinematographer and Lee Lung-yue as lighting credit.",
      "Identify Chen Po-wen as editor and Tu Duu-chih as sound credit.",
      "Identify Kaili Peng as both music and production-design credit without collapsing those departments into one task.",
      "Identify Wang Cheng-kai as art director in the Criterion record.",
      "Preserve the 173-minute runtime as release metadata rather than a proxy for production complexity.",
      "Record Taiwan and Japan as part of the transnational production context without turning country labels into aesthetic explanations.",
      "Identify 35mm as the documented acquisition medium in festival and preservation records.",
      "Explain why a surviving 35mm negative is strong preservation evidence but not a complete camera-package specification.",
      "When documenting the 35mm production, avoid inventing stock, lenses, filtration or processing details when the cited sources do not establish them.",
      "Explain why reflective glass can create exposure, camera-reflection and eyeline problems that require active planning.",
      "Distinguish a mirror reflection from rear projection or superimposition unless the source or shot analysis actually supports the technique.",
      "Describe Criterion's reflection/rear-projection/superimposition discussion as finished-film analysis rather than an original production log.",
      "Explain why architectural framing ties camera position to walls, windows, corridors, furniture and performer movement.",
      "Describe a static camera as a constraint on blocking and timing rather than evidence that the production simply observed reality.",
      "Explain how long-duration ensemble shots increase the importance of entrances, exits, focus, continuity and performance timing.",
      "Explain why limited alternate coverage makes mistakes in timing or background continuity more expensive to repair editorially.",
      "Distinguish patient shot duration from slow production pace; the two are not the same thing.",
      "Map simultaneous family threads without assuming every narrative parallel is created by cross-cutting.",
      "Explain why offscreen events still require production decisions about what sound, reaction or aftermath reaches the audience.",
      "Describe urban traffic and room tone as spatial information rather than generic ambience filler.",
      "Explain why multilingual dialogue requires intelligibility choices without treating one language as the default production norm.",
      "Keep dialogue, ambience, music and offscreen effects as distinct sound categories even when they overlap in the mix.",
      "Credit Tu Duu-chih for sound without claiming an undocumented microphone, recorder or ADR workflow.",
      "Explain why the current original-theatrical 2.0 surround presentation is a preservation/release fact, not proof of every original mix-stage procedure.",
      "Explain why the alternate 5.0 presentation belongs to later release/restoration provenance rather than the year-2000 production baseline.",
      "Record Cannes Classics' 2025 restoration from the original 35mm acetate negative as preservation evidence.",
      "Record the Hi8 sound source used for restoration without claiming that all production sound was originally recorded to Hi8.",
      "Identify Tu Duu-chih's later sound-restoration role separately from his original sound credit.",
      "Identify Kaili Peng's restoration/color-supervision role separately from her original production-design and music credits.",
      "Reject the inference that a 2025 4K restoration proves an original digital intermediate workflow.",
      "Explain why restoration color correction is a later preservation decision that must respect but cannot recreate undocumented original intent with certainty.",
      "Compare Yi Yi with In the Mood for Love: both are 2000 East Asian productions, but their production geometries, editorial rhythms and sound strategies differ.",
      "Compare Yi Yi with A Separation: both organize family tension through domestic and institutional spaces, while their industrial contexts and camera strategies remain distinct.",
      "Compare Yi Yi with Parasite: both make architecture narratively legible, but one relies on patient lived-space observation while the other foregrounds purpose-built class geometry.",
      "Keep Cannes recognition and later canon status downstream from evidence about how the film was made.",
      "Distinguish visible formal evidence from practitioner testimony and archival production documentation.",
      "Use source hierarchy so credits, format records, formal analysis and restoration notes are never silently treated as the same kind of evidence.",
      "Reject claims that Yi Yi invented reflective framing, long takes, ensemble staging, multilingual urban sound or transnational production.",
      "Audit every novelty, influence and thematic claim separately from production facts.",
    ],
    phases: [
      { id: "evidence_map", label: "Map the evidence hierarchy", player_task: "Separate Criterion credits, festival format records, finished-film formal analysis and later restoration documentation before production claims enter the brief." },
      { id: "release_record", label: "Lock the release record", player_task: "Record 2000, 173 minutes, Taiwan/Japan context and credited departments without using later canon status as production evidence." },
      { id: "transnational_production_map", label: "Map the production entities", player_task: "Track producers and listed production companies separately from later distributors, labels and restoration partners." },
      { id: "script_family_threads", label: "Map family threads", player_task: "Break the screenplay into overlapping generational arcs and identify which events are shown, heard, reported or withheld." },
      { id: "architecture_survey", label: "Survey architecture", player_task: "Map walls, windows, corridors, doors, reflective surfaces and performer routes before locking camera positions." },
      { id: "35mm_provenance", label: "Lock 35mm provenance", player_task: "Record 35mm as documented acquisition/preservation evidence while leaving stock, lens and lab details unknown unless separately sourced." },
      { id: "frame_geometry", label: "Design the frame geometry", player_task: "Choose camera height, distance and axis so architecture and ensemble relationships remain readable without relying on corrective reframing later." },
      { id: "reflection_test", label: "Test reflective surfaces", player_task: "Check glass and mirrors for camera visibility, crew reflections, flare, doubled images and exposure shifts before the take is treated as ready." },
      { id: "window_exposure", label: "Balance windows and interiors", player_task: "Coordinate lighting and exposure so exterior brightness, interior faces and reflective layers remain intentional on 35mm." },
      { id: "technique_boundary", label: "Separate visible techniques", player_task: "Tag whether a layered image is a direct reflection, rear projection, superimposition or another method instead of using one label for all visual doubling." },
      { id: "ensemble_blocking", label: "Block the ensemble", player_task: "Rehearse entrances, exits, seated positions and background action inside the fixed architecture so the frame stays alive without constant camera correction." },
      { id: "static_camera_risk", label: "Budget static-frame risk", player_task: "Identify moments where a missed eyeline, focus shift or late entrance cannot be hidden by camera movement and needs another take or alternate plan." },
      { id: "long_take_rehearsal", label: "Rehearse long-duration performance", player_task: "Run complete beats for performance, focus, props, background continuity and sound before committing scarce film stock and time." },
      { id: "coverage_boundary", label: "Protect essential information", player_task: "Identify essential reactions or story facts that need alternate coverage without converting the scene into generic shot-reverse-shot by default." },
      { id: "parallel_edit_map", label: "Map parallel storylines", player_task: "Track family threads across the 173-minute structure so editorial transitions preserve chronology, emotional information and deliberate gaps." },
      { id: "duration_review", label: "Review shot duration", player_task: "Evaluate whether a long-held shot sustains performance and spatial information rather than keeping duration only because the camera remained static." },
      { id: "offscreen_event_design", label: "Design offscreen events", player_task: "Choose what an unseen event contributes through sound, reaction, dialogue or aftermath and document what remains intentionally withheld." },
      { id: "multilingual_dialogue_map", label: "Map multilingual dialogue", player_task: "Track Mandarin, Taiwanese, Japanese and English passages for performance, intelligibility, subtitle and mix needs without ranking one language as the natural default." },
      { id: "urban_sound_beds", label: "Build urban sound beds", player_task: "Create distinct traffic, room-tone and public-space layers that preserve location identity without masking dialogue." },
      { id: "sound_credit_boundary", label: "Respect unknown sound methods", player_task: "Credit Tu Duu-chih and document audible spatial choices while leaving microphone, recorder, ADR and Foley procedures unknown unless a source establishes them." },
      { id: "music_space_balance", label: "Balance music and lived space", player_task: "Place Kaili Peng's music so it coexists with dialogue and environmental sound rather than erasing the film's spatial continuity." },
      { id: "picture_sound_continuity", label: "Review picture-sound continuity", player_task: "Check that offscreen voices, traffic, room tone and reflective visual layers preserve the intended space across cuts." },
      { id: "restoration_negative_provenance", label: "Record negative provenance", player_task: "Store the 2025 4K restoration's use of the original 35mm acetate negative as later preservation evidence, not as a claim about an original digital workflow." },
      { id: "restoration_sound_provenance", label: "Record sound-source provenance", player_task: "Store the Hi8 source used for restoration and Tu Duu-chih's restoration role without inferring the complete original production-recording chain." },
      { id: "restoration_mix_boundary", label: "Separate original and alternate mixes", player_task: "Keep the original theatrical 2.0 surround presentation distinct from the later alternate 5.0 presentation in release metadata." },
      { id: "color_restoration_boundary", label: "Separate restoration color", player_task: "Document Kaili Peng's restoration/color supervision and later color correction without projecting those decisions backward as a year-2000 digital-intermediate process." },
      { id: "comparison_audit", label: "Compare without flattening", player_task: "Compare Yi Yi with other Chapter 18 films through specific production constraints rather than broad labels such as Asian cinema, realism or digital convergence." },
      { id: "method_audit", label: "Audit production versus interpretation", player_task: "Review every technical, thematic, novelty and influence claim against whether it comes from credits, format records, formal analysis, preservation evidence or interpretation." },
    ],
  },
] as const;

export function mergeChapterEighteenYiYiExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterEighteenYiYiExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_eighteen_yi_yi_verified",
      source: { list_id: "manual_chapter_eighteen_yi_yi_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
