import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterNineteenThePowerOfTheDogExpansionDefinitions = [
  {
    id: "scenario_the_power_of_the_dog_2021",
    title: "The Power of the Dog",
    originalTitle: "The Power of the Dog",
    aliases: ["The Power of the Dog"],
    year: 2021,
    titleType: "Movie",
    runtimeMins: 127,
    directors: ["Jane Campion"],
    genres: ["Drama", "Western"],
    sourceId: "arri_the_power_of_the_dog_2021",
    sourceUrl: "https://www.arri.com/news-en/2022-oscar-winners-rely-on-arri-cameras-and-lenses",
    scenarioType: "award_priority_bafta_best_film_jane_campion_ari_wegner_alexa_lf_mini_lf_ultra_panatar_125x_anamorphic_two_lf_one_mini_lf_steadiam_long_prep_storyboards_new_zealand_montana_central_otago_ranch_build_stage_interiors_crls_redirected_sun_hmi_printed_backdrops_pandemic_shutdown_restart_peter_sciberras_avid_editing_sound_richard_flynn_robert_mackenzie_jonny_greenwood_invisible_vfx_jay_hawkins_2021",
    premise: "Build The Power of the Dog as Chapter 19's next award-priority production case because BAFTA records it as the 2022 Best Film winner and Jane Campion as the 2022 Director winner, while keeping awards strictly separate from evidence about how the film was physically made. The case treats Campion's 2021 adaptation of Thomas Savage's 1967 novel as a New Zealand-centered prestige production whose distinctive historical value lies in unusually long visual preparation, large-format digital capture, location-to-stage continuity, pandemic interruption and restart, restrained editorial construction, production-sound-led tension, score/sound interaction and invisible visual effects. BBFC classifies the 2D cinema version at exactly 127 minutes, while BFI lists 125 minutes. The playable case therefore uses 127 minutes and preserves the institutional runtime variance rather than manufacturing a false single-source certainty. Ari Wegner ACS committed to roughly a full year of preparation with Campion. Filmmaker Magazine documents weeks spent on the remote South Island studying seasonal light and references, followed by a final month in a cabin near the location during which Campion and Wegner storyboarded the entire film, acted scenes out to discover blocking, walked to sets under construction and revised boards against the real geography. That prep did not make photography rigid. Wegner explicitly describes on-day discoveries, including the long-lens final image of Peter and the ranch, so the case treats preparation as a system for informed responsiveness rather than a prohibition on spontaneity. ARRI documents ALEXA LF as the main camera and ALEXA Mini LF as support, with full-size LFs used for principal work and a Mini LF for Steadicam. The Society of Camera Operators gives the operating package more precisely as two ALEXA LF bodies plus one Mini LF, paired with Ultra Panatar 1.25x anamorphic primes at 35, 40, 50, 65, 75, 100, 135 and 180 mm and a 200-400 mm 70-series full-frame zoom. Post Magazine records that the film was shot 4K and that Wegner chose Panavision Ultra Panatar anamorphics after spherical/anamorphic testing because the storyboarding process kept pushing the frame wider. The production lesson is not simply 'large format looks cinematic': the larger sensor, subtle anamorphic compression, long-lens landscape work, Steadicam mobility and precise interior framing were coordinated with performance and geography. Central Otago and the South Island stood in for Montana. The Burbank ranch exterior was physically built on location, while major house interiors were constructed separately on a stage. Netflix records Grant Major's team building the large ranch house from scratch in a windy New Zealand valley and weathering it so it appeared to have existed for decades. Wegner states that most house interiors were built on a stage in Auckland, with the kitchen and cowboy dining room also built on location. The team therefore had to make stage interiors feel geographically continuous with the South Island exterior rather than letting the movie visually detach when it went indoors. Filmmaker documents printed panoramic location photographs used as large movable backdrops for stage windows, with HMIs supplying sun and the backdrops themselves contributing reflected light. Major and Wegner designed the house around dark timber, controlled windows and an intentionally claustrophobic relationship between bright exterior and shadowed interior. Lighting was built around this contrast. Wegner used Cine Reflect Lighting System reflectors extensively, including outdoors to redirect the powerful New Zealand sun rather than overpower it with a separate source. The Red Mill stage work combined printed exterior panoramas, HMI sunlight and CRLS reflection. Small image details, including eye light and reflective highlights, were used to keep faces alive inside deep shadow. These specifics support an evidence-bounded lighting system but do not establish a complete fixture, power-distribution or exposure ledger for the whole film. The production also demonstrates how visual effects can be deeply planned while remaining intentionally invisible. Netflix and Wegner describe the mountain 'dog' as a visual-effect problem designed before photography with VFX supervisor Jay Hawkins so that the final form would register as plausible pareidolia rather than an obvious graphic. Befores & Afters records Alt.vfx work including environment extensions, CG cattle and subtle reshaping/shadow work for the dog. Wegner says the team planned framing around VFX questions such as how a scene would read with 2,000 cattle rather than 200. The case therefore rejects both 'the film is naturalistic so it has almost no VFX' and 'the landscape is digitally manufactured' as unsupported absolutes. Production design, capture and effects were negotiated together before day one. Costume design followed the same character-first integration. Kirsty Cameron describes Phil's workwear as an extension of his body and masculinity, using industrial canvas, cotton and Japanese selvedge denim, with garments beaten, sanded, wire-brushed, dyed and burned to build physical wear. The principal characters worked from comparatively small 'suitcase wardrobes', natural fibers were emphasized, and garments were designed to respond to both character movement and the film's light. Current locked sources support these methods without establishing a complete garment census, duplicate count, laundry/continuity ledger or full makeup/prosthetic workflow. COVID-19 became an actual production-system rupture rather than merely release context. Screen Daily records that principal photography had been underway for several weeks in 2020 when production shut down for approximately four months. Campion says the pause gave her time to review what had already been shot and determine what was working and what could improve in the second half. Some cast remained in New Zealand while others returned to Los Angeles and later came back through quarantine. Filmmaker records Wegner observing a specific eye-light effect during her own two-week quarantine and later incorporating that visual observation. The restart therefore altered preparation, review and creative knowledge without erasing continuity between the two halves of photography. Editor Peter Sciberras' workflow similarly straddled the shutdown. The Rough Cut and later interviews document editing in isolation during the pandemic, perspective shifts between characters, tension built between lines of dialogue and an Avid-based workflow. Sciberras says he had substantial dailies available during the interruption and continued returning to the material; after production wrapped he had a rough cut within roughly a week to a week and a half, with quarantine shaping the handoff back to Campion. Frame.io documents his layered selects process and the way he compared initial reactions with later selections alongside Campion. He also records a COVID-break voice-recording session with Kodi Smit-McPhee used to explore Peter's point of view. The edit therefore was not a simple postproduction phase after shooting: the pandemic created a long reflective interval in which existing material, performance ideas and later production choices could influence one another. Sound is equally structural. Netflix records production sound mixer Richard Flynn and supervising sound editor Robert Mackenzie building the Burbank-house soundscape around isolation, threat and psychological pressure. The piano-versus-banjo sequence was treated as a pivotal sound-led relationship scene rather than ordinary music playback. Mackenzie describes sound design as a means of moving between the openness of the landscape and Rose's confinement inside the house. Current locked sources support the production/supervising-sound roles and the conceptual use of detailed quiet sounds, but they do not establish a complete microphone inventory, radio-frequency plan, ADR/Foley cue ledger, premix routing or final stem architecture, so those remain unresolved. Jonny Greenwood's score developed in parallel with editing and sound rather than arriving only after picture lock. Mackenzie states that Greenwood sent musical sketches through to the cutting room while the sound team sent stereo mixdowns of its work, allowing Campion to hear and curate the relationship among score, effects and picture throughout the edit. Netflix's score featurette independently documents Greenwood and Campion discussing the score's construction. The case therefore treats score, sound and editorial rhythm as an iterative system while leaving full recording-session personnel, instrument-by-cue, mix-stem and mastering documentation outside the locked boundary. Awards establish why the film is prioritized in Chapter 19, not how any department worked. Current locked sources do not establish a single audited final negative cost, complete financing waterfall, exact total principal-photography day count, exhaustive crew census, complete camera serial/body-to-shot allocation, every lens-to-shot mapping, full lighting/grip/power ledger, complete animal-safety and stunt records, complete costume/makeup duplicate ledger, full VFX shot/vendor ledger beyond documented examples, complete editorial project/version history, full production-sound/ADR/Foley/premix/stem architecture, complete score-session ledger, or distribution recoupment economics. Those remain explicit unresolved boundaries.",
    requiredChoicesSeed: {
      screenplay: ["award_priority_not_workflow_evidence", "thomas_savage_1967_adaptation", "bbfc_127_cinema_runtime", "bfi_125_runtime_variance", "budget_finance_unresolved"],
      camera: ["alexa_lf_main", "alexa_mini_lf_steadicam", "two_lf_one_mini_lf", "ultra_panatar_125_anamorphic", "35_to_180_prime_set", "200_400_full_frame_zoom", "four_k_capture", "crls_redirected_sun", "hmi_stage_sun", "printed_panorama_backdrops", "location_stage_continuity"],
      editing: ["peter_sciberras_avid", "pandemic_isolation_editing", "dailies_during_shutdown", "layered_selects", "perspective_shifts", "rough_cut_quick_after_wrap", "kodi_voice_session_during_break"],
      sound: ["richard_flynn_production_sound", "robert_mackenzie_supervising_sound", "house_isolation_soundscape", "piano_banjo_tension", "greenwood_sound_edit_iteration", "full_sound_chain_unresolved"],
      themes: ["film_history", "2021", "the_power_of_the_dog", "bafta_best_film", "new_zealand_for_montana", "pandemic_shutdown_restart", "large_format_digital", "invisible_vfx", "chapter19"]
    },
    learningGoals: [
      "Explain why the 2022 BAFTA Best Film win justifies award-priority selection without proving production workflow.",
      "Identify Jane Campion as writer-director and separate her BAFTA Director win from craft evidence.",
      "Identify Thomas Savage's 1967 novel as the adaptation source without inventing a scene-by-scene adaptation map.",
      "Preserve BBFC's exact 127-minute cinema classification and BFI's 125-minute listing as an institutional runtime variance.",
      "Use 127 minutes as the rounded playable cinema runtime while keeping the conflicting BFI record visible.",
      "Identify Ari Wegner ACS as cinematographer.",
      "Explain the roughly full year of Campion-Wegner preparation as an unusual production resource.",
      "Explain weeks of seasonal-light observation on New Zealand's South Island as preproduction research.",
      "Explain the final month of cabin-based storyboarding as a blocking and geography workflow.",
      "Explain acting scenes out during storyboarding as a way to discover blocking before photography.",
      "Explain repeated visits to sets under construction as a feedback loop between design, camera and blocking.",
      "Reject the claim that complete storyboarding eliminated spontaneous on-day discoveries.",
      "Identify ALEXA LF as the documented main camera system.",
      "Identify ALEXA Mini LF as the documented Steadicam/support system.",
      "Preserve the Society of Camera Operators record of two ALEXA LF bodies and one Mini LF.",
      "Identify Panavision Ultra Panatar 1.25x anamorphic primes as the principal documented lens family.",
      "Preserve the documented 35, 40, 50, 65, 75, 100, 135 and 180 mm prime range without inventing shot assignments.",
      "Identify the 200-400 mm 70-series full-frame zoom as a documented support lens.",
      "Preserve Post Magazine's 4K capture statement without inventing a complete codec/media ledger.",
      "Explain why storyboarding pushed the team toward a wider frame and subtle anamorphic rendering.",
      "Explain large-format capture as a relationship among sensor size, lenses, landscape, intimacy and movement rather than a prestige label.",
      "Identify Central Otago and the South Island as the principal Montana stand-in geography.",
      "Explain the physically built Burbank ranch exterior as part of the production's geographic continuity.",
      "Identify Grant Major as production designer.",
      "Explain the ranch house build and weathering process as narrative world construction rather than surface decoration.",
      "Distinguish on-location ranch/kitchen/dining builds from the major stage-built house interiors.",
      "Explain why stage interiors had to preserve visual continuity with the South Island landscape.",
      "Explain printed panoramic location photographs as in-camera stage-window scenery for selected interiors.",
      "Identify HMIs as documented simulated sunlight for the Red Mill stage work.",
      "Identify CRLS reflectors as a documented tool for redirected and bounced light.",
      "Explain Wegner's 'fight the sun with the sun' approach as redirecting existing sunlight rather than overpowering it.",
      "Explain the bright-exterior/dark-interior contrast as a coordinated cinematography/production-design choice.",
      "Explain small eye-light and reflective details as ways to preserve readable faces inside deep shadow.",
      "Keep the complete fixture, dimming, generator, power and exposure ledgers unresolved.",
      "Identify Jay Hawkins as the documented VFX supervisor in current production-facing sources.",
      "Explain the mountain dog as planned invisible VFX based on pareidolia rather than an obvious creature effect.",
      "Identify environment extensions and CG cattle as documented invisible-effects examples.",
      "Explain planning for apparent cattle scale before photography as VFX/camera integration.",
      "Reject both zero-VFX naturalism and digitally manufactured landscape as unsupported absolutes.",
      "Keep the complete VFX vendor and shot ledger unresolved.",
      "Identify Kirsty Cameron as costume designer.",
      "Explain Phil's industrial canvas, cotton and selvedge-denim wardrobe as character and physicality design.",
      "Explain sanding, wire brushing, dyeing and burning as documented garment-distress methods.",
      "Explain the small 'suitcase wardrobe' approach as performer familiarity and character consistency rather than evidence of a complete costume census.",
      "Explain natural fibers and light-aware dye choices as connections between costume, performance and cinematography.",
      "Keep the complete wardrobe duplicate, laundry, continuity and makeup ledgers unresolved.",
      "Explain the 2020 COVID shutdown as a production-system interruption rather than release-history trivia.",
      "Preserve the approximately four-month shutdown documented by Campion.",
      "Explain cast travel and quarantine as restart logistics without inventing undocumented health protocols.",
      "Explain Campion's review of already-shot material during shutdown as creative feedback into the second half of production.",
      "Explain Wegner's quarantine eye-light observation as a documented example of interruption feeding later visual design.",
      "Identify Peter Sciberras as editor.",
      "Explain editing with substantial dailies during the shutdown as a production/post overlap.",
      "Identify Avid as Sciberras' documented editing system.",
      "Explain layered selects as a method for comparing first reactions with later Campion selections.",
      "Explain perspective shifts and tension between dialogue lines as editorial story construction.",
      "Preserve the roughly one-to-one-and-a-half-week post-wrap rough-cut timing as Sciberras' own estimate rather than a precise production ledger.",
      "Explain the Kodi Smit-McPhee voice session during the COVID break as exploratory editorial/performance work.",
      "Identify Richard Flynn as production sound mixer.",
      "Identify Robert Mackenzie as supervising sound editor.",
      "Explain the Burbank-house soundscape as a way to express Rose's isolation and threat.",
      "Explain the piano-versus-banjo sequence as a sound-led dramatic relationship rather than ordinary source music.",
      "Keep the complete microphone, RF, ADR, Foley, premix and stem architecture unresolved.",
      "Identify Jonny Greenwood as composer.",
      "Explain score sketches moving to the cutting room while sound-design mixdowns moved back as an iterative collaboration.",
      "Explain Campion's curation of picture, sound and score as evidence against a simple post-lock music pipeline.",
      "Keep complete score-session, cue, mix and mastering ledgers unresolved.",
      "Keep audited final budget, financing waterfall, exact shoot-day count and exhaustive crew census unresolved.",
      "Keep full camera serial allocation, lens-to-shot map, animal/stunt record and distribution economics unresolved.",
      "Close the case only when award priority, runtime provenance, prep, camera/lens system, location/stage design, lighting, pandemic restart, edit, sound, score, VFX and uncertainty boundaries agree."
    ],
    phases: [
      { id: "award_priority", label: "Lock BAFTA Best Film priority", player_task: "Use the 2022 BAFTA Best Film win to justify case order while keeping awards separate from workflow evidence." },
      { id: "evidence_hierarchy", label: "Map the evidence hierarchy", player_task: "Separate BAFTA, BBFC and BFI records from ARRI, Netflix and direct craft testimony." },
      { id: "runtime_boundary", label: "Freeze runtime provenance", player_task: "Use the 127-minute BBFC cinema version while preserving BFI's 125-minute listing." },
      { id: "finance_boundary", label: "Freeze unresolved finance", player_task: "Do not canonicalize budget, financing shares or recoupment without audited evidence." },
      { id: "year_long_prep", label: "Fund the long prep", player_task: "Use the extended Campion-Wegner preparation period to study light, references, geography and blocking." },
      { id: "seasonal_light", label: "Learn the South Island light", player_task: "Observe the location in the intended shooting season before fixing the visual plan." },
      { id: "storyboard_cabin", label: "Storyboard the whole film", player_task: "Draw, perform, visit the construction site and revise boards against real geography." },
      { id: "responsive_plan", label: "Leave room for discovery", player_task: "Treat storyboards as a knowledge base while allowing strong unplanned images to enter the film." },
      { id: "camera_package", label: "Build the large-format camera package", player_task: "Use two ALEXA LF bodies for principal work and a Mini LF for Steadicam/support." },
      { id: "anamorphic_package", label: "Choose subtle anamorphic lenses", player_task: "Build around Ultra Panatar 1.25x primes and the documented long zoom without inventing a shot ledger." },
      { id: "widescreen_logic", label: "Let blocking define frame shape", player_task: "Connect the wider frame to storyboarding, landscape and character relationships." },
      { id: "location_geography", label: "Make New Zealand read as Montana", player_task: "Use South Island geography as a coherent production world rather than isolated scenic plates." },
      { id: "ranch_build", label: "Build and age the ranch", player_task: "Construct the Burbank ranch exterior and weather it into the landscape." },
      { id: "stage_interiors", label: "Rebuild interiors on stage", player_task: "Use controlled interiors while preserving the geographic logic of the exterior ranch." },
      { id: "window_backdrops", label: "Carry landscape into the studio", player_task: "Use panoramic location backdrops and controlled sunlight so stage windows still belong to the South Island world." },
      { id: "crls_sun", label: "Redirect natural sun", player_task: "Use CRLS reflectors to shape powerful exterior sunlight rather than merely adding more fixtures." },
      { id: "interior_darkness", label: "Protect dark interiors", player_task: "Coordinate production design, window treatment and small highlights to keep the house threatening without losing faces." },
      { id: "vfx_design", label: "Plan invisible VFX early", player_task: "Design cattle scale, environment seams and the mountain dog before photography rather than treating them as rescue work." },
      { id: "dog_pareidolia", label: "Make the dog barely visible", player_task: "Shape a plausible shadow/hill image that only resolves when the viewer knows what to seek." },
      { id: "costume_physicality", label: "Build costume into performance", player_task: "Use material, patina and small wardrobes so clothing behaves like lived-in character equipment." },
      { id: "shutdown", label: "Absorb the pandemic shutdown", player_task: "Pause safely while protecting material, continuity and the possibility of a restart." },
      { id: "review_during_pause", label: "Review the first half", player_task: "Use the four-month interruption to identify what is working and feed that knowledge into later photography." },
      { id: "restart", label: "Restart through quarantine", player_task: "Reassemble cast and crew without pretending the production resumed under unchanged conditions." },
      { id: "edit_during_shutdown", label: "Keep editing alive", player_task: "Use available dailies during the shutdown to preserve contact with the film and test structure." },
      { id: "avid_selects", label: "Trace editorial reactions", player_task: "Use Avid and layered selects to compare first impressions with later director-guided choices." },
      { id: "perspective_edit", label: "Shift point of view carefully", player_task: "Build tension and ambiguity through character perspective rather than explanatory cutting." },
      { id: "voice_session", label: "Explore Peter's interior voice", player_task: "Use the pandemic-break recording session as exploratory material rather than assuming every line was predetermined." },
      { id: "house_soundscape", label: "Make the house sound threatening", player_task: "Use detailed interior sound and contrast with open landscape to express Rose's isolation." },
      { id: "piano_banjo", label: "Stage the musical intimidation", player_task: "Treat piano and banjo timing as dramatic action and psychological sound design." },
      { id: "score_sound_loop", label: "Iterate score and sound", player_task: "Exchange Greenwood sketches and sound-design mixdowns through the cutting room while picture remains responsive." },
      { id: "uncertainty_audit", label: "Audit unresolved ledgers", player_task: "Keep unsupported budget, schedule, camera, VFX, sound, costume and release details outside canonical truth." },
      { id: "production_verification", label: "Close Production Verification", player_task: "Close only when award priority, provenance, prep, capture, design, lighting, VFX, pandemic restart, edit, sound, music and uncertainty boundaries agree." }
    ]
  }
] as const;

export function mergeChapterNineteenThePowerOfTheDogExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterNineteenThePowerOfTheDogExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_nineteen_the_power_of_the_dog_verified",
      source: { list_id: "manual_chapter_nineteen_the_power_of_the_dog_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
