import assert from "node:assert/strict";
import test from "node:test";

import { chapterEighteenTheRevenantExpansionDefinitions } from "./chapterEighteenTheRevenantExpansion.js";

test("Chapter 18 materializes The Revenant as a source-first natural-light digital large-format production case", () => {
  assert.equal(chapterEighteenTheRevenantExpansionDefinitions.length, 1);
  const film = chapterEighteenTheRevenantExpansionDefinitions[0];
  assert.equal(film.id, "scenario_the_revenant_2015");
  assert.equal(film.year, 2015);
  assert.equal(film.runtimeMins, 156);
  assert.deepEqual(film.directors, ["Alejandro González Iñárritu"]);
  assert.ok(film.scenarioType.includes("digital_large_format") && film.scenarioType.includes("natural_light") && film.scenarioType.includes("remote_location"));
  assert.ok(film.scenarioType.includes("alexa_m") && film.scenarioType.includes("alexa_xt") && film.scenarioType.includes("alexa_65"));
  assert.ok(film.scenarioType.includes("master_prime") && film.scenarioType.includes("prime65") && film.scenarioType.includes("long_take") && film.scenarioType.includes("vfx"));
  assert.ok(film.premise.includes("BFI") && film.premise.includes("156 minutes"));
  assert.ok(film.premise.includes("Mark L. Smith") && film.premise.includes("Emmanuel Lubezki") && film.premise.includes("Stephen Mirrione") && film.premise.includes("Jack Fisk"));
  assert.ok(film.premise.includes("ALEXA XT") && film.premise.includes("ALEXA M") && film.premise.includes("ALEXA 65"));
  assert.ok(film.premise.includes("Master Primes") && film.premise.includes("Prime 65"));
  assert.ok(film.premise.includes("selected/significant portions") && film.premise.includes("rather than the whole film"));
  assert.ok(film.premise.includes("chronological shooting") && film.premise.includes("natural light") && film.premise.includes("period-correct firelight"));
  assert.ok(film.premise.includes("Argentina") && film.premise.includes("warm weather") && film.premise.includes("snow"));
  assert.ok(film.premise.includes("film acquisition was tested") && film.premise.includes("abandoned in favor of digital"));
  assert.ok(film.premise.includes("handheld") && film.premise.includes("Steadicam") && film.premise.includes("crane/dolly"));
  assert.ok(film.premise.includes("ILM") && film.premise.includes("six-minute") && film.premise.includes("multiple plates and performances"));
  assert.ok(film.premise.includes("MPC") && film.premise.includes("more than 100") && film.premise.includes("39 extended shots") && film.premise.includes("2.5D projection"));
  assert.ok(film.premise.includes("video-tap") && film.premise.includes("locked and turned over") && film.premise.includes("principal photography"));
  assert.ok(film.premise.includes("Karl Bodmer") && film.premise.includes("real local materials"));
  assert.ok(film.premise.includes("Lon Bender") && film.premise.includes("Martín Hernández") && film.premise.includes("Randy Thom"));
  assert.ok(film.premise.includes("exact total budget") && film.premise.includes("exact shooting-day count") && film.premise.includes("exact percentage of ALEXA 65 footage"));
  assert.ok(film.premise.includes("universal lens-per-shot maps") && film.premise.includes("exact stunt rig geometry") && film.premise.includes("production-sound recorder/microphone chain"));
  assert.ok(film.requiredChoicesSeed.camera.includes("alexa_65_selected"));
  assert.ok(film.requiredChoicesSeed.camera.includes("natural_light_windows"));
  assert.ok(film.requiredChoicesSeed.editing.includes("vfx_early_turnover"));
  assert.ok(film.requiredChoicesSeed.sound.includes("production_sound_equipment_unknowns"));
  assert.ok(film.learningGoals.some((goal) => goal.includes("156-minute") && goal.includes("canonical runtime")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("chronological") && goal.includes("seasonal progression")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("ALEXA M") && goal.includes("ALEXA XT")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("ALEXA 65") && goal.includes("selected") && goal.includes("entire feature")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("conflicting published estimates") && goal.includes("ALEXA 65 percentage")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Master Primes") && goal.includes("Prime 65")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("film acquisition") && goal.includes("digital") && goal.includes("low-light")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("natural-light strategy") && goal.includes("scheduling")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("warm conditions") && goal.includes("snow") && goal.includes("geographic")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("monitor") && goal.includes("cables") && goal.includes("battery")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("controlled-light exceptions") && goal.includes("zero artificial light")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Jack Fisk") && goal.includes("wide-angle scrutiny")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Karl Bodmer") && goal.includes("historical source")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("handheld") && goal.includes("Steadicam") && goal.includes("crane/dolly")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("hidden stitches") && goal.includes("multiple plates")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Stephen Mirrione") && goal.includes("preproduction") && goal.includes("principal photography")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("rehearsal/video-tap") && goal.includes("rhythm")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("ILM") && goal.includes("digital animal animation") && goal.includes("multiple plates")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("six-minute") && goal.includes("one untreated camera take")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("MPC") && goal.includes("more than 100") && goal.includes("39 extended shots")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("2.5D projection") && goal.includes("sky replacement") && goal.includes("CG arrows")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Lon Bender") && goal.includes("Martín Hernández") && goal.includes("Randy Thom")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("exact total budget") && goal.includes("ALEXA 65 percentage") && goal.includes("stunt rigging")));
  assert.ok(film.phases.find((phase) => phase.id === "released_version")?.player_task.includes("156-minute"));
  assert.ok(film.phases.find((phase) => phase.id === "alexa_65")?.player_task.includes("percentage disagreement"));
  assert.ok(film.phases.find((phase) => phase.id === "firelight_exception")?.player_task.includes("controlled cushion-light"));
  assert.ok(film.phases.find((phase) => phase.id === "bear_plate_strategy")?.player_task.includes("digital bear animation"));
  assert.ok(film.phases.find((phase) => phase.id === "opening_vfx")?.player_task.includes("2.5D"));
  assert.ok(film.phases.find((phase) => phase.id === "early_vfx_turnover")?.player_task.includes("vendor"));
  assert.ok(film.phases.find((phase) => phase.id === "unknowns_register")?.player_task.includes("ALEXA 65 percentage") && film.phases.find((phase) => phase.id === "unknowns_register")?.player_task.includes("VFX software"));
  assert.ok(film.learningGoals.length >= 50);
  assert.ok(film.phases.length >= 30);
});