import assert from "node:assert/strict";
import test from "node:test";
import { chapterNineteenKillersOfTheFlowerMoonExpansionDefinitions, mergeChapterNineteenKillersOfTheFlowerMoonExpansion } from "./chapterNineteenKillersOfTheFlowerMoonExpansion.js";

test("Killers of the Flower Moon source-first production case is complete and evidence-bounded", () => {
  assert.equal(chapterNineteenKillersOfTheFlowerMoonExpansionDefinitions.length, 1);
  const film = chapterNineteenKillersOfTheFlowerMoonExpansionDefinitions[0];
  assert.equal(film.id, "scenario_killers_of_the_flower_moon_2023");
  assert.equal(film.title, "Killers of the Flower Moon");
  assert.equal(film.year, 2023);
  assert.equal(film.runtimeMins, 200);
  assert.deepEqual(film.directors, ["Martin Scorsese"]);
  assert.equal(film.sourceId, "afi_killers_of_the_flower_moon_2023");
  assert.equal(film.sourceUrl, "https://watch.afi.com/movie/killers-of-the-flower-moon");
  assert.match(film.scenarioType, /industrial_scale_technical/);
  assert.match(film.scenarioType, /community_situated_historical/);
  assert.match(film.scenarioType, /arricam_st_lt/);
  assert.match(film.scenarioType, /sony_venice/);
  assert.match(film.scenarioType, /bell_howell_2709/);
  assert.match(film.scenarioType, /ilm_700_invisible_vfx/);
  assert.ok(film.premise.includes("Osage Nation Language Teachers"));
  assert.ok(film.premise.includes("Wahzhazhe clothing"));
  assert.ok(film.premise.includes("Osage Nation Reservation"));
  assert.ok(film.premise.includes("Julie O'Keefe"));
  assert.ok(film.premise.includes("Addie Roanhorse"));
  assert.ok(film.premise.includes("Arricam ST and LT"));
  assert.ok(film.premise.includes("Sony Venice"));
  assert.ok(film.premise.includes("Phantom Flex4K"));
  assert.ok(film.premise.includes("Bell & Howell 2709"));
  assert.ok(film.premise.includes("VISION3 250D 5207"));
  assert.ok(film.premise.includes("VISION3 50D 5203"));
  assert.ok(film.premise.includes("VISION3 500T 5219"));
  assert.ok(film.premise.includes("DOUBLE-X 5222"));
  assert.ok(film.premise.includes("2.39:1 anamorphic"));
  assert.ok(film.premise.includes("Petzval"));
  assert.ok(film.premise.includes("burial at noon"));
  assert.ok(film.premise.includes("roughly 700 visual-effects shots"));
  assert.ok(film.premise.includes("about 85 minutes"));
  assert.ok(film.premise.includes("reviewed dailies together over Zoom"));
  assert.ok(film.premise.includes("around twelve edits"));
  assert.ok(film.premise.includes("partnership with Paramount Pictures"));
  assert.ok(film.premise.includes("remain unresolved"));
  assert.ok(film.learningGoals.length >= 48);
  assert.ok(film.phases.length >= 32);
  assert.equal(film.phases.at(-1)?.id, "production_verification");
  assert.ok(film.phases.find((phase) => phase.id === "representation_boundary")?.player_task.includes("Osage participation"));
  assert.ok(film.phases.find((phase) => phase.id === "invisible_vfx")?.player_task.includes("700"));
  assert.ok(film.phases.find((phase) => phase.id === "remote_editorial")?.player_task.includes("Zoom"));
  assert.ok(film.requiredChoicesSeed.camera.includes("double_x_5222"));
  assert.ok(film.requiredChoicesSeed.editing.includes("remote_zoom_dailies"));
  assert.ok(film.requiredChoicesSeed.themes.includes("theatrical_platform_distribution"));
});

test("Killers expansion merges idempotently by normalized title", () => {
  const once = mergeChapterNineteenKillersOfTheFlowerMoonExpansion([]);
  assert.equal(once.length, 1);
  const twice = mergeChapterNineteenKillersOfTheFlowerMoonExpansion(once);
  assert.equal(twice.length, 1);
  assert.equal(twice[0]?.id, "scenario_killers_of_the_flower_moon_2023");
});
