import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterNineteenGuillermoDelTorosPinocchioExpansionDefinitions = [
  {
    id: "scenario_guillermo_del_toros_pinocchio_2022",
    title: "Guillermo del Toro's Pinocchio",
    originalTitle: "Guillermo del Toro's Pinocchio",
    aliases: ["Guillermo del Toro's Pinocchio", "Pinocchio"],
    year: 2022,
    titleType: "Movie",
    runtimeMins: 117,
    directors: ["Guillermo del Toro", "Mark Gustafson"],
    genres: ["Animation", "Drama", "Fantasy", "Musical"],
    sourceId: "netflix_guillermo_del_toros_pinocchio_stop_motion_2022",
    sourceUrl: "https://www.netflix.com/tudum/articles/pinocchio-stop-motion-behind-the-scenes",
    scenarioType: "award_priority_oscar_best_animated_feature_stop_motion_shadowmachine_mackinnon_saunders_taller_del_chucho_guillermo_del_toro_mark_gustafson_georgina_hayns_brian_leif_hansen_frank_passingham_holly_klein_ken_schretzmann_scott_martin_gershin_alexandre_desplat_940_capture_days_sixty_units_forty_one_animators_puppet_hospital_mechanical_faces_replacement_face_pinocchio_3d_printed_metal_armature_canon_5d_mark_iv_nikon_zeiss_laowa_dragonframe_motion_control_layered_lighting_tungsten_key_led_bounce_avid_remote_pandemic_edit_mono_to_atmos_wood_instrument_score_2022",
    premise: "Build Guillermo del Toro's Pinocchio as Chapter 19's next award-priority animation production case because the Academy records Guillermo del Toro, Mark Gustafson, Gary Ungar and Alex Bulkley as the 2023 Animated Feature Film winners, while keeping award status separate from evidence about how the film was made. BBFC records a 2D cinema version at 116 minutes 36 seconds, a 2022 streaming classification at the same duration and a later physical/VOD version at 117 minutes 44 seconds; Netflix's platform page presents a still longer playback duration. The playable record therefore rounds the BBFC cinema master to 117 minutes and preserves platform/home variation instead of pretending every release is frame-identical. The stop-motion production itself was exceptionally long and parallelized. Netflix records 940 capture days and more than 60 units operating or preparing concurrently. Animation supervisor Brian Leif Hansen describes joining in January 2019, the first frame being photographed in August 2019 and the last frame in August 2022, with production scaling to a maximum of 41 animators across 60 sets. These figures describe the physical stop-motion shoot, not the full earlier development history: Mackinnon & Saunders records involvement approximately 15 years before release, so early design/prototyping must remain distinct from final production photography. Puppet counts also vary by source and must stay provenance-bound. Netflix records 32 Pinocchio puppets, while Hansen recalls about 30 Pinocchios, 18 Geppettos and seven Volpes in simultaneous production. The case treats that as a source-specific census rather than forcing a false single total. Georgina Hayns describes a distributed puppet system involving ShadowMachine in Portland, Mackinnon & Saunders in England and a Guadalajara unit in Mexico. Human characters largely used mechanical facial systems so animators could directly shape performance through articulated faces, while Pinocchio required a different replacement-face strategy because a flexible skin would break the continuity of visible wood grain. Mackinnon & Saunders and additive-manufacturing documentation show Pinocchio's armature using extensive metal 3D printing, with more than 100 articulated components/hinges documented in the fabrication record. Netflix also documents a puppet hospital that continually altered joint tension, range and shot-specific anatomy for animator needs. This means puppet fabrication was not finished at handoff; maintenance, repair and adaptation were live production departments. The design principle was described as 'perfectly imperfect': every set, surface, costume and prop had to be deliberately fabricated, aged and textured rather than inherited from a real location. The production therefore treats material imperfection as a controlled aesthetic choice, not sloppy execution. Cinematography was physical miniature photography rather than rendered CG. Frank Passingham documents Canon 5D Mark IV bodies with Nikon, Zeiss and LAOWA lenses, four lighting/camera teams and a lighting strategy built around tungsten direct/key light with LED bounce/indirect light. His layered-lighting method used motion control and repeated exposures/passes so a single animation performance could receive separate underwater, sunlight, torch, moonlight or moving-light treatments before digital combination. This is not a generic recipe for stop motion; it is title-specific evidence of how the production used repeatable animation, Dragonframe-era motion-control logic and compositing to achieve live-action-like naturalism while retaining stylization. Green screen was used especially for skies, while printed backgrounds were sometimes chosen where they reduced VFX cost without compromising the shot. Motion-control blocking had to be negotiated with animators because camera track, puppet access, light placement and physical stage dimensions constrained what storyboarded moves were actually possible. Editorial therefore functioned before, during and after photography. Editors Ken Schretzmann and Holly Klein describe an Avid project that evolved from storyboards to still camera tests, motion-control passes, live-action animator reference, blocking/rehearsal, final animation and VFX. Klein describes collaging these stages in Avid as a live production map across roughly 40 to 60 active stages. Camera moves were re-timed editorially, but any timing change had to be checked against the available physical track. Pandemic shutdown moved editorial home in March 2020; the team continued remotely, reviewing cuts online while physical studio work adopted constrained one-person-in/one-person-out practices. This makes the film a strong Chapter 19 case not only for stop motion but for pandemic-era distributed production continuity. Sound was designed as character performance rather than generic wood Foley. Supervising sound designer Scott Martin Gershin describes building Pinocchio from wood hits, creaks, rubber and metal recordings, selecting and shaping sounds according to emotional state. The mix begins with a deliberately puppet-theater-like mono presentation and gradually expands spatially until the third act uses full Atmos, making spatial growth part of the character arc. Gershin also describes selective treatment of the Wood Sprite and Death voices and a restrained 'minimalistic jazz' philosophy in which not every movement receives sound. Alexandre Desplat's score follows a related material logic. MoMA's production archive records his choice to avoid brass and cymbals and to build the score around guitars, mandolin, piano, harp, strings and woodwinds, aiming for an instrumental world that felt as if it could belong to the village and the handcrafted puppets. The music supervisor describes the film as containing musical moments rather than functioning as an uninterrupted conventional musical, with songs used as character and narrative compression. The locked evidence does not establish a single audited final production budget, financing waterfall, exact all-department crew total, complete puppet census reconciled across every source, every puppet/armature revision, every set count by location, full camera serial/lens-per-shot list, complete Dragonframe and motion-control software/version ledger, every exposure and lighting pass, complete VFX vendor/shot ledger, full color-management/DI settings, every editorial revision, complete dialogue/ADR/Foley recording log, complete Atmos stem/master specification, full score-session ledger, dubbing-production ledger or distribution/recoupment accounting. Those remain explicit unresolved boundaries. The production-history lesson is therefore not simply that stop motion is handmade. It is that a large contemporary stop-motion feature can combine artisanal puppet performance, additive manufacturing, miniature cinematography, motion control, digital compositing, Avid-based iterative editorial, remote pandemic coordination, spatial sound and orchestral recording without erasing the physical labor visible in every frame.",
    requiredChoicesSeed: {
      screenplay: ["oscar_priority_not_workflow_evidence", "bbfc_116m36_cinema_master", "runtime_version_variance", "fifteen_year_development_boundary", "940_capture_days", "finance_unresolved"],
      camera: ["canon_5d_mark_iv", "nikon_zeiss_laowa_lenses", "layered_lighting", "motion_control", "tungsten_key_led_bounce", "green_screen_and_printed_backgrounds", "full_camera_ledger_unresolved"],
      editing: ["avid_storyboard_to_vfx_pipeline", "camera_move_retiming", "live_action_animator_reference", "forty_to_sixty_stage_map", "pandemic_remote_edit", "full_revision_ledger_unresolved"],
      sound: ["pinocchio_material_sound_identity", "mono_to_atmos_arc", "selective_sound_restraint", "wood_sprite_death_spatial_voice", "alexandre_desplat_material_score", "full_mix_master_unresolved"],
      themes: ["film_history", "2022", "guillermo_del_toros_pinocchio", "oscar_best_animated_feature", "stop_motion", "distributed_puppet_fabrication", "pandemic_production", "chapter19"]
    },
    learningGoals: [
      "Explain why the 2023 Animated Feature Film Oscar justifies award-priority selection without proving production workflow.",
      "Identify Guillermo del Toro and Mark Gustafson as co-directors and separate that role from the producers named in the Academy record.",
      "Use BBFC's 116m36s cinema version as the canonical runtime anchor.",
      "Round the playable runtime to 117 minutes while preserving later home and platform variants.",
      "Explain why release-version runtime differences must not be collapsed into one false exact master.",
      "Separate approximately fifteen years of early development/prototyping from the later production-photography period.",
      "Use Netflix's 940 capture days as a stop-motion photography duration anchor rather than a complete project-development duration.",
      "Explain the logic of more than 60 concurrent shooting/preparation units.",
      "Identify Brian Leif Hansen's January 2019 start, August 2019 first frame and August 2022 last frame as direct animation-supervisor testimony.",
      "Explain the maximum of 41 animators across 60 sets as a peak production condition rather than a fixed daily crew census.",
      "Preserve the source variance between 32 Pinocchio puppets and Hansen's recollection of about 30.",
      "Identify the documented 18 Geppetto and seven Volpe puppets as concurrency evidence.",
      "Explain why duplicate hero puppets are a scheduling technology in stop motion.",
      "Map the distributed puppet teams across Portland, Manchester and Guadalajara.",
      "Explain how pandemic-era collaboration made geographic handoff and communication a production system.",
      "Identify Georgina Hayns as puppet fabrication supervisor and distinguish her role from animation supervision.",
      "Explain why most human characters used mechanical facial systems.",
      "Explain why Pinocchio required a different replacement-face approach to preserve visible wood grain.",
      "Explain the difference between a mechanical face and replacement-face animation without treating either as inherently superior.",
      "Use the metal 3D-printed armature as evidence of additive manufacturing inside an artisanal pipeline.",
      "Explain why more than 100 armature components/hinges creates precision and finishing requirements rather than eliminating craft labor.",
      "Explain the puppet hospital as an active maintenance and shot-adaptation department.",
      "Explain why joint tension and range could be customized to individual shots and animators.",
      "Treat 'perfectly imperfect' as controlled production design rather than accidental roughness.",
      "Explain why every stop-motion set surface, prop and costume requires an explicit fabrication decision.",
      "Identify Frank Passingham as director of photography.",
      "Identify Canon 5D Mark IV as the documented camera body.",
      "Identify Nikon, Zeiss and LAOWA as documented lens families without inventing a lens-per-shot ledger.",
      "Explain the role of LAOWA macro options in miniature close photography without generalizing them to every setup.",
      "Explain Passingham's four lighting/camera teams as a parallel-unit cinematography structure.",
      "Explain the documented tungsten direct/key and LED bounce/indirect lighting policy.",
      "Explain layered lighting as repeated exposure passes around one stop-motion performance.",
      "Explain how underwater and direct-sun passes could be combined around one animation take.",
      "Explain how torch and moonlight passes could be separated for post-production control.",
      "Explain why motion control must remain synchronized with repeated light/exposure passes.",
      "Explain why motion-control rigs and physical camera track constrain storyboarded camera movement.",
      "Explain why animators need early involvement in motion-control blocking.",
      "Explain the use of green screen for skies and printed backgrounds where useful.",
      "Reject the claim that the finished images were entirely in-camera with no digital compositing.",
      "Reject the opposite claim that the stop-motion photography was merely a source layer for a primarily CG film.",
      "Identify Ken Schretzmann and Holly Klein as editors.",
      "Explain the Avid project as a production map spanning storyboard, camera test, animator reference, rehearsal, final animation and VFX.",
      "Explain why editorial can re-time a camera move only within physical track constraints.",
      "Explain live-action animator reference as performance planning rather than final photographed acting.",
      "Explain why 40 to 60 stages active at once create non-linear editorial tracking demands.",
      "Explain how pandemic shutdown moved editorial home in March 2020.",
      "Explain remote review as a Chapter 19 production-continuity system rather than a purely creative preference.",
      "Explain why physical stop-motion stages could not become fully remote even when editorial did.",
      "Identify Scott Martin Gershin as supervising sound designer.",
      "Explain Pinocchio's sonic identity as a selective construction from wood, metal, rubber and creak recordings.",
      "Explain why character sound changes with emotional state rather than mechanically sonifying every puppet movement.",
      "Explain the mono opening as a deliberate puppet-theater spatial strategy.",
      "Explain the gradual expansion toward full Atmos as part of Pinocchio's emotional growth.",
      "Explain selective spatial treatment of Wood Sprite and Death voices.",
      "Explain Gershin's restrained sound philosophy as narrative prioritization rather than lack of detail.",
      "Identify Alexandre Desplat as composer.",
      "Explain the score's material palette of guitars, mandolin, piano, harp, strings and woodwinds with no brass or cymbals.",
      "Explain why the score's material logic mirrors the handcrafted puppet world without literally imitating puppet noises.",
      "Explain the distinction between a film with musical moments and an uninterrupted conventional musical format.",
      "Keep audited budget, financing waterfall and recoupment explicitly unresolved.",
      "Keep the complete reconciled puppet census and all armature revisions unresolved.",
      "Keep exact set counts by geography and complete stage-utilization logs unresolved.",
      "Keep complete camera serial, lens-per-shot, Dragonframe/version and motion-control ledgers unresolved.",
      "Keep every lighting exposure/pass and full VFX shot/vendor ledger unresolved.",
      "Keep complete color-management and DI settings unresolved.",
      "Keep complete editorial revision, dialogue, ADR, Foley, Atmos stem/master and score-session ledgers unresolved.",
      "Close the case only when award priority, runtime provenance, fabrication, animation scale, cinematography, editorial, pandemic workflow, sound and music evidence agree."
    ],
    phases: [
      { id: "award_priority", label: "Lock the Oscar priority", player_task: "Use the 2023 Animated Feature Film win to prioritize the case without treating the award as craft proof." },
      { id: "runtime_boundary", label: "Freeze runtime provenance", player_task: "Use BBFC's 116m36s cinema version and preserve later runtime variants." },
      { id: "development_boundary", label: "Separate development from capture", player_task: "Keep the long pre-production/prototyping history separate from the 940-day photography record." },
      { id: "capture_calendar", label: "Build the capture calendar", player_task: "Plan around the documented 2019-2022 stop-motion photography period and 940 capture days." },
      { id: "parallel_units", label: "Scale concurrent units", player_task: "Coordinate more than 60 shooting/preparation units without treating them as identical stages." },
      { id: "animator_capacity", label: "Scale animator capacity", player_task: "Model the peak 41-animator/60-set system as a concurrency constraint." },
      { id: "puppet_census", label: "Preserve puppet census variance", player_task: "Keep the 30-versus-32 Pinocchio source variance visible while using duplicate puppets as scheduling infrastructure." },
      { id: "distributed_fabrication", label: "Coordinate three puppet regions", player_task: "Route fabrication work among Portland, Manchester and Guadalajara with explicit handoff boundaries." },
      { id: "mechanical_faces", label: "Build mechanical human faces", player_task: "Give animators direct facial control where mechanical systems are documented." },
      { id: "pinocchio_face_system", label: "Protect Pinocchio's wood grain", player_task: "Use the documented replacement-face strategy rather than a flexible mechanical skin that would break grain continuity." },
      { id: "metal_armature", label: "Engineer the metal armature", player_task: "Use additive manufacturing for the documented high-part-count articulated skeleton without erasing finishing labor." },
      { id: "puppet_hospital", label: "Operate the puppet hospital", player_task: "Repair and retune puppet joints, tension and range throughout production." },
      { id: "perfectly_imperfect", label: "Design controlled imperfection", player_task: "Age and texture sets, costumes and props so handmade materiality remains visible but intentional." },
      { id: "camera_package", label: "Lock the miniature camera package", player_task: "Use Canon 5D Mark IV bodies and documented Nikon, Zeiss and LAOWA lens families without inventing per-shot metadata." },
      { id: "lighting_policy", label: "Split key and bounce technology", player_task: "Use tungsten for direct/key light and LED for bounce/indirect systems where documented." },
      { id: "layered_lighting", label: "Build layered lighting passes", player_task: "Repeat synchronized exposure passes around the same animation for controllable naturalistic and stylized light." },
      { id: "motion_control", label: "Synchronize motion control", player_task: "Keep camera motion repeatable across animation and light passes while respecting physical rig access." },
      { id: "water_passes", label: "Separate underwater and sun passes", player_task: "Capture distinct lighting states that VFX can combine after animation." },
      { id: "torch_passes", label: "Separate torch and moonlight", player_task: "Use practical miniature light plus repeated exposures without losing puppet-light interaction." },
      { id: "background_strategy", label: "Choose green or printed backgrounds", player_task: "Use green screen or printed backgrounds according to shot needs and VFX economy." },
      { id: "storyboard_to_camera", label: "Translate boards into stage geometry", player_task: "Test angles and camera motion against the physical warehouse, track and puppet-access limits." },
      { id: "live_action_reference", label: "Record animator performance reference", player_task: "Use animator live-action videos as acting/planning input rather than final performance footage." },
      { id: "avid_map", label: "Maintain the Avid production map", player_task: "Collage storyboard, still, camera move, reference, rehearsal, final animation and VFX states in one evolving editorial system." },
      { id: "camera_retime", label: "Negotiate editorial camera timing", player_task: "Re-time camera moves only after checking that the physical motion-control track can support the new duration." },
      { id: "pandemic_remote_edit", label: "Move editorial home", player_task: "Continue Avid editorial and review remotely while physical stages adopt restricted access." },
      { id: "sound_materials", label: "Build Pinocchio's material voice", player_task: "Shape wood, creak, rubber and metal recordings into a character-specific sonic identity." },
      { id: "mono_to_atmos", label: "Expand the spatial sound arc", player_task: "Begin with puppet-theater-like mono and grow toward full Atmos as the story broadens." },
      { id: "voice_spatialization", label: "Spatialize supernatural voices selectively", player_task: "Use targeted delays and room placement for Wood Sprite and Death without treating every word identically." },
      { id: "score_materiality", label: "Score the handcrafted world", player_task: "Use Desplat's documented material palette and avoid unsupported instrumentation claims." },
      { id: "uncertainty_register", label: "Freeze unsupported ledgers", player_task: "Keep finance, complete puppet/set/camera/VFX/editorial/sound/music and release accounting explicitly unresolved." },
      { id: "production_verification", label: "Close the Pinocchio production audit", player_task: "Verify runtime, capture scale, fabrication, camera/light, editorial, pandemic workflow, sound, music and unresolved boundaries before canonical promotion." }
    ]
  }
] as const;

export function mergeChapterNineteenGuillermoDelTorosPinocchioExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterNineteenGuillermoDelTorosPinocchioExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_nineteen_guillermo_del_toros_pinocchio_verified",
      source: { list_id: "manual_chapter_nineteen_guillermo_del_toros_pinocchio_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
