import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterNineteenSinnersExpansionDefinitions = [
  {
    id: "scenario_sinners_2025",
    title: "Sinners",
    originalTitle: "Sinners",
    aliases: ["Sinners"],
    year: 2025,
    titleType: "Movie",
    runtimeMins: 138,
    directors: ["Ryan Coogler"],
    genres: ["Drama", "Horror", "Music"],
    sourceId: "kodak_sinners_65mm_imax_2025",
    sourceUrl: "https://www.kodak.com/en/motion/blog-post/sinners/",
    scenarioType: "award_priority_oscar_actor_cinematography_score_original_screenplay_bafta_original_screenplay_supporting_actress_score_ryan_coogler_autumn_durald_arkapaw_hannah_beachler_ruth_e_carter_michael_p_shawver_ludwig_goransson_chris_welcker_michael_ralla_66_shoot_days_louisiana_second_line_studios_ultra_panavision_70_imax_15_perf_65mm_system_65_ultra_panatar_vision3_500t_5219_ektachrome_100d_5294_twinning_technodolly_halo_rig_1000_vfx_shots_live_music_2025",
    premise: "Build Sinners as Chapter 19's next award-priority production case because the Academy records 2026 Oscar wins for Michael B. Jordan, Autumn Durald Arkapaw, Ludwig Göransson and Ryan Coogler in Leading Actor, Cinematography, Original Score and Original Screenplay, while BAFTA records wins for Original Screenplay, Supporting Actress and Original Score. Awards establish priority and reception, not production workflow. BBFC records the UK cinema version at 137 minutes 33 seconds, so the playable record rounds to 138 minutes without claiming every theatrical, premium-format, streaming or physical-media master is frame-identical. Kodak's direct cinematography account records 66 shooting days between April and July 2024 across southeastern Louisiana, with interiors on constructed sets at Second Line Studios in New Orleans and physical locations including Donaldsonville, Thibodaux, Bogalusa and Braithwaite, where the lumber-mill/juke-joint exterior was built on an unused golf course. The visual strategy changed materially during prep: the project began as a proposed 16mm production, moved to 35mm after VFX concerns about negative stability for the Smoke/Stack twinning work, and then expanded to large-format after 65mm/70mm tests. Durald Arkapaw and Panavision document 5-perf 65mm Ultra Panavision 70 and 15-perf IMAX as complementary capture systems rather than interchangeable labels. The documented camera package includes Panavision System 65 Studio and System 65 High Speed bodies plus IMAX MSM 9802 and IMAX MKIV cameras. Panavision customized Ultra Panatar 1.3x anamorphic lenses; IMAX work used modified 50mm and 80mm optics plus a bespoke 80mm IMAX Petzval lens. Ground-glass guides simultaneously protected 1.43:1 and 1.90:1 IMAX plus 2.76:1 and 2.39:1 widescreen compositions, making framing/version planning an on-set production problem. Kodak records KODAK VISION3 500T Color Negative Film 5219 as the principal stock across the 65mm systems. A specially manufactured 65mm batch of KODAK EKTACHROME 100D 5294 was used for a bounded flashback passage; test-shoot use of 250D and bleach-bypass/pull tests at FotoKem does not make those tests principal-photography stocks. The heavy System 65 and IMAX bodies were used on cranes, Steadicam, chase-car and Technodolly configurations. IMAX magazines and mechanical camera noise imposed duration, reloading and production-sound constraints, including planned sound-only takes and ADR/noise-reduction strategies for dialogue-heavy material. Kodak records night-lighting targets around 2300K for warm interiors and 4700K for moonlight, with large practical/stage and exterior rigs including Jem Balls, bounced ARRI T-12s, SkyPanel spacelights, Vortex softboxes and balloon sources; these are documented examples rather than a complete fixture ledger. Hannah Beachler states that the principal period structures were built from scratch on Louisiana locations and ties Annie's, the church, saw mill and juke joint to research in Eudora Welty, FSA/Library of Congress imagery, Clarksdale oral-history work, color systems and exaggerated silhouettes. The juke-joint exterior and interior were therefore a production-design/lighting/VFX coordination problem, not one monolithic practical set. Ruth E. Carter documents period workwear, hand-me-down logic, sweat, wear, texture, red-white-blue color systems and movement as costume storytelling, with special requirements for the multigenerational music montage. Michael B. Jordan's dual performance as Smoke and Stack required an integrated capture/playback/VFX system. Production sound mixer Chris Welcker describes first-pass performance with a physical double, rapid costume/makeup conversion, Pro Tools playback with removed dialogue and ADR-style cue beeps for timing and prop handoffs, while Kodak's VFX account documents Technodolly repeatable split-screen work and the purpose-built Halo Rig for more complex twin interaction. The VFX record therefore keeps in-camera blocking, repeatable motion, performance capture, compositing and post cleanup as separate layers. Kodak's 2026 VFX account records more than 1,000 VFX shots and vendors including Storm Studios, Rising Sun Pictures, Industrial Light & Magic Vancouver, Base FX, Light VFX, Outpost VFX, TFX and Baraboom Los Angeles. It also documents film-grain/lens-aberration matching, digital set extensions, twinning, the stitched IMAX music montage and selected fully digital environment/sunrise work. That scale does not erase practical design, stunts, makeup or the physical roof burn; VFX is treated as a supporting system whose task was to preserve photographed craft and extend it. The surreal juke-joint music sequence was planned across cinematography, previs, choreography, music, extras and VFX. Durald Arkapaw describes floor-plan camera-path design, previs with lens information and an interior 15-perf IMAX Steadicam passage assembled from three shots. Göransson describes moving to New Orleans for three months, rehearsing the sequence across departments for weeks, timing live music to camera movement and building the score from blues lineage rather than temporary score tracks. Miles Caton's guitar/vocal performance is documented as live in key material after three months of slide-guitar preparation. Chris Welcker's production-sound account similarly treats acoustic performance, hidden microphones, twin playback and IMAX noise as production design problems for sound rather than post-only cleanup. Editor Michael P. Shawver's direct Art of the Cut account supports structural intercutting and scene-order decisions, while Kodak documents that format transitions had to retain compatible headroom and editorial continuity across 1.43, 1.90, 2.76 and 2.39 framings. The locked case therefore treats editorial as both dramatic structure and multi-format image-management. Makeup/prosthetic and VFX collaboration extended to vampire transformations: later direct craft interviews document practical stages, specialty eye work, lighting tests and digital extension rather than assigning every supernatural element to one department. The historical lesson is not simply that Sinners was shot in IMAX or that it used many VFX shots. It is that an original studio-backed feature combined a 66-day Louisiana physical production, constructed period environments, two large-format photochemical systems, one principal negative stock plus a bounded reversal-stock experiment, repeatable-motion and performance systems for a dual role, live and preplanned music, location sound, practical makeup/stunts and a distributed thousand-shot VFX pipeline while protecting multiple premium-format compositions. The locked evidence does not establish a complete financing/ownership/recoupment waterfall, final production cost to the dollar, complete 66-day call-sheet and weather ledger, all crew/payroll data, every camera serial/magazine/lens-per-shot/stock-load, full lab/dailies/scan/DI/color-management chain, every lighting fixture and exposure, every twin take/plate/Halo capture, complete VFX shot/vendor task list, full edit revision history, all production sound/ADR/Foley/noise-reduction/mix stems, full score/song session and rights ledgers, or every IMAX/70mm/DCP/HDR/SDR/streaming/territory delivery. Those remain explicit unresolved boundaries.",
    requiredChoicesSeed: {
      screenplay: ["award_priority_not_workflow_evidence", "bbfc_137m33_runtime", "66_day_louisiana_schedule", "original_feature_boundary", "finance_waterfall_unresolved"],
      camera: ["5_perf_65mm_ultra_panavision", "15_perf_imax_65mm", "system_65_and_imax_bodies", "ultra_panatar_and_imax_optics", "vision3_500t_5219", "bounded_ektachrome_5294", "four_aspect_ratio_guides", "full_camera_stock_ledger_unresolved"],
      editing: ["multi_format_headroom_continuity", "technodolly_split_screen", "halo_rig_twinning", "three_shot_imax_montage", "structural_intercutting", "full_edit_vfx_di_ledgers_unresolved"],
      sound: ["imax_camera_noise_boundary", "sound_only_takes", "twin_pro_tools_playback", "live_acoustic_music", "guitar_score_lineage", "full_adr_mix_music_ledgers_unresolved"],
      themes: ["film_history", "2025", "sinners", "large_format", "imax", "ultra_panavision", "original_studio_feature", "chapter19"]
    },
    learningGoals: [
      "Explain why the 2026 Oscar and BAFTA wins justify award-priority selection without proving production workflow.",
      "Identify Ryan Coogler as writer-director and separate award evidence from direct craft evidence.",
      "Use BBFC's 137m33s cinema version to round the playable runtime to 138 minutes.",
      "Avoid claiming every premium-format, streaming and physical-media version is frame-identical.",
      "Identify Kodak's 66 shooting days between April and July 2024 as the locked production-schedule anchor.",
      "Map principal photography to southeastern Louisiana rather than fictional Mississippi geography.",
      "Identify Second Line Studios as the documented interior-stage base in New Orleans.",
      "Identify Donaldsonville, Thibodaux, Bogalusa and Braithwaite as documented Louisiana production locations.",
      "Explain why the juke-joint exterior build on an unused golf course is a physical-production fact, not a story-location claim.",
      "Explain the format evolution from proposed 16mm to 35mm to large-format 65mm.",
      "Connect the move away from 16mm to negative-stability concerns for VFX twinning without claiming 35mm was the final principal format.",
      "Identify 5-perf 65mm Ultra Panavision 70 as one principal large-format capture system.",
      "Identify 15-perf IMAX 65mm as the complementary tall-frame capture system.",
      "Distinguish Ultra Panavision's 2.76:1 widescreen language from IMAX 1.43:1 capture.",
      "Identify Panavision System 65 Studio and System 65 High Speed cameras.",
      "Identify IMAX MSM 9802 and MKIV cameras in the documented package.",
      "Identify customized Ultra Panatar 1.3x anamorphics as the 5-perf 65mm optics.",
      "Identify the documented 50mm/80mm IMAX optics and bespoke 80mm IMAX Petzval lens.",
      "Explain why four ground-glass framing guides made downstream version compatibility an on-set concern.",
      "Identify 1.43:1, 1.90:1, 2.76:1 and 2.39:1 as the protected composition guides.",
      "Identify KODAK VISION3 500T 5219 as the principal negative stock.",
      "Keep KODAK EKTACHROME 100D 5294 bounded to the documented flashback material.",
      "Reject the inference that 250D test footage or bleach-bypass tests became principal-photography standards.",
      "Explain the operational consequences of 100-pound System 65 cameras and roughly 65-pound IMAX bodies.",
      "Explain how cranes, Steadicam, chase-car and Technodolly support changed camera movement without changing the capture format.",
      "Explain why IMAX magazine duration and reload time constrain performance and scheduling.",
      "Explain why IMAX camera noise created production-sound and ADR planning obligations.",
      "Identify 2300K interior and 4700K moonlight targets as documented lighting examples rather than universal scene settings.",
      "Explain how stage and exterior lighting rigs supported continuity between juke-joint interior and exterior spaces.",
      "Identify Hannah Beachler as production designer.",
      "Explain Beachler's structures as scratch-built Louisiana sets informed by Mississippi research.",
      "Connect Eudora Welty, FSA and Library of Congress imagery to production-design research without treating reference photos as literal blueprints.",
      "Explain how Clarksdale oral-history research informed place texture while photography remained in Louisiana.",
      "Explain color and silhouette systems as cross-department visual organization.",
      "Identify Ruth E. Carter as costume designer.",
      "Explain workwear, hand-me-downs, sweat, aging and texture as period/social evidence in costume design.",
      "Explain why large-format photography increased the visibility of costume texture and continuity demands.",
      "Describe the dual-role first-pass/second-pass performance workflow for Smoke and Stack.",
      "Explain Chris Welcker's Pro Tools playback and cue-beep method for twin dialogue and prop handoffs.",
      "Identify Technodolly repeatability as one twinning strategy.",
      "Identify the purpose-built Halo Rig as a separate strategy for more complex twin interaction.",
      "Explain why twinning combines performance, camera repeatability, wardrobe/makeup, sound playback and VFX rather than belonging to VFX alone.",
      "Use Kodak's more-than-1,000-VFX-shot figure as a scale anchor rather than a complete shot ledger.",
      "Name the documented distributed VFX vendors without inferring each vendor's exact complete shot allocation.",
      "Explain why film grain, weave, lens falloff and aberrations had to be recreated in digital compositing.",
      "Explain digital set extension as preservation/extension of Beachler's production design rather than replacement of it.",
      "Explain how practical roof burning and later digital continuation can coexist in one effects beat.",
      "Explain the sunrise/bayou work as an example of real-world reference feeding digital environment work.",
      "Map the juke-joint music sequence across floor-plan blocking, previs, choreography, live performance, Steadicam and VFX stitching.",
      "Identify the interior music passage as 15-perf IMAX Steadicam assembled from three shots rather than one literal uninterrupted magazine.",
      "Explain why IMAX magazine limits required planned stitch points in the apparent oner.",
      "Identify Ludwig Göransson as composer and music-production collaborator.",
      "Explain the blues-to-metal lineage as a score concept rather than a generic period-music cue sheet.",
      "Explain Göransson's three-month New Orleans presence and cross-department rehearsals as production integration.",
      "Identify Miles Caton's documented live guitar/vocal work and three months of slide-guitar preparation.",
      "Explain why live acoustic performance created simultaneous camera, sound, choreography and music constraints.",
      "Identify Michael P. Shawver as editor and separate structural cutting from capture-format management.",
      "Explain why editorial had to protect headroom and continuity across multiple aspect-ratio deliverables.",
      "Keep the full lab, scan, DI and color-management pipeline unresolved unless directly sourced.",
      "Keep the exact final production cost, financing terms, ownership and recoupment waterfall unresolved.",
      "Keep the complete call-sheet, weather, crew, payroll, camera, lens, stock-load and lighting ledgers unresolved.",
      "Keep every twin plate, Halo capture, VFX shot/vendor task and compositing revision unresolved.",
      "Keep every production-sound track, ADR line, Foley cue, restoration process and final mix stem unresolved.",
      "Keep complete score/song sessions, musician lists, cue sheets, synchronization/master rights and soundtrack accounting unresolved.",
      "Keep every IMAX, 70mm, DCP, HDR, SDR, streaming and territory-specific delivery master unresolved.",
      "Close the case only when awards, runtime, schedule, Louisiana physical production, large-format capture, design, costume, twinning, VFX, sound, music, editorial and unresolved boundaries agree."
    ],
    phases: [
      { id: "award_priority", label: "Lock the award priority", player_task: "Use Oscar and BAFTA results to prioritize Sinners without treating awards as workflow evidence." },
      { id: "runtime_boundary", label: "Freeze the cinema runtime", player_task: "Use BBFC's 137m33s cinema record and round the playable value to 138 minutes." },
      { id: "schedule_boundary", label: "Lock the 66-day shoot", player_task: "Anchor production to Kodak's April-July 2024 Louisiana schedule." },
      { id: "location_map", label: "Map the Louisiana production", player_task: "Separate New Orleans stage work and southeastern Louisiana locations from fictional Mississippi geography." },
      { id: "format_evolution", label: "Track the format pivot", player_task: "Preserve the 16mm-to-35mm-to-65mm decision path during preparation." },
      { id: "large_format_split", label: "Separate the two large formats", player_task: "Use 5-perf Ultra Panavision and 15-perf IMAX for distinct image languages." },
      { id: "camera_package", label: "Build the camera package", player_task: "Use the documented System 65 and IMAX bodies without inventing serials." },
      { id: "lens_package", label: "Build the lens package", player_task: "Use Ultra Panatars and documented IMAX/Petzval optics while leaving lens-per-shot metadata unresolved." },
      { id: "aspect_guides", label: "Protect four framing guides", player_task: "Compose for 1.43, 1.90, 2.76 and 2.39 downstream needs." },
      { id: "stock_policy", label: "Lock the stock policy", player_task: "Use 500T 5219 as principal stock and bound 65mm EKTACHROME 5294 to its documented passage." },
      { id: "camera_mobility", label: "Move heavy cameras", player_task: "Plan cranes, Steadicam, chase-car and Technodolly around large-format physical constraints." },
      { id: "imax_magazine", label: "Plan IMAX magazines", player_task: "Account for short magazine duration and reload cost in performance planning." },
      { id: "imax_sound", label: "Plan around IMAX noise", player_task: "Use sound-only takes, restoration and ADR where needed without assuming all dialogue was replaced." },
      { id: "lighting_policy", label: "Build day/night lighting", player_task: "Use the documented warm-interior and moonlight targets as scene systems, not universal settings." },
      { id: "design_research", label: "Research the Delta world", player_task: "Translate photographic archives and oral history into coherent period structures." },
      { id: "physical_sets", label: "Build the period structures", player_task: "Coordinate scratch-built location sets, stage interiors and exterior environments." },
      { id: "costume_texture", label: "Age the costume world", player_task: "Use workwear, hand-me-down logic, sweat, wear and movement as period storytelling." },
      { id: "twin_first_pass", label: "Capture the dominant twin", player_task: "Record the first performance against a physical double with timing and interaction preserved." },
      { id: "twin_playback", label: "Prepare twin playback", player_task: "Remove double dialogue in Pro Tools and add timing cues for the returning performance." },
      { id: "twin_repeat_motion", label: "Repeat the camera move", player_task: "Use Technodolly split-screen capture where repeatable camera motion can sell the twins." },
      { id: "twin_halo", label: "Capture complex twin interaction", player_task: "Use the Halo Rig where split-screen alone cannot preserve the required interaction." },
      { id: "vfx_film_match", label: "Match digital work to film", player_task: "Preserve grain, weave, lens behavior and photographed craft in compositing." },
      { id: "vfx_distribution", label: "Coordinate distributed VFX", player_task: "Manage the thousand-shot scale across documented vendors without inventing shot allocations." },
      { id: "music_previs", label: "Previsualize the music sequence", player_task: "Join camera path, lens choices, choreography, performers and musical timing before photography." },
      { id: "music_live", label: "Capture live music", player_task: "Protect acoustic performance and reaction timing while maintaining camera and sound requirements." },
      { id: "imax_montage", label: "Build the apparent oner", player_task: "Use planned IMAX Steadicam segments and stitch points rather than claiming one uninterrupted magazine." },
      { id: "production_sound", label: "Capture performance sound", player_task: "Balance hidden microphones, live instruments, twin playback and noisy film cameras." },
      { id: "score_lineage", label: "Build the score language", player_task: "Use Göransson's blues lineage and custom-created music world rather than temp-score imitation." },
      { id: "editorial_structure", label: "Shape the dramatic structure", player_task: "Use Shawver's structural cutting while preserving multi-format image logic." },
      { id: "delivery_boundary", label: "Freeze unsupported masters", player_task: "Keep complete IMAX/70mm/DCP/HDR/SDR/streaming and territory ledgers unresolved." },
      { id: "uncertainty_register", label: "Freeze unsupported ledgers", player_task: "Keep finance, daily reports, camera/lab, VFX, edit, sound, music and delivery accounting explicitly unresolved." },
      { id: "production_verification", label: "Close the Sinners production audit", player_task: "Verify runtime, 66-day Louisiana schedule, large-format package, stock boundary, design, costume, twinning, VFX, sound, music, editorial and unresolved ledgers before canonical promotion." }
    ]
  }
] as const;

export function mergeChapterNineteenSinnersExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterNineteenSinnersExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_nineteen_sinners_verified",
      source: { list_id: "manual_chapter_nineteen_sinners_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}