import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterEightFrenchAvantGardeExpansionDefinitions = [
  {
    id: "scenario_coeur_fidele_1923",
    title: "Cœur fidèle",
    originalTitle: "Cœur fidèle",
    aliases: ["Coeur fidèle", "Coeur fidele", "Faithful Heart"],
    year: 1923,
    titleType: "Feature",
    runtimeMins: 84,
    directors: ["Jean Epstein"],
    genres: ["Drama", "Romance"],
    premise: "Build Cœur fidèle as a 1923 Pathé Consortium Cinéma production problem in French Impressionist perception rather than as a generic tragic-romance plot. Jean and Marie Epstein shape the screenplay, Jean Epstein directs, Paul Guichard leads cinematography with camera operators Léon Donnot and Henri Stuckert, and Gina Manès, Léon Mathot and Edmond Van Daële carry a Marseille dockside melodrama whose emotional pressure is transformed through subjective framing, superimposition and rhythmic editing. Treat the celebrated fairground sequence as an integrated camera-and-editing system that contrasts Marie's isolation with mechanical rotation and public festivity, not as a checklist of flashy effects. Use photogénie as historically contested Epstein-era theory about cinema's transformation of faces, objects, movement and duration, never as a measurable gameplay score or a claim that this film invented subjective camera or rapid montage. Preserve the distinction between the 1923 silent production and modern restored 84-minute DCP/35 mm presentations with contemporary accompaniment.",
    sourceId: "manual_coeur_fidele_1923",
    sourceUrl: "https://www.cinematheque.fr/film/48086.html",
    scenarioType: "impressionist_subjective_rhythm_production",
    requiredChoicesSeed: {
      screenplay: ["epstein_marie_dockside_melodrama", "simple_tragedy_over_plot_complexity", "emotion_through_visual_relation"],
      camera: ["subjective_maritime_closeups", "fairground_motion_fragments", "faces_objects_and_environment_as_perception"],
      editing: ["rhythmic_fairground_montage", "superimposition_and_association", "emotional_duration_over_continuity_display"],
      sound: ["silent_1923_production", "exhibition_accompaniment_not_synchronized_dialogue", "modern_restoration_music_not_original_soundtrack"],
      themes: ["film_history", "french_impressionism", "jean_epstein", "pathe_consortium", "photogenie_context", "subjective_cinema"],
    },
    learningGoals: [
      "Plan a simple melodramatic situation whose emotional force comes from the relation among faces, objects, harbor space, camera position and editing rather than from adding plot complications.",
      "Coordinate subjective framing, close views, superimposition and rhythmic cutting so technique changes how Marie's isolation and pressure are experienced instead of functioning as detachable avant-garde decoration.",
      "Reconstruct the fairground passage as a production system: performance, rotating attractions, camera fragments, motion, repeated details and cut rhythm must reinforce one emotional contradiction between public festivity and private distress.",
      "Keep authorship collaborative by preserving Marie Epstein's documented screenplay role, Paul Guichard's cinematography and Donnot/Stuckert's camera work alongside Jean Epstein's direction and theory.",
      "Use photogénie as a historically specific and debated theoretical lens for cinema's transformation of things and duration, not as a universal style preset, numerical score or invention claim.",
      "Preserve object history: the photographed 1923 silent feature and today's restored 84-minute presentations, projection speeds and musical accompaniments are related but not identical historical objects.",
    ],
    phases: [
      { id: "pitch", label: "Perception-led melodrama pitch", player_task: "Define why a deliberately simple dockside love-and-coercion story can justify formal experimentation only when each technique intensifies a character relation or state of perception." },
      { id: "research", label: "Pathé and Epstein evidence", player_task: "Ground Jean and Marie Epstein, Pathé Consortium Cinéma, Guichard, Donnot, Stuckert, the principal cast, silent format and restoration history in institutional sources before assigning craft claims." },
      { id: "screenplay", label: "Simple tragedy, visual pressure", player_task: "Keep Marie, Jean and Petit Paul's causal conflict legible and sparse enough that images can carry emotional complexity without confusing formal density with narrative complexity." },
      { id: "casting", label: "Faces inside social pressure", player_task: "Direct Manès, Mathot and Van Daële through gaze, stillness, proximity and reaction so close views and montage have specific emotional material to transform." },
      { id: "production_design", label: "Harbor and fairground environments", player_task: "Use Marseille-associated dockside textures, bar space and fairground machinery as active visual materials while avoiding unsupported claims that every surviving exterior can be mapped to one documented street or set." },
      { id: "cinematography", label: "Subjective fragments and movement", player_task: "Coordinate Guichard and the camera operators around faces, objects, moving attractions and changing camera relations so perception becomes filmable without claiming a single lens or rig invented Impressionist cinema." },
      { id: "editing", label: "Rhythm as emotional structure", player_task: "Build the fairground and other associative passages from repeated motion, superimposition and variable shot duration so rhythm expresses pressure rather than merely demonstrating fast cutting." },
      { id: "sound", label: "Silent production, presentation-aware music", player_task: "Keep 1923 production silent and treat live or recorded accompaniment attached to later screenings and restorations as presentation history rather than synchronized original sound." },
      { id: "release", label: "Pathé circulation and critical afterlife", player_task: "Model commercial Pathé production/distribution alongside the film's later avant-garde canonization, keeping contemporary production facts separate from retrospective critical labels and restoration history." },
    ],
  },
  {
    id: "scenario_napoleon_1927",
    title: "Napoléon",
    originalTitle: "Napoléon vu par Abel Gance",
    aliases: ["Napoleon"],
    year: 1927,
    titleType: "Feature",
    runtimeMins: 425,
    directors: ["Abel Gance"],
    genres: ["Biography", "Drama", "History", "War"],
    premise: "Build Napoléon as Abel Gance's 1927 large-scale French production and exhibition experiment rather than as one immutable seven-hour director's cut. Société du Film Napoléon and Société Générale de Films organize Gance's direction and screenplay with cinematographers Jules Krüger, Jean-Paul Mundviller and Léonce-Henri Burel, editors Gance and Marguerite Beaugé, a large assistant-director and camera apparatus, extensive design and effects labor, and Albert Dieudonné's central performance. Coordinate body-mounted, track, vehicle, horse and pendulum-like camera solutions, rapid montage, split-screen and multiple-exposure strategies with crowds and location logistics, then treat the climactic three-screen Polyvision triptych as both a capture problem and an exhibition-infrastructure problem. Preserve version criticism as a core mechanic: the 7 April 1927 Opéra presentation, the much longer May Apollo version, MGM export recuts, Gance's 1934–1935 sound re-edit and modern reconstructions are different historical states. The representative 425-minute runtime stored here follows La Cinémathèque française's current two-part Grande Version reconstruction (220 + 205 minutes), not an assertion that one 425-minute object was the sole original 1927 release.",
    sourceId: "manual_napoleon_1927",
    sourceUrl: "https://www.cinematheque.fr/film/48685.html",
    scenarioType: "large_scale_experimental_polyvision_production",
    requiredChoicesSeed: {
      screenplay: ["gance_revolutionary_biographical_arc", "youth_to_italian_campaign_progression", "mass_history_and_personal_myth_coordination"],
      camera: ["multi_camera_mobile_rig_system", "snowball_storm_corsica_subjective_motion", "polyvision_three_camera_capture"],
      editing: ["accelerated_montage_and_multiple_images", "parallel_mass_personal_rhythm", "opera_apollo_mgm_version_control"],
      sound: ["silent_1927_release_states", "arthur_honegger_music_context", "1935_sound_reedit_and_modern_scores_separate"],
      themes: ["film_history", "french_avant_garde", "abel_gance", "polyvision", "large_scale_logistics", "version_criticism"],
    },
    learningGoals: [
      "Plan formal experimentation at epic scale by coordinating many cameras, operators, assistants, performers, extras, vehicles, sets and effects rather than treating Gance's visual ideas as solo improvisations detached from production logistics.",
      "Use mobile-camera devices only when their physical placement changes historical space or subjective experience: the snowball fight, storm, Corsican pursuit and crowd sequences require different rigs, safety assumptions and editorial consequences.",
      "Treat split screens, multiple exposures and accelerated montage as planned relations among capture, masking, exposure and editing, not as a generic 'avant-garde' button that automatically makes a scene modern.",
      "Build Polyvision as an exhibition system: three coordinated images require capture planning, editorial design, three projection channels and a venue capable of presenting the triptych, so the finale is not reducible to an extra-wide frame.",
      "Keep authorship collaborative by preserving the documented cinematographers, Marguerite Beaugé's editing, designers, effects coordinators, assistant directors and broad camera labor alongside Gance's unusually concentrated creative authority.",
      "Preserve the version tree: Opéra, Apollo, MGM/export, 1935 sound re-edit and modern reconstructions must remain separate evidence layers, and the current 425-minute Grande Version must never be mislabeled as the single untouched 1927 original.",
    ],
    phases: [
      { id: "pitch", label: "Epic experiment pitch", player_task: "Define why the early Napoleon story needs feature-scale historical logistics and aggressive camera/editing experimentation strongly enough to justify the cost and complexity." },
      { id: "research", label: "Credits, apparatus and version research", player_task: "Ground Gance, the production companies, Krüger/Mundviller/Burel, Beaugé, design/effects departments, camera apparatus, Polyvision and the 1927-to-restoration version tree in institutional evidence." },
      { id: "screenplay", label: "Biography through mass history", player_task: "Connect Brienne, revolutionary Paris, Corsica and the Italian campaign so personal myth, political crowds and military geography accumulate rather than becoming disconnected showcase sequences." },
      { id: "casting", label: "Napoleon inside crowds", player_task: "Keep Dieudonné's Napoleon and the ensemble readable through posture, reaction and recurring visual motifs even when mass staging and formal fragmentation dominate the frame." },
      { id: "production_design", label: "Historical worlds at changing scale", player_task: "Coordinate school, revolutionary assemblies, Corsican landscapes, military environments and triptych imagery with design departments while distinguishing documented credits from uncertain reconstruction of exact set plans." },
      { id: "cinematography", label: "Many cameras, many physical problems", player_task: "Assign rigs and operators according to shot function—track, body, vehicle, horse, suspended motion, conventional coverage or Polyvision—without pretending one camera trick solves every sequence." },
      { id: "editing", label: "Montage and version tree", player_task: "Use rapid rhythm, overlays, split images and parallel action to organize scale, while tracking Opéra, Apollo and MGM assemblies as historically distinct editorial states rather than one recoverable pristine cut." },
      { id: "sound", label: "Silent states and later sound layers", player_task: "Keep the 1927 film states silent, preserve Arthur Honegger's historical music context, and separate Gance's 1935 sound re-edit plus Carl Davis/Simon Cloquet-Lafollye-era restoration music from original synchronized production claims." },
      { id: "release", label: "Polyvision exhibition and reconstruction", player_task: "Model the practical difference between ordinary single-screen circulation and a triptych-capable presentation, then treat later recuts and restorations as changing access to the work rather than retroactive production facts." },
    ],
  },
  {
    id: "scenario_un_chien_andalou_1929",
    title: "Un Chien Andalou",
    originalTitle: "Un chien andalou",
    aliases: ["An Andalusian Dog"],
    year: 1929,
    titleType: "Short",
    runtimeMins: 17,
    directors: ["Luis Buñuel"],
    genres: ["Fantasy", "Horror", "Short"],
    premise: "Build Un Chien Andalou as the 1928–1929 Buñuel-Dalí small-scale Surrealist production and Paris exhibition problem rather than as a random-image generator. Luis Buñuel and Salvador Dalí write the scenario collaboratively; Buñuel directs, produces and edits; Pierre Braunberger is executive producer; Albert Duverger photographs; Pierre Schildknecht designs; and Studio-Films produces and originally distributes the work. Organize dream-derived association through concrete shot relations—montage, dissolves, superimpositions, slow motion, discontinuous transitions and parodic intertitles—without forcing a classical causal explanation onto the sequence. Treat the 6 June 1929 Studio des Ursulines presentation and later Surrealist canonization as reception history, not proof that every technique was unprecedented. The eye-cutting image, dead-animal imagery, sexual threat and other disturbing material remain historical evidence only: gameplay must never instruct the player to injure a person or animal, reproduce coercion, or score shock value; safe substitution and analysis are mandatory.",
    sourceId: "manual_un_chien_andalou_1929",
    sourceUrl: "https://www.cinematheque.fr/film/47197.html",
    scenarioType: "surrealist_discontinuous_association_production",
    requiredChoicesSeed: {
      screenplay: ["bunuel_dali_dream_derived_collaboration", "free_association_without_classical_explanation", "concrete_image_constraints_over_randomness"],
      camera: ["duverger_clear_image_capture", "ordinary_space_for_irrational_conjunction", "safe_substitution_for_harm_images"],
      editing: ["discontinuous_associative_montage", "dissolve_superimposition_slow_motion", "parodic_intertitle_time_disruption"],
      sound: ["silent_era_image_production", "preexisting_music_exhibition_context", "later_recorded_tracks_not_location_sound"],
      themes: ["film_history", "surrealism", "bunuel_dali", "alternative_financing", "alternative_exhibition", "representation_ethics"],
    },
    learningGoals: [
      "Plan a Surrealist short from concrete image associations and rejected rational links rather than equating non-classical structure with arbitrary shot order.",
      "Coordinate Buñuel and Dalí's documented screenplay collaboration with Duverger's photography, Schildknecht's design, Batcheff's assistant-direction work and Braunberger's production role instead of collapsing the film into a two-name legend.",
      "Use montage, dissolve, superimposition, slow motion and intertitle disruption to create associative pressure while keeping each photographed action operationally clear enough for the transition to register.",
      "Treat Studio-Films, small-scale financing and the Studio des Ursulines presentation as part of the production/exhibition system that allowed a short experimental work to circulate outside a normal feature model.",
      "Keep shocking historical images ethically bounded: never reproduce injury to a person or animal, never make coercion a performance objective, and use safe substitution, non-harmful effects or critical analysis instead.",
      "Separate production and afterlife: 1928-era filming, the June 1929 Paris presentation, Surrealist reception and later digital restoration/presentation states are related but distinct historical layers.",
    ],
    phases: [
      { id: "pitch", label: "Associative short-film pitch", player_task: "Define a short whose power comes from collision among specific images and desires rather than conventional plot explanation or random shock accumulation." },
      { id: "research", label: "Credits, Surrealism and safety research", player_task: "Ground Buñuel, Dalí, Studio-Films, Braunberger, Duverger, Schildknecht, Batcheff, the 1929 presentation, later restoration and the ethical status of disturbing images in institutional evidence." },
      { id: "screenplay", label: "Dream-derived constraints", player_task: "Build an ordered chain of images from the Buñuel-Dalí collaborative principle of rejecting rational explanation while still specifying concrete actions, transitions and recurring motifs." },
      { id: "casting", label: "Legible bodies in impossible relations", player_task: "Direct Mareuil, Batcheff and the ensemble so gesture and reaction remain precise even when time, identity and causality become unstable; coercion and injury are never actor tasks." },
      { id: "production_design", label: "Ordinary matter, irrational conjunction", player_task: "Use Schildknecht's design logic to keep rooms, props and clothing materially recognizable so montage can make their combinations strange without requiring unsafe spectacle." },
      { id: "cinematography", label: "Clear capture, safe effects", player_task: "Use Duverger's photography to make each constituent image readable, and replace any harmful historical act with safe props, compositing, off-screen implication or analysis rather than reenactment." },
      { id: "editing", label: "Discontinuity with internal discipline", player_task: "Join images through dissolve, superimposition, slow motion, temporal intertitles and abrupt cuts so free association remains perceptible as design rather than accidental sequencing." },
      { id: "sound", label: "Silent image, exhibition music", player_task: "Keep photographed production separate from music attached in exhibition or later presentations; pre-existing music is historical context, not evidence of synchronized location sound." },
      { id: "release", label: "Specialist venue and Surrealist reception", player_task: "Model the Studio des Ursulines presentation and later movement affiliation as alternative exhibition/reception history without pretending later canonical status was guaranteed during production." },
    ],
  },
  {
    id: "scenario_entr_acte_1924",
    title: "Entr'acte",
    originalTitle: "Entr'acte",
    aliases: ["Entr’acte"],
    year: 1924,
    titleType: "Short",
    runtimeMins: 23,
    directors: ["René Clair"],
    genres: ["Comedy", "Experimental", "Short"],
    premise: "Build Entr'acte as the 1924 Ballets Suédois commission made for Francis Picabia's Relâche rather than as an isolated anthology of random Dada images. Rolf de Maré commissions the film; René Clair directs, adapts and edits; Francis Picabia provides the scenario; Jimmy Berliet photographs; Erik Satie composes the original accompaniment; and performers including Jean Börlin, Inge Frïss, Marcel Duchamp, Man Ray, Picabia, Satie and de Maré connect the screen event to Parisian ballet and artist networks. Coordinate frame-by-frame/stop-motion work, accelerated and slowed motion, multiple exposure, unusual viewpoints, rapid cutting, inversion, disappearance and chase rhythm as concrete camera-and-editing procedures whose comic effect depends on timing and legibility. Preserve the historical inheritance from Méliès and Pathé-era trick/chase comedy instead of claiming Clair invented these devices. Treat the 4 December 1924 Théâtre des Champs-Élysées Relâche presentation as part of the production design, and preserve version criticism: Clair removed shots in 1967 when reshaping the work as an autonomous film, while the Fondation Jérôme Seydoux-Pathé restoration reinstated first-version material. The stored 23-minute runtime is a representative restoration value, not a claim that every 1924 or modern presentation has one identical duration.",
    sourceId: "manual_entr_acte_1924",
    sourceUrl: "https://www.fondation-jeromeseydoux-pathe.com/cms/restaurations",
    scenarioType: "dada_ballet_interval_trick_montage_production",
    requiredChoicesSeed: {
      screenplay: ["picabia_visual_argument", "relache_interval_function", "comic_incidents_over_classical_causality"],
      camera: ["berliet_multiple_exposure_and_viewpoint", "frame_by_frame_stop_motion", "accelerated_and_slowed_motion"],
      editing: ["clair_rapid_rhythmic_cutting", "chase_acceleration_and_reversal", "version_1924_1967_restoration_control"],
      sound: ["satie_original_accompaniment", "silent_image_production", "modern_recording_not_location_sound"],
      themes: ["film_history", "dada", "ballets_suedois", "relache", "cross_art_collaboration", "alternative_exhibition"],
    },
    learningGoals: [
      "Plan Entr'acte as a commissioned screen component of Relâche, so duration, rhythm, performers and musical accompaniment answer to a theatrical event rather than a conventional feature-release model.",
      "Coordinate Clair, Picabia, de Maré, Berliet and Satie as distinct production roles instead of collapsing Dada collaboration into a lone-director legend.",
      "Use frame-by-frame work, speed changes, multiple exposure, viewpoint and rapid cutting as planned procedures with readable inputs and comic timing rather than a one-click avant-garde effect.",
      "Preserve the trick-film and chase-comedy inheritance documented by Fondation Pathé: formal irreverence can reuse older cinema without falsely claiming every device as a 1924 invention.",
      "Make music an exhibition-time structural partner by coordinating Satie's original accompaniment with image rhythm while keeping silent image production distinct from later recorded playback.",
      "Track the version tree from the 1924 Relâche form through Clair's 1967 removals to the later restoration, and never treat the representative 23-minute restoration runtime as one immutable original duration.",
    ],
    phases: [
      { id: "pitch", label: "Interval-film commission", player_task: "Define what a film must do inside Relâche's theatrical interval and why provocation, laughter, speed and visual surprise serve that event better than a conventional self-contained plot." },
      { id: "research", label: "Ballet, credits and version research", player_task: "Ground de Maré, Ballets Suédois, Picabia, Clair, Berliet, Satie, the Théâtre des Champs-Élysées presentation, earlier trick-film inheritance and the 1967/restoration version tree in institutional evidence." },
      { id: "screenplay", label: "Visual argument, not random list", player_task: "Translate Picabia's scenario into a sequence of concrete incidents whose absurdity is designed through recurrence, escalation, inversion and collision rather than arbitrary shot accumulation." },
      { id: "casting", label: "Artists, dancers and comic bodies", player_task: "Coordinate Börlin, Frïss, Duchamp, Man Ray, Picabia, Satie, de Maré and the ensemble around precise poses, dance-derived movement and pursuit timing without turning physical identity into a score." },
      { id: "production_design", label: "Paris, props and event logic", player_task: "Use rooftops, streets, fairground imagery, the hearse, chess, cannon and everyday objects as clear visual materials whose collision can become absurd without inventing unsupported set-construction history." },
      { id: "cinematography", label: "Berliet's trick-image capture", player_task: "Plan ordinary viewpoints, low or inverted viewpoints, frame-by-frame capture, multiple exposure and speed-change material so each optical or temporal transformation has a reproducible production input." },
      { id: "editing", label: "Acceleration, chase and reversal", player_task: "Build rhythm from rapid cutting, increasing pursuit speed, repetition, disappearance and reversal while keeping the 1924, 1967 and restored assemblies historically distinct." },
      { id: "sound", label: "Satie as structural accompaniment", player_task: "Coordinate the silent image track with Satie's original accompaniment as part of the Relâche event, while treating modern recorded performances as later presentation states rather than synchronized production sound." },
      { id: "release", label: "Relâche event and restoration afterlife", player_task: "Model the 4 December 1924 theatrical presentation, later autonomous circulation and restoration as different exhibition states instead of assuming one stable release object from 1924 to the present." },
    ],
  },
  {
    id: "scenario_the_smiling_madame_beudet_1923",
    title: "The Smiling Madame Beudet",
    originalTitle: "La Souriante madame Beudet",
    aliases: ["The Smiling Mrs. Beudet"],
    year: 1923,
    titleType: "Short",
    runtimeMins: 36,
    directors: ["Germaine Dulac"],
    genres: ["Drama", "Short"],
    premise: "Build La Souriante madame Beudet as Germaine Dulac's 1923 Le Film d'Art - Vandal et Delac adaptation of the Denys Amiel-André Obey play, organized around Madame Beudet's constrained bourgeois daily life and subjective inner world rather than as a neutral filmed-stage comedy. Dulac directs and co-writes with André Obey; Charles Delac and Marcel Vandal produce; Maurice Forster and Paul Parguel photograph; Germaine Dermoz and Alexandre Arquillière carry the central marriage. Translate theatrical material into cinema through controlled performance, domestic spatial pressure, symbolic objects, fantasy, subjective emphasis and associative montage so the spectator can distinguish external routine from imagined freedom. Treat feminist interpretation as a historically grounded perspective rather than a simplistic empowerment score, and avoid claiming the film single-handedly invented feminist cinema or film Impressionism. The husband's recurring revolver joke and Madame Beudet's later intervention remain historical narrative evidence only: gameplay must never ask the player or performers to handle a functional firearm or recreate dangerous weapon behavior; use an inert prop or off-screen/non-operational substitute. Preserve copy history: La Cinémathèque française lists a 36-minute 35mm presentation while Fondation Jérôme Seydoux-Pathé lists a 38-minute 35mm Eye Filmmuseum copy, so the stored 36-minute runtime is representative rather than universal.",
    sourceId: "manual_the_smiling_madame_beudet_1923",
    sourceUrl: "https://www.cinematheque.fr/film/57083.html",
    scenarioType: "feminist_impressionist_subjective_marriage_adaptation",
    requiredChoicesSeed: {
      screenplay: ["dulac_obey_stage_to_screen_adaptation", "subjective_inner_life_structure", "domestic_routine_vs_imagined_freedom"],
      camera: ["forster_parguel_subjective_emphasis", "domestic_spatial_constraint", "safe_inert_weapon_substitution"],
      editing: ["associative_montage", "fantasy_reality_contrast", "symbolic_object_recurrence"],
      sound: ["silent_image_production", "variable_live_accompaniment", "no_canonical_synchronized_1923_score_claim"],
      themes: ["film_history", "french_impressionism", "germaine_dulac", "feminist_film_history", "subjectivity", "adaptation_ethics"],
    },
    learningGoals: [
      "Transform a stage-derived bourgeois-marriage drama into cinema by assigning subjective framing, fantasy, symbolic detail and associative montage to Madame Beudet's point of view rather than simply photographing dialogue and blocking.",
      "Coordinate Dulac and Obey's screenplay adaptation with Delac/Vandal production, Forster/Parguel photography and Dermoz/Arquillière performance as a collaborative system rather than a director-only legend.",
      "Use a constrained domestic interior as an active production problem: repetition, object placement, gesture and visual emphasis should make routine feel restrictive while fantasy passages open a contrasting subjective space.",
      "Treat the film's feminist historical importance critically and specifically—gendered marriage, autonomy, desire and authorship—without converting feminism into a player score or claiming one uncontested first.",
      "Keep the revolver motif ethically bounded: use only an inert or non-operational substitute, never require firearm handling or dangerous reenactment, and make the object function narratively through framing, reaction and editing.",
      "Preserve version and exhibition boundaries by distinguishing the 36-minute Cinémathèque presentation, the 38-minute Eye/Fondation Pathé copy and modern live accompaniment from one supposedly immutable 1923 object.",
    ],
    phases: [
      { id: "pitch", label: "Subjective adaptation pitch", player_task: "Define how the adaptation will make Madame Beudet's inner life—not merely the marriage plot—the organizing cinematic problem." },
      { id: "research", label: "Dulac, production and feminist-history research", player_task: "Ground the play adaptation, Film d'Art - Vandal et Delac, Delac/Vandal producing, Forster/Parguel photography, cast, impressionist context, feminist historiography and copy-runtime variation in institutional evidence." },
      { id: "screenplay", label: "From stage action to screen subjectivity", player_task: "Map routine domestic beats against fantasies, symbolic objects and subjective interruptions so the screenplay creates a visual argument instead of relying on theatrical dialogue." },
      { id: "casting", label: "Gesture under domestic pressure", player_task: "Direct Dermoz and Arquillière through contrasting gesture, timing and attention so the marriage's power imbalance is legible without reducing either performer to appearance-based scoring." },
      { id: "production_design", label: "The room as constraint", player_task: "Organize the piano, desk, doors and recurring objects so everyday geography reinforces confinement while remaining clear enough for fantasy and symbolic deviations to register." },
      { id: "cinematography", label: "Subjective emphasis and safe prop work", player_task: "Use Forster/Parguel's credited photographic role as the basis for controlled emphasis, contrast and fantasy transitions; any revolver image must use an inert or non-operational substitute with no dangerous handling task." },
      { id: "editing", label: "Associative inner-life montage", player_task: "Cut among routine action, imagined alternatives, symbolic inserts and reaction so subjective meaning accumulates through association rather than arbitrary discontinuity." },
      { id: "sound", label: "Silent production, variable accompaniment", player_task: "Keep the silent image production historically distinct from modern or venue-specific live accompaniment; do not invent one canonical synchronized 1923 soundtrack." },
      { id: "release", label: "Print, runtime and canon afterlife", player_task: "Model archival/presentation variation and later feminist/avant-garde canonization separately from original production, preserving the documented 36/38-minute copy boundary." },
    ],
  },
] as const;

export function mergeChapterEightFrenchAvantGardeExpansion(
  baseScenarios: readonly HistoricalFilmScenario[],
): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterEightFrenchAvantGardeExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) =>
      scenario.id === definition.id ||
      (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))),
    );
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_eight_french_avant_garde_verified",
      source: {
        list_id: "manual_chapter_eight_french_avant_garde_expansion_2026",
        position: nextPosition,
        imdb_id: definition.sourceId,
        url: definition.sourceUrl,
      },
      film: {
        title: definition.title,
        original_title: definition.originalTitle,
        year: definition.year,
        title_type: definition.titleType,
        runtime_mins: definition.runtimeMins,
        directors: definition.directors,
        genres: definition.genres,
        genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")),
        imdb_rating: 0,
        user_rating: 0,
      },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
