import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterNineteenTheBrutalistExpansionDefinitions = [
  {
    id: "scenario_the_brutalist_2024",
    title: "The Brutalist",
    originalTitle: "The Brutalist",
    aliases: ["The Brutalist"],
    year: 2024,
    titleType: "Movie",
    runtimeMins: 215,
    directors: ["Brady Corbet"],
    genres: ["Drama"],
    sourceId: "kodak_the_brutalist_vistavision_2024",
    sourceUrl: "https://www.kodak.com/en/motion/blog-post/the-brutalist/",
    scenarioType: "award_priority_venice_silver_lion_best_director_bafta_director_cinematography_score_actor_oscar_actor_cinematography_score_brady_corbet_mona_fastvold_lol_crawley_judy_becker_david_jancso_daniel_blumberg_szabolcs_gaspar_andy_neil_34_shoot_days_budapest_carrara_new_york_vistavision_8_perf_35mm_16mm_digibeta_70mm_release_leica_s_cooke_s4_zeiss_superspeed_vision3_250d_500t_push_processing_hungarian_filmlab_post_office_films_4k_6k_scan_variance_700tb_global_post_respeecher_hungarian_dialogue_hybrid_production_design_2024",
    premise: "Build The Brutalist as Chapter 19's next award-priority production case because La Biennale records Brady Corbet as the 2024 Silver Lion winner for Best Director, BAFTA records four wins including Director, Leading Actor, Cinematography and Original Score, and the Academy records Oscar wins for Adrien Brody, Lol Crawley and Daniel Blumberg. Awards establish priority and reception, not how the film was made. La Biennale records the competition version at 215 minutes and BBFC records the UK cinema version at 214 minutes 52 seconds, so the playable runtime is 215 minutes. Producer and filmmaker interviews repeatedly anchor production cost at about USD 10 million, but the complete financing waterfall, presale allocations, tax-credit structure, deferments, fees and recoupment remain unresolved. Kodak's direct production account records that photography had originally been planned for 2020 but was delayed by the pandemic and later cast/crew issues; after six weeks of cinematography prep, principal photography began around Budapest in March 2023, moved to Carrara in Italy, used a small New York unit for Manhattan/Riverside and the Statue of Liberty material, and wrapped in early May after 34 shooting days. The case therefore treats 34 days as the locked Kodak schedule anchor and does not turn secondary 33-day recollections into a false exact consensus. Lol Crawley documents that the vast majority of the feature was photographed in 8-perf horizontal 35mm VistaVision, chosen both for large architectural/quarry vistas and for intimate portraiture. The VistaVision camera and Leica-S lenses came from Camera Revolution and were rebuilt/prepared by Movietech. Standard 35mm support used ARRICAM ST/LT and ARRIFLEX 235 bodies with Cooke S4 optics; documentary-style material used ARRIFLEX 416 16mm with Zeiss Superspeeds; Digital Betacam supplied period television texture; and a specially modified ARRIFLEX 435 with a deliberately mistimed shutter created selected light-streak effects. Kodak VISION3 250D 5207/7207 and 500T 5219/7219 were the documented 35mm/16mm stocks. Crawley describes underexposure and push-processing, often one to one-and-a-half stops, to keep the high-resolution VistaVision negative from becoming too pristine and to support naturalistic low-light work. The production was designed around comparatively sparse coverage and blocking-led long takes rather than large numbers of angles. This reduced setup turnover while increasing the importance of rehearsal, camera path, performance timing and hidden lighting, especially in complex Steadicam/360-degree sequences. VistaVision rushes were intended to support 70mm release prints, making capture and exhibition format part of the production strategy rather than an after-the-fact prestige label. Kodak documents film processing and 4K scanning at Magyar Filmlabor/Hungarian Filmlab with Máté Ternyik overseeing dailies and final DI from Post Office Films. Editor Dávid Jancsó's later technical account describes VistaVision material scanned as 6K DPX, more than 700 TB of scans and over ten million files. The locked case preserves this 4K/6K source-level pipeline difference rather than inventing a single universal scan specification; it may reflect different stages, materials or reporting scopes, but the sources do not fully reconcile it. Jancsó also describes editorial and post moving Budapest to New York to London and back to Budapest, while VFX and sound collaborators worked across multiple countries. Multiple 35mm, 70mm and digital deliverables, distributor versions, SDR/HDR and aspect-ratio variants made versioning a production-management problem. Judy Becker's production design likewise used a hybrid build/location strategy rather than constructing one complete Van Buren Institute. Becker began from sketches and a large architectural model, built selected portions outside Budapest, repurposed modernist Hungarian locations, silos and a reservoir as different pieces of the fictional complex, and used post-production adjustments where needed. That strategy turned location scouting, model-making, partial construction and digital finishing into one coordinated architectural system. Costume designer Kate Forbes describes a naturalistic, nearly documentary approach across 1947-1980, using period research and social position rather than treating every decade as a stylized fashion tableau. VFX was present but comparatively restrained. Crawley describes an on-set VFX dialogue with Lipsync, limited greenscreen use, digital additions such as the institute in landscape views and a classical photographic approach for most material. Editorial was deliberately sparse and structural: Jancsó describes long scenes being radically reduced while preserving long takes, abrupt cuts and temporal architecture rather than conventional coverage-driven continuity. The post pipeline also used Respeecher for narrowly scoped Hungarian-language dialogue editing after coaching and ADR attempts. Jancsó and Corbet state that specific Hungarian vowels/letters were refined while preserving the actors' performances and that no English-language dialogue was changed. Claims that AI created the finished architectural design are not accepted: Corbet states Judy Becker and her team did not use AI to create or render the buildings, while concept-reference experimentation by an architectural consultant remains a separate previsualization issue. Sound designer Andy Neil documents reliance on production wild tracks from mixer Szabolcs Gáspár, including location-specific architecture such as the staircase, and a design problem centered on construction scale, offscreen activity, perspective and the dense opening arrival sequence. Daniel Blumberg's score was developed through experimental and location-responsive recording rather than a single conventional orchestral session; direct interviews document prepared piano, close-miked acoustic experiments, improvising collaborators, quarry acoustics and material overlap between music and construction sound. The historical lesson is therefore not simply that The Brutalist made a large-looking film cheaply. It is that a roughly USD 10 million independent production used a compressed shoot, Hungarian infrastructure, partial builds and locations, revived VistaVision, multiple film formats, laboratory/post partnerships, sparse coverage, global file transfer, selective VFX, narrowly bounded speech technology and highly integrated sound/music choices to achieve physical and temporal scale. The locked evidence does not establish a complete financing/recoupment ledger, exact all-department crew count, every shooting day and second-unit day, complete camera serial/lens-per-shot ledger, every stock load and lab push value, a reconciled 4K/6K scan map, every VFX shot/vendor task, full DI/color-management settings, complete edit revision history, every Respeecher-processed phoneme, full dialogue/ADR/Foley/mix ledger, complete score-session ledger, every 35mm/70mm/DCP/HDR/SDR version or territory-specific distribution accounting. Those remain explicit unresolved boundaries.",
    requiredChoicesSeed: {
      screenplay: ["award_priority_not_workflow_evidence", "venice_bbfc_215_runtime", "ten_million_budget_anchor", "34_day_kodak_schedule", "pandemic_delay_boundary", "finance_waterfall_unresolved"],
      camera: ["8_perf_vistavision_35mm", "leica_s_lenses", "arricam_st_lt_arriflex_235_cooke_s4", "arriflex_416_16mm_zeiss_superspeed", "modified_arriflex_435", "vision3_250d_500t", "push_processing", "full_camera_ledger_unresolved"],
      editing: ["sparse_coverage_long_take_structure", "hungarian_filmlab_post_office", "4k_6k_scan_variance", "700tb_global_post", "multi_format_versioning", "respeecher_hungarian_only", "full_revision_ledger_unresolved"],
      sound: ["production_wild_tracks", "construction_scale_perspective", "opening_arrival_mix", "blumberg_prepared_piano", "quarry_acoustics", "music_sound_overlap", "full_mix_score_ledgers_unresolved"],
      themes: ["film_history", "2024", "the_brutalist", "venice_silver_lion", "vistavision", "independent_production", "global_post", "chapter19"]
    },
    learningGoals: [
      "Explain why the Venice, BAFTA and Academy wins justify award-priority selection without proving production workflow.",
      "Identify Brady Corbet as director and separate directing awards from the craft evidence used elsewhere in the case.",
      "Use La Biennale's 215-minute competition runtime and BBFC's 214m52s cinema version as mutually consistent runtime anchors.",
      "Round the playable runtime to 215 minutes without inventing frame identity across all release versions.",
      "Use approximately USD 10 million as the documented production-budget anchor while keeping the full finance waterfall unresolved.",
      "Explain why presales and other financing components must not be inferred from the headline budget alone.",
      "Identify the planned 2020 start and pandemic/cast-crew delays as development-to-production timing evidence.",
      "Identify six weeks of cinematography preparation before principal photography.",
      "Use Kodak's 34 shooting days as the locked schedule anchor.",
      "Map principal photography from Budapest to Carrara and the later small New York camera unit.",
      "Explain why a small New York unit does not imply the full production relocated to the United States.",
      "Identify 8-perf horizontal 35mm VistaVision as the dominant capture format.",
      "Explain how VistaVision increases image area while still using 35mm stock.",
      "Explain why the format was used for both broad architecture/landscape and intimate portraiture.",
      "Identify Camera Revolution and Movietech's roles in supplying and preparing the VistaVision system.",
      "Identify Leica-S lenses as the documented VistaVision optics.",
      "Identify ARRICAM ST/LT and ARRIFLEX 235 with Cooke S4 optics as standard-35mm support systems.",
      "Identify ARRIFLEX 416 with Zeiss Superspeeds as the documented 16mm documentary-style package.",
      "Identify Digital Betacam as a deliberate period-TV texture rather than a production master format.",
      "Explain the specially modified ARRIFLEX 435 mistimed shutter as a selected in-camera streak effect.",
      "Identify KODAK VISION3 250D 5207/7207 and 500T 5219/7219 as the locked film stocks.",
      "Explain why 35mm and 16mm stock codes must stay format-specific.",
      "Explain push-processing by roughly one to one-and-a-half stops as a texture/exposure strategy rather than a universal lab setting for every roll.",
      "Explain Crawley's naturalistic lighting policy as protecting and shaping real spaces rather than imposing one lighting diagram everywhere.",
      "Explain why sparse coverage transfers risk from editorial coverage to rehearsal, blocking and camera execution.",
      "Explain how long takes can reduce setup count while increasing coordination cost inside each setup.",
      "Explain the 360-degree Steadicam sequence as a problem of camera-mode transitions, hidden lighting and performer timing.",
      "Explain why capture on VistaVision and release on 70mm are related but not the same film format.",
      "Identify Hungarian Filmlab as the documented processing/scanning facility.",
      "Identify Máté Ternyik and Post Office Films in the dailies/final-DI chain.",
      "Preserve Kodak's 4K scan account and Jancsó's 6K VistaVision DPX account as a source/pipeline scope difference.",
      "Reject the unsupported claim that all source negative was scanned once at one single resolution.",
      "Use the more-than-700-TB scan figure as a post-data scale anchor rather than a final-deliverable size.",
      "Explain why more than ten million files creates media-management and transfer constraints.",
      "Map post-production movement through Budapest, New York, London and back to Budapest.",
      "Explain distributed VFX and sound work as a Chapter 19 global post-production system.",
      "Explain why 35mm, 70mm and digital masters multiply versioning obligations.",
      "Explain why SDR/HDR, distributor and aspect-ratio variants belong to delivery/versioning rather than principal photography.",
      "Identify Judy Becker as production designer.",
      "Explain the Van Buren Institute as a composite of a scale model, partial builds, dressed locations and post adjustments.",
      "Explain why the project did not need to construct the full fictional institute at one site.",
      "Use Hungarian modernist buildings, silos and the reservoir as examples of location substitution without claiming every space was practical.",
      "Explain how model-making and partial construction supported both storytelling and budget control.",
      "Identify Kate Forbes as costume designer and the 1947-1980 span as a continuity/research burden.",
      "Explain the costume strategy as naturalistic and socially specific rather than decade caricature.",
      "Explain Lipsync's on-set VFX dialogue and the limited greenscreen approach without claiming a zero-VFX film.",
      "Explain the digitally inserted institute landscape as an example of practical/digital complementarity.",
      "Identify Dávid Jancsó as editor.",
      "Explain the editing style as deliberate long-take retention plus selective, abrupt structural cuts.",
      "Explain why reducing a long monologue in editorial does not imply conventional high-coverage shooting.",
      "Identify Respeecher as a narrowly bounded Hungarian-dialogue post tool after coaching and ADR attempts.",
      "State that specific Hungarian vowels and letters were refined while the actors' performance was retained.",
      "State that no English-language dialogue was changed according to Corbet's clarification.",
      "Reject the claim that Judy Becker's finished buildings were generated or rendered by AI.",
      "Keep architectural concept-reference experimentation separate from final production-design authorship.",
      "Identify Szabolcs Gáspár as production sound mixer and Andy Neil as sound designer in the locked sound evidence.",
      "Explain production wild tracks as material for preserving location-specific architectural sound.",
      "Explain construction sound as an offscreen scale and perspective problem rather than a library-effects checklist.",
      "Explain why the opening arrival sequence is a mix-priority problem with multiple simultaneous narrative layers.",
      "Identify Daniel Blumberg as composer.",
      "Explain prepared piano and experimental close-miking as part of the score's material construction.",
      "Explain quarry acoustic recording as location-responsive scoring rather than generic convolution-reverb evidence.",
      "Explain how brass/construction-like textures can blur the boundary between score and sound design intentionally.",
      "Keep complete production finance, payroll, deferment and recoupment ledgers unresolved.",
      "Keep complete daily reports, crew census, camera serials, lens-per-shot metadata and stock-load logs unresolved.",
      "Keep the exact 4K/6K scan-stage reconciliation and complete color-management pipeline unresolved.",
      "Keep every VFX shot, AI-processed phoneme, edit revision, dialogue/ADR/Foley stem, mix master and score session unresolved.",
      "Keep every 35mm/70mm/DCP/HDR/SDR and territory-specific delivery version unresolved.",
      "Close the case only when awards, runtime, budget boundary, schedule, formats, lab/post, design, editorial, speech-tech, sound, music and unresolved ledgers agree."
    ],
    phases: [
      { id: "award_priority", label: "Lock the award priority", player_task: "Use Venice/BAFTA/Oscar results to prioritize the case without treating awards as production evidence." },
      { id: "runtime_boundary", label: "Freeze the 215-minute runtime", player_task: "Anchor the playable record to Venice and BBFC cinema evidence." },
      { id: "budget_boundary", label: "Lock the budget anchor", player_task: "Use the documented roughly USD 10 million production budget while leaving the full finance waterfall unresolved." },
      { id: "pandemic_delay", label: "Separate delay from shoot", player_task: "Record the planned 2020 start and later delay without adding those years to principal-photography duration." },
      { id: "prep_window", label: "Plan cinematography prep", player_task: "Use the documented six-week DP preparation period before the March 2023 start." },
      { id: "shoot_calendar", label: "Build the 34-day schedule", player_task: "Route Budapest, Carrara and the small New York unit against the locked Kodak schedule." },
      { id: "vistavision_package", label: "Prepare VistaVision", player_task: "Coordinate Camera Revolution, Movietech, Leica-S optics and 8-perf 35mm transport." },
      { id: "support_formats", label: "Assign support cameras", player_task: "Use standard 35mm, 16mm and Digital Betacam only for the documented production functions." },
      { id: "special_shutter", label: "Build the streak effect", player_task: "Use the modified ARRIFLEX 435 only where the mistimed-shutter effect is intended." },
      { id: "film_stocks", label: "Load the film stocks", player_task: "Plan VISION3 250D and 500T across 35mm/16mm without inventing a roll-by-roll ledger." },
      { id: "push_processing", label: "Control texture at the lab", player_task: "Apply documented push-processing logic without pretending every roll had the same push." },
      { id: "naturalistic_lighting", label: "Light the space", player_task: "Protect useful location light and preserve camera movement rather than over-rigging every angle." },
      { id: "sparse_coverage", label: "Commit to sparse coverage", player_task: "Trade large coverage counts for rehearsal, blocking and precise long-take execution." },
      { id: "oner_coordination", label: "Execute the complex oner", player_task: "Coordinate Steadicam, handheld-like transitions, performers and concealed lighting through the 360-degree scene." },
      { id: "70mm_release", label: "Protect large-format exhibition", player_task: "Carry VistaVision material through a pipeline capable of 70mm release without conflating capture and projection formats." },
      { id: "lab_pipeline", label: "Route negative through Budapest", player_task: "Process and scan through Hungarian Filmlab with dailies/DI continuity at Post Office Films." },
      { id: "scan_variance", label: "Preserve scan provenance", player_task: "Keep the 4K and 6K source descriptions visible until their exact pipeline stages can be reconciled." },
      { id: "media_scale", label: "Manage the scan volume", player_task: "Treat 700TB-plus source scans and millions of files as storage, transfer and version-control constraints." },
      { id: "global_post", label: "Move editorial safely", player_task: "Coordinate Budapest, New York, London and remote vendor handoffs without losing source/version identity." },
      { id: "delivery_matrix", label: "Build the delivery matrix", player_task: "Separate 35mm, 70mm, digital, SDR/HDR, distributor and aspect-ratio deliverables." },
      { id: "institute_model", label: "Design the institute model", player_task: "Use the architectural model as design/continuity infrastructure rather than assuming one full-scale build." },
      { id: "partial_builds", label: "Build only critical architecture", player_task: "Allocate construction to the portions that require direct performance and camera interaction." },
      { id: "location_composite", label: "Assemble the institute from locations", player_task: "Integrate Hungarian modernist buildings, silos and reservoir spaces into one fictional complex." },
      { id: "costume_continuity", label: "Track 1947-1980 costume", player_task: "Use naturalistic period research and social-position logic across decades." },
      { id: "vfx_boundary", label: "Use selective VFX", player_task: "Add environment/institute elements where necessary while retaining the production's primarily classical photography." },
      { id: "structural_edit", label: "Cut for architectural rhythm", player_task: "Use long-take retention and decisive cuts rather than coverage-driven cutting by default." },
      { id: "language_edit", label: "Bound the speech technology", player_task: "Limit Respeecher evidence to Hungarian vowel/letter refinement and preserve the no-English-change boundary." },
      { id: "ai_authorship_boundary", label: "Protect design authorship", player_task: "Do not label Becker's finished architecture AI-generated; keep concept-reference experiments separate." },
      { id: "production_sound", label: "Capture architectural wild tracks", player_task: "Preserve location-specific stairs, rooms and construction textures for post design." },
      { id: "construction_sound", label: "Build offscreen scale", player_task: "Use sound perspective and activity to make the construction world extend beyond the frame." },
      { id: "score_materials", label: "Build the score materially", player_task: "Use prepared piano, improvisation and location-responsive recording without inventing a complete cue/session ledger." },
      { id: "uncertainty_register", label: "Freeze unsupported ledgers", player_task: "Keep finance, daily reports, full camera/lab/VFX/edit/AI/sound/music and delivery accounting explicitly unresolved." },
      { id: "production_verification", label: "Close The Brutalist production audit", player_task: "Verify runtime, budget boundary, 34-day schedule, VistaVision package, lab/post provenance, design, editorial, speech-tech, sound, music and unresolved ledgers before canonical promotion." }
    ]
  }
] as const;

export function mergeChapterNineteenTheBrutalistExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterNineteenTheBrutalistExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_nineteen_the_brutalist_verified",
      source: { list_id: "manual_chapter_nineteen_the_brutalist_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}