import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterNineteenOneBattleAfterAnotherExpansionDefinitions = [
  {
    id: "scenario_one_battle_after_another_2025",
    title: "One Battle After Another",
    originalTitle: "One Battle After Another",
    aliases: ["One Battle After Another"],
    year: 2025,
    titleType: "Movie",
    runtimeMins: 161,
    directors: ["Paul Thomas Anderson"],
    genres: ["Action", "Drama", "Thriller"],
    sourceId: "kodak_one_battle_after_another_2025",
    sourceUrl: "https://www.kodak.com/en/motion/blog-post/one-battle-after-another/",
    scenarioType: "award_priority_oscar_best_picture_bafta_best_film_paul_thomas_anderson_michael_bauman_8perf_35mm_horizontal_vistavision_150_frame_beaumont_vistavision_geo_film_panavision_engineering_super35_millennium_xl2_dialogue_exception_vision3_500t_5219_250d_5207_200t_5213_sixty_plus_spherical_lenses_prototype_vistavision_primes_location_mobile_light_footprint_northern_southern_california_el_paso_borrego_texas_dip_practical_sets_practical_explosions_andy_jurgensen_daily_dailies_iterative_edit_sound_car_character_jonny_greenwood_london_contemporary_orchestra_2025",
    premise: "Build One Battle After Another as Chapter 19's next award-priority production case because it won the 2026 Academy Award for Best Picture and the 2026 BAFTA for Best Film, while keeping those awards strictly separate from production-method evidence. The film is treated as a large-scale contemporary photochemical system whose central technical problem was not simply 'shooting on film' but adapting horizontal 8-perf 35mm VistaVision to an improvisational, mobile action production. Kodak documents Paul Thomas Anderson and cinematographer Michael Bauman using the 1.50:1 VistaVision frame with KODAK VISION3 500T 5219, 250D 5207 and 200T 5213. A restored vintage Beaumont VistaVision camera owned by Giovanni Ribisi became the A camera, with two additional bodies from Geo Film Group. Panavision engineering modified the cameras for servicing and production use, fabricated handheld, studio, stabilized-head and aerial components, and built a brighter prototype viewfinder. Because VistaVision camera noise was unsuitable for some crucial interior dialogue, the production selectively used Super 35 with a Panavision Millennium XL2 rather than pretending one acquisition system solved every scene. The lens package exceeded sixty spherical lenses; some lenses were modified to clear the VistaVision mirror and ground glass, and Panavision built prototype large-format primes informed by the optical character of older Super Speeds. Anderson and Bauman accepted warmth, flare and color aberration rather than forcing every lens into one neutral look. Production was mainly location-based across Northern and Southern California and El Paso, Texas, with a mobile, comparatively light lighting footprint that could accommodate performance improvisation. Kodak records mixed color temperatures, neon and fluorescent interiors, strategically placed practicals, construction light towers modified with neutral-density control, and small hidden sources that could be adjusted quickly when blocking changed. The production therefore links photochemical capture to flexible lighting rather than to a rigid classical-studio model. Florencia Martin's production-design testimony adds a parallel practical-build system. Scouting began in 2022 and followed the story's geographic arc through redwoods, sanctuary spaces and desert. Many environments were built practically or constructed inside real locations, while selected work was built at LA North Studios. Sensei Sergio's apartment was built above a real El Paso commercial location and connected to practical circulation spaces. Bob's escape route combined a stage-built bedroom/tunnel system with a dressed redwood-stump exit. The French 75 explosions and car crashes were substantially practical; the bank explosion was executed in a closed Sacramento bank through permits, replacement glass, debris-control furniture and coordination with special-effects supervisor Jeremy Hayes. These examples must not be generalized into a claim that the film contains no digital effects; the current case simply refuses to invent a full VFX shot or vendor ledger that the locked sources do not establish. The climactic Borrego Springs 'Texas Dip' chase makes camera engineering, location timing, editing and sound one integrated production problem. Kodak documents quick reloads at magic hour, support positioned across a miles-long run, a VistaVision camera mounted to a stabilized head on an arm car, an elevator-car rig operating behind the picture vehicles, and occasional camera jams under punishing conditions. Editor Andy Jurgensen began assembling material during production rather than waiting for a finished shoot. UCSB documents Anderson's practice of daily raw-footage screenings, which lets him know by the end of production what material exists before the edit is distilled. Jurgensen describes frame-by-frame rhythm work and repeated rough-cut screenings. For the final chase, production/editor sources document a non-storyboarded or loosely structured capture process built from multiple car perspectives, followed by iterative selection and compression. A long version went early to the sound department so each car could develop a distinct sonic identity; those sound layers then helped reveal where the sequence could be shortened. Jurgensen also projected the sequence large while editing to check motion intensity and continued refining picture into the final mix. Supervising sound editor and re-recording mixer Christopher Scarabosio is documented as a core sound author, but the current locked source set does not establish a complete production microphone inventory, radio-frequency plan, ADR/Foley ledger, premix/stem routing or final mix-stage configuration, so those remain unresolved. Jonny Greenwood's score is unusually well documented by Nonesuch: eighteen original compositions, London Contemporary Orchestra, conductor Hugh Tieppo-Brunt, and Greenwood performing piano, guitar, bass, percussion and ondes Martenot; album production credits identify Abbey Road and Angel Studios, recording, mix and mastering personnel. Editorial testimony shows that Greenwood did not simply lock music to finished picture: musical ideas moved between script, edit and later adaptation, especially in long action passages. Costume evidence from Colleen Atwood shows a similarly performance-centered process: grounded character dressing, fittings at Anderson's home and 35mm viewing of adjustments, with specific garments developed around character and actor input. The BBFC classifies the 2D cinema version at 161 minutes 31 seconds while also displaying a separate approximate 155-minute metadata field, so this case uses 161 minutes as the playable rounded runtime while preserving the catalog inconsistency as a provenance boundary. Awards establish priority and historical reception, not workflow. Current locked sources do not establish a single audited final negative cost, complete financing waterfall, exact total shooting-day count, exhaustive crew census, full laboratory/negative-conform chain, complete camera serial/body allocation, every lens-to-shot mapping, full lighting inventory, all stunt safety paperwork, complete VFX shot/vendor ledger, complete production-sound equipment list, ADR/Foley/stem architecture, full editorial software/version history, distribution recoupment or complete release-format economics; those remain unresolved.",
    requiredChoicesSeed: {
      screenplay: ["award_priority_not_workflow_evidence", "vineland_inspiration_not_literal_adaptation_map", "runtime_bbfc_161_boundary", "budget_finance_unresolved", "geographic_arc_redwoods_sanctuary_desert"],
      camera: ["8perf_35mm_horizontal_vistavision", "one_point_five_frame", "beaumont_a_camera", "geo_film_additional_bodies", "panavision_vistavision_engineering", "millennium_xl2_super35_dialogue_exception", "vision3_500t_5219", "vision3_250d_5207", "vision3_200t_5213", "sixty_plus_spherical_lens_package", "prototype_vistavision_primes", "mobile_location_lighting", "texas_dip_arm_car", "elevator_car_rig"],
      editing: ["anderson_daily_raw_footage_screenings", "jurgensen_frame_by_frame_rhythm", "chase_assembled_during_production", "early_sound_department_handoff", "large_projection_motion_check", "final_mix_picture_refinement"],
      sound: ["scarabosio_supervising_sound", "cars_as_distinct_sound_characters", "early_chase_sound_design", "greenwood_edit_music_iteration", "full_sound_chain_unresolved"],
      themes: ["film_history", "2025", "one_battle_after_another", "oscar_best_picture", "bafta_best_film", "vistavision", "photochemical_persistence", "practical_location_production", "chapter19"]
    },
    learningGoals: [
      "Explain why the 2026 Oscar Best Picture and BAFTA Best Film wins justify award-priority selection without proving production workflow.",
      "Identify Paul Thomas Anderson as writer-director-producer and Michael Bauman as cinematographer in the locked production record.",
      "Use the BBFC 161-minute cinema classification as the rounded playable runtime while preserving its separate approximate metadata discrepancy.",
      "Explain 8-perf horizontal 35mm VistaVision as the principal image-production system.",
      "Identify 1.50:1 as the documented native VistaVision composition frame.",
      "Identify KODAK VISION3 500T 5219, 250D 5207 and 200T 5213 as the documented stocks.",
      "Identify the vintage Beaumont VistaVision body as the A camera.",
      "Identify Giovanni Ribisi as the owner of the restored A-camera body without turning ownership into a cinematography credit.",
      "Identify two additional VistaVision bodies supplied by Geo Film Group.",
      "Explain why Panavision engineering had to modify and support vintage VistaVision hardware for contemporary production use.",
      "Identify purpose-built handheld, studio, stabilized-head and aerial components as adaptations to the camera system.",
      "Explain the prototype viewfinder as an operating improvement rather than a new capture format.",
      "Explain why camera noise created a sequence-specific exception to the VistaVision rule.",
      "Identify Panavision Millennium XL2 Super 35 as the documented interior-dialogue exception.",
      "Reject the claim that every shot was captured in VistaVision.",
      "Explain why the lens package exceeded sixty spherical lenses.",
      "Explain why some lenses required physical modification to clear the VistaVision mirror and ground glass.",
      "Explain prototype large-format primes as an attempt to carry older Super-Speed optical character into VistaVision coverage.",
      "Preserve warm rendering, flare and color aberration as accepted characteristics rather than defects automatically normalized away.",
      "Identify Northern California, Southern California and El Paso as principal documented production geographies.",
      "Explain mobile light-footprint production as a way to protect improvisation and location responsiveness.",
      "Explain mixed color temperatures, neon and fluorescent sources as deliberate parts of the lighting vocabulary.",
      "Explain construction light towers and neutral-density control as a practical location-lighting solution.",
      "Explain small hidden sources as a way to respond quickly when actor blocking changed.",
      "Identify Florencia Martin as production designer and Anthony Carlino as set decorator in the award/production record.",
      "Explain why scouting beginning in 2022 matters to a film built around a large geographic journey.",
      "Explain the story geography from redwoods to sanctuary spaces to desert as a production-design planning problem.",
      "Distinguish real locations, builds inside real locations and LA North stage work.",
      "Explain Sensei Sergio's apartment as a practical build integrated into a real El Paso location.",
      "Explain Bob's tunnel/escape-hatch system as a hybrid of stage construction and location dressing.",
      "Identify practical explosions and car crashes as documented physical-effects work without claiming the film has no digital effects.",
      "Explain the Sacramento bank explosion through permits, replacement glass, debris control and special-effects coordination.",
      "Keep the complete VFX vendor and shot ledger unresolved.",
      "Explain Borrego Springs and the Texas Dip as a geography-driven action-production system.",
      "Explain why magic-hour photography created quick-reload and support-positioning pressure across a miles-long run.",
      "Identify the stabilized-head arm-car configuration used for VistaVision chase photography.",
      "Identify the elevator-car camera rig as a separate moving capture solution.",
      "Explain camera jams and harsh sun as reliability/exposure constraints rather than romantic production anecdotes.",
      "Identify Andy Jurgensen as editor.",
      "Explain Anderson's daily raw-footage screenings as an information loop between production and post.",
      "Explain Jurgensen's frame-by-frame rhythm work as precise pacing rather than merely shortening runtime.",
      "Explain rough-cut screenings and trial edits as iterative editorial testing.",
      "Explain the final chase as assembled from multiple practical perspectives rather than a single previsualized master plan.",
      "Explain early sound-department involvement as a tool for evaluating picture structure.",
      "Explain each chase vehicle receiving a distinct sound identity as a narrative-orientation strategy.",
      "Explain large-screen projection during editing as a check on motion intensity and audience comfort.",
      "Explain why picture changes could continue into the final mix when sound and music were still revealing structure.",
      "Identify Christopher Scarabosio as supervising sound editor and re-recording mixer in the current source set.",
      "Keep the complete production-sound microphone, RF, ADR, Foley and stem architecture unresolved.",
      "Identify Jonny Greenwood as composer and the London Contemporary Orchestra as the documented orchestral ensemble.",
      "Identify Hugh Tieppo-Brunt as conductor.",
      "Identify Greenwood's documented piano, guitar, bass, percussion and ondes Martenot performance roles.",
      "Identify Abbey Road and Angel Studios in the documented soundtrack recording chain.",
      "Explain music as iterative with the edit rather than a layer simply attached after picture lock.",
      "Identify Colleen Atwood as costume designer and explain her grounded character-first approach.",
      "Explain 35mm viewing during costume fittings as a camera-aware costume feedback loop.",
      "Keep audited final budget, financing percentages and recoupment unresolved.",
      "Keep exact total shooting days, complete crew census and full stunt-safety paperwork unresolved.",
      "Keep complete lab/negative-conform, camera-allocation, lens-to-shot and lighting ledgers unresolved.",
      "Close the case only when award context, VistaVision/Super 35 boundaries, stocks/lenses, location/build strategy, practical action, edit, sound, music and uncertainty registers agree."
    ],
    phases: [
      { id: "award_priority", label: "Lock award priority", player_task: "Use Oscar Best Picture and BAFTA Best Film to justify selection while keeping awards separate from workflow evidence." },
      { id: "evidence_hierarchy", label: "Map the evidence hierarchy", player_task: "Separate Academy/BAFTA/BBFC records from Kodak craft testimony and filmmaker/trade interviews." },
      { id: "runtime_boundary", label: "Freeze the runtime boundary", player_task: "Use the classified 161-minute cinema version while preserving the conflicting approximate catalog field." },
      { id: "finance_boundary", label: "Freeze unresolved finance", player_task: "Do not canonicalize a final negative cost or financing waterfall without audited evidence." },
      { id: "vistavision_format", label: "Choose horizontal VistaVision", player_task: "Build the principal capture plan around 8-perf horizontal 35mm and the 1.50 frame." },
      { id: "stock_plan", label: "Map the three film stocks", player_task: "Allocate 5219, 5207 and 5213 by documented lighting needs without inventing a shot ledger." },
      { id: "beaumont_a_camera", label: "Restore the Beaumont A camera", player_task: "Treat the vintage body as production machinery that needs contemporary serviceability." },
      { id: "additional_bodies", label: "Add the Geo Film bodies", player_task: "Use the additional VistaVision bodies to make the format viable across a large action schedule." },
      { id: "panavision_engineering", label: "Engineer VistaVision for production", player_task: "Build service, handheld, studio, stabilized and aerial support around the vintage system." },
      { id: "viewfinder", label: "Improve the operating view", player_task: "Use the prototype viewfinder to improve practical operating without changing capture provenance." },
      { id: "dialogue_exception", label: "Protect sync dialogue", player_task: "Switch selected crucial interiors to Millennium XL2 Super 35 when VistaVision camera noise becomes the wrong tool." },
      { id: "lens_package", label: "Build the spherical lens library", player_task: "Manage the sixty-plus-lens package and compatibility modifications rather than pretending one uniform lens set covers every problem." },
      { id: "prototype_primes", label: "Carry optical character forward", player_task: "Use VistaVision-covering prototype primes that preserve desired older optical traits." },
      { id: "embrace_aberration", label: "Preserve useful imperfection", player_task: "Keep selected warmth, flare and aberration when they support the intended texture." },
      { id: "location_arc", label: "Map the geographic journey", player_task: "Coordinate redwoods, California locations, El Paso and desert geography as one production route." },
      { id: "mobile_lighting", label: "Keep lighting mobile", player_task: "Use practicals, small sources and adaptable units so lighting can follow improvisational blocking." },
      { id: "industrial_practicals", label: "Control industrial practical light", player_task: "Shape construction towers, neon and fluorescent sources without erasing mixed-color location texture." },
      { id: "scouting", label: "Start with long-horizon scouting", player_task: "Treat the 2022 scouting start as a design-development system rather than last-minute location finding." },
      { id: "sensei_build", label: "Integrate the Sensei apartment", player_task: "Build new spatial functions inside a real El Paso location while preserving the surrounding community geography." },
      { id: "escape_tunnel", label: "Build the escape route", player_task: "Coordinate stage-built tunnel space with a practical redwood-stump location exit." },
      { id: "practical_effects", label: "Plan practical impacts", player_task: "Coordinate explosions and crashes physically where documented while leaving undocumented digital augmentation open." },
      { id: "bank_explosion", label: "Engineer the bank explosion", player_task: "Use permits, sacrificial/replacement materials and debris containment to make the practical effect controllable." },
      { id: "texas_dip", label: "Design the Texas Dip chase", player_task: "Use rolling-road geography, magic hour and long travel distances as core action constraints." },
      { id: "arm_car", label: "Mount VistaVision to the arm car", player_task: "Solve stabilized moving photography around the large horizontal camera body." },
      { id: "elevator_car", label: "Deploy the elevator car", player_task: "Create a second moving camera geometry behind the picture vehicles." },
      { id: "camera_reliability", label: "Manage jams and reloads", player_task: "Treat vintage-camera reliability and film reload time as schedule and coverage variables." },
      { id: "daily_screenings", label: "Screen raw footage daily", player_task: "Use Anderson's film-dailies review loop to know what has actually been captured before the shoot ends." },
      { id: "editorial_rhythm", label: "Shape frame-level rhythm", player_task: "Use Jurgensen's frame-by-frame pacing method to balance action, comedy and emotional breathing space." },
      { id: "chase_assembly", label: "Assemble while shooting", player_task: "Build perspective selects during chase photography so missing material can still be identified." },
      { id: "early_sound_handoff", label: "Send the long chase to sound", player_task: "Use provisional vehicle sound identities to test where picture can be condensed." },
      { id: "projection_check", label: "Test motion at scale", player_task: "Project the chase large to judge movement intensity and viewer comfort." },
      { id: "sound_music_iteration", label: "Let sound and music reshape the cut", player_task: "Allow sound design and Greenwood's evolving music to reveal structural trims through final mix." },
      { id: "score_production", label: "Map the score production", player_task: "Track Greenwood, London Contemporary Orchestra, Hugh Tieppo-Brunt and the documented recording/mix chain." },
      { id: "costume_feedback", label: "Check costume through film capture", player_task: "Use character-grounded fittings and 35mm viewing to judge how clothing reads through the chosen imaging system." },
      { id: "uncertainty_audit", label: "Audit unresolved ledgers", player_task: "Keep unsupported budget, shoot-day, VFX, lab, sound, camera-allocation and release-economics details outside canonical truth." },
      { id: "production_verification", label: "Close Production Verification", player_task: "Close only when award priority, VistaVision engineering, practical geography/effects, editorial iteration, sound/music and uncertainty boundaries agree." }
    ]
  }
] as const;

export function mergeChapterNineteenOneBattleAfterAnotherExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterNineteenOneBattleAfterAnotherExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_nineteen_one_battle_after_another_verified",
      source: { list_id: "manual_chapter_nineteen_one_battle_after_another_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
