import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterNineteenTenetExpansionDefinitions = [
  {
    id: "scenario_tenet_2020",
    title: "Tenet",
    originalTitle: "Tenet",
    aliases: [],
    year: 2020,
    titleType: "Movie",
    runtimeMins: 149,
    directors: ["Christopher Nolan"],
    genres: ["Action", "Sci-Fi", "Thriller"],
    sourceId: "bfi_tenet_2020",
    sourceUrl: "https://www.bfi.org.uk/film/f1191430-33a7-5a09-9ad7-0d6eec1b991f/tenet",
    scenarioType: "photochemical_65mm_imax_system65_forward_reverse_inversion_global_location_practical_sfx_dneg_vfx_photochemical_finish_pandemic_release_2020",
    premise: "Build Tenet as the first source-first Chapter 19 Production Case and keep three systems separate: a production photographed in 2019 before COVID-19 shutdowns, a large-format photochemical and practical/VFX workflow, and a 2020 theatrical release disrupted by the pandemic. BFI records Christopher Nolan as director and writer, Emma Thomas and Nolan as producers, and a 149-minute running time; that 149-minute institutional record is the playable anchor rather than a claim that every release master or catalogue rounds the duration identically. Hoyte van Hoytema's production account describes a roughly 250-person shoot on US stages and locations across Denmark, Estonia, India, Italy, Norway and the UK, using a strategic combination of 70mm and IMAX cameras. He identifies six IMAX camera packages, a Panavision Large Format System 65 package, an ARRI 65 package and a Logmar Magellan 65mm prototype used for several scenes. Panavision independently records System 65 Studio camera/optics and Sphero 65 lenses, while IMAX confirms that selected sequences were photographed with 15-perf 70mm IMAX cameras and that the film was refined for IMAX exhibition. Those records establish a mixed large-format film system, not a license to invent a shot-by-shot camera, lens, film-stock, frame-rate or exposure map. The inversion concept is treated as a production-coordination problem rather than a post-production button: van Hoytema describes key time-inversion sequences being photographed in both forward and backward directions, while the case preserves that as sequence-specific evidence instead of claiming every reversed event was photographed twice. Nathan Crowley's production design, Scott Fisher's special-effects work, stunt performance, location logistics, picture editorial and VFX had to share one forward/reverse spatial logic. Andrew Jackson and DNEG describe a hierarchy favoring in-camera effects, then filmed-element compositing, then CG where needed; DNEG was deeply involved despite the relatively restrained final VFX count. The 747 set piece is an explicit boundary case: Andrew Jackson describes a full-size retired 747 striking a set-built building with practical fire, collapse and jet-bridge action, while VFX handled cable removal and cleanup. Other sequences combined full-size practical action, miniatures, photographed elements, compositing and CG, so 'practical' never becomes 'no VFX'. DNEG VFX supervisor Andy Lockley describes extensive on-set photography/LIDAR capture, a roughly 300-person DNEG effort over more than a year, and IMAX scans around 6.3K inside a pipeline geared toward a photochemical finish rather than a conventional DI. That finishing evidence is kept distinct from unsupported claims about every scan resolution, record-out setting, lab stock, printer-light value or release-print route. Jennifer Lame is the credited editor, and the film's palindromic/inversion structure requires editorial continuity across forward and reverse actions without turning the finished chronology into proof of undocumented cutting software or turnover details. Richard King describes the sound team building custom vehicle, weapon and inversion material; production sound mixer Willie Burton developed boom/planted/tiny-mic approaches for masked dialogue, and the production relied heavily on usable location dialogue with only limited looping. Ludwig Göransson's score is treated as a separate authorship system whose processed, stretched and temporally suggestive materials interact with sound design without collapsing score and effects into one track. The player must coordinate large-format negative custody, noisy IMAX-versus-dialogue constraints, global location continuity, forward/reverse blocking, stunt and performer safety, practical SFX, miniatures, VFX reference capture, editorial version control, dialogue intelligibility, sound design, score, photochemical/VFX finishing and pandemic-era theatrical delivery while refusing unsupported exact budget or financing shares, exact shooting-day count, exact film-stock inventory, complete camera-body assignment, complete Sphero or other lens-by-shot map, exact frame rates, shutter angles, exposure indexes, push/pull processing, filter package, complete stunt or pyrotechnic procedures, full VFX shot ledger, software/render topology, exact scan/record-out settings, edit software/version, complete ADR census, microphone-by-line map, music stems, final mix routing or a claim that COVID-19 protocols governed principal photography when the documented shoot occurred in 2019.",
    requiredChoicesSeed: {
      screenplay: ["nolan_writer_director", "inversion_rules", "palindromic_structure", "forward_reverse_causality", "production_release_boundary", "pandemic_release_not_pandemic_shoot"],
      camera: ["hoyte_van_hoytema", "65mm_photochemical", "imax_15perf_70mm", "panavision_system65", "sphero65", "six_imax_packages", "arri65_package", "logmar_magellan_65mm", "large_format_negative_custody", "shot_map_unknown"],
      editing: ["jennifer_lame", "forward_reverse_continuity", "palindrome_structure", "inversion_action_matching", "photochemical_vfx_handoff", "runtime_provenance"],
      sound: ["richard_king", "willie_burton", "masked_dialogue", "custom_vehicle_weapon_recordings", "limited_looping", "ludwig_goransson", "score_sound_boundary"],
      themes: ["film_history", "2020", "tenet", "christopher_nolan", "emma_thomas", "hoyte_van_hoytema", "jennifer_lame", "nathan_crowley", "richard_king", "willie_burton", "ludwig_goransson", "andrew_jackson", "andy_lockley", "scott_fisher", "dneg", "photochemical", "65mm", "imax", "system65", "sphero65", "inversion", "practical_effects", "visual_effects", "global_location_production", "photochemical_finish", "pandemic_release", "chapter19"]
    },
    learningGoals: [
      "Explain Tenet as the first Chapter 19 Production Case and distinguish its 2019 production from its pandemic-disrupted 2020 release.",
      "Use the BFI 149-minute record as the playable runtime anchor while allowing other catalogue or release records to round duration differently.",
      "Identify Christopher Nolan as writer-director and Emma Thomas plus Nolan as producers without using those credits to infer every department decision.",
      "Identify Hoyte van Hoytema as cinematographer and keep cinematography authorship distinct from camera-vendor or exhibition claims.",
      "Explain why Tenet is evidence for photochemical large-format persistence at the start of Chapter 19 rather than evidence that digital production had reversed course.",
      "Identify the documented strategic combination of 70mm and IMAX cameras without collapsing all photography into one format.",
      "Identify six IMAX camera packages as a documented production-scale fact while refusing a complete unit-by-unit or shot-by-shot camera assignment.",
      "Identify the Panavision Large Format System 65 package as documented by van Hoytema and Panavision.",
      "Identify Panavision System 65 Studio camera/optics and Sphero 65 lenses as package evidence rather than proof that every setup used one body or lens family.",
      "Identify an ARRI 65 package as part of the documented production inventory without inventing exact scenes or focal lengths assigned to it.",
      "Identify the Logmar Magellan 65mm prototype as a documented additional camera used for several scenes while preserving exact scene assignment as unresolved.",
      "Explain that selected sequences were shot with 15-perf 70mm IMAX cameras and that IMAX presentation expanded those sequences.",
      "Keep exhibition format separate from capture format: an IMAX screening or 70mm print never proves the camera used for every shot.",
      "Treat the large-format negative as a physical production asset requiring custody, scanning and VFX handoff without inventing lab-routing details.",
      "Explain the dialogue/noise constraint created by IMAX film cameras and why quieter large-format systems can remain necessary for some material.",
      "Keep exact Kodak stock numbers, exposure indexes, processing, shutter angles and filtration unresolved unless title-specific primary records establish them.",
      "Keep a complete lens-by-shot map unresolved even though Panavision documents Sphero 65 and System 65 service for the film.",
      "Explain the inversion concept as coordinated writing, rehearsal, performance, camera, SFX, stunt, VFX, editorial and sound work rather than a simple reverse-video effect.",
      "Use van Hoytema's account that key inversion sequences were photographed in forward and backward directions without generalizing that method to every inverted event.",
      "Explain why forward/reverse shooting requires continuity of geography, costume, props, vehicles, eyelines, timing and physical consequences.",
      "Treat actor movement in inverted scenes as performance choreography without converting historical production evidence into present-day stunt instruction.",
      "Treat vehicle and action inversion as a safety-intensive production problem while keeping exact driving, rigging and stunt procedures outside the learning layer.",
      "Identify Nathan Crowley as production designer and explain how architecture and spatial continuity support action that must read in two temporal directions.",
      "Explain why the seven-country production footprint requires location continuity, permits, transport and unit coordination without inventing a country-by-country shooting schedule.",
      "Identify Denmark, Estonia, India, Italy, Norway, the UK and US-stage/location work as documented production geography.",
      "Keep exact shooting-day totals, local crew counts, permit terms, incentives and country-level spend unresolved unless primary production records establish them.",
      "Identify Scott Fisher's special-effects contribution and distinguish physical SFX from DNEG's visual-effects work.",
      "Explain the production's preference hierarchy for in-camera effects, filmed-element composites and CG while rejecting the false claim that Tenet has no VFX.",
      "Use the full-size 747 sequence as evidence that major spectacle could be designed around physical production and later digital cleanup.",
      "Explain that the 747 hit a set-built structure with practical fire/collapse while cable removal and cleanup remained VFX tasks.",
      "Treat the 747 case as title-specific evidence rather than a rule that practical full-scale work is always cheaper, safer or preferable.",
      "Explain how full-size vehicles, miniatures, practical elements and CG could coexist inside the same effects sequence.",
      "Identify Andrew Jackson as overall VFX supervisor and Andy Lockley as DNEG VFX supervisor without collapsing VFX and special effects roles.",
      "Identify DNEG as a central VFX partner and preserve its roughly 300-person reported project effort as company testimony rather than an exact full-film crew census.",
      "Explain why extensive on-set photography and LIDAR capture can be valuable even when the final film contains relatively restrained visible VFX.",
      "Explain that VFX reference capture is contingency infrastructure and does not mean every photographed object became a digital asset in the final cut.",
      "Keep the exact total VFX shot count, vendor task ledger, software versions, render farm, simulation settings and per-shot asset history outside the verified layer unless directly sourced.",
      "Explain DNEG's description of IMAX scans around 6.3K as VFX-pipeline evidence without promoting that number to every scan or every source element.",
      "Explain the photochemical-finish orientation and distinguish it from a conventional full-film digital intermediate.",
      "Keep exact negative cutting, record-out, printer-light, answer-print and release-print parameters unresolved unless title-specific lab records establish them.",
      "Identify Jennifer Lame as editor and treat editorial authorship as central to maintaining comprehensible causality across forward and inverted action.",
      "Explain why the palindrome-like structure creates version-control and continuity demands before, during and after principal photography.",
      "Keep exact edit software, project settings, proxy recipes, turnover naming and conform topology unresolved unless stronger records establish them.",
      "Identify Richard King as the principal sound-design/supervising sound-editor authority used for the source-first case.",
      "Explain that custom vehicle, weapon and unusual sound recordings were created to make inversion legible rather than relying only on generic library reversal.",
      "Identify Willie Burton as production sound mixer and explain why masked dialogue required microphone experimentation and placement choices.",
      "Explain the use of boom plus tiny/planted microphone strategies around masks without turning those accounts into a line-by-line hardware map.",
      "Explain that the film retained substantial production dialogue and used comparatively limited looping while keeping an exact ADR census outside the canonical claim layer.",
      "Keep microphone model-by-line, recorder tracks, RF plan, noise-reduction chain and final dialogue automation unresolved unless title-specific records establish them.",
      "Identify Ludwig Göransson as composer and keep score authorship distinct from Richard King's sound-design authorship.",
      "Explain how processed, stretched and temporally suggestive score material can reinforce inversion without claiming a complete synth, plug-in or stem recipe.",
      "Keep music stems, recording chain, exact tempo maps, plug-ins and final score-routing topology outside the verified layer unless direct production records establish them.",
      "Explain that post-production work overlapped the COVID-19 lockdown period while principal photography had already taken place in 2019.",
      "Explain why pandemic context is legitimate for release and some post-production history but not proof that return-to-work protocols governed principal photography.",
      "Treat Tenet's unusual 2020 theatrical rollout as exhibition/distribution history rather than evidence for who financed or authored production departments.",
      "Explain why the IMAX 70mm release and large-screen design are historically significant while remaining distinct from the film's financing and production ownership.",
      "Maintain an uncertainty register for budget, financing shares, schedule, stocks, camera/lens assignment, frame rates, exposure, processing, stunt procedures, VFX ledger, finishing settings, edit system, ADR census, sound hardware, score stems and mix topology.",
      "Explain Tenet's Chapter 19 significance as a boundary case where photochemical large-format production, highly integrated practical/VFX craft and pandemic-era theatrical disruption intersect but must not be conflated.",
      "Build a closing production audit that checks production-versus-release chronology, runtime provenance, large-format capture boundaries, inversion method, effects collaboration, photochemical finishing, sound/score authorship and unresolved technical claims before verification."
    ],
    phases: [
      { id: "evidence_hierarchy", label: "Map the Tenet evidence hierarchy", player_task: "Separate BFI metadata, van Hoytema production testimony, Panavision/IMAX equipment records, effects-supervisor accounts and sound interviews before promoting claims." },
      { id: "chronology_boundary", label: "Separate production from pandemic release", player_task: "Lock the documented 2019 photography before analyzing post-production lockdown effects and the disrupted 2020 theatrical rollout." },
      { id: "runtime_anchor", label: "Lock runtime provenance", player_task: "Use BFI's 149-minute record as the playable anchor while preserving rounded or version-specific duration records as metadata differences." },
      { id: "global_locations", label: "Map the global production footprint", player_task: "Coordinate the documented US stage/location work with Denmark, Estonia, India, Italy, Norway and UK locations without inventing a day-by-day schedule." },
      { id: "large_format_strategy", label: "Design the mixed large-format strategy", player_task: "Keep IMAX 15-perf 70mm and 65mm systems distinct while deciding which production needs require each class of camera." },
      { id: "imax_packages", label: "Track the IMAX packages", player_task: "Preserve the documented six-package scale without fabricating unit, scene or body assignments." },
      { id: "system65", label: "Track Panavision System 65", player_task: "Use the documented System 65 camera/optics package and Sphero 65 lens evidence without turning rental credits into a shot map." },
      { id: "additional_65mm", label: "Track additional 65mm camera systems", player_task: "Preserve ARRI 65 and Logmar Magellan package evidence while keeping exact scene assignment source-bounded." },
      { id: "negative_custody", label: "Protect large-format negative custody", player_task: "Maintain traceable handling between exposed film, dailies/reference, VFX scans and photochemical finishing without inventing lab settings." },
      { id: "camera_noise", label: "Plan around camera noise", player_task: "Coordinate IMAX spectacle with dialogue needs and quieter alternatives rather than assuming one camera system can serve every setup identically." },
      { id: "inversion_rules", label: "Lock inversion rules", player_task: "Translate screenplay causality into department-readable forward/reverse states before staging action." },
      { id: "dual_direction_capture", label: "Coordinate forward and backward capture", player_task: "Use the documented dual-direction approach for key inversion sequences without claiming every inverted beat was photographed twice." },
      { id: "performance_continuity", label: "Rehearse temporal performance continuity", player_task: "Coordinate eyelines, gesture, prop state and timing across forward/reverse action while keeping stunt procedure non-instructional." },
      { id: "design_geography", label: "Protect production-design geography", player_task: "Use Nathan Crowley's spaces so action remains intelligible when cause and effect are experienced in opposite directions." },
      { id: "vehicle_continuity", label: "Track vehicle states", player_task: "Maintain vehicle identity, damage and temporal state through photography, SFX, stunt, editorial and VFX without specifying hazardous execution methods." },
      { id: "sfx_vfx_boundary", label: "Separate SFX and VFX responsibilities", player_task: "Keep Scott Fisher's physical-effects layer distinct from Andrew Jackson/DNEG visual-effects work while coordinating shared shots." },
      { id: "in_camera_priority", label: "Apply the in-camera preference hierarchy", player_task: "Evaluate practical capture, filmed-element compositing and CG as evidence-backed options rather than reducing the production to an anti-digital slogan." },
      { id: "plane_sequence", label: "Audit the 747 sequence", player_task: "Preserve the documented full-size aircraft, set-built structure and practical fire/collapse alongside VFX cable removal and cleanup." },
      { id: "miniatures_elements", label: "Track miniatures and filmed elements", player_task: "Keep miniature/practical plates source-labeled so later composites do not erase physical-production provenance." },
      { id: "vfx_reference", label: "Capture VFX reference", player_task: "Maintain photography/LIDAR/reference coverage as contingency infrastructure without assuming every captured asset reaches final pixels." },
      { id: "vfx_inversion", label: "Build mixed-entropy VFX", player_task: "Coordinate regular and inverted debris, fire, smoke and damage as a story-readable composite system without exposing procedural hazard instructions." },
      { id: "imax_scans", label: "Bound IMAX scan claims", player_task: "Use DNEG's around-6.3K account only where it applies and keep full scan-resolution lineage unresolved." },
      { id: "photochemical_finish", label: "Protect the photochemical finish", player_task: "Separate VFX scanning/record-out from the broader photochemical finishing path and avoid inventing printer-light or lab parameters." },
      { id: "editorial_structure", label: "Build temporal editorial continuity", player_task: "Use Jennifer Lame's editorial layer to keep cause/effect legible across palindromic and inversion structures." },
      { id: "editorial_handoff", label: "Version editorial/VFX turnovers", player_task: "Track shot state, direction-of-time, plate provenance and replacement status without assuming an undocumented software stack." },
      { id: "production_dialogue", label: "Protect production dialogue", player_task: "Coordinate Willie Burton's boom and small-mic strategies around masks while keeping exact hardware-by-line source-bounded." },
      { id: "dialogue_edit", label: "Make masked dialogue intelligible", player_task: "Use editorial and mix work to preserve intelligibility without falsely converting limited looping into zero ADR." },
      { id: "sound_recording", label: "Build title-specific sound material", player_task: "Use Richard King's custom vehicle, weapon and unusual recordings as authored sound-design material rather than generic reversed-library assumptions." },
      { id: "sound_inversion", label: "Separate forward and inverted sound logic", player_task: "Design temporal cues that clarify inversion while preserving dialogue, effects and ambience as distinct layers." },
      { id: "score_language", label: "Integrate Göransson's score language", player_task: "Coordinate processed and stretched musical ideas with inversion without collapsing score into sound effects." },
      { id: "score_sound_boundary", label: "Protect score/sound authorship", player_task: "Version score, source, ambience and designed effects separately through the final soundtrack." },
      { id: "post_lockdown", label: "Map lockdown-era post-production", player_task: "Document which post tasks were affected by COVID-19 conditions without retroactively applying return-to-work protocols to the 2019 shoot." },
      { id: "imax_exhibition", label: "Prepare IMAX exhibition", player_task: "Keep expanded IMAX sequences and IMAX 70mm delivery tied to exhibition evidence rather than camera assumptions for every shot." },
      { id: "theatrical_release", label: "Separate theatrical rollout from production", player_task: "Treat pandemic postponement and territory-by-territory release as distribution history, not proof of production authorship or financing." },
      { id: "unknowns_register", label: "Maintain the Tenet unknowns register", player_task: "Track budget, financing, schedule, stocks, camera/lens map, frame rates, exposure, processing, stunt details, VFX ledger, finishing, edit, ADR, sound and score unknowns explicitly." },
      { id: "chapter19_position", label: "Position Tenet in Chapter 19", player_task: "Explain why large-format film persistence and pandemic theatrical disruption are simultaneous but separate historical systems." },
      { id: "delivery_review", label: "Audit the complete Tenet production system", player_task: "Verify chronology, runtime, formats, inversion, practical/VFX collaboration, finishing, editorial, sound, score, exhibition and uncertainty boundaries before production verification." }
    ]
  }
] as const;

export function mergeChapterNineteenTenetExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterNineteenTenetExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_nineteen_tenet_verified",
      source: { list_id: "manual_chapter_nineteen_tenet_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
