import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterNineSovietMontageExpansionDefinitions = [
  {
    id: "scenario_mother_1926",
    title: "Mother",
    originalTitle: "Mat",
    aliases: ["Мать"],
    year: 1926,
    titleType: "Feature",
    runtimeMins: 106,
    directors: ["Vsevolod Pudovkin"],
    genres: ["Drama", "History"],
    premise: "Build Mother as a 1926 Mezhrabpom-Rus adaptation of Maxim Gorky's novel in which Vsevolod Pudovkin and screenwriter Nathan Zarkhi organize revolutionary melodrama through Vera Baranovskaya's performance, Anatoli Golovnya's photography, Sergei Kozlovsky's design and editing based on linkage and accumulation rather than Eisensteinian collision alone. The production problem is to make political causality emerge through character, recurring objects, spatial pressure and increasingly forceful shot relations. Preserve the film as a silent 1926 object while keeping modern 90-minute and 106-minute presentation records distinct rather than forcing one immutable runtime.",
    sourceId: "manual_mother_1926",
    sourceUrl: "https://www.loc.gov/rr/mopic/findaid/russian.html",
    scenarioType: "pudovkin_linkage_character_montage_production",
    requiredChoicesSeed: {
      screenplay: ["zarkhi_gorky_adaptation", "mother_radicalization_causal_arc", "melodrama_and_ideology_linkage"],
      camera: ["golovnya_character_action_fragments", "object_and_environment_relations", "mass_action_with_character_legibility"],
      editing: ["pudovkin_linkage_accumulation", "performance_detail_to_political_causality", "ice_floe_and_procession_rhythm"],
      sound: ["silent_1926_production", "live_or_recorded_accompaniment_separate", "no_original_synchronized_dialogue_claim"],
      themes: ["film_history", "soviet_montage", "pudovkin", "mezhrabpom_rus", "adaptation", "political_melodrama"],
    },
    learningGoals: [
      "Distinguish Pudovkin's linkage and accumulation model from Eisenstein's collision model without pretending either director used only one editing principle.",
      "Coordinate Baranovskaya's performance with inserts, reactions, objects and crowd action so character development remains the engine of political meaning.",
      "Preserve Zarkhi's screenplay, Golovnya's cinematography and Kozlovsky's design as documented collaborative authorship rather than collapsing the film into a director-only montage demonstration.",
      "Treat the 1905 revolutionary setting as a represented historical event, not documentary footage or a license to reward dangerous political reenactment.",
      "Use the ice-floe climax and workers' procession to study rhythm, spatial fragmentation and emotional accumulation without turning fast cutting into a universal Soviet preset.",
      "Keep surviving/presentation runtimes and modern accompaniment distinct from one supposedly immutable 1926 release state.",
    ],
    phases: [
      { id: "pitch", label: "Character-led revolutionary montage pitch", player_task: "Define why a mother's political transformation needs editing that accumulates meaning through performance and objects rather than relying on collision alone." },
      { id: "research", label: "Mezhrabpom-Rus evidence", player_task: "Ground Pudovkin, Zarkhi, Golovnya, Kozlovsky, cast, Gorky adaptation, silent format and print/runtime variation in institutional sources." },
      { id: "screenplay", label: "Causal radicalization", player_task: "Map domestic conflict, arrest, prison, procession and attempted escape so political change grows from legible personal consequences." },
      { id: "casting", label: "Performance before abstraction", player_task: "Direct controlled looks, hesitation and physical reaction so montage has human material to connect rather than reducing characters to symbols." },
      { id: "production_design", label: "Objects and social space", player_task: "Use home, factory, prison, street and recurring objects as readable social relations without inventing unsupported set-construction details." },
      { id: "cinematography", label: "Photograph for linkage", player_task: "Capture faces, hands, objects, movement and wider action as fragments that can accumulate while preserving spatial and emotional orientation." },
      { id: "editing", label: "Linkage, rhythm and escalation", player_task: "Build meaning by joining complementary details and performance beats, then intensify rhythm in mass-action passages without equating montage with speed alone." },
      { id: "sound", label: "Silent production boundary", player_task: "Keep 1926 production silent and model accompaniment as exhibition/preservation history rather than synchronized production sound." },
      { id: "release", label: "International reception and print history", player_task: "Separate the film's Soviet production and international acclaim from later prints, scores and different presentation runtimes." },
    ],
  },
  {
    id: "scenario_the_fall_of_the_romanov_dynasty_1927",
    title: "The Fall of the Romanov Dynasty",
    originalTitle: "Padenie dinastii Romanovykh",
    aliases: ["Падение династии Романовых"],
    year: 1927,
    titleType: "Feature",
    runtimeMins: 90,
    directors: ["Esfir Shub"],
    genres: ["Documentary", "History"],
    premise: "Build The Fall of the Romanov Dynasty as Esfir Shub's 1927 compilation-film production problem: archival search, source selection, preservation, recontextualization, intertitles and editing create a new historical argument from existing footage. Shub's earlier work re-editing imported and tsarist-era films becomes production knowledge; for the anniversary commission she and researcher Mark Tseitlin work through enormous quantities of court and news footage. Gameplay must record provenance and editorial transformations rather than treating archival material as neutral evidence or rewarding deceptive context stripping.",
    sourceId: "manual_fall_romanov_dynasty_1927",
    sourceUrl: "https://www.bfi.org.uk/lists/10-great-soviet-films-1920s",
    scenarioType: "shub_archival_compilation_montage_production",
    requiredChoicesSeed: {
      screenplay: ["archive_argument_outline", "tseitlin_intertitle_historical_structure", "provenance_before_rhetoric"],
      camera: ["no_new_principal_photography_required", "source_material_condition_review", "archive_provenance_logging"],
      editing: ["shub_compilation_recontextualization", "court_footage_to_revolutionary_argument", "preservation_through_selection"],
      sound: ["silent_compilation_object", "modern_piano_or_score_separate", "no_retroactive_sync_claim"],
      themes: ["film_history", "soviet_montage", "esfir_shub", "compilation_film", "archives", "documentary_ethics"],
    },
    learningGoals: [
      "Treat archival research, selection and preservation as creative production labor rather than as a passive source-gathering stage.",
      "Record where footage came from and how a new edit changes its argument so historical images are not presented as context-free truth.",
      "Preserve Esfir Shub's authorship and Mark Tseitlin's research/intertitle contribution instead of treating compilation as anonymous assembly.",
      "Distinguish footage created under the Romanovs from the political argument Shub constructs in 1927 through juxtaposition and titles.",
      "Model physical-film scarcity and preservation stakes without encouraging destruction, deceptive alteration or loss of source provenance.",
      "Keep later 86- and 90-minute presentations and accompaniment layers distinct from one immutable original runtime.",
    ],
    phases: [
      { id: "pitch", label: "Archive-history commission", player_task: "Define a historical argument that can be built from existing footage while stating what evidence and provenance must be preserved." },
      { id: "research", label: "Archive search and provenance", player_task: "Locate court, news and other surviving footage, document origins and distinguish primary footage from later editorial interpretation." },
      { id: "screenplay", label: "Argument and intertitle architecture", player_task: "Plan historical progression and title logic before cutting, keeping interpretation separate from what individual shots literally show." },
      { id: "casting", label: "Historical subjects, not performers", player_task: "Do not recast archival people as fictional roles; identify subjects cautiously and avoid invented motives not supported by evidence." },
      { id: "production_design", label: "No fabricated historical world", player_task: "Use graphic titles and archival organization rather than manufacturing fake period imagery to fill evidence gaps." },
      { id: "cinematography", label: "Source inspection instead of new coverage", player_task: "Assess gauge, framing, condition and provenance of existing material; do not pretend archival shots were photographed for the 1927 compilation." },
      { id: "editing", label: "Compilation montage as authorship", player_task: "Create relations across sourced shots while logging omissions, repetitions and contextual changes introduced by the edit." },
      { id: "sound", label: "Silent archive object", player_task: "Keep the compilation silent and treat later live or recorded accompaniment as presentation history." },
      { id: "release", label: "Preservation through reuse", player_task: "Track how the compilation both repurposed and preserved footage, and keep modern restorations separate from 1927 editorial decisions." },
    ],
  },
  {
    id: "scenario_earth_1930",
    title: "Earth",
    originalTitle: "Zemlya",
    aliases: ["Земля"],
    year: 1930,
    titleType: "Feature",
    runtimeMins: 90,
    directors: ["Alexander Dovzhenko"],
    genres: ["Drama"],
    premise: "Build Earth as Alexander Dovzhenko's 1930 Ukrainian Soviet production at the boundary between collectivization propaganda and lyrical, associative cinema. The film was commissioned to support farm collectivization, but its sustained attention to Ukrainian landscape, faces, fruit, weather, death and seasonal cycles exceeds a simple policy message. Preserve VUFKU/Ukrainian institutional context and historical hindsight: the film predates the Holodomor and must not be presented as if Dovzhenko knew the full catastrophe that followed, while the later consequences of collectivization remain essential reception context.",
    sourceId: "manual_earth_1930",
    sourceUrl: "https://www.bfi.org.uk/film/7ecb717a-9c37-5071-a235-93386e7167b7/earth",
    scenarioType: "dovzhenko_ukrainian_poetic_collectivization_production",
    requiredChoicesSeed: {
      screenplay: ["collectivization_commission_vs_poetic_structure", "death_labor_land_cycle", "historical_hindsight_boundary"],
      camera: ["ukrainian_landscape_and_faces", "tractor_and_field_relations", "poetic_close_detail"],
      editing: ["associative_nature_human_montage", "anti_narrative_crosscutting", "rhythm_beyond_policy_message"],
      sound: ["silent_1930_production", "later_scores_and_restorations_separate", "no_original_sync_dialogue"],
      themes: ["film_history", "soviet_montage", "dovzhenko", "ukrainian_cinema", "vufku", "collectivization"],
    },
    learningGoals: [
      "Keep Ukrainian VUFKU production history visible rather than flattening all Soviet cinema into an institutionally Russian category.",
      "Distinguish the collectivization commission from the film's lyrical attention to landscape, bodies and mortality without pretending politics disappears from the work.",
      "Use associative montage, stillness and crosscutting to build relations among land, labor, machinery and death rather than copying Eisenstein's collision model.",
      "Apply historical hindsight carefully: explain the later famine catastrophe without claiming Dovzhenko could foresee its full scale in 1930.",
      "Treat peasants and rural life as historically situated subjects rather than picturesque texture or a scoreable authenticity effect.",
      "Preserve the silent production object and separate later scores, restorations and presentation runtimes from original production sound.",
    ],
    phases: [
      { id: "pitch", label: "Poetry inside a state commission", player_task: "Define how the production can satisfy a collectivization commission while preserving a distinct visual inquiry into land, mortality and change." },
      { id: "research", label: "VUFKU and collectivization context", player_task: "Ground Dovzhenko, Ukrainian studio context, 1930 policy context and later historical consequences without collapsing different time horizons." },
      { id: "screenplay", label: "Land, death and machinery", player_task: "Organize a sparse causal line around community conflict while letting recurring natural and material motifs carry thematic structure." },
      { id: "casting", label: "Faces and bodies as social presence", player_task: "Direct performers for weight, stillness and group relation without reducing rural people to stereotypes or propaganda symbols." },
      { id: "production_design", label: "Landscape and material culture", player_task: "Use agricultural space, tools, homes and the tractor as social material while avoiding invented ethnographic certainty." },
      { id: "cinematography", label: "Landscape, face and object", player_task: "Photograph sky, fields, fruit, machinery and faces as recurring visual units whose relation changes across the film." },
      { id: "editing", label: "Associative Ukrainian montage", player_task: "Build poetic relations and crosscutting rhythms without treating the result as a generic montage template." },
      { id: "sound", label: "Silent production and later scores", player_task: "Keep 1930 production silent and separate subsequent accompaniment/restoration layers from original sound claims." },
      { id: "release", label: "Denunciation, canon and hindsight", player_task: "Model contemporary political criticism, later canonization and modern Ukrainian archival framing as distinct reception layers." },
    ],
  },
  {
    id: "scenario_october_1928",
    title: "October",
    originalTitle: "Oktyabr",
    aliases: ["October: Ten Days That Shook the World", "Октябрь"],
    year: 1928,
    titleType: "Feature",
    runtimeMins: 103,
    directors: ["Sergei Eisenstein", "Grigori Aleksandrov"],
    genres: ["Drama", "History"],
    premise: "Build October as the 1928 tenth-anniversary commission in which Sergei Eisenstein and Grigori Aleksandrov stage and edit the 1917 Revolution as a political reconstruction rather than documentary news footage. The production problem combines large-scale crowd staging, symbolic objects, nonprofessional resemblance casting and intellectual montage, while version control must record political recutting including the removal of Leon Trotsky references. Preserve the gap between historical event and constructed representation and do not reward the player for presenting staged images as authentic newsreel evidence.",
    sourceId: "manual_october_1928",
    sourceUrl: "https://www.moma.org/calendar/events/5338",
    scenarioType: "eisenstein_intellectual_montage_anniversary_reconstruction",
    requiredChoicesSeed: {
      screenplay: ["anniversary_commission_historical_reconstruction", "alexandrov_eisenstein_structure", "event_vs_representation_boundary"],
      camera: ["mass_staging_and_symbolic_objects", "resemblance_casting_not_newsreel", "bridge_palace_crowd_coverage"],
      editing: ["intellectual_montage_symbolic_series", "temporal_reconstruction", "trotsky_recut_version_control"],
      sound: ["silent_1928_object", "later_scores_separate", "no_newsreel_sound_fabrication"],
      themes: ["film_history", "soviet_montage", "eisenstein", "october_revolution", "intellectual_montage", "propaganda"],
    },
    learningGoals: [
      "Separate historical reconstruction from documentary evidence even when later viewers mistake staged sequences for newsreel footage.",
      "Use intellectual montage to construct abstract political relations through objects and shot series without treating symbolism as automatically persuasive.",
      "Coordinate Eisenstein and Aleksandrov's documented collaboration, crowds, casting and logistics rather than reducing the production to editing theory alone.",
      "Track political recutting and the removal of Trotsky material as version history rather than silently treating every print as the same object.",
      "Keep mass political violence analytical and staged; gameplay must not reward real-world dangerous crowd action or falsified historical evidence.",
      "Distinguish the 103-minute MoMA presentation from longer BFI runtime records as evidence of version/presentation variation.",
    ],
    phases: [
      { id: "pitch", label: "Tenth-anniversary historical reconstruction", player_task: "Define the commission's political purpose and the evidence boundary between reenactment, symbolic montage and historical record." },
      { id: "research", label: "Revolution, commission and versions", player_task: "Ground the 1917 events, anniversary commission, Eisenstein/Aleksandrov authorship, recutting and surviving presentation states." },
      { id: "screenplay", label: "History organized for montage", player_task: "Select events and symbolic motifs while clearly marking compression, reenactment and interpretive construction." },
      { id: "casting", label: "Resemblance without fake authenticity", player_task: "Use nonprofessional or resemblance casting as staged representation and never label performers as documentary footage of historical figures." },
      { id: "production_design", label: "Petrograd reconstruction", player_task: "Coordinate public spaces, symbols and crowd routes while distinguishing documented locations/sets from later myths about authenticity." },
      { id: "cinematography", label: "Crowd and object coverage", player_task: "Capture action, architecture and symbolic details so editorial relations remain legible without unsafe crowd practices." },
      { id: "editing", label: "Intellectual montage and political recut", player_task: "Build symbolic series and event compression, then track censorship/political removals as explicit version changes." },
      { id: "sound", label: "Silent production boundary", player_task: "Keep the 1928 film silent and treat later scores/presentation tracks separately." },
      { id: "release", label: "Commission, formalism and afterlife", player_task: "Model the tension between state commission, accusations of formalism, recutting and later canonization without collapsing them into one reception moment." },
    ],
  },
  {
    id: "scenario_mr_west_bolsheviks_1924",
    title: "The Extraordinary Adventures of Mr. West in the Land of the Bolsheviks",
    originalTitle: "Neobychainye priklyucheniya mistera Vesta v strane bolshevikov",
    aliases: ["Mr. West in the Land of the Bolsheviks", "The Extraordinary Adventures of Mr West in the Land of the Bolsheviks"],
    year: 1924,
    titleType: "Feature",
    runtimeMins: 94,
    directors: ["Lev Kuleshov"],
    genres: ["Comedy", "Satire"],
    premise: "Build Mr. West as a 1924 Kuleshov-workshop production in which Soviet filmmakers learn through American serial and slapstick forms while turning those forms into political satire. Porfiri Podobed and Boris Barnet anchor a deliberately physical performance system; Vsevolod Pudovkin appears as the thief Zhban. The production problem is constructive editing, screen geography, rhythmic physical action and genre quotation—not a laboratory demonstration in which the so-called Kuleshov effect automatically produces one universal audience response.",
    sourceId: "manual_mr_west_1924",
    sourceUrl: "https://harvardfilmarchive.org/calendar/the-extraordinary-adventures-of-mr-west-in-the-land-of-the-bolsh",
    scenarioType: "kuleshov_workshop_constructive_genre_satire_production",
    requiredChoicesSeed: {
      screenplay: ["american_serial_parody", "west_jeddy_satire_arc", "genre_borrowing_and_political_context"],
      camera: ["constructive_geography_fragments", "physical_action_legibility", "workshop_resource_economy"],
      editing: ["kuleshov_constructive_linkage", "action_space_from_separate_shots", "comedy_rhythm_and_satire"],
      sound: ["silent_1924_production", "live_piano_presentation_separate", "no_sync_dialogue_claim"],
      themes: ["film_history", "soviet_montage", "kuleshov", "workshop_pedagogy", "genre_exchange", "satire"],
    },
    learningGoals: [
      "Turn the Kuleshov workshop into a practical production problem in constructive geography, performance and editing rather than a mythical one-experiment origin story.",
      "Use American serial/slapstick borrowing as transnational genre exchange and satire, not as evidence that Soviet montage developed in isolation.",
      "Coordinate Podobed, Barnet and Pudovkin's physical performances with shot construction so action remains readable across separately photographed fragments.",
      "Treat the Kuleshov effect as a historically influential but contested account of editing and viewer inference, never as a guaranteed psychological formula.",
      "Preserve political satire and later censorship/reception context without turning propaganda agreement into a gameplay success metric.",
      "Keep Harvard's 94-minute silent presentation and live accompaniment as presentation evidence rather than original synchronized sound.",
    ],
    phases: [
      { id: "pitch", label: "Workshop genre-satire pitch", player_task: "Define how American-style action/comedy can be borrowed, transformed and satirized inside a Soviet production rather than copied as neutral form." },
      { id: "research", label: "Kuleshov workshop and genre evidence", player_task: "Ground the workshop, cast, silent format, American-cinema influence and political reception in institutional sources." },
      { id: "screenplay", label: "Satire through genre expectations", player_task: "Build West and Jeddy's assumptions into a comic causal structure where stereotypes can be exposed rather than merely repeated." },
      { id: "casting", label: "Physical ensemble precision", player_task: "Coordinate Podobed, Barnet, Pudovkin and ensemble action so separately framed movement can be reassembled cleanly in editing." },
      { id: "production_design", label: "Constructed Moscow geography", player_task: "Plan readable spaces and props that support serial parody without inventing unsupported claims about exact workshop sets." },
      { id: "cinematography", label: "Fragments for constructive editing", player_task: "Photograph entrances, exits, glances, movement directions and action details so coherent screen space can be built across cuts." },
      { id: "editing", label: "Constructive montage and comedy rhythm", player_task: "Create screen geography and comic timing from linked shots while avoiding claims that every juxtaposition produces a fixed viewer response." },
      { id: "sound", label: "Silent film and live presentation", player_task: "Keep production silent and separate modern/live accompaniment from original-image production." },
      { id: "release", label: "Popularity, satire and censorship", player_task: "Treat contemporary popularity, political scrutiny and later canonization as separate reception contexts." },
    ],
  },
] as const;

export function mergeChapterNineSovietMontageExpansion(
  baseScenarios: readonly HistoricalFilmScenario[],
): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterNineSovietMontageExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) =>
      scenario.id === definition.id ||
      (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))),
    );
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_nine_soviet_montage_verified",
      source: {
        list_id: "manual_chapter_nine_soviet_montage_expansion_2026",
        position: nextPosition,
        imdb_id: definition.sourceId,
        url: definition.sourceUrl,
      },
      film: {
        title: definition.title,
        original_title: definition.originalTitle,
        year: definition.year,
        title_type: definition.titleType,
        runtime_mins: definition.runtimeMins,
        directors: definition.directors,
        genres: definition.genres,
        genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")),
        imdb_rating: 0,
        user_rating: 0,
      },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
