import assert from "node:assert/strict";
import test from "node:test";

import { chapterEighteenTheNewWorldExpansionDefinitions } from "./chapterEighteenTheNewWorldExpansion.js";

test("Chapter 18 materializes The New World as a source-first photochemical countercurrent production case", () => {
  assert.equal(chapterEighteenTheNewWorldExpansionDefinitions.length, 1);
  const film = chapterEighteenTheNewWorldExpansionDefinitions[0];
  assert.equal(film.id, "scenario_the_new_world_2005");
  assert.equal(film.year, 2005);
  assert.equal(film.runtimeMins, 135);
  assert.deepEqual(film.directors, ["Terrence Malick"]);
  assert.ok(film.scenarioType.includes("photochemical_countercurrent") && film.scenarioType.includes("anamorphic_35mm") && film.scenarioType.includes("selective_65mm"));
  assert.ok(film.scenarioType.includes("natural_light") && film.scenarioType.includes("deep_focus") && film.scenarioType.includes("multi_cut_editorial"));
  assert.ok(film.premise.includes("135-minute theatrical cut") && film.premise.includes("150-minute first cut") && film.premise.includes("172-minute extended cut"));
  assert.ok(film.premise.includes("Emmanuel Lubezki") && film.premise.includes("Jack Fisk") && film.premise.includes("Sarah Green"));
  assert.ok(film.premise.includes("predominantly anamorphic 35mm") && film.premise.includes("small amount of 65mm") && film.premise.includes("hyper-enhanced"));
  assert.ok(film.premise.includes("40mm and 50mm") && film.premise.includes("C- and E-Series") && film.premise.includes("T11-T16"));
  assert.ok(film.premise.includes("Vision2 200T 5217") && film.premise.includes("Vision2 500T 5218"));
  assert.ok(film.premise.includes("naturally lit") && film.premise.includes("handheld or Steadicam"));
  assert.ok(film.premise.includes("James and Chickahominy Rivers") && film.premise.includes("State of Virginia"));
  assert.ok(film.premise.includes("Jamestown") && film.premise.includes("Virginia Algonquian/Powhatan language"));
  assert.ok(film.premise.includes("35mm original camera negative") && film.premise.includes("65mm original camera negative") && film.premise.includes("restoration evidence"));
  assert.ok(film.premise.includes("exact 65mm shot count") && film.premise.includes("complete lens-by-shot map") && film.premise.includes("universal T-stop"));
  assert.ok(film.premise.includes("later Criterion restoration") && film.premise.includes("2005 finishing workflow"));
  assert.ok(film.requiredChoicesSeed.camera.includes("anamorphic_35mm_primary"));
  assert.ok(film.requiredChoicesSeed.camera.includes("selective_65mm"));
  assert.ok(film.requiredChoicesSeed.camera.includes("65mm_shot_count_unknown"));
  assert.ok(film.requiredChoicesSeed.editing.includes("135_theatrical_anchor"));
  assert.ok(film.requiredChoicesSeed.editing.includes("150_first_cut") && film.requiredChoicesSeed.editing.includes("172_extended_cut"));
  assert.ok(film.requiredChoicesSeed.editing.includes("restoration_not_2005_pipeline"));
  assert.ok(film.learningGoals.some((goal) => goal.includes("135-minute theatrical cut") && goal.includes("150-minute first cut") && goal.includes("172-minute extended cut")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("photochemical countercurrent") && goal.includes("digital-convergence")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("anamorphic 35mm") && goal.includes("predominant capture")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("small amount of 65mm") && goal.includes("hyper-enhanced")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("exact number") && goal.includes("65mm shots") && goal.includes("unresolved")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("40mm and 50mm") && goal.includes("lens-by-shot")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("close-focus") && goal.includes("C- and E-Series")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("T11-T16") && goal.includes("universal per-shot")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Vision2 200T 5217") && goal.includes("Vision2 500T 5218")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("natural-light") && goal.includes("absolute no-artificial-light")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("handheld and Steadicam") && goal.includes("rig assignment")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("James and Chickahominy Rivers") && goal.includes("historical-location")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("State of Virginia") && goal.includes("incentive amount")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Jamestown") && goal.includes("research-driven physical production design")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Virginia Algonquian/Powhatan") && goal.includes("historical completeness")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Native and First Nations casting") && goal.includes("cultural detail")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("CIS Hollywood") && goal.includes("shot count") && goal.includes("software stack")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Criterion 4K restoration") && goal.includes("2005 production")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("35mm original negative") && goal.includes("65mm original negative")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("four editors") && goal.includes("continuing recutting")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("James Horner") && goal.includes("Wagner") && goal.includes("Mozart")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("uncertainty register") && goal.includes("65mm shot count") && goal.includes("2005 finishing settings")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Chapter 18 significance") && goal.includes("boundary case")));
  assert.ok(film.phases.find((phase) => phase.id === "version_anchor")?.player_task.includes("135-minute"));
  assert.ok(film.phases.find((phase) => phase.id === "selective_65mm")?.player_task.includes("hyper-enhanced"));
  assert.ok(film.phases.find((phase) => phase.id === "deep_focus")?.player_task.includes("T11-T16"));
  assert.ok(film.phases.find((phase) => phase.id === "natural_light")?.player_task.includes("no-artificial-light"));
  assert.ok(film.phases.find((phase) => phase.id === "language_reconstruction")?.player_task.includes("historical completeness"));
  assert.ok(film.phases.find((phase) => phase.id === "restoration_boundary")?.player_task.includes("2005 capture or finishing workflow"));
  assert.ok(film.phases.find((phase) => phase.id === "unknowns_register")?.player_task.includes("65mm shot count"));
  assert.ok(film.learningGoals.length >= 55);
  assert.ok(film.phases.length >= 35);
});
