import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterEighteenTheRevenantExpansionDefinitions = [
  {
    id: "scenario_the_revenant_2015",
    title: "The Revenant",
    originalTitle: "The Revenant",
    aliases: [],
    year: 2015,
    titleType: "Movie",
    runtimeMins: 156,
    directors: ["Alejandro González Iñárritu"],
    genres: ["Adventure", "Drama", "Western"],
    sourceId: "bfi_the_revenant_2015",
    sourceUrl: "https://www.bfi.org.uk/film/cecebfa8-c26d-587f-8de7-b34f52b21086/the-revenant",
    scenarioType: "digital_large_format_natural_light_remote_location_alexa_m_alexa_xt_alexa_65_master_prime_prime65_long_take_chronological_vfx_survival_2015",
    premise: "Build The Revenant as a source-first Chapter 18 Production Case about how a remote-location survival epic joined digital large-format capture, natural-light scheduling, long-take choreography, historically grounded design, dangerous physical action, invisible VFX, editorial preplanning and immersive sound into one production system. BFI anchors the released feature at 156 minutes and credits Alejandro González Iñárritu as director, Mark L. Smith and Iñárritu as writers, Emmanuel Lubezki as cinematographer, Stephen Mirrione as editor, Jack Fisk as production designer, and Arnon Milchan, Steve Golin, Iñárritu, Mary Parent, Keith Redmon and James Skotchdopole as producers. ARRI documents ALEXA XT, ALEXA M and ALEXA 65 use, with Master Primes and Prime 65 lenses, and explicitly limits ALEXA 65 to selected/significant portions rather than the whole film. American Cinematographer documents chronological shooting, natural light and period-correct firelight as the governing aesthetic, a short northern-winter daylight window, and the later move to Argentina when warm weather reduced usable snow. British Cinematographer records that film acquisition was tested and then abandoned in favor of digital, with the ALEXA M favored for handheld work and the ALEXA XT used for Steadicam, while also preserving Lubezki's distinction between the overwhelming natural-light strategy and specific controlled exceptions around firelight. The Society of Camera Operators describes the camera language as handheld, Steadicam and crane/dolly movement organized around a single-perspective immersive grammar rather than coverage-first shooting. ILM documents the bear attack as a six-minute continuous-seeming sequence built from multiple plates and performances over several days, with a digital bear, cubs, wounds, blood, scars, weather and environment work integrated invisibly into naturalistic plates. MPC separately documents the opening attack as more than 100 photographed elements reduced to 39 extended shots through stitching, retiming, 2.5D projection, sky replacement, CG arrows, horses, smoke, fire and mud, demonstrating that apparent real-time continuity required substantial post-production construction. Stephen Mirrione's Post Magazine account places editorial in production planning and on location, with rehearsal/video-tap material used to test rhythm and with major VFX sequences locked and turned over while principal photography was still underway. Jack Fisk's production-design interviews describe research in period journals and Karl Bodmer paintings, extensive location scouting, real local materials and sets built to withstand wide-angle scrutiny, making design, geography and historical texture operational rather than decorative. BAFTA records the winning sound team including Lon Bender, Chris Duesterdiek, Martín Hernández, Frank A. Montaño, Jon Taylor and Randy Thom; Iñárritu separately describes sound and music as a major narrative layer and identifies Hernández as a longstanding sound collaborator. The player must coordinate remote-location logistics, chronological continuity, weather and snow risk, natural-light windows, cold-weather camera support, wide-lens blocking, handheld/Steadicam/crane choreography, performance and stunt safety, animal/VFX plate strategy, production design, costume continuity, editorial turnover, VFX vendor ownership, soundscape and music while refusing unsupported exact total budget, exact shooting-day count, exact percentage of ALEXA 65 footage, universal lens-per-shot maps, universal exposure settings, exact ARRIRAW/Codex media configuration, complete artificial-light inventory, exact stunt rig geometry, exact bear-animation software stack, complete VFX shot count across all vendors, exact production-sound recorder/microphone chain, exact DI node graph or an invented single technical ratio where sources vary.",
    requiredChoicesSeed: {
      screenplay: ["survival_structure", "historical_period_world", "chronological_continuity", "long_take_storytelling", "environment_character_link"],
      camera: ["alexa_m", "alexa_xt", "alexa_65_selected", "master_primes", "prime65", "natural_light_windows", "wide_lens_proximity", "handheld_steadicam_crane"],
      editing: ["stephen_mirrione", "rehearsal_video_tap", "vfx_early_turnover", "hidden_stitches", "long_take_rhythm", "vendor_version_control"],
      sound: ["martin_hernandez", "lon_bender", "randy_thom", "location_world", "sound_music_interplay", "production_sound_equipment_unknowns"],
      themes: ["film_history", "2015", "the_revenant", "alejandro_gonzalez_inarritu", "emmanuel_lubezki", "digital_convergence", "alexa_m", "alexa_xt", "alexa_65", "natural_light", "remote_locations", "canada", "argentina", "chronological_shoot", "long_takes", "jack_fisk", "production_design", "survival", "stunts", "ilm", "mpc", "invisible_vfx", "sound_design"]
    },
    learningGoals: [
      "Explain The Revenant as a coordinated location, camera, performance, design, editorial, VFX, sound and logistics system rather than only as an endurance story or cinematography showcase.",
      "Use BFI's 156-minute record as the canonical runtime anchor while keeping alternate catalogue timing metadata separate if encountered.",
      "Identify Alejandro González Iñárritu as director and co-writer with Mark L. Smith while separating directing authorship from cinematography, editing, design, VFX and sound ownership.",
      "Identify Arnon Milchan, Steve Golin, Alejandro González Iñárritu, Mary Parent, Keith Redmon and James Skotchdopole as BFI-listed producers without inventing their individual financing shares.",
      "Treat the 1820s frontier setting as a research, location, design, costume, prop, performance and sound coordination problem rather than as scenery alone.",
      "Explain how chronological shooting tied seasonal progression, actor condition, costume wear, set state and environmental continuity together.",
      "Explain why chronological intent does not prove every individual insert or pickup was photographed in story order.",
      "Identify Emmanuel Lubezki as cinematographer and keep camera-department roles distinct from directing and VFX authorship.",
      "Identify ALEXA M and ALEXA XT as documented principal digital camera bodies used for different operating needs.",
      "Identify ALEXA 65 as a documented large-format camera used for selected or significant portions rather than claiming the entire feature was photographed with it.",
      "Preserve conflicting published estimates of the exact ALEXA 65 percentage as source variance unless a primary production record resolves them.",
      "Identify Master Primes as a documented lens family and Prime 65 lenses as documented ALEXA 65 optics while refusing a universal shot-to-lens map.",
      "Explain why very wide lenses could preserve environmental context while moving the camera physically close to performers.",
      "Separate field of view from format labels so a focal length is not treated as equivalent across ALEXA M/XT and ALEXA 65.",
      "Explain why the production tested film acquisition and ultimately committed to digital for low-light sensitivity and the desired clean image.",
      "Treat the film-versus-digital decision as a tested production choice rather than a generic claim that digital is always superior to film.",
      "Explain the natural-light strategy as a scheduling and location constraint, not merely a visual preference.",
      "Use the short winter daylight window as evidence that call times, rehearsal, blocking and camera readiness had to converge before the usable light arrived.",
      "Explain why unseasonably warm conditions and insufficient snow forced a geographic production response rather than being solved only in post.",
      "Identify Canada and Argentina as documented major location regions while avoiding unsupported claims that every scene was shot in one country.",
      "Explain how remote locations increase transport, safety, battery, monitor, cable, shelter, backup and emergency-planning dependencies.",
      "Use ARRI's cold-weather account to distinguish camera-body resilience from failures or degradation in monitors, cables and battery duration.",
      "Describe natural light and period-correct firelight as the governing aesthetic while preserving documented controlled-light exceptions instead of claiming literally zero artificial light.",
      "Explain why firelight continuity can require controlled augmentation even inside a naturalistic lighting philosophy.",
      "Distinguish lighting intention from exact exposure: natural-light testimony does not prove one EI, stop, shutter or white-balance setting across the film.",
      "Explain how wardrobe value and texture interact with faces and natural-light exposure without inventing exact fabric recipes.",
      "Identify Jack Fisk as production designer and connect design choices to wide-angle scrutiny, historical research and real environmental materials.",
      "Use period journals and Karl Bodmer paintings as documented design research rather than as evidence that every object exactly reproduces a single historical source.",
      "Explain why sets built from local wood, mud and other real materials can reduce the visual seam between construction and location.",
      "Treat location scouting as continuity design: distinct landscapes must read as a coherent journey without collapsing into visually repetitive terrain.",
      "Explain why long-take choreography transfers decisions from the edit room into rehearsal, blocking, stunt timing, camera movement and VFX planning.",
      "Distinguish the immersive long-take grammar from an assertion that the entire film is composed only of unbroken takes.",
      "Identify handheld, Steadicam and crane/dolly movement as documented operating modes and explain how each changes rehearsal, grip, safety and spatial continuity.",
      "Explain why a single-perspective camera grammar can still contain hidden stitches, multiple plates and editorial construction.",
      "Identify Stephen Mirrione as editor and explain why editorial involvement during preproduction and principal photography was essential to long-take and VFX planning.",
      "Explain how rehearsal/video-tap material could be edited before final photography to test rhythm, point of view and shot construction.",
      "Explain why major VFX sequences had to be locked and turned over while shooting continued, creating schedule dependencies between production and post.",
      "Identify ILM's bear attack work as a synthesis of digital animal animation, multiple plates, performer/stunt work, wounds, blood, scars and environment integration.",
      "Preserve the bear attack as a continuous-seeming six-minute sequence without pretending it was one untreated camera take.",
      "Explain why real bear reference can inform animation without requiring a live attacking bear on set.",
      "Use the bear sequence to distinguish stunt-performer interaction, plate photography and final CG animal animation as separate safety and VFX layers.",
      "Identify MPC's opening-sequence work as extensive stitching and reconstruction rather than assuming the apparent real-time attack was captured as a single uninterrupted photograph.",
      "Use MPC's documented reduction of more than 100 photographed elements to 39 extended shots as title-specific evidence, not a template for the whole film.",
      "Identify 2.5D projection, retiming, sky replacement, CG arrows, horses, smoke, fire and mud as documented opening-sequence tools while keeping vendor-specific boundaries explicit.",
      "Maintain VFX vendor ownership and version control so ILM bear work and MPC opening-sequence work are not flattened into one generic pipeline.",
      "Explain why matching changing natural light across VFX plates is both a cinematography and compositing problem.",
      "Explain why dangerous action requires stunt rehearsal, performer boundaries, medical planning and camera paths to be designed together.",
      "Keep exact stunt rigging, harness geometry and injury-prevention procedures unresolved unless title-specific records establish them.",
      "Identify the BAFTA-recorded sound team including Lon Bender, Chris Duesterdiek, Martín Hernández, Frank A. Montaño, Jon Taylor and Randy Thom as distinct credited contributors.",
      "Explain Iñárritu's emphasis on sound as narrative evidence while separating production recording, sound editing/design and rerecording ownership.",
      "Treat wind, water, fire, breath, weapons, animals and environmental silence as production and post sound layers rather than assuming location recording alone produced the final soundscape.",
      "Keep exact production microphones, recorders, radio systems, track layouts and ADR workflow unresolved unless stronger title-specific sources are recovered.",
      "Keep exact music recording, stem layout and final mix architecture bounded while recognizing Ryuichi Sakamoto and Alva Noto as central score collaborators in documented contemporary coverage.",
      "Distinguish awards and later reception from production evidence: cinematography or sound prizes do not prove a camera percentage, lens choice or technical setup.",
      "Maintain an uncertainty register for exact total budget, shooting-day count, ALEXA 65 percentage, complete lens inventory, shot-lens allocation, exposure values, recording media, full lighting inventory, stunt rigging, VFX software stack, sound hardware and DI settings.",
      "Explain The Revenant's Chapter 18 significance as a case where digital convergence enabled a production to pursue environmental realism, low-light shooting and invisible VFX while retaining large-scale physical production.",
      "Contrast the use of new ALEXA 65 technology with the film's historical setting so technological novelty is not confused with a visibly futuristic aesthetic.",
      "Build a closing production audit that checks runtime provenance, camera-format boundaries, natural-light exceptions, weather/location continuity, chronological scheduling, design evidence, long-take rehearsal, VFX vendor ownership, editorial turnovers, stunt safety and sound provenance before verification."
    ],
    phases: [
      { id: "evidence_hierarchy", label: "Map the Revenant evidence hierarchy", player_task: "Separate BFI catalogue facts, ARRI/ASC/Lubezki camera testimony, camera-operator accounts, vendor VFX records, editor interviews, design interviews and awards metadata before promoting claims." },
      { id: "released_version", label: "Lock the 156-minute version", player_task: "Use the BFI 156-minute record as the canonical runtime anchor and record alternate catalogue timings only as version metadata." },
      { id: "producer_map", label: "Map producer ownership", player_task: "Preserve the BFI-listed producer group while keeping exact financing shares and individual executive decisions unresolved." },
      { id: "period_research", label: "Build the 1820s research base", player_task: "Coordinate journals, visual research, Indigenous/frontier context, props, costume, weapons, transport and sound without treating one reference source as total history." },
      { id: "chronological_schedule", label: "Plan chronological production", player_task: "Tie seasonal progression, wardrobe wear, wounds, hair, set state and performance condition to a story-order plan while leaving room for bounded pickups." },
      { id: "location_map", label: "Map remote locations", player_task: "Track Canada and Argentina locations, travel paths, access, basecamp, shelter, communications and rescue contingencies as production dependencies." },
      { id: "snow_contingency", label: "Manage snow and weather continuity", player_task: "Treat changing snow and temperature as schedule risks with relocation and continuity responses rather than assuming post can replace every environmental condition." },
      { id: "daylight_window", label: "Protect the winter light window", player_task: "Schedule rehearsal, blocking, camera prep and actor readiness before the short usable natural-light period begins." },
      { id: "film_digital_tests", label: "Resolve film versus digital", player_task: "Use tested low-light performance and aesthetic results to justify the documented move away from planned film acquisition toward digital." },
      { id: "alexa_m", label: "Configure ALEXA M handheld work", player_task: "Use the documented ALEXA M for lightweight close operating while keeping unsupported rig and media details outside the locked layer." },
      { id: "alexa_xt", label: "Configure ALEXA XT movement work", player_task: "Use the documented ALEXA XT for Steadicam and related operating needs without inventing a universal body assignment for every shot." },
      { id: "alexa_65", label: "Deploy ALEXA 65 selectively", player_task: "Use ALEXA 65 for documented selected/significant portions and preserve published percentage disagreement rather than asserting one exact share." },
      { id: "lens_package", label: "Build wide-lens packages", player_task: "Use Master Primes and Prime 65 as documented families while keeping complete focal-length inventory and per-shot allocation provisional." },
      { id: "format_translation", label: "Translate field of view across formats", player_task: "Compare wide-angle intent across M/XT and 65 formats without equating focal-length numbers across different image areas." },
      { id: "natural_light", label: "Stage for natural light", player_task: "Rehearse camera and performance around real sky direction, reflection, terrain and time-of-day changes rather than lighting after blocking is fixed." },
      { id: "firelight_exception", label: "Control firelight exceptions", player_task: "Preserve period-correct fire as the motivation while allowing the documented controlled cushion-light solution when wind makes raw flicker unusable." },
      { id: "exposure_boundaries", label: "Bound exposure claims", player_task: "Do not infer one EI, stop, shutter, filter, white balance or dimmer setting for the whole feature from the natural-light strategy." },
      { id: "cold_weather_camera", label: "Protect cold-weather camera systems", player_task: "Separate camera-body performance from monitor, cable and battery vulnerabilities and build warming, charging and redundancy plans accordingly." },
      { id: "wardrobe_light", label: "Coordinate wardrobe with exposure", player_task: "Test costume value, texture and face separation under actual natural-light conditions without inventing undocumented fabric formulas." },
      { id: "production_design", label: "Build historically grounded environments", player_task: "Use Fisk's research and real-material approach so forts, camps and villages withstand wide-angle proximity and integrate with the location." },
      { id: "distinct_landscapes", label: "Differentiate journey geography", player_task: "Select mountains, forests, rivers and snowfields that remain distinct on screen while maintaining believable geographic continuity." },
      { id: "long_take_previs", label: "Preplan long-take point of view", player_task: "Define audience position, action beats, camera path, stunt zones and VFX stitch opportunities before final photography." },
      { id: "handheld", label: "Rehearse handheld immersion", player_task: "Coordinate performer proximity, operator path, focus, terrain and safety for ALEXA M handheld sequences." },
      { id: "steadicam", label: "Rehearse Steadicam passages", player_task: "Map actor and operator movement, transitions and handoffs so Steadicam remains integrated with the single-perspective grammar." },
      { id: "crane_dolly", label: "Integrate crane and dolly movement", player_task: "Use cranes or dolly movement where geography and action demand scale while maintaining continuity with handheld and Steadicam language." },
      { id: "stunt_rehearsal", label: "Lock stunt and performer safety", player_task: "Rehearse horses, weapons, falls, water, combat and terrain with protected performer boundaries before the narrow light window forces shooting." },
      { id: "bear_plate_strategy", label: "Build the bear sequence plates", player_task: "Separate DiCaprio/stunt performance, environmental plates, digital bear animation and wound/environment work while planning hidden transitions across the continuous-seeming sequence." },
      { id: "bear_reference", label: "Ground digital animal behavior", player_task: "Use real-animal reference for weight and behavior while keeping live dangerous-animal interaction outside the performance plan." },
      { id: "opening_vfx", label: "Construct the opening attack", player_task: "Track MPC's documented photographed elements, hidden stitches, 2.5D work, retiming, sky replacements and CG additions as one vendor-owned sequence pipeline." },
      { id: "vfx_vendor_map", label: "Separate VFX vendor ownership", player_task: "Keep ILM bear/environment work and MPC opening-sequence work traceable by shot and version rather than merging them into generic VFX." },
      { id: "natural_light_vfx", label: "Match changing natural-light plates", player_task: "Coordinate capture timing, reference, plate continuity and compositing so invisible VFX respects the photographed environment." },
      { id: "editor_on_location", label: "Integrate editorial during production", player_task: "Give Mirrione access to rehearsal/video-tap and photographed material so rhythm, point of view and transition problems are discovered before locations are lost." },
      { id: "early_vfx_turnover", label: "Turn over VFX early", player_task: "Lock major effects sequences early enough for vendor work while preserving change control and avoiding irreversible editorial dead ends." },
      { id: "sound_world", label: "Build the environmental sound system", player_task: "Separate production dialogue/effects capture from designed wind, water, weapons, animals, breath, fire and silence in post." },
      { id: "sound_ownership", label: "Map sound ownership", player_task: "Keep Lon Bender, Chris Duesterdiek, Martín Hernández, Frank A. Montaño, Jon Taylor and Randy Thom in distinct credited sound roles without inventing missing equipment details." },
      { id: "music_sound_boundary", label: "Coordinate score and sound design", player_task: "Treat Sakamoto/Alva Noto music, environmental sound, silence and rerecording as separate layers that can interact without collapsing authorship." },
      { id: "unknowns_register", label: "Maintain the Revenant unknowns register", player_task: "Track exact budget, shooting days, ALEXA 65 percentage, full lens map, exposure values, recording media, artificial-light inventory, stunt rigging, VFX software, sound hardware and DI settings explicitly." },
      { id: "chapter18_position", label: "Position The Revenant in digital convergence", player_task: "Explain how digital low-light capture, large format and invisible VFX supported a deliberately physical, historical and location-bound production rather than replacing physical production." },
      { id: "delivery_review", label: "Audit the complete Revenant production system", player_task: "Verify runtime provenance, camera boundaries, natural-light exceptions, weather/location continuity, chronological scheduling, design, long-take rehearsal, stunt safety, VFX ownership, editorial turnovers and sound evidence before closure." }
    ]
  }
] as const;

export function mergeChapterEighteenTheRevenantExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterEighteenTheRevenantExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_eighteen_the_revenant_verified",
      source: { list_id: "manual_chapter_eighteen_the_revenant_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}