import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterEighteenBrokebackMountainExpansionDefinitions = [
  {
    id: "scenario_brokeback_mountain_2005",
    title: "Brokeback Mountain",
    originalTitle: "Brokeback Mountain",
    year: 2005,
    titleType: "Movie",
    runtimeMins: 134,
    directors: ["Ang Lee"],
    genres: ["Drama", "Romance"],
    sourceId: "afi_brokeback_mountain_2005",
    sourceUrl: "https://catalog.afi.com/Catalog/moviedetails/54466",
    scenarioType: "us_independent_alberta_location_35mm_spherical_period_western_naturalistic_design_costume_aging_sparse_score_2005",
    premise: "Build Brokeback Mountain as Chapter 18's next P1 Production Case by treating its intimacy and landscape as the result of a tightly coordinated, modestly budgeted 2004 production rather than as an abstract prestige-Western look. The American Film Institute records the finished film at 134 minutes, directed by Ang Lee, written by Larry McMurtry and Diana Ossana from Annie Proulx's short story, produced by Ossana and James Schamus, photographed by Rodrigo Prieto, edited by Geraldine Peroni and Dylan Tichenor, designed by Judy Becker and scored by Gustavo Santaolalla. AFI records a production period from 24 May to early August 2004 and identifies Alberta locations including the Canadian Rockies, Cowley, Fort MacLeod and Calgary, even though the story is set primarily in Wyoming and Texas. That location substitution must be explicit: production geography is not story geography. Focus Features' original EPK interviews document an unusually long development path. Ossana and McMurtry optioned Proulx's story with their own money in 1997 and completed a screenplay that year; Ossana says they spent nearly seven years trying to get the film made before Focus, Ang Lee and James Schamus fully committed in late 2003. The adaptation exercise therefore separates literary source, screenplay development, financing persistence and eventual production greenlight rather than compressing them into one authorship event. Lee chose younger actors partly because the story spans roughly twenty years and youth is difficult to recreate; performance aging was treated as a combined system of makeup, wardrobe, voice, movement and behavior rather than a makeup-only effect. Dialect coach Joy Ellison and the performers researched Wyoming and Montana speech, while Lee, production designer Judy Becker and costume designer Marit Allen researched the American West through Wyoming and Texas visits and photographic references including Richard Avedon's Photographs of the American West. Becker describes a naturalistic design strategy in which period is signaled subtly rather than by obvious date markers. She and Lee wanted towns to feel colorless and cluttered in contrast with the freer mountain spaces, but the production did not have resources to build large quantities of sets; existing apartments, diners and other locations were found and transformed. The 1967 supermarket required period-specific research into products, packaging, advertising and store appearance. Costume designer Marit Allen likewise tied clothes to economic circumstance and character: earth tones were used heavily for Ennis, jackets could remain closed as a form of repression, and hats became part of the performers' physical behavior. The Production Case should therefore model design, costume and performance as interacting continuity systems across two decades. Cinematography is equally specific. Prieto and Lee wanted a tranquil, almost passive visual style rather than the frenetic camera movement associated with some of Prieto's earlier work. Prieto later explained that Brokeback Mountain was photographed in 1.85:1 to preserve the height of the mountains. American Cinematographer's January 2006 production account documents a 35mm Arricam package with Cooke S4 primes and a film-stock strategy that differentiated mountain, town, night and Texas material: Eastman EXR 50D 5245 for many day mountain scenes, Kodak Vision 250D 5246 for towns and some dusk/dawn material, Vision2 500T 5218 for most night material, and Vision 500T 5279 for Texas night material where Prieto wanted more saturation and contrast. A separate American Cinematographer interview conducted while Prieto was finishing Alexander records him saying that Brokeback Mountain would not use a digital intermediate because the controlled shoot did not require one. This establishes a 35mm photochemical-origin and largely photochemical finishing model, but it does not license claims that no digital work existed: Lee later stated that some CGI was used in landscapes, for example to place clouds, and BFI credits Buzz Image Group for visual effects plus Cine-BYTE Imaging for digital opticals. The exercise must therefore keep original photography, color timing, optical work, digital opticals, selective landscape VFX and exhibition prints as distinct stages. Location production generated its own constraints. Focus records filming beginning in Alberta in May 2004, with the Canadian Rockies, Cowley, Fort MacLeod and Calgary used as principal regions. Members of the Calgary Gay Rodeo Association advised the production and appeared in several sequences. Gyllenhaal describes arriving a month early for cowboy training in riding, sheep handling and other ranch tasks, while Lee describes the cast using physical training to build comfort and chemistry. Ossana says roughly 80 percent of the picture was exterior work and that weather could change within fifteen minutes; Lee recalls sleet, hail, persistent cold and mountains that could not be controlled, while co-producer Scott Ferguson describes long drives or hikes while moving substantial gear. These are production-logistics facts, not instructions to recreate historical hazards. Sound and music are also departmental systems. AFI and BFI credit Drew Kunin as production sound mixer and Peter Melnychuk as boom operator, with separate sound editorial, ADR, rerecording and music personnel. Santaolalla's music is described by Lee as sparse, and Lee says Santaolalla sometimes wrote material when the production could not afford a desired song. That anecdote must be treated as a documented budget/creative tradeoff, not generalized into a claim that the whole score was cheap or improvised. Editing provenance also requires care. AFI and BFI credit both Geraldine Peroni and Dylan Tichenor; the film's credits memorialize Peroni, who died during the edit, and Tichenor completed the film. The case should preserve shared editing credit and the handoff without turning a personal tragedy into a stylistic explanation. Finally, reception and awards remain downstream. Venice, Academy and later canon status may explain circulation and legacy, but they cannot substitute for evidence about May-August 2004 production decisions. The player should be able to carry one scene from adaptation and period research through location selection, costume and performance aging, 35mm capture, weather-aware logistics, production sound, editorial handoff, selective VFX/opticals, photochemical finishing and sparse music while keeping production geography, story geography, later exhibition and reception in separate provenance layers.",
    requiredChoicesSeed: {
      screenplay: ["short_story_option", "1997_screenplay", "seven_year_development", "twenty_year_structure", "story_production_geography_boundary", "adaptation_provenance"],
      camera: ["35mm_origin", "one_eighty_five_frame", "cooke_s4_primes", "stock_by_story_world", "no_di_boundary", "selective_landscape_vfx", "second_unit_landscape"],
      editing: ["peroni_tichenor_shared_credit", "editorial_handoff", "period_transition_continuity", "opticals_vs_vfx", "photochemical_finish_boundary", "reception_not_production"],
      sound: ["production_sound_mixer", "boom_operation", "sound_editorial", "adr_pipeline", "rerecording_pipeline", "sparse_score", "song_budget_tradeoff"],
      themes: ["film_history", "2005", "brokeback_mountain", "ang_lee", "rodrigo_prieto", "judy_becker", "marit_allen", "geraldine_peroni", "dylan_tichenor", "gustavo_santaolalla", "alberta", "canadian_rockies", "cowley", "fort_macleod", "calgary", "wyoming_story_geography", "texas_story_geography", "134_minutes", "24_may_early_august_2004", "35mm", "1_85_1", "arricam", "cooke_s4", "5245", "5246", "5218", "5279", "no_digital_intermediate", "digital_opticals", "landscape_vfx", "naturalistic_design", "period_research", "costume_aging", "cowboy_training", "weather_logistics", "production_sound", "sparse_score"],
    },
    learningGoals: [
      "Explain Brokeback Mountain as a coordinated 2004 production system rather than as an abstract prestige-Western aesthetic.",
      "Identify Ang Lee as director, Larry McMurtry and Diana Ossana as screenwriters, and Annie Proulx's short story as the literary source.",
      "Record AFI's 134-minute runtime as the canonical playable runtime anchor.",
      "Record the AFI production period as 24 May to early August 2004 rather than inferring schedule from release dates.",
      "Separate the film's Wyoming and Texas story geography from its Alberta production geography.",
      "Identify the Canadian Rockies, Cowley, Fort MacLeod and Calgary as documented Alberta production locations.",
      "Explain how Ossana and McMurtry optioned the story with their own money in 1997 and completed a screenplay that year.",
      "Explain the nearly seven-year development period without converting persistence into a claim that no studios or producers ever showed interest.",
      "Keep Focus/Ang Lee/James Schamus involvement in late 2003 separate from the earlier screenplay authorship.",
      "Explain why Lee chose younger actors partly to sustain a story spanning roughly twenty years.",
      "Treat aging as a combined system of makeup, wardrobe, voice, movement and behavior rather than makeup alone.",
      "Explain dialect and regional research as part of performance preparation without turning coached speech into documentary proof of every Wyoming or Texas accent.",
      "Identify Richard Avedon's Photographs of the American West as one documented visual research reference shared across costume, cinematography and direction.",
      "Explain Judy Becker's naturalistic production-design strategy and her rejection of obvious period-signposting props.",
      "Explain the intended contrast between freer mountain spaces and colorless, cluttered towns.",
      "Explain why limited set-building resources increased the importance of finding and transforming existing apartments, diners and other locations.",
      "Use the 1967 supermarket example to model period research into products, labels, advertising and store appearance.",
      "Explain how small-town architecture was researched across Wyoming and Texas rather than assumed from generic Western imagery.",
      "Identify Marit Allen as costume designer and explain her use of economic circumstance as a costume constraint.",
      "Explain the earth-tone strategy for Ennis without pretending every garment in every scene follows one palette rule.",
      "Explain how closed jackets and cowboy hats became performance-linked costume choices for Ennis.",
      "Identify Rodrigo Prieto as cinematographer and explain Lee's request for a tranquil, almost passive visual approach.",
      "Record 1.85:1 as the documented aspect-ratio choice connected to preserving mountain height.",
      "Record the 35mm Arricam and Cooke S4 production package as documented by the American Cinematographer production account.",
      "Distinguish Eastman EXR 50D 5245 mountain-day use from Kodak Vision 250D 5246 town and dusk/dawn use.",
      "Distinguish Vision2 500T 5218 for most night work from Vision 500T 5279 for Texas night material.",
      "Explain film-stock changes as scene-specific image design rather than a claim that one stock equals one emotion mechanically.",
      "Explain Prieto's documented decision not to use a digital intermediate while keeping other digital optical and VFX work visible.",
      "Reject the false inference that no DI means no digital intervention anywhere in the film.",
      "Identify Buzz Image Group visual effects and Cine-BYTE digital opticals as distinct post-production credits.",
      "Explain Lee's statement that CGI was used selectively in landscapes, including cloud placement, without inventing shot counts or software.",
      "Keep photochemical color timing, digital opticals, landscape VFX and later digital restoration/exhibition as separate provenance layers.",
      "Explain the Calgary Gay Rodeo Association's advisory and on-screen participation without treating one association as representative of all Western ranch culture.",
      "Explain cowboy training as actor preparation in riding, sheep handling and ranch tasks rather than as evidence that performers did every hazardous action themselves.",
      "Model roughly 80 percent exterior work as a logistics constraint involving weather, daylight, travel and equipment movement.",
      "Record the documented sleet, hail, cold and rapidly changing weather without turning historical production hardship into present-day safety instruction.",
      "Explain long drives and hikes with equipment as a location-production constraint separate from image style.",
      "Identify Drew Kunin as production sound mixer and Peter Melnychuk as boom operator.",
      "Explain production sound, sound editorial, ADR and rerecording as separate handoffs.",
      "Identify Gustavo Santaolalla as composer and explain Lee's preference for sparse musical placement.",
      "Explain Lee's account that Santaolalla sometimes wrote material when the production could not afford a desired song as a documented budget/creative tradeoff.",
      "Keep source-song licensing and original-score composition as different production decisions.",
      "Preserve Geraldine Peroni and Dylan Tichenor as the film's shared editing credits.",
      "Explain the editorial handoff after Peroni's death without using that personal event as an unsupported explanation for the film's style.",
      "Separate production evidence from Venice, Academy Awards and later canonical reputation.",
      "Reject claims that Brokeback Mountain invented queer Westerns, location realism, 35mm naturalism, restrained acting, sparse scoring or landscape symbolism.",
      "Audit every claim about exact exposure, filtration, lighting fixtures, camera-body allocation, stunt doubling, animal handling, budget totals, weather safety and shot-specific VFX against a title-specific source before promoting it to production fact.",
    ],
    phases: [
      { id: "evidence_hierarchy", label: "Map the evidence hierarchy", player_task: "Separate AFI production records, Focus EPK testimony, Ang Lee's DGA interview, American Cinematographer craft reporting and BFI compiled credits before converting any detail into production fact." },
      { id: "adaptation_option", label: "Trace the adaptation option", player_task: "Start with Ossana and McMurtry's 1997 option and screenplay, then keep later financing and greenlight history in a separate track." },
      { id: "development_timeline", label: "Map the development timeline", player_task: "Track the nearly seven-year path to production without inventing meetings, financing terms or rejected offers not established by the selected sources." },
      { id: "story_production_geography", label: "Separate story and production geography", player_task: "Map Wyoming and Texas as story locations while recording Alberta as the principal production geography." },
      { id: "location_research", label: "Research the West", player_task: "Use the documented Wyoming and Texas research trips, Avedon references and local observation to build a period-reference board rather than a generic Western preset." },
      { id: "period_design", label: "Build subtle period design", player_task: "Signal decade through architecture, products, labels, advertising, wear and clutter rather than obvious date-marker props." },
      { id: "location_transformation", label: "Transform found locations", player_task: "Work from existing apartments, diners and towns because the production could not build large quantities of sets, and record what art-direction changes each location needs." },
      { id: "supermarket_research", label: "Audit the 1967 supermarket", player_task: "Verify products, packaging, advertising and store layout for the period before dressing the scene." },
      { id: "costume_economics", label: "Map costume economics", player_task: "Link wear, color and wardrobe quantity to each character's economic situation without turning class into a one-color visual code." },
      { id: "costume_performance", label: "Integrate costume and performance", player_task: "Use Ennis's earth tones, closed jackets and hats as behavior-supporting choices while preserving actor movement and blocking as separate decisions." },
      { id: "aging_system", label: "Build the twenty-year aging system", player_task: "Coordinate makeup, hair, wardrobe, voice, movement and behavior so aging remains cumulative rather than a sequence of isolated prosthetic changes." },
      { id: "dialect_work", label: "Map dialect preparation", player_task: "Use coached regional rhythm and pronunciation as performance preparation while keeping speech variation character-specific." },
      { id: "visual_strategy", label: "Lock the tranquil visual strategy", player_task: "Translate Lee's request for a tranquil, almost passive image into shot duration, camera placement and movement choices without flattening every scene into the same tempo." },
      { id: "aspect_ratio", label: "Protect the 1.85 frame", player_task: "Compose in 1.85:1 so mountain height and sky remain active dramatic space rather than cropping toward a generic widescreen-Western template." },
      { id: "camera_lens_package", label: "Map the 35mm camera package", player_task: "Record the Arricam/Cooke S4 package from the craft source while leaving body-by-shot and focal-length-by-shot assignments open unless documented." },
      { id: "stock_map", label: "Build the film-stock map", player_task: "Separate 5245, 5246, 5218 and 5279 by documented use conditions and verify every proposed substitution against the desired contrast, saturation and speed." },
      { id: "mountain_town_contrast", label: "Coordinate mountain-town contrast", player_task: "Align stock, palette, set dressing and weather with the mountain/town contrast without making that contrast mechanically identical in every sequence." },
      { id: "night_strategy", label: "Separate night strategies", player_task: "Keep most-night 5218 and Texas-night 5279 use distinct rather than collapsing all nocturnal scenes into one stock or color treatment." },
      { id: "no_di_boundary", label: "Protect the no-DI boundary", player_task: "Record Prieto's no-DI decision as a finishing fact while preserving digital opticals and selective VFX as separate post-production work." },
      { id: "vfx_opticals", label: "Map selective VFX and opticals", player_task: "Track landscape CGI, cloud placement, Buzz Image visual effects and Cine-BYTE digital opticals without inventing software, shot counts or techniques." },
      { id: "second_unit", label: "Coordinate second-unit landscapes", player_task: "Give second-unit cinematography its own shot list and lighting windows while keeping authorship connected to Lee and Prieto's framing references." },
      { id: "exterior_logistics", label: "Plan exterior logistics", player_task: "Treat the roughly 80 percent exterior schedule as a dependency map for weather, travel, daylight, transport and equipment rather than as an aesthetic virtue." },
      { id: "weather_contingency", label: "Build weather contingencies", player_task: "Model sleet, hail, cold and fast weather changes as historical schedule pressures without reproducing unsafe conditions or inventing the production's safety protocols." },
      { id: "cowboy_training", label: "Map cowboy training", player_task: "Separate riding, sheep handling and ranch-task preparation from stunt performance, animal supervision and shot-specific risk decisions." },
      { id: "rodeo_advisors", label: "Use local rodeo advisors", player_task: "Record the Calgary Gay Rodeo Association's advisory and participant roles while keeping casting, technical advice and community representation distinct." },
      { id: "production_sound", label: "Capture production sound", player_task: "Give production sound mixer and boom operation clear field responsibilities before dialogue editorial and ADR begin." },
      { id: "sound_post", label: "Build the sound-post handoff", player_task: "Separate production sound, editorial, ADR and rerecording so later cleanup never erases the provenance of location-recorded dialogue and ambience." },
      { id: "sparse_score", label: "Design sparse score placement", player_task: "Use Santaolalla's sparse-score mandate as a spotting decision and leave emotional silence available rather than filling every transition with music." },
      { id: "song_budget_tradeoff", label: "Model music licensing tradeoffs", player_task: "Keep source-song licensing cost and original composition as separate options, using Lee's documented anecdote without assuming every cue originated from a denied license." },
      { id: "editorial_handoff", label: "Preserve the editorial handoff", player_task: "Keep Geraldine Peroni and Dylan Tichenor's shared credit visible and document the handoff without attributing stylistic changes to personal tragedy without evidence." },
      { id: "finish_delivery", label: "Map finish and delivery", player_task: "Separate negative cutting, color timing, prints, digital opticals, selective VFX and theatrical sound formats into inspectable delivery stages." },
      { id: "unknowns_register", label: "Register technical unknowns", player_task: "Keep exact exposure, filtration, printer lights, lighting fixtures, body-by-shot camera allocation, shot-specific VFX methods, budget total and detailed animal/stunt safety procedures unknown unless title-specific sources establish them." },
    ],
  },
] as const;

export function mergeChapterEighteenBrokebackMountainExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterEighteenBrokebackMountainExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_eighteen_brokeback_mountain_verified",
      source: { list_id: "manual_chapter_eighteen_brokeback_mountain_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
