import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterEighteenColdWarExpansionDefinitions = [
  {
    id: "scenario_cold_war_2018",
    title: "Cold War",
    originalTitle: "Zimna wojna",
    aliases: ["Zimna Wojna"],
    year: 2018,
    titleType: "Movie",
    runtimeMins: 90,
    directors: ["Paweł Pawlikowski"],
    genres: ["Drama", "Music", "Romance"],
    sourceId: "bfi_zimna_wojna_2018",
    sourceUrl: "https://www.bfi.org.uk/film/21f2d998-4b45-58b0-8661-c649bc2ed11f/zimna-wojna",
    scenarioType: "transnational_poland_uk_france_period_music_romance_elliptical_14_year_narrative_alexa_xt_arriraw_opengate_color_to_monochrome_4_3_ultra_prime_32mm_geographic_lens_depth_shift_six_month_prep_30_day_recce_seven_month_weather_breaks_practical_locations_music_sound_vfx_2018",
    premise: "Build Cold War as a source-first Chapter 18 Production Case about how an intimate, highly elliptical love story spanning roughly fourteen years was produced through a Polish/French/UK co-production, location-led period reconstruction, music-centered dramaturgy and a digital-to-monochrome image pipeline. BFI anchors a 90-minute catalogue version and credits Paweł Pawlikowski as director, Tanya Seghatchian and Ewa Puszczyńska as producers and Pawlikowski with Janusz Głowacki as writers; BFI Sight and Sound lists approximately 88m25s and the Cannes record lists 84 minutes, so runtime differences must be preserved as version/festival metadata rather than normalized away. Opus Film and Film4 document the core Polish/French/UK production network: Opus Film, Apocalypso Pictures and MK Productions, with financing/support from the Polish Film Institute, CNC/Aide aux Cinémas du Monde, ARTE France Cinéma, Film4, BFI National Lottery funding, Protagonist Pictures and other partners. The MK2 end-credit record keeps Jarosław Kamiński on editing, Katarzyna Sobańska and Marcel Sławiński on production design, Aleksandra Staszko on costume and Maciej Pawłowski plus Mirosław Makowski on sound. Pawlikowski describes the film as an elliptical anti-biopic whose lovers were partly inspired by his parents, with music functioning as a third character and historical/geographic glue rather than decoration; he repeatedly rewrote the screenplay, describing roughly 150 versions and a deliberately sparse financing script that left room for cinema. American Cinematographer documents six months of preparation, about thirty recce days, a seven-month January-to-August 2017 shoot with weather and professional-folk-ensemble breaks, production in Poland, Croatia and Paris, Paris interiors recreated in Poland, practical locations and location-built sets rather than conventional stage work. Pawlikowski and Łukasz Żal wanted a 35mm look but could not afford a photochemical shoot, so they tested 35mm and Alexa side by side and chose ARRI Alexa XT capture in color, monitored in black-and-white and desaturated in post. Codex documents ARRIRAW 3.4K Open Gate to Codex XR drives and DI Factory finishing; ASC documents ARRI/Zeiss Ultra Primes, a strong 32mm preference, Angénieux Optimo zoom use, two day/night LUTs, 4:3 framing, mostly single-camera operation, two cameras for Mazurek Ensemble performances, and dolly/handheld/Steadicam/crane movement. Poland scenes favor wider 28/32/40mm lenses and deeper focus, while Paris tends toward longer 50/65mm lenses and shallower focus, translating emotional/geographic difference into camera grammar rather than merely production convenience. Production design, costumes, surfaces and video village were all evaluated for monochrome separation. ASC also documents a complex East/West Berlin transition using large greenscreens and substantial in-camera elements, with about 70 percent of that shot generated in post; this is a shot-specific VFX fact, not evidence that the whole film relied on heavy VFX. Film4 and Pawlikowski interviews document music as a structural third character, from researched Polish folk material and the Mazowsze tradition to jazz and Western popular music; Opus credits folk arrangements associated with Tadeusz Sygietyński and jazz/song arrangements by Marcin Masecki rather than a conventional through-composed score. Pawlikowski says sound required painstaking selective calibration and a long mix because music and sparse action leave every environmental detail exposed. The player must coordinate co-production/funding, long prep, recce/version control, practical locations, period design, monochrome-aware costume/lighting, Alexa/ARRIRAW capture, 4:3 composition, lens/depth-of-field geography, one-versus-two-camera rules, music/performance logistics, elliptical script/editing, selective VFX and sound while refusing unsupported exact total budget, exact day count excluding breaks, complete financing shares, full lens-by-shot map, universal stop/exposure values, complete lighting inventory, exact LUT transforms, full Codex/data-management topology, complete VFX vendor/software list, exact edit-system version, production-sound hardware, music-rights fees, final mix topology or a claim that every visual decision was caused by budget.",
    requiredChoicesSeed: {
      screenplay: ["elliptical_anti_biopic", "moving_script", "music_third_character", "14_year_time_jumps", "polish_french_languages", "version_control"],
      camera: ["alexa_xt", "arriraw_3_4k_opengate", "codex_xr", "4_3_academy", "ultra_primes", "32mm_majority", "poland_paris_lens_shift", "color_capture_monochrome_post", "single_camera_majority"],
      editing: ["jaroslaw_kaminski", "elliptical_time_gaps", "black_screen_timing", "micro_film_scenes", "music_driven_transitions", "vfx_handoff"],
      sound: ["maciej_pawlowski", "miroslaw_makowski", "selective_sound_world", "music_as_story", "folk_jazz_pop_layers", "final_mix_hardware_unknown"],
      themes: ["film_history", "2018", "cold_war", "zimna_wojna", "pawel_pawlikowski", "lukasz_zal", "transnational_coproduction", "film4", "bfi", "polish_film_institute", "alexa_xt", "arriraw", "codex", "black_and_white", "academy_ratio", "ultra_prime", "32mm", "folk_music", "mazowsze", "jazz", "elliptical_editing", "practical_locations", "period_design", "digital_convergence"]
    },
    learningGoals: [
      "Explain Cold War as a coordinated co-production, screenplay, music, period-design, location, cinematography, editing, sound and post-production system rather than only as a black-and-white romance.",
      "Use BFI's 90-minute record as the canonical runtime anchor while preserving BFI Sight and Sound's approximately 88m25s and Cannes' 84-minute listing as version/festival metadata.",
      "Keep Paweł Pawlikowski's directing and writing authorship distinct from Tanya Seghatchian and Ewa Puszczyńska's producing, Łukasz Żal's cinematography, Jarosław Kamiński's editing and the production-design/sound departments.",
      "Explain the Polish/French/UK co-production as an industrial system involving Opus Film, Apocalypso Pictures, MK Productions, public funds, broadcasters, Film4/BFI and sales/distribution partners without inventing financing percentages.",
      "Distinguish production-company credits, funders, executive producers, sales agents and distributors rather than flattening them into one financing entity.",
      "Explain why a transnational co-production can move financing, locations, languages, crews and circulation across borders while preserving a specifically Polish historical core.",
      "Describe Pawlikowski's anti-biopic method: omit connective explanation, present resonant fragments and trust the audience to infer years of unseen change.",
      "Treat the screenplay as a moving production document; Pawlikowski describes roughly 150 versions and continued rewriting rather than one immutable shooting script.",
      "Explain why a sparse financing script can differ from the evolving production text without implying that financiers received false information.",
      "Explain music as a third character and structural glue connecting lovers, geography, historical period and political pressure.",
      "Separate folk-source research, performed folk material, jazz arrangements, licensed popular songs, production playback and sound mix as different production layers.",
      "Identify Mazowsze and Polish folk-song traditions as source/research anchors without assuming every performance in the film is a documentary recording of an unchanged traditional arrangement.",
      "Explain how the same musical material can be transformed across folk, state ensemble, jazz and exile contexts to carry both narrative and history.",
      "Use the documented six months of prep and roughly thirty recce days as evidence that apparent visual simplicity required extensive preparation.",
      "Explain why recce work placed production personnel at locations and tested angles before photography, integrating design, camera, logistics and period control.",
      "Use the January-to-August 2017 production span as evidence for a long calendar with breaks for weather and folk-ensemble availability rather than claiming seven continuous months of daily photography.",
      "Keep the exact number of principal-photography days unresolved unless a production schedule or call-sheet record establishes it.",
      "Distinguish Poland, Croatia and Paris filming geography from story geography across Poland, Berlin, Yugoslavia and Paris.",
      "Explain why Paris interiors could be recreated in Poland while Paris exteriors were photographed in Paris, and keep location substitution explicit.",
      "Explain the production preference for practical locations and location-built sets rather than conventional soundstage work.",
      "Identify Katarzyna Sobańska and Marcel Sławiński as production designers and explain why wood, surfaces, props and tonal separation were evaluated for a monochrome final image.",
      "Identify Aleksandra Staszko as costume designer and explain why costumes were judged partly by grayscale separation rather than by final on-screen hue alone.",
      "Explain the 35mm-versus-Alexa tests as a source-backed decision process: match lenses/angles, grade the photochemical reference, then seek a digital equivalent.",
      "Explain that budget limitations prevented a 35mm shoot without claiming that budget alone dictated every subsequent aesthetic choice.",
      "Identify ARRI Alexa XT as the documented principal camera and Codex ARRIRAW 3.4K Open Gate/XR drives as the documented capture path.",
      "Separate color sensor capture from the intended monochrome viewing pipeline: the film was shot in color, monitored in black-and-white and desaturated in post.",
      "Explain why shooting in color can preserve tonal controls and post flexibility even when the artistic target is monochrome.",
      "Identify DI Factory as the documented digital-intermediate facility while keeping exact grading software, node graph, trim versions and mastering settings unresolved without facility records.",
      "Explain the Academy/4:3 frame as a portrait/double-portrait and spatial-selection strategy rather than a nostalgic filter applied after shooting.",
      "Keep 1.33/1.37 catalogue terminology as a framing-family/version issue rather than pretending every source uses identical aspect-ratio notation.",
      "Identify ARRI/Zeiss Ultra Primes as the core prime family and the 32mm as the majority focal length documented by Żal.",
      "Keep Angénieux Optimo 24-290, 19.5-94 and 45-120 zoom use distinct from the Ultra Prime strategy rather than treating all lenses as one interchangeable package.",
      "Explain the Polish image strategy: wider 28/32/40mm focal lengths and deeper focus keep people embedded in environment.",
      "Explain the Paris strategy: longer 50/65mm focal lengths and shallower focus express alienation and emotional/geographic difference.",
      "Treat these focal-length families as documented broad strategies, not permission to invent a complete shot-by-shot lens map.",
      "Keep scene-specific f-stop values documented by Żal local to Poland/Paris examples rather than turning them into universal exposure settings.",
      "Explain why two day/night LUTs could support a monochrome-targeted shoot while leaving exact LUT math and CDL values unresolved.",
      "Explain why video village monitored in black-and-white even though the camera recorded color: departments needed to judge tonal separation for the intended release image.",
      "Explain high contrast with soft/wrapped light as a design principle without reducing the lighting system to one fixture type.",
      "Keep the documented SkyPanel, Aladdin, LiteMat, Kino Flo, PAR, M-Series, Dedolight and Fresnel package as a production resource list, not a shot-level lighting diagram.",
      "Explain why most of the film used one camera while Mazurek performance material used two: coverage rules changed with performance/logistical needs.",
      "Distinguish dolly, handheld, Steadicam and limited crane work as movement tools selected by scene rather than one signature rig.",
      "Explain how Pawlikowski and Żal continually adjusted camera height, angle, objects and light to find a single concentrated 'micro film' shot rather than defaulting to conventional coverage.",
      "Treat repeated takes and on-set rewriting as part of performance/image refinement without asserting an exact average take count for the production.",
      "Explain why the Poland opening can borrow documentary observation while the film remains a staged fiction production.",
      "Explain the East/West Berlin transition as a hybrid in-camera/VFX construction using large greenscreens, real people/cars/decoration and substantial post extension, with the documented shot-specific 70-percent-generated-in-post boundary kept local to that transition.",
      "Keep the roughly 70-percent-generated-in-post claim local to the documented Berlin shot rather than generalizing heavy VFX to the whole film.",
      "Keep exact greenscreen dimensions and lighting details attached to the documented Berlin setup instead of turning them into a film-wide effects recipe.",
      "Identify Jarosław Kamiński as editor and explain how ellipses, black-screen duration and scene-to-scene contrast carry time without explanatory connective scenes.",
      "Explain Pawlikowski's attention to black-screen duration as an editorial rhythm tool whose timing was judged on a cinema screen.",
      "Explain why large-screen review can change the felt duration of pauses and cuts compared with desktop editing.",
      "Keep exact NLE version, storage topology, assistant-editor workflow and conform system unresolved unless title-specific post records establish them.",
      "Identify Maciej Pawłowski and Mirosław Makowski as the documented sound team and keep their responsibilities distinct from music arrangement/performance.",
      "Explain Pawlikowski's selective sound principle: sparse cutting and limited non-diegetic scoring make environmental details more exposed and demand painstaking calibration.",
      "Explain why sound mix work can take substantial time even in a visually sparse film; simplicity of result does not imply a simple post process.",
      "Keep production recorder, microphone, radio, ADR, foley, console, plugin and stem topology outside the verified layer unless direct records establish them.",
      "Separate folk arrangements associated with Tadeusz Sygietyński from Marcin Masecki's jazz/song arrangements and from pre-existing Western pop recordings.",
      "Explain how music synchronization and performance continuity become production constraints when professional ensemble availability drives schedule breaks.",
      "Explain that period music and politics interact: folk ensemble institutionalization and jazz/pop circulation carry historical meaning inside the production design of the story.",
      "Separate final critical reception, Cannes awards and Academy recognition from production evidence about camera, financing, editing or sound.",
      "Maintain an uncertainty register for exact total budget, financing shares, continuous shooting-day count, complete call-sheet chronology, full lens map, universal exposure values, LUT transforms, Codex/data topology, full VFX stack, edit software version, production-sound hardware, music-rights fees and final mix settings.",
      "Build a closing production audit that checks runtime/version provenance, co-production roles, prep/recce/schedule boundaries, location substitution, monochrome-aware design, Alexa/ARRIRAW capture, aspect ratio, lens geography, camera-count rules, VFX exceptions, elliptical editing, music provenance, sound ownership and unresolved claims before verification."
    ],
    phases: [
      { id: "evidence_hierarchy", label: "Map the Cold War evidence hierarchy", player_task: "Separate BFI/Cannes catalogue metadata, Opus/Film4 production records, ASC/Codex cinematography testimony and filmmaker interviews before promoting claims." },
      { id: "runtime_versions", label: "Lock runtime/version evidence", player_task: "Use BFI's 90 minutes as canonical while preserving approximately 88m25s and Cannes' 84-minute listing as version/festival metadata." },
      { id: "coproduction_map", label: "Map the transnational co-production", player_task: "Separate Polish, French and UK production companies, funds, broadcasters, executive producers, sales and distribution roles without inventing financing shares." },
      { id: "script_versions", label: "Track the moving screenplay", player_task: "Preserve Pawlikowski's iterative screenplay process, elliptical deletions and financing-script boundary through version control." },
      { id: "music_structure", label: "Design music as the third character", player_task: "Map folk, ensemble, jazz and popular-music transformations to relationship, geography and historical change." },
      { id: "prep_lock", label: "Lock six months of prep", player_task: "Coordinate camera, design, costume, locations and monochrome testing across the documented long preparation period." },
      { id: "recce_lock", label: "Lock the recce process", player_task: "Use roughly thirty recce days to test positions, design and logistics while preserving exact daily records as unknown." },
      { id: "calendar_schedule", label: "Build the seven-month production calendar", player_task: "Model January-to-August 2017 with weather and ensemble breaks rather than pretending it was continuous daily shooting." },
      { id: "location_geography", label: "Reconcile filming and story geography", player_task: "Track Poland, Croatia and Paris filming separately from Poland, Berlin, Yugoslavia and Paris story locations." },
      { id: "practical_locations", label: "Prioritize practical locations", player_task: "Use practical spaces and location-built sets while documenting Paris-interior substitutions in Poland." },
      { id: "monochrome_design", label: "Design for monochrome", player_task: "Coordinate production design, costume, surfaces and props for grayscale separation before shooting." },
      { id: "film_vs_digital_test", label: "Reconstruct the 35mm/Alexa test", player_task: "Compare matching angles/lenses and grading targets to justify the Alexa decision without erasing the photochemical reference." },
      { id: "camera_capture", label: "Lock Alexa XT ARRIRAW capture", player_task: "Track Alexa XT, ARRIRAW 3.4K Open Gate and Codex XR drives while bounding unverified data-management details." },
      { id: "monochrome_pipeline", label: "Track color-to-monochrome lineage", player_task: "Keep color capture, black-and-white monitoring, day/night LUTs and post desaturation as distinct pipeline stages." },
      { id: "academy_frame", label: "Lock the 4:3 portrait frame", player_task: "Use the Academy-style frame as a production composition rule and preserve 1.33/1.37 notation differences as metadata." },
      { id: "prime_strategy", label: "Lock the Ultra Prime strategy", player_task: "Use the 32mm majority preference and documented wider Poland focal family without inventing per-shot lens assignments." },
      { id: "paris_lens_shift", label: "Shift Paris lens/depth grammar", player_task: "Move toward 50/65mm and shallower focus in Paris to make geography and emotional alienation visible." },
      { id: "zoom_boundary", label: "Map Angénieux zoom use", player_task: "Keep the documented 24-290, 19.5-94 and 45-120 tools separate from the Ultra Prime core package." },
      { id: "lighting_package", label: "Build high-contrast soft light", player_task: "Use the documented mixed lighting resources and wrapped-light principle without fabricating shot-level diagrams." },
      { id: "camera_count", label: "Set one-versus-two-camera rules", player_task: "Use a single camera for most scenes and two for Mazurek performances, preserving performance-specific exceptions." },
      { id: "movement_grammar", label: "Map dolly, handheld, Steadicam and crane", player_task: "Select movement by geography, dance and emotional energy rather than imposing one rig on every scene." },
      { id: "micro_film_staging", label: "Refine each scene as a micro film", player_task: "Iterate frame, height, blocking, props and light toward one concentrated shot instead of default coverage." },
      { id: "folk_performance", label: "Coordinate professional ensemble performance", player_task: "Integrate choreography, playback/live-performance needs, camera count and ensemble availability with the shooting calendar." },
      { id: "berlin_vfx", label: "Build the East/West Berlin transition", player_task: "Separate greenscreen/post-generated background from real people, cars and decoration and keep the 70-percent post figure local to the documented shot." },
      { id: "vfx_unknowns", label: "Bound the VFX pipeline", player_task: "Keep full vendor ownership, software, shot count and compositing settings unresolved beyond the documented Berlin construction." },
      { id: "elliptical_edit", label: "Build fourteen years through ellipses", player_task: "Remove explanatory bridges while ensuring costume, music, behavior and setting make each temporal jump legible." },
      { id: "black_screen_timing", label: "Calibrate black-screen pauses", player_task: "Judge pause duration on a cinema screen and track it as editorial rhythm rather than empty filler." },
      { id: "editing_unknowns", label: "Bound editorial infrastructure", player_task: "Keep NLE version, shared storage, assistant workflow and conform topology unresolved unless sourced." },
      { id: "selective_sound", label: "Build the selective sound world", player_task: "Make doors, rooms, crowds and environmental events precise because sparse cutting/music exposes every sonic choice." },
      { id: "music_rights", label: "Separate music provenance and rights", player_task: "Track traditional material, arrangements, performances and licensed recordings as distinct clearance and mix layers." },
      { id: "sound_mix", label: "Calibrate the long sound mix", player_task: "Preserve Pawlikowski's account of painstaking mix work while bounding hardware, stems and exact settings." },
      { id: "di_finish", label: "Close the monochrome DI", player_task: "Hand color-origin ARRIRAW through DI Factory to the monochrome release while keeping grading software/node details outside the verified layer." },
      { id: "uncertainty_register", label: "Maintain Cold War unknowns", player_task: "Track budget, finance shares, exact shooting days, full lens map, exposures, LUT math, data topology, VFX stack, edit software, sound hardware, music fees and mix settings explicitly." },
      { id: "chapter18_position", label: "Position Cold War in Chapter 18", player_task: "Explain how digital capture/post and transnational public co-production enabled a deliberately classical monochrome period film without making it either technologically or nationally simple." },
      { id: "delivery_audit", label: "Audit the complete Cold War production system", player_task: "Verify runtime/version, co-production, prep, recce, schedule, locations, design, capture, frame, lenses, camera count, VFX, edit, music, sound and unknowns before closure." }
    ]
  }
] as const;

export function mergeChapterEighteenColdWarExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterEighteenColdWarExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_eighteen_cold_war_verified",
      source: { list_id: "manual_chapter_eighteen_cold_war_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}