import assert from "node:assert/strict";
import test from "node:test";

import { chapterEighteenAmourExpansionDefinitions } from "./chapterEighteenAmourExpansion.js";

test("Chapter 18 materializes Amour as a source-first European co-production, chamber-staging and digital-negative case", () => {
  assert.equal(chapterEighteenAmourExpansionDefinitions.length, 1);
  const film = chapterEighteenAmourExpansionDefinitions[0];
  assert.equal(film.id, "scenario_amour_2012");
  assert.equal(film.year, 2012);
  assert.equal(film.runtimeMins, 127);
  assert.deepEqual(film.directors, ["Michael Haneke"]);
  assert.ok(film.scenarioType.includes("france_germany_austria") && film.scenarioType.includes("public_funding") && film.scenarioType.includes("chamber_staging"));
  assert.ok(film.scenarioType.includes("arri_alexa") && film.scenarioType.includes("arriraw") && film.scenarioType.includes("codex"));
  assert.ok(film.premise.includes("Margaret Menegoz") && film.premise.includes("Stefan Arndt") && film.premise.includes("Veit Heiduschka") && film.premise.includes("Michael Katz"));
  assert.ok(film.premise.includes("Eurimages") && film.premise.includes("Austrian Film Institute") && film.premise.includes("Vienna Film Fund"));
  assert.ok(film.premise.includes("parents' Vienna apartment") && film.premise.includes("French interior"));
  assert.ok(film.premise.includes("Éclair Studios") && film.premise.includes("February to April 2011") && film.premise.includes("five-day weeks"));
  assert.ok(film.premise.includes("storyboards") && film.premise.includes("computer previsualisation"));
  assert.ok(film.premise.includes("ARRI Alexa") && film.premise.includes("ARRIRAW recorded to Codex") && film.premise.includes("Digimage"));
  assert.ok(film.premise.includes("35 mm Master Primes") && film.premise.includes("40 mm and 50 mm Cooke S4/S5"));
  assert.ok(film.premise.includes("20Ks") && film.premise.includes("spacelights") && film.premise.includes("bounced Lekos") && film.premise.includes("practicals"));
  assert.ok(film.premise.includes("almost entirely in chronological order"));
  assert.ok(film.premise.includes("physiotherapy consultant") && film.premise.includes("nursing consultant") && film.premise.includes("piano coach"));
  assert.ok(film.premise.includes("mechanical adjustments to the bed") && film.premise.includes("performer-safety"));
  assert.ok(film.premise.includes("exact camera submodel") && film.premise.includes("exact Codex hardware") && film.premise.includes("undocumented DI settings"));
  assert.ok(film.requiredChoicesSeed.camera.includes("camera_submodel_unknown"));
  assert.ok(film.requiredChoicesSeed.editing.includes("di_unknowns"));
  assert.ok(film.requiredChoicesSeed.sound.includes("sound_equipment_unknowns"));
  assert.ok(film.learningGoals.some((goal) => goal.includes("127-minute") && goal.includes("conflicting later catalogue runtimes")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("public-funding package") && goal.includes("reporting dependencies")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("parents' Vienna apartment") && goal.includes("secondary reporting differs")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("ARRI Alexa") && goal.includes("exact Alexa submodel unresolved")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("ARRIRAW") && goal.includes("Codex") && goal.includes("exact Codex recorder model")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("35 mm Master Primes") && goal.includes("40 mm and 50 mm Cooke S4/S5")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("20K") && goal.includes("spacelights") && goal.includes("bounced Lekos")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("almost the whole film in chronological order") && goal.includes("progressive performance")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("physiotherapy consultant") && goal.includes("nursing consultant")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("mechanically adapted bed") && goal.includes("performer safety")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Monika Willi") && goal.includes("Nadine Muse")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Guillaume Sciama") && goal.includes("Jean-Pierre Laforce")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("exact set dimensions") && goal.includes("exact Alexa submodel") && goal.includes("exact Codex model")));
  assert.ok(film.phases.find((phase) => phase.id === "funding_stack")?.player_task.includes("Eurimages"));
  assert.ok(film.phases.find((phase) => phase.id === "floor_dolly")?.player_task.includes("parquet"));
  assert.ok(film.phases.find((phase) => phase.id === "camera_package")?.player_task.includes("exact camera submodel"));
  assert.ok(film.phases.find((phase) => phase.id === "care_consultants")?.player_task.includes("physiotherapy"));
  assert.ok(film.phases.find((phase) => phase.id === "unknowns_register")?.player_task.includes("Codex model"));
  assert.ok(film.learningGoals.length >= 50);
  assert.ok(film.phases.length >= 30);
});
