import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterEighteenTheNewWorldExpansionDefinitions = [
  {
    id: "scenario_the_new_world_2005",
    title: "The New World",
    originalTitle: "The New World",
    aliases: [],
    year: 2005,
    titleType: "Movie",
    runtimeMins: 135,
    directors: ["Terrence Malick"],
    genres: ["Drama", "History", "Romance"],
    sourceId: "criterion_the_new_world_2005",
    sourceUrl: "https://www.criterion.com/films/28713-the-new-world",
    scenarioType: "photochemical_countercurrent_anamorphic_35mm_selective_65mm_natural_light_deep_focus_virginia_location_historical_reconstruction_multi_cut_editorial_2005",
    premise: "Build The New World as a source-first Chapter 18 Production Case whose historical value is precisely that a large prestige feature could remain deliberately photochemical while digital post, exhibition and capture were expanding around it. Criterion documents Terrence Malick as writer-director, Sarah Green as producer, Emmanuel Lubezki as director of photography, Jack Fisk as production designer and James Horner as composer, and preserves three director-approved versions: a 135-minute theatrical cut, a 150-minute first cut and a 172-minute extended cut. The 135-minute theatrical cut is the playable runtime anchor, while the 150- and 172-minute versions remain explicit editorial-version provenance rather than interchangeable runtimes. BFI credits Richard Chew, Hank Corwin, Saar Klein and Mark Yoshikawa as editors; Jörg Widmer for cinematography; Pete Romano for underwater photography; Jacqueline West for costume design; Craig Berkey as sound designer; José Antonio García as sound mixer; Skip Lievsay and Craig Berkey as rerecording mixers; and CIS Hollywood for visual effects. American Cinematographer's January 2006 production account documents a predominantly anamorphic 35mm strategy, a small amount of 65mm for what Lubezki called hyper-enhanced moments, close camera-to-actor work with 40mm and 50mm focal lengths, custom close-focus Panavision lenses combining C- and E-Series characteristics, deep-stop ambitions around T11-T16, and Kodak Vision2 200T 5217 and Vision2 500T 5218. The case treats those values as title-specific evidence rather than a universal Malick/Lubezki recipe. Criterion and BFI both emphasize naturally lit cinematography; BFI describes an almost entirely natural-light moving-camera approach using handheld or Steadicam. Producer Sarah Green's production account and later Jack Fisk testimony describe the decision to shoot in Virginia near the James and Chickahominy Rivers, the State of Virginia's role in making location production feasible, and Fisk's historically researched Jamestown construction. Fisk's method is physical and spatial: instead of treating sets as isolated backdrops, the production built environments that could support Malick's fluid, minimally storyboarded staging and changing relationship to natural light. Historical and archaeological research inform production design, but the film is never treated as independent proof of seventeenth-century history. The production also reconstructed a form of Virginia Algonquian/Powhatan language with linguistic consultation and used Native and First Nations performers, making language coaching, casting, choreography, costume, representation and cultural evidence distinct production responsibilities. Editing is a major production system rather than a cleanup step: the existence of 150-, 135- and 172-minute cuts demonstrates continuing structural revision, and Criterion's later restoration had to combine 35mm original camera negative, a 35mm interpositive and 65mm original camera negative for selected shots because the 35mm negative had been cut for the theatrical version. That restoration evidence is used only to confirm source-element/version history, never retroactively as the 2005 finishing workflow. The player must coordinate version control, natural-light scheduling, moving-camera access, anamorphic close focus, deep-stop exposure, selective 65mm, film stock, location ecology, practical construction, language and cultural consultation, performer welfare, costume/makeup, water work, editorial lineage, sound, score and bounded VFX while refusing unsupported claims about a single canonical 150/172-minute runtime, exact 65mm shot count, complete lens-by-shot map, universal T-stop, exact exposure index or push/pull processing, full filter package, exact camera-body assignment by shot, total budget or financing shares, complete construction inventory, cultural-consultant authority beyond documented roles, complete VFX shot count/software stack, 2005 DI/scanning settings inferred from the later Criterion restoration, exact production-sound hardware, music stems or final mix topology.",
    requiredChoicesSeed: {
      screenplay: ["malick_writer_director", "historical_source_boundary", "pocahontas_smith_rolfe_structure", "voiceover_subjectivity", "versioned_editorial_structure", "cultural_history_boundary"],
      camera: ["anamorphic_35mm_primary", "selective_65mm", "panavision_close_focus_hybrids", "40mm_50mm_proximity", "vision2_200t_5217", "vision2_500t_5218", "natural_light", "deep_focus", "moving_camera", "65mm_shot_count_unknown"],
      editing: ["135_theatrical_anchor", "150_first_cut", "172_extended_cut", "four_editor_lineage", "version_provenance", "negative_cut_history", "restoration_not_2005_pipeline"],
      sound: ["craig_berkey_sound_design", "jose_antonio_garcia_mixer", "skip_lievsay_rerecording", "james_horner_score", "wagner_mozart_source_music_boundary", "production_sound_hardware_unknown"],
      themes: ["film_history", "2005", "the_new_world", "terrence_malick", "emmanuel_lubezki", "jack_fisk", "sarah_green", "photochemical_countercurrent", "anamorphic_35mm", "65mm", "panavision", "kodak_vision2", "natural_light", "deep_focus", "virginia", "jamestown", "chickahominy", "powhatan_language", "historical_reconstruction", "multi_cut_editing", "chapter18_counterexample"]
    },
    learningGoals: [
      "Explain The New World as a coordinated production system and as a deliberate photochemical countercurrent inside Chapter 18's digital-convergence period.",
      "Identify Terrence Malick as writer-director and Sarah Green as producer without turning authorship into proof of undocumented department decisions.",
      "Use the 135-minute theatrical cut as the playable runtime anchor while preserving the 150-minute first cut and 172-minute extended cut as distinct editorial versions.",
      "Explain why three materially different cuts require version-specific evidence rather than one blended description of 'the film'.",
      "Identify Emmanuel Lubezki as director of photography and distinguish his camera authorship from Jörg Widmer's credited cinematography and Pete Romano's underwater photography.",
      "Identify Jack Fisk as production designer and treat built geography as a production system rather than decorative historical background.",
      "Identify Jacqueline West as costume designer and keep costume research distinct from production design, makeup and historical truth claims.",
      "Identify Richard Chew, Hank Corwin, Saar Klein and Mark Yoshikawa as documented editors and treat editorial lineage as central to the released-version history.",
      "Identify James Horner as composer while separating original score from Wagner, Mozart and other pre-existing musical material used in the film.",
      "Identify Craig Berkey, José Antonio García and Skip Lievsay within their documented sound roles instead of collapsing production sound, sound design and rerecording into one credit.",
      "Explain why a 2005 prestige feature shot predominantly on film is historically useful evidence against a simplistic universal digital-camera transition.",
      "Identify anamorphic 35mm as the predominant capture system rather than digital acquisition or full-feature 65mm.",
      "Explain that only a small amount of 65mm was photographed for selected hyper-enhanced moments and reject any claim that the entire feature was shot in 65mm.",
      "Keep the exact number and identity of 65mm shots unresolved unless a shot-level production record establishes them.",
      "Explain why 65mm could function as an emphasis layer inside a predominantly 35mm feature without becoming the production's default capture format.",
      "Record 40mm and 50mm as documented core focal lengths used close to performers while refusing a complete lens-by-shot map.",
      "Explain why Panavision created close-focus lenses combining C- and E-Series characteristics for the production's desire to stay physically close to actors.",
      "Treat the custom close-focus lens work as a response to anamorphic close-focus constraints, not as proof that every setup used the same lens design.",
      "Explain Lubezki's deep-focus objective and the documented T11-T16 working ambition without converting those values into a universal per-shot exposure claim.",
      "Explain how deep stops, natural light, moving performers and close camera proximity create a coupled exposure, focus and scheduling problem.",
      "Record Kodak Vision2 200T 5217 and Vision2 500T 5218 as documented stocks while keeping scene-by-scene stock assignment bounded where evidence is absent.",
      "Reject invented exposure indexes, push/pull processing, shutter angles, filtration or lab timing values unless title-specific records support them.",
      "Explain Criterion and BFI's natural-light evidence as a core aesthetic-production constraint rather than an absolute no-artificial-light rule for every setup.",
      "Explain why sun direction, cloud cover, season and time of day become scheduling inputs when the production prioritizes natural light.",
      "Describe handheld and Steadicam movement as documented parts of the camera grammar while keeping exact rig assignment by shot unresolved.",
      "Explain how a moving-camera, low-heavy-grip approach changes blocking and set access compared with rigidly prelit coverage.",
      "Explain why Malick's fluid, minimally storyboarded working method makes complete physical environments especially valuable to actors and camera crews.",
      "Identify Virginia near the James and Chickahominy Rivers as the principal historical-location strategy rather than an anonymous wilderness double.",
      "Explain how the State of Virginia's support affected the feasibility of keeping the production near the historical geography without inventing a precise incentive amount.",
      "Treat local location feasibility, union/crew availability and landscape authenticity as separate production variables.",
      "Explain Fisk's Jamestown construction as research-driven physical production design rather than a digital environment replacement.",
      "Explain why complete buildable environments can support unscripted camera directions and changing light more effectively than isolated facade coverage.",
      "Use archaeological and historical research as filmmaker reference while refusing to treat the finished film as independent verification of seventeenth-century facts.",
      "Explain how a historically plausible saw-pit or rough construction method can emerge from research and design reasoning without implying perfect archaeological certainty.",
      "Separate the Jamestown fort, Powhatan settlement, river geography and later English spaces as distinct design/location systems that require continuity management.",
      "Explain why plants, mud, water, smoke, weather and seasonal landscape changes are continuity inputs when the environment is allowed to remain visually active.",
      "Treat river and underwater work as separate safety and camera domains and keep exact marine rigging or underwater housing details unresolved unless sourced.",
      "Explain why language reconstruction and coaching are production tasks involving script, performance, sound, dialect/language expertise and cultural responsibility.",
      "Keep the reconstructed Virginia Algonquian/Powhatan language distinct from a claim of historical completeness or a fully certain spoken-language reconstruction.",
      "Explain why Native and First Nations casting is representation and labor evidence without treating performers' identities as proof of every cultural detail in the production.",
      "Separate casting, language coaching, choreography, costume, hair/makeup and historical consultation as distinct responsibilities that must coordinate without collapsing authority.",
      "Protect the welfare of young performers and large background groups as a production responsibility independent of the film's historical subject.",
      "Explain how costume materials, movement and color interact with natural-light photography while leaving undocumented wardrobe-by-scene technical rules unresolved.",
      "Identify CIS Hollywood as a documented VFX credit while refusing to infer a complete shot count, software stack or digital-environment replacement pipeline.",
      "Explain why limited VFX can coexist with a predominantly physical, photochemical production without making the film either 'no VFX' or 'digitally produced'.",
      "Treat the later Criterion 4K restoration as source-element and version-history evidence, not as evidence for the 2005 production or finishing pipeline.",
      "Explain why Criterion's use of 35mm original negative, 35mm interpositive and selected 65mm original negative reveals the material complexity of reconstructing the extended cut.",
      "Explain why the theatrical cut's physical negative history matters when later versions are reconstructed from multiple film elements.",
      "Keep later Northlight scanning, restoration tools and remastered audio outside the 2005 production layer unless the question is specifically about restoration history.",
      "Explain how four editors and continuing recutting can alter rhythm, point of view, scene duration and even the presence of material without changing principal photography.",
      "Use the 150-minute awards-season first cut, 135-minute theatrical cut and 172-minute extended cut as evidence of editorial evolution rather than quality ranking.",
      "Explain why release date, awards qualification and later home-video restoration are distribution/version facts, not substitutes for production-process evidence.",
      "Separate James Horner's authored score from source music and from Craig Berkey/Skip Lievsay sound construction in the final soundtrack.",
      "Keep exact microphones, recorders, ADR chain, music stems, reverbs, loudness targets and final mix topology unresolved unless title-specific records establish them.",
      "Maintain an uncertainty register for exact budget and financing shares, full camera-body map, exact 65mm shot count, complete lens map, exposure values, filter package, processing, construction inventory, VFX details, production-sound hardware and 2005 finishing settings.",
      "Explain The New World's Chapter 18 significance as a boundary case showing that sophisticated analogue capture, physical construction and natural-light production remained viable while digital post and exhibition infrastructures expanded.",
      "Contrast The New World with digital-camera Chapter 18 cases without claiming that photochemical capture makes its editing, VFX, sound or later distribution non-digital.",
      "Build a closing production audit that checks cut identity, capture-format boundaries, natural-light evidence, Virginia geography, construction provenance, language/cultural consultation, editorial lineage, sound/music credits and unresolved technical claims before verification."
    ],
    phases: [
      { id: "evidence_hierarchy", label: "Map the evidence hierarchy", player_task: "Separate Criterion version records, BFI/AFI credits, American Cinematographer camera evidence, producer/location testimony, Fisk design testimony and later restoration evidence before promoting claims." },
      { id: "version_anchor", label: "Lock the playable version", player_task: "Use the 135-minute theatrical cut as the playable anchor and preserve the 150- and 172-minute versions as separately identified editorial states." },
      { id: "historical_boundary", label: "Set the historical boundary", player_task: "Use historical and archaeological research as production reference without treating the finished drama as independent historical proof." },
      { id: "virginia_location", label: "Commit to Virginia geography", player_task: "Coordinate landscape access, river geography, period sightlines, crew feasibility and state support without inventing incentive values." },
      { id: "environment_map", label: "Map the physical world", player_task: "Relate fort, settlement, river, forest and later English spaces so blocking and moving-camera choices remain geographically coherent." },
      { id: "jamestown_build", label: "Build Jamestown physically", player_task: "Translate archaeological and construction research into a full working environment that can tolerate fluid staging and changing camera direction." },
      { id: "powhatan_world", label: "Build the Powhatan environment", player_task: "Coordinate design, landscape, costume, movement and language evidence without flattening distinct cultural responsibilities into one department." },
      { id: "language_reconstruction", label: "Plan language reconstruction", player_task: "Track linguistic sources, coaching authority, pronunciation work and actor preparation while preserving uncertainty about historical completeness." },
      { id: "casting_context", label: "Coordinate situated casting", player_task: "Separate representation, performer identity, historical role, language preparation and production labor rather than treating any one as proof of the others." },
      { id: "young_performer_welfare", label: "Protect young performers", player_task: "Treat age, schedule, water/weather exposure, costume and emotional work as safeguarding constraints independent of the film's aesthetics." },
      { id: "costume_system", label: "Build costume continuity", player_task: "Coordinate Jacqueline West's period wardrobe with movement, weather, water, dirt and natural-light rendering without inventing unsupported scene recipes." },
      { id: "anamorphic_primary", label: "Lock anamorphic 35mm primary", player_task: "Treat anamorphic 35mm as the dominant capture system and reject any full-feature 65mm or digital-acquisition rewrite." },
      { id: "selective_65mm", label: "Reserve selective 65mm", player_task: "Use 65mm only for documented hyper-enhanced moments and keep the exact shot list unresolved." },
      { id: "close_focus_lenses", label: "Configure close-focus anamorphics", player_task: "Use the documented C/E-Series hybrid approach to preserve actor proximity while keeping body/lens assignment by shot unknown." },
      { id: "focal_length_boundary", label: "Bound focal-length evidence", player_task: "Use 40mm and 50mm as documented core choices without turning them into an exhaustive or universal lens map." },
      { id: "deep_focus", label: "Plan deep focus", player_task: "Treat T11-T16 as a documented working ambition and coordinate focus, negative sensitivity and daylight without asserting every shot used those stops." },
      { id: "film_stock", label: "Track film stocks", player_task: "Log Vision2 200T 5217 and 500T 5218 while leaving scene-level stock assignment and processing open unless stronger records establish them." },
      { id: "natural_light", label: "Schedule natural light", player_task: "Plan sun position, clouds, season and available-light windows while preserving the evidence boundary against an absolute no-artificial-light claim." },
      { id: "moving_camera", label: "Keep the camera mobile", player_task: "Coordinate handheld and Steadicam access with performance and complete environments without inventing a per-shot rig ledger." },
      { id: "minimal_grip", label: "Protect light-footprint staging", player_task: "Keep heavy grip and prelighting from unnecessarily freezing the environment while retaining safety and access controls." },
      { id: "water_unit", label: "Separate water work", player_task: "Coordinate Pete Romano's underwater photography and river activity as distinct safety/camera domains without inventing underwater housing or marine-rig details." },
      { id: "weather_continuity", label: "Track weather continuity", player_task: "Log mud, water level, vegetation, cloud state, costume condition and season so editorial has evidence for environmental changes." },
      { id: "performance_freedom", label: "Preserve performance freedom", player_task: "Let complete environments and close moving cameras support exploratory blocking while retaining continuity and safety notes." },
      { id: "vfx_boundary", label: "Bound visual effects", player_task: "Record CIS Hollywood and on-set VFX supervision without inventing shot totals, software or a digital replacement model for the physical world." },
      { id: "sound_roles", label: "Map sound ownership", player_task: "Keep José Antonio García, Craig Berkey and Skip Lievsay in distinct production, design and rerecording responsibilities." },
      { id: "score_boundary", label: "Map music ownership", player_task: "Separate James Horner's score from Wagner, Mozart and other source music and from sound-design authorship." },
      { id: "editorial_lineage", label: "Track editor lineage", player_task: "Preserve Chew, Corwin, Klein and Yoshikawa as documented editorial authors and record handoffs rather than assuming one editor made every version." },
      { id: "first_cut", label: "Preserve the 150-minute first cut", player_task: "Treat the awards-season first cut as a distinct released/versioned object without making it the only canonical text." },
      { id: "theatrical_cut", label: "Preserve the 135-minute theatrical cut", player_task: "Use the wide theatrical version as the playable anchor and retain its own sequence and timing identity." },
      { id: "extended_cut", label: "Preserve the 172-minute extended cut", player_task: "Treat the later extended cut as a separate director-approved version containing material not released theatrically." },
      { id: "negative_history", label: "Track physical negative history", player_task: "Record that the 35mm negative was cut for the theatrical version and keep that fact available when explaining later reconstruction." },
      { id: "restoration_boundary", label: "Separate restoration from production", player_task: "Use Criterion's later element/scanning history only for restoration provenance, never as the 2005 capture or finishing workflow." },
      { id: "release_boundary", label: "Separate release from production", player_task: "Keep awards qualification, wide release and later home-video versions distinct from principal-photography and post-production facts." },
      { id: "unknowns_register", label: "Maintain the unknowns register", player_task: "Leave exact budget shares, camera assignments, 65mm shot count, complete lens map, exposure/filters/processing, VFX details, sound hardware and 2005 finishing settings unresolved." },
      { id: "chapter18_counterexample", label: "Position the analogue counterexample", player_task: "Explain why photochemical persistence is a Chapter 18 finding rather than evidence that digital convergence did not exist." },
      { id: "delivery_review", label: "Audit the complete production system", player_task: "Verify version identity, film-format boundaries, natural-light evidence, Virginia geography, design research, language/casting provenance, editorial lineage, sound/music roles and technical unknowns before closure." }
    ]
  }
] as const;

export function mergeChapterEighteenTheNewWorldExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterEighteenTheNewWorldExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_eighteen_the_new_world_verified",
      source: { list_id: "manual_chapter_eighteen_the_new_world_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
