import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterEighteenGetOutExpansionDefinitions = [
  {
    id: "scenario_get_out_2017",
    title: "Get Out",
    originalTitle: "Get Out",
    aliases: [],
    year: 2017,
    titleType: "Movie",
    runtimeMins: 103,
    directors: ["Jordan Peele"],
    genres: ["Horror", "Thriller"],
    sourceId: "bfi_get_out_2017",
    sourceUrl: "https://www.bfi.org.uk/film/81a56239-4e69-56b1-b2f0-128204576ae9/get-out",
    scenarioType: "blumhouse_low_budget_social_horror_23_day_alabama_location_production_alexa_mini_angeniuex_3_2k_prores4444_2k_finish_four_luts_two_camera_sunken_place_practical_vfx_editorial_test_screening_gospel_horror_score_2017",
    premise: "Build Get Out as a source-first Chapter 18 Production Case about how a culturally specific social-horror screenplay was realized inside a low-budget Blumhouse production system without treating resource scarcity as an excuse for vague craft claims. BFI and AFI both anchor a 103-minute 2017 release and identify Jordan Peele as writer-director, Sean McKittrick, Jason Blum, Edward H. Hamm Jr. and Peele as producers, Toby Oliver as cinematographer, Gregory Plotkin as editor, Rusty Smith as production designer and Michael Abels as composer. Other catalogues list 104- or 105-minute timings, so the player must preserve runtime variation as version metadata rather than silently normalizing every release. ASC and Toby Oliver's Filmmaker Magazine production account document a tight 23-day principal-photography schedule, the move from an originally intended California shoot to Alabama when the California tax break did not work for the budget, and a Mobile/Fairhope location strategy in which the Armitage house and almost every scene were shot in practical real locations. The Sunken Place was the major exception: a civic center was treated as a stage, with Daniel Kaluuya supported on a limited wire rig, fans used to create drifting cloth movement, 200-fps Alexa Mini photography for the falling material, and camera/dolly cheats that substituted for unaffordable large-scale rigging. Oliver documents ARRI Alexa Mini capture in 3.2K ProRes 4444 for a standard 2K cinema finish, two cameras on literally every setup, Angénieux compact zoom use, preproduction photoboards and location stills, and four production LUTs for city, estate day, estate night and basement/games-room conditions that were later refined in the DI. The practical-house restrictions prohibited drilling or heavy ceiling rigging, so the camera and lighting departments used tools such as the MAX Menace Arm, small fixtures and mobile approaches to preserve speed and protect the location. The visual strategy begins with a natural/cool city world, shifts to a warm, golden and deliberately welcoming estate, then introduces increasingly uneasy green/cyan night color and motivated horror cues as Chris understands the threat. Gregory Plotkin's editing account treats horror and comedy as timing disciplines: he often held shots longer than expected, used negative space and performance before overt stings, built the Sunken Place with Avid resizing and temporary wire cleanup, and worked with Peele through alternate endings and audience-response evidence without reducing editorial decisions to test-score obedience. Michael Abels' score was developed around Peele's demand for a distinctly Black voice without stereotype; Abels described the concept as 'gospel horror,' used Swahili choral material as a warning voice around Chris, and began developing the title idea before photography. Mix reporting documents a compressed score-mix schedule and a 5.1-oriented music delivery, but the production case must keep the full final-dub topology, exact sound-effect chain and department-by-department hardware outside the locked layer unless stronger title-specific records establish them. The player must coordinate a 23-day schedule, practical-location protection, Alabama incentive logic, storyboards/photoboards, two-camera coverage, Alexa Mini/Angénieux capture, 3.2K ProRes 4444 data, four LUTs, 2K finish, Sunken Place practical/VFX handoff, editorial timing, alternate-ending review, score and sound boundaries while refusing unsupported exact department budgets, exact lens-by-shot maps beyond specifically documented examples, universal exposure settings, full LUT transforms, complete lighting inventory, wire-rig geometry, complete VFX shot/vendor/software lists, production-sound recorder/microphone packages, final DI node trees, complete test-screening score histories or a claim that every creative change was caused by budget.",
    requiredChoicesSeed: {
      screenplay: ["social_horror_authorship", "jordan_peele_writer_director", "horror_comedy_timing", "sunken_place_story_function", "culturally_specific_point_of_view", "ending_version_control"],
      camera: ["alexa_mini", "angeniuex_compact_zooms", "3_2k_prores4444", "two_camera_every_setup", "four_luts", "2k_finish", "practical_location_constraints", "exact_lens_map_bounded"],
      editing: ["gregory_plotkin", "negative_space", "performance_first", "avid_sunken_place_temp", "alternate_endings", "test_screening_context", "timing_over_stings"],
      sound: ["michael_abels", "gospel_horror", "swahili_voices", "score_mix_5_1_context", "sound_music_boundary", "production_sound_hardware_unknown"],
      themes: ["film_history", "2017", "get_out", "jordan_peele", "blumhouse", "low_budget_genre", "social_horror", "black_authorship", "23_day_schedule", "alabama", "tax_incentive", "practical_locations", "alexa_mini", "angeniuex", "prores_4444", "sunken_place", "gregory_plotkin", "michael_abels", "gospel_horror", "test_screening", "digital_convergence"]
    },
    learningGoals: [
      "Explain Get Out as a coordinated screenplay, producing, schedule, location, camera, lighting, performance, editorial, VFX, music and sound system rather than only as a successful horror concept.",
      "Use the BFI/AFI 103-minute record as the canonical runtime anchor while preserving 104- and 105-minute catalogue timings as version metadata rather than silently forcing one duration across every release.",
      "Identify Jordan Peele as writer-director and producer while keeping Sean McKittrick, Jason Blum and Edward H. Hamm Jr. distinct as documented producers.",
      "Explain the Chapter 18 significance of a culturally specific Black-authored social-horror film scaling through a specialty low-budget production pipeline without blockbuster resources.",
      "Treat the low-budget frame as an industrial condition that shaped schedule, location and rigging choices without assuming scarcity automatically caused every aesthetic decision.",
      "Use the documented 23-day principal-photography schedule as a planning constraint while keeping additional-photography dates and exact second-unit day counts unresolved unless title-specific records establish them.",
      "Explain why a tight schedule increases the value of preproduction decisions, storyboards, photoboards, location scouting and coverage strategy.",
      "Identify the production's move from an intended California shoot to Alabama as a budget/incentive decision documented by Toby Oliver rather than as evidence that the story is set in Alabama.",
      "Distinguish filming geography from story geography: Alabama locations were selected to represent an East Coast/upstate environment and were actively screened for unwanted Southern specificity.",
      "Explain how a location incentive can change crew, travel, equipment and infrastructure assumptions without proving an exact rebate amount unless the production accounting record is recovered.",
      "Identify the Armitage house and most other scenes as practical-location work in real houses and buildings around Mobile/Fairhope.",
      "Explain why practical-house preservation rules affected lighting and rigging: drilling ceilings and installing heavy permanent pipe were not acceptable in the hero house.",
      "Explain how a MAX Menace Arm and smaller mobile fixtures solved location-protection and speed problems without treating one dinner-scene setup as a universal lighting recipe for the film.",
      "Keep the complete lighting package, fixture quantities by day and department rental cost unresolved beyond specifically documented examples.",
      "Identify Toby Oliver as cinematographer and keep cinematography authorship distinct from Peele's direction, Rusty Smith's production design and later DI work.",
      "Identify ARRI Alexa Mini as the documented principal camera platform and explain why its small body was valuable in cramped practical interiors.",
      "Identify 3.2K ProRes 4444 capture as Oliver's documented recording choice and distinguish capture raster/codec from the later standard 2K cinema finish.",
      "Explain why 3.2K capture gave post some reframing/resizing latitude without claiming a 4K or native-3.2K theatrical master.",
      "Identify Angénieux compact zooms as the documented primary lens strategy while refusing to fabricate a complete prime/zoom inventory.",
      "Keep exact focal length assignments unresolved except where Oliver explicitly documents a shot or approximate focal range.",
      "Explain why zoom flexibility and minimal lens changes can support a 23-day schedule, especially when two cameras and practical interiors must be serviced quickly.",
      "Identify two cameras on literally every setup as Oliver's documented coverage strategy and distinguish that from a claim that every shot used both cameras in the final edit.",
      "Explain how two-camera coverage can protect performance and schedule while creating lighting, eyeline and camera-placement compromises.",
      "Explain why cross-shooting was used selectively rather than as a universal rule.",
      "Explain Peele and Oliver's use of an in-depth mood board, storyboards and location photoboards as previsualization tools that aligned director, cinematographer and producers before the compressed shoot.",
      "Identify Rosemary's Baby, The Stepford Wives and Candyman as documented broad visual/narrative references and Under the Skin as a specific Sunken Place reference without treating influence as copied shot design.",
      "Explain the city-to-estate visual progression: natural/cool urban realism gives way to a warm, golden and deliberately welcoming estate before more overt horror cues emerge.",
      "Explain why the estate's welcoming warmth is a dramatic misdirection rather than a failure to create horror atmosphere.",
      "Identify the four documented LUT categories for city, estate day, estate night and basement/games-room material.",
      "Explain that the LUTs were developed before production from scouting stills, refined with the DIT, loaded for on-set/dailies viewing and later massaged in the DI.",
      "Keep the exact LUT matrices, CDL values, display transforms and final DI node graph unresolved unless color-facility records establish them.",
      "Distinguish trailer grades from the final DI: early marketing color is not authoritative evidence for the released feature's final look.",
      "Explain the Walter night scene as a planned long-distance-lighting problem using mapped camera/light positions, distant HMIs, selective green/cyan contamination and foreground fill.",
      "Keep any single documented color-temperature or gel setup local to that scene rather than promoting it to a film-wide exposure rule.",
      "Identify The Sunken Place as the principal stage-like exception to the otherwise practical-location production strategy.",
      "Explain that the civic center was treated as a stage rather than assuming a conventional purpose-built soundstage booking.",
      "Identify the limited wire suspension, fans and 200-fps Alexa Mini photography as documented practical components of the Sunken Place illusion.",
      "Explain how horizontal body orientation and dolly movement substituted for a much larger overhead crane/wire solution on specific falling imagery.",
      "Distinguish practical Sunken Place photography from post work: editor Gregory Plotkin describes resizing and temporary wire cleanup, with final CGI adding particulate and wire removal rather than replacing the whole performance.",
      "Keep exact wire-rig geometry, harness models, safety calculations, VFX vendor ownership, software and per-shot compositing recipes unresolved unless stronger records establish them.",
      "Identify Gregory Plotkin as editor and explain his horror/comedy timing principle: setup duration, withholding and release can function like joke timing without collapsing horror into comedy.",
      "Explain Plotkin's preference for holding shots and using negative space to build discomfort rather than cutting simply because coverage exists.",
      "Explain why performance can carry unease without an added sting, using the Georgina/dessert example as evidence for editorial restraint rather than a ban on music or effects stings.",
      "Explain the deer-hit and Walter-running sequences as examples of establishing spatial expectation before changing the timing/context of the threat.",
      "Explain why picture editing should work dramatically before music becomes a corrective layer, following Plotkin's stated workflow principle.",
      "Identify Avid as documented for Sunken Place resizing/temp cleanup while keeping the exact Avid version, shared-storage architecture and assistant-editor turnover system unresolved.",
      "Explain that temporary effects in editorial are communication/proof-of-concept tools and not evidence that picture editorial delivered final VFX.",
      "Explain the alternate-ending process as a version-control problem: preserve what was shot, audience response, thematic consequences and final editorial choice separately.",
      "Explain why test-screening response informed the ending without proving that test scores mechanically dictated every cut.",
      "Separate audience research from authorship: Peele and Plotkin retained thematic goals while changing the final release resolution.",
      "Identify Rusty Smith as production designer and keep exact set-build budgets, art-department crew-day allocations and dressing inventories unresolved unless department records are recovered.",
      "Explain why the practical estate needed to look affluent and East Coast-coded without appearing so ostentatious or regionally Southern that it broke the story's social premise.",
      "Identify Michael Abels as composer and treat Get Out as his feature-film scoring breakthrough without converting later career information into production evidence for this title.",
      "Explain Peele's request for a distinctly Black sonic voice without stereotype as a creative brief that shaped the score's choral and harmonic language.",
      "Identify Abels' 'gospel horror' formulation as a documented conceptual response to that brief.",
      "Explain the Swahili choral warning material as a designed point-of-view/ancestral voice around Chris rather than generic exotic horror texture.",
      "Explain why the score can carry cultural meaning and suspense simultaneously without treating translated lyric paraphrases as production-sound dialogue.",
      "Use Mix reporting on 5.1-oriented score delivery as evidence for music-post complexity while keeping the complete final dub stem map and theatrical loudness settings outside the locked layer.",
      "Keep production sound mixer hardware, microphones, radio systems, ADR chain, foley stage, re-recording console and plugin stack unresolved unless primary records establish them.",
      "Distinguish original score, licensed songs, production sound, editorial sound effects and final re-recording as separate ownership/clearance layers.",
      "Explain that a low-budget production can still require sophisticated digital capture, LUT management, editorial temp effects, score mixing and final DI rather than equating low budget with technically simple post.",
      "Separate production evidence from reception: box office, awards and later cultural status do not prove the 23-day workflow, lens choice, editorial method or sound chain.",
      "Maintain an uncertainty register for exact department budgets, incentive amount, full camera/lens inventory, shot-level focal map, exposure values, full lighting package, LUT math, wire geometry, VFX vendor/software list, production-sound hardware, DI settings, test-screening score history and exact final-dub topology.",
      "Build a closing production audit that checks runtime/version provenance, 23-day schedule evidence, location/incentive logic, two-camera coverage, capture/finish boundaries, LUT lineage, Sunken Place practical/VFX handoff, editorial versioning, production-design constraints, score/sound ownership and unresolved technical claims before verification."
    ],
    phases: [
      { id: "evidence_hierarchy", label: "Map the Get Out evidence hierarchy", player_task: "Separate BFI/AFI catalogue metadata, ASC/Filmmaker cinematography testimony, editor interviews, composer/mix reporting and later reception before promoting claims." },
      { id: "runtime_version", label: "Lock runtime and version metadata", player_task: "Use 103 minutes as the BFI/AFI anchor while logging 104- and 105-minute catalogue variants instead of silently normalizing them." },
      { id: "industrial_model", label: "Define the low-budget genre model", player_task: "Map Blumhouse/QC/Universal roles, low-budget constraints and creative control without inventing department allocations or financing shares." },
      { id: "schedule_lock", label: "Lock the 23-day schedule", player_task: "Treat 23 principal-photography days as a hard planning fact while keeping additional-photography timing separate until sourced." },
      { id: "location_incentive", label: "Reconcile California and Alabama", player_task: "Record the incentive-driven move to Alabama and keep filming geography distinct from the story's East Coast social setting." },
      { id: "hero_house", label: "Secure the Armitage house", player_task: "Choose a practical estate that reads affluent and East Coast-coded without unwanted Southern or mansion-scale signals." },
      { id: "location_protection", label: "Protect the practical location", player_task: "Design lighting and grip plans that avoid drilling and permanent ceiling rigging in the private home." },
      { id: "previsualization", label: "Build boards and photoboards", player_task: "Use Peele's storyboards/mood board and staged location stills to align framing, blocking, light and producer expectations before the compressed shoot." },
      { id: "camera_package", label: "Lock the Alexa Mini boundary", player_task: "Use ARRI Alexa Mini as the documented principal camera while refusing unsourced extra bodies, sensor modes or secondary-camera models." },
      { id: "lens_strategy", label: "Lock Angénieux zoom strategy", player_task: "Use documented compact zoom coverage and preserve shot-specific focal lengths only where Oliver explicitly names them." },
      { id: "recording_format", label: "Lock capture and finish", player_task: "Track 3.2K ProRes 4444 capture separately from the standard 2K cinema finish and later home-video deliverables." },
      { id: "two_camera_plan", label: "Plan two-camera coverage", player_task: "Use two cameras on every setup as the coverage strategy while logging cross-shoot compromises and final-use uncertainty." },
      { id: "look_progression", label: "Design the visual deception", player_task: "Move from cool/natural city realism to welcoming golden estate warmth, then introduce more unsettling color and contrast as the threat becomes legible." },
      { id: "lut_package", label: "Build the four-LUT package", player_task: "Track city, estate-day, estate-night and basement/games-room LUT intent from scout stills through on-set/dailies use and DI refinement." },
      { id: "lut_unknowns", label: "Bound LUT technical claims", player_task: "Keep exact matrices, CDL values, display transforms and DI nodes outside the verified layer without facility records." },
      { id: "dinner_lighting", label: "Solve the practical-house dinner", player_task: "Use mobile overhead support such as the MAX Menace Arm and small fixtures to preserve the house and keep coverage fast." },
      { id: "walter_night", label: "Map the Walter night scene", player_task: "Pre-map distant and near lighting, camera positions and color contamination while keeping that setup local to the scene." },
      { id: "sunken_place_stage", label: "Build the Sunken Place stage exception", player_task: "Treat the civic center as a stage-like controlled space within an otherwise location-heavy production." },
      { id: "sunken_place_practical", label: "Execute the practical Sunken Place", player_task: "Coordinate limited wire suspension, fans, body orientation, dolly movement and 200-fps capture without inventing rig geometry." },
      { id: "sunken_place_post", label: "Hand the Sunken Place to post", player_task: "Separate editorial resizing/temp wire cleanup from final wire removal and particulate VFX rather than calling the whole sequence CGI." },
      { id: "vfx_unknowns", label: "Bound VFX claims", player_task: "Keep complete shot counts, vendors, software, simulation settings and compositing recipes unresolved without primary VFX records." },
      { id: "performance_coverage", label: "Protect performance under schedule", player_task: "Use two-camera coverage and selective cross-shooting to preserve actor continuity without accepting unnecessary lighting compromise." },
      { id: "editorial_timing", label: "Build horror timing", player_task: "Use holds, expectation, negative space and performance to create dread instead of treating faster cutting as automatic intensity." },
      { id: "sound_restraint", label: "Test silence versus stings", player_task: "Evaluate whether image/performance already carries the beat before adding an editorial sting or temp-score accent." },
      { id: "avid_temp_vfx", label: "Build editorial temp effects", player_task: "Use documented Avid resizing and temporary cable cleanup as communication tools while reserving final VFX ownership for finishing." },
      { id: "ending_versions", label: "Track alternate endings", player_task: "Maintain separate edit/version records for the darker arrest ending and the released Rod-rescue resolution." },
      { id: "audience_response", label: "Interpret test-screening evidence", player_task: "Use audience response as one input while preserving theme, authorship and the difference between a screening result and a direct edit command." },
      { id: "production_design", label: "Map production-design ownership", player_task: "Keep Rusty Smith's documented production-design role distinct from location choice, cinematography and set decoration." },
      { id: "score_brief", label: "Define the Black sonic brief", player_task: "Translate Peele's request for a distinctly Black voice without stereotype into composer-facing musical constraints." },
      { id: "gospel_horror", label: "Develop gospel horror", player_task: "Use Abels' formulation to develop choral/harmonic threat while preserving point of view and cultural specificity." },
      { id: "swahili_voice", label: "Track the Swahili warning layer", player_task: "Treat choral language as composed score material with its own lyric/recording provenance rather than production dialogue." },
      { id: "score_mix", label: "Prepare score delivery", player_task: "Track documented 5.1-oriented score-mix complexity while keeping the final dub's complete stem topology unresolved." },
      { id: "sound_boundaries", label: "Separate sound ownership layers", player_task: "Keep production sound, ADR, effects, music editing, original score and final rerecording distinct unless credits explicitly join them." },
      { id: "sound_unknowns", label: "Bound sound hardware claims", player_task: "Keep microphones, recorders, radio systems, ADR chain, foley stage, console and plugin details unresolved without title-specific records." },
      { id: "di_finish", label: "Close the 2K DI boundary", player_task: "Track the standard 2K cinema finish and final color refinement without importing trailer grades or home-video specs as theatrical proof." },
      { id: "uncertainty_register", label: "Maintain the Get Out unknowns register", player_task: "Track department budgets, incentive amount, full lens map, exposure, lighting inventory, LUT math, wire geometry, VFX stack, sound hardware, DI settings and test-screening score history explicitly." },
      { id: "chapter18_position", label: "Position Get Out in digital convergence", player_task: "Explain how a low-budget social-horror production used digital capture, LUTs, fast coverage, editorial temp effects and sophisticated post without blockbuster scale." },
      { id: "delivery_audit", label: "Audit the complete Get Out production system", player_task: "Verify runtime/version, schedule, location/incentive logic, camera/codec/finish, LUT lineage, Sunken Place handoff, editorial versions, production design, score/sound boundaries and unknowns before closure." }
    ]
  }
] as const;

export function mergeChapterEighteenGetOutExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterEighteenGetOutExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_eighteen_get_out_verified",
      source: { list_id: "manual_chapter_eighteen_get_out_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}