import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterNineteenCollectiveExpansionDefinitions = [
  {
    id: "scenario_collective_2020",
    title: "Collective",
    originalTitle: "Colectiv",
    aliases: ["Collective", "Colectiv"],
    year: 2020,
    titleType: "Movie",
    runtimeMins: 109,
    directors: ["Alexander Nanau"],
    genres: ["Documentary"],
    sourceId: "european_film_academy_collective_2020",
    sourceUrl: "https://vod.europeanfilmacademy.org/videos/collective",
    scenarioType: "nonfiction_hybrid_romanian_observational_documentary_investigative_journalism_whistleblower_access_public_institution_accountability_small_crew_single_operator_location_sound_archive_fire_footage_four_copy_data_security_14_month_shoot_18_month_edit_multi_editor_structure_transnational_coproduction_festival_platform_circulation_2020",
    premise: "Build Collective as Chapter 19's nonfiction/hybrid rotation case while keeping documentary evidence, access, ethics, risk, authorship, post-production and circulation separate. The European Film Academy records a 109-minute Romania/Luxembourg film under the original title Colectiv, directed and photographed by Alexander Nanau, scripted by Antoaneta Opris and Nanau, edited by Nanau, George Cragg and Dana Bunescu, with sound credited to Angelo Dos Santos, and explicitly describes Nanau's method as observational with no interviews and no voice-over. IDFA separately records the 2019 festival object at 109 minutes, credits Nanau and Bianca Oana for production, HBO Europe and Samsa Film for co-production, Nanau for cinematography, Nanau/Cragg/Bunescu for editing, and Michel Schillings, Mihai Grecea and Angelo Dos Santos for sound. Magnolia's official production notes state that Nanau and HBO Europe executive producer Hanka Kastelicova began discussing the project in November 2015 after the Colectiv fire and protests, that shooting took place over 14 months, editing over another 18 months, and the full co-production involved about 60 people from several European countries. Nanau's BFI interview defines the production method more narrowly than the final co-production headcount: he says he does not intervene or ask people to reenact actions, that trust is built over time, and that footage improves as subjects become comfortable with the project. Reporting and interviews describe a deliberately small field presence, often Nanau with one camera and at times a single sound collaborator, because newsroom, whistleblower and ministry access could be damaged by a larger crew. Reverse Shot documents the sound strategy as adaptive: Nanau could begin with a recorder placed in the room and a camera-mounted boom, moving to body microphones only when subjects were comfortable; Mihai Grecea, a Colectiv survivor and filmmaker, became a close sound collaborator who learned Nanau's fast reactive method. Film Inquiry documents a security workflow developed under perceived surveillance risk in which footage was copied each evening to four separate destinations, dispersed with different people, with material periodically moved outside the country. That claim supports redundancy and risk planning for this title without licensing a universal documentary-security recipe. The film also incorporates pre-existing Colectiv-club fire footage rather than pretending every image was generated by Nanau's observational unit; interviews identify survivor/filmmaker Mihai Grecea as a key bridge to that material and to the victims' community. Filmmaker Magazine and Hyperallergic document Nanau's editorial process: he first cuts himself for months, brings George Cragg in for a short structural pass that can radically reshuffle story arcs, resumes editing alone, and later brings Dana Bunescu in to remove ballast and consolidate the final structure. That long post process is consistent with the official 18-month edit but does not establish exact software versions, storage topology, assistant-editor staffing, proxy formats or conform details. The player must therefore coordinate consent and trust, access to journalists and public officials, source protection, whistleblower safety, survivor representation, observational non-intervention, embedded small-crew coverage, evolving story focus, pre-existing fire footage, production sound, data redundancy, legal and editorial risk, 14 months of shooting, 18 months of editing, three-editor structural authorship, Romania/Luxembourg co-production, public and broadcaster support, world sales and 2019-to-2020 festival/theatrical/platform circulation while keeping exact budget, financing shares, access agreements, releases, newsroom confidentiality protocols, legal review memos, insurance, complete shooting calendar, camera body/lens/codec/frame-rate settings, exact microphone/recorder package, encryption implementation, all backup locations, complete archive-rights chain, translation/subtitle workflow, edit software/version, storage architecture, color pipeline, mix chain and distribution terms unresolved unless title-specific public evidence establishes them.",
    requiredChoicesSeed: {
      screenplay: ["observational_no_interviews", "no_voice_over", "evolving_real_time_story", "journalism_and_ministry_access", "archive_fire_footage", "109_minute_runtime"],
      camera: ["alexander_nanau_cinematography", "small_field_presence", "single_operator_observation", "access_over_coverage_scale", "camera_package_unknown", "shot_metadata_unknown"],
      editing: ["alexander_nanau_edit", "george_cragg_structure_pass", "dana_bunescu_final_structure", "14_month_shoot", "18_month_edit", "editorial_topology_unknown"],
      sound: ["mihai_grecea_sound_collaboration", "adaptive_microphone_intrusion", "camera_boom_and_room_recorder", "body_mics_after_trust", "sound_chain_unknown"],
      themes: ["film_history", "2020", "collective", "colectiv", "alexander_nanau", "romanian_cinema", "nonfiction_hybrid", "observational_documentary", "investigative_journalism", "whistleblowers", "institutional_accountability", "access_ethics", "small_crew", "data_security", "archive_footage", "long_form_editing", "transnational_coproduction", "festival_circulation", "platform_circulation", "balanced_rotation", "chapter19"]
    },
    learningGoals: [
      "Explain Collective as Chapter 19's third balanced-rotation case and the first nonfiction/hybrid lane case after Nomadland and Drive My Car.",
      "Use the European Film Academy's 109-minute record as the canonical playable runtime anchor while preserving the film's 2019 festival origin and 2020 Chapter 19 circulation role as separate chronology layers.",
      "Identify Alexander Nanau as director and cinematographer without treating those combined credits as proof that he performed every production function alone.",
      "Identify Antoaneta Opris and Alexander Nanau as credited script authors while explaining that documentary scripting can organize an evolving nonfiction structure rather than predetermine real events.",
      "Explain the European Film Academy's explicit no-interviews/no-voice-over statement as a production-method constraint rather than a claim that the film contains no mediated or pre-existing material.",
      "Explain observational non-intervention as Nanau's refusal to ask subjects to perform or reenact actions for camera while preserving the filmmaker's active choices of access, framing, duration and editing.",
      "Explain why observational documentary is not neutral surveillance: proximity, trust, selection, camera placement and editorial structure remain authored decisions.",
      "Identify Catalin Tolontan's investigative newsroom, whistleblowers, survivor communities and Vlad Voiculescu's health ministry as distinct access environments with different confidentiality and risk requirements.",
      "Explain why newsroom access required protecting sources and avoiding production behavior that could expose whistleblowers or interrupt reporting.",
      "Explain why ministry access created a different accountability problem from newsroom access because the camera entered a public institution while policy decisions were unfolding.",
      "Explain Nanau's trust-building method as a long-duration relationship in which subjects gradually become less self-conscious around the production.",
      "Reject the inference that trust removes power imbalance or eliminates the need for continuing ethical judgment about what is filmed and retained.",
      "Explain a very small field presence as an access strategy: one camera and at times one sound collaborator can reduce disruption in sensitive rooms.",
      "Distinguish the small observational field unit from the official production-note statement that roughly 60 people participated across the full transnational co-production.",
      "Explain why total production headcount and on-location crew size measure different layers of documentary labor.",
      "Identify the documented 14-month shooting period as long-form observational commitment rather than evidence that every day of those months was filmed.",
      "Identify the documented 18-month edit as a major production phase in which meaning and story structure continued to be discovered after filming.",
      "Explain why an evolving corruption investigation prevents the production from locking a conventional fiction-style beat sheet before events occur.",
      "Explain Nanau's willingness to change the film's central point of view from journalists toward the incoming health minister as evidence of story discovery during production.",
      "Explain why changing protagonists mid-production affects coverage priorities, access negotiations, chronology and editorial architecture.",
      "Separate contemporaneous observational footage from pre-existing Colectiv-club fire footage so provenance and rights remain inspectable.",
      "Explain why graphic disaster footage demands evidentiary, rights and harm considerations distinct from newly photographed newsroom or ministry scenes.",
      "Identify Mihai Grecea as both a survivor/filmmaker connected to the fire footage and a later close production collaborator without collapsing survivor identity into crew function.",
      "Explain the adaptive sound method in which a room recorder or camera-mounted boom can be less intrusive initially, with body microphones introduced only after subjects become comfortable.",
      "Explain why a body microphone can improve intelligibility while also increasing perceived intrusion and therefore cannot be treated as an automatic documentary default.",
      "Explain why Nanau required a sound collaborator who could react quickly and remain physically coordinated with his camera rather than impose a slower conventional coverage pattern.",
      "Keep exact microphones, recorder models, radio frequencies, timecode architecture, gain staging and final dialogue-processing chain unresolved because the locked sources do not establish them.",
      "Explain the reported four-copy nightly backup routine as a title-specific response to perceived surveillance and break-in risk.",
      "Explain geographic dispersal of copies and periodic movement of material outside Romania as risk management without inferring exact encryption, courier, cloud or storage-vendor details.",
      "Reject the inference that four copies automatically guarantee security; redundancy, confidentiality and access control solve different threat classes.",
      "Explain why source protection and footage protection are linked but not identical: a secure image file can still expose a whistleblower through its content.",
      "Identify Alexander Nanau Production, Samsa Film and HBO Europe as core production/co-production entities while keeping exact financing percentages unresolved.",
      "Identify Romanian Film Centre, Film Fund Luxembourg, Sundance Documentary Fund and broadcaster participation as documented support layers without inventing amounts or recoupment terms.",
      "Explain Romania/Luxembourg co-production as a financing, institutional and post-production network rather than a generic label for 'European documentary.'",
      "Identify Nanau, George Cragg and Dana Bunescu as distinct editorial contributors and preserve their different documented functions in the long edit.",
      "Explain Nanau's initial self-editing period as an exploratory assembly stage rather than proof of a locked director's cut.",
      "Explain George Cragg's short structural intervention as permission to test radical rearrangements of story arcs and scene halves rather than merely trim duration.",
      "Explain Dana Bunescu's later role as a decisive consolidation pass that removes ballast and helps the complete film cohere.",
      "Reject the idea that three credited editors imply simultaneous equal labor on every scene; the documented workflow is staged and iterative.",
      "Keep exact edit software, project version, assistant-editor database, proxy format, sync method, storage topology and conform workflow outside the verified layer unless sourced.",
      "Explain the 109-minute final structure as the result of selection across a much longer observation period, not as a transparent transcript of reality.",
      "Separate documentary evidence from journalistic evidence: the film observes reporters verifying claims, but the production itself must still verify provenance, context and editorial use of what it shows.",
      "Explain why public-interest subject matter does not remove consent, confidentiality, defamation, privacy, safety or archive-rights questions from production planning.",
      "Explain 2019 Venice/IDFA-era festival circulation and 2020 theatrical/platform circulation as release history rather than proof that the production method is intrinsically superior.",
      "Explain the pandemic-era movement from Romanian cinemas to HBO Europe's platform as a circulation event affecting audience access, not a production-stage event inside the 2015-2017 observational shoot.",
      "Maintain an uncertainty register for budget, financing shares, access agreements, releases, legal review, insurance, source-protection protocols, camera/lens settings, sound package, security implementation, archive rights, translation, editorial infrastructure, color, mix and distribution contracts.",
      "Explain Collective's Chapter 19 importance as a production history of access under uncertainty: journalism unfolds in real time, institutional doors open and close, a tiny field unit protects intimacy, data security becomes physical production work, and an 18-month edit turns evolving events into a coherent feature.",
      "Build a closing production audit that checks source hierarchy, chronology, observation versus archive, access ethics, field-crew scale, sound intrusion, data risk, co-production, editorial authorship, circulation and unresolved claims before Production Verification."
    ],
    phases: [
      { id: "evidence_hierarchy", label: "Map the Collective evidence hierarchy", player_task: "Separate institutional credits and production notes from filmmaker interviews, secondary reporting and interpretive reviews before promoting craft claims." },
      { id: "chronology_lock", label: "Separate 2019 origin from 2020 circulation", player_task: "Keep the 2019 festival object and 2020 Chapter 19 candidate year explicit so release chronology does not masquerade as production chronology." },
      { id: "method_lock", label: "Lock the observational method", player_task: "Use no interviews and no voice-over as the documented formal baseline while retaining framing and editing as active authorship." },
      { id: "non_intervention", label: "Protect non-intervention", player_task: "Do not ask subjects to reenact actions or manufacture scenes for the camera." },
      { id: "access_map", label: "Map access environments", player_task: "Treat newsroom, whistleblower, survivor and ministry access as separate permissions, risks and production relationships." },
      { id: "trust_building", label: "Build trust over time", player_task: "Reduce production self-consciousness through continuity and predictable behavior rather than promises of favorable portrayal." },
      { id: "newsroom_confidentiality", label: "Protect newsroom source boundaries", player_task: "Avoid coverage choices that expose confidential sources, unpublished evidence or investigative strategy." },
      { id: "ministry_access", label: "Enter the health ministry", player_task: "Use unusual institutional access without treating proximity to officials as endorsement or surrendering editorial independence." },
      { id: "small_field_unit", label: "Keep the field unit small", player_task: "Prioritize access and low disruption with Nanau operating camera and only essential sound/production presence in sensitive rooms." },
      { id: "crew_scale_split", label: "Separate field crew from co-production headcount", player_task: "Reconcile the tiny observational unit with the roughly 60-person full co-production team as different production layers." },
      { id: "long_observation", label: "Sustain fourteen months of shooting", player_task: "Plan continuity, availability and data management across a long observation window without inventing a day-by-day schedule." },
      { id: "story_discovery", label: "Let the real-time story change", player_task: "Reassess protagonists and coverage as the investigation and government response evolve rather than forcing events into a prewritten fiction template." },
      { id: "point_of_view_shift", label: "Shift from newsroom to ministry", player_task: "Rebalance access and editorial attention when Vlad Voiculescu becomes a central route into the state system." },
      { id: "archive_provenance", label: "Separate fire footage provenance", player_task: "Track pre-existing Colectiv-club imagery as archive/source material rather than presenting it as footage made by the observational unit." },
      { id: "survivor_boundary", label: "Protect survivor representation", player_task: "Treat grief, injury and survivor testimony as ethically distinct from institutional accountability footage." },
      { id: "sound_low_intrusion", label: "Start sound with low intrusion", player_task: "Use room recording and camera boom strategies when body microphones would alter access or participant comfort." },
      { id: "body_mic_trust", label: "Add body microphones only after trust", player_task: "Introduce closer microphones only when participants are comfortable and the additional intrusion is justified." },
      { id: "sound_camera_coordination", label: "Coordinate reactive camera and sound", player_task: "Keep the sound collaborator physically and rhythmically connected to Nanau's fast observational movement." },
      { id: "data_threat_model", label: "Model footage threats", player_task: "Treat surveillance, office intrusion, confiscation, accidental loss and source exposure as different risks requiring different controls." },
      { id: "four_copy_backup", label: "Create four nightly copies", player_task: "Use the documented four-copy redundancy as a title-specific security response without pretending copy count alone equals protection." },
      { id: "disperse_media", label: "Disperse copies physically", player_task: "Separate storage locations and custodians so one intrusion cannot destroy the entire record." },
      { id: "offshore_copy", label: "Move selected material outside the country", player_task: "Use geographic separation as additional resilience while leaving exact transport and encryption implementation unresolved." },
      { id: "coproduction_map", label: "Map the transnational co-production", player_task: "Separate Alexander Nanau Production, Samsa Film, HBO Europe and public/broadcaster support rather than treating all money as one pool." },
      { id: "finance_unknowns", label: "Keep financing shares unresolved", player_task: "Record named support institutions without inventing grant amounts, equity percentages, recoupment or rights splits." },
      { id: "first_edit", label: "Build Nanau's first edit", player_task: "Let the director assemble and discover the story for months before treating structure as settled." },
      { id: "cragg_structure", label: "Run George Cragg's structural pass", player_task: "Test alternate story arcs, reorder scenes and split material when the rough cut reveals stronger structures." },
      { id: "return_to_edit", label: "Return to solo refinement", player_task: "Resume detailed editing after the structural intervention instead of freezing Cragg's experiments as final." },
      { id: "bunescu_consolidation", label: "Bring in Dana Bunescu", player_task: "Remove ballast and consolidate the long-form structure with a fresh late-stage editorial eye." },
      { id: "eighteen_month_post", label: "Sustain eighteen months of editing", player_task: "Budget post as a prolonged story-discovery phase rather than a short technical finishing window." },
      { id: "legal_editorial_review", label: "Review legal and editorial risk", player_task: "Check source protection, privacy, context, archive provenance and public-interest justification without inventing unpublished counsel memos." },
      { id: "sound_finish", label: "Separate field sound from final sound work", player_task: "Preserve named production-sound contributors and later sound authorship without guessing the recorder, plug-in, stem or mix chain." },
      { id: "festival_circulation", label: "Map 2019 festival circulation", player_task: "Keep Venice and later documentary-festival visibility in the release layer rather than using awards as production evidence." },
      { id: "pandemic_distribution", label: "Track 2020 platform circulation", player_task: "Separate pandemic-era cinema closure and HBO Europe viewing from the earlier observational production timeline." },
      { id: "unknowns_register", label: "Maintain the Collective unknowns register", player_task: "Track access contracts, releases, finance, legal review, camera, sound, backups, archive rights, translation, edit infrastructure, color, mix and distribution unknowns explicitly." },
      { id: "delivery_review", label: "Audit the complete Collective production system", player_task: "Verify chronology, observational ethics, access, archive boundaries, field scale, sound, data security, co-production, editorial authorship, circulation and unresolved claims before production verification." }
    ]
  }
] as const;

export function mergeChapterNineteenCollectiveExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterNineteenCollectiveExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_nineteen_collective_verified",
      source: { list_id: "manual_chapter_nineteen_collective_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
