import assert from "node:assert/strict";
import test from "node:test";

import { chapterEighteenIAmNotYourNegroExpansionDefinitions } from "./chapterEighteenIAmNotYourNegroExpansion.js";

test("Chapter 18 materializes I Am Not Your Negro as a source-first hybrid archival documentary production case", () => {
  assert.equal(chapterEighteenIAmNotYourNegroExpansionDefinitions.length, 1);
  const film = chapterEighteenIAmNotYourNegroExpansionDefinitions[0];
  assert.equal(film.id, "scenario_i_am_not_your_negro_2016");
  assert.equal(film.year, 2016);
  assert.equal(film.runtimeMins, 93);
  assert.deepEqual(film.directors, ["Raoul Peck"]);
  assert.ok(film.scenarioType.includes("hybrid_archival_documentary") && film.scenarioType.includes("fair_use") && film.scenarioType.includes("text_first_edit"));
  assert.ok(film.scenarioType.includes("baldwin_estate") && film.scenarioType.includes("remember_this_house") && film.scenarioType.includes("voice_performance"));
  assert.ok(film.premise.includes("Artémis Productions") && film.premise.includes("93-minute") && film.premise.includes("1.85") && film.premise.includes("5.1 DCP"));
  assert.ok(film.premise.includes("Velvet Film") && film.premise.includes("Close Up Films") && film.premise.includes("ARTE France") && film.premise.includes("RTS") && film.premise.includes("RTBF"));
  assert.ok(film.premise.includes("James Baldwin Estate") && film.premise.includes("published and unpublished") && film.premise.includes("ten-year"));
  assert.ok(film.premise.includes("thirty-page Remember This House") && film.premise.includes("structural entry point"));
  assert.ok(film.premise.includes("text") && film.premise.includes("manuscript/libretto") && film.premise.includes("archival researchers"));
  assert.ok(film.premise.includes("Fair Use lawyer") && film.premise.includes("about a year") && film.premise.includes("paid for"));
  assert.ok(film.premise.includes("Henry Adebonojo") && film.premise.includes("Bill and Turner Ross") && film.premise.includes("New York") && film.premise.includes("American South"));
  assert.ok(film.premise.includes("Samuel L. Jackson") && film.premise.includes("Sofia, Bulgaria") && film.premise.includes("temporary voice"));
  assert.ok(film.premise.includes("Alexandra Strauss") && film.premise.includes("layer by layer"));
  assert.ok(film.premise.includes("Valérie Le Docte") && film.premise.includes("David Gillain") && film.premise.includes("Alexei Aigui"));
  assert.ok(film.premise.includes("exact total budget") && film.premise.includes("per-clip license fees") && film.premise.includes("universal Fair Use duration rule"));
  assert.ok(film.premise.includes("exact camera bodies/lenses/codecs") && film.premise.includes("exact scanner/restoration settings") && film.premise.includes("exact edit software/version"));
  assert.ok(film.premise.includes("all third-party footage was cleared under Fair Use"));
  assert.ok(film.requiredChoicesSeed.screenplay.includes("baldwin_words_only"));
  assert.ok(film.requiredChoicesSeed.editing.includes("fair_use_review") && film.requiredChoicesSeed.editing.includes("paid_licensing"));
  assert.ok(film.requiredChoicesSeed.camera.includes("camera_models_unknown"));
  assert.ok(film.requiredChoicesSeed.sound.includes("recording_chain_unknown"));
  assert.ok(film.learningGoals.some((goal) => goal.includes("93-minute") && goal.includes("canonical runtime")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("James Baldwin Estate") && goal.includes("production dependency")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("roughly ten-year") && goal.includes("development")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("thirty-page Remember This House") && goal.includes("structural entry point")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("no-talking-head") && goal.includes("production constraint")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("text-first") && goal.includes("manuscript or libretto")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("archive log") && goal.includes("rights holder") && goal.includes("legal status")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Fair Use") && goal.includes("contextual legal analysis")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("lawyer") && goal.includes("about a year") && goal.includes("edit versions")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("universal number-of-seconds Fair Use rule")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("paid licensing")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("versioned legal status") && goal.includes("duration") && goal.includes("context")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Alexandra Strauss") && goal.includes("structural writing")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("temporary voice track") && goal.includes("final performer")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Samuel L. Jackson") && goal.includes("Baldwin's archival on-camera voice")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Sofia, Bulgaria") && goal.includes("late editing phase")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Henry Adebonojo") && goal.includes("Bill and Turner Ross")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("camera bodies") && goal.includes("codecs") && goal.includes("unresolved")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("1.85") && goal.includes("archival element")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("scanner models") && goal.includes("restoration tools") && goal.includes("unresolved")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Valérie Le Docte") && goal.includes("David Gillain")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Alexei Aigui") && goal.includes("licensed music")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Velvet Film") && goal.includes("Artémis Productions") && goal.includes("Close Up Films")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Rémi Grellety") && goal.includes("Hébert Peck") && goal.includes("financing shares")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("exact total budget") && goal.includes("complete archive inventory") && goal.includes("edit software")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Chapter 18 significance") && goal.includes("hybrid nonfiction")));
  assert.ok(film.phases.find((phase) => phase.id === "released_version")?.player_task.includes("93-minute"));
  assert.ok(film.phases.find((phase) => phase.id === "estate_relationship")?.player_task.includes("third-party media"));
  assert.ok(film.phases.find((phase) => phase.id === "fair_use_review")?.player_task.includes("edit version"));
  assert.ok(film.phases.find((phase) => phase.id === "legal_edit_loop")?.player_task.includes("revised version"));
  assert.ok(film.phases.find((phase) => phase.id === "camera_unknowns")?.player_task.includes("camera bodies"));
  assert.ok(film.phases.find((phase) => phase.id === "sofia_recording")?.player_task.includes("studio/hardware details"));
  assert.ok(film.phases.find((phase) => phase.id === "unknowns_register")?.player_task.includes("clip fees") && film.phases.find((phase) => phase.id === "unknowns_register")?.player_task.includes("mix specifications"));
  assert.ok(film.learningGoals.length >= 55);
  assert.ok(film.phases.length >= 35);
});