import assert from "node:assert/strict";
import test from "node:test";

import { chapterNineteenTenetExpansionDefinitions } from "./chapterNineteenTenetExpansion.js";

test("Chapter 19 materializes Tenet as a source-first large-format photochemical inversion and pandemic-release production case", () => {
  assert.equal(chapterNineteenTenetExpansionDefinitions.length, 1);
  const film = chapterNineteenTenetExpansionDefinitions[0];
  assert.equal(film.id, "scenario_tenet_2020");
  assert.equal(film.title, "Tenet");
  assert.equal(film.originalTitle, "Tenet");
  assert.equal(film.year, 2020);
  assert.equal(film.runtimeMins, 149);
  assert.deepEqual(film.directors, ["Christopher Nolan"]);
  assert.ok(film.scenarioType.includes("photochemical_65mm_imax") && film.scenarioType.includes("forward_reverse_inversion"));
  assert.ok(film.scenarioType.includes("practical_sfx_dneg_vfx") && film.scenarioType.includes("pandemic_release"));
  assert.ok(film.premise.includes("photographed in 2019") && film.premise.includes("2020 theatrical release disrupted by the pandemic"));
  assert.ok(film.premise.includes("149-minute") && film.premise.includes("Emma Thomas") && film.premise.includes("Hoyte van Hoytema"));
  assert.ok(film.premise.includes("Denmark") && film.premise.includes("Estonia") && film.premise.includes("India") && film.premise.includes("Italy") && film.premise.includes("Norway") && film.premise.includes("UK"));
  assert.ok(film.premise.includes("six IMAX camera packages") && film.premise.includes("Panavision Large Format System 65") && film.premise.includes("ARRI 65") && film.premise.includes("Logmar Magellan"));
  assert.ok(film.premise.includes("Sphero 65") && film.premise.includes("15-perf 70mm IMAX"));
  assert.ok(film.premise.includes("both forward and backward directions") && film.premise.includes("sequence-specific evidence"));
  assert.ok(film.premise.includes("Nathan Crowley") && film.premise.includes("Scott Fisher") && film.premise.includes("Jennifer Lame"));
  assert.ok(film.premise.includes("Andrew Jackson") && film.premise.includes("DNEG") && film.premise.includes("Andy Lockley"));
  assert.ok(film.premise.includes("full-size retired 747") && film.premise.includes("set-built building") && film.premise.includes("cable removal and cleanup"));
  assert.ok(film.premise.includes("no VFX") && film.premise.includes("roughly 300-person DNEG effort") && film.premise.includes("6.3K"));
  assert.ok(film.premise.includes("photochemical finish") && film.premise.includes("conventional DI"));
  assert.ok(film.premise.includes("Richard King") && film.premise.includes("Willie Burton") && film.premise.includes("limited looping"));
  assert.ok(film.premise.includes("Ludwig Göransson") && film.premise.includes("score and effects"));
  assert.ok(film.premise.includes("exact film-stock inventory") && film.premise.includes("complete Sphero or other lens-by-shot map"));
  assert.ok(film.premise.includes("exact frame rates") && film.premise.includes("full VFX shot ledger") && film.premise.includes("music stems"));
  assert.ok(film.premise.includes("COVID-19 protocols") && film.premise.includes("principal photography") && film.premise.includes("2019"));

  assert.ok(film.requiredChoicesSeed.screenplay.includes("pandemic_release_not_pandemic_shoot"));
  assert.ok(film.requiredChoicesSeed.camera.includes("imax_15perf_70mm") && film.requiredChoicesSeed.camera.includes("panavision_system65") && film.requiredChoicesSeed.camera.includes("logmar_magellan_65mm"));
  assert.ok(film.requiredChoicesSeed.editing.includes("jennifer_lame") && film.requiredChoicesSeed.editing.includes("forward_reverse_continuity"));
  assert.ok(film.requiredChoicesSeed.sound.includes("richard_king") && film.requiredChoicesSeed.sound.includes("willie_burton") && film.requiredChoicesSeed.sound.includes("ludwig_goransson"));
  assert.ok(film.requiredChoicesSeed.themes.includes("practical_effects") && film.requiredChoicesSeed.themes.includes("visual_effects") && film.requiredChoicesSeed.themes.includes("photochemical_finish"));

  assert.ok(film.learningGoals.some((goal) => goal.includes("2019 production") && goal.includes("pandemic-disrupted 2020 release")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("BFI 149-minute") && goal.includes("playable runtime anchor")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("six IMAX camera packages") && goal.includes("shot-by-shot")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("System 65 Studio") && goal.includes("Sphero 65")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("ARRI 65") && goal.includes("Logmar Magellan")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("15-perf 70mm IMAX") && goal.includes("expanded")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("exact Kodak stock") && goal.includes("unresolved")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("forward and backward directions") && goal.includes("without generalizing")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Nathan Crowley") && goal.includes("two temporal directions")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Denmark") && goal.includes("Estonia") && goal.includes("India") && goal.includes("Norway")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Scott Fisher") && goal.includes("DNEG")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("false claim") && goal.includes("no VFX")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("full-size 747") && goal.includes("digital cleanup")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("747 hit a set-built structure") && goal.includes("cable removal")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Andrew Jackson") && goal.includes("Andy Lockley")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("roughly 300-person") && goal.includes("company testimony")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("photography and LIDAR") && goal.includes("contingency")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("6.3K") && goal.includes("full scan-resolution lineage unresolved")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("photochemical-finish") && goal.includes("digital intermediate")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Jennifer Lame") && goal.includes("forward and inverted action")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Richard King") && goal.includes("sound-design")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Willie Burton") && goal.includes("masked dialogue")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("limited looping") && goal.includes("ADR census")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Ludwig Göransson") && goal.includes("Richard King")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("COVID-19 lockdown") && goal.includes("2019")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("return-to-work protocols") && goal.includes("principal photography")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("uncertainty register") && goal.includes("VFX ledger") && goal.includes("mix topology")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Chapter 19 significance") && goal.includes("photochemical large-format production")));

  assert.ok(film.phases.find((phase) => phase.id === "chronology_boundary")?.player_task.includes("2019"));
  assert.ok(film.phases.find((phase) => phase.id === "large_format_strategy")?.player_task.includes("IMAX 15-perf 70mm") && film.phases.find((phase) => phase.id === "large_format_strategy")?.player_task.includes("65mm"));
  assert.ok(film.phases.find((phase) => phase.id === "system65")?.player_task.includes("Sphero 65"));
  assert.ok(film.phases.find((phase) => phase.id === "dual_direction_capture")?.player_task.includes("key inversion sequences") && film.phases.find((phase) => phase.id === "dual_direction_capture")?.player_task.includes("not claiming every"));
  assert.ok(film.phases.find((phase) => phase.id === "sfx_vfx_boundary")?.player_task.includes("Scott Fisher") && film.phases.find((phase) => phase.id === "sfx_vfx_boundary")?.player_task.includes("Andrew Jackson/DNEG"));
  assert.ok(film.phases.find((phase) => phase.id === "plane_sequence")?.player_task.includes("full-size aircraft") && film.phases.find((phase) => phase.id === "plane_sequence")?.player_task.includes("cable removal"));
  assert.ok(film.phases.find((phase) => phase.id === "photochemical_finish")?.player_task.includes("photochemical finishing"));
  assert.ok(film.phases.find((phase) => phase.id === "production_dialogue")?.player_task.includes("Willie Burton"));
  assert.ok(film.phases.find((phase) => phase.id === "post_lockdown")?.player_task.includes("2019 shoot"));
  assert.ok(film.phases.find((phase) => phase.id === "unknowns_register")?.player_task.includes("VFX ledger") && film.phases.find((phase) => phase.id === "unknowns_register")?.player_task.includes("ADR"));
  assert.ok(film.learningGoals.length >= 55);
  assert.ok(film.phases.length >= 35);
});
