import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterEighteenIAmNotYourNegroExpansionDefinitions = [
  {
    id: "scenario_i_am_not_your_negro_2016",
    title: "I Am Not Your Negro",
    originalTitle: "I Am Not Your Negro",
    aliases: [],
    year: 2016,
    titleType: "Movie",
    runtimeMins: 93,
    directors: ["Raoul Peck"],
    genres: ["Documentary"],
    sourceId: "artemis_i_am_not_your_negro_2016",
    sourceUrl: "https://www.artemisproductions.com/en/films/I_Am_Not_Your_Negro",
    scenarioType: "hybrid_archival_documentary_baldwin_estate_remember_this_house_fair_use_licensed_archive_text_first_edit_voice_performance_contemporary_footage_transnational_coproduction_2016",
    premise: "Build I Am Not Your Negro as a source-first Chapter 18 Production Case about how literary rights, estate trust, archival research and acquisition, Fair Use review, text-first montage, contemporary photography, voice performance, sound design and a transnational documentary co-production became one production system. Artémis Productions anchors a 93-minute 2016 film, color/black-and-white, 1.85 presentation and 5.1 DCP metadata; it credits Raoul Peck as director, Henry Adebonojo plus Bill and Turner Ross as directors of photography, Alexandra Strauss as picture editor, Valérie Le Docte as sound editor, David Gillain as sound mixer and Alexei Aigui as composer. PBS Independent Lens documents Velvet Film in co-production with Artémis Productions and Close Up Films, additional co-production with ARTE France, RTS Radio Télévision Suisse, RTBF and Shelter Prod, producers Rémi Grellety, Raoul Peck and Hébert Peck, co-producers Patrick Quinet and Joëlle Bertossa, Samuel L. Jackson as the voice, Alexandra Strauss as editor, archival research credit and full support/collaboration from the James Baldwin Estate. Peck and producer Hébert Peck describe a roughly ten-year development in which the Estate granted unusually broad access to Baldwin's published and unpublished body of work, letters and photographs. The project spent years testing forms before the thirty-page Remember This House material became the structural entry point. Peck describes beginning with Baldwin's text: he assembled a dramatic manuscript/libretto, while archival researchers searched film, radio, television, photographs and other records around Baldwin and the histories he invoked. The archive was not a neutral stock-footage library. Peck's team had to identify, acquire, license or legally justify individual materials, and he reports that a Fair Use lawyer worked with them for about a year across edit versions, sometimes forcing changes in duration or context. Some material still had to be licensed and paid for. This makes legal review, provenance, clip duration, contextual transformation and budget control editorial variables rather than administrative afterthoughts. Peck also describes physically laying archival material out to build a first structure and then developing the film layer by layer with editor Alexandra Strauss, repeatedly returning to Baldwin's books, footnotes, images, music and newly discovered connections. Contemporary footage was photographed by Henry Adebonojo and Bill and Turner Ross, including material from New York and the American South, so the film's image system combines historical archive, photographs, cinema excerpts, television, graphics and new production rather than pretending all images share one capture provenance. Samuel L. Jackson entered near the final editing phase; Peck sent him a cut and then recorded him in a studio in Sofia, Bulgaria, directing the performance as Baldwin's character rather than conventional explanatory narration. A temporary voice had been used during editing, allowing text and timing to evolve before the final performance. Peck explicitly rejected talking-head interpretation and wanted Baldwin's words to remain the governing verbal layer. Sound and music were treated with narrative-film intensity, using reconstruction, silence, music and image-sound juxtaposition to make archival material function dramatically. The player must coordinate estate rights, unpublished-text provenance, script/libretto construction, archival search and metadata, source quality, Fair Use versus paid licensing, legal notes by edit version, contemporary-location shoots, archive/new-footage visual transitions, typography/graphics, temporary and final voice recording, editorial layer-building, music clearance/composition, sound design, mix and delivery while refusing unsupported exact total budget, exact per-clip license fees, a universal Fair Use duration rule, complete archival source inventory, exact camera bodies/lenses/codecs for every contemporary unit, exact scanner/restoration settings for archive, exact temporary-voice recording chain, exact Samuel L. Jackson microphone/recorder chain, exact edit software/version, complete graphics software stack, exact music stem layout or a claim that all third-party footage was cleared under Fair Use.",
    requiredChoicesSeed: {
      screenplay: ["baldwin_words_only", "remember_this_house_spine", "text_first_libretto", "three_lives_structure", "no_talking_heads", "estate_provenance"],
      camera: ["archive_source_separation", "new_footage_units", "henry_adebonojo", "bill_turner_ross", "new_york_south_geography", "camera_models_unknown"],
      editing: ["alexandra_strauss", "layered_montage", "archive_metadata", "fair_use_review", "paid_licensing", "temporary_voice", "versioned_legal_notes"],
      sound: ["samuel_l_jackson_voice", "sofia_recording", "valerie_le_docte", "david_gillain", "alexei_aigui", "silence_music_archive_sound", "recording_chain_unknown"],
      themes: ["film_history", "2016", "i_am_not_your_negro", "raoul_peck", "james_baldwin", "remember_this_house", "baldwin_estate", "archival_documentary", "fair_use", "rights_clearance", "hybrid_nonfiction", "text_first_editing", "samuel_l_jackson", "alexandra_strauss", "transnational_coproduction", "arte", "rts", "rtbf", "independent_lens", "contemporary_footage", "sound_design"]
    },
    learningGoals: [
      "Explain I Am Not Your Negro as a coordinated rights, archive, writing, photography, editing, voice, sound and financing system rather than only as a compilation of James Baldwin quotations.",
      "Use the producer/co-producer-linked 93-minute record as the canonical runtime anchor while preserving alternate catalogue timings as version metadata if encountered.",
      "Identify Raoul Peck as director and distinguish his structural authorship from James Baldwin's words, Alexandra Strauss's editing, the cinematographers, archival research and sound roles.",
      "Identify James Baldwin's published and unpublished words as the governing verbal source without converting Peck's selection and arrangement into a claim that Baldwin authored the finished film screenplay in conventional production terms.",
      "Explain why unusually broad James Baldwin Estate access was a production dependency affecting what texts, letters, photographs and unpublished materials could enter research.",
      "Treat estate trust and rights duration as production infrastructure rather than as a purely legal footnote.",
      "Explain how a roughly ten-year development period allowed the project to test documentary, narrative and mixed forms before settling on its final construction.",
      "Identify the thirty-page Remember This House material as the structural entry point discovered years into development rather than pretending the complete film was predetermined from project launch.",
      "Explain how Medgar Evers, Malcolm X and Martin Luther King Jr. provide a narrative spine through Baldwin's planned book without reducing the film to three conventional biographies.",
      "Explain Peck's no-talking-head rule as an authorship and production constraint that forced images, archive, text, voice, sound and montage to carry interpretation.",
      "Explain the text-first workflow in which Peck assembled a coherent dramatic manuscript or libretto from Baldwin's writings before the final image structure existed.",
      "Distinguish source text selection from quotation invention: the production could rearrange and juxtapose Baldwin's words but should not silently manufacture new Baldwin statements.",
      "Explain why archival research began as a broad search across film, radio, television, photography and other records around Baldwin and the histories he references.",
      "Treat archival research as iterative: a footnote, name, film reference, song or newly found image could trigger a new search and change the edit.",
      "Explain why an archive log must track source, rights holder, provenance, format, date, description, intended context and legal status rather than only a filename.",
      "Distinguish archive discovery from archive acquisition: finding an image does not prove permission, usable resolution, affordable licensing or Fair Use eligibility.",
      "Explain Fair Use as contextual legal analysis, not a blanket category that automatically clears documentary footage.",
      "Use Peck's account of a lawyer reviewing edit versions for about a year as evidence that legal review and editing were interdependent.",
      "Reject a universal number-of-seconds Fair Use rule: duration can matter, but context, purpose, amount and transformation require title-specific legal review.",
      "Explain how a legal note requesting a shorter or differently contextualized clip can become a creative montage problem rather than simply a compliance deletion.",
      "Distinguish Fair Use material from footage or music that still required permission and paid licensing.",
      "Explain why archive licensing affects budget, schedule and editorial alternatives, especially when a desired clip becomes unavailable or unaffordable.",
      "Maintain versioned legal status so an approved use in one edit is not assumed to remain approved after duration, context or sequence changes.",
      "Explain why third-party film excerpts referenced by Baldwin can function as argumentative evidence rather than decorative nostalgia.",
      "Explain how juxtaposing Hollywood imagery, historical violence, television interviews and contemporary footage creates meaning at the edit rather than merely illustrating spoken text.",
      "Identify Alexandra Strauss as picture editor and treat editing as structural writing with heterogeneous image and sound sources.",
      "Explain Peck's layer-by-layer editing process as repeated return to Baldwin's text, archive, music and new associations rather than a single assembly pass.",
      "Explain why a long gestation with periods away from the edit can alter critical distance without turning delay itself into proof of quality.",
      "Treat physical or spatial arrangement of archival material as a documented thinking method while keeping exact room layout and card taxonomy outside the verified layer.",
      "Explain how a temporary voice track can let text order, rhythm and duration evolve before committing to the final performer.",
      "Identify Samuel L. Jackson as the final voice performer and distinguish that performance from Baldwin's archival on-camera voice and from conventional omniscient narration.",
      "Explain Peck's direction to approach Baldwin as a character rather than simply mimic his recorded voice.",
      "Identify the final Jackson recording as a studio session in Sofia, Bulgaria, undertaken after he had received a cut during the late editing phase.",
      "Keep the exact studio, microphone, preamp, recorder, session length and take count unresolved unless stronger production records establish them.",
      "Explain why changing from a temporary voice to a final performer can force timing, pause, picture and music adjustments late in editorial.",
      "Identify Henry Adebonojo and Bill and Turner Ross as documented directors of photography for contemporary material while keeping exact unit-by-unit ownership bounded where credits do not resolve it.",
      "Explain why newly photographed New York and American South material must be tracked separately from historical archive even when the final montage deliberately blends eras.",
      "Keep exact camera bodies, lenses, codecs, frame rates, filters and data-management hardware for the contemporary units unresolved unless title-specific camera records are recovered.",
      "Explain how mixed color and black-and-white sources require editorial and finishing decisions about contrast, scale, texture and transition without pretending all archive was restored through one pipeline.",
      "Use the documented 1.85 presentation as delivery metadata while avoiding unsupported claims about the native aspect ratio of every archival element.",
      "Explain why archival images with different original aspect ratios may require pillarboxing, cropping, reframing, graphics or background treatment rather than silent geometric normalization.",
      "Keep exact scanner models, restoration tools, deinterlacing methods and archive upscaling settings unresolved unless facility records establish them.",
      "Identify graphics and animation as documented production layers without inventing the complete software stack or per-shot design workflow.",
      "Explain why photographs, moving-image archive, film excerpts, television recordings, graphics and contemporary footage need distinct provenance even if they occupy the same final frame.",
      "Identify Valérie Le Docte and David Gillain as documented sound-post contributors and keep editing/design versus final-mix responsibilities distinct where source credits specify them.",
      "Identify Alexei Aigui as composer and distinguish original score from licensed music, archival source music and sound-design elements.",
      "Explain Peck's statement that the documentary was treated like a narrative film in sound as evidence for constructed sound, music, silence and image-sound dramaturgy rather than raw archive playback alone.",
      "Explain why silence can be an editorial and sound-design decision with its own rights-free status but still requires deliberate mix and pacing choices.",
      "Keep exact music cue sheets, recording ensemble, stems, reverbs, loudness targets and final mix automation outside the locked layer unless title-specific records establish them.",
      "Identify Velvet Film, Artémis Productions and Close Up Films as documented production/co-production entities while preserving ARTE France, RTS, RTBF and Shelter Prod as distinct additional co-production layers.",
      "Identify Rémi Grellety, Raoul Peck and Hébert Peck as documented producers and Patrick Quinet and Joëlle Bertossa as documented co-producers without inventing exact financing shares.",
      "Explain how public-service broadcasters and documentary funders can shape financing and delivery obligations without assuming they dictated editorial conclusions.",
      "Treat Independent Lens/ITVS support as a financing and distribution context where documented, not as proof of ownership over every creative decision.",
      "Explain why long-term self-production gave Peck unusual control over pauses, fundraising and returns to the edit while also increasing responsibility for time and financing risk.",
      "Separate production evidence from reception: awards, reviews and political relevance do not prove rights status, camera technique, edit software or sound hardware.",
      "Maintain an uncertainty register for exact total budget, per-clip fees, complete archive inventory, camera equipment, archive digitization settings, edit software, graphics tools, temporary/final voice recording chain, music stems and final mix specifications.",
      "Explain I Am Not Your Negro's Chapter 18 significance as a hybrid nonfiction case where digital convergence expanded access, recombination, legal review and circulation of heterogeneous historical media without erasing rights or provenance constraints.",
      "Contrast archive-heavy digital montage with camera-centered production cases so Chapter 18 does not mistake digital convergence for a history of camera bodies alone.",
      "Explain how legal, archival and editorial systems can become as production-critical as photography in contemporary documentary.",
      "Build a closing production audit that checks estate provenance, Baldwin-text fidelity, archive source logs, rights/Fair Use status by edit version, paid licenses, new-footage provenance, temporary/final voice state, edit lineage, sound/music ownership and 93-minute delivery metadata before verification."
    ],
    phases: [
      { id: "evidence_hierarchy", label: "Map the documentary evidence hierarchy", player_task: "Separate producer/co-producer credits, Peck and Hébert Peck testimony, editor accounts, archive/legal reporting and later reception before promoting production claims." },
      { id: "released_version", label: "Lock the 93-minute production anchor", player_task: "Use the producer-linked 93-minute record and preserve alternate runtimes only as version metadata until a specific delivery is identified." },
      { id: "estate_relationship", label: "Secure Baldwin Estate provenance", player_task: "Document the scope and duration of estate access, unpublished materials and rights authority without assuming access automatically clears third-party media." },
      { id: "development_history", label: "Map the ten-year development", player_task: "Track abandoned narrative, hybrid and documentary approaches so development history explains choices without treating unused forms as released-film evidence." },
      { id: "remember_this_house", label: "Establish the Remember This House spine", player_task: "Use the thirty-page unfinished-book material as the structural entry point and preserve its unfinished status rather than presenting it as a completed Baldwin manuscript." },
      { id: "baldwin_text_corpus", label: "Build the Baldwin text corpus", player_task: "Log source work, edition, page or archival identifier for each selected passage so rearrangement remains traceable to Baldwin." },
      { id: "libretto", label: "Assemble the text-first libretto", player_task: "Create a dramatic beginning-middle-end structure from Baldwin's words before using images to fill a conventional documentary template." },
      { id: "no_talking_heads", label: "Enforce the no-talking-head rule", player_task: "Test whether archive, voice, image, sound and montage can carry context without expert interviews explaining Baldwin to the audience." },
      { id: "archive_search", label: "Launch broad archival research", player_task: "Search film, radio, television, photographs, speeches, news and cultural references around Baldwin and the three civil-rights figures." },
      { id: "archive_metadata", label: "Normalize archive metadata", player_task: "Track source, rights holder, provenance, date, format, description, intended context, cost and legal state for every candidate asset." },
      { id: "archive_quality", label: "Audit technical archive quality", player_task: "Separate editorial value from technical usability by logging resolution, damage, cadence, aspect, audio and available masters without inventing restoration settings." },
      { id: "discovery_acquisition", label: "Separate discovery from acquisition", player_task: "Do not place found footage into a locked sequence until availability, source quality, rights path and cost are known." },
      { id: "fair_use_review", label: "Run versioned Fair Use review", player_task: "Give counsel the actual clip, duration, surrounding argument and edit version; record the reasoning without turning one legal decision into a universal rule." },
      { id: "paid_licenses", label: "Track paid licenses separately", player_task: "Record assets that require permission or fees so Fair Use, licensed archive and estate-owned material never collapse into one rights state." },
      { id: "legal_edit_loop", label: "Turn legal notes into edit choices", player_task: "When duration or context is challenged, test shorter, transformed or alternative constructions and send the revised version back through review." },
      { id: "rights_budget", label: "Model rights-budget exposure", player_task: "Track fees and contingencies by source while keeping unsupported exact historical per-clip prices outside the case." },
      { id: "temporary_voice", label: "Cut with a temporary Baldwin voice", player_task: "Use a replaceable working voice to iterate text timing and structure without hard-locking picture to an unavailable final performance." },
      { id: "archive_floor_structure", label: "Build the first visual structure", player_task: "Use Peck's documented spatial handling of archive as a thinking method, while keeping exact room/card layout provisional." },
      { id: "layered_edit", label: "Build montage layer by layer", player_task: "Return repeatedly to books, footnotes, images, music and archive leads so new evidence can deepen rather than merely decorate the first assembly." },
      { id: "editorial_distance", label: "Use deliberate editorial distance", player_task: "Schedule review points after time away from the cut to identify superficial layers without romanticizing delay as a quality guarantee." },
      { id: "contemporary_shoot_map", label: "Map contemporary photography", player_task: "Separate Adebonojo and Ross-brothers new footage from archive and assign location, date, unit and provenance without guessing camera models." },
      { id: "new_york_south", label: "Build contemporary geographic counterpoints", player_task: "Plan New York and American South imagery as present-day dialogue with Baldwin's historical argument rather than generic establishing footage." },
      { id: "camera_unknowns", label: "Bound contemporary camera claims", player_task: "Keep camera bodies, lenses, codecs, filters and data hardware unresolved until title-specific production records support them." },
      { id: "aspect_strategy", label: "Normalize mixed aspect ratios visibly", player_task: "Choose crop, matte, pillarbox, graphic or background treatment per source while preserving each asset's original geometry in metadata." },
      { id: "color_bw", label: "Integrate color and black-and-white sources", player_task: "Test contrast, texture and transitions across heterogeneous media without applying one invented restoration recipe to all archive." },
      { id: "graphics", label: "Assign graphics and animation ownership", player_task: "Track titles, maps, text and animated elements as separate assets while leaving unsupported software and template details outside the verified layer." },
      { id: "jackson_casting", label: "Cast the final Baldwin voice", player_task: "Evaluate presence, political maturity and ability to disappear into Baldwin's words rather than selecting a conventional celebrity narrator by familiarity alone." },
      { id: "sofia_recording", label: "Record Samuel L. Jackson in Sofia", player_task: "Record the final performance against the current cut and preserve exact studio/hardware details as unknown unless production records establish them." },
      { id: "voice_reconform", label: "Reconform picture to final voice", player_task: "Audit pauses, emphases, shot duration, music entries and silence after replacing the temporary voice with Jackson's performance." },
      { id: "sound_dramaturgy", label: "Build narrative-film sound dramaturgy", player_task: "Use archive sound, reconstructed elements, silence and designed transitions to support Baldwin's argument without falsifying source provenance." },
      { id: "music_layers", label: "Separate score and licensed music", player_task: "Track Alexei Aigui's score, source music, licensed songs and archival performance audio as distinct rights and mix layers." },
      { id: "mix_ownership", label: "Map sound-post ownership", player_task: "Keep Valérie Le Docte and David Gillain's documented roles distinct while refusing unsupported microphone, plug-in, stem and automation details." },
      { id: "coproduction_map", label: "Map the transnational co-production", player_task: "Preserve Velvet Film, Artémis, Close Up, ARTE France, RTS, RTBF and Shelter Prod as distinct entities and obligations rather than one generic financing pool." },
      { id: "producer_map", label: "Map producer responsibility", player_task: "Track Rémi Grellety, Raoul Peck, Hébert Peck, Patrick Quinet and Joëlle Bertossa by documented producer/co-producer credit without guessing financing shares." },
      { id: "funder_delivery", label: "Track funder and broadcaster delivery", player_task: "Record technical and contractual delivery requirements where documented without assuming financial support equals editorial control." },
      { id: "unknowns_register", label: "Maintain the documentary unknowns register", player_task: "Track budget, clip fees, complete archive inventory, camera gear, digitization/restoration settings, edit/graphics software, voice hardware, music stems and mix specifications explicitly." },
      { id: "chapter18_position", label: "Position archive montage in digital convergence", player_task: "Explain how digitized archives, nonlinear editing and digital distribution increase combinatorial possibilities while rights, provenance and source quality remain binding constraints." },
      { id: "delivery_review", label: "Audit the complete Baldwin production system", player_task: "Verify 93-minute delivery metadata, estate/text provenance, rights states, legal notes, archive logs, new-footage provenance, voice versions, edit lineage, sound/music ownership and co-production credits before closure." }
    ]
  }
] as const;

export function mergeChapterEighteenIAmNotYourNegroExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterEighteenIAmNotYourNegroExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_eighteen_i_am_not_your_negro_verified",
      source: { list_id: "manual_chapter_eighteen_i_am_not_your_negro_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}