import assert from "node:assert/strict";
import test from "node:test";

import { chapterEighteenAtlanticsExpansionDefinitions } from "./chapterEighteenAtlanticsExpansion.js";

test("Chapter 18 materializes Atlantics as a source-first Senegalese transnational supernatural-social-realist production case", () => {
  assert.equal(chapterEighteenAtlanticsExpansionDefinitions.length, 1);
  const film = chapterEighteenAtlanticsExpansionDefinitions[0];
  assert.equal(film.id, "scenario_atlantics_2019");
  assert.equal(film.title, "Atlantics");
  assert.equal(film.originalTitle, "Atlantique");
  assert.equal(film.year, 2019);
  assert.equal(film.runtimeMins, 104);
  assert.deepEqual(film.directors, ["Mati Diop"]);
  assert.ok(film.scenarioType.includes("senegalese_french_belgian") && film.scenarioType.includes("supernatural_social_realism"));
  assert.ok(film.scenarioType.includes("street_cast") && film.scenarioType.includes("wolof") && film.scenarioType.includes("red_epic_varicam_day_night"));
  assert.ok(film.scenarioType.includes("1_66") && film.scenarioType.includes("platform_circulation"));
  assert.ok(film.premise.includes("104 minutes") && film.premise.includes("France-Senegal-Belgium") && film.premise.includes("1.66") && film.premise.includes("5.1"));
  assert.ok(film.premise.includes("Les Films du Bal") && film.premise.includes("Cinekap") && film.premise.includes("Frakas"));
  assert.ok(film.premise.includes("ARTE France Cinéma") && film.premise.includes("Canal+ International"));
  assert.ok(film.premise.includes("RED Epic") && film.premise.includes("Panasonic VariCam") && film.premise.includes("85-135 mm") && film.premise.includes("Optimo 45-120 mm"));
  assert.ok(film.premise.includes("RED Epic Dragon") && film.premise.includes("VariCam LT") && film.premise.includes("VariCam 35") && film.premise.includes("body-label discrepancy"));
  assert.ok(film.premise.includes("Souleiman") && film.premise.includes("construction site") && film.premise.includes("Dior") && film.premise.includes("nightclub") && film.premise.includes("Thiaroye"));
  assert.ok(film.premise.includes("Wolof") && film.premise.includes("Olivier Demangel") && film.premise.includes("Violaine Huisman"));
  assert.ok(film.premise.includes("very end of editing") && film.premise.includes("not recorded during principal photography"));
  assert.ok(film.premise.includes("Fatima Al Qadiri") && film.premise.includes("ancient/futuristic") && film.premise.includes("Netflix"));
  assert.ok(film.premise.includes("exact total budget") && film.premise.includes("exact financing shares") && film.premise.includes("shooting-day count"));
  assert.ok(film.premise.includes("fabricated resolution of VariCam LT versus VariCam 35") && film.premise.includes("LUT/CDL recipes") && film.premise.includes("final mix topology"));
  assert.ok(film.requiredChoicesSeed.screenplay.includes("late_poetic_text") && film.requiredChoicesSeed.screenplay.includes("editing_continues_writing"));
  assert.ok(film.requiredChoicesSeed.camera.includes("red_epic_day") && film.requiredChoicesSeed.camera.includes("varicam_night") && film.requiredChoicesSeed.camera.includes("varicam_body_discrepancy"));
  assert.ok(film.requiredChoicesSeed.camera.includes("long_lenses_85_135") && film.requiredChoicesSeed.camera.includes("dakar_available_light"));
  assert.ok(film.requiredChoicesSeed.sound.includes("fatima_al_qadiri") && film.requiredChoicesSeed.sound.includes("5_1_delivery"));
  assert.ok(film.learningGoals.some((goal) => goal.includes("104-minute") && goal.includes("canonical runtime")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Chapter 18 function") && goal.includes("African authorship") && goal.includes("European co-production")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("France, Senegal and Belgium") && goal.includes("Senegalese authorship")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Wolof") && goal.includes("place and authorship")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("street casting") && goal.includes("social environments")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("construction site") && goal.includes("nightclub") && goal.includes("Thiaroye")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Claire Mathon") && goal.includes("real but lyrical Dakar")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("RED Epic") && goal.includes("daytime")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Panasonic VariCam") && goal.includes("night strategy")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("VariCam LT") && goal.includes("VariCam 35") && goal.includes("source conflict")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("1.66") && goal.includes("sensor's native raster")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("85-135 mm") && goal.includes("complete lens-by-shot map")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Angénieux Optimo 45-120 mm") && goal.includes("working range")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Zeiss G.O. T1.3") && goal.includes("every shot")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("dark skin at night") && goal.includes("exposure/color responsibility")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("exact ISO") && goal.includes("white balance") && goal.includes("unresolved")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Aël Dallier Vega") && goal.includes("genre shift")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("very end of editing") && goal.includes("principal photography")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Violaine Huisman") && goal.includes("principal screenplay credit")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Benoit De Clerck") && goal.includes("Emmanuel de Boissieu")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Fatima Al Qadiri") && goal.includes("official composer")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("ancient/futuristic") && goal.includes("supernatural")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Netflix") && goal.includes("post-Cannes") && goal.includes("not proof")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("uncertainty register") && goal.includes("VariCam body") && goal.includes("DI nodes")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Chapter 18 significance") && goal.includes("locally specific Wolof-language authorship")));
  assert.ok(film.phases.find((phase) => phase.id === "released_version")?.player_task.includes("104-minute"));
  assert.ok(film.phases.find((phase) => phase.id === "varicam_discrepancy")?.player_task.includes("VariCam LT") && film.phases.find((phase) => phase.id === "varicam_discrepancy")?.player_task.includes("VariCam 35"));
  assert.ok(film.phases.find((phase) => phase.id === "long_lenses")?.player_task.includes("85-135 mm") && film.phases.find((phase) => phase.id === "long_lenses")?.player_task.includes("Optimo 45-120 mm"));
  assert.ok(film.phases.find((phase) => phase.id === "late_poem")?.player_task.includes("Violaine Huisman") && film.phases.find((phase) => phase.id === "late_poem")?.player_task.includes("principal-photography dialogue"));
  assert.ok(film.phases.find((phase) => phase.id === "platform_rights")?.player_task.includes("Netflix") && film.phases.find((phase) => phase.id === "platform_rights")?.player_task.includes("not principal-photography financing"));
  assert.ok(film.phases.find((phase) => phase.id === "unknowns_register")?.player_task.includes("VariCam body conflict") && film.phases.find((phase) => phase.id === "unknowns_register")?.player_task.includes("mix topology"));
  assert.ok(film.learningGoals.length >= 55);
  assert.ok(film.phases.length >= 35);
});
