import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterNineteenTheBoyAndTheHeronExpansionDefinitions = [
  {
    id: "scenario_the_boy_and_the_heron_2023",
    title: "The Boy and the Heron",
    originalTitle: "Kimitachi wa Do Ikiru ka",
    aliases: ["The Boy and the Heron", "Kimitachi wa Do Ikiru ka", "How Do You Live?"],
    year: 2023,
    titleType: "Movie",
    runtimeMins: 124,
    directors: ["Hayao Miyazaki"],
    genres: ["Animation", "Adventure", "Drama", "Fantasy"],
    sourceId: "studio_ghibli_the_boy_and_the_heron_2023",
    sourceUrl: "https://studioghibli.jp/films/the-boy-and-the-heron/",
    scenarioType: "award_priority_oscar_best_animated_feature_studio_ghibli_hayao_miyazaki_toshio_suzuki_takeshi_honda_atsushi_okui_yoji_takeshige_shinya_ohira_hand_drawn_storyboards_organic_story_development_no_finished_screenplay_analog_key_animation_background_painting_digital_compositing_hybrid_2d_cg_no_3d_character_rendering_seven_year_production_no_deadline_joe_hisaishi_minimalist_score_2023",
    premise: "Build The Boy and the Heron as Chapter 19's next award-priority animation production case because the Academy records Hayao Miyazaki and Toshio Suzuki as the 2024 Animated Feature Film winners, while keeping award status separate from evidence about how the film was made. Studio Ghibli documents production beginning around 2016 and taking approximately seven years. Miyazaki drew storyboards by hand and developed the story organically rather than beginning from a finished screenplay. The production therefore treats storyboard creation as an evolving writing-and-directing system, not merely a visualization step after script lock. The locked production record supports a primarily hand-drawn feature with digital compositing used to integrate effects and backgrounds. Supervising animator Takeshi Honda describes the work as relying largely on orthodox analog-era methods, with Miyazaki seeking to preserve hand drawing and with everyday behavior requiring exact animation. Producer Toshio Suzuki describes a production environment with abundant time and no fixed deadline, adjusted to Miyazaki's pace. Honda supervised and revised animation, animators worked from Miyazaki's storyboards, and material went back to Miyazaki for taste-based approval and correction. This does not support a myth of solitary authorship: the feature was unusually collaborative, with specialist animators carrying sequences while Miyazaki retained strong storyboard and approval authority. Shinya Ohira's opening fire sequence is a documented example of assigning a sequence to an animator whose individual drawing style was allowed to remain visible rather than normalized away. Atsushi Okui's digital-imaging account establishes the core hybrid boundary. Animators and background artists still began with pencil, paint and paper; analog elements were then converted to digital data. Character animation was not created through 3D character rendering. At the same time, the film was not 'computer free': digital compositing, CGI layers and 3D models were used where appropriate, including texture integration and hybrid effects. Okui describes hand-drawn key animation combined with CGI texture layers and a hybrid approach to the collapsing tower in which animators designed the breakup while CGI assisted the effect. The film also deliberately deepened blacks and shadow values digitally to support Mahito's darker emotional world. The opening fire sequence used extensive layered hand-drawn motion and deliberately unstable, soft or out-of-focus image behavior to align the visual field with Mahito's psychology. Production design and background art therefore remain materially tied to drawn and painted source elements even after digital conversion. The case distinguishes animation cinematography from live-action acquisition: there is no physical camera/lens package to inventory in the usual sense. Okui's role concerns digital imaging, compositing, depth, focus behavior, color density and the translation of drawn layers into final moving images. The relevant format boundary is a 1.85:1 digital theatrical presentation and a hybrid analog-to-digital image pipeline, not an invented sensor or lens list. BBFC records multiple 2D cinema classifications around 123 minutes 42-48 seconds and later home-entertainment variants around 123 minutes 50-55 seconds. The playable record uses 124 minutes as the rounded institutional runtime while preserving those version differences rather than forcing false frame-level identity. Music followed a comparatively autonomous process. Joe Hisaishi describes seeing a nearly completed film in July 2022, receiving limited storyboards afterward and being told by Miyazaki that the music was largely up to him. Hisaishi chose a minimalist language: sparse piano for much of the more realistic first half, expanding toward orchestra in the fantasy second half while retaining restraint. This means the score was shaped late relative to the long animation process and with unusual trust, not through dense spotting meetings documented throughout production. The locked record does not establish a complete production-sound or final-mix chain, every dialogue recording session, full foley/effects library, exact dubbing workflow, complete music-session ledger or mastering package, so those remain unresolved. The seven-year process is independently corroborated by the NHK making-of documentary record presented by Cannes, which had exclusive access to Studio Ghibli over the production period. That documentary evidence supports duration and collaboration context but does not replace direct craft testimony for every department. Current locked sources do not establish a single audited final production budget, financing waterfall, exact animation crew total, complete shot/frame count, animator-per-shot ledger, full storyboard revision chronology, exact number of drawings, complete background-paint inventory, every digital tool/version/plugin, full compositing node graph, exact color-management specification, complete sound editorial/ADR/Foley/mix chain, full score-session ledger, complete Japanese and international dubbing-production records, distribution recoupment or release accounting. Those remain explicit unresolved boundaries. The production-history lesson is therefore neither 'Ghibli is purely analog' nor 'digital tools replaced hand craft.' The film demonstrates a long-duration auteur animation system in which evolving hand-drawn storyboards, specialist key animation, paper-and-paint backgrounds, supervisory correction, selective individual animator style, digital scanning/compositing, invisible hybrid CGI and a late minimalist score were coordinated without collapsing their distinct labor and evidence layers.",
    requiredChoicesSeed: {
      screenplay: ["oscar_priority_not_workflow_evidence", "organic_storyboard_development", "no_finished_screenplay_start", "seven_year_process", "bbfc_runtime_variance", "budget_finance_unresolved"],
      camera: ["animation_cinematography_not_live_action_camera", "atsushi_okui_digital_imaging", "paper_to_digital_pipeline", "deepened_blacks", "unstable_fire_sequence_image", "one_eighty_five_presentation", "physical_camera_package_not_applicable"],
      editing: ["storyboard_driven_structure", "miyazaki_taste_based_revision", "honda_supervision", "late_nearly_complete_picture_for_score", "full_edit_system_unresolved"],
      sound: ["joe_hisaishi_minimalist_score", "sparse_piano_first_half", "orchestral_expansion_second_half", "limited_spotting_direction", "full_sound_chain_unresolved"],
      themes: ["film_history", "2023", "the_boy_and_the_heron", "studio_ghibli", "oscar_best_animated_feature", "hand_drawn_animation", "analog_digital_hybrid", "chapter19"]
    },
    learningGoals: [
      "Explain why the 2024 Animated Feature Film Oscar justifies award-priority selection without proving production workflow.",
      "Identify Hayao Miyazaki as director and Toshio Suzuki as producer/award recipient without conflating their responsibilities.",
      "Use Studio Ghibli's approximately seven-year production record as a duration anchor.",
      "Explain production beginning around 2016 without inventing an exact first production day.",
      "Explain Miyazaki's hand-drawn storyboards as an evolving writing-and-directing system.",
      "Explain why the film did not begin from a finished screenplay.",
      "Distinguish organic story development from improvisation without structure.",
      "Preserve BBFC cinema runtimes around 123m42s-123m48s and later home variants as version evidence.",
      "Use 124 minutes as a rounded playable runtime rather than a false exact master duration.",
      "Identify Takeshi Honda as supervising animator.",
      "Explain Honda's supervisory role as revision, coordination and return-to-Miyazaki approval rather than replacement of Miyazaki's authorship.",
      "Explain why the production environment allowed abundant time and no fixed deadline.",
      "Explain why no-deadline production still required supervision, iteration and approval discipline.",
      "Identify Shinya Ohira as the animator strongly associated with the opening fire sequence.",
      "Explain the opening fire sequence as a case where individual animator style remained visible.",
      "Explain why stylistic variation can be deliberately retained instead of corrected toward uniformity.",
      "Explain Honda's description of largely analog-era animation methods.",
      "Explain why exact everyday behavior creates difficult hand-animation requirements.",
      "Reject the myth that Miyazaki alone drew the entire feature.",
      "Reject the opposite myth that Miyazaki merely delegated and approved a conventional studio pipeline.",
      "Identify Atsushi Okui as the central digital-imaging/cinematography source in the locked record.",
      "Explain the paper-and-paint starting point for animators and background artists.",
      "Explain analog-to-digital conversion as a production handoff rather than replacement of original drawn material.",
      "Explain that 3D character rendering was not used to create the characters themselves.",
      "Reject the unsupported statement that the film contains no CGI or digital work.",
      "Explain digital compositing as a bridge among hand-drawn animation, backgrounds, effects and selective CGI.",
      "Explain hand-drawn key animation combined with CGI texture layers as a hybrid workflow.",
      "Explain the collapsing tower as a documented hybrid effect combining animator-designed breakup with CGI assistance.",
      "Explain why hybrid effects can remain visually subordinate to hand-drawn style.",
      "Explain deliberate deepening of blacks as a digital imaging decision tied to Mahito's emotional darkness.",
      "Explain the opening fire sequence's unstable and soft image behavior as subjective visual design.",
      "Distinguish animation cinematography from physical camera acquisition.",
      "Do not invent sensor, lens, stock or exposure metadata for an animation production without evidence.",
      "Use the documented 1.85:1 presentation as a display-format anchor without inventing internal canvas specifications.",
      "Explain backgrounds as painted/drawn source elements that enter a later digital compositing stage.",
      "Identify Yoji Takeshige as art director in the locked production record.",
      "Explain layout handoff toward background art as a production-design coordination step.",
      "Explain why a layout can contain both staging information and downstream background guidance.",
      "Explain the role of taste-based correction in Miyazaki's approval process.",
      "Explain why storyboards could become more ambitious once Honda carried supervising-animation responsibilities.",
      "Explain why the many birds made the production visibly time-intensive in Suzuki's account.",
      "Explain hand-drawn bird crowds as labor evidence, not proof that every effect in the film was hand drawn.",
      "Identify Joe Hisaishi as composer.",
      "Explain Hisaishi seeing a nearly completed film in July 2022 as evidence of the score's late relationship to picture production.",
      "Explain Miyazaki's unusually broad delegation of musical decision-making to Hisaishi.",
      "Explain sparse piano in the more realistic first half as a documented scoring strategy.",
      "Explain orchestral expansion in the fantasy second half while preserving minimalist restraint.",
      "Explain why minimalism can support an epic animated feature without mirroring every visual beat.",
      "Separate music evidence from the unresolved full sound-design and final-mix chain.",
      "Use Cannes/NHK making-of evidence to corroborate long-duration production access and collaboration context.",
      "Do not treat the making-of documentary as proof of undocumented departmental ledgers.",
      "Keep audited budget and financing waterfall unresolved.",
      "Keep exact total crew size and complete animator-per-shot assignment unresolved.",
      "Keep exact drawing/frame count unresolved unless a locked production record establishes it.",
      "Keep complete storyboard revision chronology and layout inventory unresolved.",
      "Keep complete background-paint and digital-compositing asset inventories unresolved.",
      "Keep every software version, plugin, compositing graph and color-management setting unresolved.",
      "Keep full dialogue recording, ADR, foley, sound editorial, mix and mastering architecture unresolved.",
      "Keep full score-session, dubbing and international release accounting unresolved.",
      "Explain why 'purely analog Ghibli' is an inaccurate description of the documented pipeline.",
      "Explain why 'CG replaced hand drawing' is equally inaccurate.",
      "Close the case only when award priority, runtime provenance, storyboard development, hand animation, supervisory labor, backgrounds, digital compositing, hybrid CGI and music evidence agree."
    ],
    phases: [
      { id: "award_priority", label: "Lock Oscar animation priority", player_task: "Use the 2024 Animated Feature Film win to prioritize the case while keeping award evidence separate from production method." },
      { id: "evidence_hierarchy", label: "Map the evidence hierarchy", player_task: "Separate Academy and BBFC institutional records from Studio Ghibli, Cannes/NHK and direct craft interviews." },
      { id: "runtime_boundary", label: "Freeze runtime provenance", player_task: "Use 124 minutes as rounded runtime while preserving BBFC cinema and home-version differences." },
      { id: "finance_boundary", label: "Freeze unresolved finance", player_task: "Do not invent an audited budget, financing waterfall or recoupment model." },
      { id: "seven_year_timeline", label: "Build the seven-year production", player_task: "Anchor production around 2016-2023 without inventing unsupported exact start or shot dates." },
      { id: "storyboard_writing", label: "Write through storyboards", player_task: "Treat Miyazaki's hand-drawn boards as evolving screenplay, staging and directing documents." },
      { id: "no_finished_script", label: "Preserve the script boundary", player_task: "Do not rewrite the production as a conventional locked-script-first pipeline." },
      { id: "supervising_animation", label: "Assign supervising animation", player_task: "Use Takeshi Honda to coordinate and revise animation while preserving Miyazaki's storyboard and approval authority." },
      { id: "no_deadline_environment", label: "Protect iteration time", player_task: "Model abundant production time without confusing it with absence of management or review." },
      { id: "specialist_animators", label: "Protect specialist style", player_task: "Allow sequence animators such as Shinya Ohira to contribute distinctive movement where documented." },
      { id: "fire_sequence", label: "Build subjective fire animation", player_task: "Layer hand-drawn crowd motion, instability and softness around Mahito's distressed point of view." },
      { id: "paper_animation", label: "Keep key animation on paper", player_task: "Start character motion from drawn key animation rather than inventing a 3D-character pipeline." },
      { id: "background_art", label: "Paint the environment layer", player_task: "Route layouts into paper/paint background work before digital conversion." },
      { id: "analog_to_digital", label: "Convert analog elements", player_task: "Move drawings and painted backgrounds into digital data while preserving their visual character." },
      { id: "no_3d_characters", label: "Protect the character boundary", player_task: "Use no 3D character rendering for the characters themselves while leaving room for selective CGI elsewhere." },
      { id: "digital_compositing", label: "Composite the drawn layers", player_task: "Integrate animation, backgrounds and effects digitally instead of claiming an all-analog finish." },
      { id: "hybrid_textures", label: "Blend CGI textures selectively", player_task: "Combine hand-drawn key animation with CGI texture layers only where the locked craft evidence supports it." },
      { id: "tower_hybrid", label: "Design the collapsing tower", player_task: "Let animators design breakup motion and use CGI assistance without turning the sequence into a fully 3D character scene." },
      { id: "black_levels", label: "Deepen the darkness", player_task: "Use digital imaging to deepen blacks in support of Mahito's psychological state." },
      { id: "animation_cinematography", label: "Define animation cinematography", player_task: "Treat focus, depth, layer integration and final image behavior as imaging work rather than inventing physical camera metadata." },
      { id: "format_boundary", label: "Lock display format", player_task: "Use the documented 1.85:1 digital presentation without inventing internal render-canvas details." },
      { id: "layout_feedback", label: "Route layout feedback", player_task: "Use layouts as staging documents that can be checked, revised and handed toward background production." },
      { id: "miyazaki_approval", label: "Run taste-based approvals", player_task: "Return animation for Miyazaki's acceptance or correction without pretending approval criteria were algorithmic." },
      { id: "bird_complexity", label: "Scale bird animation", player_task: "Budget labor for dense hand-drawn bird movement without generalizing that every effect avoids CGI." },
      { id: "picture_near_complete", label: "Reach near-complete picture", player_task: "Carry the long animation process far enough that Hisaishi can respond to a nearly completed film." },
      { id: "music_delegation", label: "Delegate musical authorship", player_task: "Give Hisaishi unusually broad musical discretion consistent with his direct account." },
      { id: "minimalist_score", label: "Build the minimalist score", player_task: "Use restrained piano for the realistic first half and broader orchestration later without abandoning minimalism." },
      { id: "sound_boundary", label: "Freeze unresolved sound", player_task: "Do not invent the complete dialogue, effects, foley, ADR, mix or mastering chain." },
      { id: "documentary_corroboration", label: "Corroborate the long process", player_task: "Use the Cannes/NHK making-of record to confirm duration and collaboration context without treating it as a universal ledger." },
      { id: "anti_myth_audit", label: "Reject analog-versus-digital myths", player_task: "Check that the case preserves both hand craft and digital compositing instead of collapsing the film into either extreme." },
      { id: "uncertainty_register", label: "Freeze unsupported ledgers", player_task: "Keep budget, crew, frame counts, software versions, full sound, score and distribution records explicitly unresolved." },
      { id: "production_verification", label: "Close The Boy and the Heron audit", player_task: "Verify award priority, runtime provenance, seven-year development, storyboards, hand animation, supervision, backgrounds, compositing, hybrid CGI, music and uncertainty boundaries before canonical promotion." }
    ]
  }
] as const;

export function mergeChapterNineteenTheBoyAndTheHeronExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterNineteenTheBoyAndTheHeronExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_nineteen_the_boy_and_the_heron_verified",
      source: { list_id: "manual_chapter_nineteen_the_boy_and_the_heron_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
