import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterNineteenF1ExpansionDefinitions = [
  {
    id: "scenario_f1_2025",
    title: "F1",
    originalTitle: "F1",
    aliases: ["F1: The Movie", "F1 The Movie", "F1® The Movie"],
    year: 2025,
    titleType: "Movie",
    runtimeMins: 155,
    directors: ["Joseph Kosinski"],
    genres: ["Drama", "Sport", "Action"],
    sourceId: "asc_f1_the_movie_2025",
    sourceUrl: "https://theasc.com/article/on-the-fast-track-for-f1-the-movie/",
    scenarioType: "award_priority_oscar_sound_bafta_sound_best_picture_nominee_joseph_kosinski_claudio_miranda_stephen_mirrione_hans_zimmer_lewis_hamilton_f1_live_grand_prix_access_modified_f2_dallara_apxgp_mercedes_applied_science_sony_venice_2_fx6_carmen_prototype_sensor_on_a_stick_voigtlander_zeiss_loxia_panavision_remote_heads_imax_190_239_real_actor_driving_5000_hours_race_footage_2500_vfx_shots_framestore_ilm_media_composer_scriptsync_pro_tools_dolby_atmos_authentic_f1_engine_reconstruction_2025",
    premise: "Build F1 as Chapter 19's next award-priority production case because the Academy records the 2026 Oscar for Sound and a Best Picture nomination, while BAFTA records the 2026 Sound win. Those awards establish priority and reception, not production workflow. BBFC records the UK 2D cinema version at 155 minutes 5 seconds, so the playable record rounds to 155 minutes; the locked case does not assume every IMAX, digital, streaming, UHD, Blu-ray, airline or territory master is frame-identical. The official film site identifies Joseph Kosinski as director, Ehren Kruger as screenwriter, Claudio Miranda as director of photography, Mark Tildesley and Ben Munro as production designers, Stephen Mirrione as editor, Julian Day as costume designer and Hans Zimmer as composer. Formula 1's own production reporting establishes the unusual industrial condition: filming was embedded into real Grand Prix weekends with the cooperation of Formula 1, the FIA, teams, drivers and promoters, while Lewis Hamilton served as producer and technical adviser. This access is not equivalent to unrestricted control of a race weekend. The filmmakers had to fit short production windows into a live global sports event whose sporting operations remained primary. The central race-car solution began from real racing hardware rather than a conventional picture car. Kosinski's direct Formula 1 interview states that the production bought six Dallara Formula 2 chassis, worked with Mercedes engineers and designers, extended the wheelbase by 400 millimetres and created custom bodywork for the fictional APXGP team. Formula 1's separate engineering feature records multiple propulsion configurations, including Mecachrome-powered cars, GP3-era V6 cars and an electric chassis that made pit-lane filming practical where combustion operation could be constrained. These records prove a family of purpose-built film/race vehicles, not one mechanically identical APXGP car used for every shot. Brad Pitt and Damson Idris performed substantial real driving in the modified race cars, with stunt drivers handling more demanding work. American Cinematographer records the production's rejection of volume-stage or broad bluescreen substitution as the default racing method because Kosinski and Miranda wanted real kinetic energy, while acknowledging that some footage was modestly speed-adjusted and digitally augmented. The camera system was therefore engineered around real high-speed operation. ASC and Sony document a custom Sony prototype nicknamed Carmen: a stripped-down FX6-derived full-frame camera/recorder architecture designed around a very small remote head, described by Miranda as a sensor on a stick. Sony states the prototype used FX6-family full-frame sensor architecture, S-Gamut3.Cine color science and XAVC recording so it could intercut with the production's main Sony VENICE 2 photography. ASC adds that the Carmen system removed the automatic ND mechanism, used Voigtländer Hyper Wide Heliar 10/12/15mm lenses for actor-facing in-car views and Zeiss Loxia lenses for tighter/outward-looking angles. Standard FX6 bodies were also used as crash cameras. Panavision developed remote pan heads for the Carmen system, with the production networking focus, pan, exposure, color temperature, roll and record control across the moving cars. The modified vehicles offered roughly fifteen camera-mount positions, while no more than four cameras were mounted on one car for a setup because weight, space, bandwidth, driveability and mutual camera visibility imposed hard constraints. ASC estimates about 5,000 hours of racing footage, and records principal photography beginning at Silverstone in July 2023 before moving with the real Formula 1 calendar through multiple Grand Prix locations. The case treats that estimate as a scale anchor, not a complete camera-roll or storage ledger. Off-track and principal dramatic material used Sony VENICE 2 bodies, mostly in Super 35 5.8K 17:9 with ARRI/Zeiss Master Primes, while some full-frame 8.6K material and additional zoom/plate configurations were used when VFX or framing needs required them. Miranda composed primarily for 2.39:1 while protecting the 1.90:1 digital IMAX presentation; the IMAX version opens to 1.90:1 after the introductory material and remains there. The locked evidence therefore does not claim a 1.43:1 IMAX film workflow. Formula 1 and ASC also document live broadcast and trackside imagery entering the production. Actual race footage, broadcast cameras, track cameras and custom 4K raw units based on iPhone technology were coordinated with the cinema material, with camera settings and requested broadcast positions adjusted when possible. This is a multi-source acquisition system, not proof that every race image originated from the custom Carmen cameras. Visual effects were designed to preserve photographed racing rather than replace it wholesale. VFX supervisor Ryan Tudhope states that Framestore and ILM contributed to more than 2,500 VFX shots, with many effects intentionally hidden. Digital work included reskinning cars, combining or adapting race material, replacing backgrounds, adding weather and integrating the fictional APXGP team into real Formula 1 environments. Formula 1 itself notes that Pitt and Idris did not participate in actual competitive racing, so race-to-race continuity and competitive interactions required post-production construction. The locked case therefore rejects both extremes: it is neither a mostly-CG racing film nor an untouched documentary capture of real competition. Editorial was correspondingly data-heavy. Avid's direct behind-the-scenes material identifies Media Composer as Mirrione's main editorial system and ScriptSync as one tool used to locate dialogue takes quickly. ASC's estimated 5,000 hours of race footage explains the scale problem, while Mirrione's direct interviews describe building races so each sequence remained narratively legible rather than becoming interchangeable spectacle. Picture editorial, VFX turnover, performance selection, sound structure and race continuity evolved together; the evidence does not establish a single fixed race cut before performances or effects were available. Sound had a similarly hybrid authenticity problem. The Oscar/BAFTA-winning sound team includes production sound mixer Gareth John, supervising sound editors Al Nelson and Gwendolyn Yates Whittle, and re-recording mixers Gary Rizzo and Juan Peralta. Dolby's direct team interview emphasizes early planning and the resources required to make the Formula 1 environment convincing. Avid records Peralta working from Lewis Hamilton's technical input so revs, gear shifts and braking points aligned accurately with the picture, while Rizzo had to preserve dialogue and music intelligibility against extremely dense engine material. SoundWorks and later direct team interviews document dedicated clean-car recording, extensive replacement/reconstruction of engine passes, differentiated engine identities and Dolby Atmos spatial mixing rather than simply relying on noisy live Grand Prix production tracks. This means production sound, isolated vehicle recording, sound editorial, ADR/radio processing and final re-recording must remain distinct evidence layers. Hans Zimmer's score is also separate from the sound-effects system. Official credits identify Zimmer as composer, while direct interviews describe a hybrid electronic/orchestral score designed to express both Formula 1 history and current technology. The locked case does not convert score, soundtrack songs and engine sound into one undifferentiated audio layer. Production design and costume likewise operated inside a real sporting environment. Formula 1's own reporting on Julian Day records the challenge of creating a coherent fictional eleventh team that could appear beside real teams during live race weekends without looking generic or accidentally copying an existing identity, while APXGP's vehicle/livery design had to survive both full-scale race use and digital augmentation. The historical lesson is not simply that F1 used small cameras on fast cars. It is that a 2020s studio feature temporarily embedded a fictional team into a live global sports infrastructure, engineered near-race-spec picture vehicles and a new cinema-camera system, combined performer driving with stunt work, broadcast and cinema acquisition, protected 2.39 and 1.90 framing, processed thousands of hours of footage through editorial, used more than 2,500 largely invisible VFX shots to reconcile fiction with real competition, reconstructed technically specific Formula 1 sound and delivered the result as a premium-format theatrical event. The locked evidence does not establish a complete production budget or financing/ownership/recoupment waterfall, exact full shooting-day count, every Grand Prix access agreement or sporting restriction, complete crew/payroll/safety/insurance ledger, all vehicle serial numbers and mechanical revisions, every camera body/firmware/lens/filter/mount/network/codec setting, complete broadcast/iPhone/Carmen/VENICE shot allocation, every stunt-driving handoff, all 5,000 hours of media provenance, the full 2,500-plus VFX shot/vendor/task ledger, every editorial project/version/turnover, all production-sound/mic/ADR/radio/Foley/effects/stem details, complete score/song/session/licensing ledger, full color-management/DI/IMAX/HDR/SDR mastering configuration or every theatrical/streaming/home-video/territory delivery master. Those remain explicit unresolved boundaries.",
    requiredChoicesSeed: {
      screenplay: ["award_priority_not_workflow_evidence", "bbfc_155m05_cinema_runtime", "live_grand_prix_access_boundary", "fiction_inside_real_sporting_infrastructure", "budget_finance_unresolved"],
      camera: ["sony_venice_2_main_dramatic_camera", "fx6_derived_carmen_sensor_on_a_stick", "voigtlander_zeiss_loxia_in_car_lenses", "panavision_remote_heads", "fifteen_mount_positions_max_four_per_setup", "imax_190_protect_239", "multi_source_broadcast_iphone_cinema_capture", "full_camera_network_ledger_unresolved"],
      editing: ["stephen_mirrione_media_composer", "scriptsync_dialogue_search", "estimated_5000_hours_race_footage", "race_story_legibility", "vfx_performance_sound_parallel_refinement", "full_edit_revision_ledger_unresolved"],
      sound: ["oscar_bafta_sound_team", "f1_engine_reconstruction", "lewis_hamilton_technical_validation", "dolby_atmos_spatial_mix", "dialogue_music_engine_balance", "full_production_sound_adr_mix_ledger_unresolved"],
      themes: ["film_history", "2025", "f1", "live_sports_integration", "custom_camera_engineering", "real_driving", "invisible_vfx", "premium_format", "chapter19"]
    },
    learningGoals: [
      "Explain why F1's 2026 Oscar and BAFTA Sound wins justify award-priority selection without proving workflow.",
      "Keep the Oscar Best Picture nomination as reception evidence rather than a production-method source.",
      "Identify Joseph Kosinski as director and Ehren Kruger as screenwriter from official credits.",
      "Use BBFC's 155m05s UK cinema record to round the playable runtime to 155 minutes.",
      "Reject the claim that every IMAX, streaming, UHD, Blu-ray and territory master is frame-identical.",
      "Explain why filming during real Grand Prix weekends created access as well as operational constraints.",
      "Identify Formula 1, the FIA, teams, drivers and promoters as part of the documented production environment.",
      "Identify Lewis Hamilton as producer and technical adviser without attributing every technical decision to him.",
      "Explain why sporting operations remained primary during live race weekends.",
      "Identify six purchased Dallara Formula 2 chassis as the documented starting point for APXGP vehicles.",
      "Explain the documented 400mm wheelbase extension and custom bodywork work with Mercedes engineers/designers.",
      "Keep Mecachrome, GP3-era V6 and electric APXGP vehicle configurations distinct.",
      "Explain why the electric chassis solved pit-lane production problems without proving it was used for every pit-lane shot.",
      "Reject the idea that every APXGP vehicle was mechanically identical.",
      "Explain why starting from a real race car differs from making a conventional picture car look fast.",
      "Identify Brad Pitt and Damson Idris as substantial real-driving performers without claiming they executed every stunt.",
      "Keep stunt-driver work distinct from actor driving.",
      "Explain why Kosinski and Miranda rejected a volume-stage or broad bluescreen default for racing.",
      "Recognize that modest speed adjustment and digital augmentation still occurred.",
      "Identify Claudio Miranda as cinematographer.",
      "Identify Sony VENICE 2 as the main dramatic/off-track camera system.",
      "Explain the Carmen prototype as a stripped-down FX6-derived full-frame camera system.",
      "Describe the sensor-on-a-stick requirement as a response to cockpit size, driver visibility and g-force constraints.",
      "Identify S-Gamut3.Cine/XAVC compatibility as part of the Sony integration evidence.",
      "Identify Voigtländer 10/12/15mm lenses as documented in-car actor-facing optics.",
      "Identify Zeiss Loxia lenses as documented tighter/outward-looking in-car options.",
      "Identify standard FX6 bodies as documented crash-camera tools.",
      "Explain why removing the automatic ND mechanism mattered to the compact Carmen package.",
      "Identify Panavision-built remote pan heads as part of the in-car camera-control system.",
      "Explain remote focus, pan, exposure, color-temperature, roll and record control as a network problem.",
      "Use roughly fifteen vehicle camera positions as a configuration space rather than simultaneous coverage.",
      "Explain why a maximum of four cameras per car per setup reflected weight, space, bandwidth and visibility limits.",
      "Keep all camera serial numbers, firmware, mount and RF-network revisions unresolved.",
      "Use the estimated 5,000 hours of racing footage as a scale anchor rather than a complete media ledger.",
      "Identify July 2023 Silverstone as the documented beginning of principal photography.",
      "Explain how production followed the Formula 1 calendar across multiple Grand Prix locations.",
      "Identify real Formula 1 race and broadcast footage as one source layer in the finished film.",
      "Explain why trackside/broadcast cameras and custom 4K raw iPhone-derived units complicate a single-camera-origin narrative.",
      "Reject the claim that every race image came from Carmen prototypes.",
      "Identify ARRI/Zeiss Master Primes as documented lenses for much of the VENICE 2 dramatic material.",
      "Use Super 35 5.8K 17:9 as a documented common VENICE 2 mode without treating it as universal.",
      "Identify selected 8.6K full-frame capture as a VFX/framing tool rather than a universal acquisition mode.",
      "Explain why Miranda protected both 2.39:1 and 1.90:1 framing.",
      "Reject the unsupported claim that F1 used 1.43:1 IMAX film framing as its primary format.",
      "Explain the IMAX version's move to 1.90:1 after introductory material as a release-format choice.",
      "Identify Ryan Tudhope as production VFX supervisor.",
      "Use more than 2,500 VFX shots as a scale anchor without inventing a full shot ledger.",
      "Identify Framestore and ILM as documented major VFX contributors without assigning every task to either vendor.",
      "Explain hidden VFX as a realism strategy rather than an absence of digital work.",
      "Identify digital car reskinning as a documented technique.",
      "Explain why weather/background replacement and race-combination work were needed around live-event capture.",
      "Recognize that Pitt and Idris did not compete in actual Formula 1 races.",
      "Reject both the mostly-CG and untouched-documentary descriptions of the racing imagery.",
      "Identify Stephen Mirrione as editor.",
      "Identify Avid Media Composer as the documented primary editorial platform.",
      "Identify ScriptSync as a documented tool for locating dialogue takes.",
      "Explain why race scenes needed distinct story logic to avoid spectacle fatigue.",
      "Explain how performance selection, VFX, sound and race continuity could mature in parallel.",
      "Keep the full edit revision and turnover ledger unresolved.",
      "Identify Gareth John as production sound mixer.",
      "Identify Al Nelson and Gwendolyn Yates Whittle as supervising sound editors.",
      "Identify Gary Rizzo and Juan Peralta as re-recording mixers.",
      "Explain why noisy live Grand Prix tracks could not by themselves provide a complete final engine soundtrack.",
      "Explain clean vehicle recording and engine reconstruction as separate from production dialogue capture.",
      "Explain Lewis Hamilton's sound validation as technical guidance rather than authorship of the entire sound mix.",
      "Explain gear, rev and braking synchronization as a picture-sound editorial problem.",
      "Identify Dolby Atmos as a documented final spatial-mix context.",
      "Explain why dialogue and score had to remain intelligible against dense engine material.",
      "Keep production sound, ADR, radio processing, Foley, effects editorial and final re-recording distinct.",
      "Identify Hans Zimmer as composer.",
      "Keep Zimmer's hybrid score distinct from engine sound design and soundtrack songs.",
      "Identify Mark Tildesley and Ben Munro as production designers.",
      "Identify Julian Day as costume designer.",
      "Explain why APXGP had to look credible beside real teams while remaining visually distinct.",
      "Keep the complete APXGP graphic, sponsor, costume and livery approval ledger unresolved.",
      "Keep the complete production budget, financing, ownership and recoupment structure unresolved.",
      "Keep every Grand Prix access contract, insurance rule, safety restriction and sporting-operation constraint unresolved.",
      "Keep the complete vehicle engineering, maintenance and race-preparation ledger unresolved.",
      "Keep the full camera, broadcast, iPhone, RF network, codec and color-management ledger unresolved.",
      "Keep the complete 5,000-hour media archive and 2,500-plus VFX shot/vendor ledger unresolved.",
      "Keep the complete production-sound, isolated-car-recording, ADR, Foley, mix, score and song-rights ledger unresolved.",
      "Keep the full IMAX, DCP, HDR, SDR, streaming and physical-media delivery matrix unresolved.",
      "Close the case only when awards, runtime, live-race access, race-car engineering, camera systems, multi-source capture, VFX, editorial, sound, music and unresolved boundaries agree."
    ],
    phases: [
      { id: "award_priority", label: "Lock award priority", player_task: "Use the Oscar/BAFTA Sound wins and Best Picture nomination for priority, not as workflow evidence." },
      { id: "runtime_boundary", label: "Freeze runtime provenance", player_task: "Use BBFC's 155m05s cinema version while keeping other release masters unresolved." },
      { id: "live_sport_access", label: "Embed inside Formula 1", player_task: "Plan fiction around real Grand Prix operations without assuming unrestricted control." },
      { id: "hamilton_advice", label: "Use technical advising", player_task: "Apply Lewis Hamilton's sport expertise without assigning every decision to him." },
      { id: "f2_chassis", label: "Start from race hardware", player_task: "Use Dallara F2 chassis rather than a conventional slow picture-car base." },
      { id: "apxgp_geometry", label: "Create APXGP proportions", player_task: "Extend wheelbase and build custom bodywork with Mercedes engineering input." },
      { id: "vehicle_variants", label: "Separate vehicle variants", player_task: "Keep combustion and electric APXGP configurations distinct by production need." },
      { id: "actor_driving", label: "Capture real performer driving", player_task: "Use Pitt/Idris driving where appropriate while preserving stunt-driver handoffs." },
      { id: "real_kinetic_energy", label: "Reject stage-default racing", player_task: "Prioritize real track motion instead of default volume/bluescreen substitution." },
      { id: "carmen_requirement", label: "Define the tiny cinema camera", player_task: "Engineer a full-frame sensor head small enough for high-speed cockpit mounting." },
      { id: "carmen_optics", label: "Match in-car optics", player_task: "Use Voigtländer and Zeiss Loxia choices according to view and geometry." },
      { id: "remote_pan", label: "Remote-control the camera", player_task: "Coordinate pan, focus and exposure through the car's networked camera system." },
      { id: "mount_budget", label: "Budget camera positions", player_task: "Choose among roughly fifteen mounts while limiting active cameras per setup." },
      { id: "crash_camera", label: "Protect dangerous coverage", player_task: "Use expendable/protected FX6 crash-camera strategies where appropriate." },
      { id: "venice_dramatic", label: "Shoot dramatic material", player_task: "Use VENICE 2 and Master Prime configurations for principal non-race coverage." },
      { id: "format_protection", label: "Protect 2.39 and 1.90", player_task: "Compose for theatrical scope while preserving digital IMAX immersion." },
      { id: "broadcast_integration", label: "Integrate real race feeds", player_task: "Combine production cinema cameras with broadcast/track sources without losing provenance." },
      { id: "custom_4k_track_camera", label: "Use tiny race-legal cameras", player_task: "Treat custom iPhone-derived 4K raw units as another acquisition layer." },
      { id: "race_calendar", label: "Follow the race calendar", player_task: "Capture short production windows across real 2023-2024 Grand Prix weekends." },
      { id: "media_ingest", label: "Control the footage flood", player_task: "Organize an estimated 5,000 hours of racing material without pretending every clip is equally useful." },
      { id: "invisible_vfx", label: "Design invisible VFX", player_task: "Use digital work to reconcile fiction and real competition without advertising the effect." },
      { id: "car_reskin", label: "Reskin racing vehicles", player_task: "Change car identity digitally where the photographed base does not match the story." },
      { id: "weather_background", label: "Repair event continuity", player_task: "Use weather/background work when live-event conditions cannot be repeated." },
      { id: "competitive_race_build", label: "Construct fictional competition", player_task: "Build race interactions without claiming actors joined real competitive sessions." },
      { id: "edit_race_story", label: "Make each race tell story", player_task: "Prevent high-speed sequences from collapsing into interchangeable spectacle." },
      { id: "media_composer", label: "Cut in Media Composer", player_task: "Use the documented Avid environment for long-form narrative assembly." },
      { id: "scriptsync", label: "Find performance quickly", player_task: "Use ScriptSync to navigate dialogue material while race/VFX elements evolve." },
      { id: "sound_reference", label: "Build technical sound references", player_task: "Separate noisy live-event capture from clean vehicle recordings and final reconstruction." },
      { id: "engine_sync", label: "Synchronize engine behavior", player_task: "Match revs, shifts and braking behavior to picture with technical validation." },
      { id: "dialogue_music_balance", label: "Preserve intelligibility", player_task: "Keep dialogue and score readable inside dense race sound." },
      { id: "atmos_mix", label: "Build spatial race scale", player_task: "Use Dolby Atmos as a documented theatrical spatial-mix context." },
      { id: "score_layer", label: "Keep score distinct", player_task: "Use Zimmer's score as music rather than treating it as engine sound design." },
      { id: "apxgp_identity", label: "Design the fictional team", player_task: "Make APXGP credible beside real teams without copying one existing identity." },
      { id: "versioning", label: "Protect delivery provenance", player_task: "Keep IMAX, scope, streaming and home masters distinct until directly evidenced." },
      { id: "uncertainty_register", label: "Freeze unresolved ledgers", player_task: "Keep finance, access, safety, vehicle, camera, VFX, editorial, audio and delivery ledgers explicit." },
      { id: "production_verification", label: "Close F1 production audit", player_task: "Verify awards, runtime, live-race access, vehicles, camera, VFX, edit, sound, music and unresolved boundaries before canonical promotion." }
    ]
  }
] as const;

export function mergeChapterNineteenF1Expansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterNineteenF1ExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_nineteen_f1_verified",
      source: { list_id: "manual_chapter_nineteen_f1_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
