import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterEighteenTheIrishmanExpansionDefinitions = [
  {
    id: "scenario_the_irishman_2019",
    title: "The Irishman",
    originalTitle: "The Irishman",
    year: 2019,
    titleType: "Movie",
    runtimeMins: 209,
    directors: ["Martin Scorsese"],
    genres: ["Crime", "Drama", "Biography"],
    sourceId: "film_lincoln_center_the_irishman_2019",
    sourceUrl: "https://www.filmlinc.org/nyff2019/films/the-irishman/",
    scenarioType: "american_streaming_epic_hybrid_35mm_red_helium_ir_witness_markerless_flux_deaging_longform_editorial_restrained_sound_2019",
    premise: "Build The Irishman as Chapter 18's late-2010s production case about a long-form American crime film whose historical span required hybrid photochemical/digital cinematography, markerless facial-performance capture, performance-preserving visual effects, large-scale period production design, unusually extended editorial iteration and deliberately restrained sound. Film at Lincoln Center records the 2019 New York Film Festival opening-night presentation at 209 minutes and identifies Martin Scorsese as director; Netflix is the release platform, but platform distribution is not itself proof of how the film was photographed, edited or mixed. Cinematographer Rodrigo Prieto documents that material not requiring de-aging was photographed on 35mm Kodak stock, while scenes requiring the facial-age work used a RED Helium as the primary camera with two synchronized ARRI ALEXA Mini infrared witness cameras on a custom three-camera rig developed with ILM and ARRI. Keep those capture systems separate: the production is neither simply a 35mm film nor simply an all-digital Netflix feature. Prieto designed different period looks around remembered photographic color characteristics from successive decades, but a LUT or stock reference is not a substitute for lighting, exposure, filtration, art direction or grading decisions. ILM states that Scorsese and the actors required de-aging performances to be captured on set without visible facial markers or head-mounted cameras. Pablo Helman's team therefore developed a markerless process in which the synchronized RGB and infrared images, set lighting data and geometry information fed the Flux system. Flux is a reconstruction and retargeting toolchain, not evidence that the performances were generated automatically; the final younger faces remain dependent on the actors' photographed timing, expression and body work, artist supervision, modeling, rendering and compositing. ILM reports 1,750 visual-effects shots overall, while its detailed accounts distinguish the subset using fully CG younger faces from the wider body of invisible VFX. Do not describe all 1,750 shots as de-aging. Production design by Bob Shaw and set decoration by Regina Graves had to support a story moving across decades and hundreds of environments; contemporary interviews describe roughly 295 sets and locations, with stage builds including period restaurants, houses and car interiors. Treat that number as production-scale evidence rather than a claim that every listed environment was independently built. Thelma Schoonmaker describes an edit that took about a year, with abrupt temporal transitions, long accumulation and deliberately plain violence. VFX review continued after the picture was substantially shaped: Schoonmaker could ask ILM to restore facial detail when a younger render weakened acting information. Editorial and VFX therefore exchange performance judgments rather than existing as a one-way picture-lock pipeline. Sound follows the same anti-spectacle discipline. Schoonmaker, supervising sound editors Eugene Gearty and Philip Stockton, and re-recording mixer Tom Fleischman describe Scorsese's request for fewer sound effects and for silence or sparse detail to carry power. Period cars and environments were still researched and recorded, but the final track avoids constant sonic emphasis. The case should leave the player able to trace a scene from script and period design through either 35mm or three-camera digital acquisition, actor performance, markerless capture data, Flux/VFX reconstruction, editorial review, sound editorial and final mix, while separating documented production method from claims about historical truth, awards, technological novelty or later influence.",
    requiredChoicesSeed: {
      screenplay: ["memory_frame_structure", "decades_without_exposition", "violence_as_banal_action", "loyalty_consequence_arc", "historical_claim_boundary"],
      camera: ["hybrid_35mm_digital_map", "red_helium_primary", "dual_ir_alexa_witness", "synchronized_three_camera_rig", "period_look_lut_boundary", "lighting_for_vfx_and_drama"],
      editing: ["longform_temporal_map", "abrupt_transition_logic", "performance_over_vfx_polish", "vfx_review_loop", "plain_violence_duration", "final_act_deceleration"],
      sound: ["restraint_over_density", "period_vehicle_recording", "room_tone_specificity", "silence_as_structure", "dialogue_priority", "final_mix_continuity"],
      themes: ["film_history", "2019", "the_irishman", "martin_scorsese", "steven_zaillian", "rodrigo_prieto", "thelma_schoonmaker", "bob_shaw", "regina_graves", "pablo_helman", "eugene_gearty", "philip_stockton", "tom_fleischman", "netflix", "35mm", "kodak_vision3", "red_helium", "alexa_mini", "infrared_witness_camera", "three_headed_monster", "markerless_capture", "flux", "deaging", "performance_preservation", "period_production_design", "longform_editing", "restrained_sound", "209_minutes"],
    },
    learningGoals: [
      "Explain The Irishman as a coordinated production system rather than a de-aging technology demonstration.",
      "Identify Martin Scorsese as director and Steven Zaillian as screenwriter without treating authorship as a one-person process.",
      "Identify Rodrigo Prieto, Thelma Schoonmaker, Bob Shaw, Pablo Helman, Eugene Gearty, Philip Stockton and Tom Fleischman in their documented craft roles.",
      "Preserve Film at Lincoln Center's 209-minute 2019 festival record as release metadata rather than using streaming interface data as production proof.",
      "Distinguish Netflix's distribution/platform role from the production methods used by camera, VFX, editorial and sound departments.",
      "Explain why the film uses both 35mm acquisition and digital acquisition instead of flattening it into one format.",
      "Identify 35mm Kodak capture for material not requiring the de-aging workflow.",
      "Identify the RED Helium as the primary camera for scenes requiring the specialized facial-performance pipeline.",
      "Identify the paired ARRI ALEXA Mini cameras as infrared witness cameras rather than additional beauty-picture cameras.",
      "Explain why the three cameras needed synchronized shutters and matched spatial relationships.",
      "Explain how infrared witness imagery captured useful facial information without visible tracking markers on the performers.",
      "Separate the actors' performance from the later digital reconstruction of younger facial appearance.",
      "Describe Flux as part of a markerless reconstruction and retargeting workflow rather than an automatic performance generator.",
      "Explain why lighting data, HDRI or set geometry can be production evidence for VFX without replacing cinematographic lighting intent.",
      "Distinguish the reported 1,750 VFX shots from the smaller subset requiring fully CG younger faces.",
      "Avoid describing every VFX shot in the film as a de-aging shot.",
      "Explain why face replacement still depends on modeling, matching, rendering, compositing and artist review.",
      "Describe editorial review of de-aged faces as a performance-preservation task, not only a continuity or technical-QC task.",
      "Explain Schoonmaker's ability to request restored wrinkles or facial detail when an effect weakened acting information.",
      "Describe the approximately year-long edit as part of the film's long-form temporal construction rather than a simple consequence of runtime.",
      "Explain why abrupt transitions can coexist with an overall slow accumulation across decades.",
      "Describe the film's plain presentation of killings as an editorial/directorial strategy that resists glamorized action coverage.",
      "Explain why long duration, sparse coverage and abrupt violence require precise performance timing rather than more cutting by default.",
      "Describe Prieto's period-look strategy as a coordinated color-memory system rather than a claim that each decade literally reproduces one historical stock.",
      "Separate LUT, stock, lens, exposure, lighting, production design and grade as distinct contributors to the final period image.",
      "Explain why the visual-effects camera rig had to remain usable on normal heads and within practical sets instead of turning the production into a capture stage.",
      "Describe Bob Shaw's and Regina Graves's period-world work as a large environment-management problem across decades.",
      "Use the roughly 295 sets-and-locations figure as scale evidence without claiming 295 independently constructed sets.",
      "Explain how stage-built restaurants, houses and vehicle interiors support repeatable camera, lighting and performance control.",
      "Distinguish period authenticity work from proof that the film's contested historical claims are true.",
      "Explain why a biographical crime narrative still requires source-boundary discipline between production history and story assertions.",
      "Describe Scorsese's request for fewer sound effects as a mixing and editorial constraint rather than literal absence of sound design.",
      "Explain how period vehicle recording and detailed ambience can support realism while the final track remains sparse.",
      "Identify silence and low-density backgrounds as designed choices that require active mixing decisions.",
      "Distinguish dialogue editing, effects editing, ambience, Foley, music and re-recording even when the final soundtrack sounds understated.",
      "Explain why sonic restraint can make a single gunshot, door, engine or room tone more narratively legible.",
      "Compare The Irishman with Parasite: both are digitally finished late-2010s productions, but one centers hybrid capture and facial VFX while the other centers constructed-space geometry and controlled large-format digital capture.",
      "Compare The Irishman with Spider-Verse: both redesign pipelines around performance intent, but one preserves photographed acting through markerless VFX while the other reshapes CG animation around illustration-led intervention.",
      "Compare The Irishman with Zodiac: both use digital postproduction to manage period crime narratives, while their capture technologies and temporal structures differ.",
      "Keep awards, reviews and later influence downstream from evidence about how a shot, face, cut or sound element was made.",
      "Reject claims that the film invented digital de-aging, markerless capture, hybrid film/digital cinematography, long-form editing or sparse sound design.",
      "Audit every novelty claim against whether the source is a practitioner account, institutional record, vendor case study, trade report or later interpretation.",
    ],
    phases: [
      { id: "evidence_map", label: "Map the evidence hierarchy", player_task: "Separate festival metadata, practitioner interviews, vendor case studies, trade reporting and later reception before production claims enter the brief." },
      { id: "runtime_lock", label: "Lock the release record", player_task: "Record the 209-minute 2019 NYFF presentation and keep that release metadata separate from capture, post and later platform versions." },
      { id: "story_decades_map", label: "Map the decades", player_task: "Break the screenplay into time periods, character ages and recurring locations so camera, design, makeup and VFX needs can be scheduled coherently." },
      { id: "history_boundary", label: "Separate story from proof", player_task: "Mark disputed biographical or historical assertions as narrative content unless independently verified; do not use production craft sources as historical fact-checks." },
      { id: "capture_split", label: "Choose film or digital per scene", player_task: "Map scenes not requiring de-aging to 35mm capture and scenes requiring the markerless facial workflow to the synchronized digital rig." },
      { id: "film_negative_plan", label: "Plan the 35mm path", player_task: "Track stock, exposure, processing, scan and grade for photochemical-origin material so it can coexist with digitally captured VFX scenes." },
      { id: "three_camera_rig", label: "Build the three-camera rig", player_task: "Synchronize the RED Helium primary camera with two infrared ALEXA Mini witness cameras while preserving normal operating movement and set access." },
      { id: "ir_capture", label: "Capture invisible witness data", player_task: "Use infrared witness images to gather facial information without visible markers while keeping the production image and actors' eyelines unobstructed." },
      { id: "lighting_coordination", label: "Coordinate drama and capture", player_task: "Light the photographed scene for story and faces while recording the reference information VFX needs for later reconstruction." },
      { id: "period_look_tests", label: "Test remembered color eras", player_task: "Build controlled look tests for successive decades and document what comes from stock, LUT, lighting, art direction and final grade." },
      { id: "performance_capture", label: "Protect the on-set performance", player_task: "Evaluate takes for acting first; markerless technology must preserve the selected timing and expression rather than redirect performance around equipment." },
      { id: "vfx_reference_ingest", label: "Ingest VFX reference", player_task: "Organize synchronized RGB/IR imagery, camera solves, lighting reference and set geometry so every facial shot can be traced back to its photographed take." },
      { id: "flux_solve", label: "Run the Flux reconstruction", player_task: "Use Flux and related facial tools to reconstruct the photographed expression while keeping the distinction between captured performance data and artist-built younger geometry." },
      { id: "younger_face_build", label: "Build age-specific faces", player_task: "Create age-specific facial models and surface responses without erasing individual asymmetry, muscle movement or expression cues from the actor." },
      { id: "render_comp", label: "Render and composite", player_task: "Integrate younger facial renders into the plate while matching lighting, grain, lens behavior and surrounding skin/body continuity." },
      { id: "vfx_scope_audit", label: "Audit the 1,750-shot figure", player_task: "Tag which VFX shots actually contain facial age work and which serve other invisible-effects tasks so the global shot count is not misrepresented." },
      { id: "period_environment_plan", label: "Schedule the period world", player_task: "Coordinate hundreds of locations and set states across decades, prioritizing spaces that need repeatable camera, lighting, reset or vehicle control." },
      { id: "stage_builds", label: "Build repeatable interiors", player_task: "Use stage-built restaurants, homes and car interiors where repeatability or camera access justifies construction, and label found locations separately." },
      { id: "editorial_longform_map", label: "Map the long-form edit", player_task: "Track chronology, flashback position, recurring faces and emotional information across the 209-minute structure before polishing local transitions." },
      { id: "abrupt_transition_test", label: "Test abrupt transitions", player_task: "Use hard temporal or spatial transitions where they serve the film's moral and tonal logic without confusing essential chronology." },
      { id: "violence_restraint", label: "Cut violence plainly", player_task: "Test whether a killing remains legible and disturbing with minimal coverage and duration instead of defaulting to action-style fragmentation." },
      { id: "vfx_editorial_loop", label: "Review acting after de-aging", player_task: "Compare VFX iterations against the selected performance and request restored facial detail whenever younger rendering weakens acting information." },
      { id: "late_act_deceleration", label: "Protect the final deceleration", player_task: "Let the retirement, isolation and mortality sections change rhythm without treating slower pace as material that must be compressed." },
      { id: "sound_restraint_brief", label: "Write the restraint brief", player_task: "Define where silence, sparse effects and dialogue priority should dominate so sound teams do not fill every available moment by habit." },
      { id: "period_vehicle_recording", label: "Record period vehicles", player_task: "Capture period-appropriate engines, doors and road behavior as source material, then use only what the final dramatic perspective requires." },
      { id: "ambient_specificity", label: "Build specific room tones", player_task: "Create distinct environmental beds for homes, restaurants, institutional spaces and vehicles while keeping density subordinate to dialogue and performance." },
      { id: "effects_selectivity", label: "Choose effects selectively", player_task: "Prioritize the few gunshots, doors, footsteps or mechanical details that carry perspective instead of increasing loudness or track count for spectacle." },
      { id: "final_mix", label: "Complete the restrained mix", player_task: "Balance dialogue, effects, ambience, Foley and music so the understated design survives theatrical and home playback without flattening dynamic contrast." },
      { id: "release_platform_boundary", label: "Separate film from platform", player_task: "Record Netflix distribution and exhibition context without using platform technology as evidence for the camera or postproduction choices." },
      { id: "method_audit", label: "Audit novelty and history claims", player_task: "Review every claim of first, invention, realism or historical truth against the source hierarchy and downgrade anything not supported by appropriate evidence." },
    ],
  },
] as const;

export function mergeChapterEighteenTheIrishmanExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterEighteenTheIrishmanExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_eighteen_the_irishman_verified",
      source: { list_id: "manual_chapter_eighteen_the_irishman_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
