import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterEighteenChildrenOfMenExpansionDefinitions = [
  {
    id: "scenario_children_of_men_2006",
    title: "Children of Men",
    originalTitle: "Children of Men",
    aliases: ["The Children of Men"],
    year: 2006,
    titleType: "Movie",
    runtimeMins: 114,
    directors: ["Alfonso Cuarón"],
    genres: ["Drama", "Sci-Fi", "Thriller"],
    sourceId: "bfi_children_of_men_2006",
    sourceUrl: "https://www.bfi.org.uk/film/aca1e8dc-9c0d-51fa-abf1-83b68192d3c9/children-of-men",
    scenarioType: "uk_usa_japan_35mm_handheld_long_take_natural_light_two_axis_car_rig_digital_intermediate_invisible_vfx_2006",
    premise: "Build Children of Men as a source-first Chapter 18 Production Case about a 2006 USA/United Kingdom/Japan production whose documentary-like immediacy was engineered through 35mm negative, extreme exposure management, handheld staging, long-duration blocking, specialized camera rigs, digital intermediate work and deliberately invisible visual effects. BFI records Alfonso Cuarón as director, Emmanuel Lubezki as cinematographer, Hilary Shor, Marc Abraham, Tony Smith, Eric Newman and Iain Smith as producers, a 114-minute running time, and the USA/United Kingdom/Japan production context. AFI independently preserves the screenwriting, production, camera, editorial and sound-credit structure. American Cinematographer documents Kodak Vision2 Expression 500T 5229 as the principal stock chosen for low contrast and extreme interior/exterior latitude, with 35mm dailies given a 30-percent Deluxe ACE silver-retention treatment so the production could judge denser blacks before the final digital intermediate. Lubezki and colorist Steve Scott at EFilm used the DI to desaturate the picture while preserving a naturalistic rather than glossy future. The camera system was not one generic package: American Cinematographer records extensive handheld Arricam Lite use, an Arri 235 in the car ambush, early Arri/Zeiss Master Primes, an Ultra Prime kept available when lens weight became impractical, and an 18mm lens for much of the film without making that focal length universal. The visual strategy avoided conventional coverage, minimized movie lighting, used available and practical sources where possible, and forced exposure changes across long takes; some locations were moved to stages when winter daylight failed, so the case distinguishes location naturalism from the controlled lighting required to preserve it. The car ambush was engineered with Gary Thieltges' Doggicam Two-Axis Dolly, a Sparrow Head and a roofless vehicle operated from above the actors. The finished apparent one-shot contains seamless cuts, so the player must not equate long-take appearance with an uninterrupted negative. Framestore documents another critical boundary in the birth sequence: the approximately three-and-a-half-minute handheld sequence was assembled from two invisibly joined sections, used a partial physical baby stand-in for interaction, and replaced it with a photoreal CG baby. Framestore delivered 32 shots, 20 featuring the baby, with paint, tracking, animation, rendering and compositing handoffs using Maya, RenderMan, MatchMover/Boujou, Commotion and Shake. This does not license the claim that the film is primarily a CGI production; the production achievement is the coordination of practical staging, 35mm capture and selective invisible digital intervention. Production designers Jim Clay and Geoffrey Kirkland, set decorator Jennifer Williams and costume designer Jany Temime are preserved from institutional/trade records, while editors Alfonso Cuarón and Alex Rodríguez remain distinct from DI, VFX and sound-post roles. The player must therefore coordinate one difficult sequence from evidence hierarchy and production design through blocking, 35mm exposure, handheld operation, specialized rigging, production sound, editorial concealment, VFX replacement, color finishing and exhibition, while keeping runtime variants, awards, later canon status and unsupported equipment details outside the production-fact layer.",
    requiredChoicesSeed: {
      screenplay: ["future_as_present", "documentary_observation", "violence_without_glamor", "long_take_information_flow", "runtime_version_boundary", "adaptation_boundary"],
      camera: ["35mm_5229", "arricam_lite", "arri_235", "master_prime_ultra_prime", "18mm_nonuniversal", "handheld_camera", "two_axis_car_rig", "natural_light_exposure", "ace_dailies", "di_finish"],
      editing: ["avoid_conventional_coverage", "long_take_rhythm", "seamless_cut_boundary", "birth_sequence_join", "vfx_editorial_handoff", "runtime_versioning"],
      sound: ["production_sound", "supervising_sound_edit", "offscreen_context", "variable_hum_design", "re_recording_boundary", "music_boundary"],
      themes: ["film_history", "2006", "children_of_men", "alfonso_cuaron", "emmanuel_lubezki", "united_kingdom", "usa", "japan", "kodak_5229", "35mm", "arricam_lite", "arri_235", "master_prime", "ultra_prime", "handheld", "long_take", "doggicam", "sparrow_head", "ace_dailies", "efilm_di", "framestore", "cg_baby", "production_design", "invisible_vfx"],
    },
    learningGoals: [
      "Explain Children of Men as a 2006 production system rather than only as dystopian science fiction.",
      "Identify Alfonso Cuarón as director and Emmanuel Lubezki as cinematographer from institutional and trade records.",
      "Preserve BFI's USA/United Kingdom/Japan production geography without collapsing the film into one national industry.",
      "Use BFI's 114-minute record as the playable runtime anchor while preserving shorter 109/110-minute records as release or database provenance rather than silently normalizing them.",
      "Identify Hilary Shor, Marc Abraham, Tony Smith, Eric Newman and Iain Smith as the producer group preserved by BFI and AFI.",
      "Keep adaptation authorship separate from production authorship and do not treat P. D. James's novel as evidence for how scenes were photographed.",
      "Explain why Cuarón and Lubezki avoided conventional A-B-A-B coverage for much of the film.",
      "Explain how long takes were designed to create presence while still being shortened or invisibly joined when rhythm and logistics required it.",
      "Reject the claim that every famous Children of Men long take is literally one uninterrupted negative.",
      "Identify Kodak Vision2 Expression 500T 5229 as the principal American Cinematographer-documented stock.",
      "Explain why 5229's low contrast helped hold detail between dark interiors and bright exteriors when additional lighting was minimized.",
      "Identify the 30-percent Deluxe ACE silver-retention treatment on 35mm dailies as a viewing and judgment step, not the final release grade.",
      "Separate the photochemical dailies look from the later EFilm digital intermediate.",
      "Identify Steve Scott as the American Cinematographer-documented DI colorist at EFilm.",
      "Explain that desaturation in the DI was used to support naturalism rather than to prove an all-digital capture pipeline.",
      "Identify Arricam Lite as a major handheld production camera without claiming it was the only body used.",
      "Identify the Arri 235 inside the car rig for the ambush sequence.",
      "Identify early Arri/Zeiss Master Primes and the backup Ultra Prime without inventing a complete lens inventory.",
      "Record that much of the film used an 18mm lens while preserving Lubezki's own warning that there were exceptions.",
      "Explain why constant f-stop changes became a major operational burden when natural light shifted during long takes.",
      "Distinguish naturalistic lighting from the claim that the film used no lighting.",
      "Explain why some winter locations had to be recreated on soundstages when daylight became insufficient.",
      "Use the bus example to show that planned movie lights could be removed when available light solved the exposure problem.",
      "Explain how practical or story-world fixtures could function as motivated production lighting.",
      "Separate aesthetic accidents such as changing sunlight from unmanaged exposure mistakes.",
      "Identify Gary Thieltges' Two-Axis Dolly and the Sparrow Head as title-specific components of the car-ambush rig.",
      "Explain that the roofless car and overhead operating platform were engineered so the camera could move among actors while the vehicle traveled.",
      "Keep the car rig's specialized mechanics separate from ordinary handheld operating elsewhere in the film.",
      "Record that the car sequence contains seamless cuts and use this as an editorial/VFX boundary rather than calling the shot fraudulent.",
      "Explain how documentary-inspired camera distance and wide-angle framing were used to deglamorize violence.",
      "Separate camera objectivity as an aesthetic goal from literal documentary production.",
      "Identify Jim Clay and Geoffrey Kirkland as production designers and Jennifer Williams as set decorator from institutional/trade records.",
      "Explain how the future was built from degraded, familiar present-day infrastructure rather than clean futuristic novelty.",
      "Identify Jany Temime as costume designer without inventing wardrobe-fabrication procedures not established by the selected sources.",
      "Identify Alfonso Cuarón and Alex Rodríguez as editors and keep editorial responsibility distinct from camera and VFX departments.",
      "Explain how invisible joins can preserve apparent real-time duration while solving actor, camera and effects logistics.",
      "Identify Framestore and Tim Webber's team as responsible for the most demanding CG-baby work.",
      "Record that the birth sequence was roughly three and a half minutes and built from two invisibly joined sections rather than one untouched take.",
      "Explain the purpose of the partial physical baby stand-in for actor interaction and later paint-out.",
      "Record Framestore's 32 delivered shots and 20 baby shots without generalizing those numbers to the film's total VFX count.",
      "Identify Maya, RenderMan, MatchMover/Boujou, Commotion and Shake as Framestore-documented tools for the baby work without claiming the whole film used the same software stack.",
      "Explain why tracking, paint, animation, lighting and compositing are separate handoffs inside one invisible-VFX shot.",
      "Reject the inference that a photoreal CG baby means the surrounding performance, lighting or camera movement was synthetic.",
      "Identify David Evans and Richard Beggs within the AFI supervising-sound record while leaving exact responsibility splits source-bounded.",
      "Explain how Lubezki coordinated a variable humming sound with a deliberately unstable shutter/light effect without turning that example into a universal sound rule.",
      "Keep production sound, sound editing, re-recording and John Tavener's music as distinct production layers.",
      "Separate awards for cinematography, editing or production design from evidence about the original workflow.",
      "Reject claims that Children of Men invented long takes, handheld realism, digital compositing, photoreal CG humans or DI finishing.",
      "Audit every claim about exact camera serials, per-shot focal lengths, shutter angles, laboratory scan resolution, sound recorder, microphones, VFX shot count beyond Framestore's contribution and final release-print process against a title-specific source before promoting it to production fact.",
      "Explain why Children of Men is historically useful as a digital-convergence case precisely because photochemical capture, photochemical dailies, specialized mechanical rigs, digital intermediate and invisible VFX all coexist.",
    ],
    phases: [
      { id: "evidence_hierarchy", label: "Map the evidence hierarchy", player_task: "Separate BFI/AFI credits, American Cinematographer craft testimony, Framestore VFX documentation and later reception before converting details into production facts." },
      { id: "runtime_versions", label: "Lock runtime provenance", player_task: "Use BFI's 114-minute record as the playable anchor while retaining shorter public records as version provenance rather than production contradictions." },
      { id: "production_network", label: "Map the production network", player_task: "Separate producers, national production labels, departments and vendors instead of treating the UK/USA/Japan production as one company." },
      { id: "adaptation_boundary", label: "Separate adaptation from production", player_task: "Use the novel and screenplay only for narrative provenance; do not derive camera or design facts from the source book." },
      { id: "future_as_present", label: "Design a familiar future", player_task: "Build 2027 from modified present-day infrastructure so production design feels accumulated and degraded rather than generically futuristic." },
      { id: "coverage_strategy", label: "Reject default coverage", player_task: "Block a scene around a self-contained moving shot and reserve conventional coverage only for a documented dramatic need." },
      { id: "long_take_blocking", label: "Block for duration", player_task: "Coordinate actors, background action, camera, focus and exposure so information changes continuously inside a long take." },
      { id: "stock_choice", label: "Choose the 35mm stock", player_task: "Use Kodak 5229's documented low-contrast latitude to solve extreme interior/exterior exposure differences without inventing alternate stocks." },
      { id: "camera_package", label: "Map the 35mm package", player_task: "Track Arricam Lite, Arri 235, Master Prime and Ultra Prime roles while keeping unsupported body/lens combinations open." },
      { id: "wide_lens_strategy", label: "Use wide-angle distance", player_task: "Use the documented 18mm preference as a dominant strategy while explicitly preserving exceptions." },
      { id: "handheld_operation", label: "Operate handheld", player_task: "Design handheld movement that can observe context independently of actor movement without turning camera shake into randomness." },
      { id: "exposure_riding", label: "Ride exposure through the take", player_task: "Plan live f-stop changes as actors move between dark interiors and bright windows while protecting continuity across takes." },
      { id: "available_light", label: "Use naturalistic light", player_task: "Start from available or motivated sources, then add or remove movie lighting according to exposure rather than a blanket no-light rule." },
      { id: "stage_substitution", label: "Move naturalism to stage", player_task: "When winter daylight fails, recreate location logic on stage and preserve window-motivated illumination instead of abandoning the visual system." },
      { id: "ace_dailies", label: "Prepare ACE dailies", player_task: "Use the documented 30-percent Deluxe ACE treatment to judge denser blacks in 35mm dailies without confusing it with final DI color." },
      { id: "car_rig_engineering", label: "Engineer the car ambush", player_task: "Coordinate the roofless vehicle, Doggicam Two-Axis Dolly, Sparrow Head, Arri 235, focus and low-position drivers as one safety-critical rig." },
      { id: "car_long_take", label: "Stage the ambush take", player_task: "Move the camera among five actors while preserving vehicle motion, performance beats, practical impacts and operator clearance." },
      { id: "seamless_cut", label: "Hide the necessary joins", player_task: "Place invisible cuts at motivated visual events so the apparent long take remains immersive without falsely claiming an uninterrupted negative." },
      { id: "violence_boundary", label: "Avoid glamorous violence", player_task: "Use wide, mobile observation and limited coverage so violent action reads as chaotic context rather than fetishized spectacle." },
      { id: "production_design", label: "Coordinate the art department", player_task: "Give Jim Clay, Geoffrey Kirkland and Jennifer Williams separate design/decor responsibilities while keeping undocumented set assignments open." },
      { id: "costume_context", label: "Preserve costume independence", player_task: "Let Jany Temime's character logic remain primary instead of forcing every wardrobe value to serve cinematography." },
      { id: "production_sound", label: "Capture production sound", player_task: "Plan long-take sound continuity and actor intelligibility while leaving unsupported recorder and microphone models unknown." },
      { id: "sound_design", label: "Extend the frame with sound", player_task: "Use offscreen ambience, impacts and the documented variable hum example to add context without converting one effect into a film-wide rule." },
      { id: "editing_structure", label: "Edit duration, not coverage", player_task: "Give Cuarón and Alex Rodríguez editorial control over long-take length and joins rather than assuming long takes eliminate editing." },
      { id: "birth_practical_plate", label: "Shoot the birth plates", player_task: "Use the handheld birth setup and partial physical baby stand-in to preserve actor contact, eyelines and interactive lighting." },
      { id: "birth_join", label: "Build the invisible birth join", player_task: "Join the two documented sections when Kee is briefly out of view so staging logistics disappear inside apparent real time." },
      { id: "cg_baby", label: "Create the digital baby", player_task: "Replace the stand-in with a photoreal CG infant while matching motion, skin, lighting, Theo's hands, dress interaction and atmospheric detail." },
      { id: "vfx_tracking_paint", label: "Track and paint the plate", player_task: "Separate tracking, cable/stand-in removal and plate repair before animation and final compositing." },
      { id: "vfx_animation_render", label: "Animate and render the baby", player_task: "Use Framestore's documented Maya/RenderMan pipeline as title-specific evidence and keep unsupported global pipeline claims out." },
      { id: "vfx_composite", label: "Composite invisible VFX", player_task: "Integrate the baby into changing handheld light and contact points so the effect supports the documentary surface rather than calling attention to itself." },
      { id: "digital_intermediate", label: "Grade the final image", player_task: "Move from 35mm negative into the EFilm DI, use Steve Scott's documented desaturation work and keep exact scan/output resolution unknown unless sourced." },
      { id: "version_provenance", label: "Separate production from reception", player_task: "Keep awards, later canon status and runtime variants downstream from the production-evidence model." },
      { id: "unknowns_register", label: "Register technical unknowns", player_task: "Keep exact shutter angles, camera serials, shot-by-shot focal lengths, sound equipment, non-Framestore VFX counts and final release-print details unknown unless title-specific evidence establishes them." },
    ],
  },
] as const;

export function mergeChapterEighteenChildrenOfMenExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterEighteenChildrenOfMenExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_eighteen_children_of_men_verified",
      source: { list_id: "manual_chapter_eighteen_children_of_men_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
