import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterNineteenFuriosaExpansionDefinitions = [{
  id: "scenario_furiosa_a_mad_max_saga_2024",
  title: "Furiosa: A Mad Max Saga",
  originalTitle: "Furiosa: A Mad Max Saga",
  aliases: ["Furiosa"],
  year: 2024,
  titleType: "Movie",
  runtimeMins: 148,
  directors: ["George Miller"],
  genres: ["Action", "Adventure"],
  sourceId: "screen_nsw_furiosa_2024",
  sourceUrl: "https://www.screen.nsw.gov.au/news/mad-max-prequel-furiosa-to-be-filmed-in-nsw",
  scenarioType: "scheduler_priority_australian_action_practical_vehicles_stunts_physical_sets_alexa65_red_arrays_unreal_previs_digital_environments_cg_takeovers_on_set_editorial_first_person_score_atmos_mix_2024",
  premise: "Build Furiosa: A Mad Max Saga as the next Chapter 19 Production Case because the balanced scheduler advances to the industrial_scale_technical lane after Spider-Man: Across the Spider-Verse closes the remaining P0 gap. Furiosa remains a P1 source-first case; selection is not an award claim. Version provenance stays explicit. BBFC records the UK cinema version at 148m02s, rounded to 148 playable minutes, and a home-entertainment version at 148m11s. Cannes records the film at 2h28. The locked evidence does not establish the exact master-lineage reason for the nine-second BBFC difference, so that difference remains unresolved rather than being normalized away. The production is also a useful Chapter 19 financing and regional-industry case, but announcement figures must remain announcement figures. Screen NSW stated before production that Furiosa was expected to create more than 850 local jobs and inject about A$350 million into the NSW economy, with support through Made in NSW, the federal PDV Rebate and the 40 percent Producer Offset. Those projections do not establish final audited local employment, final spend, total budget, financing waterfall or incentive receipts. Screen NSW identified Kennedy Miller Mitchell, Warner Bros. and Village Roadshow in the production/distribution structure and key Australian heads including production designer Colin Gibson, editor Margaret Sixel, sound mixer Ben Osmo, first assistant director P.J. Voeten and second-unit director/stunt coordinator Guy Norris. The film's core production lesson is that practical and digital systems are complementary. Art director Jacinta Leong describes the War Rig as a physical design-and-engineering problem: the production reused the same tanker/chassis structure retained from Fury Road, Leong and set designer Jemma Awad developed construction drawings, mechanics built the vehicle, and a model was passed to Guy Norris and the stunt team for action previs. This is not evidence that every vehicle, environment or stunt remained fully practical. Simon Duggan ASC ACS and ARRI Rental document ALEXA 65 photography with DNA lenses, including custom optics, while George Miller's action planning used Unreal Engine previs. Camera movement was designed to stay close to actors and moving vehicles through remote crane-arm and Steadicam work, with 360-degree coverage frequently limiting conventional keying-screen placement and increasing the need for rotoscoped foreground extraction and background extensions. American Cinematographer documents the difficult Australian weather and a large artificial-daylight strategy: six 18K HMI PARs mounted on three telescopic handlers were used to create controllable sun-like continuity when clouds, rain and wind disrupted natural daylight. RED separately documents V-RAPTOR and KOMODO use, multi-camera arrays and a RED Control Pro application developed for the production so multiple KOMODO bodies could be controlled from an iPad; the spherical 2.39 framing protected 16:9 image area for VFX reframing. These records establish a heterogeneous acquisition system, not a complete camera-body/lens/filter/media inventory for every unit. Screen NSW key grip Adam Kuiper likewise describes vehicle/crane mounting and the need to plan what is physically photographed versus what will be extended digitally. DNEG's official breakdown provides unusually specific vendor-scoped numbers that must not be mistaken for whole-film totals: DNEG says more than 1,000 artists delivered 880 shots across 24 key sequences, built 16 signature environments, more than 100 character assets and more than 50 vehicles. DNEG identifies the Stowaway to Nowhere work as a 250-shot sequence assembled from material filmed across 78 separate days in NSW and at Fox Studios Sydney. Weather and the long schedule required generated Wasteland backgrounds, while live-action characters and vehicles were extracted from photographed plates and nearly every vehicle also received a full-CG counterpart built from scans and reference. Bullet Farm began with physical production elements that DNEG extended digitally, while Gas Town drew on scans, photography and industrial-reference libraries. Framestore documents the same hybrid logic from another vendor: editorial/postvis rough composites shaped evolving chase work, safety required CG takeovers and some full-CG shots, and weather sometimes forced vehicles to be photographed static under cover before motion, suspension, wheels and bright exterior environments were created in post. Those facts support a practical-plus-digital production system; they do not support a slogan that either practical effects or CGI alone made Furiosa. Editorial was embedded in production. Editor Eliot Knapman describes working on set with Miller on first assembly while Margaret Sixel remained co-editor, allowing photographed action, previs, postvis and evolving structure to meet early instead of waiting for a conventional post-only edit. The locked sources do not establish a complete edit-software, storage, proxy, turnover, database, conform or archival ledger. Music and final sound are another distinct layer. Composer Tom Holkenborg describes a first-person score concept and recurring motifs rather than simply repeating Fury Road's musical architecture; Dolby's Creator Talks identifies Holkenborg as also participating in re-recording alongside Robert Mackenzie and describes an eight-week final mix with Dolby Atmos spacing and deliberate handoffs between score and sound design. That does not establish the complete production-sound, ADR, Foley, sound-effects editorial, premix, stem, printmaster or delivery ledger. Costume remains physically integrated with stunt work. Jenny Beavan describes a material language built around surviving leather, rough canvas and linen, reuse of existing costume elements from Fury Road, and wardrobe decisions that accommodate stunt safety. That supports continuity and practical performance constraints without establishing a complete costume inventory, fabrication census or department schedule. Furiosa is historically useful because it makes industrial hybridity visible: real vehicles, stunt performers, built environments, large-format digital photography, compact camera arrays, previs, roto, full-CG doubles, digital landscapes, on-set editorial, score and Atmos mixing are coordinated parts of one system. The locked record still does not establish final audited budget/spend/jobs, the total whole-film VFX shot count, every VFX vendor and asset, complete stunt/SFX ledger, exact camera and lens inventory for all units, full editorial infrastructure, complete music/audio-post chain, costume inventory or exact lineage among BBFC runtime variants. Those remain explicit unresolved boundaries.",
  requiredChoicesSeed: {
    screenplay: ["scheduler_not_award_claim", "bbfc_multi_version_provenance", "regional_finance_projection_boundary", "twenty_year_story_scope", "final_budget_unresolved"],
    camera: ["alexa65_dna_custom_optics", "red_vraptor_komodo_arrays", "unreal_action_previs", "six_18k_hmi_daylight_array", "rotoscope_background_extension", "complete_camera_ledger_unresolved"],
    editing: ["on_set_first_assembly", "previs_postvis_editorial_loop", "kna pman_sixel_coediting".replace(" ", ""), "edit_infrastructure_unresolved"],
    sound: ["first_person_score", "recurring_motifs", "eight_week_atmos_mix", "music_sound_handoffs", "full_audio_ledger_unresolved"],
    themes: ["film_history", "2024", "furiosa", "australian_production", "practical_stunts", "digital_post", "large_format", "chapter19"]
  },
  learningGoals: [
    "Explain why the balanced scheduler selects Furiosa after Across the Spider-Verse.",
    "Explain why P1 is a source-first priority label rather than an award or quality ranking.",
    "Use BBFC's 148m02s cinema version as 148 playable minutes.",
    "Preserve BBFC's 148m11s home-entertainment version separately.",
    "Use Cannes' 2h28 record as institutional runtime corroboration without inventing master lineage.",
    "Keep the exact reason for the BBFC runtime difference unresolved.",
    "Identify George Miller as director.",
    "Treat Screen NSW's 850-plus-job figure as a pre-production expectation, not an audited outcome.",
    "Treat Screen NSW's approximately A$350 million NSW-economy figure as a projection, not final spend.",
    "Distinguish Made in NSW support, the PDV Rebate and the Producer Offset from a complete financing waterfall.",
    "Recognize the production as a major Australian/NSW industrial case without reducing it to national branding.",
    "Identify Colin Gibson's production-design role in the locked production context.",
    "Explain how the War Rig linked art direction, construction mechanics and stunt planning.",
    "Explain why reusing the Fury Road tanker/chassis does not mean simply repeating the earlier vehicle design.",
    "Explain how construction drawings and physical mechanics turn design into a stunt-capable object.",
    "Explain why the physical vehicle model was transferred into action previs.",
    "Recognize Guy Norris as the documented second-unit/stunt coordination link.",
    "Identify Simon Duggan ASC ACS as cinematographer.",
    "Explain the ALEXA 65 and DNA-lens large-format layer.",
    "Recognize custom optics without inventing a complete lens manifest.",
    "Explain Unreal Engine previs as action-planning infrastructure rather than final-image acquisition.",
    "Explain why moving the camera close to vehicles and performers changes rigging and safety requirements.",
    "Explain how remote crane-arm and Steadicam work support dynamic vehicle coverage.",
    "Explain why 360-degree action coverage can make conventional key screens impractical.",
    "Explain foreground rotoscoping and background extension as responses to photographed action constraints.",
    "Recognize RED V-RAPTOR and KOMODO as additional documented acquisition systems.",
    "Explain multi-KOMODO arrays as an action/performance capture choice rather than the sole camera package.",
    "Explain the production-specific RED Control Pro/iPad control workflow.",
    "Explain why 2.39 framing protected to 16:9 can preserve VFX reframing latitude.",
    "Explain the six-18K-HMI/three-telehandler daylight array.",
    "Explain why artificial daylight helped preserve continuity under unstable Australian weather.",
    "Keep the complete all-unit camera, lens, filter, media and data ledger unresolved.",
    "Use Adam Kuiper's grip evidence to connect vehicle mounting, camera motion and planned digital extension.",
    "Explain why practical photography and CGI should not be treated as opposing production philosophies.",
    "Scope DNEG's more-than-1,000-artist figure to DNEG's contribution rather than the whole film.",
    "Scope DNEG's 880 shots to that vendor's delivered work rather than calling it the film's total VFX count.",
    "Recognize DNEG's 24 key sequences as vendor scope, not a complete editorial sequence census.",
    "Recognize DNEG's 16 signature environments as a documented environment-build scope.",
    "Recognize more than 100 character assets and more than 50 vehicles as DNEG-scoped asset numbers.",
    "Explain the 250-shot Stowaway to Nowhere sequence as a specific DNEG case study.",
    "Explain why 78 separate shooting days created continuity and environment-replacement pressure.",
    "Explain how generated Wasteland backgrounds responded to weather and schedule realities.",
    "Explain why live-action extraction and full-CG vehicle counterparts can coexist in the same shots.",
    "Explain Bullet Farm as a physical-plus-digital environment rather than an all-CG or all-built binary.",
    "Explain Gas Town's scan/reference library as evidence-led environment construction.",
    "Use Framestore's CG takeovers to explain safety-driven digital substitution.",
    "Explain how static covered vehicle photography could be converted into moving exterior action through VFX.",
    "Keep vendor shot counts and asset counts separate from unsupported whole-film totals.",
    "Identify Eliot Knapman as a documented on-set editor working on first assembly with Miller.",
    "Identify Margaret Sixel as co-editor in the production record.",
    "Explain how on-set assembly lets photography, action design, previs and postvis feed editorial earlier.",
    "Keep edit software, storage, proxy, turnover, database and conform details unresolved without direct evidence.",
    "Identify Tom Holkenborg as composer.",
    "Explain the first-person score concept as a point-of-view strategy rather than a generic action score label.",
    "Recognize recurring motifs without inventing a complete cue-by-cue score ledger.",
    "Explain Holkenborg's documented re-recording role separately from composition.",
    "Explain Robert Mackenzie's documented participation in final re-recording.",
    "Explain the eight-week final mix as a documented post-production window, not the total sound schedule.",
    "Explain Dolby Atmos spacing and music/sound handoffs as mix architecture.",
    "Keep ADR, Foley, effects editorial, premix, stems and delivery details unresolved unless directly sourced.",
    "Explain Jenny Beavan's leather/canvas/linen material logic in relation to the post-apocalyptic world.",
    "Explain costume-element reuse from Fury Road as production continuity rather than unchanged replication.",
    "Explain why stunt safety shapes wardrobe construction and material choices.",
    "Keep complete costume inventory, fabrication census and department schedule unresolved.",
    "Keep final audited budget, actual regional spend and final employment totals unresolved.",
    "Keep the total whole-film VFX-shot count and complete vendor census unresolved.",
    "Keep the complete stunt, SFX and vehicle-loss ledger unresolved.",
    "Explain Furiosa as a coordinated practical-digital system rather than a contest between practical effects and CGI.",
    "Close the case only when versioning, regional production, physical action, cameras, lighting, VFX, editorial, music, sound and uncertainty boundaries agree."
  ],
  phases: [
    { id: "priority", label: "Lock scheduler priority", player_task: "Select Furiosa through the balanced industrial-scale lane, not an award claim." },
    { id: "runtime", label: "Version the runtime", player_task: "Keep 148m02s cinema and 148m11s home records distinct." },
    { id: "regional_context", label: "Map NSW production", player_task: "Separate regional infrastructure and incentives from marketing shorthand." },
    { id: "projection_boundary", label: "Freeze projected outcomes", player_task: "Do not convert expected jobs or economic injection into audited results." },
    { id: "finance_boundary", label: "Freeze financing unknowns", player_task: "Do not infer final budget, incentive receipts or financing waterfall." },
    { id: "war_rig_design", label: "Design the War Rig", player_task: "Translate production design into buildable, stunt-capable vehicle geometry." },
    { id: "construction", label: "Build physically", player_task: "Coordinate drawings, mechanics and defensive vehicle construction." },
    { id: "stunt_previs", label: "Previsualize action", player_task: "Pass physical design into Guy Norris's stunt/action planning." },
    { id: "unreal_previs", label: "Block complex action", player_task: "Use Unreal Engine previs to plan movement before final photography." },
    { id: "alexa65", label: "Frame large-format action", player_task: "Use ALEXA 65 and DNA optics for landscapes and close moving action." },
    { id: "custom_optics", label: "Shape optical character", player_task: "Use documented custom optics without inventing a complete lens set." },
    { id: "vehicle_camera", label: "Rig moving cameras", player_task: "Coordinate remote crane, Steadicam and vehicle movement around performers." },
    { id: "coverage_360", label: "Protect 360-degree action", player_task: "Plan coverage where conventional key screens often cannot remain in frame." },
    { id: "red_arrays", label: "Deploy compact arrays", player_task: "Use V-RAPTOR/KOMODO systems as complementary action cameras." },
    { id: "red_control", label: "Control camera arrays", player_task: "Coordinate multiple KOMODO bodies through the production-specific iPad workflow." },
    { id: "vfx_reframe", label: "Protect reframing area", player_task: "Frame 2.39 while retaining 16:9 image area for VFX flexibility." },
    { id: "daylight_array", label: "Build controllable sun", player_task: "Use six 18K HMI PARs on three telescopic handlers for daylight continuity." },
    { id: "weather", label: "Manage weather discontinuity", player_task: "Plan for clouds, rain and wind across desert action photography." },
    { id: "grip_vfx_plan", label: "Plan physical/digital split", player_task: "Decide what is mounted, photographed, stabilized and later extended." },
    { id: "dneg_scope", label: "Scope vendor evidence", player_task: "Keep DNEG artist, shot, environment and asset counts vendor-specific." },
    { id: "stowaway", label: "Assemble Stowaway", player_task: "Integrate 250 DNEG shots across material photographed over 78 days." },
    { id: "wasteland", label: "Extend the Wasteland", player_task: "Generate environment continuity where production weather cannot supply it." },
    { id: "vehicle_cg", label: "Build vehicle counterparts", player_task: "Create scan/reference-based CG vehicles that can replace or extend photographed rigs." },
    { id: "bullet_farm", label: "Extend Bullet Farm", player_task: "Combine physical set elements with digital expansion." },
    { id: "gas_town", label: "Construct Gas Town", player_task: "Use industrial scans, photography and reference libraries to build the environment." },
    { id: "framestore_takeover", label: "Use safety takeovers", player_task: "Substitute CG action where performer or vehicle safety requires it." },
    { id: "static_to_motion", label: "Recover weather-limited plates", player_task: "Turn static protected vehicle photography into convincing exterior motion when necessary." },
    { id: "editorial_set", label: "Assemble on set", player_task: "Let Knapman build first assembly alongside Miller during production." },
    { id: "editorial_loop", label: "Loop previs and postvis", player_task: "Use evolving action composites to inform structure without inventing edit infrastructure." },
    { id: "score_pov", label: "Score first-person experience", player_task: "Build musical perspective around Furiosa's point of view." },
    { id: "mix", label: "Mix for space", player_task: "Use the documented eight-week Atmos mix to balance score, effects and perspective." },
    { id: "costume", label: "Build wearable survival", player_task: "Coordinate reused materials, leather/canvas/linen logic and stunt safety." },
    { id: "ledger_boundaries", label: "Freeze unsupported ledgers", player_task: "Keep full camera, VFX, stunt, editorial, sound and costume inventories unresolved." },
    { id: "production_verification", label: "Close Furiosa audit", player_task: "Verify versions, regional production, practical action, cameras, VFX, editorial, music, mix, costume and uncertainty before promotion." }
  ]
}] as const;

export function mergeChapterNineteenFuriosaExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterNineteenFuriosaExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle, ...definition.aliases].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({ id: definition.id, status: "manual_chapter_nineteen_furiosa_verified", source: { list_id: "manual_chapter_nineteen_furiosa_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl }, film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 }, scenario_type: definition.scenarioType, production_challenge: definition.premise, required_choices_seed: definition.requiredChoicesSeed, phases: definition.phases, learning_goals_seed: definition.learningGoals, manual_enrichment_needed: [] });
    nextPosition += 1;
  }
  return merged;
}
