import type { HistoricalFilmScenario } from "./earlyCinemaExpansion.js";
import { normalizeEarlyCinemaTitle } from "./earlyCinemaExpansion.js";

export const chapterEighteenSpiderVerseExpansionDefinitions = [
  {
    id: "scenario_spider_man_into_the_spider_verse_2018",
    title: "Spider-Man: Into the Spider-Verse",
    originalTitle: "Spider-Man: Into the Spider-Verse",
    year: 2018,
    titleType: "Movie",
    runtimeMins: 117,
    directors: ["Bob Persichetti", "Peter Ramsey", "Rodney Rothman"],
    genres: ["Animation", "Action", "Adventure"],
    sourceId: "sony_imageworks_spider_verse_2018",
    sourceUrl: "https://www.imageworks.com/node/1371",
    scenarioType: "stylized_cg_2d_hybrid_comic_pipeline_frame_modulation_twos_no_motion_blur_linework_halftone_nuke_comp_atmos_2018",
    premise: "Build Spider-Man: Into the Spider-Verse as Chapter 18's deliberately non-photoreal digital-animation production case: a Sony Pictures Animation/Sony Pictures Imageworks feature in which story editorial, performance animation, rigged and hand-authored line work, frame modulation, stylized rendering, 2D effects, compositing, sound and music operate as one coordinated system without collapsing into one technique. Sony Pictures Imageworks describes a production philosophy that privileged artist intention over photoreal accuracy and required changes to both technology and workflow. Treat that as a title-specific pipeline response, not proof that computer animation before 2018 lacked stylization or that the film invented comic-book imagery. The film uses 3D CG as an underlying volumetric system while deliberately exposing drawn intervention: facial lines could be drawn by artists, converted to geometry and rigged; more predictable geometry-based lines could be assisted algorithmically; additional environmental lines could be added in compositing. Do not call the result simply 2D, simply 3D, or a single toon shader. Imageworks documents stepped animation and animation on twos as a central graphic strategy, while editor Robert Fisher Jr. describes modulation between twos and ones, including different timing for backgrounds and characters. Preserve that flexibility: 'on twos' is a designed timing choice, not a blanket claim that every element of every frame runs at twelve unique poses per second. Traditional motion blur was intentionally avoided for much of the look, so fast motion could instead use geometry smears, speed lines and multiple limbs; those graphic substitutes are authored motion-design solutions rather than evidence of missing simulation. The rendering and compositing system borrows from print language through halftoning, line hatching, bold shapes, offset-registration depth cues and deliberately simplified gradients. Animation World Network's Imageworks interviews identify the film as unusually compositing-heavy, with extensive Nuke work, more than twenty-five compositor tools plus templates, and named Hatcher and Thresher tools for hatch lines and halftone patterns. Treat those tools as production infrastructure whose parameters remained artist-controlled shot by shot, not as an automatic filter that generated the look. The FX team combined reusable hand-drawn 2D elements with 3D simulations, and multidimensional glitching could combine differently styled renders from multiple virtual-camera angles. This case must therefore keep layout, animation, line systems, lighting, rendering, FX and compositing distinct even when they contribute to the same final pixel. The scale of the labor is part of the production history: Animation World Network reports more than 170 animators, nine leads, primarily in Vancouver with some Culver City work, and a substantial reduction in typical weekly animation output under the technical complexity. Do not convert that report into a universal productivity ratio or erase departments outside character animation. Editorial begins before final animation. Fisher describes animation editing as story development through boards, layout, animation and successive versions, with editors preserving earlier cuts, working with temp music and effects, testing pacing and returning to boards when layout temporarily loses intended emotion. Version history and editorial judgment are therefore production assets, not disposable previews. SoundWorks documents an equally deliberate sound system. Supervising sound editors Geoffrey G. Rubay and Curt Schulkey and mixers Michael Semanick and Tony Lamberti balanced fantastical multiverse design against realistic environmental anchors; collider sounds were built from mechanical, electrical and electromagnetic sources; characters received distinct sonic signatures; and the final mix was completed natively in Dolby Atmos at Sony's Kim Novak Theater. Daniel Pemberton's orchestral score, recorded at Air Studios in London, and songs such as What's Up Danger were coordinated with effects and picture rather than treated as a separate decorative layer. The case must distinguish temp editorial audio, designed effects, dialogue, Foley, songs, original score, premix and final Atmos placement. The production history ends with evidence discipline: Sony's official project records establish the three directors and principal producers; an Australian government classification record independently supports the 117-minute original theatrical version and 2018 production metadata. Awards and later home-media circulation belong to reception and distribution, not proof that a production claim is true. The player should leave the case able to explain why Spider-Verse is historically important as a cross-department workflow redesign in late-2010s feature animation without turning novelty, critical success or a studio's own promotional language into unsupported claims of invention.",
    requiredChoicesSeed: {
      screenplay: ["miles_identity_arc", "multiverse_rule_clarity", "comic_voice_text", "genre_emotion_balance", "universe_distinction"],
      camera: ["virtual_camera_graphic_staging", "frame_modulation_ones_twos", "no_motion_blur_spacing", "offset_registration_depth", "linework_projection", "universe_visual_grammar"],
      editing: ["story_reel_iteration", "board_layout_animation_versions", "character_moment_pacing", "frame_modulation_continuity", "comp_editorial_versioning", "music_picture_sync"],
      sound: ["grounded_brooklyn_ambience", "multiverse_collider_design", "character_signature_sound", "temp_sound_to_animation", "native_atmos_mix", "song_score_transition"],
      themes: ["film_history", "2018", "spider_man_into_the_spider_verse", "miles_morales", "bob_persichetti", "peter_ramsey", "rodney_rothman", "phil_lord", "christopher_miller", "sony_pictures_animation", "sony_pictures_imageworks", "justin_k_thompson", "danny_dimian", "josh_beveridge", "robert_fisher_jr", "geoffrey_rubay", "curt_schulkey", "michael_semanick", "tony_lamberti", "daniel_pemberton", "cg_2d_hybrid", "frame_modulation", "animation_on_twos", "no_motion_blur", "facial_linework", "halftone", "hatching", "nuke_compositing", "hand_drawn_fx", "dolby_atmos"],
    },
    learningGoals: [
      "Explain Spider-Verse as a coordinated story, animation, rendering, compositing, sound and music system rather than a single visual-effect trick.",
      "Distinguish Sony Pictures Animation's producing role from Sony Pictures Imageworks' animation and image-production work.",
      "Identify Bob Persichetti, Peter Ramsey and Rodney Rothman as the credited directors without flattening their different department-facing work into lone authorship.",
      "Explain why the production prioritized artist intention and graphic design over default photorealism.",
      "Avoid treating the studio's novelty language as evidence that the film invented comic-inspired animation or non-photoreal rendering.",
      "Describe the underlying 3D CG world while identifying the hand-authored 2D and line-work interventions layered through the pipeline.",
      "Explain how facial lines could be drawn, converted to geometry and rigged so illustration remained animatable in three-dimensional character space.",
      "Distinguish artist-authored line placement from geometry-driven or algorithmically assisted line behavior.",
      "Explain why additional line work could also be introduced in compositing rather than belonging to one department only.",
      "Reject the simplification that the finished image is merely a toon shader applied after conventional animation.",
      "Define animation on twos as holding a pose across two frames while preserving title-specific modulation between ones and twos.",
      "Explain why characters, backgrounds and different moments can use different temporal cadences inside one shot or sequence.",
      "Distinguish frame cadence from theatrical playback rate.",
      "Explain how avoiding conventional motion blur creates a need for alternate readability techniques in fast action.",
      "Identify geometry smears, speed lines and multiple-limb drawings as designed substitutes for continuous blur rather than errors.",
      "Explain how offset-print misregistration can inspire a stylized depth-of-field cue without functioning like photographed optical focus.",
      "Describe halftoning and hatching as comic-print-derived rendering/compositing languages rather than physical texture captured by a camera.",
      "Explain why graphic shapes, bold color and simplified gradients require shot-specific art direction rather than automatic realism.",
      "Identify the unusually heavy compositing workload and the role of Nuke in carrying much of the final graphic treatment.",
      "Describe Hatcher and Thresher as production tools for hatch-line and halftone control without implying that two tools generated the whole film.",
      "Explain why more than twenty-five compositor tools and many templates still required individual artist adjustment at shot level.",
      "Distinguish BlinkScript/tool prototyping and compiled artist-facing tools from the creative decisions made with those tools.",
      "Explain how hand-drawn 2D FX elements and 3D simulations could be combined in explosions, fire and other effects.",
      "Describe the collider glitch as a compositing system that can combine differently styled renders from multiple virtual-camera angles.",
      "Map production design, layout, animation, lighting, FX, rendering and compositing as separate departments that converge on one final image.",
      "Use the reported 170-plus animator scale as evidence about this production, not as a proxy for total crew size or a universal staffing benchmark.",
      "Treat the reported output slowdown as a title-specific consequence of complexity rather than a general productivity law for stylized animation.",
      "Explain why animation editorial begins during story development rather than only after final shots exist.",
      "Trace a sequence through boards, editorial, layout, animation, lighting/compositing and revised editorial versions.",
      "Explain why preserving earlier cuts and returning to storyboards can protect intention during temporary low-fidelity production stages.",
      "Describe temp music and temp sound as editorial communication tools rather than final soundtrack evidence.",
      "Explain how realistic Brooklyn ambience can anchor a fantastical visual world without making the image physically realistic.",
      "Describe the collider sound as layered mechanical, electrical and electromagnetic design rather than a literal recording of a fictional device.",
      "Explain why character-specific sonic signatures function as narrative identification inside a crowded multiverse.",
      "Distinguish sound editing, Foley, dialogue, songs, original score, premixing and final re-recording.",
      "Identify the final mix as natively Dolby Atmos while avoiding the claim that immersive format alone creates good spatial storytelling.",
      "Explain how Daniel Pemberton's orchestral score and licensed/original songs can hand off energy within a sequence.",
      "Keep the 117-minute original theatrical version separate from alternate or later release versions.",
      "Separate production evidence from awards, critical reception, marketing language and later franchise influence.",
      "Compare Spider-Verse with Spirited Away: both reject a simple digital-replacement narrative, but one preserves a hand-drawn production core while the other rebuilds CG around illustration-like intervention.",
      "Compare Spider-Verse with Avatar: both alter production around digital image systems, but performance capture and virtual cinematography are not the same pipeline as stylized feature animation.",
      "Compare Spider-Verse with Roma: both use digital tools to resist default digital smoothness, but one does so through graphic animation timing and print-derived compositing while the other transforms large-format color capture into monochrome live-action imagery.",
      "Audit every claim by separating documented workflow, practitioner recollection, studio description, aesthetic interpretation and downstream reception.",
    ],
    phases: [
      { id: "evidence_map", label: "Map the production evidence", player_task: "Separate official studio records, practitioner interviews, trade reporting, release metadata and reception before deciding which claims can enter the production brief." },
      { id: "story_identity", label: "Center Miles in the multiverse", player_task: "Test every multiverse rule, joke and visual invention against Miles Morales's identity and emotional arc so spectacle does not erase character causality." },
      { id: "director_department_map", label: "Map collaborative direction", player_task: "Assign story, editorial, layout, animation and performance decisions to the credited three-director production without inventing a single-author workflow." },
      { id: "visual_language_tests", label: "Test a graphic language", player_task: "Build controlled look tests that compare photoreal defaults with illustration-led shape, line, color, print texture and motion choices before scaling the pipeline." },
      { id: "pipeline_breakpoints", label: "Find pipeline breakpoints", player_task: "Identify where conventional CG assumptions block the desired look, then define bounded tool or workflow changes instead of replacing the whole pipeline indiscriminately." },
      { id: "character_line_system", label: "Rig expressive line work", player_task: "Design facial and body lines that can be hand-authored, converted to geometry, rigged and corrected without detaching expression from character performance." },
      { id: "line_assistance", label: "Automate only predictable lines", player_task: "Use geometry-driven or learned assistance for repeatable line behavior while keeping artists able to override placement when emotion or design demands it." },
      { id: "frame_modulation", label: "Author cadence shot by shot", player_task: "Choose ones, twos or mixed timing for characters and backgrounds according to performance and readability rather than applying one twelve-image rule to the whole film." },
      { id: "motion_readability", label: "Replace blur with graphic motion", player_task: "Test smears, speed lines, multiple limbs and spacing so fast action stays readable after conventional motion blur is reduced or removed." },
      { id: "virtual_camera", label: "Stage graphic cinematography", player_task: "Compose virtual-camera movement and perspective around strong silhouettes, comic-panel emphasis and emotional geography instead of mimicking live-action lens behavior by default." },
      { id: "offset_depth", label: "Design print-derived focus", player_task: "Use controlled color-channel misregistration and graphic separation as depth cues while keeping them distinct from photographed optical depth of field." },
      { id: "production_design_grammar", label: "Differentiate universes", player_task: "Define recurring shape, palette, line, texture and motion rules for each Spider-Person's world, then document how those rules coexist in shared shots." },
      { id: "story_reel", label: "Cut before final animation", player_task: "Build and revise story reels from boards, dialogue, temp music and temp effects so pacing and character emphasis are tested before expensive final animation." },
      { id: "version_archive", label: "Preserve editorial history", player_task: "Keep accessible prior cuts and sequence states so the team can recover lost intention when layout or animation changes the emotional reading." },
      { id: "layout_handoff", label: "Protect intent through layout", player_task: "Compare layout against the approved boards and cut, preserving camera logic and performance pauses rather than tightening merely because temporary images feel incomplete." },
      { id: "animation_performance", label: "Animate emotion through style", player_task: "Use poses, timing, facial lines and body mechanics to keep emotional specificity legible even when the visual language deliberately breaks physical realism." },
      { id: "hand_drawn_fx", label: "Build a reusable 2D FX library", player_task: "Create hand-drawn effects elements with known cadence and compositing requirements, then combine them with 3D simulations only where each layer adds information." },
      { id: "stylized_render", label: "Render for illustration", player_task: "Tune materials, lighting and gradients toward graphic shapes and print logic while keeping render outputs flexible enough for later shot-level compositing." },
      { id: "compositor_toolset", label: "Package comp tools", player_task: "Turn tested hatching, halftone, offset, ink, smear, brush and streak operations into controllable artist-facing tools rather than a locked one-click treatment." },
      { id: "shot_dialing", label: "Art-direct every final pixel", player_task: "Adjust halftones, hatch density, edge treatment, depth cues and glows shot by shot so tools serve sequence design rather than replace artistic judgment." },
      { id: "collider_glitch", label: "Construct multiverse fracture", player_task: "Render selected virtual-camera variants with distinct looks and combine them through a controlled screen-space pattern so glitching remains readable as story information." },
      { id: "capacity_plan", label: "Budget artistic complexity", player_task: "Use actual animator throughput and revision data to forecast staffing and schedule pressure, while tracking bottlenecks across departments instead of assuming animation alone sets capacity." },
      { id: "sound_predesign", label: "Feed sound back into picture", player_task: "Develop key web, collider and character sounds early enough for editorial and animation to react, while labeling temp and exploratory material separately from finals." },
      { id: "grounded_ambience", label: "Anchor Brooklyn sonically", player_task: "Build recognizable environmental beds and concrete source details that can stabilize fantastical imagery without pretending the animated world is documentary reality." },
      { id: "character_sound", label: "Give characters sonic signatures", player_task: "Define distinct material, mechanical and tonal identities for Spider-People and villains so sound helps audiences parse rapid visual changes." },
      { id: "music_handoffs", label: "Coordinate songs and score", player_task: "Plan transitions among songs, Daniel Pemberton's score, dialogue and effects so each sequence can shift energy without masking story beats." },
      { id: "atmos_mix", label: "Place the multiverse in Atmos", player_task: "Use native Atmos placement for depth, movement and contrast, then verify that dialogue, music and effects remain intelligible in supported downstream formats." },
      { id: "release_version", label: "Lock the original version", player_task: "Record the 117-minute original theatrical version separately from later alternate cuts, home-media masters, awards and franchise sequels." },
      { id: "method_audit", label: "Audit novelty claims", player_task: "Review every claim of first, invention, automation or influence against the source hierarchy and downgrade anything supported only by marketing or retrospective enthusiasm." },
    ],
  },
] as const;

export function mergeChapterEighteenSpiderVerseExpansion(baseScenarios: readonly HistoricalFilmScenario[]): readonly HistoricalFilmScenario[] {
  const merged = [...baseScenarios];
  let nextPosition = Math.max(0, ...baseScenarios.map((scenario) => scenario.source.position)) + 1;
  for (const definition of chapterEighteenSpiderVerseExpansionDefinitions) {
    const acceptedTitles = [definition.title, definition.originalTitle].map(normalizeEarlyCinemaTitle);
    const exists = merged.some((scenario) => scenario.id === definition.id || (scenario.film.year === definition.year && [scenario.film.title, scenario.film.original_title].map(normalizeEarlyCinemaTitle).some((title) => acceptedTitles.includes(title))));
    if (exists) continue;
    merged.push({
      id: definition.id,
      status: "manual_chapter_eighteen_spider_verse_verified",
      source: { list_id: "manual_chapter_eighteen_spider_verse_expansion_2026", position: nextPosition, imdb_id: definition.sourceId, url: definition.sourceUrl },
      film: { title: definition.title, original_title: definition.originalTitle, year: definition.year, title_type: definition.titleType, runtime_mins: definition.runtimeMins, directors: definition.directors, genres: definition.genres, genre_keys: definition.genres.map((genre) => genre.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "")), imdb_rating: 0, user_rating: 0 },
      scenario_type: definition.scenarioType,
      production_challenge: definition.premise,
      required_choices_seed: definition.requiredChoicesSeed,
      phases: definition.phases,
      learning_goals_seed: definition.learningGoals,
      manual_enrichment_needed: [],
    });
    nextPosition += 1;
  }
  return merged;
}
