import assert from "node:assert/strict";
import test from "node:test";

import { chapterEighteen1917ExpansionDefinitions } from "./chapterEighteen1917Expansion.js";

test("Chapter 18 materializes 1917 as a source-first continuous-take-illusion production case", () => {
  assert.equal(chapterEighteen1917ExpansionDefinitions.length, 1);
  const film = chapterEighteen1917ExpansionDefinitions[0];
  assert.equal(film.id, "scenario_1917_2019");
  assert.equal(film.year, 2019);
  assert.equal(film.runtimeMins, 119);
  assert.deepEqual(film.directors, ["Sam Mendes"]);
  assert.ok(film.scenarioType.includes("continuous_take_illusion") && film.scenarioType.includes("real_time") && film.scenarioType.includes("alexa_mini_lf"));
  assert.ok(film.scenarioType.includes("trinity") && film.scenarioType.includes("wireless_sound") && film.scenarioType.includes("hidden_stitches"));
  assert.ok(film.premise.includes("119 minutes") && film.premise.includes("Krysty Wilson-Cairns") && film.premise.includes("Roger Deakins"));
  assert.ok(film.premise.includes("not one literal take") && film.premise.includes("Schofield's blackout"));
  assert.ok(film.premise.includes("four months of rehearsal") && film.premise.includes("Dennis Gassner"));
  assert.ok(film.premise.includes("ALEXA Mini LF") && film.premise.includes("ARRI Signature Primes") && film.premise.includes("TRINITY"));
  assert.ok(film.premise.includes("99 percent") && film.premise.includes("40 mm") && film.premise.includes("47 mm") && film.premise.includes("35 mm"));
  assert.ok(film.premise.includes("Stuart Wilson") && film.premise.includes("hundreds of meters of fiber") && film.premise.includes("lavaliers"));
  assert.ok(film.premise.includes("Lee Smith") && film.premise.includes("reshoots") && film.premise.includes("Oliver Tarney"));
  assert.ok(film.premise.includes("Guillaume Rocheron") && film.premise.includes("stitching") && film.premise.includes("set extensions"));
  assert.ok(film.premise.includes("exact total budget") && film.premise.includes("complete stitch count") && film.premise.includes("final mix automation"));
  assert.ok(film.requiredChoicesSeed.screenplay.includes("blackout_time_break"));
  assert.ok(film.requiredChoicesSeed.camera.includes("alexa_mini_lf") && film.requiredChoicesSeed.camera.includes("40mm_primary"));
  assert.ok(film.requiredChoicesSeed.camera.includes("47mm_river") && film.requiredChoicesSeed.camera.includes("35mm_basement"));
  assert.ok(film.requiredChoicesSeed.editing.includes("seams_designed_in_prep") && film.requiredChoicesSeed.editing.includes("reshoot_over_patch"));
  assert.ok(film.requiredChoicesSeed.sound.includes("fiber_network") && film.requiredChoicesSeed.sound.includes("costume_lavs"));
  assert.ok(film.learningGoals.some((goal) => goal.includes("119-minute") && goal.includes("canonical runtime")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("continuous-shot illusion") && goal.includes("literal unbroken take")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Schofield's blackout") && goal.includes("temporal discontinuity")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("four months of rehearsal") && goal.includes("before sets were finalized")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("set could not simply be shortened") && goal.includes("actor pace")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("ALEXA Mini LF") && goal.includes("prototype large-format camera")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("99 percent") && goal.includes("40 mm Signature Prime")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("47 mm river") && goal.includes("35 mm German-basement")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("TRINITY") && goal.includes("stabilization system")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("camera handoffs") && goal.includes("operator") && goal.includes("focus")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("universal ISO") && goal.includes("white-balance")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Stuart Wilson") && goal.includes("360-degree moving camera")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("trench fiber network") && goal.includes("radio/sound coverage")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("hidden antenna housings") && goal.includes("costume-integrated lavaliers")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Lee Smith") && goal.includes("editing began during prep")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("exact number and location of hidden cuts") && goal.includes("unresolved")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("VFX stitching") && goal.includes("continuous camera space and time")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Guillaume Rocheron") && goal.includes("production design") && goal.includes("camera planning")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Oliver Tarney") && goal.includes("sound density")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("prosthetics") && goal.includes("microphone compatibility")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("Chapter 18 significance") && goal.includes("digital large-format capture")));
  assert.ok(film.learningGoals.some((goal) => goal.includes("uncertainty register") && goal.includes("stitch count") && goal.includes("RF topology")));
  assert.ok(film.phases.find((phase) => phase.id === "released_version")?.player_task.includes("119-minute"));
  assert.ok(film.phases.find((phase) => phase.id === "rehearsal_calendar")?.player_task.includes("cross-department"));
  assert.ok(film.phases.find((phase) => phase.id === "set_length")?.player_task.includes("trench") && film.phases.find((phase) => phase.id === "set_length")?.player_task.includes("duration"));
  assert.ok(film.phases.find((phase) => phase.id === "lens_strategy")?.player_task.includes("47 mm river") && film.phases.find((phase) => phase.id === "lens_strategy")?.player_task.includes("35 mm basement"));
  assert.ok(film.phases.find((phase) => phase.id === "sound_network")?.player_task.includes("fiber") && film.phases.find((phase) => phase.id === "sound_network")?.player_task.includes("radio coverage"));
  assert.ok(film.phases.find((phase) => phase.id === "seam_design")?.player_task.includes("exact final stitch inventory unresolved"));
  assert.ok(film.phases.find((phase) => phase.id === "unknowns_register")?.player_task.includes("stitch count") && film.phases.find((phase) => phase.id === "unknowns_register")?.player_task.includes("final mix settings"));
  assert.ok(film.learningGoals.length >= 50);
  assert.ok(film.phases.length >= 30);
});
