import { DIRECTOR_TERMS, type DirectorTerm } from "./directorKnowledge.js";

const extensions: readonly DirectorTerm[] = [
  { id: "camera_test", term: "Camera test", norwegian: "Kameratest", category: "production_post", phase: "preproduction", level: "foundation", definition: "En planlagt prøve av kamera, objektiv, lys, eksponering, kostyme, sminke eller arbeidsflyt før hovedopptak.", directorUse: "Regissøren bruker testen til å gjøre estetiske valg konkrete og oppdage tekniske problemer før de blir kostbare.", example: "To linsesett testes på hud, praktiske lyskilder og høylys før filmens optikk velges.", sourceIds: ["arri-image", "screenskills-director"] },
  { id: "dramatic_purpose", term: "Dramatic purpose", norwegian: "Dramatisk funksjon", category: "shot_composition", phase: "preproduction", level: "foundation", definition: "Den konkrete fortellende eller emosjonelle oppgaven et bilde, en lyd eller en bevegelse skal utføre.", directorUse: "Begrepet hindrer at shotlisten blir en liste over pene utsnitt uten begrunnelse i scenens utvikling.", example: "Nærbildets funksjon er å vise at karakteren forstår løgnen før hun svarer.", sourceIds: ["dga-blocking", "academy-craft"] },
  { id: "line_reading", term: "Line reading", norwegian: "Replikkinstruksjon", category: "performance_casting", phase: "production", level: "intermediate", definition: "Regissøren demonstrerer nøyaktig hvordan en replikk kan sies, med bestemt rytme eller betoning.", directorUse: "Kan være nyttig i spesielle tilfeller, men bør brukes bevisst fordi den lett erstatter skuespillerens egen handling med imitasjon.", example: "Regissøren viser bare den tekniske timingen som må treffe en dørsmell.", sourceIds: ["dga-actors"] },
  { id: "shot_reverse_shot", term: "Shot/reverse shot", norwegian: "Bilde–motbilde", category: "shot_composition", phase: "production", level: "foundation", definition: "Et klippemønster som veksler mellom motstående bilder, ofte i dialog eller konflikt.", directorUse: "Regissøren bestemmer størrelse, vinkel, eyeline og når mønsteret skal brytes for å uttrykke relasjonen.", example: "Motbildet blir gradvis tettere mens presset øker.", sourceIds: ["dga-blocking", "academy-craft"] },
  { id: "pan", term: "Pan", norwegian: "Panorering", category: "camera_lens", phase: "production", level: "foundation", definition: "Kameraet roterer horisontalt fra en fast fysisk posisjon.", directorUse: "Kan følge handling, avsløre informasjon eller flytte oppmerksomhet uten å endre kameraets plass i rommet.", example: "En langsom panorering avslører personen som har lyttet utenfor bildet.", sourceIds: ["academy-craft"] },
  { id: "tilt", term: "Tilt", norwegian: "Vertikal panorering", category: "camera_lens", phase: "production", level: "foundation", definition: "Kameraet roterer vertikalt opp eller ned fra en fast posisjon.", directorUse: "Brukes til å følge høydebevegelse, avdekke skala eller endre hierarki i bildet.", example: "Kameraet tilter fra skoene til ansiktet når karakteren presenteres.", sourceIds: ["academy-craft"] },
  { id: "dolly", term: "Dolly move", norwegian: "Kamerakjøring", category: "camera_lens", phase: "production", level: "foundation", definition: "Kameraet flyttes fysisk gjennom rommet på dolly, skinner eller annet stabilt system.", directorUse: "Endrer perspektiv og romforhold, i motsetning til en ren zoom som bare endrer brennvidde.", example: "En langsom dolly inn gjør bakgrunnen gradvis mindre viktig mens valget nærmer seg.", sourceIds: ["academy-craft", "arri-lens"] },
  { id: "truck", term: "Truck / lateral move", norwegian: "Sideveis kamerakjøring", category: "camera_lens", phase: "production", level: "foundation", definition: "Kameraet flyttes sideveis parallelt med motivet eller rommet.", directorUse: "Kan følge en gående karakter, avdekke rom eller skape grafisk bevegelse gjennom lag i bildet.", example: "Kameraet trucker langs butikkvinduene mens samtalen fortsetter.", sourceIds: ["academy-craft"] },
  { id: "crane_shot", term: "Crane shot", norwegian: "Kranbilde", category: "camera_lens", phase: "production", level: "intermediate", definition: "Kameraet beveges vertikalt og ofte horisontalt med kran eller jib.", directorUse: "Brukes når høyde, skala, overgang eller kompleks rombevegelse har en tydelig dramatisk funksjon.", example: "Bildet løfter seg fra avskjeden til hele den tomme plassen.", sourceIds: ["academy-craft"] },
  { id: "handheld", term: "Handheld", norwegian: "Håndholdt kamera", category: "camera_lens", phase: "production", level: "foundation", definition: "Kameraet bæres direkte eller skuldermontert slik at operatørens kropp påvirker bevegelsen.", directorUse: "Gir responsivitet og fysisk nærhet, men graden av uro må defineres presist fremfor å brukes som generelt realistisk signal.", example: "Kameraet er rolig håndholdt før det mister stabilitet under flukten.", sourceIds: ["academy-craft"] },
  { id: "steadicam", term: "Steadicam", norwegian: "Stabilisert kroppsbåret kamera", category: "camera_lens", phase: "production", level: "intermediate", definition: "Et mekanisk stabiliseringssystem som isolerer kameraet fra mye av operatørens kroppsrystelser.", directorUse: "Lar kameraet bevege seg flytende gjennom rom, trapper og blocking uten tradisjonelle skinner.", example: "Et langt Steadicam-bilde følger karakteren gjennom tre avdelinger.", sourceIds: ["academy-craft"] },
  { id: "timecode", term: "Timecode", norwegian: "Tidskode", category: "production_post", phase: "production", level: "foundation", definition: "En standardisert tidsadresse som identifiserer hvert bilde eller lydøyeblikk i opptak og postproduksjon.", directorUse: "Synkronisert timecode gjør logging, kamera–lyd-sync, VFX-notater og klipp mer pålitelig.", example: "Kamera og lydjammes til samme timecode før opptak.", sourceIds: ["arri-image"] },
  { id: "offline_edit", term: "Offline edit", norwegian: "Offline-klipp", category: "editing_time", phase: "postproduction", level: "intermediate", definition: "Kreativt klippearbeid som ofte gjøres med proxy- eller arbeidsmedier før fullkvalitets conform.", directorUse: "Regissøren utvikler struktur og rytme uten at systemet må håndtere alle originaldata i full kvalitet.", example: "Filmen klippes med ProRes-proxyer før conform til kamerafiler.", sourceIds: ["avid-glossary", "arri-image"] },
  { id: "online_edit", term: "Online edit", norwegian: "Online og finishing", category: "editing_time", phase: "postproduction", level: "intermediate", definition: "Teknisk ferdigstilling av låst klipp med originalmedier, grafikk, effekter og korrekt format.", directorUse: "Regissøren kontrollerer at alle kreative valg fra offline er gjenskapt korrekt i final kvalitet.", example: "Reframing, hastigheter og titler sammenlignes mot den låste referansen.", sourceIds: ["avid-glossary", "arri-image"] },
  { id: "m_and_e", term: "M&E", norwegian: "Musikk- og effektspor", category: "sound_music", phase: "postproduction", level: "advanced", definition: "En versjon av miksen med musikk og effekter, men uten original dialog, laget for internasjonal dubbing.", directorUse: "Krever at alle viktige ikke-dialoglyder finnes separat slik at scenen fungerer når dialogsporet erstattes.", example: "Pust, rop og bevegelser må eventuelt fylles med Foley i M&E-versjonen.", sourceIds: ["academy-craft", "dga-process"] },
  { id: "color_space", term: "Color space", norwegian: "Fargerom", category: "lighting_color", phase: "postproduction", level: "advanced", definition: "En definert modell for hvordan fargeverdier representeres, med bestemte primærfarger, hvitpunkt og overføringsfunksjon.", directorUse: "Riktig fargerom og transformasjon er nødvendig for at det samme kreative uttrykket skal gjengis konsistent på ulike skjermer og mastere.", example: "Arbeidsmaterialet håndteres i ACES før separate output transforms til kino og HDR.", sourceIds: ["aces-glossary"] },
];

const mutableTerms = DIRECTOR_TERMS as DirectorTerm[];
for (const term of extensions) {
  if (!mutableTerms.some((candidate) => candidate.id === term.id)) mutableTerms.push(term);
}

export const DIRECTOR_KNOWLEDGE_EXTENSIONS = extensions;
