export type DirectorKnowledgePhase = "development" | "preproduction" | "production" | "postproduction";
export type DirectorKnowledgeLevel = "foundation" | "intermediate" | "advanced";

export const DIRECTOR_KNOWLEDGE_CATEGORIES = [
  { id: "directing_process", label: "Regiarbeid", description: "Hvordan regissøren utvikler, kommuniserer og beskytter filmens helhetlige idé." },
  { id: "script_dramaturgy", label: "Manus og dramaturgi", description: "Begreper for sceneanalyse, konflikt, informasjon og dramatisk utvikling." },
  { id: "performance_casting", label: "Casting og skuespillerarbeid", description: "Arbeid med rollevalg, prøver, handlinger, undertekst og kontinuitet i prestasjonen." },
  { id: "blocking_staging", label: "Blocking og iscenesettelse", description: "Hvordan kropper, blikk, bevegelser og rom organiseres foran kamera." },
  { id: "shot_composition", label: "Bildeutsnitt og komposisjon", description: "Bildegrammatikk, utsnitt, perspektiv og visuell prioritering." },
  { id: "camera_lens", label: "Kamera og optikk", description: "Kameraets plassering, objektiver, fokus og romgjengivelse." },
  { id: "exposure_motion", label: "Eksponering og bevegelse", description: "Lysmengde, bildefrekvens, lukkertid og gjengivelse av bevegelse." },
  { id: "lighting_color", label: "Lys og farge", description: "Lyskvalitet, retning, kontrast, fargetemperatur og fargestyring." },
  { id: "design_continuity", label: "Scenografi og kontinuitet", description: "Miljø, rekvisitter, kostyme, romlogikk og sammenheng mellom opptak." },
  { id: "editing_time", label: "Klipp og filmisk tid", description: "Sammenstilling, rytme, kontinuitet, ellipser og bilde-lyd-overganger." },
  { id: "sound_music", label: "Lyd og musikk", description: "Dialog, atmosfære, effekter, musikk, perspektiv og miks." },
  { id: "production_post", label: "Opptak og postproduksjon", description: "Settarbeid, opptakslogistikk, metadata, VFX, grading og levering." },
] as const;

export type DirectorKnowledgeCategoryId = (typeof DIRECTOR_KNOWLEDGE_CATEGORIES)[number]["id"];

export type DirectorKnowledgeSource = {
  readonly id: string;
  readonly label: string;
  readonly organization: string;
  readonly url: string;
  readonly scope: string;
};

export const DIRECTOR_KNOWLEDGE_SOURCES: readonly DirectorKnowledgeSource[] = [
  { id: "dga-process", label: "Directors’ Minimum Conditions: Preparation, Production and Post-Production", organization: "Directors Guild of America", url: "https://www.dga.org/contracts/creative-rights/basic-agreement-article-7", scope: "Regissørens ansvar gjennom forberedelse, opptak, klipp, lyd og director’s cut." },
  { id: "dga-blocking", label: "The Director’s Prep: Blocking & Shot Listing", organization: "Directors Guild of America", url: "https://www.dga.org/Events/2019/Dec2019/DDI_Lab_LA_Prep_1019", scope: "Blocking, floor plan, shotlisting og kommunikasjon av scenen." },
  { id: "dga-actors", label: "Working with Actors", organization: "Directors Guild of America", url: "https://www.dga.org/Events/2026/June2026/DDI_WorkingWithActors-0426", scope: "Casting, prøver, tilpasning til skuespillerens metode og regi av prestasjon." },
  { id: "screenskills-director", label: "Director: Film and TV Drama", organization: "ScreenSkills", url: "https://www.screenskills.com/job-profiles/roles/director-film-and-tv-drama/", scope: "Regissørens kreative ledelse og samarbeid med produsent, fotograf, skuespillere og klipper." },
  { id: "kodak-glossary", label: "Glossary of Motion Picture Terms", organization: "Kodak", url: "https://www.kodak.com/en/motion/page/glossary-of-motion-picture-terms/", scope: "Filmformat, optikk, eksponering, farge, laboratorie- og visningsterminologi." },
  { id: "arri-lens", label: "ALEXA LF FAQ: focal length, sensor size and angle of view", organization: "ARRI", url: "https://www.arri.com/en/learn-help/learn-help-camera-system/frequently-asked-questions/alexa-lf-faq", scope: "Objektivets brennvidde, sensorformat og bildevinkel." },
  { id: "arri-image", label: "ARRI Camera Image Science and Metadata", organization: "ARRI", url: "https://www.arri.com/en/learn-help/arri-camera-technology/best-overall-image-quality", scope: "Dynamisk omfang, highlight roll-off, eksponeringsrom, Log og metadata." },
  { id: "avid-glossary", label: "MediaCentral Glossary", organization: "Avid", url: "https://resources.avid.com/SupportFiles/attach/Interplay_Central/IPC_Help/InterplayCentral_Help/IPC_Glossary.html", scope: "Klipp, logging, sekvenser, L-cuts og redaksjonell arbeidsflyt." },
  { id: "academy-craft", label: "Academy Academy: filmmaking crafts", organization: "Academy of Motion Picture Arts and Sciences", url: "https://www.oscars.org/videos-photos/academy-academy", scope: "Kinematografi, scenografi, kostyme, lyd, musikk, VFX og andre filmfag." },
  { id: "aces-glossary", label: "ACES Glossary and System Documentation", organization: "Academy Color Encoding System", url: "https://docs.acescentral.com/glossary/", scope: "Fargestyring, input-, look- og output-transformer, LUT-er og digital masterflyt." },
] as const;

export type DirectorWorkflowStep = {
  readonly id: string;
  readonly order: number;
  readonly phase: DirectorKnowledgePhase;
  readonly title: string;
  readonly goal: string;
  readonly actions: readonly string[];
  readonly outputs: readonly string[];
  readonly collaborators: readonly string[];
  readonly termIds: readonly string[];
  readonly sourceIds: readonly string[];
};

export const DIRECTOR_WORKFLOW: readonly DirectorWorkflowStep[] = [
  { id: "script-interpretation", order: 1, phase: "development", title: "Tolke manus og definere ståsted", goal: "Finne hva filmen handler om dramatisk, emosjonelt og formelt før løsninger velges.", actions: ["Bryt manuset ned i beats, mål, hindringer og vendepunkter.", "Definer publikums kunnskap og filmens synsvinkel.", "Skill tema fra konkret spillbar handling."], outputs: ["Reginotat", "Sceneanalyse", "Spørsmål til manus"], collaborators: ["Manusforfatter", "Produsent"], termIds: ["beat", "scene_objective", "obstacle", "turning_point", "point_of_view", "directors_statement"], sourceIds: ["dga-process", "screenskills-director"] },
  { id: "creative-system", order: 2, phase: "development", title: "Bygge filmens formelle system", goal: "Oversette tolkningen til regler for bilde, lyd, skuespill, rom og tid.", actions: ["Definer tone og visuell grammatikk.", "Lag prinsipper for når kamera beveger seg og når det står stille.", "Bestem hvilke kontraster som skal utvikle seg gjennom filmen."], outputs: ["Visuelt konsept", "Tone- og referansepakke", "Formelle regler"], collaborators: ["Fotograf", "Produksjonsdesigner", "Klipper", "Lyddesigner"], termIds: ["creative_vision", "tone", "visual_language", "formal_rule", "palette", "sound_perspective"], sourceIds: ["screenskills-director", "academy-craft"] },
  { id: "casting-performance", order: 3, phase: "preproduction", title: "Casting og prestasjonsstrategi", goal: "Finne skuespillere og arbeidsmåter som kan bære scenenes handling og undertekst.", actions: ["Definer hva rollen gjør, ikke bare hva den føler.", "Gjennomfør auditions, callbacks og chemistry reads.", "Planlegg hvordan ulike skuespillere mottar justeringer."], outputs: ["Castingvalg", "Rollehandlinger", "Prøveplan"], collaborators: ["Castingansvarlig", "Skuespillere", "Produsent"], termIds: ["casting", "callback", "chemistry_read", "playable_action", "adjustment", "subtext"], sourceIds: ["dga-actors", "screenskills-director"] },
  { id: "department-alignment", order: 4, phase: "preproduction", title: "Samordne avdelingene", goal: "Sørge for at alle fagavdelinger løser samme dramatiske idé uten å arbeide i parallelle siloer.", actions: ["Gjennomfør fagmøter og manusgjennomgang.", "Knytt design-, kamera-, lys- og lydvalg til scenens funksjon.", "Avklar kostnad, tid og teknisk risiko tidlig."], outputs: ["Avdelingsbrief", "Lookbook", "Tekniske tester", "Prioritetsliste"], collaborators: ["Fotograf", "Produksjonsdesigner", "Kostymedesigner", "Lyd", "VFX", "1. AD"], termIds: ["head_of_department", "lookbook", "camera_test", "wardrobe_test", "tech_scout", "production_constraint"], sourceIds: ["screenskills-director", "academy-craft"] },
  { id: "location-tech-scout", order: 5, phase: "preproduction", title: "Location og teknisk befaring", goal: "Forstå hvordan rom, lys, lyd, logistikk og sikkerhet påvirker scenens muligheter.", actions: ["Gå scenen fysisk i rommet.", "Sjekk solretning, støy, strøm, rigg, adkomst og kameraposisjoner.", "Oppdater blocking og shotplan etter virkelige forhold."], outputs: ["Floor plan", "Kameraposisjoner", "Lys- og lydplan", "Risikoliste"], collaborators: ["1. AD", "Fotograf", "Gaffer", "Grip", "Location", "Lyd"], termIds: ["location_scout", "tech_scout", "floor_plan", "practical_light", "wild_track", "screen_geography"], sourceIds: ["dga-blocking", "dga-process"] },
  { id: "blocking-rehearsal", order: 6, phase: "preproduction", title: "Blocking og prøve", goal: "Finne spillbare bevegelser og maktforhold før kameraet låser scenen.", actions: ["La skuespillerne undersøke handling og rom.", "Plasser innganger, utganger, blikk og kryssinger.", "Juster kamera etter prestasjonen, ikke omvendt som automatikk."], outputs: ["Blockingplan", "Reviderte marks", "Prestasjonstoner", "Kamerabehov"], collaborators: ["Skuespillere", "Fotograf", "Script supervisor", "1. AD"], termIds: ["blocking", "staging", "mark", "eyeline", "cross", "motivated_movement"], sourceIds: ["dga-blocking", "dga-actors"] },
  { id: "shot-design", order: 7, phase: "preproduction", title: "Shot design og dekning", goal: "Velge de bildene som faktisk uttrykker scenens informasjon, relasjoner og forandring.", actions: ["Bestem master, singles, inserts og reaksjoner ut fra scenens behov.", "Test akselinje, skjermretning og øyelinjer.", "Gi hvert bilde en dramatisk funksjon."], outputs: ["Shotlist", "Storyboard ved behov", "Linseliste", "Dekningsstrategi"], collaborators: ["Fotograf", "Storyboard artist", "Script supervisor", "1. AD"], termIds: ["coverage", "shot_list", "master_shot", "axis_of_action", "shot_size", "dramatic_purpose"], sourceIds: ["dga-blocking", "kodak-glossary", "arri-lens"] },
  { id: "schedule-priorities", order: 8, phase: "preproduction", title: "Planlegge tid og prioriteringer", goal: "Beskytte de viktigste kreative valgene når opptaksdagen møter begrensninger.", actions: ["Marker ufravikelige bilder og prestasjonsbehov.", "Planlegg alternative dekninger.", "Avtal rekkefølge med 1. AD og fotograf."], outputs: ["Prioritert shotlist", "Plan B", "Tidsestimater", "Pickup-liste"], collaborators: ["Produsent", "1. AD", "Fotograf", "Produksjonsleder"], termIds: ["shooting_schedule", "company_move", "setup", "pickup", "safety_take", "coverage"], sourceIds: ["dga-process", "screenskills-director"] },
  { id: "shooting-floor", order: 9, phase: "production", title: "Lede opptaket", goal: "Samle prestasjon, bilde, lyd og produksjon til ett tydelig resultat under tidspress.", actions: ["Kommuniser hva tagningen skal forbedre.", "Gi presise justeringer til skuespiller og avdeling.", "Vurder kontinuitet, teknisk kvalitet og om scenens vendepunkt er synlig."], outputs: ["Godkjente takes", "Reginotater", "Pickup-behov", "Metadata og logg"], collaborators: ["Skuespillere", "Fotograf", "1. AD", "Script supervisor", "Lyd", "Alle avdelingsledere"], termIds: ["take", "print_take", "adjustment", "continuity", "video_assist", "slate"], sourceIds: ["dga-process", "dga-actors"] },
  { id: "dailies-adaptation", order: 10, phase: "production", title: "Se dailies og tilpasse planen", goal: "Kontrollere at materialet fungerer samlet og oppdage problemer før opptaket har gått videre.", actions: ["Vurder prestasjon, fokus, eksponering, dekning og lyd.", "Sammenlign materialet med scenens hensikt.", "Oppdater kommende shotlister og pickups."], outputs: ["Dailies-notater", "Korrigerte planer", "Pickup- og VFX-notater"], collaborators: ["Fotograf", "Klipper", "Script supervisor", "Produsent"], termIds: ["dailies", "rushes", "circle_take", "focus_pull", "exposure", "pickup"], sourceIds: ["dga-process", "arri-image"] },
  { id: "picture-edit", order: 11, phase: "postproduction", title: "Bygge filmens bildeklipp", goal: "Finne den sterkeste rytmen, synsvinkelen og informasjonsflyten i det innspilte materialet.", actions: ["Start med assembly og vurder scenens faktiske materiale.", "Arbeid fra dramatisk funksjon fremfor å bevare planlagt dekning.", "Lås bilde først når struktur og rytme er kontrollert."], outputs: ["Assembly", "Rough cut", "Fine cut", "Picture lock"], collaborators: ["Klipper", "Produsent", "VFX editor"], termIds: ["assembly", "rough_cut", "fine_cut", "picture_lock", "reaction_shot", "ellipsis"], sourceIds: ["dga-process", "avid-glossary"] },
  { id: "finish", order: 12, phase: "postproduction", title: "Lyd, musikk, VFX, farge og levering", goal: "Ferdigstille filmens sanselige helhet og sikre at intensjonen overlever teknisk distribusjon.", actions: ["Spot lyd, musikk og VFX med fagavdelingene.", "Godkjenn ADR, Foley, design, miks og grading.", "Kontroller mastere i relevante visningsformater."], outputs: ["Låst lydmiks", "Ferdige VFX", "Color grade", "DCP og øvrige leveranser"], collaborators: ["Lyddesigner", "Komponist", "VFX supervisor", "Colorist", "Post supervisor"], termIds: ["spotting_session", "adr", "foley", "final_mix", "color_grade", "dcp"], sourceIds: ["dga-process", "academy-craft", "aces-glossary"] },
] as const;

export type DirectorTerm = {
  readonly id: string;
  readonly term: string;
  readonly norwegian: string;
  readonly category: DirectorKnowledgeCategoryId;
  readonly phase: DirectorKnowledgePhase;
  readonly level: DirectorKnowledgeLevel;
  readonly definition: string;
  readonly directorUse: string;
  readonly example: string;
  readonly sourceIds: readonly string[];
};

const CATEGORY_SOURCES: Record<DirectorKnowledgeCategoryId, readonly string[]> = {
  directing_process: ["dga-process", "screenskills-director"],
  script_dramaturgy: ["dga-process", "screenskills-director"],
  performance_casting: ["dga-actors", "screenskills-director"],
  blocking_staging: ["dga-blocking", "dga-actors"],
  shot_composition: ["dga-blocking", "academy-craft"],
  camera_lens: ["kodak-glossary", "arri-lens"],
  exposure_motion: ["kodak-glossary", "arri-image"],
  lighting_color: ["kodak-glossary", "arri-image", "aces-glossary"],
  design_continuity: ["academy-craft", "dga-process"],
  editing_time: ["avid-glossary", "dga-process"],
  sound_music: ["academy-craft", "dga-process"],
  production_post: ["dga-process", "arri-image", "aces-glossary"],
};

const TERM_ROWS = `
creative_vision|Creative vision|Kreativ helhetsvisjon|directing_process|development|foundation|Den samlende ideen for hvordan filmens historie, tone, bilde, lyd og prestasjoner skal virke sammen.|Brukes til å prioritere mellom gode enkeltideer og den løsningen som tjener hele filmen.|En intim film kan kreve at kameraet blir nær først når karakteren mister kontroll.
directors_statement|Director's statement|Reginotat|directing_process|development|foundation|En kort formulering av regissørens tolkning, hensikt og formelle strategi.|Tvinger regissøren til å uttrykke hva filmen skal gjøre med publikum og hvordan.|Historien fortelles som en gradvis innsnevring av karakterens handlingsrom.
tone|Tone|Tone|directing_process|development|foundation|Filmens følelsesmessige og holdningsmessige grunnklang.|Styrer tempo, prestasjonsnivå, design, musikk og hvor tydelig humor eller alvor markeres.|Samme scene kan spilles som tørr komedie eller truende realisme.
point_of_view|Point of view|Synsvinkel|directing_process|development|foundation|Hvem eller hva filmen organiserer publikums kunnskap og opplevelse rundt.|Avgjør hva kamera, klipp og lyd lar publikum vite eller misforstå.|Vi hører telefonen før hovedpersonen forstår hvem som ringer.
visual_language|Visual language|Visuelt språk|directing_process|development|intermediate|Et gjentakende system av utsnitt, bevegelse, lys, farge og rombruk.|Gir filmen gjenkjennelige regler og gjør avvik meningsfulle.|Statiske totaler dominerer til karakteren endelig handler.
formal_rule|Formal rule|Formell regel|directing_process|development|intermediate|En bevisst begrensning som organiserer filmens form.|Hjelper avdelingene å ta konsistente valg under press.|Kamera krysser aldri dørterskelen før vendepunktet.
reference|Reference|Referanse|directing_process|development|foundation|Et bilde, verk, sted eller uttrykk brukt for å konkretisere en ønsket kvalitet.|Skal forklare en egenskap, ikke kopiere et helt uttrykk blindt.|Referansen brukes for kontrast og fargetemperatur, ikke kameraføring.
lookbook|Lookbook|Visuell referansepakke|directing_process|preproduction|foundation|En kuratert samling bilder og notater som kommuniserer filmens visuelle retning.|Samordner fotograf, design, kostyme, sminke og produsent.|Lookbooken viser hvordan grønt gradvis forsvinner fra miljøet.
coverage|Coverage|Dekning|directing_process|preproduction|foundation|Mengden og typen bilder som gir klipperen mulighet til å bygge en scene.|Regissøren velger dekning ut fra dramatisk behov, tid og ønsket fleksibilitet.|En master, to singles og ett avgjørende insert kan være nok.
shot_list|Shot list|Shotliste|directing_process|preproduction|foundation|En ordnet liste over planlagte kameraoppsett og deres funksjon.|Brukes til kommunikasjon, tidsplan og prioritering på sett.|Bilde 12 er et nærbilde som først tas etter vendepunktet.
storyboard|Storyboard|Bilderuteplan|directing_process|preproduction|foundation|Tegnede eller visualiserte ruter som viser planlagte bilder i rekkefølge.|Nyttig for komplekse bevegelser, VFX, action og presis rytme.|En jaktsekvens tegnes for å avklare retning og kollisjoner.
dailies|Dailies|Dagens opptak|directing_process|production|foundation|Materiale fra opptaksdagen som gjennomgås før eller under videre produksjon.|Avslører om prestasjon, fokus, dekning og tone fungerer samlet.|Dailies viser at scenens reaksjonsbilde mangler.
rushes|Rushes|Råopptak|directing_process|production|foundation|Et annet vanlig navn på nylig fremkalt eller prosessert opptaksmateriale.|Brukes på samme måte som dailies for kvalitets- og kontinuitetskontroll.|Regissøren ser rushes før neste dags nærbilder.
directors_cut|Director's cut|Regissørens klippeversjon|directing_process|postproduction|foundation|Versjonen regissøren forbereder etter fotografering før eventuell endelig godkjenning hos andre.|Samler regissørens første fullstendige bilde- og lydintensjon.|Director's cut inkluderer midlertidig musikk og lyd for å demonstrere rytmen.
beat|Beat|Dramatisk slag|script_dramaturgy|development|foundation|Den minste meningsfulle endringen i handling, taktikk, informasjon eller relasjon i en scene.|Regissøren bruker beats til å dele scenen i spillbare forandringer.|Hun smiler, forstår løgnen og endrer strategi.
scene_objective|Scene objective|Scenemål|script_dramaturgy|development|foundation|Det konkrete resultatet en karakter forsøker å oppnå i scenen.|Gir skuespilleren en aktiv retning og regissøren en målestokk for blocking.|Han vil få søsteren til å bli i rommet.
super_objective|Super-objective|Overordnet mål|script_dramaturgy|development|intermediate|Karakterens langsiktige drivkraft gjennom en større del av filmen.|Hjelper regissøren å koble små scenehandlinger til karakterbuen.|Hun prøver gjennom hele filmen å gjenopprette kontroll.
obstacle|Obstacle|Hindring|script_dramaturgy|development|foundation|Det som aktivt står mellom karakteren og målet.|Skaper motstand som prestasjon, blocking og klipp kan synliggjøre.|Den andre personen nekter å svare direkte.
conflict|Conflict|Konflikt|script_dramaturgy|development|foundation|Sammenstøtet mellom uforenlige mål, behov, verdier eller krefter.|Regissøren må vise konflikten i handling, ikke bare forklare den.|Begge vil beskytte barnet, men på motsatte måter.
stakes|Stakes|Hva som står på spill|script_dramaturgy|development|foundation|Konsekvensen av å lykkes eller mislykkes.|Bestemmer hvor mye press scenen tåler og hvordan prestasjonen kan eskalere.|Hvis avtalen faller, mister hun hjemmet.
turning_point|Turning point|Vendepunkt|script_dramaturgy|development|foundation|Øyeblikket som endrer scenens retning eller karakterenes handlingsmuligheter.|Bør få en tydelig filmisk konsekvens i bilde, lyd, spill eller rytme.|Et navn nevnes og maktbalansen snur.
reversal|Reversal|Reversering|script_dramaturgy|development|intermediate|En vending der situasjonen får motsatt verdi eller forventning brytes markant.|Regissøren kan bygge forventning og så endre publikums forståelse.|Den som så ut som offer, kontrollerte møtet.
setup_payoff|Setup and payoff|Planting og innfrielse|script_dramaturgy|development|foundation|Informasjon eller element etableres tidlig og får betydning senere.|Krever presis nok vekt til at publikum registrerer uten å få svaret for tidlig.|En ødelagt lås vises før innbruddet avsløres.
subtext|Subtext|Undertekst|script_dramaturgy|development|foundation|Det karakteren mener, ønsker eller skjuler under de uttalte ordene.|Regi bør rette skuespilleren mot handlingen bak teksten fremfor en generell følelse.|Jeg har det fint betyr ikke spør mer.
exposition|Exposition|Eksposisjon|script_dramaturgy|development|foundation|Informasjon publikum trenger om verden, fortid, relasjoner eller regler.|Regissøren fordeler informasjon gjennom konflikt, handling, bilde og lyd så den ikke stopper scenen.|Familiehistorien kommer frem mens de slåss om bordplasseringen.
dramatic_irony|Dramatic irony|Dramatisk ironi|script_dramaturgy|development|intermediate|Publikum vet noe en karakter ikke vet.|Regissøren styrer synsvinkel og timing for å skape spenning, humor eller smerte.|Vi ser nøkkelen i lommen før karakteren leter.
ellipsis_script|Narrative ellipsis|Fortellingsellipse|script_dramaturgy|development|intermediate|Et tidsrom eller handlingsledd utelates, men kan forstås gjennom sammenheng.|Brukes til å komprimere eller la publikum arbeide aktivt.|Vi går fra frieri til tomt festlokale.
sequence|Sequence|Sekvens|script_dramaturgy|development|foundation|Flere scener som sammen utgjør en større dramatisk enhet.|Regissøren planlegger progresjon på tvers av scener, ikke bare enkeltvis.|En etterforskning består av tre scener med økende risiko.
casting|Casting|Rollebesetning|performance_casting|preproduction|foundation|Prosessen med å finne og velge utøvere til rollene.|Regissøren vurderer tilstedeværelse, handlingsevne, samspill og filmens helhet, ikke bare likhet med beskrivelsen.|En uventet ro kan gjøre antagonisten mer truende.
audition|Audition|Prøvespill|performance_casting|preproduction|foundation|En strukturert prøve der en skuespiller arbeider med materiale for rollen.|Regissøren tester respons på justeringer og samarbeid, ikke bare første versjon.|Skuespilleren spiller scenen på nytt med en konkret handling.
callback|Callback|Ny prøverunde|performance_casting|preproduction|foundation|En senere audition for utvalgte kandidater.|Gir rom for dypere arbeid, nye partnere og mer presise justeringer.|To kandidater prøves med samme motspiller.
chemistry_read|Chemistry read|Samspillprøve|performance_casting|preproduction|foundation|En audition der mulige medspillere testes sammen.|Regissøren undersøker rytme, lytting, spenning og troverdig relasjon.|De to hovedrollene leser en scene med konflikt og stillhet.
table_read|Table read|Bordlesning|performance_casting|preproduction|foundation|En samlet høytlesning av manus med skuespillere og nøkkelpersoner.|Avslører rytme, uklar informasjon, rollebalanse og dialogproblemer.|Regissøren noterer hvor publikum mister oversikten.
rehearsal|Rehearsal|Prøve|performance_casting|preproduction|foundation|Forberedende arbeid med scene, handling, tekst, rom eller teknikk før opptak.|Brukes til å undersøke, ikke nødvendigvis fastlåse alle valg.|Skuespillerne prøver scenen uten kamera før blocking bestemmes.
playable_action|Playable action|Spillbar handling|performance_casting|preproduction|foundation|Et aktivt verb skuespilleren kan forsøke mot en annen person.|Gir mer presis regi enn følelsesinstruksjoner.|Overtal henne er mer spillbart enn vær trist.
intention|Intention|Hensikt|performance_casting|preproduction|foundation|Hva karakteren prøver å gjøre med den andre eller situasjonen i øyeblikket.|Regissøren bruker hensikt for å justere energi og retning uten å diktere resultatet.|Han prøver å få henne til å le for å unngå spørsmålet.
given_circumstances|Given circumstances|Gitte omstendigheter|performance_casting|preproduction|intermediate|Fakta om karakter, tid, sted, relasjon og situasjon som gjelder før scenen begynner.|Gir prestasjonen konkrete rammer og konsekvenser.|Hun har ikke sovet og må skjule at pengene er borte.
adjustment|Adjustment|Regijustering|performance_casting|production|foundation|En konkret endring regissøren ber om mellom takes.|Bør uttrykke hva som skal undersøkes, ikke bare hva som var galt.|Denne gangen: vent til han setter seg før du angriper.
listening|Listening|Aktiv lytting|performance_casting|production|foundation|Skuespillerens mottak av partnerens handling og ord før responsen oppstår.|Regissøren beskytter ekte reaksjon mot mekanisk timing.|Nærbildet holdes gjennom pausen før svaret.
continuity_performance|Performance continuity|Spillekontinuitet|performance_casting|production|intermediate|Sammenheng i energi, handling, kropp og emosjonell utvikling mellom takes og utsnitt.|Gjør klipping mulig uten at karakterens utvikling hopper utilsiktet.|Tårene kommer først etter samme replikk i alle utsnitt.
emotional_arc|Emotional arc|Emosjonell bue|performance_casting|development|foundation|Forandringen i karakterens følelsesmessige tilstand gjennom scene eller film.|Regissøren knytter buen til beats og handlinger, ikke bare intensitetsnivå.|Forsvar blir til håp og deretter skam.
mark|Mark|Gulvmerke|performance_casting|production|foundation|Et fysisk punkt skuespilleren skal treffe for fokus, lys, komposisjon eller teknikk.|Regissøren må balansere teknisk presisjon med levende blocking.|Skuespilleren stanser på merket idet vinduet åpnes.
blocking|Blocking|Blocking|blocking_staging|preproduction|foundation|Planlegging av skuespillernes plasseringer og bevegelser i rommet.|Regissøren uttrykker relasjon, makt, mål og endring gjennom romlig handling.|Hun flytter seg mellom ham og døren når hun tar kontroll.
staging|Staging|Iscenesettelse|blocking_staging|preproduction|foundation|Den samlede organiseringen av kropper, rom, kamera og handling i en scene.|Staging gjør scenens informasjon lesbar uten å være avhengig av klipp.|Tre personer plasseres i dybden slik at allianser kan skifte i ett bilde.
business|Stage business|Fysisk aktivitet|blocking_staging|preproduction|intermediate|Små konkrete handlinger med kropp eller gjenstander under scenen.|Kan gi rytme, undertekst og motstand, men må ha dramatisk funksjon.|Hun sorterer bestikk for å unngå øyekontakt.
cross|Cross|Kryssing|blocking_staging|preproduction|foundation|En skuespiller beveger seg fra én posisjon eller side av rommet til en annen.|Regissøren bruker kryssing for å endre relasjon og motivere kamera.|Han krysser bak henne og bryter den etablerte maktaksen.
entrance|Entrance|Inngang|blocking_staging|preproduction|foundation|Karakterens ankomst inn i scene eller bilde.|Timing, lyd og retning kan definere status før dialogen begynner.|Hun kommer inn før døren har sluttet å vibrere.
exit|Exit|Utgang|blocking_staging|preproduction|foundation|Karakterens forlatelse av scene eller bilde.|Kan avslutte et beat, skape tomrom eller flytte publikums fokus.|Han går, men stemmen blir igjen på telefonen.
axis_of_action|Axis of action|Handlingsakse|blocking_staging|preproduction|foundation|En tenkt linje gjennom den viktigste handlingen eller relasjonen i scenen.|Hjelper regissøren å holde skjermretning og blikk forståelige.|Aksen går mellom de to ved bordet.
rule_180|180-degree rule|180-gradersregelen|blocking_staging|preproduction|foundation|Kamera holdes vanligvis på én side av handlingsaksen for å bevare retning og romlogikk.|Regissøren kan bryte regelen bevisst når ny orientering eller uro er ønsket.|Aksen krysses først etter at et nøytralt bilde reetablerer rommet.
screen_direction|Screen direction|Skjermretning|blocking_staging|production|foundation|Retningen en person eller gjenstand beveger seg eller ser i bildet.|Kontinuitet i retning gjør geografi lesbar mellom klipp.|Hun går konsekvent mot høyre på vei til huset.
eyeline|Eyeline|Blikkretning|blocking_staging|production|foundation|Retningen og høyden en karakter ser mot, ofte knyttet til en annen person eller gjenstand.|Korrekte eller bevisst avvikende eyelines bygger rom og relasjon.|Begge ser mot samme punkt utenfor bildet.
cheat|Cheat|Jukse plassering|blocking_staging|production|intermediate|En liten justering av kropp eller gjenstand for kameraet som ikke skal oppleves som en reell romendring.|Brukes for å åpne ansikt, forbedre lys eller bevare komposisjon.|Skuespilleren vrir seg fem grader mot kamera.
motivated_movement|Motivated movement|Motivert bevegelse|blocking_staging|preproduction|foundation|Bevegelse som springer ut av karakterens handling eller situasjon, ikke bare kameraets behov.|Gir blocking og kamerabevegelse dramatisk troverdighet.|Hun går til vinduet fordi hun hører bilen.
foreground_midground_background|Foreground, midground, background|Forgrunn, mellomgrunn og bakgrunn|blocking_staging|preproduction|foundation|Tre dybdeplan som organiserer informasjon og visuell hierarki.|Regissøren kan spille flere handlinger samtidig og styre oppmerksomhet med fokus og bevegelse.|Barnet er i forgrunn mens konflikten skjer bak.
ensemble_staging|Ensemble staging|Ensemble-iscenesettelse|blocking_staging|preproduction|advanced|Staging av flere karakterer der relasjoner og fokus skifter innen samme rom eller bilde.|Krever presis geografi, timing og prioritering av publikums blikk.|Et middagsselskap utvikles uten å dele alle i singles.
shot_size|Shot size|Bildeutsnitt|shot_composition|preproduction|foundation|Hvor mye av motivet og omgivelsene bildet viser.|Regissøren bruker utsnitt til å styre informasjon, intimitet og kroppslig lesbarhet.|Et nærbilde skjuler hvem som står bak døren.
extreme_wide|Extreme wide shot|Ekstremt totalbilde|shot_composition|preproduction|foundation|Et svært vidt bilde der miljøet dominerer og personer ofte er små.|Brukes for skala, isolasjon, geografi eller overgang.|En person krysser et enormt snøfelt.
wide_shot|Wide shot|Totalbilde|shot_composition|preproduction|foundation|Et bilde som viser hele eller store deler av kroppen sammen med rommet.|Egnet for blocking, geografi og relasjoner mellom personer og miljø.|Hele kjøkkenet og begge karakterenes avstand er synlig.
full_shot|Full shot|Helbilde|shot_composition|preproduction|foundation|Et utsnitt som vanligvis viser en person fra hode til fot.|Bevarer kroppsspråk samtidig som ansiktet fortsatt kan leses.|Karakterens nøling vises gjennom hele kroppen.
medium_shot|Medium shot|Halvnært bilde|shot_composition|preproduction|foundation|Et utsnitt omtrent fra midje eller bryst og opp.|Balanserer gest, dialog og ansiktsinformasjon.|To personer kan snakke mens hendene fortsatt er synlige.
medium_close_up|Medium close-up|Nært halvbilde|shot_composition|preproduction|foundation|Et utsnitt omtrent fra bryst eller skuldre og opp.|Gir tydelig ansikt uten å bli like isolerende som et tett nærbilde.|Brukes gjennom en nøktern samtale.
close_up|Close-up|Nærbilde|shot_composition|preproduction|foundation|Et tett bilde av ansikt eller betydningsfull detalj.|Regissøren reserverer ofte nærbildet til informasjon eller emosjonell endring.|Nærbildet kommer når karakteren innser sannheten.
extreme_close_up|Extreme close-up|Ekstremt nærbilde|shot_composition|preproduction|foundation|Et svært tett bilde av en liten del av motivet.|Skaper intensitet, abstraksjon eller presis informasjon.|Bare øyet og refleksjonen i det er synlig.
insert|Insert|Detaljinnskudd|shot_composition|preproduction|foundation|Et nærbilde av en gjenstand eller handling som settes inn i scenen.|Brukes når detaljen har narrativ eller rytmisk betydning.|Nøkkelen går i feil lomme.
cutaway|Cutaway|Bortklipp|shot_composition|production|foundation|Et bilde som forlater hovedhandlingen for å vise noe relatert.|Kan gi informasjon, skjule tidskutt eller endre vekt.|Vi klipper til klokken mens samtalen fortsetter.
two_shot|Two-shot|Tobildet|shot_composition|preproduction|foundation|Et bilde som inneholder to hovedpersoner.|Viser relasjon, avstand og felles reaksjon uten å splitte dem.|Begge forblir i bildet når alliansen brytes.
over_shoulder|Over-the-shoulder|Over skulderen|shot_composition|preproduction|foundation|Et bilde av én person med del av motspilleren i forgrunnen.|Bevarer romlig relasjon og kan variere makt gjennom størrelse og vinkel.|Motspillerens skulder fyller mer når presset øker.
pov_shot|Point-of-view shot|Subjektivt synsbilde|shot_composition|preproduction|foundation|Et bilde presentert som det en karakter ser.|Knytter publikum direkte til karakterens oppmerksomhet og kunnskap.|Vi ser brevet fra hennes synsvinkel.
master_shot|Master shot|Masterbilde|shot_composition|preproduction|foundation|Et sammenhengende bilde som dekker hele eller store deler av scenens handling.|Gir geografisk og redaksjonell grunnstruktur, men må fortsatt ha en dramatisk idé.|Scenen kan spilles komplett i en bevegelig master.
establishing_shot|Establishing shot|Etableringsbilde|shot_composition|preproduction|foundation|Et bilde som etablerer sted, tid, geografi eller situasjon.|Regissøren avgjør hvor mye orientering publikum faktisk trenger.|Før interiøret ser vi at huset ligger isolert.
reaction_shot|Reaction shot|Reaksjonsbilde|shot_composition|production|foundation|Et bilde som viser responsen på en handling, replikk eller oppdagelse.|Kan flytte scenens synsvinkel og definere betydningen av det som nettopp skjedde.|Vi blir på den tause søsteren etter tilståelsen.
clean_single|Clean single|Rent enkeltbilde|shot_composition|production|intermediate|Et enkeltbilde uten motspillerens kropp i forgrunnen.|Gir isolasjon og fleksibel klipping, men kan svekke romlig forbindelse.|Det rene nærbildet brukes når karakteren mentalt trekker seg unna.
negative_space|Negative space|Negativt rom|shot_composition|preproduction|intermediate|Tomt eller lite aktivt område i komposisjonen rundt motivet.|Kan skape forventning, ubalanse, isolasjon eller plass for en kommende handling.|Tomrommet til venstre gjør at vi venter på noen.
headroom|Headroom|Luft over hodet|shot_composition|production|foundation|Avstanden mellom motivets hode og øvre bildekant.|Regissør og fotograf bruker headroom til balanse eller bevisst press.|Lite headroom gjør rommet trangere.
lead_room|Lead room|Blikk- eller bevegelsesrom|shot_composition|production|foundation|Plass i bildet foran et motivs blikk eller bevegelsesretning.|Støtter naturlig retning eller kan brytes for uro.|Karakteren ser inn i et tomt område av rammen.
focal_length|Focal length|Brennvidde|camera_lens|preproduction|foundation|Avstanden fra objektivets optiske sentrum til fokusplanet ved fokus på uendelig, uttrykt i millimeter.|Påvirker bildevinkel og perspektiv sammen med sensorstørrelse og kameraavstand.|En 25 mm gir videre bildevinkel enn en 75 mm på samme format.
angle_of_view|Angle of view|Bildevinkel|camera_lens|preproduction|foundation|Hvor mye av scenen objektiv og sensor fanger horisontalt, vertikalt eller diagonalt.|Regissøren bruker bildevinkel til å velge hvor mye rom og relasjon som skal inkluderes.|Større sensor viser mer av objektivets projiserte bilde ved samme brennvidde.
prime_lens|Prime lens|Fast objektiv|camera_lens|preproduction|foundation|Et objektiv med én fast brennvidde.|Kan oppmuntre til bevisst kameraplassering og har ofte spesifikke optiske egenskaper.|Scenen fotograferes hovedsakelig på 35 mm og 50 mm.
zoom_lens|Zoom lens|Zoomobjektiv|camera_lens|preproduction|foundation|Et objektiv med variabel brennvidde.|Gir rask omramming eller en synlig zoombevegelse uten å flytte kamera.|En langsom zoom snevrer inn rommet mens karakteren forstår.
spherical_lens|Spherical lens|Sfærisk objektiv|camera_lens|preproduction|intermediate|Et objektiv som danner bildet uten anamorfisk horisontal kompresjon.|Velges ut fra ønsket format, bokeh, flare, skarphet og romgjengivelse.|Sfærisk optikk kombineres med et beskåret 2.39-format.
anamorphic_lens|Anamorphic lens|Anamorfisk objektiv|camera_lens|preproduction|intermediate|Et objektiv som komprimerer bildet horisontalt ved opptak og strekkes tilbake i visning.|Gir bredt format og karakteristiske optiske egenskaper som oval bokeh og horisontale flares.|2x anamorfisk opptak de-squeezes i monitor og post.
depth_of_field|Depth of field|Dybdeskarphet|camera_lens|preproduction|foundation|Området fra nærmeste til fjerneste punkt som oppleves akseptabelt skarpt.|Regissøren bruker dybdeskarphet til å inkludere eller isolere informasjon.|Forgrunn og bakgrunn holdes skarpe i et maktspill.
shallow_focus|Shallow focus|Grunn dybdeskarphet|camera_lens|production|foundation|Smal sone av skarphet med tydelig uskarp for- eller bakgrunn.|Isolerer oppmerksomhet og kan skjule rominformasjon.|Bare ansiktet er skarpt mens rommet faller bort.
deep_focus|Deep focus|Stor dybdeskarphet|camera_lens|production|intermediate|Stor del av rommets dybde holdes lesbart skarp.|Lar handlinger i flere plan konkurrere eller kommentere hverandre.|Barnet i forgrunn og foreldrene i bakgrunn er samtidig skarpe.
focus_pull|Focus pull|Fokusdragning|camera_lens|production|foundation|Kontrollert endring av fokusavstand under et bilde.|Kan flytte oppmerksomhet uten klipp og følge handling i dybden.|Fokus går fra brevet til personen i døren.
rack_focus|Rack focus|Markert fokusskift|camera_lens|production|foundation|Et tydelig fokusdrag mellom to motiver eller dybdeplan.|Brukes som dramatisk overgang eller avsløring.|Fokus skifter fra pistolen til eierens ansikt.
hyperfocal_distance|Hyperfocal distance|Hyperfokal avstand|camera_lens|preproduction|advanced|Fokusavstanden som gir størst mulig dybdeskarphet fra en nærgrense til uendelig.|Nyttig når fokus må være robust i dokumentarisk eller krevende bevegelse.|Kamera settes slik at både gaten og horisonten er akseptabelt skarpe.
lens_distortion|Lens distortion|Objektivforvrengning|camera_lens|preproduction|intermediate|Geometrisk eller optisk endring av motivets form, særlig mot bildekantene.|Regissøren kan bruke eller unngå forvrengning ut fra ansikter, rom og tone.|Et vidt objektiv tett på ansiktet overdriver avstanden til bakgrunnen.
perspective_compression|Perspective compression|Perspektivkompresjon|camera_lens|preproduction|intermediate|Opplevelsen av at avstander i dybden virker redusert, vanligvis når kameraet flyttes langt unna og lengre brennvidde brukes.|Kan gjøre rommet tett, flatt eller truende.|Fjellene virker nærmere karakteren med teleperspektiv.
sensor_size|Sensor size|Sensorformat|camera_lens|preproduction|intermediate|Det fysiske bildearealet som registrerer objektivets projiserte bilde.|Påvirker bildevinkel ved gitt brennvidde og valg av optikk og dybdeskarphet.|50 mm viser videre utsnitt på large format enn på Super 35.
crop_factor|Crop factor|Beskjæringsfaktor|camera_lens|preproduction|Et sammenligningstall for bildevinkel mellom sensorformater.|Hjelper teamet å oversette ønsket utsnitt mellom ulike kameraformater.|En mindre sensor fanger en mindre del av samme bildesirkel.
minimum_focus|Minimum focus distance|Nærgrense|camera_lens|preproduction|intermediate|Den korteste avstanden objektivet kan fokusere på.|Påvirker om et planlagt nærbilde eller insert er fysisk mulig.|Objektivet kan ikke komme nær nok detaljen uten diopter.
diopter|Diopter|Nærfokuslinse|camera_lens|production|advanced|Et optisk element foran objektivet som endrer nærfokusevnen.|Brukes for ekstreme detaljer eller spesielle fokusvirkninger.|Split diopter holder nær forgrunn og fjern bakgrunn skarp med en synlig overgang.
aperture|Aperture|Blenderåpning|exposure_motion|production|foundation|Den variable åpningen i objektivet som regulerer lysmengde og påvirker dybdeskarphet.|Regissør og fotograf balanserer eksponering mot ønsket fokusuttrykk.|Blenderen åpnes for mindre dybdeskarphet.
f_stop|F-stop|F-tall|exposure_motion|production|foundation|Forholdet mellom brennvidde og blenderdiameter, brukt som mål for blenderåpning.|Lavere f-tall slipper nominelt inn mer lys og reduserer ofte dybdeskarpheten.|f/2 er mer åpent enn f/4.
t_stop|T-stop|T-tall|exposure_motion|production|intermediate|Et eksponeringsmål som også tar hensyn til faktisk lystap gjennom objektivet.|Gjør eksponering mer konsistent mellom ulike cinemaobjektiver.|To objektiver settes begge til T2.8.
iso_ei|ISO / Exposure Index|ISO / eksponeringsindeks|exposure_motion|production|foundation|En følsomhets- eller arbeidsindeks som brukes til å beregne eksponering.|Valget påvirker eksponeringsstrategi, støy og fordeling av highlight- og skyggerom.|Kameraet vurderes på EI 800 under testen.
shutter_angle|Shutter angle|Lukkervinkel|exposure_motion|production|foundation|En filmkamerabasert måte å uttrykke hvor stor del av hver bildeperiode sensoren eksponeres.|Påvirker eksponering og mengden bevegelsesuskarphet.|180 grader ved 24 fps gir omtrent 1/48 sekund.
shutter_speed|Shutter speed|Lukkertid|exposure_motion|production|foundation|Hvor lenge hvert bilde eksponeres.|Kortere tid gir skarpere bevegelse og mindre lys, lengre tid gir mer motion blur.|1/500 brukes for hakkete, skarp action.
frame_rate|Frame rate|Bildefrekvens|exposure_motion|production|foundation|Antall bilder registrert eller vist per sekund.|Regissøren velger frekvens for normal tid, slow motion, fast motion eller teknisk levering.|48 fps avspilt i 24 fps gir halv hastighet.
slow_motion|Slow motion|Sakte film|exposure_motion|production|foundation|Opptak med høyere bildefrekvens enn avspilling slik at tiden strekkes.|Brukes for analyse, vekt, skjønnhet eller subjektiv opplevelse.|En fallende kopp filmes i 96 fps.
fast_motion|Fast motion|Hurtig film|exposure_motion|production|foundation|Opptak eller avspilling som komprimerer tid og øker bevegelseshastigheten.|Kan skape komikk, energi eller tidsforkortelse.|Skyer passerer raskt over bygningen.
motion_blur|Motion blur|Bevegelsesuskarphet|exposure_motion|production|foundation|Uskarpheten som oppstår når motiv eller kamera beveger seg under eksponeringen av ett bilde.|Regissøren bruker mengden til å påvirke opplevelsen av flyt, fart og uro.|Lengre lukkertid gjør løpingen mer flytende og urolig.
exposure|Exposure|Eksponering|exposure_motion|production|foundation|Mengden lys som registreres og hvordan motivets toner plasseres i opptaksmediet.|Må vurderes dramatisk og teknisk for hud, høylys, skygger og etterarbeid.|Ansiktet prioriteres selv om vinduet klipper litt.
exposure_latitude|Exposure latitude|Eksponeringslatitude|exposure_motion|production|intermediate|Området et opptaksmedium tåler under- eller overeksponering og fortsatt gir brukbart resultat.|Påvirker hvor risikabelt lyskontrast og eksponeringsvalg er.|Testen viser hvor mye vinduet kan overeksponeres.
dynamic_range|Dynamic range|Dynamisk omfang|exposure_motion|production|intermediate|Spennet mellom mørkeste og lyseste detalj kamera eller medium kan gjengi samtidig.|Regissøren og fotografen vurderer om scene, lys og format kan holde ønsket informasjon.|Interiør og solbelyst eksteriør må eksistere i samme bilde.
highlight_rolloff|Highlight roll-off|Overgang i høylys|exposure_motion|production|advanced|Hvordan svært lyse områder gradvis eller brått går mot maksimal hvitverdi.|Påvirker hvordan vinduer, hudglans og lyskilder oppleves.|Myk roll-off lar lampen beholde form før den blir hvit.
underexposure|Underexposure|Undereksponering|exposure_motion|production|foundation|For lite eksponering i forhold til valgt referanse, slik at toner plasseres mørkere.|Kan være bevisst, men må vurderes mot skyggeinformasjon, støy og hud.|Natten eksponeres lavt uten at ansiktene forsvinner.
overexposure|Overexposure|Overeksponering|exposure_motion|production|foundation|Mer eksponering enn valgt referanse, slik at toner plasseres lysere.|Kan gi åpen, bleket eller drømmeaktig effekt, men risikerer tap av høylysdetalj.|Bakgrunnen brennes ut for å isolere silhuetten.
nd_filter|Neutral density filter|ND-filter|exposure_motion|production|foundation|Et nøytralt filter som reduserer lys uten å skulle endre farge.|Lar ønsket blender og lukkertid beholdes i sterkt lys.|ND brukes ute for å filme på T2.
false_color|False color|Falskfarge|exposure_motion|production|intermediate|Et monitorverktøy som viser eksponeringsnivåer som bestemte farger.|Hjelper teamet å kontrollere hud, gråkort, høylys og skygger konsistent.|Hudområdet sjekkes mot kameraets false-color-skala.
key_light|Key light|Hovedlys|lighting_color|preproduction|foundation|Det dominerende lyset som definerer motivets viktigste retning og form.|Regissøren bruker retningen til å støtte rom, tid og prestasjon.|Vinduet fungerer som scenens key.
fill_light|Fill light|Fylllys|lighting_color|production|foundation|Lys som løfter skyggesiden og styrer kontrast uten å bli nytt hovedlys.|Mengden fill avgjør hvor mye informasjon og mykhet som beholdes.|Et svakt bounce gir detalj i skyggesiden.
backlight|Backlight|Baklys|lighting_color|production|foundation|Lys som treffer motivet bakfra eller bakfra-siden.|Kan separere figur fra bakgrunn, vise atmosfære eller skape silhuett.|Sol gjennom røyk tegner kanten av kroppen.
practical_light|Practical light|Praktisk lyskilde|lighting_color|preproduction|foundation|En lyskilde som er synlig i scenen, som lampe, skjerm eller stearinlys.|Gir motivasjon, design og eksponeringsutfordring i samme element.|Bordlampen begrunner det varme ansiktslyset.
motivated_lighting|Motivated lighting|Motivert lyssetting|lighting_color|preproduction|foundation|Lys som oppleves å komme fra troverdige kilder i scenens verden selv når det er forsterket utenfor bildet.|Holder stilisert lys forankret i rom og historie.|Et større lys utenfor vinduet etterligner måneskinn.
hard_light|Hard light|Hardt lys|lighting_color|production|foundation|Lys fra en liten eller fjern kilde som gir tydelige skygger og markert tekstur.|Kan skape presisjon, varme, brutalitet eller grafikk.|Direkte sol lager skarpe persienneskygger.
soft_light|Soft light|Mykt lys|lighting_color|production|foundation|Lys fra en stor eller diffus kilde som gir gradvise skyggoverganger.|Kan gi naturlig omslutning eller redusere tekstur og kontrast.|En stor diffus ramme lager mykt vinduslys.
negative_fill|Negative fill|Negativ fill|lighting_color|production|intermediate|Mørke flater brukes til å redusere reflektert lys og gjøre skyggesiden mørkere.|Skaper form og kontrast uten å legge til lys.|Sort tekstil ved ansiktet absorberer rommets bounce.
bounce_light|Bounce light|Reflektert lys|lighting_color|production|foundation|Lys sendes mot en flate og reflekteres mykere mot motivet.|Gir stor, indirekte kilde og kan etterligne naturlig romlys.|En lampe bounces i hvit vegg.
diffusion|Diffusion|Diffusjon|lighting_color|production|foundation|Materiale eller metode som sprer lys og øker kildens tilsynelatende størrelse.|Brukes til å mykne skygger, hud og overganger.|Silke plasseres mellom lampe og skuespiller.
flag|Flag|Flagg|lighting_color|production|foundation|En ugjennomsiktig ramme som blokkerer eller former lys.|Hindrer spill, beskytter bakgrunn eller skaper presis avgrensning.|Et flagg holder lyset borte fra veggen.
gobo|Gobo|Mønstermaske|lighting_color|production|intermediate|En form eller mal mellom lys og motiv som lager mønster eller tekstur.|Kan simulere vinduer, løv, bevegelse eller grafisk form.|En branchaloris skaper skygger som fra trær.
color_temperature|Color temperature|Fargetemperatur|lighting_color|production|foundation|En beskrivelse i kelvin av lysets varme eller kjølige karakter langs en idealisert skala.|Regissøren og fotografen bruker forskjeller til tid, rom, kilde og følelseskontrast.|Tungsten rundt 3200 K kontrasteres mot dagslys.
white_balance|White balance|Hvitbalanse|lighting_color|production|foundation|Kameraets eller prosessens referanse for hva som skal gjengis nøytralt.|Valget bestemmer hvordan ulike lyskilder blir varme, kalde eller nøytrale.|Kamera balanseres til 4300 K i blandingslys.
contrast_ratio|Contrast ratio|Kontrastforhold|lighting_color|preproduction|intermediate|Forholdet mellom lysnivåer, ofte mellom key- og skyggeside eller lyseste og mørkeste område.|Gjør ønsket kontrast målbar og repeterbar.|Ansiktet holdes rundt fire til én mellom sidene.
palette|Color palette|Fargepalett|lighting_color|development|foundation|Det utvalgte systemet av dominerende og aksentfarger i film eller scene.|Samordner design, kostyme, lys og grading med dramatisk progresjon.|Rødt reserveres for øyeblikk der kontroll brytes.
gel|Lighting gel|Lysfilter|lighting_color|production|foundation|Farget eller korrigerende materiale foran en lyskilde.|Endrer farge, spektrum eller intensitet for å matche eller uttrykke en kilde.|CTB brukes for å gjøre tungstenlys blåere.
log_encoding|Log encoding|Logaritmisk bildekurve|lighting_color|production|advanced|En opptakskurve som koder eksponeringssteg effektivt over et stort område for senere bearbeiding.|Krever korrekt monitorering og transformasjon for at settbildet skal være meningsfullt.|LogC vises gjennom en monitor-LUT.
lut|LUT|Oppslagstabell|lighting_color|production|intermediate|En tabell som omformer innverdier til utverdier, ofte for visning eller fargebehandling.|Regissøren må vite om LUT-en er en visningshjelp eller en kreativ transformasjon som skal følge prosjektet.|En show LUT brukes på dailies og i klipperommet.
show_lut|Show LUT|Prosjekt-LUT|lighting_color|preproduction|advanced|En definert LUT eller transformasjon som uttrykker prosjektets grunnleggende bildeintensjon.|Hjelper sett, dailies, klipp og VFX å se et mer konsistent utgangspunkt.|Show LUT-en testes mot hud og høylys før opptak.
production_design|Production design|Produksjonsdesign|design_continuity|preproduction|foundation|Den overordnede visuelle utformingen av filmens fysiske verden.|Regissøren samarbeider om hvordan miljø, form, farge og materiale forteller historien.|Leiligheten blir trangere gjennom møblering og ombygging.
art_direction|Art direction|Art direction|design_continuity|preproduction|foundation|Praktisk og organisatorisk realisering av produksjonsdesignerens konsept gjennom art department.|Regissøren avklarer prioriterte sett, bygg, grafikk og gjennomførbarhet.|Art director koordinerer byggingen av korridoren.
set_decoration|Set decoration|Set dressing og dekor|design_continuity|preproduction|foundation|Valg og plassering av møbler, tekstiler og miljødetaljer i settet.|Gir karakter, historie, rytme og muligheter for blocking.|Bordet er overfylt slik at karakterene må strekke seg over hverandre.
prop|Prop|Rekvisitt|design_continuity|preproduction|foundation|En gjenstand som brukes eller inngår aktivt i scenen.|Regissøren vurderer hvordan rekvisitten påvirker handling, kontinuitet og nærbilder.|Telefonen må fungere likt i alle takes.
hero_prop|Hero prop|Hovedrekvisitt|design_continuity|preproduction|intermediate|En særlig viktig rekvisitt som tåler nærbilde og ofte finnes i flere kontrollerte kopier.|Krever tidlig beslutning om utseende, funksjon og kontinuitet.|Brevet bygges i flere identiske versjoner.
costume_design|Costume design|Kostymedesign|design_continuity|preproduction|foundation|Utforming av klær og tilbehør som uttrykker karakter, tid, status, bevegelse og filmens palett.|Regissøren samarbeider om hvordan kostyme påvirker silhuett, blocking og progresjon.|Jakken blir strammere etter hvert som karakteren mister kontroll.
makeup_hair|Makeup and hairstyling|Sminke og hår|design_continuity|preproduction|foundation|Utforming av hud, hår, alder, skade, stil og kontinuitet for karakterene.|Må støtte kameraformat, lys, tid og karakterutvikling.|Skaden utvikles gjennom dokumenterte stadier.
texture|Texture|Tekstur|design_continuity|preproduction|foundation|Den synlige og taktile kvaliteten i overflater, stoff, hud og miljø.|Kan skape historisk troverdighet, kontrast eller sanselig tone.|Glatt kostyme står mot ru vegger.
silhouette|Silhouette|Silhuett|design_continuity|preproduction|foundation|Motivets ytre form, lesbar uavhengig av indre detalj.|Regissøren og designerne bruker silhuett til gjenkjennelse, status og grafikk.|Karakterens store frakk leses i mørket.
spatial_geography|Spatial geography|Romgeografi|design_continuity|preproduction|foundation|Publikums forståelse av hvor steder, personer og retninger befinner seg i forhold til hverandre.|Regissøren etablerer nok informasjon til at handling og fare kan følges.|Vi vet hvor utgangen er før brannen starter.
screen_geography|Screen geography|Skjermgeografi|design_continuity|production|foundation|Hvordan romlige forhold representeres gjennom bilder og klipp.|Blocking, akselinje og etableringer må arbeide sammen.|Døren forblir på samme side av karakteren mellom utsnitt.
continuity|Continuity|Kontinuitet|design_continuity|production|foundation|Sammenheng i tid, rom, handling, kostyme, rekvisitter, lys og prestasjon mellom opptak.|Regissøren må skille viktige kontinuitetsbrudd fra irrelevante detaljer.|Koppen er like full før og etter klippet.
matching_action|Matching action|Sammenfallende handling|design_continuity|production|foundation|En bevegelse fortsetter troverdig fra ett bilde til et annet.|Gir klipperen et sømløst eller bevisst brutt overgangspunkt.|Hånden åpner døren i total og fullfører i nærbilde.
wardrobe_test|Wardrobe test|Kostymeprøve for kamera|design_continuity|preproduction|intermediate|Kostymer testes med skuespiller, kamera og ofte lys før opptak.|Avslører moaré, fargeproblemer, bevegelse, passform og karaktervirkning.|Stripet skjorte byttes etter kameratesten.
set_extension|Set extension|Digital eller fysisk set-utvidelse|design_continuity|postproduction|advanced|Utvidelse av et miljø utover det som faktisk er bygget eller fotografert.|Regissøren må planlegge komposisjon, lys, tracking og skuespillerens orientering.|Byggets øvre etasjer legges til med VFX.
assembly|Assembly cut|Assembly|editing_time|postproduction|foundation|En tidlig sammenstilling av opptakene i manus- eller sceneorden.|Viser hva materialet faktisk inneholder før finere rytmevalg.|Alle scenene legges grovt etter hverandre.
rough_cut|Rough cut|Grovklipp|editing_time|postproduction|foundation|En arbeidsversjon der struktur, scenelengde og grunnleggende valg er under utvikling.|Regissøren vurderer helhet og større problemer før detaljpolering.|En scene flyttes og tre minutter fjernes.
fine_cut|Fine cut|Finklipp|editing_time|postproduction|foundation|En mer presis versjon der bildevalg, rytme og overganger finjusteres.|Regissøren arbeider med frames, reaksjoner og lydforløp uten å miste helheten.|Pausen før svaret kortes med åtte frames.
picture_lock|Picture lock|Bildelås|editing_time|postproduction|foundation|Punktet der bilderekkefølge og varighet ikke lenger skal endres vesentlig.|Gjør at lyd, VFX, musikk og conform kan ferdigstilles mot stabile tidskoder.|Filmen låses før endelig lydmiks.
continuity_editing|Continuity editing|Kontinuitetsklipp|editing_time|postproduction|foundation|Et klippesystem som gjør tid, rom og handling lett å følge over flere bilder.|Regissøren kan bruke det som usynlig grunnform eller bryte det med hensikt.|Blikk og bevegelse matcher gjennom samtalen.
montage|Montage|Montasje|editing_time|postproduction|foundation|Sammenstilling av bilder som skaper mening, komprimerer tid eller bygger en idé gjennom kontrast og rekkefølge.|Regissøren planlegger hvilke handlinger og lyder som bærer utviklingen.|Treningen komprimeres gjennom fem handlinger og ett musikalsk forløp.
match_cut|Match cut|Form- eller handlingsmatch|editing_time|postproduction|foundation|Et klipp som kobler to bilder gjennom lik form, bevegelse, lyd eller idé.|Kan skape kontinuitet, kontrast eller metafor.|En rund lampe klipper til solen.
jump_cut|Jump cut|Hoppklipp|editing_time|postproduction|foundation|Et synlig tids- eller posisjonshopp mellom lignende bilder.|Brukes for kompresjon, uro, energi eller selvbevisst form.|Pauser fjernes fra samme kameravinkel.
cross_cutting|Cross-cutting|Kryssklipp|editing_time|postproduction|foundation|Veksling mellom handlinger på forskjellige steder eller tider, ofte forstått som parallelle.|Bygger sammenheng, kontrast, forventning eller samtidighet.|Redningen kryssklippes med faren som nærmer seg.
parallel_editing|Parallel editing|Parallellklipp|editing_time|postproduction|intermediate|Klipp mellom to eller flere handlingsforløp som tematisk eller tidslig settes i forhold.|Regissøren kan skape ironi selv uten at hendelsene møtes.|To familier forbereder samme ritual på ulike måter.
smash_cut|Smash cut|Bråkontrastklipp|editing_time|postproduction|intermediate|Et plutselig klipp mellom sterkt kontrasterende bilder eller lydtilstander.|Brukes som støt, vits, tidsbrudd eller emosjonell kontrast.|Et skrik klipper til absolutt stillhet ved frokostbordet.
cut_on_action|Cut on action|Klipp i bevegelse|editing_time|postproduction|foundation|Klippet legges inne i en handling slik at bevegelsen leder oppmerksomheten over overgangen.|Kan skjule klippet og bevare energi.|Karakteren reiser seg i total og fullfører i halvnært.
ellipsis|Ellipsis|Ellipse|editing_time|postproduction|foundation|Et klipp utelater tid eller handling som publikum kan slutte seg til.|Regissøren bruker ellipsen til kompresjon, mysterium eller subjektivitet.|Døren lukkes og vi klipper til morgenen etter.
j_cut|J-cut|J-klipp|editing_time|postproduction|foundation|Lyden fra neste bilde begynner før bildet skifter.|Forbereder overgang, trekker publikum fremover eller skaper kontrast.|Toget høres før vi ser stasjonen.
l_cut|L-cut|L-klipp|editing_time|postproduction|foundation|Lyden fra forrige bilde fortsetter etter at bildet har skiftet.|Bevarer emosjonell eller informativ forbindelse over bildeovergangen.|Tilståelsen fortsetter over reaksjonen i neste rom.
pace|Pace|Tempo|editing_time|postproduction|foundation|Den opplevde hastigheten i filmens hendelser og informasjonsflyt.|Regissøren styrer tempo gjennom scenevarighet, bevegelse, dialog, klipp og lyd.|Filmen roer seg før det siste valget.
rhythm|Rhythm|Rytme|editing_time|postproduction|foundation|Mønsteret av varighet, trykk, pauser, bevegelse og lyd gjennom tid.|Rytme kan eksistere innen bildet og mellom bildene.|Tre raske avbrytelser følges av ett langt stillestående bilde.
hold|Hold|La bildet stå|editing_time|postproduction|foundation|Å beholde et bilde lenger før klipp.|Gir rom for reaksjon, ubehag, informasjon eller publikums egen tolkning.|Vi holder etter replikken til smilet forsvinner.
trim|Trim|Finjustere klippepunkt|editing_time|postproduction|foundation|Å flytte inn- eller utpunkt på et klipp.|Regissør og klipper former timing på frame-nivå.|Utpunktet flyttes tolv frames tidligere.
production_sound|Production sound|Opptakslyd|sound_music|production|foundation|Dialog og andre lyder registrert under selve opptaket.|Regissøren må beskytte prestasjon og miljø samtidig som lyden blir brukbar.|Scenen prioriterer ren dialog fremfor vifte i lokalet.
room_tone|Room tone|Romtone|sound_music|production|foundation|Opptak av et roms grunnlyd uten hovedhandling eller dialog.|Gir lydklippen materiale til sømløse overganger og pauser.|Tretti sekunder romtone tas etter scenen.
wild_track|Wild track|Separat lydopptak|sound_music|production|foundation|Lyd tatt uten synkront bilde, ofte dialog, atmosfære eller spesifikk handling.|Kan redde eller berike en scene uten ny bildeopptak.|Fottrinnene tas separat etter tagningen.
ambience|Ambience|Atmosfærelyd|sound_music|production|foundation|Bakgrunnslyder som definerer sted, tid og miljø.|Regissøren bruker atmosfære som rom, rytme og narrativ informasjon.|Fjerne tog gjør natten urban og urolig.
dialogue|Dialogue|Dialog|sound_music|production|foundation|Talt språk mellom eller fra karakterer.|Regissøren vurderer tekst, undertekst, rytme, overlapping og lydperspektiv.|En replikk spilles lavt men ligger tydelig i miksen.
adr|ADR|Ettersynkronisert dialog|sound_music|postproduction|foundation|Dialog spilles inn på nytt i studio for å erstatte eller supplere opptakslyd.|Regissøren hjelper skuespilleren å gjenskape timing, pust og handling.|En vindutsatt replikk tas på nytt mot bildet.
foley|Foley|Foley-lyd|sound_music|postproduction|foundation|Synkroniserte menneskeskapte lyder for skritt, klær og fysisk kontakt.|Regissøren og lyddesigner kan bruke detaljene realistisk eller ekspressivt.|Frakkens stoff blir tydeligere når karakteren nærmer seg.
sound_effect|Sound effect|Lydeffekt|sound_music|postproduction|foundation|En konkret lyd skapt, funnet eller behandlet for en handling eller hendelse.|Kan være naturalistisk, forsterket eller helt designet.|Døren får et tyngre mekanisk uttrykk enn opptakslyden.
diegetic_sound|Diegetic sound|Diegetisk lyd|sound_music|postproduction|foundation|Lyd som forstås å eksistere i filmens verden og i prinsippet kan høres av karakterene.|Regissøren kan flytte lyd mellom kilde, rom og subjektiv opplevelse.|Musikken kommer fra radioen i scenen.
non_diegetic_sound|Non-diegetic sound|Ikke-diegetisk lyd|sound_music|postproduction|foundation|Lyd som ikke presenteres som en fysisk del av filmens verden.|Brukes til fortellerstemme, score, struktur eller subjektiv kommentar.|Orkestermusikken høres bare av publikum.
source_music|Source music|Kildemusikk|sound_music|production|foundation|Musikk med en identifiserbar kilde i scenen.|Påvirker playback, blocking, rettigheter, tempo og kontinuitet.|Bandet spiller i rommet mens dialogen pågår.
score|Score|Original filmmusikk|sound_music|postproduction|foundation|Komponert musikk laget for filmens dramatiske og strukturelle behov.|Regissøren samarbeider om tema, instrumentering, plassering og hvor musikk ikke skal brukes.|Et tema kommer først komplett etter karakterens valg.
temp_score|Temp score|Midlertidig musikk|sound_music|postproduction|foundation|Eksisterende eller foreløpig musikk lagt under arbeidsklipp.|Kan kommunisere rytme, men også låse forventninger for tidlig.|Klipperen bruker temp for å teste scenens puls.
spotting_session|Spotting session|Musikk- eller lydspotting|sound_music|postproduction|foundation|Gjennomgang der regissør og fagpersoner bestemmer hvor musikk eller lyddesign begynner, slutter og hva det skal gjøre.|Knytter hvert cue til dramatisk funksjon og overgang.|De beslutter at musikken starter etter blikket, ikke ved døren.
leitmotif|Leitmotif|Ledemotiv|sound_music|postproduction|intermediate|Et tilbakevendende musikalsk motiv knyttet til person, idé, sted eller utvikling.|Regissøren kan la motivet endres med karakterens forståelse.|Temaet spilles i redusert form før avsløringen.
sound_bridge|Sound bridge|Lydbro|sound_music|postproduction|foundation|Lyd fortsetter eller begynner over et sceneskifte og binder to bilder eller tider sammen.|Kan skape kontinuitet, kontrast eller forventning.|Applaus fortsetter over et tomt rom dagen etter.
sound_perspective|Sound perspective|Lydperspektiv|sound_music|postproduction|intermediate|Hvordan avstand, rom, retning og subjektivitet uttrykkes i lyd.|Regissøren bestemmer hva publikum hører fra karakterens posisjon eller mentale tilstand.|Dialogen dempes når karakteren får panikk.
silence|Silence|Stillhet|sound_music|postproduction|foundation|Bevisst reduksjon eller fravær av forventet lyd, ofte relativt til omgivelsene.|Stillhet skaper vekt, brudd eller subjektiv isolasjon.|Byens lyd faller bort idet beskjeden kommer.
prelap|Prelap|Forhåndslyd|sound_music|postproduction|intermediate|Lyd fra neste scene høres før bildeovergangen.|Brukes som overgang, forventning eller tematisk kobling.|Barnelatter begynner over kirkegården.
final_mix|Final mix|Sluttmiks|sound_music|postproduction|foundation|Den endelige balanseringen og behandlingen av dialog, effekter, atmosfære og musikk.|Regissøren kontrollerer hierarki, dynamikk, klarhet og filmens totale lydreise.|Musikken senkes slik at pusten blir scenens fokus.
head_of_department|Head of department|Avdelingsleder|production_post|preproduction|foundation|Lederen for et fagområde som foto, design, kostyme, lyd eller sminke.|Regissøren kommuniserer helhetsvisjonen gjennom avdelingslederne.|Fotograf og produksjonsdesigner samordner farge og materialer.
first_ad|First assistant director|Første regiassistent|production_post|preproduction|foundation|Leder den praktiske opptaksavviklingen, tidsplanen og koordineringen på sett under regissørens kreative ledelse.|Regissøren bruker 1. AD til å gjøre kreative prioriteringer gjennomførbare og sikre.|1. AD beregner tiden for tre kameraoppsett.
dp|Director of photography|Filmfotograf|production_post|preproduction|foundation|Avdelingsleder for kamera og lys som utvikler og gjennomfører filmens fotografiske uttrykk med regissøren.|Regissør og fotograf oversetter dramatisk idé til optikk, lys, bevegelse og eksponering.|De tester to linsesett før valg.
script_supervisor|Script supervisor|Script og kontinuitetsansvarlig|production_post|production|foundation|Fører detaljert kontroll med manusdekning, takes, kontinuitet, skjermretning og informasjon til klipp.|Regissøren bruker notatene til å vite hva som er dekket og hva som mangler.|Script supervisor varsler at blikkretningen ikke matcher.
production_constraint|Production constraint|Produksjonsbegrensning|production_post|preproduction|foundation|En ramme som tid, budsjett, sted, sikkerhet, vær, rettighet eller utstyr setter for løsningen.|Regissøren prioriterer intensjonen og finner en form som fungerer innen rammen.|Solnedgangen gir bare tjue minutter for hovedbildet.
location_scout|Location scout|Locationbefaring|production_post|preproduction|foundation|Kreativ og praktisk vurdering av mulige opptakssteder.|Regissøren undersøker rom, lys, lyd, tilgang, geografi og produksjonsverdi.|En bred korridor velges for dybdestaging.
tech_scout|Technical scout|Teknisk befaring|production_post|preproduction|foundation|Felles befaring med nøkkelavdelinger for å planlegge faktisk gjennomføring på valgt location.|Avklarer kamera, lys, lyd, strøm, rigg, sikkerhet og logistikk.|Teamet merker hvor kranen kan stå.
floor_plan|Floor plan|Plantegning|production_post|preproduction|foundation|En ovenfra-tegning av rom, vegger, dører, personer og kameraoppsett.|Brukes til blocking, akselinjer, lys, rigg og shotplanning.|Kamera A og B markeres på hver side av bordet.
shooting_schedule|Shooting schedule|Opptaksplan|production_post|preproduction|foundation|Planen for når scener og elementer skal fotograferes, ofte gruppert av location, skuespiller og logistikk.|Regissøren beskytter kreativ progresjon gjennom prioritering og forberedelse selv når scenene tas ute av rekkefølge.|Alle nattscener samles i samme uke.
call_sheet|Call sheet|Dagsplan|production_post|production|foundation|Dokumentet som oppgir dagens scener, tider, location, vær, cast, crew og praktisk informasjon.|Regissøren bruker det sammen med 1. AD for å forstå dagens rekkefølge og presspunkter.|Første scene står klar til opptak klokken 08.00.
setup|Setup|Kameraoppsett|production_post|production|foundation|En bestemt kombinasjon av kameraposisjon, optikk, lys og rigg som krever forberedelse.|Shotlisten og tidsplanen må skille mellom bilder og faktiske setups.|Tre bilder tas fra samme setup med små omramminger.
company_move|Company move|Flytting av hele enheten|production_post|production|intermediate|Når produksjonen flytter cast, crew og utstyr til nytt sted i løpet av dagen.|Regissøren vurderer om et kreativt bilde forsvarer tidskostnaden.|Et ekstra eksteriør krever company move og faller ut.
slate|Slate / clapperboard|Klapp|production_post|production|foundation|Tavle og klapp som identifiserer scene, bilde og take og gir synkroniseringspunkt.|Korrekt slating gjør dailies, sync, logging og klipp pålitelig.|Scene 24, bilde 3B, take 2 klappes.
take|Take|Tagning|production_post|production|foundation|Én sammenhengende innspilling fra kamera og lyd starter til de stopper.|Regissøren vurderer hva som skal beholdes og hva neste take skal undersøke.|Take 4 har best prestasjon, men trenger pickup av slutten.
print_take|Print take|Foretrukket tagning|production_post|production|foundation|En take regissøren markerer som særlig brukbar eller ønsket for klipp.|Hjelper dailies og klipper, men andre takes forblir tilgjengelige.|Regissøren kaller take 6 print.
circle_take|Circle take|Sirklet tagning|production_post|production|foundation|En foretrukket take markert i rapport eller metadata for rask identifikasjon.|Brukes i dailies og klipp som startpunkt, ikke nødvendigvis endelig valg.|Script supervisor sirkler take 3.
pickup|Pickup|Supplerende delopptak|production_post|production|foundation|En kort del av en scene eller handling tas på nytt eller i tillegg uten full ny tagning.|Sparer tid når bare ett element mangler.|De tar pickup fra replikken til døren lukkes.
safety_take|Safety take|Sikkerhetstagning|production_post|production|foundation|En ekstra take etter en tilsynelatende god versjon for å sikre alternativ eller teknisk trygghet.|Regissøren må vite hva sikkerhetstaken skal forbedre, ellers blir den bare tidsbruk.|En siste take prøver mindre intensitet.
video_assist|Video assist|Videomonitorering|production_post|production|foundation|Systemet som lar regissør og andre se kamerabildet under eller etter opptak.|Brukes til komposisjon, prestasjon, kontinuitet og teknisk vurdering uten å erstatte samarbeid på gulvet.|Regissøren sjekker eyeline på monitoren.
metadata|Metadata|Metadata|production_post|production|intermediate|Beskrivende data om opptak, som timecode, fps, EI, hvitbalanse, objektiv, rull og take.|Korrekt metadata binder kamera, lyd, dailies, VFX og post sammen.|Linsedata følger klippet til VFX.
proxy|Proxy|Arbeidskopi|production_post|postproduction|foundation|En lettere mediefil laget for effektiv klipp og deling mens originalmaterialet bevares.|Regissøren ser ofte proxy i klipperom eller fjernreview.|ARRIRAW transkodes til ProRes proxy.
conform|Conform|Konformering|production_post|postproduction|intermediate|Prosessen der den låste klippen kobles tilbake til originalmedier med full kvalitet.|Regissøren og postteamet kontrollerer at bildevalg, hastigheter og framing er riktig gjenskapt.|EDL-en bygger finalen fra kameranegativet.
color_grade|Color grade|Fargekorrigering og grading|production_post|postproduction|foundation|Kreativ og teknisk bearbeiding av eksponering, kontrast, farge og bildebalanse etter klipp.|Regissøren og colorist fullfører bildets hierarki og kontinuitet uten å miste fotografisk hensikt.|Hud holdes konsistent mens bakgrunnen kjøles gradvis.
aces|ACES|Academy Color Encoding System|production_post|postproduction|advanced|Et standardisert system for å håndtere og utveksle fargeinformasjon gjennom opptak, VFX, grading, mastering og arkiv.|Regissøren trenger ikke operere transformene, men bør forstå at visning og master kan være ulike ledd i samme pipeline.|Kameradata går gjennom input transform og riktig output transform.
input_transform|Input Transform|Input-transform|production_post|postproduction|advanced|En ACES-transform som oversetter kameraets eller kildens native bildedata til ACES-representasjon.|Sikrer at ulike kameraer starter riktig i fargepipelinen.|Kameraets LogC-materiale får riktig input transform.
output_transform|Output Transform|Output-transform|production_post|postproduction|advanced|En ACES-transform som gjør scene-referert materiale klart for en bestemt skjerm eller visningsstandard.|Regissøren må evaluere bildet gjennom riktig transform for kino, HDR eller SDR.|Kinoversjonen og HDR-masteren bruker ulike output transforms.
vfx|Visual effects|Visuelle effekter|production_post|postproduction|foundation|Bilder eller bildeelementer som skapes, kombineres eller endres utover ordinær fotografi og klipp.|Regissøren planlegger VFX som del av iscenesettelsen, ikke som tilfeldig reparasjon etterpå.|En set extension og digital crowd kombineres med live action.
previs|Previsualization|Forvisualisering|production_post|preproduction|intermediate|Animert eller annen forhåndsvisualisering av komplekse bilder, sekvenser eller VFX.|Hjelper regi og avdelinger å teste kamera, timing og logistikk før opptak.|Actionsekvensen bygges som enkel 3D-previs.
plate|Plate|Bakgrunns- eller effektplate|production_post|production|intermediate|Et opptak laget som element for senere compositing, ofte uten hovedhandling.|Regissøren må sikre riktig perspektiv, lys, bevegelse og varighet.|Tom gate fotograferes som clean plate.
clean_plate|Clean plate|Ren bakgrunnsplate|production_post|production|intermediate|Et bilde av miljøet uten skuespiller eller element som senere skal fjernes eller legges til.|Gir VFX fleksibilitet til cleanup og compositing.|Rommet tas tomt etter scenen.
dcp|Digital Cinema Package|Digital kinopakke|production_post|postproduction|foundation|Standardisert filpakke for digital kinovisning med bilde, lyd, tekst og metadata.|Regissøren kontrollerer at kinoens visning, lydnivå og teksting gjengir intensjonen.|Finalen kvalitetssikres fra DCP i kinosal.
deliverables|Deliverables|Leveransemateriale|production_post|postproduction|foundation|Alle avtalte mastere, lydversjoner, tekstfiler, metadata og øvrige elementer som skal leveres.|Regissør og postteam må forstå hvilke versjoner som krever kreativ kontroll.|Produksjonen leverer DCP, IMF, tekstløse bilder og M&E.
`.trim();

export const DIRECTOR_TERMS: readonly DirectorTerm[] = TERM_ROWS.split("\n").map((line) => {
  const [id, term, norwegian, category, phase, level, definition, directorUse, example] = line.split("|");
  if (!id || !term || !norwegian || !category || !phase || !level || !definition || !directorUse || !example) {
    throw new Error(`Invalid director terminology row: ${line}`);
  }
  return {
    id,
    term,
    norwegian,
    category: category as DirectorKnowledgeCategoryId,
    phase: phase as DirectorKnowledgePhase,
    level: level as DirectorKnowledgeLevel,
    definition,
    directorUse,
    example,
    sourceIds: CATEGORY_SOURCES[category as DirectorKnowledgeCategoryId],
  };
});

export function getDirectorTerm(termId: string): DirectorTerm | undefined {
  return DIRECTOR_TERMS.find((term) => term.id === termId);
}

export function searchDirectorTerms(
  query: string,
  category: DirectorKnowledgeCategoryId | "all" = "all",
  phase: DirectorKnowledgePhase | "all" = "all",
): readonly DirectorTerm[] {
  const normalizedQuery = normalizeSearchText(query);
  return DIRECTOR_TERMS.filter((term) => {
    if (category !== "all" && term.category !== category) return false;
    if (phase !== "all" && term.phase !== phase) return false;
    if (!normalizedQuery) return true;
    const haystack = normalizeSearchText([
      term.term,
      term.norwegian,
      term.definition,
      term.directorUse,
      term.example,
    ].join(" "));
    return haystack.includes(normalizedQuery);
  });
}

export function getDirectorTermsForWorkflowStep(step: DirectorWorkflowStep): readonly DirectorTerm[] {
  return step.termIds.map((termId) => getDirectorTerm(termId)).filter((term): term is DirectorTerm => Boolean(term));
}

export function getDirectorKnowledgeCategory(categoryId: DirectorKnowledgeCategoryId) {
  return DIRECTOR_KNOWLEDGE_CATEGORIES.find((category) => category.id === categoryId);
}

function normalizeSearchText(value: string): string {
  return value.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim();
}
