import type { DirectorWorkflowStep } from "./directorKnowledge.js";
import type { FilmWorkLanguage } from "./filmWorkLanguage.js";

export type DirectorWorkflowNarrative = Pick<
  DirectorWorkflowStep,
  "title" | "goal" | "actions" | "outputs" | "collaborators"
>;

export type FilmDirectorWorkflowCopy = {
  readonly railAria: string;
  readonly stepLabel: string;
  readonly directorDoes: string;
  readonly outputs: string;
  readonly collaborators: string;
  readonly terms: string;
  readonly steps: Readonly<Record<string, DirectorWorkflowNarrative>>;
};

export const FILM_DIRECTOR_WORKFLOW_COPY: Record<FilmWorkLanguage, FilmDirectorWorkflowCopy> = {
  en: {
    railAria: "Director workflow steps",
    stepLabel: "Step",
    directorDoes: "What the director does",
    outputs: "Working outputs",
    collaborators: "Works with",
    terms: "Terms to know at this step",
    steps: {
      "script-interpretation": { title: "Interpret the screenplay and define a point of view", goal: "Identify what the film is about dramatically, emotionally and formally before choosing solutions.", actions: ["Break the screenplay down into beats, objectives, obstacles and turning points.", "Define what the audience knows and the film's point of view.", "Separate theme from concrete playable action."], outputs: ["Director's notes", "Scene analysis", "Questions for the screenplay"], collaborators: ["Screenwriter", "Producer"] },
      "creative-system": { title: "Build the film's formal system", goal: "Translate the interpretation into rules for image, sound, performance, space and time.", actions: ["Define the tone and visual grammar.", "Establish principles for when the camera moves and when it remains still.", "Decide which contrasts should develop through the film."], outputs: ["Visual concept", "Tone and reference package", "Formal rules"], collaborators: ["Cinematographer", "Production designer", "Editor", "Sound designer"] },
      "casting-performance": { title: "Casting and performance strategy", goal: "Find actors and working methods that can carry the scenes' action and subtext.", actions: ["Define what the character does, not only what they feel.", "Run auditions, callbacks and chemistry reads.", "Plan how different actors receive adjustments."], outputs: ["Casting decisions", "Character actions", "Rehearsal plan"], collaborators: ["Casting director", "Actors", "Producer"] },
      "department-alignment": { title: "Align the departments", goal: "Ensure every department serves the same dramatic idea instead of working in parallel silos.", actions: ["Hold department meetings and a screenplay review.", "Connect design, camera, lighting and sound choices to the scene's function.", "Resolve cost, time and technical risk early."], outputs: ["Department brief", "Lookbook", "Technical tests", "Priority list"], collaborators: ["Cinematographer", "Production designer", "Costume designer", "Sound", "VFX", "1st AD"] },
      "location-tech-scout": { title: "Location and technical scout", goal: "Understand how space, light, sound, logistics and safety affect the scene's possibilities.", actions: ["Walk the scene physically in the space.", "Check sun direction, noise, power, rigging, access and camera positions.", "Update blocking and the shot plan to reflect real conditions."], outputs: ["Floor plan", "Camera positions", "Lighting and sound plan", "Risk list"], collaborators: ["1st AD", "Cinematographer", "Gaffer", "Grip", "Locations", "Sound"] },
      "blocking-rehearsal": { title: "Blocking and rehearsal", goal: "Find playable movement and power relationships before the camera locks the scene.", actions: ["Let the actors explore action and space.", "Place entrances, exits, eyelines and crosses.", "Adjust the camera to the performance rather than automatically forcing the performance to the camera."], outputs: ["Blocking plan", "Revised marks", "Performance tones", "Camera requirements"], collaborators: ["Actors", "Cinematographer", "Script supervisor", "1st AD"] },
      "shot-design": { title: "Shot design and coverage", goal: "Choose the images that actually express the scene's information, relationships and change.", actions: ["Choose masters, singles, inserts and reactions according to the scene's needs.", "Test the axis of action, screen direction and eyelines.", "Give every shot a dramatic function."], outputs: ["Shot list", "Storyboard when needed", "Lens list", "Coverage strategy"], collaborators: ["Cinematographer", "Storyboard artist", "Script supervisor", "1st AD"] },
      "schedule-priorities": { title: "Plan time and priorities", goal: "Protect the most important creative choices when the shooting day meets real constraints.", actions: ["Identify non-negotiable shots and performance needs.", "Plan alternative coverage.", "Agree the shooting order with the 1st AD and cinematographer."], outputs: ["Prioritised shot list", "Plan B", "Time estimates", "Pickup list"], collaborators: ["Producer", "1st AD", "Cinematographer", "Production manager"] },
      "shooting-floor": { title: "Lead the shoot", goal: "Bring performance, image, sound and production together into a clear result under time pressure.", actions: ["Communicate what the next take needs to improve.", "Give precise adjustments to actors and departments.", "Assess continuity, technical quality and whether the scene's turning point is visible."], outputs: ["Approved takes", "Director's notes", "Pickup needs", "Metadata and log"], collaborators: ["Actors", "Cinematographer", "1st AD", "Script supervisor", "Sound", "All department heads"] },
      "dailies-adaptation": { title: "Review dailies and adapt the plan", goal: "Check that the material works together and catch problems before the shoot has moved on.", actions: ["Assess performance, focus, exposure, coverage and sound.", "Compare the material with the scene's intention.", "Update upcoming shot lists and pickups."], outputs: ["Dailies notes", "Revised plans", "Pickup and VFX notes"], collaborators: ["Cinematographer", "Editor", "Script supervisor", "Producer"] },
      "picture-edit": { title: "Build the picture edit", goal: "Find the strongest rhythm, point of view and flow of information in the material that was shot.", actions: ["Start with the assembly and assess the scene's actual material.", "Work from dramatic function rather than preserving planned coverage.", "Lock picture only when structure and rhythm are under control."], outputs: ["Assembly", "Rough cut", "Fine cut", "Picture lock"], collaborators: ["Editor", "Producer", "VFX editor"] },
      "finish": { title: "Sound, music, VFX, colour and delivery", goal: "Complete the film's sensory whole and ensure the intention survives technical distribution.", actions: ["Spot sound, music and VFX with the departments.", "Approve ADR, Foley, sound design, mix and grading.", "Check masters in the relevant exhibition formats."], outputs: ["Locked sound mix", "Final VFX", "Colour grade", "DCP and other deliverables"], collaborators: ["Sound designer", "Composer", "VFX supervisor", "Colourist", "Post-production supervisor"] },
    },
  },
  nb: {
    railAria: "Regissørens arbeidstrinn",
    stepLabel: "Trinn",
    directorDoes: "Regissøren gjør",
    outputs: "Arbeidsresultater",
    collaborators: "Samarbeider med",
    terms: "Begreper du må kunne i dette trinnet",
    steps: {
      "script-interpretation": { title: "Tolke manus og definere ståsted", goal: "Finne hva filmen handler om dramatisk, emosjonelt og formelt før løsninger velges.", actions: ["Bryt manuset ned i beats, mål, hindringer og vendepunkter.", "Definer publikums kunnskap og filmens synsvinkel.", "Skill tema fra konkret spillbar handling."], outputs: ["Reginotat", "Sceneanalyse", "Spørsmål til manus"], collaborators: ["Manusforfatter", "Produsent"] },
      "creative-system": { title: "Bygge filmens formelle system", goal: "Oversette tolkningen til regler for bilde, lyd, skuespill, rom og tid.", actions: ["Definer tone og visuell grammatikk.", "Lag prinsipper for når kamera beveger seg og når det står stille.", "Bestem hvilke kontraster som skal utvikle seg gjennom filmen."], outputs: ["Visuelt konsept", "Tone- og referansepakke", "Formelle regler"], collaborators: ["Fotograf", "Produksjonsdesigner", "Klipper", "Lyddesigner"] },
      "casting-performance": { title: "Casting og prestasjonsstrategi", goal: "Finne skuespillere og arbeidsmåter som kan bære scenenes handling og undertekst.", actions: ["Definer hva rollen gjør, ikke bare hva den føler.", "Gjennomfør auditions, callbacks og chemistry reads.", "Planlegg hvordan ulike skuespillere mottar justeringer."], outputs: ["Castingvalg", "Rollehandlinger", "Prøveplan"], collaborators: ["Castingansvarlig", "Skuespillere", "Produsent"] },
      "department-alignment": { title: "Samordne avdelingene", goal: "Sørge for at alle fagavdelinger løser samme dramatiske idé uten å arbeide i parallelle siloer.", actions: ["Gjennomfør fagmøter og manusgjennomgang.", "Knytt design-, kamera-, lys- og lydvalg til scenens funksjon.", "Avklar kostnad, tid og teknisk risiko tidlig."], outputs: ["Avdelingsbrief", "Lookbook", "Tekniske tester", "Prioritetsliste"], collaborators: ["Fotograf", "Produksjonsdesigner", "Kostymedesigner", "Lyd", "VFX", "1. AD"] },
      "location-tech-scout": { title: "Location og teknisk befaring", goal: "Forstå hvordan rom, lys, lyd, logistikk og sikkerhet påvirker scenens muligheter.", actions: ["Gå scenen fysisk i rommet.", "Sjekk solretning, støy, strøm, rigg, adkomst og kameraposisjoner.", "Oppdater blocking og shotplan etter virkelige forhold."], outputs: ["Floor plan", "Kameraposisjoner", "Lys- og lydplan", "Risikoliste"], collaborators: ["1. AD", "Fotograf", "Gaffer", "Grip", "Location", "Lyd"] },
      "blocking-rehearsal": { title: "Blocking og prøve", goal: "Finne spillbare bevegelser og maktforhold før kameraet låser scenen.", actions: ["La skuespillerne undersøke handling og rom.", "Plasser innganger, utganger, blikk og kryssinger.", "Juster kamera etter prestasjonen, ikke omvendt som automatikk."], outputs: ["Blockingplan", "Reviderte marks", "Prestasjonstoner", "Kamerabehov"], collaborators: ["Skuespillere", "Fotograf", "Script supervisor", "1. AD"] },
      "shot-design": { title: "Shot design og dekning", goal: "Velge de bildene som faktisk uttrykker scenens informasjon, relasjoner og forandring.", actions: ["Bestem master, singles, inserts og reaksjoner ut fra scenens behov.", "Test akselinje, skjermretning og øyelinjer.", "Gi hvert bilde en dramatisk funksjon."], outputs: ["Shotlist", "Storyboard ved behov", "Linseliste", "Dekningsstrategi"], collaborators: ["Fotograf", "Storyboard artist", "Script supervisor", "1. AD"] },
      "schedule-priorities": { title: "Planlegge tid og prioriteringer", goal: "Beskytte de viktigste kreative valgene når opptaksdagen møter begrensninger.", actions: ["Marker ufravikelige bilder og prestasjonsbehov.", "Planlegg alternative dekninger.", "Avtal rekkefølge med 1. AD og fotograf."], outputs: ["Prioritert shotlist", "Plan B", "Tidsestimater", "Pickup-liste"], collaborators: ["Produsent", "1. AD", "Fotograf", "Produksjonsleder"] },
      "shooting-floor": { title: "Lede opptaket", goal: "Samle prestasjon, bilde, lyd og produksjon til ett tydelig resultat under tidspress.", actions: ["Kommuniser hva tagningen skal forbedre.", "Gi presise justeringer til skuespiller og avdeling.", "Vurder kontinuitet, teknisk kvalitet og om scenens vendepunkt er synlig."], outputs: ["Godkjente takes", "Reginotater", "Pickup-behov", "Metadata og logg"], collaborators: ["Skuespillere", "Fotograf", "1. AD", "Script supervisor", "Lyd", "Alle avdelingsledere"] },
      "dailies-adaptation": { title: "Se dailies og tilpasse planen", goal: "Kontrollere at materialet fungerer samlet og oppdage problemer før opptaket har gått videre.", actions: ["Vurder prestasjon, fokus, eksponering, dekning og lyd.", "Sammenlign materialet med scenens hensikt.", "Oppdater kommende shotlister og pickups."], outputs: ["Dailies-notater", "Korrigerte planer", "Pickup- og VFX-notater"], collaborators: ["Fotograf", "Klipper", "Script supervisor", "Produsent"] },
      "picture-edit": { title: "Bygge filmens bildeklipp", goal: "Finne den sterkeste rytmen, synsvinkelen og informasjonsflyten i det innspilte materialet.", actions: ["Start med assembly og vurder scenens faktiske materiale.", "Arbeid fra dramatisk funksjon fremfor å bevare planlagt dekning.", "Lås bilde først når struktur og rytme er kontrollert."], outputs: ["Assembly", "Rough cut", "Fine cut", "Picture lock"], collaborators: ["Klipper", "Produsent", "VFX editor"] },
      "finish": { title: "Lyd, musikk, VFX, farge og levering", goal: "Ferdigstille filmens sanselige helhet og sikre at intensjonen overlever teknisk distribusjon.", actions: ["Spot lyd, musikk og VFX med fagavdelingene.", "Godkjenn ADR, Foley, design, miks og grading.", "Kontroller mastere i relevante visningsformater."], outputs: ["Låst lydmiks", "Ferdige VFX", "Color grade", "DCP og øvrige leveranser"], collaborators: ["Lyddesigner", "Komponist", "VFX supervisor", "Colorist", "Post supervisor"] },
    },
  },
  fr: {
    railAria: "Étapes du workflow de réalisation",
    stepLabel: "Étape",
    directorDoes: "Le réalisateur fait",
    outputs: "Résultats de travail",
    collaborators: "Collabore avec",
    terms: "Termes à connaître à cette étape",
    steps: {
      "script-interpretation": { title: "Interpréter le scénario et définir le point de vue", goal: "Déterminer ce que le film raconte sur les plans dramatique, émotionnel et formel avant de choisir des solutions.", actions: ["Décomposer le scénario en beats, objectifs, obstacles et tournants.", "Définir ce que sait le public et le point de vue du film.", "Distinguer le thème de l’action concrète et jouable."], outputs: ["Note de réalisation", "Analyse de scène", "Questions sur le scénario"], collaborators: ["Scénariste", "Producteur"] },
      "creative-system": { title: "Construire le système formel du film", goal: "Traduire l’interprétation en règles pour l’image, le son, le jeu, l’espace et le temps.", actions: ["Définir le ton et la grammaire visuelle.", "Établir des principes pour décider quand la caméra bouge et quand elle reste fixe.", "Déterminer les contrastes qui doivent évoluer au fil du film."], outputs: ["Concept visuel", "Dossier de ton et de références", "Règles formelles"], collaborators: ["Directeur de la photographie", "Chef décorateur", "Monteur", "Concepteur sonore"] },
      "casting-performance": { title: "Casting et stratégie de jeu", goal: "Trouver les interprètes et les méthodes de travail capables de porter l’action et le sous-texte des scènes.", actions: ["Définir ce que fait le personnage, pas seulement ce qu’il ressent.", "Mener auditions, callbacks et essais d’alchimie.", "Prévoir comment chaque interprète reçoit les ajustements."], outputs: ["Choix de casting", "Actions du personnage", "Plan de répétitions"], collaborators: ["Directeur de casting", "Comédiens", "Producteur"] },
      "department-alignment": { title: "Aligner les départements", goal: "Veiller à ce que tous les départements servent la même idée dramatique sans travailler en silos parallèles.", actions: ["Tenir des réunions de département et une revue du scénario.", "Relier les choix de décor, caméra, lumière et son à la fonction de la scène.", "Arbitrer tôt les coûts, le temps et les risques techniques."], outputs: ["Brief des départements", "Lookbook", "Essais techniques", "Liste de priorités"], collaborators: ["Directeur de la photographie", "Chef décorateur", "Créateur de costumes", "Son", "VFX", "1er assistant réalisateur"] },
      "location-tech-scout": { title: "Repérage et visite technique", goal: "Comprendre comment l’espace, la lumière, le son, la logistique et la sécurité influencent les possibilités de la scène.", actions: ["Parcourir physiquement la scène dans le lieu.", "Vérifier la course du soleil, le bruit, l’alimentation, les accroches, les accès et les positions caméra.", "Mettre à jour le blocking et le plan de tournage selon les conditions réelles."], outputs: ["Plan au sol", "Positions caméra", "Plan lumière et son", "Liste des risques"], collaborators: ["1er assistant réalisateur", "Directeur de la photographie", "Chef électricien", "Machiniste", "Régie / repérages", "Son"] },
      "blocking-rehearsal": { title: "Blocking et répétition", goal: "Trouver des déplacements jouables et les rapports de force avant que la caméra ne fige la scène.", actions: ["Laisser les comédiens explorer l’action et l’espace.", "Placer les entrées, sorties, regards et croisements.", "Adapter la caméra au jeu plutôt que d’imposer automatiquement le jeu à la caméra."], outputs: ["Plan de blocking", "Marques révisées", "Tonalités de jeu", "Besoins caméra"], collaborators: ["Comédiens", "Directeur de la photographie", "Scripte", "1er assistant réalisateur"] },
      "shot-design": { title: "Conception des plans et découpage", goal: "Choisir les plans qui expriment réellement l’information, les relations et l’évolution de la scène.", actions: ["Choisir plans maîtres, plans individuels, inserts et réactions selon les besoins de la scène.", "Tester l’axe d’action, la direction à l’écran et les regards.", "Donner à chaque plan une fonction dramatique."], outputs: ["Liste de plans", "Storyboard si nécessaire", "Liste d’optiques", "Stratégie de découpage"], collaborators: ["Directeur de la photographie", "Storyboarder", "Scripte", "1er assistant réalisateur"] },
      "schedule-priorities": { title: "Planifier le temps et les priorités", goal: "Protéger les choix créatifs essentiels lorsque la journée de tournage rencontre ses contraintes réelles.", actions: ["Identifier les plans et besoins de jeu non négociables.", "Prévoir des découpages alternatifs.", "Convenir de l’ordre de tournage avec le 1er assistant réalisateur et le directeur de la photographie."], outputs: ["Liste de plans priorisée", "Plan B", "Estimations de temps", "Liste de reprises"], collaborators: ["Producteur", "1er assistant réalisateur", "Directeur de la photographie", "Directeur de production"] },
      "shooting-floor": { title: "Diriger le tournage", goal: "Réunir jeu, image, son et production dans un résultat clair sous la pression du temps.", actions: ["Communiquer ce que la prise suivante doit améliorer.", "Donner des ajustements précis aux comédiens et aux départements.", "Évaluer la continuité, la qualité technique et la lisibilité du tournant de la scène."], outputs: ["Prises validées", "Notes de réalisation", "Besoins de reprises", "Métadonnées et rapport"], collaborators: ["Comédiens", "Directeur de la photographie", "1er assistant réalisateur", "Scripte", "Son", "Tous les chefs de département"] },
      "dailies-adaptation": { title: "Visionner les rushes et adapter le plan", goal: "Vérifier que le matériel fonctionne dans son ensemble et repérer les problèmes avant que le tournage n’avance.", actions: ["Évaluer le jeu, le point, l’exposition, le découpage et le son.", "Comparer le matériel à l’intention de la scène.", "Mettre à jour les prochaines listes de plans et les reprises."], outputs: ["Notes de rushes", "Plans révisés", "Notes de reprises et VFX"], collaborators: ["Directeur de la photographie", "Monteur", "Scripte", "Producteur"] },
      "picture-edit": { title: "Construire le montage image", goal: "Trouver le rythme, le point de vue et la circulation de l’information les plus forts dans le matériel tourné.", actions: ["Commencer par l’assemblage et évaluer le matériel réel de la scène.", "Travailler à partir de la fonction dramatique plutôt que de préserver le découpage prévu.", "Verrouiller l’image seulement lorsque structure et rythme sont maîtrisés."], outputs: ["Assemblage", "Premier montage", "Montage affiné", "Verrouillage image"], collaborators: ["Monteur", "Producteur", "Monteur VFX"] },
      "finish": { title: "Son, musique, VFX, étalonnage et livraison", goal: "Achever l’unité sensorielle du film et veiller à ce que l’intention survive à la distribution technique.", actions: ["Faire les séances de spotting son, musique et VFX avec les départements.", "Valider ADR, Foley, design sonore, mixage et étalonnage.", "Contrôler les masters dans les formats de projection pertinents."], outputs: ["Mixage son verrouillé", "VFX finalisés", "Étalonnage", "DCP et autres livrables"], collaborators: ["Concepteur sonore", "Compositeur", "Superviseur VFX", "Étalonneur", "Superviseur de postproduction"] },
    },
  },
  pt: {
    railAria: "Etapas do fluxo de trabalho de realização",
    stepLabel: "Etapa",
    directorDoes: "O realizador faz",
    outputs: "Resultados de trabalho",
    collaborators: "Colabora com",
    terms: "Termos a dominar nesta etapa",
    steps: {
      "script-interpretation": { title: "Interpretar o argumento e definir o ponto de vista", goal: "Identificar o que o filme exprime em termos dramáticos, emocionais e formais antes de escolher soluções.", actions: ["Decompor o argumento em beats, objetivos, obstáculos e pontos de viragem.", "Definir o que o público sabe e o ponto de vista do filme.", "Distinguir o tema da ação concreta e interpretável."], outputs: ["Nota de realização", "Análise de cena", "Questões sobre o argumento"], collaborators: ["Argumentista", "Produtor"] },
      "creative-system": { title: "Construir o sistema formal do filme", goal: "Traduzir a interpretação em regras para imagem, som, interpretação, espaço e tempo.", actions: ["Definir o tom e a gramática visual.", "Estabelecer princípios para decidir quando a câmara se move e quando fica estática.", "Determinar os contrastes que devem evoluir ao longo do filme."], outputs: ["Conceito visual", "Dossier de tom e referências", "Regras formais"], collaborators: ["Diretor de fotografia", "Diretor de arte", "Montador", "Designer de som"] },
      "casting-performance": { title: "Casting e estratégia de interpretação", goal: "Encontrar atores e métodos de trabalho capazes de sustentar a ação e o subtexto das cenas.", actions: ["Definir o que a personagem faz, não apenas o que sente.", "Realizar audições, callbacks e provas de química.", "Planear como diferentes atores recebem ajustamentos."], outputs: ["Escolhas de casting", "Ações da personagem", "Plano de ensaios"], collaborators: ["Diretor de casting", "Atores", "Produtor"] },
      "department-alignment": { title: "Alinhar os departamentos", goal: "Garantir que todos os departamentos servem a mesma ideia dramática sem trabalhar em silos paralelos.", actions: ["Realizar reuniões de departamento e uma revisão do argumento.", "Ligar as escolhas de arte, câmara, luz e som à função da cena.", "Resolver cedo custos, tempo e risco técnico."], outputs: ["Brief dos departamentos", "Lookbook", "Testes técnicos", "Lista de prioridades"], collaborators: ["Diretor de fotografia", "Diretor de arte", "Figurinista", "Som", "VFX", "1.º assistente de realização"] },
      "location-tech-scout": { title: "Local de rodagem e visita técnica", goal: "Compreender como espaço, luz, som, logística e segurança condicionam as possibilidades da cena.", actions: ["Percorrer fisicamente a cena no espaço.", "Verificar direção do sol, ruído, alimentação elétrica, rigging, acessos e posições de câmara.", "Atualizar o blocking e o plano de rodagem segundo as condições reais."], outputs: ["Planta", "Posições de câmara", "Plano de luz e som", "Lista de riscos"], collaborators: ["1.º assistente de realização", "Diretor de fotografia", "Chefe eletricista", "Maquinista", "Produção de locais", "Som"] },
      "blocking-rehearsal": { title: "Blocking e ensaio", goal: "Encontrar movimentos interpretáveis e relações de poder antes de a câmara fixar a cena.", actions: ["Deixar os atores explorar a ação e o espaço.", "Definir entradas, saídas, linhas de olhar e cruzamentos.", "Ajustar a câmara à interpretação em vez de impor automaticamente a interpretação à câmara."], outputs: ["Plano de blocking", "Marcas revistas", "Tons de interpretação", "Necessidades de câmara"], collaborators: ["Atores", "Diretor de fotografia", "Responsável pela continuidade", "1.º assistente de realização"] },
      "shot-design": { title: "Conceção dos planos e cobertura", goal: "Escolher os planos que exprimem realmente a informação, as relações e a mudança da cena.", actions: ["Escolher plano master, planos individuais, inserts e reações segundo as necessidades da cena.", "Testar o eixo de ação, a direção no ecrã e as linhas de olhar.", "Dar a cada plano uma função dramática."], outputs: ["Lista de planos", "Storyboard quando necessário", "Lista de objetivas", "Estratégia de cobertura"], collaborators: ["Diretor de fotografia", "Artista de storyboard", "Responsável pela continuidade", "1.º assistente de realização"] },
      "schedule-priorities": { title: "Planear tempo e prioridades", goal: "Proteger as escolhas criativas mais importantes quando o dia de rodagem encontra limitações reais.", actions: ["Identificar planos e necessidades de interpretação inegociáveis.", "Planear coberturas alternativas.", "Acordar a ordem de rodagem com o 1.º assistente de realização e o diretor de fotografia."], outputs: ["Lista de planos priorizada", "Plano B", "Estimativas de tempo", "Lista de pickups"], collaborators: ["Produtor", "1.º assistente de realização", "Diretor de fotografia", "Diretor de produção"] },
      "shooting-floor": { title: "Dirigir a rodagem", goal: "Reunir interpretação, imagem, som e produção num resultado claro sob pressão de tempo.", actions: ["Comunicar o que a próxima take deve melhorar.", "Dar ajustamentos precisos aos atores e aos departamentos.", "Avaliar continuidade, qualidade técnica e se o ponto de viragem da cena está visível."], outputs: ["Takes aprovadas", "Notas de realização", "Necessidades de pickups", "Metadados e relatório"], collaborators: ["Atores", "Diretor de fotografia", "1.º assistente de realização", "Responsável pela continuidade", "Som", "Todos os chefes de departamento"] },
      "dailies-adaptation": { title: "Rever os rushes e adaptar o plano", goal: "Verificar se o material funciona como um todo e detetar problemas antes de a rodagem avançar.", actions: ["Avaliar interpretação, foco, exposição, cobertura e som.", "Comparar o material com a intenção da cena.", "Atualizar as próximas listas de planos e pickups."], outputs: ["Notas de rushes", "Planos revistos", "Notas de pickups e VFX"], collaborators: ["Diretor de fotografia", "Montador", "Responsável pela continuidade", "Produtor"] },
      "picture-edit": { title: "Construir a montagem de imagem", goal: "Encontrar o ritmo, o ponto de vista e o fluxo de informação mais fortes no material rodado.", actions: ["Começar pela montagem inicial e avaliar o material real da cena.", "Trabalhar a partir da função dramática em vez de preservar a cobertura planeada.", "Fechar a imagem apenas quando estrutura e ritmo estiverem controlados."], outputs: ["Montagem inicial", "Primeiro corte", "Montagem afinada", "Imagem fechada"], collaborators: ["Montador", "Produtor", "Montador de VFX"] },
      "finish": { title: "Som, música, VFX, cor e entrega", goal: "Concluir a unidade sensorial do filme e garantir que a intenção sobrevive à distribuição técnica.", actions: ["Fazer spotting de som, música e VFX com os departamentos.", "Aprovar ADR, Foley, design de som, mistura e correção de cor.", "Verificar masters nos formatos de exibição relevantes."], outputs: ["Mistura final de som", "VFX finalizados", "Correção de cor", "DCP e restantes entregáveis"], collaborators: ["Designer de som", "Compositor", "Supervisor de VFX", "Colorista", "Supervisor de pós-produção"] },
    },
  },
};

export function getDirectorWorkflowNarrative(
  language: FilmWorkLanguage,
  step: DirectorWorkflowStep,
): DirectorWorkflowNarrative {
  return FILM_DIRECTOR_WORKFLOW_COPY[language].steps[step.id] ?? {
    title: step.title,
    goal: step.goal,
    actions: step.actions,
    outputs: step.outputs,
    collaborators: step.collaborators,
  };
}
