import {
  DIRECTOR_APPLIED_LEARNING_GUIDES,
  type DirectorAppliedLearningGuide,
} from "./directorAppliedLearning.js";
import type { FilmWorkLanguage } from "./filmWorkLanguage.js";

const canonicalNorwegianTitles = Object.fromEntries(
  DIRECTOR_APPLIED_LEARNING_GUIDES.map((guide) => [guide.id, guide.norwegianLabel]),
) as Readonly<Record<string, string>>;

export const FILM_DIRECTOR_PRACTICE_GUIDE_TITLES: Record<FilmWorkLanguage, Readonly<Record<string, string>>> = {
  en: {
    "brief:sceneTitle": "Scene title",
    "brief:sceneContext": "Scene context",
    "brief:sceneObjective": "Scene objective",
    "brief:audienceEffect": "Audience effect",
    "brief:conflictTurn": "Conflict and turn",
    "brief:formalStrategy": "Formal strategy",
    "brief:blocking": "Blocking",
    "brief:performanceDirection": "Performance direction",
    "brief:productionDesign": "Production design",
    "brief:shotPlan": "Shot plan",
    "brief:cameraMovementLenses": "Camera, movement and lenses",
    "brief:lightingPalette": "Lighting and palette",
    "brief:editingRhythm": "Editing rhythm",
    "brief:soundStrategy": "Sound strategy",
    "brief:practicalConstraints": "Practical constraints",
    "brief:proofOfIntent": "Proof of directing intent",
    "shot:title": "Shot title",
    "shot:shotSize": "Shot size",
    "shot:cameraPosition": "Camera position",
    "shot:movement": "Camera movement",
    "shot:lens": "Lens and focus",
    "shot:subjectAction": "Action and blocking",
    "shot:dramaticPurpose": "Dramatic purpose",
    "shot:sound": "Sound and dialogue priority",
    "shot:estimatedDuration": "Estimated duration",
  },
  nb: canonicalNorwegianTitles,
  fr: {
    "brief:sceneTitle": "Titre de la scène",
    "brief:sceneContext": "Contexte de la scène",
    "brief:sceneObjective": "Objectif de la scène",
    "brief:audienceEffect": "Effet sur le public",
    "brief:conflictTurn": "Conflit et bascule",
    "brief:formalStrategy": "Stratégie formelle",
    "brief:blocking": "Placement et déplacements",
    "brief:performanceDirection": "Direction d’acteurs",
    "brief:productionDesign": "Direction artistique",
    "brief:shotPlan": "Plan de découpage",
    "brief:cameraMovementLenses": "Caméra, mouvement et focales",
    "brief:lightingPalette": "Lumière et palette",
    "brief:editingRhythm": "Rythme du montage",
    "brief:soundStrategy": "Stratégie sonore",
    "brief:practicalConstraints": "Contraintes pratiques",
    "brief:proofOfIntent": "Preuve de l’intention de réalisation",
    "shot:title": "Intitulé du plan",
    "shot:shotSize": "Échelle de plan",
    "shot:cameraPosition": "Position de caméra",
    "shot:movement": "Mouvement de caméra",
    "shot:lens": "Focale et mise au point",
    "shot:subjectAction": "Action et placement",
    "shot:dramaticPurpose": "Fonction dramatique",
    "shot:sound": "Priorité du son et des dialogues",
    "shot:estimatedDuration": "Durée estimée",
  },
  pt: {
    "brief:sceneTitle": "Título da cena",
    "brief:sceneContext": "Contexto da cena",
    "brief:sceneObjective": "Objetivo da cena",
    "brief:audienceEffect": "Efeito no público",
    "brief:conflictTurn": "Conflito e viragem",
    "brief:formalStrategy": "Estratégia formal",
    "brief:blocking": "Marcação cénica",
    "brief:performanceDirection": "Direção de atores",
    "brief:productionDesign": "Direção de arte",
    "brief:shotPlan": "Planificação dos planos",
    "brief:cameraMovementLenses": "Câmara, movimento e objetivas",
    "brief:lightingPalette": "Iluminação e paleta",
    "brief:editingRhythm": "Ritmo de montagem",
    "brief:soundStrategy": "Estratégia sonora",
    "brief:practicalConstraints": "Condicionantes práticas",
    "brief:proofOfIntent": "Prova da intenção de realização",
    "shot:title": "Título do plano",
    "shot:shotSize": "Escala do plano",
    "shot:cameraPosition": "Posição da câmara",
    "shot:movement": "Movimento de câmara",
    "shot:lens": "Objetiva e foco",
    "shot:subjectAction": "Ação e marcação",
    "shot:dramaticPurpose": "Função dramática",
    "shot:sound": "Prioridade do som e do diálogo",
    "shot:estimatedDuration": "Duração estimada",
  },
};

export function getFilmDirectorPracticeGuideTitle(language: FilmWorkLanguage, guide: DirectorAppliedLearningGuide): string {
  return FILM_DIRECTOR_PRACTICE_GUIDE_TITLES[language][guide.id] ?? guide.norwegianLabel;
}
