import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterThreeMovementThree: readonly FilmHistoryBookSection[] = [
  {
    id: "ch3_parallel_action_problem",
    title: "11. When several spaces matter at once",
    sourceIds: ["ch3_loc_lonely_villa", "ch3_gunning_lonely_villa", "ch3_ucp_griffith"],
    paragraphs: [
      "By the end of the 1900s, one of the central narrative problems was no longer merely how to link one action to the next, but how to make several separated actions matter at the same time. A threatened family, an approaching attacker and a distant rescuer can all be causally relevant before they occupy the same space. To sustain that situation, a film has to teach the spectator that a cut away does not abandon the previous scene. Instead, the absent action continues to exist as part of the same narrative present. Parallel action therefore demands memory, expectation and confidence in simultaneity.",
      "This principle did not appear in one instant. Earlier chase, rescue and multi-scene films already asked viewers to connect separated spaces, and international filmmakers experimented with forms of alternation before the Biograph period. What changes is the density and persistence with which the relation can be maintained. The spectator can be made to wait across repeated returns, compare progress in different places and anticipate a point of convergence. Editing becomes a way to distribute dramatic information among spaces whose connection is temporal and causal even before it becomes physical.",
      "The shift also has production consequences. Separate locations or sets must be designed so the audience can recognize them instantly on return. Performance has to carry unresolved action across interruptions. Props or communication technologies can create narrative bridges. The order and frequency of cuts become part of suspense construction. The film is no longer simply a chain of complete tableaux; it can become a system of partially suspended actions that borrow urgency from one another. The Lonely Villa provides the chapter's clearest late-period case because it turns precisely that coordination problem into the basis of its home-invasion melodrama."
    ]
  },
  {
    id: "ch3_lonely_villa_three_lines",
    title: "12. The Lonely Villa: three lines of danger",
    sourceIds: ["ch3_loc_lonely_villa", "ch3_afi_lonely_villa", "ch3_moma_lonely_villa"],
    paragraphs: [
      "The Lonely Villa organizes suspense among three intelligible lines of action: the family isolated inside the house, the burglars forcing their way toward them, and the husband trying to overcome distance and return with help. Library of Congress documentation identifies the 1909 Biograph production, D. W. Griffith's direction, G. W. Bitzer and Arthur Marvin's camera work and filming in Fort Lee and Biograph's New York studio. AFI independently preserves the release context and a synopsis built around false information, burglary, telephone discovery and rescue. The production therefore combines studio and location work with a story whose dramatic force depends on their being mentally connected.",
      "The key is not the mere existence of alternating cuts. The family line has its own escalating threat; the burglars have a separate sequence of actions; the husband's delay and return create a third clock. Each cut changes what the spectator knows about the others. Returning to the house after seeing the husband delayed makes the family's danger feel longer. Returning to the husband after seeing the burglars advance makes distance more urgent. Parallel editing becomes dramatic because every line modifies the meaning of time in the others.",
      "This coordination is a production design and performance problem as much as an editorial one. The villa must remain spatially readable; doors, rooms and thresholds have to support escalating invasion. The husband's route must remain distinct from the family interior. Performers have to sustain emotional continuity across scenes that will be interrupted by other actions. The final rescue works because the film has spent time constructing separation. Convergence is satisfying only after distance has been made legible. In that sense, The Lonely Villa gathers several developments traced earlier in the chapter—linked space, causal action, route, spectator memory—into a more sustained integrated system."
    ]
  },
  {
    id: "ch3_telephone_bridge",
    title: "13. The telephone joins spaces before bodies can",
    sourceIds: ["ch3_loc_lonely_villa", "ch3_gunning_lonely_villa"],
    paragraphs: [
      "The telephone in The Lonely Villa is more than a prop. It is a narrative technology that allows separated spaces to become dramatically present to one another before characters can travel between them. Tom Gunning's study of the film and its de Lorde lineage places communication technology at the center of the melodramatic system. The family can communicate danger across distance; the husband can know what is happening without yet being able to intervene; the line can be cut, converting connection into renewed isolation. The telephone therefore gives editing a material counterpart inside the story.",
      "This is historically revealing because cinema and telecommunications solve related problems of distance in different ways. The telephone transmits information while bodies remain apart. Editing places images of separated bodies next to one another while the spectator infers simultaneity. When the film alternates between caller and receiver, the narrative can make a spatial gap feel active rather than empty. Communication becomes suspense because knowledge travels faster than rescue. A cut can therefore express not only 'meanwhile' but also the painful difference between knowing and arriving.",
      "The telephone example also helps resist a purely formalist history. Parallel editing is not just a pattern of alternating strips. Its dramatic intelligibility depends on story devices, technologies, performance and social expectations. A communication network gives characters reasons to know about off-screen events; transport delay gives rescue a measurable obstacle; the home-invasion plot gives alternation emotional stakes. Narrative integration emerges when these systems reinforce one another. The film's form is powerful because the production coordinates the material world of the story with the temporal logic of the edit."
    ]
  },
  {
    id: "ch3_griffith_consolidator_not_inventor",
    title: "14. Consolidation is not invention",
    sourceIds: ["ch3_ucp_griffith", "ch3_uillinois_griffith", "ch3_bfi_innovators"],
    paragraphs: [
      "D. W. Griffith's Biograph work is indispensable to the history of narrative cinema, but its importance becomes less accurate when translated into a list of devices he supposedly invented. University of California Press and University of Illinois Press scholarship places his work inside wider industrial, social and international developments. Intercutting, camera movement, closer views and scene construction had precedents and contemporaries. Griffith's historical significance lies substantially in the sustained refinement, combination and repetition of techniques across a large body of films produced within an increasingly organized company system.",
      "The difference between invention and consolidation matters because it changes what we look for. An invention story asks who used a device first. A production history asks how reliably the device could be integrated into stories, how often it could be repeated, how performers and camera operators adapted to it, how audiences learned its cues, and how a company organized work around it. The Lonely Villa is valuable because its parallel action is not an isolated trick. It demonstrates a system whose dramatic logic can be sustained across a reel and coordinated with communication, travel and rescue.",
      "This wider framing also restores the films that disappear when history is written backward from Griffith. Smith's analytical inserts, Williamson's linked spaces, Méliès's tableau succession, Porter's multi-scene action, Hepworth's route clarity and Zecca's represented memory are not merely primitive steps toward Biograph. They are distinct solutions circulating within a transnational field. Griffith and Biograph become more historically interesting, not less, when understood as powerful organizers of an already active repertoire. The chapter therefore uses 'consolidator' deliberately: it recognizes scale and influence without converting complex collective development into personal invention mythology."
    ]
  },
  {
    id: "ch3_transition_to_industry_scale",
    title: "15. When stories grow, institutions have to grow with them",
    sourceIds: ["ch3_pathe_history", "ch3_fondation_pathe", "ch3_loc_great_train", "ch3_loc_lonely_villa"],
    paragraphs: [
      "By 1912, the narrative problems traced through this chapter increasingly intersected with industrial scale. Longer and more complex films required dependable access to performers, locations, sets, equipment, negative stock, processing, duplication, distribution and exhibition. Pathé's organized production service, Edison's expanding fiction catalogue, Hepworth's need to replace worn negatives and Biograph's studio-location workflow all show that formal development depended on institutions capable of reproducing production. A more integrated story was not only an artistic achievement. It was also a logistical object that had to be made, copied, sold or rented and shown repeatedly.",
      "This perspective clarifies the relationship between film form and business. Continuity devices can reduce confusion when stories become longer; recognizable performers can help audiences follow recurring genres and companies; standardized production routines can make complex staging repeatable; distribution systems can reward films with enough length and narrative appeal to anchor programmes. None of these developments follows mechanically from the others, but they create pressures that increasingly bind narrative organization to corporate organization. The more a film asks a spectator to remember, compare and anticipate, the more production has to deliver consistent material from scene to scene and copy to copy.",
      "That is the point at which Chapter 3 hands the story to Chapter 4. The next problem is not simply a new editing device. It is how companies, patent conflicts, exchanges, rental, theatres, stars and the transition toward longer films reorganize what can be produced and circulated. Chapter 3 has shown that cinema learned many ways to construct a story from discontinuous pieces. Chapter 4 asks what happens when those increasingly ambitious stories become products inside larger industrial systems. Form does not vanish from the history; it changes scale because the institutions supporting it change scale too."
    ]
  }
];
