import type { FilmHistoryBookChapter, FilmHistoryBookSource } from "./filmHistoryBook.js";
import { filmHistoryChapterTwoMovementOne } from "./filmHistoryChapterTwoMovementOne.js";
import { filmHistoryChapterTwoMovementTwo } from "./filmHistoryChapterTwoMovementTwo.js";
import { filmHistoryChapterTwoMovementThree } from "./filmHistoryChapterTwoMovementThree.js";

export const filmHistoryChapterTwoSources: readonly FilmHistoryBookSource[] = [
  { id: "nsm_short_history_cinema", title: "A very short history of cinema", publisher: "National Science and Media Museum", url: "https://www.scienceandmediamuseum.org.uk/objects-and-stories/very-short-history-of-cinema" },
  { id: "nsm_lumiere", title: "The Lumière brothers: pioneers of cinema and colour photography", publisher: "National Science and Media Museum", url: "https://blog.scienceandmediamuseum.org.uk/the-lumiere-brothers-pioneers-of-cinema-and-colour-photography/" },
  { id: "loc_vitascope_shift", title: "Shift to Projectors and the Vitoscope", publisher: "Library of Congress", url: "https://www.loc.gov/collections/edison-company-motion-pictures-and-sound-recordings/articles-and-essays/history-of-edison-motion-pictures/shift-to-projectors-and-the-vitoscope/" },
  { id: "loc_variety_stage_context", title: "Content and Historical Context", publisher: "Library of Congress", url: "https://www.loc.gov/collections/variety-stage-sound-recordings-and-motion-pictures/articles-and-essays/content-and-historical-context/" },
  { id: "loc_koster_bial_treasures", title: "Koster and Bial — American Treasures", publisher: "Library of Congress", url: "https://www.loc.gov/exhibits/treasures/tr22c.html" },
  { id: "loc_edison_catalogue_context", title: "Inventing Entertainment: The Early Motion Pictures and Sound Recordings of the Edison Companies", publisher: "Library of Congress", url: "https://www.loc.gov/collections/edison-company-motion-pictures-and-sound-recordings/" },
  { id: "loc_vitascope_poster", title: "Vitascope poster", publisher: "Library of Congress", url: "https://www.loc.gov/item/2003689462/" },
  { id: "loc_actuality_film", title: "The Actuality Film", publisher: "Library of Congress", url: "https://www.loc.gov/collections/variety-stage-sound-recordings-and-motion-pictures/articles-and-essays/actuality-film/" },
  { id: "loc_fictional_films_dominate", title: "Fictional Films Dominate", publisher: "Library of Congress", url: "https://www.loc.gov/collections/edison-company-motion-pictures-and-sound-recordings/articles-and-essays/history-of-edison-motion-pictures/fictional-films-dominate/" },
  { id: "loc_may_irwin_kiss", title: "The May Irwin kiss", publisher: "Library of Congress", url: "https://www.loc.gov/item/00694131/" },
  { id: "loc_great_train_robbery", title: "The Great Train Robbery", publisher: "Library of Congress", url: "https://www.loc.gov/item/00694220/" },
  { id: "loc_corbett_fitzsimmons", title: "Corbett-Fitzsimmons fight — excerpts", publisher: "Library of Congress", url: "https://www.loc.gov/item/2023602024/" },
  { id: "loc_uncle_josh", title: "Uncle Josh at the moving picture show", publisher: "Library of Congress", url: "https://www.loc.gov/item/00694324/" },
  { id: "loc_edison_comedy", title: "Comedy — Edison motion pictures", publisher: "Library of Congress", url: "https://www.loc.gov/collections/edison-company-motion-pictures-and-sound-recordings/articles-and-essays/genres/comedy/" },
  { id: "cinematheque_machine_cinema", title: "De Méliès à la 3D: La Machine cinéma", publisher: "La Cinémathèque française", url: "https://www.cinematheque.fr/expositions-virtuelles/guide-expo-machine/index.htm" },
  { id: "cinematheque_1896_expansion", title: "1896 / 2016: expansion du spectacle cinématographique", publisher: "La Cinémathèque française", url: "https://www.cinematheque.fr/intervention/577.html" },
  { id: "bfi_mitchell_kenyon_collection", title: "Mitchell & Kenyon's Edwardian Britain", publisher: "BFI National Archive", url: "https://replay.bfi.org.uk/collection/430" },
  { id: "bfi_electric_edwardians", title: "Electric Edwardians: The Films of Mitchell and Kenyon", publisher: "BFI", url: "https://shop.bfi.org.uk/electric-edwardians-the-films-of-mitchell-and-kenyon/" },
  { id: "bfi_browns_atlas", title: "Employees Leaving Brown's Atlas Works, Sheffield (1901)", publisher: "British Film Institute", url: "https://player.bfi.org.uk/free/film/watch-employees-leaving-browns-atlas-works-sheffield-1901-1901-online" },
  { id: "bfi_sedgwick_showfront", title: "Sedgwick's Bioscope Showfront at Pendlebury Wakes", publisher: "BFI Replay", url: "https://replay.bfi.org.uk/video/227/23391d66-35e9-512a-8271-311d28f601aa" },
  { id: "bfi_trip_to_the_moon", title: "A Trip to the Moon", publisher: "British Film Institute", url: "https://player.bfi.org.uk/free/film/watch-a-trip-to-the-moon-1902-online" },
  { id: "sheffield_browns_context", title: "Introducing our Writer in Residence, Désirée Reynolds", publisher: "Sheffield Libraries / Sheffield City Archives", url: "https://shefflibraries.blogspot.com/2021/07/introducing-our-writer-in-residence.html" },
  { id: "nsm_corbett_fitzsimmons", title: "Corbett vs. Fitzsimmons, the fight of the century and the earliest feature film", publisher: "National Science and Media Museum", url: "https://blog.scienceandmediamuseum.org.uk/corbett-fitzsimmons-fight-film-fragment/" },
  { id: "ucp_streible_fight_pictures", title: "Fight Pictures: A History of Boxing and Early Cinema — The Corbett-Fitzsimmons Fight", publisher: "University of California Press / JSTOR", url: "https://www.jstor.org/stable/10.1525/j.ctt1pnd60.9" },
  { id: "afi_corbett_fitzsimmons", title: "Corbett and Fitzsimmons Fight", publisher: "American Film Institute", url: "https://catalog.afi.com/Film/28825-CORBETT-AND-FITZSIMMONS-FIGHT" },
  { id: "afi_uncle_josh", title: "Uncle Josh at the Moving Picture Show", publisher: "American Film Institute", url: "https://catalog.afi.com/Film/28980-UNCLE-JOSH-AT-THE-MOVING-PICTURE-SHOW" },
  { id: "rutgers_viewing_positions", title: "Viewing Positions: Ways of Seeing Film", publisher: "Rutgers University Press", url: "https://www.rutgersuniversitypress.org/viewing-positions/9780813521336" },
];

export const filmHistoryChapterTwo: FilmHistoryBookChapter = {
  id: "projection-programmes-audiences",
  number: 2,
  title: "Projection, programmes and audiences",
  period: "1895–1907",
  summary: "Cinema became a recurring public medium not simply because films could be made and projected, but because exhibitors assembled programmes, adapted presentation to venues, mobilized publicity and live performance, cultivated local and event audiences, and created recurring demand that reshaped production and distribution.",
  status: "full",
  learningObjectives: [
    "Compare music halls, fairgrounds, travelling shows and storefront theatres as distinct early exhibition systems.",
    "Explain why the programme, rather than the individual film alone, was a central unit of early public cinema.",
    "Distinguish the material film from the variable exhibition event built around projection, sound, explanation and audience response.",
    "Explain exhibitor and showman agency in film selection, sequencing, publicity, venue design and live presentation.",
    "Use The Corbett–Fitzsimmons Fight to connect capture technology, proprietary projection, territorial rights, commentary and ticket economics.",
    "Analyze local actuality as a recognition economy shaped by staging and anticipated audiences rather than as transparent reality.",
    "Evaluate evidence about early spectators without treating comic films or later train-panic legends as direct records of universal audience behavior.",
    "Explain how recurring exhibition demand and the rise of film-dedicated venues created pressure for dependable production, circulation and increasingly varied film supply.",
  ],
  keyTerms: [
    "exhibitor",
    "programme",
    "projection",
    "music hall",
    "vaudeville",
    "fairground cinema",
    "bioscope",
    "showfront",
    "actuality",
    "local film",
    "event cinema",
    "territorial rights",
    "live commentary",
    "accompaniment",
    "spectatorship",
    "rube comedy",
    "film catalogue",
    "storefront theatre",
    "nickelodeon",
    "circulation",
  ],
  sections: [
    ...filmHistoryChapterTwoMovementOne,
    ...filmHistoryChapterTwoMovementTwo,
    ...filmHistoryChapterTwoMovementThree,
  ],
  filmReferences: [
    { title: "Workers Leaving the Lumière Factory", year: 1895, role: "anchor_film", atlasDecision: "use_existing_atlas_case", atlasScenarioId: "scenario_workers_leaving_lumiere_factory_1895", note: "Connects portable Lumière production to collective projection, actuality programming and the public exhibition of modern everyday life." },
    { title: "May Irwin Kiss", year: 1896, role: "comparative_film", atlasDecision: "P2", note: "Book-level comparison for celebrity, theatrical familiarity and the programme value of a very short staged attraction; not required as a Production Case." },
    { title: "The Corbett–Fitzsimmons Fight", year: 1897, role: "anchor_film", atlasDecision: "use_existing_atlas_case", atlasScenarioId: "scenario_the_corbett_fitzsimmons_fight_1897", note: "Anchor for event cinema: long-form capture, three-camera logistics, proprietary wide-gauge projection, live commentary, territorial rights and ticket economics." },
    { title: "Employees Leaving Brown's Atlas Works, Sheffield", year: 1901, role: "comparative_film", atlasDecision: "use_existing_atlas_case", atlasScenarioId: "scenario_employees_leaving_browns_atlas_works_sheffield_1901", note: "Local actuality in which staged crowd flow, recognizable faces and showman commissioning connect production directly to the prospective paying audience." },
    { title: "Sedgwick's Bioscope Showfront at Pendlebury Wakes", year: 1901, role: "comparative_film", atlasDecision: "P2", note: "Book-level evidence for fairground publicity, showfront performance and the Mitchell–Kenyon/showman network; retained outside the Production Case queue." },
    { title: "Uncle Josh at the Moving Picture Show", year: 1902, role: "comparative_film", atlasDecision: "use_existing_atlas_case", atlasScenarioId: "scenario_uncle_josh_at_the_moving_picture_show_1902", note: "Self-reflexive spectator comedy that makes projection space visible while demonstrating why fictional rube behavior cannot be used as documentary proof of universal audience credulity." },
    { title: "A Trip to the Moon", year: 1902, role: "comparative_film", atlasDecision: "use_existing_atlas_case", atlasScenarioId: "scenario_a_trip_to_the_moon_1902", note: "Shows the programme and circulation value of an elaborate, exportable trick-film spectacle." },
    { title: "The Great Train Robbery", year: 1903, role: "comparative_film", atlasDecision: "use_existing_atlas_case", atlasScenarioId: "scenario_the_great_train_robbery_1903", note: "Its flexibly placeable direct-address bandit shot illustrates continued exhibitor/programme agency alongside increasingly organized internal narrative action." },
  ],
  historicalObjects: [
    { label: "Lumière Grand Café programme, 28 December 1895", role: "historical_object", atlasDecision: "no_production_case", note: "A programme and exhibition event, not a film title; used to study collective projection without turning one screening into a universal birthday." },
    { label: "Vitascope exhibition at Koster and Bial's Music Hall, 23 April 1896", role: "historical_object", atlasDecision: "no_production_case", note: "Venue, projection system and mixed-bill exhibition evidence rather than a Production Case." },
    { label: "Vitascope publicity and exhibitor advertising", role: "historical_object", atlasDecision: "no_production_case", note: "Publicity demonstrates how projection was sold as an attraction before a spectator reached the screen." },
    { label: "Edison film catalogues and exhibitor-selected programme sequencing", role: "historical_object", atlasDecision: "no_production_case", note: "Commercial and programming infrastructure showing exhibitor agency over selection and order." },
    { label: "Music-hall and vaudeville mixed bills", role: "historical_object", atlasDecision: "no_production_case", note: "Existing entertainment systems in which moving pictures appeared beside live acts." },
    { label: "Fairground and travelling bioscope showfronts", role: "historical_object", atlasDecision: "no_production_case", note: "Mobile exhibition infrastructure and showmanship, distinct from any one film production." },
    { label: "Live lecturers, commentary and musical accompaniment", role: "historical_object", atlasDecision: "no_production_case", note: "Variable exhibition layers that explain why photographed silent film did not imply a silent room." },
    { label: "Nickelodeon storefront exhibition and frequent low-cost screenings", role: "historical_object", atlasDecision: "no_production_case", note: "A film-dedicated exhibition model emerging in the mid-1900s; not a template to project backward over the entire early period." },
  ],
  sources: filmHistoryChapterTwoSources,
};
