import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterSixMovementTwo: readonly FilmHistoryBookSection[] = [
  {
    id: "ch6_mgm_crowd",
    title: "6. MGM and The Crowd: centralized resources without automatic sameness",
    paragraphs: [
      "Metro-Goldwyn-Mayer is useful because the studio-system argument becomes too simple if consolidation is treated as the opposite of artistic specificity. Loew's corporate structure connected production to a powerful exhibition organization, while MGM assembled permanent departments, contract talent, facilities and managerial routines capable of sustaining a large release program. Such resources imposed constraints: schedules, budgets, previews and executive decisions could redirect a film. Yet those same resources could also make technically difficult work possible. The historical question is therefore not whether industrial organization destroys authorship, but how creative agency operates through institutions that distribute money, labor, equipment and final authority unevenly.",
      "The Crowd demonstrates that tension unusually well. AFI identifies King Vidor and John V. A. Weaver's screenplay, Henry Sharp's photography, Cedric Gibbons and A. Arnold Gillespie's settings and Hugh Wynn's editing inside an MGM/Loew's production. Library of Congress material emphasizes the film's celebrated movement from the scale of New York into an immense office and its concealed-camera exteriors. The film's ordinary protagonist is not made significant by escaping the system; his anonymity is visualized with the resources of the system. Massive design, location work, camera movement and continuity make social scale intelligible enough that one desk and one marriage can be felt inside it.",
      "The film's endings make studio process visible in another way. AFI documents previewing and the availability of two release endings to exhibitors. That history should replace the romantic assumption that a film necessarily had one untouched final form issuing directly from a director's intention. Preview response, exhibitor choice and corporate distribution could alter how a feature closed, while a later Brownlow-Gill restoration added a new Carl Davis score decades after the silent release. The Crowd therefore teaches centralized production and social realism together, but it also teaches that version control is part of industrial authorship rather than a footnote after the art is complete."
    ],
    sourceIds: ["ch6_afi_crowd", "ch6_loc_registry_descriptions", "ch6_academy_1929"],
  },
  {
    id: "ch6_exhibition_power_first_national",
    title: "7. Exhibition power could organize the industry from the screen backward",
    paragraphs: [
      "Vertical integration is often narrated only from producer to theater: a company makes films, distributes them and then acquires screens. The silent-era market was more contested. First National emerged from exhibitor interests and demonstrated that access to theaters could become leverage over production and stars from the opposite direction. The larger point is structural. Once feature supply, first-run screens and national publicity became scarce strategic assets, bargaining power could accumulate at several points in the chain. Studios needed reliable outlets, exhibitors needed attractive films, and stars who could move audiences could negotiate against both. The Hollywood system was therefore a struggle over bottlenecks, not a smooth march toward one corporate design.",
      "Later antitrust records help reconstruct what was at stake, provided their later date remains visible. The Paramount litigation describes runs, clearances, theater ownership, package licensing and other practices through which distributors and exhibitors could shape competitive access. Those records concern a mature system and cannot prove that every mechanism existed unchanged in 1917. They do, however, make the economic logic legible: a film's value depended on where it opened, how long geographic exclusivity lasted, which circuit controlled desirable houses and whether an independent exhibitor could bid for an individual title. Release architecture was therefore a form of industrial design with consequences for what production could be financed.",
      "For the book this matters because exhibition cannot be relegated to the moment after a film is finished. A company planning stars, genres and annual output did so in relation to a market of theaters segmented by location, run and audience. First National's exhibitor base, Paramount's distribution strength, Loew's theater interests and United Artists' alternative arrangement represent different answers to the same problem: how does control of circulation translate into production power? Chapter 6 keeps those institutions as historical objects rather than fake Production Cases because the learning target is a network relation, not a film one can responsibly imitate scene by scene."
    ],
    sourceIds: ["ch6_classical_columbia", "ch6_paramount_antitrust_1946", "ch6_paramount_antitrust_1949"],
  },
  {
    id: "ch6_united_artists_gold_rush",
    title: "8. United Artists and The Gold Rush: independence still required an industrial route",
    paragraphs: [
      "United Artists is best treated as a countermodel inside Hollywood rather than an escape from industry. Chaplin, Mary Pickford, Douglas Fairbanks and D. W. Griffith created a distribution vehicle intended to give major producers greater control over their pictures. The arrangement did not eliminate financing, schedules, laboratories, publicity, bookings or exhibition; it rearranged who controlled key decisions and how finished films reached theaters. This distinction prevents a misleading opposition between studio products and pure independent art. Independence at feature scale still depended on specialist labor and market infrastructure, but it could relocate authority toward a star-producer with unusual bargaining power.",
      "The Gold Rush makes that arrangement concrete. AFI and Chaplin archival sources identify Charles Chaplin Productions and United Artists distribution while documenting a production that moved between Truckee snow-country work and an elaborate Hollywood reconstruction. Roughly six hundred extras were used for the Chilkoot Pass image before the main production returned to controlled studio conditions where artificial mountains, effects and repeated performance could be coordinated. Chaplin's writer-director-producer-editor credits are historically significant, but they do not erase Roland Totheroh's cinematography, Charles D. Hall's design work, construction labor, extras or the distribution organization that converted a costly comedy into an international product.",
      "The film also demonstrates why star authorship must be version-aware. Chaplin's 1942 reissue was not simply the 1925 film with better sound: archival sources document narration, a newly composed synchronized score, removal of intertitles and footage changes. Cineteca di Bologna's later restoration history adds another material layer. The chapter therefore uses The Gold Rush as a strong counterexample to vertical integration while refusing the idea that independence means an unchanging authorial object. Control can be unusually concentrated and still operate through collaborators, distributors, exhibitors and subsequent versions."
    ],
    sourceIds: ["ch6_afi_goldrush", "ch6_chaplin_filming", "ch6_chaplin_music", "ch6_cineteca_goldrush", "ch6_afi_goldrush_spotlight"],
  },
  {
    id: "ch6_star_system_it",
    title: "9. It: the star system was a media-production system",
    paragraphs: [
      "The star system cannot be understood as the discovery that audiences liked attractive performers. It was a coordinated process that connected casting, contracts, screen roles, still photography, publicity, magazines, fashion discourse and repeated audience recognition. A star image could travel ahead of a film and continue after it, giving companies a form of brand value attached to a person. That value was unstable: studios and performers negotiated over roles, salaries and publicity, while scandals or changing tastes could damage it. The industrial achievement was to make a performer legible across films and media strongly enough that a new release could be sold partly through expectations accumulated elsewhere.",
      "It is unusually explicit because Paramount tied Clara Bow's vehicle to Elinor Glyn's already circulating idea of personal magnetism and to the Hearst/Cosmopolitan media environment. AFI documents the Glyn adaptation arrangement, Paramount Famous Lasky production, Hope Loring and Louis D. Lighton's scenario work, Clarence Badger's direction and Josef von Sternberg's additional direction during Badger's illness. Library of Congress and UCLA material place Bow's screen presence at the center of the release's identity. The result shows a studio not merely photographing a star but coordinating story, magazine concept, publicity and performance into a product whose title itself functions as a marketing hook.",
      "That history also requires an ethical distinction between analyzing objectification and reproducing it. Period publicity frequently turned women performers into commodities measured through beauty, sexuality and availability. The Production Case therefore converts the star-system lesson into media coordination, performance strategy and publicity design rather than appearance scoring. Bow's historical importance lies in how a modern screen identity was industrially circulated and how her performance exceeded the narrow slogans used to market it. A serious production history can study the economic force of sexualized publicity without making the player reenact its demeaning assumptions as a success metric."
    ],
    sourceIds: ["ch6_afi_it", "ch6_ucla_it", "ch6_hollywood_vault", "ch6_loc_registry_complete"],
  },
  {
    id: "ch6_genre_general",
    title: "10. Genre made repetition productive: The General and the engineering of comic action",
    paragraphs: [
      "Genre is another place where standardization and difference have to be held together. A comedy, western, melodrama or war film could inherit recognizable situations, star expectations and marketing categories without becoming interchangeable with every other title in the cycle. Repetition lowered some kinds of risk because producers could reuse expertise, locations, props, performers and publicity language; differentiation created the reason to buy a ticket again. Genre production therefore worked like a set of constraints that organized invention. A company could ask what kind of picture it was making while still needing a fresh combination of spectacle, character and craft to distinguish that release from the previous one.",
      "The General provides a precise physical example. AFI credits Buster Keaton and Clyde Bruckman as directors, Joseph Schenck as producer, Dev Jennings and Bert Haines in photography and Fred Gabourie in technical direction, and records United Artists distribution. Location production around Cottage Grove turned locomotives, tracks, landscape and a large material apparatus into comic geometry. Keaton's performance is inseparable from the engineering of space: the viewer must understand where the train, tracks, pursuing forces and obstacles are for a gag to register. Classical legibility here supports danger and surprise rather than suppressing them.",
      "The case also complicates the word independent. During production Schenck became president of United Artists and additional financing helped complete the picture, according to AFI. Keaton's authorship and production autonomy therefore existed inside financial and distribution relationships rather than outside them. MoMA's account rightly emphasizes the precision of his mechanical comic world, but Chapter 6 pairs that aesthetic insight with institutional evidence so that machinery does not become a lone-genius myth. Genre, star performance, practical engineering, location control and distribution were mutually dependent resources in making a feature whose action still reads with extraordinary clarity."
    ],
    sourceIds: ["ch6_afi_general", "ch6_moma_general", "ch6_loc_general_findingaid", "ch6_classical_routledge"],
  },
];
