import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterSevenMovementTwo: readonly FilmHistoryBookSection[] = [
  {
    id: "ch7_kammerspiel_last_laugh",
    title: "6. Kammerspielfilm compressed social pressure into bodies, objects and everyday space",
    paragraphs: [
      "Kammerspielfilm provides the clearest counterexample to the idea that Weimar ambition always meant monumental spectacle. Its production logic concentrates attention: relatively few central characters, limited social environments, emotionally charged objects and a preference for behavior that can carry information without constant explanatory titles. The Last Laugh makes this tendency especially legible because Carl Mayer's story turns a hotel doorman's uniform into a complete social technology. The coat gives access, posture and recognition; losing it changes how Emil Jannings moves, how others look at him and how the hotel and tenement spaces register his status. Production design, costume and performance therefore perform narrative work before the camera begins to move.",
      "filmportal identifies the project as an UFA/Union-Film production under Erich Pommer with F. W. Murnau directing, Mayer writing, Karl Freund photographing and Robert Herlth and Walter Röhrig responsible for sets. The division of labor matters because the film is often summarized through one famous phrase—the 'unchained camera'—as though mobility alone created its effect. In practice, camera movement gains meaning because hotel doors, lifts, corridors, glass, smoke, uniforms and Jannings' body have been staged to make changes of rank and perception readable. A moving viewpoint without that prepared environment would be technical display rather than chamber drama.",
      "The film's famous near-elimination of intertitles is likewise a production challenge rather than proof that titles suddenly became obsolete. Images must carry cause, recognition, memory and humiliation with enough clarity that text can be reduced. The intentionally conspicuous intertitle before the improbable wealthy coda is powerful because the film has established a different norm. BFI and filmportal both treat the ending as a tonal rupture, so the chapter preserves it as a historical choice rather than smoothing it into a uniformly realistic story. Kammerspielfilm here means concentrated coordination, not a rule that every chamber drama must avoid titles or use the same emotional scale.",
    ],
    sourceIds: ["ch7_last_laugh_filmportal", "ch7_last_laugh_bfi", "ch7_ufa_filmportal", "ch7_weimar_classical_avant"],
  },
  {
    id: "ch7_unchained_camera_collaboration",
    title: "7. The 'unchained camera' was a collaborative practice, not a first-ever invention",
    paragraphs: [
      "The German phrase entfesselte Kamera names a historically important expansion of mobile and subjective cinematography, but it easily attracts invention myths. filmportal's dedicated account is explicit that Karl Freund was not the first person ever to remove a camera from a tripod. What distinguished The Last Laugh was the sustained, motivated integration of movement into a feature's narration. The apparatus could travel with bodies, descend through architectural systems or simulate intoxicated perception, while the resulting views remained connected to the protagonist's social and psychological situation. The achievement lies in systematization and expressive coordination rather than a patent-like claim to the first moving shot.",
      "That coordination required hardware, bodies and sets to work together. A camera carried, mounted, suspended or moved through constructed architecture creates safety, focus, exposure and staging problems that a locked tripod does not. Freund's practice depended on Murnau's blocking, Mayer's visual construction, the designers' routes and surfaces, performers hitting repeatable positions, assistants maintaining the apparatus and editorial choices that connected moving images to surrounding shots. The Production Case therefore asks who needs to know a movement in advance and what must be built or rehearsed to support it, rather than rewarding the player for selecting 'handheld' as an anachronistic universal solution.",
      "Varieté demonstrates that mobility was already circulating beyond a single film. E. A. Dupont's UFA production, again photographed by Freund with Carl Hoffmann, uses rapid changes of camera distance, circus space and aerial spectacle to organize jealousy and performance. filmportal's Weimar history treats this mobility as part of the international prestige of German production, and Varieté's foreign success helped validate UFA's risk-taking strategy. The comparison prevents The Last Laugh from becoming an isolated miracle: techniques moved between productions, crews learned from one another, and an internationally legible 'German' camera style emerged from repeated labor rather than one moment of spontaneous invention.",
    ],
    sourceIds: ["ch7_unchained_camera_filmportal", "ch7_variete_filmportal", "ch7_variete_murnau", "ch7_weimar_classical_avant"],
  },
  {
    id: "ch7_ufa_prestige_nibelungen_faust",
    title: "8. UFA prestige joined monumental design to financial and international strategy",
    paragraphs: [
      "Die Nibelungen and Faust show another production scale operating beside Kammerspielfilm. Both turn pre-existing cultural material into carefully organized screen worlds whose architecture, costumes, crowds, lighting and effects require long preparation. filmportal records Die Nibelungen as an Erich Pommer production associated with Decla-Bioscop and UFA, photographed and built across the Neubabelsberg facilities over an extended period. Fritz Lang's severe compositions and mass choreography are not merely aesthetic signatures; they are consequences of constructing spaces in which bodies can be arranged ornamentally and photographed with repeatable geometric control.",
      "Faust extends the same prestige logic through Murnau's fantasy production at UFA's Tempelhof studios. filmportal records shooting from September 1925 to May 1926 and a silent 35 mm original whose elaborate imagery had to combine performers, designed environments and effects. The film is important here not because it needs another Atlas case, but because it makes visible the industrial resources behind supernatural imagery. Smoke, scale, miniature-like vistas and controlled illumination are credible only when departments agree on perspective, exposure, movement and timing. Monumental style is therefore a coordination problem before it becomes a critical label.",
      "Prestige also carried economic risk. Deutsche Kinemathek and filmportal describe UFA's mid-decade push for internationally competitive, expensive films while documenting the financial strain that accompanied it. The same organization could produce The Last Laugh's concentrated chamber story and Metropolis's immense future city because 'UFA style' was not one image grammar but a strategy of technical ambition and export prestige. Chapter 7 keeps Die Nibelungen and Faust at P2 because their production functions deepen the industrial comparison without adding enough new gameplay beyond Metropolis, Nosferatu and The Last Laugh. Their value lies in showing the range—and cost—of the system.",
    ],
    sourceIds: ["ch7_nibelungen_filmportal", "ch7_faust_filmportal", "ch7_ufa_kinemathek", "ch7_ufa_filmportal"],
  },
  {
    id: "ch7_variete_export_mobility",
    title: "9. Varieté turned camera mobility and circus space into an exportable prestige form",
    paragraphs: [
      "Varieté is an especially useful bridge between the chamber scale of The Last Laugh and the spectacular resources of UFA. E. A. Dupont builds a jealousy melodrama around Emil Jannings, Lya de Putti and Warwick Ward, but the production's identity also depends on the Wintergarten environment and the challenge of making acrobatic height readable. filmportal credits Karl Freund and Carl Hoffmann with photography and records the 1925 UFA production under Erich Pommer. Camera distance changes, subjective angles and aerial viewpoints allow the circus to be experienced as both workplace and emotional danger rather than as a detached stage attraction.",
      "The production illustrates how a technique becomes marketable through repetition and variation. Mobile-camera work had already become associated with German prestige through The Last Laugh; Varieté applies related resources to a different genre and spatial problem. filmportal's period overview emphasizes the film's international success, while the Murnau Foundation's restoration history reminds us that the work survives today through reconstruction of materials and color information rather than as a transparent window onto 1925. Export reputation and preservation reputation are therefore separate historical layers, even when both help sustain the same film's canonical status.",
      "Keeping Varieté as a P2 comparison is pedagogically deliberate. A second mobile-camera Production Case could tempt gameplay into treating movement as a collectible trick: attach the camera to something unusual and receive historical credit. The Last Laugh already supplies the stronger canonical case for motivated subjectivity. Varieté belongs in the book because it proves that the technique was circulating across genres, crews and markets, and because it expands the discussion toward circus labor, risk and international exhibition. Its historical function is comparative breadth rather than duplication of the Atlas mechanic.",
    ],
    sourceIds: ["ch7_variete_filmportal", "ch7_variete_murnau", "ch7_weimar_classical_avant", "ch7_weimar_moma"],
  },
  {
    id: "ch7_metropolis_scale_versions",
    title: "10. Metropolis made the future city a production system—and then became a version-history problem",
    paragraphs: [
      "Metropolis is the chapter's maximal UFA anchor. filmportal records a production running from May 1925 to October 1926 at Filmwerke Staaken and UFA's Neubabelsberg facilities, with Fritz Lang directing, Thea von Harbou writing, Erich Pommer producing and Karl Freund and Günther Rittau among the cinematographers. The city emerges from sets, miniatures, effects, mass choreography, costume, machinery and carefully controlled photography. Its scale is not reducible to one famous visual effect: hundreds of design and logistical decisions must agree on architecture, body movement and screen geography before the city can function as a coherent social machine.",
      "The film also demonstrates how prestige can destabilize the institution that finances it. Deutsche Kinemathek notes that expensive productions such as Metropolis contributed to UFA's mid-1920s financial crisis before Alfred Hugenberg acquired and restructured the company in 1927. filmportal's Lang biography likewise connects the long shoot and extraordinary expense to management conflict. This chronology matters because the spectacular image cannot be separated from the financial system that made it possible. Industrial ambition created technical opportunity, but it also created debt, bargaining pressure and incentives to reshape films for different markets.",
      "No Chapter 7 film makes version criticism more unavoidable. filmportal distinguishes the January 1927 Berlin premiere from radically shortened distribution forms, later releases and the 2010 restoration, while Deutsche Kinemathek describes the American shortening and UFA's subsequent decision to circulate a similarly altered version in Germany. The rediscovery of material in Buenos Aires allowed a much fuller reconstruction, but even that restoration is not an untouched original negative. The Production Case therefore treats 1927 production, market-driven recutting, archival recovery and reconstructed Huppertz music as distinct layers. To teach Metropolis without those boundaries would turn preservation history into false production fact.",
    ],
    sourceIds: ["ch7_metropolis_filmportal", "ch7_metropolis_history", "ch7_weimar_revisited", "ch7_lang_filmportal", "ch7_ufa_kinemathek"],
  },
];
