import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterSixMovementThree: readonly FilmHistoryBookSection[] = [
  {
    id: "ch6_wings_logistics",
    title: "11. Wings: blockbuster scale was a logistics problem before it was an awards fact",
    paragraphs: [
      "Wings is often introduced through the first Academy Awards, but its deeper Chapter 6 value lies in production coordination. AFI identifies Paramount Famous Lasky, William A. Wellman, producer Lucien Hubbard, writers John Monk Saunders, Hope Loring and Louis D. Lighton, chief cinematographer Harry Perry, a broad specialist photography team, editor-in-chief E. Lloyd Sheldon and engineering-effects specialist Roy Pomeroy. The film's scale was therefore not a single department's achievement. Aircraft, performers, military personnel, ground battle construction, cameras, effects and editorial records had to be synchronized so that expensive material produced usable dramatic continuity rather than disconnected spectacle.",
      "War Department cooperation made that coordination unusually visible. AFI documents San Antonio-area production connected to Camp Stanley, Kelly Field and Brooks Field, along with military aircraft, pilots, servicemen, trench construction and explosives. Real resources do not automatically produce realism: the player still needs screen direction, cockpit geography, matching ground objectives and editorial escalation to convert aviation into intelligible action. The case therefore distinguishes material authenticity from documentary truth. Staged battle scenes made with real planes and soldiers remain dramatic constructions, and institutional cooperation becomes part of production history rather than a guarantee that the image records World War I as it occurred.",
      "Exhibition history again complicates the object called a film. AFI separates the 1927 premiere and roadshow history from a 1929 national release with added musical score and sound effects. The Academy's later restoration reinstated tinting and recreated Handschiegl color-process effects for modern presentation. Those changes are historically important, but they do not belong inside an imaginary synchronized 1927 production track. Wings closes the Production Case sequence by making industrial scale, specialist labor and version history impossible to separate: a studio spectacle is both a coordinated event of production and a changing material object in circulation."
    ],
    sourceIds: ["ch6_afi_wings", "ch6_academy_wings", "ch6_academy_1929", "ch6_loc_nfr_1997"],
  },
  {
    id: "ch6_release_geography",
    title: "12. Runs, clearances and block booking made geography part of the product",
    paragraphs: [
      "A national market did not mean that every theater received the same film at the same moment. Runs and clearances organized releases through time and geography: desirable first-run houses could open a title before later-run theaters, while territorial protection limited how quickly nearby competitors could show the same picture. This hierarchy helped companies extract different prices and publicity value from successive engagements. It also meant that exhibition architecture fed back into production decisions. A prestige film, star vehicle or expensive spectacle could be planned for a release pattern that treated scarcity and venue status as commercial resources rather than simply sending identical prints everywhere at once.",
      "Block booking extended distributor power across a slate. The 1932 Famous Players-Lasky litigation describes packages of 13, 26, 52 or 104 films offered to exhibitors, while the later Paramount case records the antitrust objection to conditioning access to one film on taking others. These judicial records postdate many silent titles in this chapter and must be used chronologically: they document mature versions of practices and conflicts whose institutional roots developed earlier, not a timeless formula mechanically applied to 1915. Used carefully, they show why annual output, stars and genres could become bargaining assets at the distribution level as well as creative categories at the production level.",
      "The historical consequence is that a studio's power cannot be measured only by how many cameras or soundstages it owned. Control over booking, affiliated theaters, clearance zones and high-demand pictures affected whether competitors could reach audiences on comparable terms. That is why the eventual antitrust record is so revealing even for a chapter that ends in 1929: it exposes the economic mechanisms that later drew legal scrutiny. Chapter 6 does not import the 1948 Paramount remedy backward. It uses later evidence to name structural tendencies while preserving the difference between a developing silent-era system and its more consolidated sound-era form."
    ],
    sourceIds: ["ch6_famous_lasky_blockbooking", "ch6_paramount_antitrust_1946", "ch6_paramount_antitrust_1949", "ch6_classical_columbia"],
  },
  {
    id: "ch6_mppda_self_regulation",
    title: "13. The MPPDA: industrial legitimacy became organized work",
    paragraphs: [
      "In 1922 major film companies created the Motion Picture Producers and Distributors of America under Will Hays. The organization belongs in this chapter because consolidation created collective political problems as well as economies of scale. Censorship disputes, moral campaigns, labor questions and public distrust could threaten the industry's access to markets. A trade association allowed companies that competed at the box office to coordinate around shared institutional interests. The MPPDA should not be treated as if a fully enforced Production Code suddenly governed every silent film in 1922; the stricter Code administration associated with 1934 belongs to a later chapter.",
      "The need for legitimacy is visible in controversies surrounding films as well as in organization charts. The Birth of a Nation provoked protests and suppression efforts because its white-supremacist account of Reconstruction and heroic Ku Klux Klan were political interventions, not neutral historical scenery. Library of Congress materials preserve both the film and contemporaneous or later critical records of its racism and protest history. That controversy predates the MPPDA, but it demonstrates why a national industry capable of mass circulation also became a target for civic groups, censors and political authorities. Scale magnified both commercial reach and social responsibility.",
      "Self-regulation therefore belongs beside distribution and publicity as a form of industrial management. Companies were not only manufacturing films; they were managing relationships with governments, exhibitors, reformers and audiences whose objections could interrupt circulation. The MPA's own institutional history traces the organization to 1922, while later Code history shows that self-regulatory mechanisms changed over time. Chapter 6 keeps that chronology explicit: Hays-era organization is evidence that the industry recognized collective reputational risk, not proof that classical Hollywood was already operating under the later 1934 enforcement regime."
    ],
    sourceIds: ["ch6_mpa_history", "ch6_loc_birth_today", "ch6_loc_birth_symposium", "ch6_loc_birth_item"],
  },
  {
    id: "ch6_critical_countercanon",
    title: "14. What the classical-system story explains—and what it can conceal",
    paragraphs: [
      "A history of classical Hollywood can become celebratory if efficiency, continuity and market growth are treated as self-evident progress. The Birth of a Nation is the clearest warning. It is historically important for feature-scale circulation and formal organization, but its narrative makes white supremacy emotionally legible and helped normalize racist historical mythology. The Library of Congress records the continuing controversy and protest surrounding the film. Chapter 6 therefore keeps it as P2 analytical evidence rather than a Production Case: students need to understand the commercial and formal power of the film without being asked to reproduce its propagandistic objectives as successful gameplay.",
      "Other P2 films expose different limits of a simple system narrative. Intolerance pushes enormous sets and crosscutting toward a scale already partly covered by Chapter 3's editing history; Greed makes conflict between expansive location-based authorship and corporate control unusually visible because its surviving release history cannot be reduced to one director-approved master; Sunrise demonstrates that Hollywood's resources could import European personnel, design practices and camera ambitions rather than merely export a fixed American style. MoMA's accounts of Greed and Sunrise are especially useful because they connect form to production circumstances and preservation rather than isolating celebrated images from the institutions that made and remade them.",
      "The remaining P2 titles widen the comparison without requiring redundant gameplay. The Kid and Safety Last! complicate star comedy; The Covered Wagon, The Big Parade and Ben-Hur show genre and spectacle at industrial scale; Flesh and the Devil makes MGM star pairing visible; The Cameraman turns Keaton's entry into MGM into evidence about changing autonomy; Show People reflects Hollywood back at itself. The point of a P2 designation is not lesser historical value. It means the chapter can teach the distinct historical claim through prose and comparison because a new Production Case would duplicate a craft problem already embodied more clearly elsewhere in the Atlas."
    ],
    sourceIds: ["ch6_loc_birth_item", "ch6_loc_registry_complete", "ch6_moma_greed", "ch6_afi_greed", "ch6_moma_sunrise_event", "ch6_moma_sunrise_history"],
  },
  {
    id: "ch6_synthesis_1929",
    title: "15. By 1929 the system was powerful, contested and already changing",
    paragraphs: [
      "The six Atlas anchors now form a deliberately nonredundant map of the classical Hollywood problem. The Cheat shows company style and the ethical stakes of representation; The Gold Rush shows star-producer independence routed through United Artists; The General shows genre, machinery and action geography; It shows publicity and stardom as coordinated media production; The Crowd shows MGM resources, social scale and version negotiation; Wings shows Paramount logistics, military cooperation, specialist photography and engineering effects. None is presented as the film that invented continuity or the studio system. Together they expose different interfaces between craft and organization.",
      "The historical objects supply the infrastructure those films cannot represent by themselves: the Hollywood labor cluster, Famous Players-Lasky/Paramount distribution, Loew's/MGM integration, First National's exhibitor power, United Artists' consortium, runs and clearances, collaborative continuity practice, contract stars, genre planning and the MPPDA. Keeping those objects out of the scenario count is methodologically important. A distribution network is not a movie, a trade association is not a production, and a labor convention does not have a single director. The book can explain systems without pretending every important historical phenomenon must be converted into playable imitation.",
      "The chapter ends in 1929 because synchronized sound is about to reorganize the same system rather than because silent Hollywood reached a perfect final form. The 1920s industry was already absorbing imported talent, experimenting with sound presentations, changing exhibition practices and negotiating corporate concentration. Silent accompaniment itself varied by venue and release, as Library of Congress music collections demonstrate, while films such as Wings acquired later sound packages. Chapter 11 will examine the sound transition directly. Chapter 6 leaves us with the prerequisite: a mature industrial network capable of standardizing labor and circulation strongly enough that a new technology could reorganize an entire production ecology."
    ],
    sourceIds: ["ch6_classical_routledge", "ch6_loc_silent_music", "ch6_loc_registry_complete", "ch6_hollywood_vault", "ch6_academy_wings"],
  },
];
