import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterFiveMovementThree: readonly FilmHistoryBookSection[] = [
  {
    id: "ch5_italian_epic_cycle",
    title: "Italian epic production before Cabiria",
    paragraphs: [
      "Italian historical spectacle became internationally important before Cabiria appeared in 1914. Longer films based on classical, biblical and literary subjects helped companies in Turin and Rome demonstrate that feature scale could be sold through architecture, crowds, costumes and cultural prestige. L'Inferno and Quo Vadis? remain P2 references because they establish this cycle without forcing the Atlas to create several nearly identical epic gameplay problems. Their value in the chapter is comparative: Cabiria belongs to an already developing industrial and aesthetic strategy rather than arriving as a solitary invention.",
      "The epic form changed production arithmetic. A spectacle that depended on many performers, large built environments, historical dress and complex action required coordination across departments and shooting days. Its selling point could be visible expenditure, yet expenditure alone did not create clarity. The camera had to make scale intelligible; crowd movement had to direct attention; sets had to support action rather than merely fill the frame; and a multi-reel structure had to renew interest after the novelty of a single tableau faded. These demands made the epic a test of production organization as much as of capital.",
      "International circulation then multiplied the stakes. A costly film needed markets larger than one city or nation if producers were to recover the investment, encouraging prestige advertising, road-show presentation and export relationships. The chapter therefore treats Italian historical-epic production centres as infrastructure and individual films as evidence of different stages within that system. Quo Vadis? and L'Inferno prove that Cabiria did not invent Italian spectacle, while Cabiria earns the playable anchor because its surviving production record supports a more distinctive integrated case involving design, camera movement, effects coordination, music and version history.",
    ],
    sourceIds: ["ch5_bfi_silent_epics", "ch5_cannes_cabiria", "ch5_moma_cabiria", "ch5_ucpress_transformation"],
  },
  {
    id: "ch5_cabiria_system",
    title: "Cabiria: spectacle as an integrated production system",
    paragraphs: [
      "Cabiria concentrates the Italian epic's production pressures at exceptional scale. Museo Nazionale del Cinema and La Cinémathèque française identify Giovanni Pastrone's Itala Film production, a cinematography team that included Segundo de Chomón, large historical settings and original music associated with Ildebrando Pizzetti and Manlio Mazza. The useful lesson is not that the film is simply bigger than its predecessors. Its spectacle emerges from coordination: architecture, crowds, fire, effects, performance, intertitles, camera movement and music must all direct the same narrative attention across a long running time.",
      "Moving-camera work is particularly important because scale creates a spatial problem. BFI notes Cabiria's generous use of tracking movement, while the museum and Cinémathèque records place that visual strategy inside a multi-person production rather than an isolated auteur gesture. A camera that advances through a set can reveal depth, connect layers of action and turn built space into dramatic discovery. Chapter 5 therefore refuses the common shortcut that labels every lateral or forward movement a uniquely invented 'Cabiria movement'. The stronger historical insight is that mobile framing became one solution for making expensive three-dimensional spectacle readable and impressive.",
      "Restoration history places another limit around certainty. Museo Nazionale del Cinema distinguishes reconstruction of a 1914 edition from Pastrone's substantially altered 1931 sound reissue. That separation protects the chapter from treating later sound, altered material or modern runtime as transparent evidence of the original release. Cabiria is a powerful international anchor precisely because its production ambition and its version history can both be taught. The producer must coordinate spectacle at scale; the historian must coordinate sources at scale, preserving differences among surviving elements rather than flattening them into one supposedly untouched master.",
    ],
    sourceIds: ["ch5_museo_cabiria_record", "ch5_cinematheque_cabiria", "ch5_museo_cabiria_restoration", "ch5_bfi_silent_epics", "ch5_cannes_cabiria", "ch5_moma_cabiria"],
  },
  {
    id: "ch5_traffic_in_souls_comparison",
    title: "Traffic in Souls: an American feature inside an international market",
    paragraphs: [
      "Traffic in Souls prevents Chapter 5 from becoming a story in which Europe innovates while the United States merely waits for Hollywood. UCLA, AFI and Library of Congress records identify the 1913 film as an IMP production directed by George Loane Tucker and distributed by Universal, with a six-reel feature-scale form and real New York locations. Its production circumstances differ sharply from Cabiria's historical spectacle or Queen Elizabeth's prestige vehicle. The subject is contemporary urban trafficking, and the film's commercial proposition depends on topicality, sensationalism and the ability to sustain a social-problem melodrama across feature length.",
      "The case also reveals how reform discourse could become exploitation. AFI records promotional controversy around claims of institutional approval, while UCLA's account emphasizes secret production, location work and remarkable contemporary returns. A responsible history must separate the film's marketing claims from verified social authority. The camera can use real streets without turning staged melodrama into documentary evidence, and a producer can package a moral warning while also selling danger, surveillance and sexual threat. This tension is not a flaw outside the production system; it is part of how topical feature cinema created value.",
      "International comparison changes the interpretation again. Traffic in Souls emerged while American exhibitors and distributors were already encountering imported prestige films and European feature spectacle. Its success therefore belongs to a competitive market in which longer films were becoming thinkable through multiple routes. The Atlas keeps it as an existing case from Chapter 4 but reuses it here to show reciprocity: international imports affected American expectations, while American independents developed features capable of competing for the same attention. Chapter 5's global map is not a one-way transfer of influence but a network of simultaneous experiments in length, genre and market positioning.",
    ],
    sourceIds: ["ch5_ucla_traffic", "ch5_afi_traffic", "ch5_loc_traffic_copyright", "ch5_bfi_long_take", "ch5_loc_nfr", "ch5_ucpress_transformation"],
  },
  {
    id: "ch5_beyond_core_centres",
    title: "Beyond the usual centres: Germany, Sweden and India",
    paragraphs: [
      "A chapter about international cinema becomes self-defeating if France, Denmark, Italy and the United States are allowed to stand for the whole world. The Student of Prague, Ingeborg Holm and Raja Harishchandra remain P2 references because each demonstrates a production culture that the later book will examine in greater depth. Their presence matters now as a boundary condition: by 1913, feature-scale or artistically ambitious film production was already emerging through different institutions in Germany, Sweden and India. The historical map must register those developments without tokenizing them into under-researched gameplay cases merely to claim geographic coverage.",
      "The Student of Prague links Deutsche Bioscope, Stellan Rye, Hanns Heinz Ewers, Paul Wegener and cinematographer Guido Seeber to a five-act 35 mm production whose double motif makes photographic effects and performance central. Ingeborg Holm demonstrates Victor Sjöström's early Swedish social drama and the capacity of a film to generate public debate; Svenska Filminstitutet also places it inside the institutional beginnings of Swedish silent cinema. Raja Harishchandra marks a foundational Indian feature-production moment under Dadasaheb Phalke, while the fragmentary state and disputed identity of surviving material make preservation caution essential.",
      "These films therefore teach two lessons at once. First, internationalization was plural: industries and filmmakers did not merely receive a finished French, Danish, Italian or American model. They adapted theatre, literature, local exhibition, technical knowledge and social subjects to their own production environments. Second, archival survival is radically uneven. A film can be historically central even when only fragments or uncertain versions remain. Chapter 5 preserves these titles as book references and explicitly defers fuller production treatment to later chapters, where national institutions and silent-era contexts can be researched without compressing them into a decorative global appendix.",
    ],
    sourceIds: ["ch5_filmportal_student", "ch5_filmportal_student_material", "ch5_sfi_ingeborg", "ch5_sfi_silent", "ch5_assam_raja", "ch5_google_raja"],
  },
  {
    id: "ch5_1914_boundary",
    title: "1914 is a rupture, not a finish line",
    paragraphs: [
      "The chapter ends in 1914 because the First World War reorganized the conditions under which films crossed borders, not because international cinema had reached a stable completed form. Before the war, French companies, Danish exporters, Italian epic producers, American independents and many smaller production cultures occupied a volatile market in which no single centre possessed permanent control. War disrupted personnel, finance, transport and access to territories, while the American industry would gain structural advantages that belong to Chapter 6's account of classical continuity and the Hollywood system.",
      "This boundary also prevents hindsight from turning prewar experiments into incomplete versions of later institutions. Fantômas should not be judged only as a primitive serial, Nordisk only as a studio that failed to become Hollywood, or Cabiria only as a precursor to later epics. Each solved immediate problems within the 1907–1914 market: recurring identity, exportable performance, feature-scale versioning, prestige rights and integrated spectacle. The later dominance of other systems does not erase the contingency of those choices. Film history is strongest when it preserves what producers could know at the time rather than writing every decision backward from the winners of the next decade.",
      "Chapter 5 therefore closes with a methodological rule that carries into the rest of the book: national labels are useful only when paired with institutions, circulation and evidence. A film can be made in one country, financed through one company, adapted from another cultural source, distributed through foreign rights holders, altered for particular territories and preserved by archives elsewhere. International cinema is not a later layer added to national cinema; it is present in the material life of prints, people and contracts from the beginning. The completed Atlas matrix makes that argument concrete without pretending every historically important film needs its own Production Case.",
    ],
    sourceIds: ["ch5_ucpress_transformation", "ch5_rutgers_silent", "ch5_dfi_history_1910_1920", "ch5_sfi_silent", "ch5_bfi_silent_epics"],
  },
];
