import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterOneMovementThree: readonly FilmHistoryBookSection[] = [
  {
    id: "when-one-shot-is-not-enough",
    title: "9. When one shot is no longer enough",
    sourceIds: [
      "bfi_big_swallow",
      "bfi_fire",
      "bfi_edwardian_cinema",
    ],
    paragraphs: [
      "A one-shot film can contain complex staging, but the camera position places a hard limit on what can be shown. As filmmakers began to join shots, the central problem changed. The question was no longer only how to arrange action inside one rectangle; it was how a spectator could understand the relationship between several rectangles separated by cuts. Early multi-shot films did not move in a straight line toward one inevitable continuity system. A cut could reveal a new view, repeat an event, make a joke, create a transformation, connect distant places or simply place separate tableaux in sequence. The important development is that editing became a production decision made before and after photography: filmmakers had to imagine how independently recorded pieces might work together.",
      "James Williamson’s *The Big Swallow* (1901) turns this problem into a joke about the camera itself. A man objects to being filmed and advances toward the lens until his mouth fills the frame; the film then cuts to a black interior in which camera and operator appear to fall into the mouth, before returning to the man as he retreats and reacts. The extreme change in scale is startling because it makes camera distance part of the action. Rather than pretending the apparatus is invisible, the film treats filming as an event and the spectator’s viewpoint as something that can be attacked. The sequence demonstrates that shot size and cutting could be manipulated long before later textbooks codified close-ups as routine components of continuity editing.",
      "Williamson’s *Fire!* (1901) tackles a different problem: how can a rescue unfold across several places while remaining intelligible as one action? The film moves from the discovery of a fire to the fire station, the departure of the engine and the rescue at the burning house. BFI discussion highlights the matching of action and the construction of connected film space. The film does not reproduce the later classical system in finished form, and it would be anachronistic to grade it by those rules. Its achievement lies in making separate views serve a common event. A spectator is asked to infer that action continues across a cut and that one place leads causally to another.",
      "This kind of construction requires coordination in production. If an action is to continue from one shot into another, performers and vehicles must be staged so that the transition remains readable. If a location changes, the order of shots has to make the new space intelligible. The filmmaker must decide which part of an event deserves its own view and how much of an action should be repeated or overlapped. These are questions of shooting and assembly together. Editing is therefore not merely something done to finished footage; once filmmakers anticipate cuts, it begins to reshape how footage is produced in the first place.",
      "British filmmakers around Brighton and Hove are important here because surviving films by Williamson, George Albert Smith and others show unusually bold experiments with point of view, scale, inserts, superimposition and multi-shot construction around the turn of the century. The label ‘Brighton School’ can be useful as shorthand but should not imply a formal school with one doctrine or a monopoly on innovation. Similar problems were being explored internationally. What the British examples provide is a concentrated demonstration that film form developed through practical experiments with apparatus and spectatorship, often in short popular subjects rather than in works that resemble later prestige cinema.",
      "The step from multiple shots to coherent narrative organization was neither automatic nor singular. A film could contain several shots without using them to create continuous space; it could present scenes successively like illustrations, or repeat an action from another viewpoint. Those alternatives matter because later continuity norms can make earlier choices look like mistakes. For this chapter, *The Big Swallow* and *Fire!* are comparative films rather than mandatory Atlas anchors: each isolates a specific formal problem that helps explain the changing production logic. The stronger narrative synthesis appears in longer, more spatially dispersed subjects such as Edwin S. Porter’s *The Great Train Robbery*.",
    ],
  },
  {
    id: "great-train-robbery-growing-narrative",
    title: "10. The Great Train Robbery and the growth of narrative construction",
    sourceIds: [
      "loc_great_train_robbery",
      "loc_edison_early_productions",
      "loc_edison_narrative_films",
    ],
    paragraphs: [
      "*The Great Train Robbery* (1903), photographed and produced under Edwin S. Porter for the Edison Manufacturing Company, became one of the most durable landmarks of American early cinema. Its historical usefulness does not depend on claiming that it invented the western, narrative cinema, location shooting, the close-up or editing. Such claims collapse a distributed history into one title. The film matters because it brings together practices that had been developing separately and gives them unusual scale and momentum: staged action, exterior locations, studio work, multiple scenes, camera effects, violence, pursuit and a sustained causal chain. It shows how much more production coordination a film could demand by 1903 than a brief Kinetoscope subject had demanded a decade earlier.",
      "The robbery unfolds across a series of distinct spaces: the telegraph office, train, tracks, countryside and dance hall. The spectator must connect actions that occur in separate shots and infer changing relations among robbers, railway workers, passengers and pursuers. Some transitions depend on simple succession rather than the later convention of tightly matched screen direction. Nevertheless, the film asks viewers to retain narrative information over a longer span and across more locations. Production must therefore sustain continuity of costume, props, action and story state even when photography is broken into separate setups. The film’s scale is organizational as well as aesthetic.",
      "Porter also used techniques that reveal early cinema’s hybrid vocabulary. Portions of the film use compositing or matte work to combine images, while exterior scenes exploit locomotives and landscape as spectacle. The celebrated shot of a bandit firing toward the camera was distributed so that exhibitors could place it at either the beginning or the end. That flexibility is a reminder that a film’s final form was not always fixed in the modern sense. Exhibition practice could affect ordering, and a sensational image could function as an attraction somewhat independently of narrative position. Even an increasingly story-driven film still belonged to the programme culture and attraction-based traditions from which it emerged.",
      "The famous gunshot image also complicates modern assumptions about point of view. It is tempting to label it a ‘close-up’ and then place it on a timeline toward classical shot scales. The more revealing question is what it does in its historical context. The bandit confronts the spectator directly; the image breaks the spatial scale of the surrounding action and intensifies the showmanlike address of the film. Early narrative integration did not immediately eliminate direct display. Attractions and storytelling could coexist inside the same title. This is one reason a teleological account — one in which spectacle disappears as narrative matures — fails to describe early cinema.",
      "The film’s commercial success and later canonical status can themselves distort analysis. Once a title becomes famous, historians are tempted to make it the cause of developments that were already underway. Multi-shot narratives existed before 1903; British, French and American filmmakers were experimenting with connected action; Méliès had made lengthy staged fantasies; actuality producers had learned to organize complex events. *The Great Train Robbery* should instead be treated as a powerful convergence and demonstration. It shows a company able to plan, photograph, assemble and sell a relatively elaborate action film within an expanding market for moving pictures.",
      "That distinction is important for Film Atlas. The film is a P0 recommendation because it would support a Production Case substantially different from *A Trip to the Moon*: not a second generic ‘early film’, but a case about staging action across interiors and exteriors, preserving causal clarity across scenes, coordinating camera effects with location production and balancing spectacle with narrative progression. The book does not need the Atlas case in order to make its historical argument, but the case would let players experience the production problem. The gap is therefore pedagogically meaningful rather than merely canonical.",
    ],
  },
  {
    id: "toward-coherent-film-language",
    title: "11. Toward a more coherent film language — and why the path was not straight",
    sourceIds: [
      "loc_life_american_fireman_registry",
      "bfi_fire",
      "bfi_rescued_by_rover",
      "bfi_edwardian_cinema",
    ],
    paragraphs: [
      "The phrase ‘film language’ can suggest that cinema was discovering a grammar that had always existed, but early filmmakers were not filling in blanks in a universal rulebook. They were testing ways of making spatial and causal relations understandable. Some solutions became widespread because they were efficient, teachable and compatible with industrial production; others remained local, were abandoned, or reappeared later for different purposes. By the first years of the twentieth century, repeated experiments with multi-shot action were beginning to produce more systematic expectations about where an event is happening, what follows what, and how a spectator should connect one view to another.",
      "*Life of an American Fireman* (1903), another Porter production, is especially instructive because the film’s historiography became part of the history. For decades, a version edited with alternating views of the interior and exterior rescue encouraged claims that Porter had developed sophisticated cross-cutting earlier than other filmmakers. Research into the surviving paper-print evidence showed that this intercut structure resulted from a later re-edit; the original arrangement presented the action differently, with temporal overlap between successive viewpoints. The correction is a model for this whole chapter. Film history cannot rely only on familiar copies or inherited textbook claims. The material history of a print can change what historians think a filmmaker did.",
      "The original structure should not be dismissed simply because it differs from later continuity. Repeating or overlapping an event from another position can clarify action in a system where spatial conventions are not yet standardized. It also reflects a tableau logic in which a scene may be presented substantially from one viewpoint before another view takes over. If we rewrite the film into classical cross-cutting, we make it seem more modern at the cost of understanding its actual production logic. Historical specificity requires allowing a film to solve a problem differently from the solution that later became dominant.",
      "*Rescued by Rover* (1905), produced by Cecil Hepworth and directed with Lewin Fitzhamon, provides a useful later point of comparison. The dog Rover leads a father from home through a chain of exterior spaces to find a kidnapped child, then retraces the route. The repeated journey helps orient the spectator because locations recur in a stable order and movement becomes a connective device. BFI accounts emphasize the film’s clarity and extraordinary popularity; demand was so strong that the negative wore out and the film had to be remade. That production fact joins form to industry: a successful narrative pattern creates material demand, and duplication itself encounters the fragility of early film stock.",
      "By 1905, filmmakers had accumulated a practical toolkit: changed camera distance, inserts, superimposition, substitution, multi-shot sequencing, repeated routes, causal chains, movement across locations and various forms of temporal overlap or alternation. Not every producer used all of these devices, and no global standard had yet erased local practice. The important change from the 1890s is the number of available choices and the growing ability to plan them. A filmmaker could decide not only what should happen before the lens but what relationship one photographed fragment should have to another.",
      "The next chapter devoted to narrative will follow how these devices became more systematic after 1905, including continuity practices, longer fiction and the integration of shots into increasingly standardized storytelling. Stopping here is methodologically useful. It prevents this chapter from treating all innovation as a prelude to D. W. Griffith or classical Hollywood, and it gives the first decade of cinema its own historical density. By 1905 the medium had acquired enough technical and formal flexibility to support many futures. Which future became dominant depended not only on style but on companies, distribution, exhibition, audiences and the economics of producing films at greater scale.",
    ],
  },
  {
    id: "what-existed-in-1905",
    title: "12. What existed in 1905 that did not exist in 1875?",
    sourceIds: [
      "nsm_short_history_cinema",
      "nsm_celluloid_beginnings",
      "loc_edison_origins",
      "loc_edison_early_productions",
      "nsm_lumiere",
      "bfi_edwardian_cinema",
    ],
    paragraphs: [
      "The most useful way to end the chapter is not with another first but with a comparison. In 1875, photography could freeze visible reality, optical entertainments could create illusions of change and motion, and scientists were beginning to push exposure times toward the analysis of movement. There was no stable system for recording a long succession of photographs onto flexible transparent film, no established motion-picture camera-and-viewer industry, no dedicated moving-picture studio comparable to the Black Maria, no international network of operators making photographic motion views, and no accumulated repertoire of screen techniques comparable to what filmmakers possessed thirty years later. The transformation was not one invention. It was the construction of an ecosystem.",
      "At the material level, motion pictures now had flexible photographic stock, repeatable transport mechanisms, shutters, perforations, cameras, printers, viewers and projectors. These components were not perfectly standardized, but enough compatibility and manufacturing capacity existed for films to become reproducible commodities rather than singular demonstrations. The strip could be exposed, processed, printed, transported, worn out, recoloured, reordered, copied and projected. Film history is partly the history of that vulnerable object: nitrate stock enabled extraordinary mobility while also making preservation difficult, and the survival of particular versions continues to shape what can be known about the period.",
      "At the production level, there were recognizable environments and workflows for making moving pictures. Edison’s operation had built a studio to manufacture subjects for machines. Lumière operators could travel with portable apparatus. Méliès integrated sets, performers, camera tricks and laboratory manipulation. British producers experimented with location action and multi-shot construction. Gaumont and other firms were developing sustained production activity in which figures such as Alice Guy could direct and supervise films. None of these systems yet resembled the mature studio organizations of the 1910s and 1920s, but production was no longer an occasional appendage to invention. New films were an ongoing requirement.",
      "At the level of form, filmmakers had discovered that moving photographs could do many different things. They could analyse motion, record ordinary life, display celebrity and performance, stage comedy, reconstruct events, fabricate fantasy, alter scale, colour prints, make bodies disappear, combine exposures, move action across several shots and sustain increasingly elaborate chains of cause and effect. These possibilities did not line up in a single hierarchy. Actuality remained valuable after fiction appeared; tableau staging remained expressive after cutting became common; direct address survived inside narrative films. Early cinema’s richness lies partly in this coexistence before later norms made some choices seem natural and others exceptional.",
      "At the social and commercial level, moving images could now be sold as repeated experiences rather than occasional marvels. Kinetoscope parlours had demonstrated individual paid viewing; projection systems had demonstrated collective viewing; companies had reasons to maintain catalogues and supply new subjects; exhibitors could combine films into programmes. This chapter has deliberately not followed those institutions in detail because that is the work of Chapter 2. The point here is simply that apparatus and film form had become embedded in recurring practices. A medium exists differently once people can make a living producing, supplying and showing it.",
      "At the historiographic level, the period also leaves a warning. Our knowledge is uneven because patents, trade papers, company catalogues, copyright deposits, memoirs, surviving prints and later reconstructions preserve different things. Famous pioneer stories often grew in the gaps. The Lumière audience did not need to run from a train for the film to be important. Méliès did not need to invent every trick alone. Alice Guy does not need an uncontested claim to the first fiction film to be central to production history. Porter does not need to have invented cross-cutting in 1903 for his work to matter. Removing weak priority claims makes the history more, not less, interesting because it exposes networks of labour, borrowing and experiment.",
      "The chapter’s central thesis can therefore be restated with greater precision. Cinema emerged when the analysis of movement, flexible photographic film, reliable apparatus, recurring production, individual and projected viewing, commercial circulation and an expanding repertoire of film forms became connected strongly enough to reproduce one another. Every element changed the others. Portable cameras widened the world of possible subjects. Projection changed the scale of spectatorship. Demand for new programmes created pressure for production. Production experience encouraged new forms. New forms made audiences and exhibitors ask for more films. By 1905, cinema was no longer an answer to one technical question; it was a medium capable of generating new technical, aesthetic and industrial questions of its own.",
      "Those questions now divide into the next two histories. Chapter 2 asks how projection, programmes, venues and audiences converted moving pictures into a recurring public institution. Chapter 3 asks how fiction, editing and narrative organization became more systematic. The separation matters because neither exhibition nor narrative should be smuggled backward as the single essence of cinema. The medium existed before the feature film and before one dominant continuity system. Its earliest history is the history of a field becoming possible — a field in which cameras, strips, performers, operators, manufacturers, colourists, exhibitors and spectators collectively discovered that photographed time could be organized, reproduced and made to mean.",
    ],
  },
];
