import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterNineMovementThree: readonly FilmHistoryBookSection[] = [
  {
    id: "ch9_vufku_ukrainian_soviet_cinema",
    title: "11. VUFKU reveals Ukrainian Soviet cinema as an institution with its own studios, labour and cultural stakes",
    paragraphs: [
      "The category 'Soviet cinema' can describe a political state system while still concealing important cultural and institutional differences inside that system. BFI's reporting from the Dovzhenko Centre reconstructs VUFKU as a Ukrainian organization with production studios, distribution, education, advertising and a substantial workforce across Kyiv, Odesa and Kharkiv. By the end of the 1920s it was producing dozens of films a year and supporting filmmakers whose work would later be absorbed into a Russian-centered story of Soviet montage. The chapter therefore uses 'Soviet' without treating it as a synonym for 'Russian' and preserves Ukrainian institutional identity wherever the evidence supports it.",
      "That distinction changes how several canonical works are read. Vertov made Man with a Movie Camera within a Ukrainian production environment and photographed urban life in cities including Kyiv, Kharkiv and Odesa. Oleksandr Dovzhenko's Zvenyhora, Arsenal and Earth form a Ukrainian trilogy whose landscapes, historical references and political contradictions cannot be reduced to generic Moscow revolutionary culture. The Dovzhenko Centre's modern cataloguing deliberately reasserts this lineage, while BFI identifies the later dissolution of VUFKU under centralization. Institutional history therefore helps explain both artistic opportunity in the 1920s and later patterns of erasure.",
      "The safeguard is not to replace one nationalist simplification with another. Filmmakers, crews, financing and distribution crossed borders inside the Soviet Union, and identities were complex. What the chapter rejects is an automatic relabelling that discards documented production context. A historical game should let a player learn that studios and cultural institutions shape work, but it should not infer ethnicity from geography or assign a political essence to technique. VUFKU remains a historical object because its significance lies in infrastructure, labour and cultural autonomy rather than in one reusable visual style.",
    ],
    sourceIds: ["ch9_ukraine_archive_bfi", "ch9_dovzhenko_rediscovery", "ch9_earth_dovzhenko", "ch9_man_camera_bfi"],
  },
  {
    id: "ch9_dovzhenko_earth_hindsight",
    title: "12. Earth combines collectivization propaganda with poetic form, while historical hindsight must not be back-projected as production intention",
    paragraphs: [
      "Earth is a crucial endpoint for the chapter because its commission and its form pull in different directions. BFI identifies the 1930 Ukrainian SSR production as a film commissioned to promote collectivization, yet describes Dovzhenko's emphasis on landscape, fruit, faces, weather, machinery, death and renewal as profoundly lyrical. The Production Case therefore does not ask whether the film is either propaganda or poetry; it asks how an official political purpose can coexist with a film whose sensuous organization exceeds a simple policy message. Shot duration, recurring natural forms and abrupt associative transitions become part of that tension.",
      "Modern historical knowledge makes the film especially difficult. Forced collectivization contributed to catastrophic famine in Ukraine, including the Holodomor, but chronology matters when discussing what Dovzhenko could have known while making Earth in 1929–30. BFI explicitly warns against assuming he could foresee the later catastrophe in the form it took. The chapter therefore distinguishes three claims: the film was commissioned in support of collectivization; later historical evidence changes how that policy is understood; and later knowledge must not be falsely rewritten as a documented intention inside Dovzhenko's production process. Ethical hindsight constrains interpretation without fabricating evidence.",
      "Zvenyhora and Arsenal help locate Earth inside a changing Ukrainian practice. Zvenyhora layers myth, history and modernity; Arsenal turns the 1918 Kyiv uprising into an anti-war and revolutionary image field that alternates propulsive movement with extraordinary stillness. BFI's Arsenal entry emphasizes precisely this tension between revolutionary energy and suffering. These films remain P2 comparisons because Earth already provides the distinct playable problem, but together they show why Dovzhenko does not fit comfortably inside a single montage-theory lineage. His work keeps landscape, folklore, bodies and political contradiction active alongside editing.",
    ],
    sourceIds: ["ch9_earth_bfi", "ch9_earth_dovzhenko", "ch9_arsenal_bfi", "ch9_dovzhenko_rediscovery", "ch9_peak_silent_bfi"],
  },
  {
    id: "ch9_feks_room_diversity",
    title: "13. FEKS, The New Babylon and Bed and Sofa keep Soviet silent cinema broader than a canon of five montage theorists",
    paragraphs: [
      "A chapter centered on montage can accidentally reproduce the narrow canon it is trying to explain. FEKS—the Factory of the Eccentric Actor—grew from theatre, circus, constructivism and an enthusiasm for popular spectacle, and Grigori Kozintsev and Leonid Trauberg's The New Babylon channels that background into a stylized account of the Paris Commune. BFI's 1920s survey stresses the film's eccentric performance, cross-cutting, art-historical references and Dmitri Shostakovich's score. It belongs in the chapter not because every unusual Soviet cut is montage doctrine, but because it shows another network in which performance, design, music and politics were coordinated.",
      "Abram Room's Bed and Sofa pushes the contrast further. Instead of revolutionary epic, it studies intimate domestic life, housing pressure, sexuality and abortion in contemporary Moscow. Sight and Sound's account emphasizes that the film was praised for making everyday Soviet life cinematically interesting before political attacks restricted it. Its importance is historiographic: a viewer who knows only Eisenstein and Vertov might mistake Soviet cinema for a continuous stream of heroic crowds, factories and manifestos. Bed and Sofa shows narrative psychology, social satire and gendered domestic space occupying the same film culture.",
      "Fragment of an Empire, By the Law and The New Babylon remain P2 references for the same reason. Each opens a distinct route—memory and social transformation, Kuleshov's resource-conscious chamber construction, FEKS performance and design—but none requires another Production Case after the seven Chapter 9 anchors are in place. The book can therefore broaden historical coverage without turning every canonical title into gameplay. Production Cases are reserved for distinct production problems; comparative films preserve the plural field around them.",
    ],
    sourceIds: ["ch9_field_bfi", "ch9_peak_silent_bfi", "ch9_1941_bfi", "ch9_mrwest_harvard"],
  },
  {
    id: "ch9_propaganda_distribution_reception",
    title: "14. Propaganda operated through commissions, editing, mobile exhibition and international censorship rather than one ideological content score",
    paragraphs: [
      "Political purpose runs through much of the chapter, but propaganda cannot be modeled as a binary property that makes every formal decision politically equivalent. A state anniversary commission such as October, a collectivization film such as Earth, a Kino-Pravda issue, an agit-train programme and a comedy such as Mr. West use different institutions, genres and audience relations. Some aim to persuade through historical reconstruction, some through factual claims, some through satire and some through the organization of everyday work. The historically useful question is what institution wanted communicated, how filmmakers shaped that purpose, and where the resulting film was shown.",
      "Distribution changes the answer. Mobile projectors and workers' clubs brought film to audiences far from metropolitan theatres, while specialist film societies abroad created different interpretive settings. BFI's history of the British Film Society shows Soviet works becoming objects of censorship battles and cinephile debate; Potemkin, Mother and The End of St. Petersburg encountered restrictions precisely because officials feared political effects. Once a film crossed borders, translated intertitles, censorship cuts, musical accompaniment and programme context could alter how it functioned. Reception history therefore belongs beside production history whenever the chapter makes claims about influence or persuasion.",
      "The game safeguard is strict: players never gain points for political violence, falsifying archival evidence or stripping context to maximize persuasion. They may be asked to recognize that a commission has political goals, that censorship can demand changes, or that a mobile exhibition strategy changes audience reach. But the system evaluates historical and production reasoning, not ideological agreement. Propaganda is studied as a relation among institutions, evidence, rhetoric, circulation and power, which is more demanding—and more accurate—than attaching a red 'propaganda' label to a finished film.",
    ],
    sourceIds: ["ch9_field_bfi", "ch9_film_society_bfi", "ch9_kinopravda_9", "ch9_kinopravda_21", "ch9_kinopravda_23", "ch9_1952_bfi"],
  },
  {
    id: "ch9_1930_sound_boundary_legacy",
    title: "15. The 1930 boundary preserves silent montage on its own terms while handing Vertov's Enthusiasm to the sound-transition chapter",
    paragraphs: [
      "Chapter 9 ends at 1930 deliberately. Soviet filmmakers were already debating recorded sound, but synchronized sound reorganizes capture, editing, exhibition and theory enough to require a separate production history. BFI's early-sound survey identifies Vertov's Enthusiasm as a radical experiment in complementary and contrapuntal recorded sound, while Eisenstein and Pudovkin also argued against merely synchronizing dialogue and image. Those questions belong to Chapter 11 because their central production problem is the new recorded soundtrack, not because montage suddenly disappears when sound arrives.",
      "The boundary also prevents silent films from being retroactively treated as mute modern videos. Mother, Potemkin, October, Earth and Man with a Movie Camera circulated with live, commissioned or later accompaniment in varying combinations, and modern restorations often carry scores created long after photography and editing were completed. The chapter therefore separates silent-era accompaniment, later score reconstruction and synchronized production sound. A modern soundtrack can be historically and aesthetically important without becoming evidence that the original shoot used recorded dialogue or location sound.",
      "The legacy of Soviet montage is consequently framed as a set of enduring questions rather than a closed style period. How does an edit create causality or collision? How does nonfiction construction remain accountable to provenance? How do state institutions and censorship shape a film without fully determining form? How should collaborative labour be credited? How do Ukrainian and other regional institutions alter a Moscow-centered narrative? These questions continue into sound cinema, documentary, political film and modern editing practice, but the chapter closes with its own period evidence intact: seven playable Atlas anchors, fourteen book-level comparisons and ten institutional or theoretical objects that remain context rather than fake films.",
    ],
    sourceIds: ["ch9_early_sound_bfi", "ch9_peak_silent_bfi", "ch9_potemkin_version_bfi", "ch9_man_camera_recommends_bfi", "ch9_vertov_objects"],
  },
];
