import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterThreeMovementTwo: readonly FilmHistoryBookSection[] = [
  {
    id: "ch3_version_history_is_form_history",
    title: "6. Version history is part of form",
    sourceIds: ["ch3_loc_life_fireman", "ch3_bfi_innovators", "ch3_bfi_rover", "ch3_science_museum_rover"],
    paragraphs: [
      "Once films are connected across several shots, surviving order becomes historical evidence. Early cinema often reaches the present through paper prints, duplicate negatives, replacement negatives, fragments, reissues and later editorial interventions. A sequence that looks formally decisive today may not be identical to the version first sold or shown. This means that version history is not an archival appendix added after aesthetic analysis; it can determine the aesthetic analysis itself. Before a historian labels a cut parallel editing, repetition, continuity or flashback, the material relation among shots has to be established as carefully as possible.",
      "Two Chapter 3 cases make the problem especially clear. Life of an American Fireman became famous in part through a later re-edit that intercut interior and exterior rescue actions. Library of Congress and BFI scholarship show that the original construction instead completes the rescue inside and then repeats it from outside. Rescued by Rover poses a different version problem: Science Museum history records that extraordinary demand wore out negatives and forced the production to be re-shot. The title therefore refers not to one untouchable physical object but to a production that had to be reproduced again in order to keep circulating.",
      "These examples complicate any simple story in which technique can be read directly from a modern copy. Film history depends on identifying the status of the object: original order, contemporary replacement, later reconstruction or modern restoration. The rule is not that archives make formal interpretation impossible. It is that interpretation becomes stronger when it names its evidence. This chapter therefore treats copy history, catalogues, paper prints and reconstruction choices as part of the narrative-form problem. A history of editing that ignores how films survive risks describing the history of later archival decisions instead of the history of production."
    ]
  },
  {
    id: "ch3_life_fireman_repetition",
    title: "7. One rescue, shown twice",
    sourceIds: ["ch3_loc_life_fireman", "ch3_bfi_innovators", "ch3_afi_life_fireman", "ch3_moma_porter"],
    paragraphs: [
      "Edwin S. Porter's Life of an American Fireman is a useful test because the familiar modern expectation of cross-cut suspense can make its original structure seem strange. The Library of Congress copyright paper print and Charles Musser's BFI account establish that the rescue action was not originally intercut between interior and exterior. Instead, the action is completed from the inside and then replayed from the outside. The film asks the spectator to accept temporal overlap and repetition: the second view does not simply advance time but re-presents an event from another spatial position.",
      "That choice belongs to a production with substantial fire-service spectacle behind it. AFI preserves Edison catalogue material describing rehearsals, participation by several city fire departments and hundreds of firefighters. The scale of the operation reminds us that early narrative form was not just an editing-room abstraction. Staged emergency action had to be organized for the camera, and different views could be treated as complete scenes. Showing the rescue twice preserves the integrity of each staged tableau while offering a second spatial understanding of the same event.",
      "The later cross-cut version is historiographically important because it demonstrates how modern expectations can rewrite evidence. Once the rescue was intercut, Porter appeared to have anticipated a later convention more completely than the original material supports. The correct conclusion is not that the original film is less sophisticated. Its repetition solves a different problem: how to provide multiple spatial accounts of one event while preserving scene completeness. By teaching that structure explicitly, the chapter replaces a false invention story with a more interesting history of competing ways to organize time and space."
    ]
  },
  {
    id: "ch3_great_train_multi_scene",
    title: "8. Causal action across a larger world",
    sourceIds: ["ch3_loc_great_train", "ch3_moma_great_train", "ch3_bfi_innovators"],
    paragraphs: [
      "The Great Train Robbery expands causal action across a more varied set of locations and production techniques. Library of Congress and MoMA records connect Edison studio interiors with New Jersey exterior work, railway action, moving-train photography, double exposure and hand-applied colour. The story passes from robbery preparations to the train, escape, pursuit and confrontation. What holds the film together is not a modern rulebook but the repeated causal question of what the robbers do next and how the consequences catch up with them. Location changes enlarge the story world because action gives each new space a purpose.",
      "The film also resists one of the most persistent early-cinema myths: that Porter simply invented narrative editing. Musser's BFI analysis places the film within historically specific temporal organization before later continuity practices became standardized. The famous bandit image, in which a gun is fired toward the camera, could be placed flexibly by exhibitors rather than functioning as one fixed point in a modern internally closed narrative. That direct address is not an embarrassing leftover that continuity had not yet eliminated. It shows that attraction and narrative could coexist in the same commercial object.",
      "For production history, the film demonstrates integration across departments before those departments had later studio-era identities. Location access, railway movement, staging, camera effects, action timing and scene order all contribute to narrative scale. The story feels larger not merely because it has more shots, but because each shot extends a chain of action into a different physical environment. This is one route by which early filmmakers made screen worlds more expansive: they did not need to erase discontinuity; they needed to make the spectator understand why the story had moved."
    ]
  },
  {
    id: "ch3_rover_route_continuity",
    title: "9. A route becomes a narrative structure",
    sourceIds: ["ch3_bfi_rover", "ch3_sase_rover", "ch3_dfi_rover", "ch3_science_museum_rover"],
    paragraphs: [
      "Rescued by Rover turns geography itself into a repeated causal pattern. After the child is taken, Rover travels from the family home through a sequence of recognizable spaces to find the child, returns to bring the father, and then travels the route again. BFI Screenonline emphasizes the clarity of this multi-shot storytelling. Stable landmarks and repeated movement make the route memorable, so the spectator can compare one journey with the next. The film's continuity does not depend only on smoothing individual cuts; it depends on building a spatial model that can be traversed more than once.",
      "The dog performer Blair is central to that system. Rover's goal-directed movement makes causality visible across shots: leave, search, discover, return, lead, rescue. Animal performance, location choice and editing therefore become inseparable. Screen Archive South East and the Danish Film Institute provide independent identity and production checks for the Hepworth/Fitzhamon film, while Science Museum history documents the material consequence of its popularity: negatives wore out and the film had to be re-shot. The narrative route had to be reproducible not only for spectators but for production itself.",
      "That replacement history is particularly revealing. A film celebrated for stable geography exists through multiple acts of rebuilding the same geography for the camera. Continuity is therefore both a screen effect and a production discipline. Performers have to repeat paths; camera positions and staging have to restore recognizable relations; the finished order has to preserve the route. Rescued by Rover is consequently a stronger bridge toward systematic continuity than a simplistic claim that one cut suddenly invented the principle. It shows how repeated action, material reproducibility and spectator memory reinforce one another."
    ]
  },
  {
    id: "ch3_histoire_memory_time",
    title: "10. The past can enter the present",
    sourceIds: ["ch3_cnc_histoire", "ch3_pathe_history", "ch3_fondation_pathe", "ch3_grimh_histoire", "ch3_bloomsbury_french_cinema"],
    paragraphs: [
      "Ferdinand Zecca's Histoire d'un crime adds a temporal problem that cannot be reduced to route continuity. The film organizes crime, arrest, imprisonment, represented recollection and execution into a longer multi-tableau causal structure. CNC identifies the 1901 Pathé social drama and emphasizes increased footage, multiple tableaux and public success. The story does not simply move from one present action to the next. During the prison episode, the condemned man's earlier life becomes visible as a distinct scenic layer while his present confinement remains part of the composition. Past experience is staged as something the spectator can see inside the narrative present.",
      "It is tempting to translate this immediately into the later term flashback and then search for a first. That would be historically imprecise. The scholarly reference material used by the Production Case describes two scenic sets visible within the composition, and the film's method remains close to theatrical/scenic presentation even as it creates retrospective narration. The important achievement is not ownership of a universal device but the ability to differentiate temporal levels and make their relation intelligible. The spectator understands that one visible action belongs to a remembered or earlier time and that it explains the condemned man's present trajectory.",
      "Pathé's industrial context is equally important. Company and foundation histories place Zecca inside a newly organized film-production service and an expanding catalogue of differentiated genres. Narrative length and complexity could develop because production itself was becoming more systematic. Histoire d'un crime therefore links form to institution: longer fiction, genre organization, production leadership and circulation create conditions in which a story can contain both present action and represented past. The chapter's anti-myth rule is explicit: describe this as an important early experiment in narrative time and represented memory, not as an uncontested invention of 'the first flashback.'"
    ]
  }
];
