import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterTwoMovementOne: readonly FilmHistoryBookSection[] = [
  {
    id: "exhibition-makes-cinema-recurring",
    title: "1. A medium becomes a public habit",
    sourceIds: [
      "nsm_short_history_cinema",
      "loc_variety_stage_context",
      "loc_vitascope_shift",
      "cinematheque_1896_expansion",
    ],
    paragraphs: [
      "The history of cinema changes when the unit of analysis moves from the individual film to the event in which a film was seen. A strip of photographed images could exist without creating a stable public medium. For cinema to become a habit, somebody had to secure a room or a booth, obtain or operate a projector, advertise a show, assemble enough material to sustain attention, set a price, control light and sightlines, and persuade an audience that the experience was worth repeating. These tasks belonged largely to exhibitors and showmen. Their work is easy to underestimate because later film culture encourages us to imagine that a completed feature simply arrives at a cinema and retains the same identity everywhere. In the late 1890s and early 1900s, however, the public event often had a much looser relationship to any single title. A programme might combine several short moving pictures with live acts, music, explanation, slides or other attractions. The institution of cinema was therefore built not only by inventors and producers, but by people who made projection recur.",
      "This perspective also makes the famous dates of 1895 and 1896 more useful. The Lumière programme at the Salon Indien of the Grand Café in Paris on 28 December 1895 became one of the most durable symbols of projected cinema, while the Vitascope exhibition at Koster and Bial's Music Hall in New York on 23 April 1896 became a corresponding American landmark. Both mattered, but neither should be treated as a universal birthday. Projection experiments and public demonstrations occurred through several competing systems, and the Library of Congress explicitly places the Vitascope beside the Eidoloscope, Cinématographe, Kineopticon and Biograph rather than at the beginning of a single uncontested line. The National Science and Media Museum likewise presents early cinema as a convergence of machines and practices. What distinguishes the successful moments is less that no one had projected an image before than that projection became commercially repeatable, reproducible and mobile enough to enter existing entertainment circuits.",
      "Existing entertainment institutions mattered because a new visual technology did not need to build an audience from nothing. Music halls, vaudeville theatres, fairgrounds and travelling shows already knew how to gather crowds, schedule acts and turn novelty into revenue. The Library of Congress describes American vaudeville managers as eager to book projected moving pictures after hearing of their success in London music halls. A projector could be marketed as a spectacular act within a bill that also contained singers, comedians, dancers and specialty performers. This meant that early motion pictures entered a world whose basic economic unit was often the programme rather than the autonomous film. A customer bought an evening or a sequence of attractions. The moving picture competed with the acts around it for attention, but it also benefited from their established venues, advertising and audience expectations. Exhibition was not a passive endpoint after production. It was an institution capable of shaping what kinds of films producers had reasons to supply.",
      "The geography of early exhibition followed this flexibility. The National Science and Media Museum notes that short films could be shown at fairgrounds, music halls or wherever a screen could be erected and a room sufficiently darkened. Such portability helps explain why the medium spread quickly without waiting for a standardized purpose-built cinema chain. A film could travel with an exhibitor; a projector could enter a theatre whose primary identity was not cinematic; a temporary booth could appear at a fair; a local hall could become a film venue for one evening. Different sites created different conditions of attention. A music-hall audience encountered films among live performances. A fairground patron encountered a showfront, barkers and competing attractions. A local community might attend because the programme contained images filmed in its own streets. The same technological category—projected motion pictures—therefore produced several social experiences rather than one fixed mode of spectatorship.",
      "The central argument of this chapter follows from that variety. Cinema became a mass medium not only because films could be made, but because exhibitors assembled programmes, adapted presentation to particular venues and cultivated audiences whose demand reshaped production and distribution. The chapters around this one divide the problem deliberately. Chapter 1 established the material and production conditions that made moving photographs repeatable. Chapter 3 will examine the growth of staged fiction and more systematic narrative organization. Here the question is what happened between camera and spectator: how films circulated, how programmes were constructed, how live presentation altered the event, how local and event films recruited audiences, and how recurring exhibition created a market hungry for new material. Only by studying that middle layer can we explain why moving pictures became something people expected to see again rather than a novelty encountered once.",
    ],
  },
  {
    id: "projection-is-a-programme",
    title: "2. Projection is a programme, not just a machine",
    sourceIds: [
      "nsm_lumiere",
      "cinematheque_machine_cinema",
      "loc_koster_bial_treasures",
      "loc_vitascope_shift",
    ],
    paragraphs: [
      "A projector is often treated in technological history as the decisive object: once a machine can enlarge moving photographs onto a screen, collective cinema supposedly exists. Yet the first successful projection systems immediately reveal why that account is incomplete. A projector does not decide what the audience sees first, how long the event lasts, whether an image is repeated, what accompanies it or how several films relate to one another. Those choices belong to a programme. The Lumière operation demonstrates the distinction clearly. The Cinématographe combined camera, printing and projection functions in a portable system, but its commercial force came from an organized supply of short views and from programmes that could be exhibited repeatedly. The famous Grand Café event was not the unveiling of one master film. It offered a set of brief subjects whose accumulated variety—workers, family scenes, comic action and other views—made the moving-image show itself the attraction.",
      "The Vitascope's New York debut likewise entered an already structured evening of entertainment. The Library of Congress records the 23 April 1896 event at Koster and Bial's Music Hall as a theatrical exhibition in a vaudeville setting. Its surviving contextual material emphasizes the visual framing of projection: the image appeared on a screen within a gilt frame, making the technological novelty resemble a picture that had come alive. The bill included several short subjects rather than a single long work, and the venue supplied a ready audience accustomed to variety. Film subjects and stage culture overlapped as well. Performers familiar from theatre and vaudeville could become motion-picture attractions, and stage material could be recreated before the camera. The new medium was therefore not culturally isolated from the institutions that housed it. Projection inserted recorded performance and photographed movement into an entertainment ecology that already understood how to package multiple attractions together.",
      "The difference between a programme and a later feature is important for historical interpretation. When viewers today encounter an early film in an archive, on a streaming page or in a classroom, the film often appears alone, with a canonical title and a stable runtime. That presentation can make the surviving item seem more self-contained than it originally was. In exhibition, a brief film could function as one component among many. Its effect depended partly on what came before and after, on whether the exhibitor repeated a popular subject, and on the live framing supplied by the venue. A train view placed among travel pictures could belong to a geographical sequence; the same image inserted into a mixed novelty bill might function primarily as a display of movement and depth. A local actuality could be valuable not because its formal construction was unique but because the audience recognized people and places. Programme history asks what a film did in a particular show rather than assuming that its archival identity exhausted its meaning.",
      "This does not mean that early films lacked form or intention. The programme model should not dissolve production into exhibition. Producers composed individual shots, staged performances, selected locations and designed effects with care, and some films rapidly became valuable attractions in their own right. The point is that production and exhibition remained unusually permeable. A successful subject could circulate internationally, be advertised under varying titles, appear in different sequences and acquire different accompaniment. An exhibitor's practical needs—freshness, variety, recognizable subjects, topical events, comedy, spectacle—became signals to producers. A company that could provide many kinds of films had an advantage because programmes required replenishment. The catalogue therefore functioned as more than a list of completed works: it was a menu from which exhibitors could build an event.",
      "Understanding projection as programme also changes how we interpret authorship. The filmmaker determined photographed content, but the exhibitor could influence the spectator's temporal experience by choosing order and context. This was not modern editing in the sense of physically joining shots inside a canonical print, yet it was a form of arrangement. The distinction matters because we should neither exaggerate exhibitor power into a claim that films had no identity nor ignore it by projecting later feature-film norms backward. Early cinema involved several levels of organization at once: the shot, the film, the catalogue, the programme and the live event. Chapter 3 will focus on how relationships among shots became increasingly systematic inside films. This chapter remains one level outside the print, where the order of films and attractions could itself create rhythm, contrast and expectation.",
    ],
  },
  {
    id: "exhibitor-as-programme-editor",
    title: "3. The exhibitor as programme editor",
    sourceIds: [
      "loc_vitascope_shift",
      "loc_edison_catalogue_context",
      "loc_variety_stage_context",
      "loc_great_train_robbery",
    ],
    paragraphs: [
      "The Edison catalogue and Vitascope history make exhibitor agency unusually concrete. The Library of Congress notes that exhibitors could select films from Edison inventory and sequence them in whatever order they wished. That sentence describes a business arrangement, but it also has aesthetic consequences. The producer supplied discrete units; the exhibitor built a temporary whole. A show could alternate comedy and actuality, cluster travel views, emphasize topical material or place a striking attraction near the end. The logic resembles programming in broadcasting, festivals or online playlists more than the later assumption that one feature determines the principal duration and sequence of a cinema visit. It also means that demand was granular. An exhibitor could notice that a certain kind of subject worked well and order more of it without committing to a complete standardized feature package.",
      "Catalogue culture helped make this possible. Producers and distributors needed ways to describe films to buyers and exhibitors who might never have seen the material. Titles, synopses, lengths and promotional descriptions converted photographed events into commercial units. The language of catalogues could be exuberant because it had to sell an attraction in advance: a comic situation might be summarized around its payoff, an actuality around the fame or recognizability of its subject, and a trick film around the marvel it promised. Such descriptions are historically valuable, but they must be read as sales documents rather than transparent interpretations. They reveal what suppliers thought exhibitors might value. They also remind us that circulation relied on information systems—catalogues, correspondence, agents and publicity—as much as on physical prints.",
      "The Great Train Robbery provides a compact illustration of why flexible presentation should not be mistaken for a flaw. Its famous close view of the bandit firing toward the camera has often been absorbed into modern memories of a fixed ending. Edison catalogue material, however, allowed the shot to be shown at either the beginning or the end of the film. The point is not that every shot in every film floated freely. Most of the picture's action depends on an intelligible sequence. Rather, one spectacular direct-address attraction retained a degree of programmability around the narrative body. The case is useful because it sits at the boundary explored by Chapters 2 and 3: a film can develop increasingly organized story relations while exhibition still preserves options associated with attraction and showmanship.",
      "Programme editing could also respond to place. A travelling exhibitor entering a town might foreground locally photographed material because recognition promised immediate attention, then surround it with comedy, news or imported spectacle. A metropolitan music hall might sell projection as one novelty among famous live acts. A storefront theatre later depended more heavily on a regular flow of films because it had to fill repeated shows throughout the day. These contexts generated different programming pressures. The word exhibitor therefore covers people and businesses with unequal resources and different strategies. Some owned or controlled venues; some travelled with equipment; some commissioned films; some relied on catalogues and exchanges. Treating them all as identical would reproduce the same simplification this chapter is trying to avoid.",
      "For film history, the exhibitor-as-editor model offers a safeguard against teleology. It prevents us from assuming that cinema was always heading toward one feature, one scheduled start time and one stable projection copy. Those arrangements eventually became powerful, but they emerged through industrial change. In the period covered here, short films and mixed programmes made flexibility commercially useful. The historical question is therefore not why early exhibitors failed to respect the integrity of a feature-film text that had not yet become dominant. It is how their freedom to choose and arrange material helped establish audience expectations, created markets for particular subjects and encouraged producers to supply a growing repertoire. Programme construction was part of the medium's development because it converted a catalogue of possibilities into an actual social encounter.",
    ],
  },
  {
    id: "showmanship-publicity-live-frame",
    title: "4. The show before the film",
    sourceIds: [
      "loc_koster_bial_treasures",
      "loc_vitascope_poster",
      "nsm_short_history_cinema",
      "bfi_sedgwick_showfront",
    ],
    paragraphs: [
      "Before a projected image could impress an audience, the audience had to enter. Early film exhibition was therefore also a history of showfronts, posters, announcements, barkers, venue reputation and visual promise. Surviving Vitascope publicity at the Library of Congress shows that promotion did not merely identify a machine; it inserted the machine into an established graphic culture of attractions. Koster and Bial's could advertise moving pictures within the same theatrical economy that sold performers and novelty acts. At a fairground the architecture itself could become advertising. Painted façades, lights, organs, displayed names and the activity around an entrance turned a bioscope show into a spectacle before the screen was visible. The boundary between marketing and exhibition was porous because anticipation was part of the purchased experience.",
      "The surviving film of Sedgwick's Bioscope Showfront at Pendlebury Wakes is valuable precisely because it directs attention away from the screen. The BFI describes the showfront's activity as a warm-up intended to entice crowds and situates the film within the fairground relationships that were crucial to Mitchell and Kenyon's business. In this book it remains a P2 reference rather than a required Production Case because its primary function is evidentiary: it lets us study the infrastructure and performance surrounding films. The distinction embodies a rule for the Film Atlas. A historically important projector, poster, booth or programme should not be turned into a fake film production merely to make it playable. Some objects belong in the book because they explain the system around films.",
      "Showmanship also continued after a customer entered. The National Science and Media Museum emphasizes that early projected films could be accompanied by lectures, music and substantial audience participation. An exhibitor or lecturer might identify places, explain topical events, add jokes or guide attention. Musicians could supply mood and rhythm. The audience itself contributed noise, commentary and response. The common label silent cinema is therefore technically useful only if it refers to the absence of recorded synchronized dialogue on the film; it becomes misleading when it imagines a silent room. The historical event was frequently sonically active. Because accompaniment could vary from one venue or performance to another, no single reconstructed soundtrack should automatically be treated as the original universal sound of a film.",
      "The live frame could also change the social meaning of photographed material. A film of a distant place might be introduced as education, travel, imperial spectacle or novelty depending on the speaker and programme. A prizefight film could be accompanied by expert commentary that helped spectators follow an event. A local film could be announced in a way that invited recognition and collective reaction. Comedy might be amplified by a performer's patter or by an audience already familiar with a character type. These examples show why spectatorship cannot be reconstructed from the image alone. The print is evidence of what was photographed and assembled; the exhibition context is evidence of how that material was made present to a particular crowd.",
      "Showmanship therefore links several systems that later histories often separate. Publicity recruits the audience; architecture organizes approach and visibility; programming determines sequence; live performance frames meaning; projection technology constrains the image; and ticketing turns attention into revenue. None of these replaces the film, but together they explain how films acquired social force. They also establish the transition to the next movement of this chapter. Once exhibitors understood that locality, topicality and recognizable events could draw paying spectators, some producers began making films specifically around those commercial relationships. Mitchell and Kenyon's local actualities and the extraordinary scale of The Corbett–Fitzsimmons Fight show two different ways in which an anticipated audience could shape production before the camera started.",
    ],
  },
];
