import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterSevenMovementThree: readonly FilmHistoryBookSection[] = [
  {
    id: "ch7_mabuse_finance_surveillance",
    title: "11. Mabuse turned finance, disguise and surveillance into a modern urban control system",
    paragraphs: [
      "Dr. Mabuse, the Gambler expands the chapter from architectural modernism toward systems of information and control. Fritz Lang's two-part crime film makes its criminal protagonist powerful not through one location or weapon but through the ability to manipulate markets, identities, documents, hypnosis and social networks. filmportal records the Uco/Decla-Bioscop context, Erich Pommer's production role and the two-part 1922 release. The subtitle 'A Picture of Our Time' is therefore productive rather than merely promotional: the film organizes anxieties about speculation, unstable identity and urban anonymity into a serial-scale production whose many settings and disguises have to remain causally legible.",
      "The comparison also prevents the chapter's account of Weimar modernity from being confined to distorted sets. Mabuse moves through clubs, financial spaces, private rooms and criminal infrastructures, and the fiction's power comes from the relation among those spaces. Disguise requires makeup, costume and performance continuity; market manipulation requires intertitles and props that communicate information; surveillance requires eyelines, hidden observation points and editing that tells the viewer who controls knowledge. The film's spectacle is organizational. Its production problem resembles a network more than a single iconic image, which is why it belongs in the book even though Fantômas and later Lang cases already cover much of that gameplay territory in the Atlas.",
      "Restoration again complicates the object under discussion. filmportal distinguishes the original silent parts from later digitized reconstructions and records materially different durations. The chapter uses those records to keep modern access copies separate from the production event. It also avoids reading every image as a coded prediction of dictatorship. Mabuse can illuminate fears about authority, markets and manipulation in the early republic without becoming a mystical forecast of 1933. A stronger historical method asks how contemporary institutions and genre conventions made such fantasies intelligible, then traces later political interpretations as reception history rather than destiny embedded in the negative.",
    ],
    sourceIds: ["ch7_mabuse_one_filmportal", "ch7_mabuse_two_filmportal", "ch7_weimar_filmportal", "ch7_weimar_moma"],
  },
  {
    id: "ch7_inflation_street_realism",
    title: "12. Inflation and stabilization changed the social worlds that late-Weimar films could stage",
    paragraphs: [
      "The economic crises of the 1920s were not simply atmospheric explanations for dark imagery. They altered production costs, company finances, social experience and the subjects filmmakers could make recognizable to audiences. The Joyless Street stages a Vienna marked by inflation, scarcity, speculation and sharply unequal access to food and money. filmportal records G. W. Pabst's 1925 production and its censorship history while contemporary reviews preserved there describe the film as a recent social image shaped by the memory of inflation. The value of the film is not that it photographs economic reality transparently, but that it converts material insecurity into queues, interiors, clothing, exchange and unequal control over bodies.",
      "filmportal's broader Weimar history warns against treating Pabst's social films as the simple opposite of Expressionism. The label Neue Sachlichkeit can name an important turn toward social observation and material environments, but staging remains highly designed. The Joyless Street was shot in Berlin while representing Vienna; sets, lighting and star performances organize the viewer's access to poverty and luxury. Realist effect is therefore produced. This matters for gameplay because 'use real locations' is not a sufficient realism mechanic. Social realism depends on research, casting, design, costume, blocking and narrative selection that make structures of inequality visible without claiming that fiction has become unmediated evidence.",
      "Stabilization also changed the industrial environment. filmportal's chronology for the middle and late 1920s places prestigious UFA production alongside changing currency conditions, export ambitions and the growing importance of international competition. Chapter 7 uses macroeconomic context sparingly and chronologically: hyperinflation does not explain every film made in 1927, and the Dawes-era stabilization did not remove inequality. Economic history is most useful when it clarifies specific production constraints, market strategies or represented experiences. It becomes misleading when it is used as a universal mood generator that supposedly caused an entire national cinema to look anxious.",
    ],
    sourceIds: ["ch7_joyless_filmportal", "ch7_joyless_review", "ch7_weimar_filmportal", "ch7_weimar_classical_avant", "ch7_1925_1934_filmportal"],
  },
  {
    id: "ch7_pabst_pandora_performance",
    title: "13. Pabst and Pandora's Box shifted emphasis from graphic distortion to performance and social proximity",
    paragraphs: [
      "Pandora's Box is the chapter's strongest playable counterweight to Expressionism because its central production resource is not a visibly distorted world but a network of people whose desires, dependencies and social positions keep changing. filmportal records Seymour Nebenzahl's Nero-Film production, G. W. Pabst's direction, Ladislaus Vajda's screenplay work, Günther Krampf's photography and the Filmwerke Staaken shoot. Louise Brooks enters that system as a transatlantic star whose movement and direct physical presence alter the texture of the German silent film. The case therefore asks how framing, blocking and environment can keep relationship power legible without turning the performer into an object scored for attractiveness.",
      "Pabst's association with Neue Sachlichkeit is historically useful only if it remains bounded. filmportal's biography describes his socially critical realism and contrasts it with Expressionist fantasy, while BFI emphasizes the naturalism of Brooks's performance. Yet Pandora's Box is still carefully staged melodrama: interiors are designed, encounters are composed, and the route from bourgeois rooms through courtroom, gambling and London poverty is a constructed dramatic descent. The lesson is not 'realism replaces style.' It is that style can move toward behavioral observation and social geometry while remaining dependent on studio craft, editing and highly selective narrative organization.",
      "The film's reception and version history also resist easy canonization. filmportal preserves contemporary criticism that was far from uniformly admiring and documents separate original, American, television and later reconstruction states. Modern recognition of Brooks and Pabst cannot be back-projected as unanimous 1929 judgment. This distinction matters pedagogically because canons are histories of rediscovery as well as production. Pandora's Box became a durable reference for performance, sexuality and Weimar modernity through preservation and changing critical values, not because everyone at the premiere already agreed on the meaning it would hold a century later.",
    ],
    sourceIds: ["ch7_pandora_filmportal", "ch7_pabst_filmportal", "ch7_brooks_filmportal", "ch7_pabst_bfi", "ch7_pandora_review"],
  },
  {
    id: "ch7_gender_censorship_diary",
    title: "14. Gender, sexuality and censorship were production conditions—not decorative signs of decadence",
    paragraphs: [
      "Weimar cinema's treatment of gender and sexuality is often flattened into a retrospective image of urban permissiveness. The historical record is more contested. filmportal notes that the republic's early abolition of state censorship was followed by the Reichslichtspielgesetz of 1920, restoring a formal censorship regime. Films could address prostitution, same-sex desire, reproductive politics and changing gender roles, but those subjects moved through institutions that could restrict audiences, demand alterations or reshape circulation. Chapter 7 therefore treats sexual modernity as a field of representation and regulation rather than as proof that all of Weimar culture shared one liberated position.",
      "Pandora's Box makes this especially visible through Countess Geschwitz and Lulu. The Production Case acknowledges the historical importance of same-sex desire without turning queerness into exotic decoration, penalty or reward. Diary of a Lost Girl extends the comparison through another Pabst-Brooks collaboration centered on sexual coercion, institutional discipline and the social category of the 'fallen woman.' filmportal records the 1929 production and its censorship documentation, while Pabst's biography notes the film's conflict with censors and fragmentary survival. In both cases, ethical study requires distinguishing what the films reveal about their period from what their plots may reproduce about punishment, stigma and gendered vulnerability.",
      "This approach also changes how star studies enter the chapter. Brooks's bob, face and movement have become iconic, but iconography alone can reproduce the same objectification that historical analysis is supposed to examine. The relevant production question is how casting, costume, gesture, eyeline, framing and publicity construct screen identity, and how those decisions interact with narrative power. The chapter therefore refuses appearance scoring and avoids presenting queer identity or sexual exploitation as imitable creative shortcuts. Representation belongs to craft analysis because craft determines who is granted agency, who is made visible as a threat or desire, and whose vulnerability becomes spectacle.",
    ],
    sourceIds: ["ch7_weimar_filmportal", "ch7_pandora_filmportal", "ch7_diary_filmportal", "ch7_pabst_filmportal", "ch7_weimar_kinemathek"],
  },
  {
    id: "ch7_asphalt_city_transition_legacy",
    title: "15. Asphalt's artificial street and the sound threshold reveal a cinema changing without a clean break",
    paragraphs: [
      "Asphalt closes the chapter because it joins late-silent social modernity to one of UFA's most spectacular acts of studio construction. filmportal identifies Joe May's 1929 street film and Günther Rittau's cinematography, while a contemporary production report preserved by the archive describes an enormous urban set extending through multiple Neubabelsberg stages and outward through opened studio doors. The design had to match interior and exterior light so the constructed boulevard would read as continuous metropolitan space. Here realism depends on artificiality: department stores, traffic, hotels and intersections are manufactured at scale to produce the sensation of an observed modern city.",
      "That paradox summarizes much of the chapter. Caligari advertises its artificial surfaces; Nosferatu charges real locations with the uncanny; The Last Laugh makes a hotel set support mobile subjectivity; Metropolis builds a city that cannot exist; Pandora's Box uses controlled environments to make relationships feel behaviorally immediate; Asphalt constructs a realistic street in a studio. 'Real' and 'Expressionist' are therefore not opposite technical settings. Weimar production repeatedly combines location, construction, performance, optical work and photography according to different dramatic aims. The useful distinction is not between truth and artifice, but between historically specific systems for making an image persuasive.",
      "The year 1929 also marks a technological transition rather than an instant extinction of silent practice. filmportal's chronology records the expansion of German sound production and the Tobis-Klangfilm system while silent features such as Asphalt, Pandora's Box and Diary of a Lost Girl were still appearing. The chapter ends at this threshold deliberately. Sound would reorganize studios, acting, camera mobility, language markets and exhibition, but it did not erase the personnel or visual knowledge of the 1920s. The transatlantic careers of Murnau, Freund and other Weimar workers further show techniques moving across borders. Later restorations keep that inheritance visible, provided we distinguish reconstructed music and digital presentation from what was photographed and exhibited in the silent era.",
    ],
    sourceIds: ["ch7_asphalt_filmportal", "ch7_asphalt_report", "ch7_1929_filmportal", "ch7_weimar_revisited", "ch7_murnau_moma"],
  },
];
