import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterTenMovementOne: readonly FilmHistoryBookSection[] = [
  {
    id: "ch10_survival_not_map",
    title: "1. The surviving silent canon is an archive-shaped sample, not a map of everything that was produced",
    paragraphs: [
      "Chapter 10 begins with absence because any global history of silent cinema is distorted if survival is treated as neutral. Film Heritage Foundation estimates that only a tiny fraction of India's silent output survives complete, while BFI notes that only fragments remain of Raja Harishchandra. Similar losses structure Japanese, Chinese, Australian, Scandinavian and Mexican film history. Cellulose-nitrate decay, fire, commercial disposal, war, political disruption, reuse of prints and the absence of early preservation institutions all determined what later historians could see. A surviving title can be exceptionally valuable without being statistically representative of the industry that produced it.",
      "Restoration history makes the same point from another direction. The Swedish Film Institute describes nitrate collections moving among archives and restored silent classics emerging from surviving negatives and prints; Australia's NFSA reconstructed The Sentimental Bloke from materials located across institutions; Cineteca Nacional rebuilt El automóvil gris by stabilizing and reintegrating material from a complex serial history. These are not invisible technical services that simply return an original object to us. Archivists choose sources, compare versions, reconstruct intertitles, infer color systems and document gaps. The modern film text is therefore often a historically reasoned assembly whose provenance must remain visible.",
      "The production-game consequence is strict. Atlas cases are not awarded merely because a film survived, and missing films are not treated as historically unimportant. The Burning of the Red Lotus Temple and Raja Harishchandra remain book-level evidence precisely because fragmentary or lost material cannot support a fabricated complete Production Case. Conversely, A Page of Madness, Red Heroine and The Sentimental Bloke are taught with their rediscovery and restoration histories attached. The chapter asks what evidence survives, who preserved it, which version is being analyzed and what claims remain impossible—not how confidently a modern database can fill every blank.",
    ],
    sourceIds: ["ch10_india_nitrate_fhf", "ch10_raja_bfi", "ch10_sweden_archive_sfi", "ch10_bloke_restore_nfsa", "ch10_auto_cineteca", "ch10_page_nfaj"],
  },
  {
    id: "ch10_denmark_sweden_industries",
    title: "2. Denmark and Sweden built exportable star, studio and prestige systems before the familiar Hollywood-centered silent canon hardened",
    paragraphs: [
      "A global silent history does not begin by leaving Europe; it begins by refusing to make Hollywood and central Europe the only European baseline. Danish film history records a powerful export industry in the 1910s, with companies, genre cycles and stars circulating internationally. Asta Nielsen's breakthrough in Urban Gad's Afgrunden demonstrates how screen performance, erotic melodrama and international star identity could become industrial assets. DFI records the film's 35mm silent production, Alfred Lind's cinematography and its later preservation problems, while its history of Danish cinema places Nielsen and other stars inside a broader commercial system rather than treating them as isolated artistic exceptions.",
      "Sweden developed a different prestige model through companies, literary adaptation, landscape shooting and internationally recognized directors and cinematographers. The Swedish Film Institute describes the period associated with Victor Sjöström, Mauritz Stiller and the Jaenzon cinematographers as the Swedish silent golden age, while its archive history records later restorations of Körkarlen, Herr Arnes pengar, Erotikon and Gösta Berlings saga. The point is not that Swedish cinema possessed one national style. Social melodrama, comedy, supernatural narrative and literary epic used different combinations of location, performance, design and photography even when they shared institutions and personnel.",
      "Afgrunden and The Phantom Carriage therefore function as playable anchors without exhausting Scandinavian silent cinema. Afgrunden exposes the relation between performer, melodrama, circulation and preservation; The Phantom Carriage anchors literary adaptation and photographic effects. Ingeborg Holm, The Outlaw and His Wife, Sir Arne's Treasure, Erotikon and Gösta Berling's Saga remain comparative films because they broaden the system rather than introducing production problems that require duplicate gameplay. The book can preserve a dense industrial and aesthetic field while Atlas remains selective about what becomes a scenario.",
    ],
    sourceIds: ["ch10_afgrunden_dfi", "ch10_asta_dfi", "ch10_danish_history_dfi", "ch10_sweden_golden_sfi", "ch10_sweden_archive_sfi"],
  },
  {
    id: "ch10_norway_growth_location",
    title: "3. Growth of the Soil makes Norwegian literary prestige, Nordland location production, color treatment and film music one fragile production system",
    paragraphs: [
      "Markens grøde is useful precisely because early Norwegian production operated at a different scale from the larger Danish and Swedish industries. Nasjonalbiblioteket identifies Gunnar Sommerfeldt as director, screenwriter and production leader for Norrøna Film, George Schnéevoigt as cinematographer and Leif Halvorsen as composer. The adaptation of Knut Hamsun's novel was an ambitious prestige project whose production depended on extensive location work and an unusually long feature format. DFI's presentation history emphasizes Nordland landscapes, while Nasjonalbiblioteket records a Boxing Day 1921 premiere and contemporary expectations around a major literary adaptation.",
      "The film also makes the word 'silent' materially inadequate. Nasjonalbiblioteket preserves Halvorsen's original 1921 film music and orchestral instrumentation, while the national filmography classifies the film as silent and tinted or toned. Music was part of exhibition but not synchronized production dialogue; tinting and toning altered the projected image without making the film a modern color-photography production. Those distinctions matter because later recordings and digital restorations can otherwise be back-projected into the shoot. The chapter treats score, image coloration and projection as coordinated historical presentation layers whose production provenance can differ.",
      "Survival complicates the case further. DFI records that the film was long regarded as lost and that reconstruction depended on material located in New York and Amsterdam; modern Norwegian presentations also document missing and reordered material in earlier versions. A modern 117-minute presentation is therefore a usable archive state, not proof of one untouched 1921 master. The chapter keeps later debates around Hamsun's politics and representation ethically visible without inventing them as causal intentions in a production made years before his later political commitments. Historical hindsight constrains interpretation; it does not rewrite the evidence chain.",
    ],
    sourceIds: ["ch10_growth_nb", "ch10_growth_nb_music", "ch10_growth_dfi", "ch10_growth_dfi_cinema", "ch10_growth_nb_1921"],
  },
  {
    id: "ch10_japan_benshi_system",
    title: "4. Japanese silent cinema joined studio production to benshi performance, making exhibition a co-authored event rather than a mute image track",
    paragraphs: [
      "Japanese silent cinema developed within institutions and performance practices that make a simple sound-versus-silence binary misleading. BFI's work on benshi explains that narrators could voice characters, explain settings and shape moral or emotional interpretation, sometimes becoming attractions in their own right. NFAJ's national-history exhibition places early Japanese films, stars, scripts and surviving materials inside a broader institutional history rather than treating benshi as an exotic accessory. A film print was therefore only one component of a historical screening event that could include spoken narration, music, translated or absent intertitles and local performance conventions.",
      "A Page of Madness makes this especially clear. The surviving version's lack of conventional intertitles can appear radically opaque to a modern viewer, yet BFI notes that original exhibition operated in a culture where benshi could supply narrative explanation. Aaron Gerow's research further shows that the film surviving after Kinugasa's rediscovery is not simply identical to the 1926 release. The correct historical question is not why Japanese audiences tolerated an incomprehensible avant-garde object, but how image construction, live narration, publicity, venue and contemporary knowledge interacted in exhibition. Missing intertitles are not automatically missing data.",
      "The same principle extends beyond one avant-garde film. NFAJ's material on Tsumasaburo Bando and BFI's discussion of Orochi show star-company production and later benshi traditions intersecting with jidaigeki and chanbara. Exhibition history must therefore remain distinct from production sound: a 1965 or modern benshi commentary can illuminate a silent film tradition without becoming evidence of synchronized 1925 audio. The chapter treats benshi as institutional and performative labor, credits it where documented, and refuses to score Japanese films as incomplete merely because their historical presentation system differs from later standardized sound cinema.",
    ],
    sourceIds: ["ch10_nfaj_history", "ch10_page_bfi_player", "ch10_page_umich", "ch10_page_nfaj", "ch10_orochi_nfaj_bantsuma", "ch10_orochi_bfi_year"],
  },
  {
    id: "ch10_page_madness_modernism",
    title: "5. A Page of Madness turns independent production, collaborative modernism, mental-institution imagery and rediscovery into one evidence problem",
    paragraphs: [
      "A Page of Madness is often introduced as Japanese Expressionism or as a surreal asylum nightmare, but its production history is more specific. NFAJ records Teinosuke Kinugasa's independent National Art Film/Shinkankakuha context and credits writing and adaptation labor across Yasunari Kawabata, Kinugasa, Minoru Inuzuka and Banko Sawada. It also identifies Kohei Sugiyama's cinematography, Eiji Tsuburaya's camera assistance, Masao Uchida's lighting and set work by Kasaku Hayashi and Seyo Ozaki. The film's radical appearance was therefore produced by a collaboration among writers, performers and craftspeople rather than by a director applying a ready-made European style.",
      "BFI and Gerow describe rapid cutting, mobile framing, superimposition, distortion and non-linear construction, but the chapter refuses the shorthand 'Caligari in Japan.' International modernism mattered, yet the film emerged from Japanese literary, performance and exhibition networks and from Kinugasa's own production experiment. Its asylum setting also requires an ethical safeguard: subjective images and institutional confinement can be analyzed historically without turning mental illness into a horror mechanic or treating the film as a medical document. The Production Case evaluates visual and narrative reasoning, not the intensity of stigmatizing spectacle.",
      "Rediscovery is part of the film's modern identity. BFI notes that it was believed lost for decades before resurfacing in the 1970s, while Gerow's work distinguishes the surviving version from original release history. Restoration-era music, modern subtitles and contemporary runtimes consequently belong to later presentation states. The chapter uses the film as a model of three simultaneous histories: a 1926 independent production, a benshi-era exhibition event and a rediscovered archive object. Treating those layers separately gives the film more historical depth than calling it simply a timeless avant-garde masterpiece.",
    ],
    sourceIds: ["ch10_page_nfaj", "ch10_page_umich", "ch10_page_bfi_1926", "ch10_page_bfi_player", "ch10_nfaj_history"],
  },
];
