import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterTenMovementTwo: readonly FilmHistoryBookSection[] = [
  {
    id: "ch10_orochi_star_company_chanbara",
    title: "6. Orochi links independent star-company economics to chanbara choreography, social conflict, preservation and later benshi performance",
    paragraphs: [
      "Orochi belongs in the chapter because its production problem is neither generic samurai cinema nor generic action. NFAJ documents Tsumasaburo Bando's move into independent production in 1925, while Matsuda Film and Institut Lumière identify Bantsuma Production, director Buntaro Futagawa, screenwriter Rokuhei Susukita and additional craft credits. Bando was therefore not merely the face of a genre film: star labor, company formation and production autonomy intersected. A historical account must ask how a performer-producer could organize financing, personnel, identity and circulation around a screen persona without assuming that stardom eliminated collaboration.",
      "BFI places Orochi inside a transition toward action-oriented chanbara and emphasizes tracking shots, close-ups, rapid editing and a climactic choreography of bodies and blades. Those elements do not amount to a reusable 'samurai action' preset. The film's antiheroic social structure and critique of hierarchical injustice shape why the violence escalates, while camera position and cutting make space intelligible. Gameplay therefore evaluates coordination among performance, blocking, photography and editing. More sword strikes do not equal more historical accuracy, and feudal hierarchy is not rewarded as an aesthetic virtue.",
      "Preservation and presentation complete the system. BFI records that Bando preserved the negative; Lumière documents a modern 4K restoration under NFAJ supervision; Matsuda Film and BFI also connect Orochi to later benshi performance traditions. These facts occupy different dates and must remain separated. Negative survival is archival history, 4K work is restoration history and spoken commentary is exhibition history. None is synchronized 1925 production sound. Orochi thus demonstrates how a film can survive partly through star-producer agency while acquiring new performance and restoration layers long after its original production.",
    ],
    sourceIds: ["ch10_orochi_bfi_year", "ch10_orochi_bfi_1925", "ch10_orochi_nfaj_bantsuma", "ch10_orochi_matsuda", "ch10_orochi_lumiere"],
  },
  {
    id: "ch10_shanghai_mingxing_labor",
    title: "7. Laborer's Love makes early Shanghai studio formation, bilingual intertitles and handmade gag mechanics visible without turning survival into an origin myth",
    paragraphs: [
      "Laborer's Love survives from the formative years of Mingxing and therefore carries an evidentiary burden larger than its short running time. Hong Kong Film Archive credits Zhang Shichuan as director, Zheng Zhengqiu as screenwriter, Zhang Weitao as cinematographer and Mingxing as producer, while China Film Archive places the company in Shanghai's rapidly developing film culture. The film is often described as the earliest Chinese fiction film available to view today, but that phrase must remain a survival claim. It is not evidence that Chinese narrative cinema began with this one production or that the surviving short represents everything its contemporaries were making.",
      "Its comedy is also industrial evidence. Chinese Film Classics analyzes physical devices, staircase construction, visual puns and trick photography alongside international comic influences. These details make production labor tangible: carpentry, props, camera placement, timing and editing turn a fruit seller's tools and a doctor's staircase into mechanisms for cause-and-effect comedy. The bilingual Chinese and English intertitles documented by HKFA and scholarly sources add a circulation dimension. Translation was present in the film object itself, but language versions can carry different emphases, so bilinguality should not be reduced to a generic international-market badge.",
      "Modern restoration clarifies the archive boundary. China Film Archive records later digital and 4K work and contemporary live accompaniment. A modern restored runtime or score can make the film accessible while remaining distinct from synchronized 1922 sound. The chapter therefore uses Laborer's Love to show how an early company coordinated writing, photography, performance, practical construction, intertitles and exhibition while making the surviving print's exceptional status explicit. Preservation scarcity is a reason for precision, not permission to turn one surviving comedy into a total history of early Chinese cinema.",
    ],
    sourceIds: ["ch10_labor_hkfa", "ch10_labor_cfa", "ch10_labor_mingxing", "ch10_labor_cfc", "ch10_labor_cfc_module", "ch10_labor_restore"],
  },
  {
    id: "ch10_wuxia_serial_red_heroine",
    title: "8. Wuxia serial culture survives unevenly: The Red Heroine can be played only by keeping its missing twelve-part context visible",
    paragraphs: [
      "The Red Heroine is valuable because it opens a route into late-1920s Shanghai wuxia without pretending that the archive is complete. UCLA Film & Television Archive identifies the surviving film as the only extant section of a thirteen-part Red Knight-Errant serial produced by Youlian. China Film Archive and NFAJ credit Wen Yimin, cinematographer Yao Shiquan, performers including Fan Xuepeng and production-design work by Hu Xuguang. The playable object is therefore a surviving installment embedded in a much larger serial economy whose other parts cannot be reconstructed simply because a game would prefer a complete arc.",
      "The surviving section still provides rich production evidence. China Film Archive emphasizes stunt photography and stage mechanisms; NFAJ supplies format and craft data. Female martial agency, movement through designed space and trick effects can therefore be studied as material production choices. Yet the story's threats, abduction and gendered violence require an ethical limit: peril is historically present but cannot become an automatic score multiplier. Wuxia is treated as a genre system involving seriality, performance, effects, companies and audiences, not as a license to reward escalating spectacle without context.",
      "Version evidence is unusually instructive. UCLA, China Film Archive and NFAJ document modern presentations with substantially different runtimes, reflecting print condition, restoration and projection-speed decisions. The chapter therefore refuses one immutable runtime and identifies each cited version when temporal analysis matters. The lost Burning of the Red Lotus Temple broadens the serial context as a P2 comparison precisely because no complete film survives. Together the two titles teach a historiographic principle: lost popularity can be historically central, and surviving fragments can be playable only when the boundary between evidence and invention is enforced.",
    ],
    sourceIds: ["ch10_red_ucla", "ch10_red_cfa", "ch10_red_nfaj", "ch10_red_catalog", "ch10_labor_mingxing"],
  },
  {
    id: "ch10_phalke_survival_india",
    title: "9. Phalke matters to Indian film history, but a founder narrative cannot substitute for the scale, diversity and loss of silent production",
    paragraphs: [
      "Raja Harishchandra has enormous historical importance, yet the chapter avoids the trap of making one founder stand in for an entire national cinema. BFI notes that only about twelve known minutes survive, while Film Heritage Foundation describes catastrophic losses across Indian silent production. Dadasaheb Phalke's entrepreneurship, mythological subjects and technical improvisation are therefore part of an industrial history whose surviving evidence is radically incomplete. A P2 classification protects that distinction: the book can teach production significance without fabricating a complete playable feature from fragments.",
      "Kaliya Mardan broadens the picture because Phalke's work developed through recurring mythological production, performance and effects rather than one origin event. At the same time, the chapter keeps colonial distribution, regional industries and other producers in view. 'First' language is used carefully because premiere claims, surviving fragments and later canonization answer different questions. The point is not to demote Phalke but to prevent the success of an origin story from erasing the many films and companies for which prints no longer survive.",
      "Nitrate loss makes this more than a theoretical concern. Film Heritage Foundation documents both the instability of nitrate stock and the very small number of complete Indian silent films that remain. Preservation policy consequently shapes the canon a century later. A historical game cannot solve that gap by generating missing footage or by giving a surviving film representative weight it did not historically possess. The correct response is to record absence, use documentary and production records where appropriate, and reserve full Production Cases for works whose surviving evidence can sustain the required craft and version claims.",
    ],
    sourceIds: ["ch10_raja_bfi", "ch10_india_nitrate_fhf", "ch10_throw_silentfest"],
  },
  {
    id: "ch10_rai_osten_transnational",
    title: "10. The Rai–Osten trilogy shows transnational Indian production as a network of producer-star agency, German craft collaboration, location work and international circulation",
    paragraphs: [
      "The Light of Asia, Shiraz and A Throw of Dice form a particularly useful counterexample to national-purity histories. BFI describes Himansu Rai and Franz Osten's silent collaborations as films shot on location in India, while filmportal.de records A Throw of Dice through a production network involving Himansu Rai Film, UFA and British Instructional Films. Rai was not merely an actor inside a German-controlled project: he functioned as producer-star and organizer, while German direction and technical labor, Indian cast and locations, and British participation intersected. 'Indian', 'German' and 'British' therefore describe real institutional relations without any one label exhausting the production.",
      "A Throw of Dice becomes the playable anchor because its production records identify cinematographer Emil Schünemann, designer Promode Nath, multiple companies and Indian locations. Shiraz and The Light of Asia remain P2 comparisons that reveal continuity across the collaboration. BFI's Shiraz material makes lavish location and costume production visible, while the trilogy context demonstrates how international circulation could be built into a film's conception. The chapter therefore asks who financed, organized, performed, photographed and distributed rather than assigning ownership automatically from director nationality.",
      "Modern music makes version discipline essential. BFI explicitly distinguishes contemporary commissioned scores for the restored silent films from the 1920s production. Nitin Sawhney's score for A Throw of Dice or Anoushka Shankar's work for Shiraz can be historically significant acts of modern presentation without becoming evidence of synchronized original sound. The same logic applies across the chapter: restoration can create a new exhibition event while leaving production chronology intact. Transnational production and transhistorical presentation are both complex, but they are not the same complexity and should not be collapsed into one metadata field.",
    ],
    sourceIds: ["ch10_throw_bfi", "ch10_throw_filmportal", "ch10_throw_bfi_trilogy", "ch10_throw_silentfest", "ch10_shiraz_bfi"],
  },
];
