import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterEightMovementThree: readonly FilmHistoryBookSection[] = [
  {
    id: "ch8_dulac_coquille_authorship",
    title: "11. La Coquille et le clergyman makes authorship conflict part of Surrealist film history",
    paragraphs: [
      "La Coquille et le clergyman is crucial because it prevents Surrealist cinema from being narrated as a clean succession of universally agreed masterpieces. La Cinémathèque credits Germaine Dulac as director and producer, Antonin Artaud as screenwriter, Studio-Films as production and distribution company and Paul Parguel and Paul Guichard in photography. The same institutional record documents the hostile controversy around the film's public presentation and the accusation that Dulac had distorted Artaud's text. That conflict belongs to production history: a screenplay does not automatically determine the finished film, and disagreement between writer and director can become part of how authorship is remembered.",
      "Dulac's own theoretical trajectory makes the disagreement more than a personality clash. Cinémathèque scholarship describes her cinema as increasingly oriented toward rhythm, visual sensation and interior states; its retrospective materials situate La Coquille among experiments in blur, superimposition, acceleration and abstraction. Reading the film only as a failed transcription of Artaud therefore reproduces one participant's authority and erases Dulac's established method. At the same time, calling it simply 'Dulac's Surrealist film' can erase the screenplay and the historical dispute. The chapter keeps both claims visible and asks students to distinguish contribution, control of production, reception and later canonization.",
      "This is also why the film remains P2 rather than becoming a second Dulac Production Case. The Smiling Madame Beudet already gives the player a distinct Dulac system of subjective montage, gendered social space and adaptation, while Un Chien Andalou supplies a dedicated Surrealist collaboration case. La Coquille is more valuable here as an authorship and historiography problem: it shows how labels such as 'first Surrealist film' can become weapons in later canon formation, especially when the labor of a woman director is contested by male avant-garde networks. The educational task is to reconstruct evidence, not to settle a century of debate with a badge.",
    ],
    sourceIds: ["ch8_coquille_cinematheque", "ch8_dulac_classic_modern", "ch8_dulac_sensations", "ch8_dulac_retrospective"],
  },
  {
    id: "ch8_surrealism_chien",
    title: "12. Un Chien Andalou organizes Surrealist discontinuity through collaboration, constraints and ethical limits",
    paragraphs: [
      "Un Chien Andalou is the chapter's clearest Production Case for Surrealist association because the institutional record makes its collaborative structure visible. La Cinémathèque credits Luis Buñuel as director, producer and editor, Buñuel and Salvador Dalí as screenwriters, Pierre Braunberger as executive producer, Albert Duverger as cinematographer, Pierre Schildknecht as designer and Studio-Films as production company and original distributor. MoMA places the film inside the Buñuel-Dalí partnership and the broader Surrealist context. The result is not a license to throw unrelated images together: a short still has to specify actions, performers, locations, props, transitions and safe methods before discontinuity can be constructed in the edit.",
      "BFI identifies montage, dissolves, superimpositions, slow motion, discontinuous editing and parodic intertitles among the film's formal resources. Those techniques make dream-like association operational because each transition is concrete even when causal explanation is rejected. A dissolve must connect two photographed states, a superimposition requires layers, a temporal intertitle establishes a relation that the following images may undermine, and abrupt cuts gain force from precise pictorial contrast. The Production Case therefore teaches Surrealism as disciplined rejection of conventional rational links, not as an RNG mode that excuses weak planning. Irrationality on screen can be highly organized behind the camera.",
      "The film's notorious imagery also requires an ethical boundary stronger than aesthetic admiration. Historical discussion may analyze the eye-cutting image, dead-animal material and sexual threat, but gameplay never asks a player to injure a person or animal, reproduce coercion or score shock value. Safe props, compositing, implication and critical analysis substitute for dangerous reenactment. This safeguard is part of film history rather than an external warning label: avant-garde provocation was produced under particular social and material conditions, and a contemporary educational simulator should distinguish studying a historical image from operationalizing its harm as a creative objective.",
    ],
    sourceIds: ["ch8_chien_cinematheque", "ch8_dali_moma", "ch8_bunuel_moma", "ch8_bfi_french_avant", "ch8_field_moma"],
  },
  {
    id: "ch8_independent_kirsanoff_epstein",
    title: "13. Independent production reveals how urban texture and material atmosphere could carry subjectivity without studio spectacle",
    paragraphs: [
      "Dimitri Kirsanoff's Ménilmontant offers a smaller-scale counterweight to Gance and L'Herbier. La Cinémathèque credits Kirsanoff as director, screenwriter, producer, cinematographer and editor, with Paris locations integral to a social melodrama built around two sisters. Its archival account emphasizes the alternation of rapid, jagged montage and ellipsis, the absence of conventional intertitle dependence and the way the Ménilmontant district becomes both refuge and trap. This compact production demonstrates that subjective rhythm did not require enormous studio infrastructure; a filmmaker could organize location texture, performance and editing with a much smaller apparatus while still participating in the experimental field.",
      "The film's restoration history also shows how independence complicates survival. Cinémathèque documents preservation from an original distribution copy and later work using a BFI nitrate print, a duplicate element from its own collections and an additional fragment. What appears today as one coherent canonical short is therefore the product of archival comparison and reconstruction. That does not diminish the film's authorship; it clarifies the material path by which the authorship remains visible. The chapter treats restored completeness as an evidentiary achievement rather than a transparent window onto an untouched 1920s object.",
      "Epstein's The Fall of the House of Usher extends the same lesson in another direction. Cinémathèque records Epstein's independent company, Georges Lucas's photography, Pierre Kéfer's design and a production that used slow motion, superimposition, mobile camera and atmospheric sets to transform Poe. Its restoration corpus documents both the original production and later reconstruction. The film stays P2 because Cœur fidèle already owns the core Epstein perception problem in gameplay, but Usher deepens the book's account of how independent finance, borrowed resources, material atmosphere and optical technique could support a feature whose formal ambition exceeded the security of its production base.",
    ],
    sourceIds: ["ch8_menilmontant_cinematheque", "ch8_menilmontant_restoration", "ch8_usher_cinematheque", "ch8_usher_restoration", "ch8_france1920_corpus"],
  },
  {
    id: "ch8_institutions_patronage_censorship",
    title: "14. Cine-clubs, specialist venues, patrons and censorship made alternative cinema an institutional system",
    paragraphs: [
      "Avant-garde circulation depended on institutions as much as on techniques. Delluc's criticism helped create a vocabulary and public for a first avant-garde; Dulac participated in cine-club organization; Entr'acte belonged to a ballet program; Studio des Ursulines and Studio 28 became important specialist venues; artist networks linked painters, poets, composers and filmmakers. MoMA's account of 1920s Paris stresses that the interaction among film and other visual arts benefited from a cultural field not wholly controlled by either commerce or the state. Alternative exhibition therefore meant building audiences, programs and reputations through smaller institutions, not merely rejecting mainstream theatres in principle.",
      "Alternative financing could also change what kinds of risk a production could take. L'Inhumaine credits Marie-Laure de Noailles as producer, while Un Chien Andalou emerged from small-scale family financing and L'Âge d'Or from patron-supported Surrealist production. These arrangements could protect experiments from normal studio expectations but also concentrate dependence on a few individuals and social networks. The chapter treats patronage as an economic model with freedoms and vulnerabilities, not as magical independence from money. A production still has a budget, labor obligations, rights questions and a route to an audience even when its capital comes from private wealth rather than a vertically integrated company.",
      "Provocation also met legal, political and social limits. Surrealist screenings generated scandal, La Coquille's premiere became an authorship battle and L'Âge d'Or became bound to censorship history as its sound-era provocation circulated. The game does not reward scandal for its own sake. Instead, the chapter asks what institution bears the consequences when a work challenges religious, sexual, political or bourgeois norms: producer, venue, patron, distributor, performer or censor. This keeps controversy inside production analysis while avoiding a romantic story in which repression automatically proves artistic value or in which harmful representation becomes a shortcut to historical importance.",
    ],
    sourceIds: ["ch8_delluc_cinematheque", "ch8_dulac_moma", "ch8_field_moma", "ch8_inhumaine_cinematheque", "ch8_chien_cinematheque", "ch8_coquille_cinematheque"],
  },
  {
    id: "ch8_versions_transition_afterlife",
    title: "15. Restoration and the sound threshold turn the avant-garde canon into a history of changing film objects",
    paragraphs: [
      "Chapter 8 ends with a methodological problem shared by nearly every anchor film: the object seen today is often not identical to one fixed premiere print. La Roue exists through several historical assemblies and a major reconstruction; Napoléon has Opéra, Apollo, export, sound-reedit and modern Grande Version histories; Entr'acte changed when Clair removed material in 1967 and later restorers reinstated first-version elements; Ménilmontant combines surviving nitrate and duplicate sources; The Passion of Joan of Arc survived loss and rediscovery. Modern duration, tinting, music and digital repair are therefore evidence about preservation and presentation, not neutral metadata that can be projected backward onto original production.",
      "The same discipline matters at the border of sound. Un Chien Andalou belongs to a silent-era production environment even when later presentations attach recorded music; Entr'acte's relation to Satie's accompaniment is an exhibition-performance problem rather than synchronized location recording; L'Âge d'Or in 1930 points forward to the different industrial and aesthetic questions that Chapter 11 will own. The arrival of recorded sound did not instantly erase silent craft, nor does a restored soundtrack prove that a 1920s camera crew recorded synchronized dialogue. Keeping layers separate lets the book connect periods without allowing later technology to rewrite earlier production facts.",
      "The completed Atlas matrix follows the same principle of disciplined selectivity. Six films are now playable Chapter 8 anchors because each contributes a distinct production problem: Cœur fidèle for perception-led rhythm, Napoléon for epic apparatus and Polyvision, Un Chien Andalou for Surrealist discontinuity, The Smiling Madame Beudet for gendered subjectivity, Entr'acte for event cinema and The Passion of Joan of Arc as a radical French-production boundary anchor. Nine further films remain P2 comparisons, and ten institutions or concepts remain historical objects rather than fake scenarios. Completion therefore means enough playable difference to support the chapter's argument, not converting every canonical title or theoretical concept into a game level.",
    ],
    sourceIds: ["ch8_roue_launch", "ch8_napoleon_comet", "ch8_napoleon_grande_version", "ch8_entracte_fondation", "ch8_menilmontant_restoration", "ch8_passion_bfi_catholic", "ch8_bfi_french_avant"],
  },
];
