import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterSixMovementOne: readonly FilmHistoryBookSection[] = [
  {
    id: "ch6_system_not_inventor",
    title: "1. Classical Hollywood was a production system, not a single invention",
    paragraphs: [
      "Classical continuity is easiest to misunderstand when it is reduced to a list of editing rules or credited to one heroic inventor. By the later 1910s, American feature production was stabilizing a much wider system: scripts organized causes and goals, sets and locations were planned for legible movement, performers were blocked so looks and gestures could be matched, camera positions protected screen direction, and editors assembled material whose spatial relations had already been anticipated during production. The point was not that every film looked identical. It was that a growing labor system made certain forms of clarity repeatable across directors, genres and companies while leaving room for differentiation inside the norm.",
      "The distinction matters historically because many devices associated with continuity predate the mature Hollywood studio system. Analytical cutting, eyeline relations, matched action, parallel editing and closer framings emerged unevenly across companies and countries before 1914. Chapter 3 therefore treats Griffith-era narrative construction through The Lonely Villa rather than making Chapter 6 repeat an origin story. What changes after 1914 is the density of coordination: central producers, scenario departments, specialized crews, larger feature schedules, distribution commitments and standardized technical expectations increasingly turn continuity from an occasional solution into a dependable production practice.",
      "The classical system should also be understood as an industrial compromise rather than a law of cinema. It privileged causal protagonists, readable space and temporal orientation because those choices supported long features made by divided labor for national distribution. Other cinemas in the same decade pursued montage, expressionist design, mobile-camera subjectivity and avant-garde discontinuity; those alternatives receive their own chapters precisely because Hollywood's solution was powerful without being inevitable. Calling it a system therefore names a historical configuration of labor, style, technology and commerce—not a universal grammar discovered once and for all in Los Angeles."
    ],
    sourceIds: ["ch6_classical_columbia", "ch6_classical_routledge", "ch6_moma_ince"],
  },
  {
    id: "ch6_cluster_division_labor",
    title: "2. Hollywood concentration turned geography into an industrial resource",
    paragraphs: [
      "The migration of production toward Southern California did more than provide sun and varied locations. Concentration created a labor market in which carpenters, electricians, laboratories, costume suppliers, camera specialists, stunt performers, animal handlers, property houses and experienced crews could move among productions. A company did not need to own every skill or material internally to benefit from the cluster. The result was a production ecology: large firms could maintain permanent departments while independents and specialized suppliers sold services into the same regional network. Hollywood became powerful partly because repeated production made expertise, equipment and infrastructure easier to assemble on schedule.",
      "Thomas Ince's career is especially useful here because his importance lies less in a mythology of individual directing than in production organization. MoMA notes that by 1913 he had largely shifted from full-time directing toward producing and that methods associated with his companies became foundations for the studio system. This managerial turn helps explain why the mature feature was increasingly planned through written continuity, budgets, schedules, units and supervisory roles. Creative decisions remained contested, but they were made inside organizations capable of coordinating several departments and sometimes several pictures at once rather than around an isolated camera crew improvising from scene to scene.",
      "Concentration also produced inequalities of access. Contract labor, capital, distribution relationships and ownership of facilities gave established companies advantages that could not be reduced to aesthetic talent. At the same time, independent stars and producers could exploit the same regional suppliers while resisting full corporate integration, as Chaplin and Keaton later demonstrate. The chapter therefore treats Hollywood as a cluster with multiple organizational forms, not as a monolithic studio that suddenly appeared fully formed. What consolidated was an ecosystem whose scale made standardization, specialization and rapid recombination of labor economically valuable."
    ],
    sourceIds: ["ch6_moma_ince", "ch6_classical_columbia", "ch6_hollywood_vault"],
  },
  {
    id: "ch6_continuity_workflow",
    title: "3. Continuity began before the cut",
    paragraphs: [
      "A match cut cannot repair production coverage that never established who is looking where, which door a character used or how an action changes the dramatic situation. Classical continuity therefore begins upstream of editing. Scenario construction defines goals and causal beats; staging places performers and objects in comprehensible relations; camera planning decides when to preserve or change screen direction; art direction and costume help separate people and spaces; and slating, script supervision and editorial records make repetitions comparable. The editor receives fragments, but their compatibility depends on a chain of earlier choices. Treating continuity as an editor's trick hides the organizational achievement that made feature-scale clarity reproducible.",
      "This is also why the system could absorb stylistic variation. The Cheat can use deep shadow, selective illumination and unusually charged compositions while still remaining dramatically legible because entrances, looks, gestures and spatial relationships are organized around narrative information. The Crowd can move from a monumental city exterior into a vast office and then into intimate domestic pressure without abandoning causal orientation. The General can stage long physical gags in depth and preserve machinery as real space. Continuity does not require invisible style; it requires that expressive choices remain coordinated with the viewer's ability to track action, knowledge and consequence.",
      "Once production is understood this way, the familiar search for a single inventor becomes historically unhelpful. Individual filmmakers contributed important solutions, but an industrial norm requires repetition across many workers and many films. The standardized practice described by film historians emerged through training, imitation, trade circulation, equipment conventions and managerial pressure as much as through celebrated directors. Chapter 6 therefore asks a production question whenever a formal term appears: who had to know this relation in advance, what information had to travel between departments, and how did the company make the result dependable enough to release features week after week?"
    ],
    sourceIds: ["ch6_classical_routledge", "ch6_classical_columbia", "ch6_afi_cheat"],
  },
  {
    id: "ch6_paramount_scale_distribution",
    title: "4. Famous Players-Lasky and Paramount linked production to national distribution",
    paragraphs: [
      "A feature does not become an industrial system merely because it is expensive to photograph. It becomes one when production decisions are tied to a repeatable route to screens. Famous Players, Lasky and Paramount are central to this chapter because their consolidation joined stars, feature production, publicity and national distribution on a scale that changed what a producer could plan for. The Cheat belongs to the earlier Lasky-Paramount relationship; It belongs to the later Paramount Famous Lasky organization. Read together, the films show that house style and star vehicles were not separate from distribution. A recognizable performer, marketable story premise and coordinated release campaign could be budgeted as parts of the same product strategy.",
      "Block booking later became one of the practices through which powerful distributors sold groups of films to exhibitors. The 1932 federal appellate record concerning Paramount Famous-Lasky is later than most films in this chapter, so it must not be projected backward as if every 1915 contract already had the same form. It is valuable instead as retrospective evidence that a company combining production and interstate distribution developed package-selling practices whose effects on exhibitor choice became a regulatory issue. Likewise, the later Paramount antitrust litigation documents runs, clearances and block booking at a mature stage; Chapter 6 uses those records to explain the logic and consequences of integration while keeping chronology explicit.",
      "National distribution changed style indirectly because it rewarded predictable delivery, recognizable genres and publicity that could travel. It also changed bargaining power. An independent theater depended on access to films audiences wanted, while a distributor with a large annual program could negotiate across a slate rather than title by title. The resulting system never eliminated uncertainty—hits still surprised companies and expensive films still failed—but it made production planning inseparable from release architecture. Hollywood's classical period therefore has to be studied through contracts, circulation and exhibition geography as well as through shots and cuts."
    ],
    sourceIds: ["ch6_afi_cheat", "ch6_afi_it", "ch6_famous_lasky_blockbooking", "ch6_paramount_antitrust_1946"],
  },
  {
    id: "ch6_cheat_style_representation",
    title: "5. The Cheat: company style, star construction and the ethics of what style serves",
    paragraphs: [
      "The Cheat is an effective Chapter 6 anchor because its visual distinction does not sit outside industrial production. AFI identifies the Jesse L. Lasky Feature Play Company, Paramount distribution, Cecil B. DeMille, writers Hector Turnbull and Jeanie Macpherson, cinematographer Alvin Wyckoff and art director Wilfred Buckland. Film Foundation and MoMA accounts emphasize the film's low-key illumination, silhouettes, elaborate interiors and Sessue Hayakawa's restrained performance. The lesson is therefore not that classical Hollywood suppressed style. A company could pursue a recognizable visual treatment when lighting, design, performance and framing were coordinated with a melodramatic structure that remained readable to a broad audience.",
      "But craft analysis becomes distorted if it treats the film's racial politics as neutral decoration. The scenario turns Hayakawa's character into a sexual-threat figure, and institutional histories explicitly note the racist construction around the role. The 1918 reissue altered the character's name and national identity, evidence that representation and market management were historically entangled rather than separable layers. Chapter 6 therefore studies how lighting, interiors, performance restraint and publicity helped create Hayakawa's screen power while refusing to convert racialized coercion into a production objective for the player. Style answers to a narrative and a market; ethical analysis asks what that narrative makes visible, desirable or threatening.",
      "Version history adds a second safeguard. AFI documents the later reissue and a much later Robert Israel score on restored material; the Film Foundation describes reconstruction work from surviving elements. Those layers cannot be silently folded into an imaginary pristine 1915 master. The Production Case preserves the difference between original production, reissue modification and restoration, while the book uses the same distinction to show that studio-era films are material objects with distribution histories. Classical legibility may make a film easy to follow, but historical legibility requires us to know which version, which credit and which representational decision we are actually discussing."
    ],
    sourceIds: ["ch6_afi_cheat", "ch6_ucla_cheat", "ch6_filmfoundation_cheat", "ch6_moma_cheat", "ch6_loc_registry_descriptions"],
  },
];
