import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterFiveMovementTwo: readonly FilmHistoryBookSection[] = [
  {
    id: "ch5_afgrunden_performance",
    title: "Afgrunden: performance becomes an export strategy",
    paragraphs: [
      "Afgrunden demonstrates how a comparatively small production could become internationally significant by concentrating resources on performance. Det Danske Filminstitut identifies Urban Gad as director and screenwriter, Alfred Lind as cinematographer, Kosmorama as the producing company and Asta Nielsen as the central performer. BFI's production history describes an eight-day shoot using a deserted jail yard, Copenhagen streets and Frederiksberg Gardens. Those conditions matter because the film's distinction did not depend on vast construction. Production value was concentrated in bodies, locations, staging and a dramatic structure that made Nielsen's changes of posture, gaze and movement legible to the camera.",
      "The famous rope dance with Poul Reumert is often remembered for erotic provocation, but as production history it is also an exercise in controlled screen attention. The action must remain physically readable while revealing Magda's changing relationship to Rudolf and to the circus environment. A performance-centred camera can preserve the tension between attraction and coercion without fragmenting the body into explanatory inserts. Nielsen's achievement should not be converted into an invention myth about naturalistic acting; stage and screen performers were already experimenting with degrees of gesture. What Afgrunden documents is the commercial power of a particularly concentrated, psychologically legible screen presence at a moment when films and stars travelled rapidly.",
      "The international consequence was larger than one Danish success. Nielsen and Gad soon worked in Germany, and Nielsen's image became marketable across national boundaries. This mobility makes Afgrunden an ideal bridge between craft and industry. Acting style, framing and publicity are not separate topics: they cooperate to manufacture an identity distributors can sell. The Atlas case therefore asks how a producer with limited time and money creates a feature whose most valuable asset is a performer. The book uses that case to explain why a small production centre could matter internationally when it developed stars and genres that foreign markets recognized as distinctive.",
    ],
    sourceIds: ["ch5_dfi_afgrunden", "ch5_bfi_asta", "ch5_stumfilm_afgrunden", "ch5_dfi_history_1910_1919"],
  },
  {
    id: "ch5_danish_long_form",
    title: "Danish long films, imitation and export competition",
    paragraphs: [
      "Danish cinema's prewar strength was not reducible to Asta Nielsen. Around 1910 several companies were testing longer dramatic formats, and the white-slave cycle shows how quickly a successful subject could trigger competitive imitation. Stumfilm.dk distinguishes Fotorama's three-reel Den hvide Slavehandel from Nordisk Film's later production with the same title and describes the Nordisk version as a close imitation that became a major export success. The episode is valuable because it makes copying, speed and distribution visible. A company could respond to a rival not only through artistic differentiation but by mobilizing a stronger network around a familiar sensational premise.",
      "The films also show why genre history must be read critically. White-slave narratives sold themselves through moral warning and contemporary social anxiety while simultaneously exploiting images of confinement, sexual threat, pursuit and rescue. Modern historians should neither accept their claims to social realism at face value nor dismiss their popularity as irrelevant sensationalism. Production, publicity and reception worked together: the same story could be promoted as topical warning, suspense attraction and evidence of a company's capacity to sustain three reels. This mixture of reform language and spectacle later finds an American comparison in Traffic in Souls.",
      "Nordisk's turn toward longer dramas from 1911 indicates a wider industrial bet on exportable feature form. The key lesson is not that Denmark alone invented the feature, since multi-reel experiments and long attractions existed elsewhere. It is that a small-language market could build an internationally oriented production strategy by standardizing longer dramas, recognizable performers and saleable genres. Chapter 5 keeps The White Slave Trade as P2 because its strongest function is comparative: it explains competitive imitation and long-form risk, while Afgrunden and Atlantis provide cleaner, distinct playable problems of star-centred performance and export-scale versioned production.",
    ],
    sourceIds: ["ch5_stumfilm_white_slave", "ch5_stumfilm_white_slave_theme", "ch5_stumfilm_silent_art", "ch5_dfi_history_1910_1920"],
  },
  {
    id: "ch5_atlantis_export_feature",
    title: "Atlantis: a feature designed for the world market",
    paragraphs: [
      "Atlantis pushes the Danish export strategy to a different scale. Det Danske Filminstitut identifies August Blom's 1913 film as a Nordisk production adapted from Gerhart Hauptmann, photographed by Louis Larsen and Johan Ankerstjerne, and made at 2,280 metres on 35 mm. DFI's historical account presents it as Nordisk's largest and most ambitious production of the period. The production challenge is therefore organizational: a long literary melodrama, transatlantic travel, a major shipwreck sequence and an international cast of situations had to remain coherent across a work far larger than a routine short subject.",
      "Its two documented endings make the film especially important for an international history. The unhappy ending produced for the Russian market demonstrates that export could alter the work at the level of photographed narrative outcome. Versioning was not merely a translated title card pasted onto a stable master. It could require planned alternatives, separate assembly and reliable records so a distributor received the intended ending. The Production Case models that problem without inventing undocumented shot ownership for the two cinematographers or speculative effects techniques for the wreck. What is known and what is inferred remain separate.",
      "Atlantis also warns against equating expenditure with success. DFI's account describes the project as artistically and commercially problematic despite its ambition. That tension belongs in a production textbook because internationalization increased both opportunity and exposure. Larger films required more capital, more coordination and stronger distribution assumptions; if those assumptions failed, scale amplified risk. The case therefore complements Cabiria rather than duplicating it. Cabiria teaches integrated spectacle and mobile spatial design within the Italian epic; Atlantis teaches how literary prestige, disaster logistics, dual-camera credit and market-specific narrative versioning operate inside a Scandinavian export company.",
    ],
    sourceIds: ["ch5_dfi_atlantis", "ch5_dfi_history_1910_1920", "ch5_stumfilm_atlantis", "ch5_ucpress_transformation"],
  },
  {
    id: "ch5_fantomas_cycle",
    title: "Fantômas: recurring identity inside company production",
    paragraphs: [
      "Fantômas turns international company scale into a genre problem. Gaumont and French archival records identify Louis Feuillade's 1913 work as part of a five-film cycle adapted from the popular novels by Pierre Souvestre and Marcel Allain, with René Navarre returning as the elusive criminal and recurring figures such as Juve and Fandor organizing pursuit. The production advantage of recurrence is memory: the audience can recognize a name, silhouette, disguise pattern or relationship before a new plot fully explains it. That accumulated familiarity reduces exposition while creating a reason to return for another film.",
      "Recurring identity also creates continuity risks. Fantômas is valuable because disguise makes recognition unstable by design. Costume, performance, staging and editing must reveal enough for suspense while preserving the criminal's capacity to evade capture. The production team therefore manages two audiences at once: characters who may be deceived and spectators who may know more, less or differently depending on which film in the cycle they have seen. This is more specific than simply calling the work a serial. The craft problem is the repeatable manufacture of recognition and uncertainty across releases produced by an established company.",
      "Archival runtime differences reinforce that caution. Gaumont and La Cinémathèque française catalogue restored programmes of different total duration, while BnF records individual entries within the cycle. Chapter 5 refuses to turn those modern presentations into a single original runtime. Instead, the film becomes evidence for the international circulation of a recurring popular property whose production identity survived different copies and later reconstructions. The historical claim is deliberately bounded: Feuillade did not single-handedly invent serial storytelling, but Gaumont's infrastructure allowed a sustained crime universe to become a scalable, exportable product before the First World War.",
    ],
    sourceIds: ["ch5_gaumont_fantomas", "ch5_cinematheque_fantomas", "ch5_bnf_juve", "ch5_bnf_mort"],
  },
  {
    id: "ch5_queen_elizabeth_prestige",
    title: "Queen Elizabeth: prestige crosses the Atlantic",
    paragraphs: [
      "Queen Elizabeth demonstrates a different international pathway: a French prestige production could acquire additional industrial meaning through the overseas value of Sarah Bernhardt's name. Fondation Jérôme Seydoux-Pathé, BFI, MoMA and NYPL records connect the 1912 film to Le Film d'Art, Émile Moreau's play, Bernhardt and Paul Poiret's costume contribution. The production strategy was legibility through prestige. Historical subject, theatrical celebrity, elaborate dress and multi-reel scale signalled that projected film could be sold as an event worthy of sustained attention rather than as a disposable programme item.",
      "Adolph Zukor's acquisition of United States rights is important, but it must not be allowed to rewrite authorship. The film remained a French production; American rights and presentation were distribution and business interventions. That distinction is central to Chapter 5 because transnational history often collapses the country where a work was made into the country where it became commercially influential. The Atlas case makes the separation playable: production decisions build Bernhardt's prestige vehicle, while rights strategy determines how that completed work can be exploited in another market.",
      "Queen Elizabeth also exposes the difficulty of using surviving copies as transparent historical facts. Institutional records provide differing running times and director attributions, reflecting cataloguing and version histories. Rather than choosing one modern number and declaring it universal, the chapter treats the variance as evidence. Prestige circulation depended on prints, territories and later preservation just as popular genre did. The film's significance lies not in being the single origin of feature cinema or the studio system, but in showing how celebrity, cultural status and transatlantic rights could reinforce one another while longer films were becoming commercially normalizable.",
    ],
    sourceIds: ["ch5_fondation_queen", "ch5_bfi_queen", "ch5_moma_queen", "ch5_nypl_queen", "ch5_ucpress_transformation"],
  },
];
