import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterTenMovementThree: readonly FilmHistoryBookSection[] = [
  {
    id: "ch10_haxan_evidence_spectacle",
    title: "11. Häxan makes research, lecture, reenactment, horror spectacle and censorship inseparable as production problems but unequal as evidence",
    paragraphs: [
      "Häxan is trans-Scandinavian before it is a genre label. DFI credits the Danish filmmaker Benjamin Christensen as writer-director, Johan Ankerstjerne as cinematographer, Richard Louw as production designer and Emil Reesen as composer, while Swedish Film Institute material describes Swedish financing and Danish studio production over a long and expensive process. That infrastructure matters because the film's extraordinary imagery required research, design, makeup, performance, photography and trick work. Calling it simply an auteur horror film hides the industrial coordination that made its hybrid form possible.",
      "The hybrid form also creates an evidence problem. DFI describes documentary-like exposition alongside dramatized sequences, historical images and supernatural fantasy. The chapter therefore marks every shift in evidentiary status: a reproduced woodcut can be historical evidence about representation; an intertitle can make Christensen's claim; a staged torture scene can illustrate an argument; a demon produced through performance and trick photography is an invention. The lecture voice does not make reenactment true. Christensen's final comparison between witch persecution and modern psychiatric diagnosis is taught as a 1922 intellectual argument, not as contemporary medical consensus.",
      "Reception and restoration add further layers. Swedish Film Institute documents censorship and a 2016 restoration that reconstructed tinting and toning using surviving materials and period color instructions. The restored colors are historically reasoned archive work, not proof that every surviving 1922 print looked identical. Likewise, Reesen's music credit belongs to silent-era musical presentation without implying synchronized dialogue or effects. Häxan therefore closes a loop running throughout the chapter: historical method becomes stronger when production, representation, exhibition, censorship and restoration are all named rather than collapsed into one supposedly original text.",
    ],
    sourceIds: ["ch10_haxan_dfi", "ch10_haxan_sfi_restore", "ch10_haxan_sfi_century", "ch10_danish_history_dfi"],
  },
  {
    id: "ch10_sweden_comparative_field",
    title: "12. The Swedish golden age remains a comparative field of social realism, landscape, literary adaptation, comedy, stars and archive reconstruction",
    paragraphs: [
      "The Swedish silent canon becomes misleading if Körkarlen alone is allowed to represent it. Swedish Film Institute material places Victor Sjöström and Mauritz Stiller alongside cinematographers Julius and Henrik Jaenzon in a period of international prestige, yet the films vary sharply in production problem. Ingeborg Holm turns welfare institutions and social melodrama into controlled performance; The Outlaw and His Wife and Sir Arne's Treasure coordinate harsh landscapes with literary adaptation; Erotikon develops urban comedy; Gösta Berling's Saga scales Selma Lagerlöf adaptation and star formation. A shared institutional period is not a single visual template.",
      "This comparative field also reveals why Atlas should remain selective. The Phantom Carriage already provides a playable Swedish case for adaptation, layered photography and supernatural representation, while Häxan supplies a different Scandinavian research-and-effects problem. Adding every Stiller or Sjöström film would increase title count without necessarily increasing gameplay distinction. The chapter instead uses film references to compare production choices and preserve names, institutions and genres that would disappear if the narrative were built only from playable cases.",
      "Archive history reinforces the plural approach. Swedish Film Institute records restoration and repatriation work across multiple silent titles, showing that the modern canon is partly a history of what materials could be recovered and reconstructed. When restored boxes or retrospectives place films together, they create valuable new viewing contexts but do not prove that contemporaries understood all the works as one coherent school. The book therefore uses 'golden age' as a historiographic category to examine, not as a preset that automatically assigns landscape, literary prestige or photographic solemnity to every Swedish silent production.",
    ],
    sourceIds: ["ch10_sweden_golden_sfi", "ch10_sweden_archive_sfi", "ch10_haxan_sfi_century"],
  },
  {
    id: "ch10_australia_mexico_comparisons",
    title: "13. Australia and Mexico show why global silent history needs vernacular production, serial form, location evidence and restoration outside the usual national centers",
    paragraphs: [
      "The Sentimental Bloke provides an Australian comparison grounded in production and survival rather than token geography. NFSA credits Raymond Longford and Lottie Lyell's adaptation of C.J. Dennis, records Sydney locations including Woolloomooloo and Manly, and describes the film as one of relatively few Australian silent features to survive complete. Its vernacular intertitles, location photography and performance connect national popular culture to a local production industry. The film remains P2 because Chapter 10 already has enough playable cases, but its presence prevents the chapter's 'global' claim from stopping at Asia and northern Europe.",
      "NFSA's restoration history is just as instructive as the original production. Materials survived in different generations and territories, including an American version with altered titles and censorship. Later restorers combined sources and reconstructed tinting, while new musical scores created modern exhibition events. The resulting film is not a fraud; it is an archive reconstruction whose decisions can be documented. This makes The Sentimental Bloke a particularly clear demonstration that national film heritage can depend on prints that crossed borders and returned decades later in materially transformed form.",
      "El automóvil gris offers a Mexican counterpart through a different form. Cineteca Nacional and UNAM document Enrique Rosas's 1919 crime serial, location work around Mexico City and a mixture of staged fiction with material tied to real events. The restored version reintegrates material from an originally episodic work and uses newly composed live music because the original music has not survived. The chapter therefore refuses to call its actuality elements neutral proof or its restored feature-length assembly the only authentic version. Mexico and Australia enter the narrative through production systems and archive problems, not as decorative evidence that the book has visited enough countries.",
    ],
    sourceIds: ["ch10_bloke_nfsa", "ch10_bloke_restore_nfsa", "ch10_bloke_reconstruction_nfsa", "ch10_auto_cineteca", "ch10_auto_unam", "ch10_auto_cinematheque"],
  },
  {
    id: "ch10_restoration_sound_color_versions",
    title: "14. Restoration changes what modern audiences can see and hear, so tints, scores, projection speeds, fragments and recuts require version criticism",
    paragraphs: [
      "Nearly every major case in this chapter reaches modern viewers through some form of archival mediation. A Page of Madness resurfaced after decades of presumed loss; Orochi survives through preservation associated with Bando and later restoration; Growth of the Soil was reconstructed from dispersed material; Red Heroine survives as one part of a larger serial; Häxan's tinting and toning have been reconstructed; The Sentimental Bloke and El automóvil gris were assembled through modern archive work. These histories make restoration a central film-history method rather than a technical appendix.",
      "Sound and color are especially easy to misdescribe. Silent films were rarely experienced in literal silence, but live music, benshi narration and later commissioned scores do not become synchronized production tracks merely because a digital file now contains audio. Tinting and toning belong to historical color practice even when photographed negatives were black-and-white, while a modern digital reconstruction may infer or recover those colors from surviving evidence. The chapter therefore labels production image, historical presentation, later score and restoration intervention separately whenever a claim depends on them.",
      "Runtime is equally unstable. Projection speed, censorship, serial-to-feature reassembly, lost footage and restoration choices can produce legitimate modern presentations of different lengths. A database runtime is useful for identifying a version but cannot settle the duration of every historical screening. Version criticism therefore becomes a practical habit: name the print or restoration, identify known changes, distinguish missing evidence from creative reconstruction and avoid precise shot-duration claims when the underlying version is not specified. The result is not historical uncertainty for its own sake; it is a more reproducible way to reason from fragile media.",
    ],
    sourceIds: ["ch10_page_umich", "ch10_orochi_lumiere", "ch10_growth_dfi_cinema", "ch10_red_ucla", "ch10_haxan_sfi_restore", "ch10_bloke_reconstruction_nfsa", "ch10_auto_cineteca", "ch10_labor_restore"],
  },
  {
    id: "ch10_plural_silent_to_sound_boundary",
    title: "15. Chapter 10 ends with plural silent systems and hands the industrial disruption of recorded sound to Chapter 11",
    paragraphs: [
      "The chapter's central conclusion is that 'silent cinema' names a period condition shared by radically different systems, not one worldwide style. Japanese benshi exhibition, Shanghai studio comedy and wuxia serials, Indian mythological and transnational productions, Danish star circulation, Swedish prestige filmmaking, Norwegian literary-location production, Australian vernacular feature culture and Mexican crime serials organized labor and audiences differently. Their films could exchange forms internationally without becoming culturally interchangeable. A global history becomes stronger when it compares specific institutions, practices and routes rather than grouping everything outside Hollywood under the label 'world cinema.'",
      "The archive adds a second conclusion: what survives is a historical outcome, not a neutral sample. Loss can make founders look more singular, surviving masterpieces more representative and restored versions more stable than they really are. The production cases therefore carry provenance and version safeguards, while P2 films and historical objects preserve evidence that cannot responsibly become complete gameplay. This is why the chapter can end with nine existing Atlas anchors, fifteen book-level comparisons and ten institutional or historiographic objects without treating the different categories as a hierarchy of artistic value.",
      "The endpoint of 1929 is also methodological. Recorded sound was already developing unevenly, and Japan's benshi system helps explain why transition timelines differed across markets, but the industrial consequences of microphones, sound-on-film and sound-on-disc, dialogue recording, multilingual versions, dubbing and altered camera practice belong to Chapter 11. Alam Ara in 1931 and later Japanese and Chinese sound transitions are therefore not pulled backward merely to create a dramatic finale. Chapter 10 closes on silent systems in their own production terms and passes a clearly defined technological and institutional problem to the sound-transition chapter.",
    ],
    sourceIds: ["ch10_nfaj_history", "ch10_labor_hkfa", "ch10_throw_bfi", "ch10_danish_history_dfi", "ch10_growth_nb", "ch10_bloke_nfsa", "ch10_auto_unam", "ch10_india_nitrate_fhf"],
  },
];
