import {
  DIRECTOR_APPLIED_LEARNING_GUIDES,
  type DirectorAppliedLearningGuide,
} from "./directorAppliedLearning.js";
import type { FilmWorkLanguage } from "./filmWorkLanguage.js";

const canonicalNorwegianPurposes = Object.fromEntries(
  DIRECTOR_APPLIED_LEARNING_GUIDES.map((guide) => [guide.id, guide.purpose]),
) as Readonly<Record<string, string>>;

export const FILM_DIRECTOR_PRACTICE_GUIDE_PURPOSES: Record<FilmWorkLanguage, Readonly<Record<string, string>>> = {
  en: {
    "brief:sceneTitle": "A precise working title makes it easier to discuss the scene's function, not just its number in the screenplay.",
    "brief:sceneContext": "The director needs to know which facts, relationships and expectations the audience and characters bring into the scene.",
    "brief:sceneObjective": "A playable objective gives the scene direction and makes it possible to judge whether the action actually changes anything.",
    "brief:audienceEffect": "Directing also means planning the audience's knowledge, emotion and expectation through the scene.",
    "brief:conflictTurn": "The scene needs resistance and a moment when tactics, power or information change direction.",
    "brief:formalStrategy": "A formal rule unifies choices in image, sound, performance and time, and makes departures from the rule meaningful.",
    "brief:blocking": "Position, distance, eyelines and movement express relationship and power before the camera is decided.",
    "brief:performanceDirection": "Precise direction gives the actor something concrete to do to another person instead of asking for a vague emotion.",
    "brief:productionDesign": "Space, costume, props, textures and colours must do dramatic work rather than merely decorate the scene.",
    "brief:shotPlan": "Coverage should express the scene's development while giving the editor enough material to build it.",
    "brief:cameraMovementLenses": "Camera position and optics determine perspective, spatial feeling, proximity and what the audience can discover.",
    "brief:lightingPalette": "Lighting needs a credible source logic while shaping faces, space, contrast and colour development.",
    "brief:editingRhythm": "The director plans duration, reactions, pauses and transitions before shooting, while allowing the material to challenge that plan in the edit.",
    "brief:soundStrategy": "Dialogue, ambience, room tone, isolated sounds, music and silence determine place, perspective and emotional focus.",
    "brief:practicalConstraints": "Time, budget, location, safety and available equipment must be translated into creative priorities before the shooting day.",
    "brief:proofOfIntent": "A directing idea must be assessable in the recorded and edited material, not merely sound convincing in a note.",
    "shot:title": "A short working title makes the camera setup easy to identify in the shot list, shooting plan and on-set conversation.",
    "shot:shotSize": "Shot size determines how much body, face, action and environment the audience can read at the same time.",
    "shot:cameraPosition": "The camera's side, height and distance affect screen direction, eyelines, power and the audience's place in the space.",
    "shot:movement": "Movement should react to or create a dramatic change; it should not merely add generic energy.",
    "shot:lens": "Focal length, camera distance and focus strategy shape perspective and determine how space and faces are perceived.",
    "shot:subjectAction": "The shot card must describe what the person actually does in the frame and which positions need to meet focus, lighting and composition.",
    "shot:dramaticPurpose": "Every shot must perform a narrative or emotional task that is not already served better by another shot.",
    "shot:sound": "A shot card should tell the sound department what must be clean, what can be recorded separately and which sound perspective the shot requires.",
    "shot:estimatedDuration": "Duration affects performance, camera movement, shooting time and how the shot can function within the editing rhythm.",
  },
  nb: canonicalNorwegianPurposes,
  fr: {
    "brief:sceneTitle": "Un titre de travail précis facilite la discussion sur la fonction de la scène, et pas seulement sur son numéro dans le scénario.",
    "brief:sceneContext": "Le réalisateur doit savoir quels faits, relations et attentes le public et les personnages apportent avec eux dans la scène.",
    "brief:sceneObjective": "Un objectif jouable donne une direction à la scène et permet d'évaluer si l'action produit réellement un changement.",
    "brief:audienceEffect": "La réalisation consiste aussi à organiser, tout au long de la scène, ce que le public sait, ressent et anticipe.",
    "brief:conflictTurn": "La scène a besoin d'une résistance et d'un moment où la tactique, le rapport de force ou l'information changent de direction.",
    "brief:formalStrategy": "Une règle formelle unifie les choix d'image, de son, de jeu et de temps, et donne du sens aux écarts à cette règle.",
    "brief:blocking": "Le placement, la distance, les regards et les déplacements expriment les relations et les rapports de force avant même de décider de la caméra.",
    "brief:performanceDirection": "Une direction précise donne au comédien quelque chose de concret à faire envers l'autre, plutôt que de lui demander une émotion vague.",
    "brief:productionDesign": "L'espace, les costumes, les accessoires, les textures et les couleurs doivent accomplir un travail dramatique, pas seulement décorer la scène.",
    "brief:shotPlan": "Le découpage doit exprimer l'évolution de la scène tout en donnant au monteur suffisamment de matière pour la construire.",
    "brief:cameraMovementLenses": "La position de la caméra et les optiques déterminent la perspective, la sensation d'espace, la proximité et ce que le public peut découvrir.",
    "brief:lightingPalette": "La lumière doit suivre une logique de sources crédible tout en modelant les visages, l'espace, le contraste et l'évolution des couleurs.",
    "brief:editingRhythm": "Le réalisateur prévoit la durée, les réactions, les pauses et les transitions avant le tournage, tout en laissant la matière remettre ce plan en question au montage.",
    "brief:soundStrategy": "Les dialogues, les ambiances, le son seul, les sons isolés, la musique et le silence déterminent le lieu, la perspective et le foyer émotionnel.",
    "brief:practicalConstraints": "Le temps, le budget, le lieu, la sécurité et le matériel disponible doivent être traduits en priorités créatives avant la journée de tournage.",
    "brief:proofOfIntent": "Une intention de réalisation doit pouvoir être évaluée dans la matière tournée et montée, et pas seulement paraître convaincante dans une note.",
    "shot:title": "Un titre de travail court permet d'identifier facilement le dispositif caméra dans la liste de plans, le plan de tournage et les échanges sur le plateau.",
    "shot:shotSize": "L'échelle de plan détermine quelle part du corps, du visage, de l'action et du décor le public peut lire simultanément.",
    "shot:cameraPosition": "Le côté, la hauteur et la distance de la caméra influencent la direction à l'écran, les regards, le rapport de force et la place du public dans l'espace.",
    "shot:movement": "Le mouvement doit réagir à un changement dramatique ou le provoquer ; il ne devrait pas seulement ajouter une énergie générale.",
    "shot:lens": "La focale, la distance caméra-sujet et la stratégie de mise au point façonnent la perspective et déterminent la perception de l'espace et des visages.",
    "shot:subjectAction": "La fiche de plan doit décrire ce que la personne fait réellement dans l'image et quelles positions doivent correspondre à la mise au point, à la lumière et à la composition.",
    "shot:dramaticPurpose": "Chaque plan doit accomplir une tâche narrative ou émotionnelle qui n'est pas déjà mieux remplie par un autre plan.",
    "shot:sound": "Une fiche de plan doit indiquer au département son ce qui doit être propre, ce qui peut être enregistré séparément et quelle perspective sonore le plan exige.",
    "shot:estimatedDuration": "La durée influence le jeu, le mouvement de caméra, le temps de tournage et la manière dont le plan peut fonctionner dans le rythme du montage.",
  },
  pt: {
    "brief:sceneTitle": "Um título de trabalho preciso facilita a discussão sobre a função da cena, e não apenas sobre o seu número no argumento.",
    "brief:sceneContext": "O realizador precisa de saber que factos, relações e expectativas o público e as personagens trazem para a cena.",
    "brief:sceneObjective": "Um objetivo jogável dá direção à cena e permite avaliar se a ação realmente muda alguma coisa.",
    "brief:audienceEffect": "Realizar também implica planear, ao longo da cena, o conhecimento, a emoção e a expectativa do público.",
    "brief:conflictTurn": "A cena precisa de resistência e de um momento em que a tática, o poder ou a informação mudam de direção.",
    "brief:formalStrategy": "Uma regra formal unifica escolhas de imagem, som, interpretação e tempo, e dá significado aos desvios dessa regra.",
    "brief:blocking": "A posição, a distância, as linhas de olhar e o movimento exprimem relações e poder antes de a câmara ser definida.",
    "brief:performanceDirection": "Uma direção precisa dá ao ator algo de concreto para fazer em relação ao outro, em vez de pedir uma emoção vaga.",
    "brief:productionDesign": "O espaço, o guarda-roupa, os adereços, as texturas e as cores têm de cumprir uma função dramática, não apenas decorar a cena.",
    "brief:shotPlan": "A cobertura deve exprimir a evolução da cena e, ao mesmo tempo, dar ao montador material suficiente para a construir.",
    "brief:cameraMovementLenses": "A posição da câmara e as objetivas determinam a perspetiva, a sensação de espaço, a proximidade e aquilo que o público pode descobrir.",
    "brief:lightingPalette": "A luz precisa de uma lógica de fontes credível, ao mesmo tempo que modela rostos, espaço, contraste e evolução cromática.",
    "brief:editingRhythm": "O realizador planeia duração, reações, pausas e transições antes da rodagem, deixando que o material desafie esse plano na montagem.",
    "brief:soundStrategy": "Diálogo, ambiente, som de sala, sons isolados, música e silêncio determinam lugar, perspetiva e foco emocional.",
    "brief:practicalConstraints": "Tempo, orçamento, localização, segurança e equipamento disponível têm de ser traduzidos em prioridades criativas antes do dia de rodagem.",
    "brief:proofOfIntent": "Uma ideia de realização tem de poder ser avaliada no material filmado e montado, e não apenas soar convincente numa nota.",
    "shot:title": "Um título de trabalho curto facilita a identificação da configuração de câmara na lista de planos, no plano de rodagem e na comunicação em plateau.",
    "shot:shotSize": "A escala do plano determina quanto do corpo, rosto, ação e ambiente o público consegue ler ao mesmo tempo.",
    "shot:cameraPosition": "O lado, a altura e a distância da câmara influenciam a direção no ecrã, as linhas de olhar, o poder e a posição do público no espaço.",
    "shot:movement": "O movimento deve reagir a uma mudança dramática ou criá-la; não deve apenas acrescentar energia genérica.",
    "shot:lens": "A distância focal, a distância da câmara e a estratégia de foco moldam a perspetiva e determinam como o espaço e os rostos são percecionados.",
    "shot:subjectAction": "O cartão de plano deve descrever o que a pessoa realmente faz no enquadramento e que posições têm de corresponder ao foco, à luz e à composição.",
    "shot:dramaticPurpose": "Cada plano deve cumprir uma tarefa narrativa ou emocional que não seja já melhor resolvida por outro plano.",
    "shot:sound": "Um cartão de plano deve indicar ao departamento de som o que tem de ficar limpo, o que pode ser gravado separadamente e que perspetiva sonora o plano exige.",
    "shot:estimatedDuration": "A duração influencia a interpretação, o movimento de câmara, o tempo de rodagem e a forma como o plano pode funcionar no ritmo da montagem.",
  },
};

export function getFilmDirectorPracticeGuidePurpose(language: FilmWorkLanguage, guide: DirectorAppliedLearningGuide): string {
  return FILM_DIRECTOR_PRACTICE_GUIDE_PURPOSES[language][guide.id] ?? guide.purpose;
}
