import {
  DIRECTOR_APPLIED_LEARNING_GUIDES,
  type DirectorAppliedLearningGuide,
} from "./directorAppliedLearning.js";
import type { FilmWorkLanguage } from "./filmWorkLanguage.js";

const canonicalNorwegianChecklists = Object.fromEntries(
  DIRECTOR_APPLIED_LEARNING_GUIDES.map((guide) => [guide.id, guide.checklist]),
) as Readonly<Record<string, readonly string[]>>;

export const FILM_DIRECTOR_PRACTICE_GUIDE_CHECKLISTS: Record<FilmWorkLanguage, Readonly<Record<string, readonly string[]>>> = {
  en: {
    "brief:sceneTitle": ["The name distinguishes the scene from the others", "The name points to the scene's dramatic development"],
    "brief:sceneContext": ["Time and place are clear", "Relevant backstory is bounded", "Differences in knowledge between characters are visible"],
    "brief:sceneObjective": ["The objective can be pursued through action", "The obstacle is active", "The stakes are concrete"],
    "brief:audienceEffect": ["The point of view is clear", "The tone is specific", "The audience effect changes"],
    "brief:conflictTurn": ["Conflicting objectives are visible", "The turn is caused by action or information", "The situation has a different value after the turn"],
    "brief:formalStrategy": ["The rule can be observed in the finished scene", "The rule supports the scene's dramatic idea", "Any deviation has a clear reason"],
    "brief:blocking": ["The movements are motivated", "Eyelines can be photographed", "The axis and screen direction are understood", "Blocking changes the relationship"],
    "brief:performanceDirection": ["Directions use active verbs", "The subtext is understood", "The actor has room to listen", "The adjustment describes a change"],
    "brief:productionDesign": ["The elements support character or conflict", "The palette is controlled", "Important props can withstand a close-up", "The environment affects blocking"],
    "brief:shotPlan": ["Every shot has a reason", "A master or alternative spatial orientation has been considered", "Crucial reactions are covered", "Inserts are used only when the information needs them"],
    "brief:cameraMovementLenses": ["Camera distance and focal length are considered together", "Depth of field has a function", "Movement is motivated", "Perspective supports the point of view"],
    "brief:lightingPalette": ["The key-light direction is understandable", "Practical sources are integrated", "Contrast supports the tone", "Colour choices follow the film's palette"],
    "brief:editingRhythm": ["Rhythm follows dramatic development", "Ellipses are understandable", "Cuts on action are used deliberately", "Picture and sound transitions are planned"],
    "brief:soundStrategy": ["Dialogue priority is decided", "Room tone and wild tracks are planned", "Sound perspective follows the point of view", "The function of the music is specific"],
    "brief:practicalConstraints": ["The main risk is identified", "Priority shots are marked", "Alternative setups exist", "Timing and moves are realistic"],
    "brief:proofOfIntent": ["The signs can be observed in dailies", "They connect to the formal rule", "They can be assessed before picture lock"],
    "shot:title": ["The subject is identified", "The dramatic function is visible in the name"],
    "shot:shotSize": ["The shot size fits the subject's action", "The importance of the environment is considered", "Proximity is dramatically motivated"],
    "shot:cameraPosition": ["The axis is known", "Eyelines can be matched", "Screen direction is controlled", "Distance and angle of view are chosen together"],
    "shot:movement": ["The movement has a triggering cause", "Start and end have different meaning", "The direction fits blocking and screen direction"],
    "shot:lens": ["Focal length is chosen together with camera distance", "Depth of field has a function", "Distortion is considered", "The focus shift is dramatically motivated"],
    "shot:subjectAction": ["The action can be performed", "Start and end positions are known", "Crossings are understood", "Blocking supports the scene objective"],
    "shot:dramaticPurpose": ["The shot changes knowledge, feeling or relationship", "Its function connects to the scene objective", "The chosen point of view is deliberate"],
    "shot:sound": ["Dialogue requirements are clear", "Ambience and room tone are considered", "A wild track is planned when needed", "Sound perspective fits the shot"],
    "shot:estimatedDuration": ["Duration is based on actual action", "The function of the rhythm is described", "Possible ellipses or cuts on action are considered"],
  },
  nb: canonicalNorwegianChecklists,
  fr: {
    "brief:sceneTitle": ["Le nom distingue la scène des autres", "Le nom indique l’évolution dramatique de la scène"],
    "brief:sceneContext": ["Le temps et le lieu sont compréhensibles", "Le passé pertinent est délimité", "Les différences de savoir entre les personnages sont visibles"],
    "brief:sceneObjective": ["L’objectif peut être poursuivi par l’action", "L’obstacle est actif", "L’enjeu est concret"],
    "brief:audienceEffect": ["Le point de vue est clair", "Le ton est précis", "L’effet sur le public évolue"],
    "brief:conflictTurn": ["Les objectifs opposés sont visibles", "La bascule vient d’une action ou d’une information", "La situation a une valeur différente après la bascule"],
    "brief:formalStrategy": ["La règle peut s’observer dans la scène terminée", "La règle soutient l’idée dramatique de la scène", "Tout écart a une raison claire"],
    "brief:blocking": ["Les déplacements sont motivés", "Les regards peuvent être filmés", "L’axe et la direction à l’écran sont maîtrisés", "Le placement modifie la relation"],
    "brief:performanceDirection": ["Les indications utilisent des verbes d’action", "Le sous-texte est compris", "Le comédien a l’espace pour écouter", "L’ajustement décrit un changement"],
    "brief:productionDesign": ["Les éléments soutiennent le personnage ou le conflit", "La palette est maîtrisée", "Les accessoires importants supportent un gros plan", "L’environnement influence le placement"],
    "brief:shotPlan": ["Chaque plan a une justification", "Un master ou une autre lecture de l’espace a été envisagé", "Les réactions décisives sont couvertes", "Les inserts ne sont utilisés que lorsque l’information l’exige"],
    "brief:cameraMovementLenses": ["Distance caméra et focale sont pensées ensemble", "La profondeur de champ a une fonction", "Le mouvement est motivé", "La perspective soutient le point de vue"],
    "brief:lightingPalette": ["La direction de la lumière principale est compréhensible", "Les sources pratiques sont intégrées", "Le contraste soutient le ton", "Les choix de couleur suivent la palette du film"],
    "brief:editingRhythm": ["Le rythme suit l’évolution dramatique", "Les ellipses sont compréhensibles", "Les coupes dans l’action sont utilisées consciemment", "Les transitions image-son sont planifiées"],
    "brief:soundStrategy": ["La priorité du dialogue est définie", "Le room tone et les wild tracks sont planifiés", "La perspective sonore suit le point de vue", "La fonction de la musique est précise"],
    "brief:practicalConstraints": ["Le risque principal est identifié", "Les plans prioritaires sont marqués", "Des dispositifs alternatifs existent", "Le temps et les déplacements sont réalistes"],
    "brief:proofOfIntent": ["Les signes sont observables dans les rushes", "Ils sont liés à la règle formelle", "Ils peuvent être évalués avant le picture lock"],
    "shot:title": ["Le sujet est identifié", "La fonction dramatique apparaît dans le nom"],
    "shot:shotSize": ["L’échelle du plan convient à l’action du sujet", "L’importance de l’environnement est prise en compte", "La proximité est justifiée dramatiquement"],
    "shot:cameraPosition": ["L’axe est connu", "Les regards peuvent être raccordés", "La direction à l’écran est maîtrisée", "La distance et l’angle de champ sont choisis ensemble"],
    "shot:movement": ["Le mouvement a un déclencheur", "Le début et la fin ont des significations différentes", "La direction respecte le placement et la direction à l’écran"],
    "shot:lens": ["La focale est choisie avec la distance caméra", "La profondeur de champ a une fonction", "La distorsion est prise en compte", "Le changement de point est motivé dramatiquement"],
    "shot:subjectAction": ["L’action est réalisable", "Les positions de départ et d’arrivée sont connues", "Les croisements sont compris", "Le placement soutient l’objectif de la scène"],
    "shot:dramaticPurpose": ["Le plan modifie une connaissance, une émotion ou une relation", "La fonction est liée à l’objectif de la scène", "Le point de vue choisi est délibéré"],
    "shot:sound": ["Le besoin de dialogue est clair", "L’ambiance et le room tone sont pris en compte", "Un wild track est prévu si nécessaire", "La perspective sonore convient au plan"],
    "shot:estimatedDuration": ["La durée repose sur l’action réelle", "La fonction du rythme est décrite", "Les ellipses ou coupes dans l’action possibles sont envisagées"],
  },
  pt: {
    "brief:sceneTitle": ["O nome distingue a cena das restantes", "O nome aponta para a evolução dramática da cena"],
    "brief:sceneContext": ["O tempo e o espaço são compreensíveis", "A história anterior relevante está delimitada", "As diferenças de conhecimento entre as personagens são visíveis"],
    "brief:sceneObjective": ["O objetivo pode ser perseguido através da ação", "O obstáculo é ativo", "O que está em jogo é concreto"],
    "brief:audienceEffect": ["O ponto de vista é claro", "O tom é concreto", "O efeito no público muda"],
    "brief:conflictTurn": ["Os objetivos em conflito são visíveis", "A viragem resulta de uma ação ou informação", "A situação tem um valor diferente depois da viragem"],
    "brief:formalStrategy": ["A regra pode ser observada na cena final", "A regra apoia a ideia dramática da cena", "Qualquer desvio tem uma razão clara"],
    "brief:blocking": ["Os movimentos têm motivação", "As linhas de olhar podem ser filmadas", "O eixo e a direção no ecrã são compreendidos", "A marcação altera a relação"],
    "brief:performanceDirection": ["As indicações usam verbos de ação", "O subtexto é compreendido", "O ator tem espaço para escutar", "O ajuste descreve uma mudança"],
    "brief:productionDesign": ["Os elementos apoiam a personagem ou o conflito", "A paleta é controlada", "Os adereços importantes suportam um grande plano", "O espaço influencia a marcação"],
    "brief:shotPlan": ["Cada plano tem uma justificação", "Foi considerado um master ou uma leitura espacial alternativa", "As reações decisivas estão cobertas", "Os inserts são usados apenas quando a informação os exige"],
    "brief:cameraMovementLenses": ["A distância da câmara e a distância focal são consideradas em conjunto", "A profundidade de campo tem uma função", "O movimento é motivado", "A perspetiva apoia o ponto de vista"],
    "brief:lightingPalette": ["A direção da luz principal é compreensível", "As fontes práticas estão integradas", "O contraste apoia o tom", "As escolhas de cor seguem a paleta do filme"],
    "brief:editingRhythm": ["O ritmo acompanha a evolução dramática", "As elipses são compreensíveis", "Os cortes na ação são usados de forma consciente", "As transições de imagem e som estão planeadas"],
    "brief:soundStrategy": ["A prioridade do diálogo está definida", "O room tone e os wild tracks estão planeados", "A perspetiva sonora acompanha o ponto de vista", "A função da música é concreta"],
    "brief:practicalConstraints": ["O risco principal está identificado", "Os planos prioritários estão assinalados", "Existem setups alternativos", "O tempo e as deslocações são realistas"],
    "brief:proofOfIntent": ["Os sinais podem ser observados nos dailies", "Estão ligados à regra formal", "Podem ser avaliados antes do picture lock"],
    "shot:title": ["O motivo está identificado", "A função dramática é visível no nome"],
    "shot:shotSize": ["A escala do plano adequa-se à ação do motivo", "A importância do espaço foi considerada", "A proximidade tem justificação dramática"],
    "shot:cameraPosition": ["O eixo é conhecido", "As linhas de olhar podem ter raccord", "A direção no ecrã está controlada", "A distância e o ângulo de visão são escolhidos em conjunto"],
    "shot:movement": ["O movimento tem uma causa desencadeadora", "O início e o fim têm significados diferentes", "A direção respeita a marcação e a direção no ecrã"],
    "shot:lens": ["A distância focal é escolhida em conjunto com a distância da câmara", "A profundidade de campo tem uma função", "A distorção foi considerada", "A mudança de foco tem motivação dramática"],
    "shot:subjectAction": ["A ação pode ser executada", "As posições inicial e final são conhecidas", "Os cruzamentos são compreendidos", "A marcação apoia o objetivo da cena"],
    "shot:dramaticPurpose": ["O plano altera conhecimento, emoção ou relação", "A função liga-se ao objetivo da cena", "O ponto de vista escolhido é deliberado"],
    "shot:sound": ["A necessidade de diálogo é clara", "O ambiente e o room tone foram considerados", "É planeado um wild track quando necessário", "A perspetiva sonora adequa-se ao plano"],
    "shot:estimatedDuration": ["A duração baseia-se na ação real", "A função do ritmo está descrita", "Possíveis elipses ou cortes na ação foram considerados"],
  },
};

export function getFilmDirectorPracticeGuideChecklist(language: FilmWorkLanguage, guide: DirectorAppliedLearningGuide): readonly string[] {
  return FILM_DIRECTOR_PRACTICE_GUIDE_CHECKLISTS[language][guide.id] ?? guide.checklist;
}
