import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterTwoMovementTwo: readonly FilmHistoryBookSection[] = [
  {
    id: "fairgrounds-travelling-bioscopes",
    title: "5. Fairgrounds and travelling bioscopes",
    sourceIds: [
      "loc_variety_stage_context",
      "nsm_short_history_cinema",
      "bfi_sedgwick_showfront",
      "bfi_mitchell_kenyon_collection",
    ],
    paragraphs: [
      "Fairground cinema makes the mobility of early exhibition impossible to ignore. A travelling showman had to transform cinema from a laboratory apparatus into a transportable business. Equipment, films, lighting, seating or standing space, façade and publicity all had to survive movement between places and compete for attention beside other attractions. The showfront mattered because the audience could not be assumed. It had to be gathered. From outside, a bioscope booth could advertise technological modernity, spectacular pictures and the energy of the performance within. The fairground setting also complicates any simple distinction between old entertainment and new media. Cinema did not replace the fair; it entered the fair's established economy of spectacle and used its skills in crowd management, novelty and rapid turnover.",
      "Travelling exhibition also created a distinctive relationship to geography. A film print could carry distant places into a town, but the exhibitor could increase the programme's value by adding material made nearby. That combination made cinema simultaneously global and intensely local. Imported views, comic films and trick pictures could demonstrate the reach of the medium, while a factory gate, football crowd or civic procession photographed in the same region promised recognition. The BFI's Mitchell and Kenyon collection shows how productive that commercial logic became in Britain. Their company worked with fairground operators and other showmen across northern and central England, Scotland, Ireland and Wales. The films were not simply documents that happened to find local audiences later. Many were produced within a circuit whose economic purpose depended on showing local people back to themselves.",
      "The surviving Sedgwick's Bioscope Showfront film provides unusual evidence of the front end of that circuit. Its value is not primarily that it contains a complex story or a unique photographic technique. It shows activity designed to attract customers before they enter the bioscope. The BFI connects the commission to the showman's relationship with Mitchell and Kenyon and describes performances around the showfront as a means of drawing a crowd. Such evidence helps restore labour that disappears when film history begins with the projected image. Showpeople had to choose locations, negotiate fairground space, transport equipment, maintain machinery, publicize programmes and manage repeated performances. Their decisions connected production to audiences through a commercial network that was flexible enough to reach communities without permanent cinemas.",
      "Fairgrounds also warn against making exhibition history too metropolitan. Paris, London and New York are indispensable because their surviving records document important demonstrations, companies and entertainment industries. Yet a medium becomes socially widespread through provincial and regional circuits as well. Travelling exhibitors could bring projected pictures to towns whose audiences were not regular patrons of metropolitan music halls. Local commissions could then turn those audiences into subjects. The resulting history is less a story in which innovation radiates from a few capitals and more a network in which machines, prints, showpeople and filming practices move in several directions. Regional demand could generate production rather than merely consume what a central industry supplied.",
      "The fairground model remained one exhibition form among several, and its importance should not be converted into a claim that all early cinema was itinerant. Permanent venues and storefront theatres became increasingly significant, while established theatres continued to include films in mixed bills. What fairground history contributes is a clear demonstration that cinema's institutional identity was initially open. A projector could belong to a travelling bioscope, a music hall or another temporary arrangement. This openness allowed rapid diffusion and experimentation, but it also meant that the same film could enter very different social frames. The next case study narrows that point to one local actuality, where the anticipated paying audience is visible inside the image itself.",
    ],
  },
  {
    id: "local-films-local-audiences",
    title: "6. Local films for local audiences",
    sourceIds: [
      "bfi_browns_atlas",
      "bfi_mitchell_kenyon_collection",
      "bfi_electric_edwardians",
      "sheffield_browns_context",
    ],
    paragraphs: [
      "Employees Leaving Brown's Atlas Works, Sheffield, filmed in 1901, initially resembles a simple actuality: workers emerge through a factory gate and pass before a fixed camera. Its exhibition history makes the scene more complicated. The BFI notes visible crowd management and situates such factory-gate films within Mitchell and Kenyon's practice. People do not merely happen to cross an indifferent recording machine. They are being organized into a view designed to make faces, movement and collective presence legible. Some acknowledge the camera directly. Children and workers become performers at the edge of documentary and spectacle. The film is still an actuality in the sense that it records a real place and real participants, but actuality here does not mean untouched reality. Production decisions structure what can be recognized later on the screen.",
      "Recognition was the commercial engine. BFI material on Mitchell and Kenyon describes their films as local films for local people and emphasizes that audiences paid to see neighbours, relatives and themselves. This reverses the usual assumption that an audience is external to production. For a local film, the prospective audience may already be in front of the lens. The camera creates not only an image but a reason to attend. Someone photographed leaving work can return later as a customer, bringing family or friends who hope to identify familiar faces. The film's value is therefore partly relational. A similar view made in another town would not be interchangeable because the identities and places on screen are the attraction.",
      "That business model helps explain formal choices that might otherwise be dismissed as primitive. A stable, sufficiently wide viewpoint lets many people pass through the frame, but the camera must remain close enough for recognition. The end of a shift produces a dense flow of bodies without requiring a fictional script. Crowd management can increase visibility and keep movement directed toward the lens. A wave or glance at the camera may be commercially productive rather than an error that breaks an imagined documentary rule. Later observational conventions often ask subjects to ignore the filmmaking apparatus. These local actualities operate under another logic: acknowledgment can confirm the encounter between filmmaker, participant and future spectator.",
      "The local-film economy also distributes authorship differently from a modern feature production. Sagar Mitchell and James Kenyon were filmmakers and business partners working within commissions and exhibition relationships. The showman who ordered or presented a film could shape subject choice because he understood the audience he needed to attract. The BFI records a possible connection between the Brown's Atlas Works film and the showman A. D. Thomas, but treats the attribution cautiously. That uncertainty is instructive. Historical reconstruction should preserve the difference between a plausible commission context and a documented credit. It is better to describe a network of filmmaker, showman, workplace and audience than to force every surviving actuality into a later director-producer hierarchy for which the evidence is incomplete.",
      "Employees Leaving Brown's Atlas Works is therefore an anchor for a wider principle: exhibition can reach backward into production. If the commercial promise is local recognition, the choice of location, time of day, crowd, framing and even participant behavior follows from that promise. The film does not become less historical because some movement is staged or marshalled; instead, the staging is part of the history we need to understand. For the Film Atlas, the case is valuable because the production challenge cannot be solved by generic documentary realism. The player must recognize the local audience as a design variable. For the book, the case demonstrates how a public habit of cinema could grow through communities seeing themselves as part of the new medium.",
    ],
  },
  {
    id: "event-cinema-corbett-fitzsimmons",
    title: "7. Event cinema at feature scale",
    sourceIds: [
      "loc_corbett_fitzsimmons",
      "nsm_corbett_fitzsimmons",
      "ucp_streible_fight_pictures",
      "afi_corbett_fitzsimmons",
    ],
    paragraphs: [
      "The Corbett–Fitzsimmons Fight of 1897 reveals another way in which the anticipated audience could determine an entire production system. The heavyweight championship bout between James J. Corbett and Bob Fitzsimmons in Carson City was not filmed as a brief novelty extracted from a larger event. Enoch J. Rector and the Veriscope operation attempted to record the fight across its full fourteen rounds and intervals. The Library of Congress and the National Science and Media Museum describe a production extending to roughly one hundred minutes and involving three cameras positioned to maintain coverage. At a moment when many films lasted well under a minute, the duration itself was an engineering, logistical and commercial proposition. The audience was being sold the possibility of re-experiencing a major event in extraordinary temporal detail.",
      "Long duration changed the capture problem. A single short reel could not simply run through the whole contest. The production required planned handoffs among adjacent cameras and a format capable of supporting the Veriscope system. The surviving evidence identifies a wide-gauge film around 63 mm and proprietary projection requirements. These technical choices cannot be separated from exhibition. A special capture system created a special projection dependency. The film's commercial value therefore rested not only in ownership of a negative but in control over an apparatus and a way of presenting it. Production and exhibition were designed together more tightly than in a later standardized 35 mm market where a print could be expected to run on compatible equipment almost anywhere.",
      "The fight also demonstrates why distribution rights belong inside production history. The Library of Congress documents territorial arrangements and local theatre deals associated with Veriscope exhibition. Rights to show the event in particular areas transformed the film into a geographically managed commodity. Tickets monetized the prestige of an event that spectators already knew from sport and press culture. Live expert commentary could accompany projection, helping audiences interpret the photographed contest. Again, recorded silence did not mean a silent event. The complete system joined a famous live occurrence, special cameras, proprietary film gauge, controlled projection, territorial rights, local promotion, commentary and admission revenue. Calling the result merely a long actuality would miss the industrial coordination that made the length worthwhile.",
      "The historical record also contains traps. Later material associated with Sigmund Lubin reproduced or imitated the fight, and cataloguing traditions have sometimes blurred credits between the Veriscope original and later facsimile material. The Library of Congress explicitly distinguishes Rector and Dan Stuart's original production from Lubin's reproduction and cautions against crediting William A. Brady as producer of the original simply because he was connected to Corbett and appears in conflicting metadata. The surviving original is fragmentary. Those distinctions matter because a production history can be falsified by treating every image labelled with the fight as one stable film. Version history is not an archival footnote; it determines which apparatus, rights and production decisions belong to which object.",
      "As a chapter anchor, The Corbett–Fitzsimmons Fight expands the meaning of early cinema in two directions. First, it shows that long-form event recording existed before feature fiction became an industrial norm, so duration alone should not be treated as evidence of mature narrative cinema. Second, it makes exhibition economics visible in production design. The cameras, gauge and coverage strategy make sense because a paying public wanted the championship event; the proprietary projector and rights structure make sense because the owners wanted to control that demand. The case therefore joins technology, sport, media rights and spectatorship. It is an early example of event cinema in the strongest sense: not simply a film about an event, but a film whose production and exhibition were organized around the event's public value.",
    ],
  },
  {
    id: "spectatorship-without-panic-myth",
    title: "8. Audience history without the train-panic myth",
    sourceIds: [
      "loc_uncle_josh",
      "loc_edison_comedy",
      "afi_uncle_josh",
      "rutgers_viewing_positions",
    ],
    paragraphs: [
      "Audience history becomes especially difficult when fictional representations of spectators are mistaken for direct evidence of how real people behaved. Edwin S. Porter's Uncle Josh at the Moving Picture Show, made for Edison in 1902, is a perfect test. The film places the familiar rural comic character Uncle Josh before projected attractions. He responds physically to a dancing woman, retreats from an approaching express train, interferes with a country-couple scene and finally tears down the screen, exposing the operator behind it. The joke depends on a spectator who cannot maintain the boundary between projected representation and the physical space around him. Because the scenario seems to dramatize famous stories about naïve early viewers, it can be tempting to treat the comedy as proof that such responses were normal. That is precisely what the film cannot establish.",
      "The Library of Congress places Uncle Josh within the Edison company's rube-comedy tradition. The rural figure confronted by modern technology was already a comic type. His confusion is scripted and performed by Charles Manley for an audience expected to understand the exaggeration. The train is therefore not a hidden documentary camera catching a genuine spectator panic; it is one step in an escalating gag. The comedy works because viewers can see more than Josh can. They understand the projection setup and anticipate the consequences of his misreading. Treating him as a representative sample of 1902 spectators would erase the very comic competence that the real audience needs in order to enjoy the film.",
      "This distinction belongs to a larger historiographic debate about early spectatorship. Tom Gunning's work on the aesthetic of astonishment and the credulous-spectator problem challenged simplistic versions of the story in which the first audiences were so visually unsophisticated that they treated moving photographs as physical reality. Astonishment need not mean perceptual incapacity. Spectators can understand that an image is an image while still responding strongly to scale, movement, novelty and the social performance of projection. The recurring legend that audiences fled from an oncoming Lumière train compresses a much richer history into an anecdote. Responsible film history asks what evidence survives for particular screenings and distinguishes contemporary publicity, later memory, fiction and scholarly reconstruction.",
      "Uncle Josh remains historically valuable once it is removed from the role of documentary witness. The film tells us that spectatorship itself had become a subject for comedy. Cinema was familiar enough that filmmakers could stage a screen inside a screen, represent a type of viewer and expose the projection apparatus as a punch line. The final destruction of the screen makes exhibition space visible: image, spectator and operator occupy different physical layers. The fixed camera must keep those layers legible so that the joke can move from illusion to reveal. The film is therefore self-reflexive without needing to be a theoretical essay. It converts the social situation of going to moving pictures into material for moving pictures.",
      "The lesson extends beyond one comedy. Audience response should be reconstructed from multiple kinds of evidence: venue records, programmes, journalism, correspondence, publicity, memoirs, business data and films, with each source read according to what it can actually show. A promotional account may exaggerate amazement; a comic film may caricature ignorance; a later memoir may reshape an experience through nostalgia. None is useless, but none should dominate automatically. This evidentiary discipline is essential because early cinema has accumulated powerful myths precisely where documentation is uneven. The goal is not to drain wonder from the period. It is to understand astonishment historically—as a response produced by technology, showmanship, familiarity and expectation—rather than to imagine a universal audience unable to tell screen from world.",
    ],
  },
];
