import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterEightMovementOne: readonly FilmHistoryBookSection[] = [
  {
    id: "ch8_plural_french_field",
    title: "1. The French avant-gardes were a field of overlapping institutions, not one anti-commercial style",
    paragraphs: [
      "Calling 1920s French cinema an avant-garde is useful only if the term remains plural. Louis Delluc, Germaine Dulac, Jean Epstein, Abel Gance and Marcel L'Herbier worked through commercial companies, independent firms, criticism, cine-clubs and specialist venues while artists such as Fernand Léger, Man Ray, Francis Picabia and Marcel Duchamp approached film from painting, photography, poetry or performance. MoMA's survey of the French avant-garde stresses this unusually open traffic between filmmakers and visual artists, while La Cinémathèque française identifies Delluc as a leading figure of the first French avant-garde often called Impressionist. The field was therefore held together less by one visual signature than by arguments over what cinema could do that theatre, literature and painting could not.",
      "That institutional plurality matters for production history. Cœur fidèle was made within Pathé Consortium Cinéma; Napoléon mobilized large companies, many camera operators and exceptional exhibition hardware; Dulac combined commercial narrative work with explicitly experimental films and her own production activity; Entr'acte was commissioned for a Ballets Suédois event; Man Ray and Léger brought artist networks into short-form moving images; Un Chien Andalou relied on small-scale alternative financing and specialist exhibition. To call all of these works simply 'non-commercial' would erase the contracts, companies, patrons, venues and distribution systems that made them possible. Their alternatives were relative to particular industrial norms, not an existence outside economics.",
      "The chapter therefore treats Impressionism, Dada, cinéma pur and Surrealism as intersecting historical formations rather than levels on one progression bar. A technique such as superimposition may serve Epstein's emotional perception, Gance's epic accumulation, Man Ray's abstraction or Buñuel and Dalí's discontinuous association; the same optical procedure does not imply the same artistic program. Likewise, a close-up may intensify photogénie, performance, documentary detail or Dreyer's radically isolated faces. The production question is always relational: who financed the work, what was the intended venue, which crafts coordinated the effect, what kind of spectator relation was sought, and how did later criticism name the result.",
    ],
    sourceIds: ["ch8_field_moma", "ch8_delluc_cinematheque", "ch8_dulac_moma", "ch8_france1920_corpus"],
  },
  {
    id: "ch8_photogenie_theory",
    title: "2. Photogénie was an argument about cinematic transformation, not a measurable camera effect",
    paragraphs: [
      "Photogénie is among the most famous and most easily flattened concepts in French film theory. Delluc, Epstein and other writers used the term in changing ways to describe cinema's capacity to reveal or transform the expressive value of faces, objects, movement and duration. La Cinémathèque's Epstein restoration corpus places photogénie inside his sustained investigation of time and movement, while its retrospective account connects his rapid early career to books such as Bonjour cinéma and to the first-avant-garde milieu. The concept therefore belongs to criticism and theory before it belongs to any particular lens, lighting setup or edit pattern. It cannot responsibly be implemented as a numeric 'photogenic' score attached to performers, props or locations.",
      "In production terms, the theory becomes useful when it generates testable relationships. A face may change under duration, proximity and motion; a fairground apparatus may become expressive through camera movement and cutting; an ordinary object may acquire emotional weight when repeated or isolated; slow motion may make a familiar gesture newly strange. None of those techniques guarantees photogénie, because the historical claim concerns a transformation produced by cinema as an ensemble of framing, movement, rhythm and spectatorship. The game therefore teaches players to specify what an image is meant to reveal and which coordinated choices might produce that relation, rather than to select a preset named after a contested critical term.",
      "The same caution prevents a false invention narrative. Cinémathèque material around Cœur fidèle preserves Henri Langlois's warning that Epstein synthesized possibilities that cinema already possessed rather than inventing every celebrated device in one film. Delluc likewise drew on American and Swedish cinema while arguing for a distinctive French critical vocabulary. French Impressionism is consequently best understood as an unusually self-conscious conversation among filmmakers, critics and institutions about perception, rhythm and specifically cinematic expression. That makes theory operational for production study without pretending that a manifesto is a patent or that one film marks a clean technical beginning.",
    ],
    sourceIds: ["ch8_epstein_corpus", "ch8_epstein_retrospective", "ch8_delluc_cinematheque", "ch8_coeur_cinematheque"],
  },
  {
    id: "ch8_dulac_subjectivity",
    title: "3. Dulac made interior life, gender and rhythm into production problems rather than decorative themes",
    paragraphs: [
      "Germaine Dulac is indispensable to the chapter because her career breaks several retrospective simplifications at once. MoMA describes her as a central figure of the 1920s French avant-garde who worked across narrative, avant-garde and documentary forms, maintained production independence, wrote theory and participated in cine-club organization. La Cinémathèque's scholarship likewise presents her as a feminist, socialist and prolific filmmaker whose work moved between commercial structures and experiments in what she called the inner life of cinema. This breadth matters: Dulac was not a marginal exception who appeared only when Surrealism needed a precursor, but a producer-director-theorist whose industrial and intellectual work helped constitute the field.",
      "The Smiling Madame Beudet makes that history concrete. Its stage-derived bourgeois marriage becomes cinematic through the contrast between constrained domestic routine and Madame Beudet's subjective fantasies, gestures and symbolic associations. Cinémathèque credits Dulac and André Obey with the screenplay adaptation, Le Film d'Art - Vandal et Delac with production, Charles Delac and Marcel Vandal as producers and Maurice Forster and Paul Parguel with photography. The Production Case therefore treats subjectivity as collaborative construction: room geography, performance, object recurrence, emphasis and associative montage must work together. Feminist interpretation emerges from how the film organizes unequal social space and desire, not from assigning a generic empowerment bonus to the protagonist.",
      "Dulac's broader practice also warns against making 'women's cinema' a stylistic box. Cinémathèque accounts of her work emphasize symbolic iconography, associative montage, realistic performance, superimposition, blur, slow and accelerated motion, but those devices appear across different genres and purposes. Her feminist politics and experiments inform one another without becoming identical. The chapter therefore keeps gender, authorship and industrial access visible while resisting both erasure and tokenization: women were producers, theorists, performers and organizers in the avant-garde field, and their labor should be traced through credits, archives and institutions rather than retroactively reduced to a single thematic category.",
    ],
    sourceIds: ["ch8_dulac_moma", "ch8_dulac_classic_modern", "ch8_dulac_sensations", "ch8_beudet_cinematheque", "ch8_beudet_fondation"],
  },
  {
    id: "ch8_epstein_coeur",
    title: "4. Cœur fidèle turns a spare melodrama into a laboratory of perception, rhythm and collaborative camera work",
    paragraphs: [
      "Jean Epstein's Cœur fidèle is the chapter's clearest playable anchor for French Impressionist perception because its formal ambition is attached to an unusually simple melodramatic situation. La Cinémathèque credits Jean and Marie Epstein for the screenplay, Marie Epstein as assistant director, Paul Guichard as director of photography and Léon Donnot and Henri Stuckert as camera operators within Pathé Consortium Cinéma. That credit structure is already a lesson: the film's famous visual intensity did not emerge from an abstract auteur mind operating alone. It depended on writing, direction, photography, camera operation, performers and a company capable of mounting and circulating the production.",
      "BFI emphasizes subjective camera, poetic superimposition and innovative rhythmic editing, especially in the fairground sequence. The sequence is productive for gameplay because it can be decomposed into coordinated actions: capture readable fragments of machinery, faces and motion; vary proximity and movement; repeat motifs; shorten shot duration; layer images where appropriate; and let the accelerating relation among shots express emotional pressure. The lesson is not 'use fast montage to make Impressionism.' It is that rhythm can carry subjective information when the photographed material has been planned to support the edit. Formal intensity therefore grows from coverage design and editorial relation rather than a detachable post-production filter.",
      "The film also demonstrates why melodrama and experimentation should not be treated as opposites. BFI's silent-romance discussion notes that Epstein's formal sophistication transforms rather than abolishes a spare tragic design. The emotional stakes give the perceptual experiments direction, while the experiments alter how those stakes are felt. This interaction explains why Cœur fidèle is a Production Case and The Fall of the House of Usher remains a book-level comparison: the later film extends Epstein's slow motion, mobile camera, superimposition and atmospheric rhythm, but the core production problem of perception-led image organization is already playable here without multiplying near-duplicate cases.",
    ],
    sourceIds: ["ch8_coeur_cinematheque", "ch8_bfi_1923", "ch8_bfi_silent_romances", "ch8_usher_cinematheque", "ch8_usher_restoration"],
  },
  {
    id: "ch8_gance_scale_rhythm",
    title: "5. Gance links accelerated montage to industrial scale, camera logistics and unstable versions",
    paragraphs: [
      "Abel Gance demonstrates that formal radicalism was not confined to inexpensive shorts. La Roue and Napoléon required long schedules, extensive crews, company financing, location and studio coordination and complex release histories. Cinémathèque credits La Roue to Société des Films Abel Gance with Charles Pathé as producer and Léonce-Henri Burel, Marc Bujard and Maurice Duverger in photography; its archival account describes multiple versions between 1922 and 1929 and a restoration aimed at the February 1923 state. Rapid cutting, superimposition and accelerated imagery thus belong simultaneously to aesthetics, industrial endurance and version control. An edit cannot be historicized responsibly without asking which assembly of the film is being discussed.",
      "Napoléon magnifies those relations. Cinémathèque's technical material documents eight cameramen, eighteen cameras and a patented triple-screen process, while BFI describes sequence-specific rigs including chest-mounted, vehicle, horse, overhead and pendulum-like solutions as well as split and multiple exposures. Polyvision is therefore not an aspect-ratio slider. It required three-camera capture and an exhibition situation capable of three adjacent projections, sometimes operating independently and sometimes forming a panorama. The Production Case makes the player coordinate capture, editorial design and venue capability, showing why spectacular form can depend on infrastructure far beyond the individual shot.",
      "Version history is equally central. Cinémathèque distinguishes the April 1927 Opéra presentation, a much longer Apollo assembly, MGM/export recutting, Gance's later sound reworking and modern reconstruction. Its current Grande Version is presented in two parts of 220 and 205 minutes, a representative restoration state rather than proof of one untouched 425-minute original. Gance's work consequently provides a bridge between invention rhetoric and archival discipline: ambitious filmmakers may push apparatus and form, but historians must separate what was shot, what was assembled for a particular premiere, what distributors changed, and what restorers later reconstructed from surviving evidence.",
    ],
    sourceIds: ["ch8_roue_cinematheque", "ch8_roue_launch", "ch8_napoleon_cinematheque", "ch8_napoleon_machines", "ch8_napoleon_bfi", "ch8_napoleon_comet", "ch8_napoleon_grande_version"],
  },
];
