import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterOneMovementOne: readonly FilmHistoryBookSection[] = [
  {
    id: "what-does-it-mean-to-invent-film",
    title: "1. What does it mean to ‘invent film’?",
    sourceIds: [
      "nsm_short_history_cinema",
      "nsm_celluloid_beginnings",
      "loc_edison_origins",
      "nsm_robert_paul",
      "nsm_lumiere",
      "loc_projectors_vitascope",
    ],
    paragraphs: [
      "Film history becomes misleading the moment it asks for a single inventor before deciding what, exactly, is supposed to have been invented. A device that records a short sequence of photographs is not yet the same thing as a machine that lets one customer inspect moving images, and neither is the same thing as a projector capable of throwing an image onto a screen for a roomful of spectators. Even projection does not by itself create the social institution later called cinema. Films must be produced in sufficient quantity, prints or machines must circulate, exhibitors must find audiences, programmes must be assembled, and spectators must learn what kind of experience they are being offered. The emergence of cinema therefore belongs to a chain of technical, commercial, aesthetic and social solutions rather than to one inspired moment. This chapter begins from that chain. Its question is not ‘who invented the movies?’ but ‘how did photographs of movement become a repeatable medium with its own production practices and expressive possibilities?’",
      "That distinction changes the chronology. If the criterion is photographic analysis of movement, important beginnings appear in the 1870s and 1880s, before there was a practical motion-picture industry. If the criterion is a machine that records successive pictures on a strip and makes them appear to move, the early 1890s become decisive. If the criterion is individual commercial viewing, the Kinetoscope parlour matters. If the criterion is projected moving photographs, several inventors and businesses in several countries crowd into 1895 and 1896. If the criterion is a recurring public institution in which audiences buy access to programmes of films, the answer depends on exhibition networks and business practices as much as on apparatus. No date is useless; each date answers a different question. The danger comes when one answer is promoted into a universal birthday and the other processes disappear from view.",
      "A systems approach also prevents national myths from swallowing the history. Edison and W. K. L. Dickson developed an extraordinarily important camera-and-viewer system in the United States, but Edison did not patent the Kinetoscope in Britain, a circumstance that helped Robert W. Paul enter moving pictures there. Paul first manufactured Kinetoscope copies, then faced the practical problem that his customers needed fresh films, collaborated with Birt Acres on a camera, and moved toward projection. In France, the Lumière family’s photographic business, engineering resources and Cinématographe produced another influential solution. Elsewhere, inventors and showmen pursued competing projectors, cameras and viewing systems. These paths were not isolated races toward a finish line already called ‘cinema’. They were commercial and technical experiments whose participants often understood the problem differently and whose solutions borrowed, competed and overlapped.",
      "The word ‘invention’ can obscure another fact: a medium has to be used before its possibilities become visible. A camera mechanism may make a moving image technically possible, yet filmmakers still have to discover what subjects work, how close a performer can come to the lens, how an action can continue from one shot to another, what happens when an image is stopped and restarted, and how a film can be staged for a rectangle rather than for a theatre audience. Exhibitors likewise discover what kinds of programmes keep spectators interested. The medium is therefore invented twice over: materially, through apparatus and photographic stock, and practically, through thousands of decisions made in production and presentation. Those decisions do not occur after the ‘real’ invention. They are part of what turns a device into cinema.",
      "For the same reason, this chapter will resist a ladder-of-progress story in which each early film exists only because it contains a primitive version of something that later becomes normal. A one-shot actuality is not merely an immature narrative film waiting to learn editing. A Kinetoscope subject is not simply failed projection. A trick film is not a detour before realism. Each belongs to a particular production and exhibition situation and may be highly accomplished within it. The goal is to understand how different practices coexisted and interacted until, by about 1905, filmmakers had a much larger repertoire of ways to organize images than they possessed three decades earlier. The chapters that follow will trace exhibition and narrative systems in detail; here the task is to establish the conditions from which those histories become possible.",
    ],
  },
  {
    id: "photography-learns-to-record-time",
    title: "2. Before cinema: photography learns to record time",
    sourceIds: [
      "loc_horse_in_motion",
      "loc_muybridge_animal_locomotion",
      "nsm_celluloid_beginnings",
      "nsm_marey_motion_capture",
    ],
    paragraphs: [
      "Long before cinema became a public entertainment business, photography was being asked to solve a different problem: how can movement be examined when the eye cannot easily separate its phases? Faster photographic emulsions and shorter exposure times made it possible in the late nineteenth century to freeze actions that earlier processes blurred. Eadweard Muybridge’s celebrated horse studies, undertaken in California in the 1870s and widely associated with the 1878 sequences of a horse in motion, converted locomotion into a series of discrete photographic instants. Multiple cameras arranged along the track were triggered in succession as the animal passed. The result did more than settle arguments about a horse’s gait. It made a powerful visual claim: an action that appears continuous to human perception can be divided, inspected and reordered as a sequence of images.",
      "Muybridge’s work belongs to photography, scientific observation, commercial publishing and visual spectacle at once. His later Animal Locomotion plates extended sequential photography across human and animal movement. The images could be studied as data, but they could also be recombined for display. His Zoopraxiscope projected drawn or photographic-derived phases around a rotating disc, helping audiences experience analysed movement as reanimated motion. It would be too simple to call the device ‘the first movie projector’: the material and mechanical principles differed from the film-strip systems that became commercially dominant. Its importance is conceptual. Motion could now circulate in two directions — broken into measurable phases and re-synthesized into an illusion of continuous movement. Cinema would make that double operation routine.",
      "Étienne-Jules Marey approached the problem with a different scientific emphasis. Interested in physiology and the mechanics of bodies, he developed chronophotographic techniques for recording successive phases from a single viewpoint. His photographic gun of 1882 could record multiple exposures in rapid succession on a rotating plate; later arrangements placed multiple phases on one plate or, as materials changed, onto moving strips. Where Muybridge’s bank of cameras distributed an action across separate viewpoints, Marey’s systems sought to register change through time from one optical position. The contrast matters because there was no single straight technical line from motion study to cinema. Researchers were designing apparatus around the questions they wanted to ask, and those questions shaped how time appeared in the image.",
      "The term chronophotography — literally the photography of time — captures the historical shift. Photography had long been associated with fixing a moment. Sequential and multiple-exposure experiments made duration itself into an object that could be recorded, compared and represented. The resulting images often look unlike later cinema because their purpose was analytical rather than theatrical. A runner’s limbs might overlap across one plate; a bird’s wingbeat might appear as a succession of translucent positions. Yet these experiments established several problems that motion-picture technology would also have to solve: rapid exposure, reliable timing, regular image intervals and the transport of sensitive material through a camera. They made time a mechanical and photographic engineering problem.",
      "It is important not to turn Muybridge and Marey into prophets who were unknowingly trying to invent Hollywood. Their ambitions and contexts were different, and many other optical entertainments and photographic experiments also contributed to nineteenth-century cultures of moving and changing images. The historical connection is more precise: motion study created techniques, materials and ways of thinking that made sequential photography increasingly practical and culturally intelligible. By the 1880s, investigators could produce convincing sequences. What they still lacked was an economical way to store a much longer run of small images on material that could move rapidly, survive mechanical stress and pass repeatedly through cameras and viewing or projection machines. That problem leads from the photography of movement to the physical strip on which motion pictures would be industrialized.",
    ],
  },
  {
    id: "from-images-to-filmstrip-and-apparatus",
    title: "3. From single images to filmstrip and apparatus",
    sourceIds: [
      "nsm_celluloid_beginnings",
      "loc_edison_origins",
      "nsm_robert_paul",
    ],
    paragraphs: [
      "Glass was excellent for a photographic negative but awkward for a long moving-image sequence. It was heavy, rigid and fragile; a practical motion-picture camera needed many exposures in quick succession and therefore needed a support that could travel. Paper roll film offered one route, but transparent flexible celluloid changed the engineering problem much more decisively. The National Science and Media Museum dates Eastman’s transparent celluloid roll film entering the American market to the autumn of 1889. Experimenters including Marey and Dickson quickly investigated the material. Celluloid did not ‘invent cinema’ by itself, but it removed a severe practical limit: a long succession of images could now be carried on a strip that bent around rollers, advanced through a gate and could be copied for viewing or projection.",
      "Once images live on a strip, the machine has to control that strip with extraordinary regularity. Each frame must stop in the gate long enough to be exposed or projected, then move out of the way while the next frame arrives. If the strip simply slides continuously while the shutter is open, the image smears. Motion-picture apparatus therefore depends on intermittent movement coordinated with a shutter. Perforations can give sprockets a repeatable grip so that each image lands in the correct position. Frame size, perforation pattern, strip width, transport speed and shutter timing become interdependent design choices. The familiar rectangular film frame is not merely a window chosen by artists; it is also the result of a material system designed to move thousands of photographs with dependable spacing.",
      "Edison’s laboratory initially explored ideas that did not yet resemble the final Kinetoscope system, and surviving records caution against a heroic account in which one inventor sees the whole future at once. Dickson’s practical work was central. The laboratory tested film materials and transport mechanisms while drawing on Edison’s established business in mechanically reproduced sound and on the larger world of photographic experimentation. By the early 1890s, the Kinetograph camera and Kinetoscope viewer had established a workable system using perforated celluloid. This was a significant achievement because recording was no longer an isolated scientific demonstration. A production apparatus, a viewing apparatus and a potential commercial supply of short subjects could now be designed around one another.",
      "Standards emerge partly because successful systems create demand for compatible material. The strip associated with Edison and Dickson helped establish the dimensions that became the basis of 35 mm motion-picture film, but standardization was not instantaneous or universal. Other inventors used different widths, perforations and mechanisms. Competition mattered: incompatible systems could lock exhibitors or producers into particular suppliers, while copying and adaptation spread useful solutions across borders. Robert Paul’s British work is instructive. Because Edison had not secured a British Kinetoscope patent, Paul could manufacture duplicate machines. That commercial opening created another problem — where would the films come from? When Edison would not supply them, Paul and Birt Acres moved toward making their own. Apparatus, rights and content demand became entangled.",
      "This is the point at which it becomes useful to think of film as an infrastructure rather than an object. A strip of exposed celluloid is only one component. Cameras require unexposed stock and precision mechanisms; processed negatives require printing; viewing and projection require compatible positive prints; repeated use causes wear and damage; new subjects have to be made to keep machines attractive. Technical choices therefore create production obligations. The successful moving-image system is not the one that merely produces a striking demonstration once. It is the one that can support repetition: another recording, another copy, another machine, another customer. The pressure to repeat would push Edison’s operation toward a dedicated studio and would push other manufacturers toward their own production cultures.",
    ],
  },
  {
    id: "dickson-edison-kinetoscope-world-and-1895",
    title: "4. Dickson, Edison and the Kinetoscope world — and why 1895 is not one birthday",
    sourceIds: [
      "loc_edison_timeline",
      "loc_blacksmith_copyright",
      "loc_edison_early_productions",
      "nsm_robert_paul",
      "nsm_lumiere",
      "loc_projectors_vitascope",
    ],
    paragraphs: [
      "The Edison laboratory’s moving-picture work illustrates how an apparatus produces a production culture around itself. The Black Maria studio at West Orange was built in 1892–93 because Kinetoscope viewing would require a continuing supply of new subjects. Its dark exterior and opening roof were practical responses to the dependence of early photographic emulsions on strong light. The building could turn on a pivot so that its opening could follow the sun. Inside, the camera faced brief acts that could fit the machine and the available film: boxing, dancing, athletic displays, vaudeville routines, comic actions and celebrities. The studio was therefore not simply a room where an invention was tested. It was an early answer to a recurring media problem: once the hardware is in circulation, what will people watch next?",
      "*Blacksmith Scene* — identified in Library of Congress research as *The Blacksmith Shop* in the first U.S. motion-picture copyright registration — is an unusually useful anchor because it makes that production system visible. W. K. L. Dickson’s 1893 copyright correspondence included a strip of images showing three men around an anvil. The action is staged rather than a transparent record of industrial labour: the performers hammer, pause and drink for the camera. Its significance is therefore richer than the label ‘first’ suggests. Here is a moving-picture subject built to be legible within a brief fixed view, produced in a dedicated environment by workers solving photographic and mechanical constraints. It joins performance, studio design, copyright strategy and a viewing technology. For this chapter, that combination is more historically valuable than treating the film as a trophy in a race for priority.",
      "The Kinetoscope’s commercial form also reminds us that projected cinema was not an inevitable first business model. One person looked into the cabinet at a time, and parlours could earn money by installing multiple machines with different subjects. Edison had reason to defend a profitable individual-viewing system rather than immediately replace it with projection. Meanwhile, others saw the advantage of putting one moving image before a larger audience. In Britain, Paul’s experience manufacturing Kinetoscope copies and supplying films pushed him toward projection. In the United States, Woodville Latham and his associates demonstrated the Eidoloscope publicly in 1895, while C. Francis Jenkins and Thomas Armat developed the Phantoscope; Armat’s machine would later be marketed through Edison interests as the Vitascope. Projection emerged from competition, appropriation and business calculation, not from a single laboratory handoff.",
      "The Lumière Cinématographe became the most durable symbol of this transition because it offered an elegant portable system and because Lumière production and exhibition spread internationally. The device could serve camera, printing and projection functions, and its hand-operated portability encouraged filming outside a fixed studio. The Lumières demonstrated their films during 1895 and opened the famous Paris public programme at the Salon Indien of the Grand Café on 28 December. That date deserves attention: it helped establish projected moving photographs as a reproducible commercial attraction, and the Lumière network became extraordinarily influential. But calling it ‘the birthday of cinema’ flattens the year. Projection systems and demonstrations already existed; the criteria for ‘public’, ‘commercial’ and ‘cinematic’ vary; and the practices that made cinema sustainable continued to develop afterward.",
      "The better historical use of 1895 is as a convergence point. Several technical pathways had become viable enough to enter public commerce at roughly the same moment. Flexible film could be transported through cameras and projectors. Producers could make short subjects repeatedly. Viewers had already paid for Kinetoscope experiences. Projection could turn moving photographs into a group spectacle. Photographic firms, engineers, showmen and entrepreneurs now had reasons to copy, improve and distribute machines and films. Yet the medium still had no settled grammar, no single exhibition institution and no stable division of labour comparable to later studios. The next movement of this chapter therefore turns away from priority claims and toward use: what happened when portable cameras went into streets and stations, when performers confronted the lens, and when filmmakers discovered that recording movement could become the construction of impossible screen events?",
    ],
  },
];
