import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterEightMovementTwo: readonly FilmHistoryBookSection[] = [
  {
    id: "ch8_cross_art_lherbier",
    title: "6. L'Inhumaine turns modernist collaboration into an art-direction and production-management system",
    paragraphs: [
      "Marcel L'Herbier's L'Inhumaine is useful precisely because it makes the avant-garde's cross-art rhetoric materially visible. La Cinémathèque credits Cinégraphic and Films Armor as production companies, Marie-Laure de Noailles as producer, Georges Specht and Georges Maurice in photography, Darius Milhaud for original music and a design group that includes Claude Autant-Lara, Fernand Léger, Alberto Cavalcanti and Robert Mallet-Stevens, with Paul Poiret on costume. This is not simply a list of famous modernist names. A production had to coordinate several visual disciplines so that architecture, objects, costume, performance, photography and musical presentation could belong to one designed world while retaining distinct authorship.",
      "The film therefore complicates the convenient contrast between industrial cinema and artist cinema. It required financing, scheduling, construction, wardrobe, photography and distribution just as other features did, but it recruited artistic prestige and modernist design as part of its production identity. That makes L'Inhumaine a strong book comparison without demanding a new Production Case: its cross-disciplinary design problem overlaps the broader large-scale coordination already playable in Napoléon, while the chapter can use L'Herbier to show how producers and designers assembled a modern image through specialist collaboration. The important lesson is that modernism was organized labor as well as visual novelty.",
      "Cross-art collaboration also creates attribution problems that a director-centered history can obscure. A set associated with Léger or Mallet-Stevens, a Poiret costume or Milhaud's music can be folded into a phrase such as 'L'Herbier's style' until the production ecology disappears. The chapter instead names departments and collaborators and asks how their work was made compatible. That approach also makes later canon formation more legible: an avant-garde film may become famous because several art histories claim it at once—architecture, design, music, fashion and cinema—while the original production still depended on concrete contracts, materials and schedules rather than an abstract total artwork assembling itself.",
    ],
    sourceIds: ["ch8_inhumaine_cinematheque", "ch8_field_moma", "ch8_moma_avant_term"],
  },
  {
    id: "ch8_pure_cinema_ballet",
    title: "7. Cinéma pur and Ballet mécanique make rhythm, repetition and objects carry structure without a conventional plot",
    paragraphs: [
      "The phrase cinéma pur names an aspiration more than a single organization: strip cinema of inherited narrative obligations and explore movement, light, repetition, shape and duration as primary materials. MoMA's account of film experimentation places 1920s Paris among the environments where artists treated montage and assembled images as a means of breaking ordinary spatial and temporal continuity. Ballet mécanique is a particularly concrete example because MoMA describes ordinary kitchenware, machinery, faces and repeated actions transformed by camera and editing rhythms. The film's structure does not need a conventional protagonist to be organized; repetition and juxtaposition themselves create expectation, interruption and return.",
      "Authorship again resists simplification. BFI identifies Ballet mécanique as a collaboration between Fernand Léger and Dudley Murphy and discusses the project's relation to composer George Antheil, while MoMA credits Murphy's photographed material and Léger's mechanical preoccupations. The lesson is not that painters discovered a purer cinema than professional filmmakers. It is that film could become a shared experimental medium whose collaborators disagreed about ownership, score, financing and form. For production study, an abstract short still needs shot inventories, objects, performers, exposure, graphic relations and an editing plan; eliminating conventional plot does not eliminate logistics or intentional structure.",
      "This is why the chapter keeps Ballet mécanique as P2 book evidence rather than manufacturing a separate Production Case. Entr'acte already gives the player a short-form cross-art production with variable speed, visual tricks, rhythm and event exhibition, while Cœur fidèle demonstrates rhythmic editing tied to emotion. Ballet mécanique expands the conceptual range toward machine-body abstraction and repetition without requiring another nearly identical interaction loop. The book can therefore compare how the same basic cinematic resources—duration, repetition, close-up, angle, movement and cut—change function when narrative causality is deliberately weakened or suspended.",
    ],
    sourceIds: ["ch8_moma_avant_term", "ch8_ballet_moma", "ch8_ballet_bfi", "ch8_bfi_french_avant"],
  },
  {
    id: "ch8_man_ray_poetic_objects",
    title: "8. Man Ray makes artist-film production a problem of optical transformation, found objects and poetic collaboration",
    paragraphs: [
      "Man Ray's films broaden the chapter beyond feature directors by showing how photographic and Surrealist practices entered moving images through an artist's existing methods. MoMA's French avant-garde survey describes his films as determinedly non-narrative and poetic, and its collection record for Emak-Bakia places the work inside his wider experiments with camera-less and transformed photographic imagery. The important production shift is not that narrative disappears completely but that objects, textures, exposure and optical surprise can become organizing units. A filmmaker arriving from photography may therefore begin with material operations—what light does to a surface, what repetition does to an object—rather than with a dramatic scene.",
      "L'Étoile de mer shows that artist film could also be collaborative adaptation. La Cinémathèque credits Man Ray as director and Robert Desnos as screenwriter and source poet, with Studio-Films producing and distributing. Its preserved starfish object and archival account connect Desnos's poem, the recurring specimen in a jar and the film's intertitles and imagery, while emphasizing that Man Ray transformed the poem into a domain no longer wholly owned by either collaborator. That history is useful against two myths at once: Surrealist work is not simply automatic randomness, and adaptation is not only a feature-film problem. Poem, object, performer, optical distortion and title card must still be selected and related.",
      "The chapter treats Emak-Bakia and L'Étoile de mer as P2 comparisons because their strongest lessons are already distributed across existing Production Cases. Cœur fidèle teaches image transformation through rhythm, Entr'acte teaches artist-network collaboration and Un Chien Andalou teaches discontinuous Surrealist association. Man Ray nevertheless matters for understanding how a portable, short-form practice could circulate between photography, objects and film without needing a studio feature apparatus. His work helps define avant-garde production as a network of techniques and institutions rather than a minor genre inside the normal commercial slate.",
    ],
    sourceIds: ["ch8_field_moma", "ch8_emak_moma", "ch8_etoile_cinematheque", "ch8_etoile_object", "ch8_bfi_french_avant"],
  },
  {
    id: "ch8_entracte_event_cinema",
    title: "9. Entr'acte reveals that exhibition can be designed into a film before the camera rolls",
    paragraphs: [
      "Entr'acte is not merely a short later attached to an avant-garde program. Institutional records place it inside Francis Picabia's ballet Relâche for Rolf de Maré's Ballets Suédois, with René Clair directing and editing, Picabia supplying the scenario, Jimmy Berliet photographing and Erik Satie providing the original accompaniment. Centre Pompidou documents the Relâche presentation at the Théâtre des Champs-Élysées on 4 December 1924. That context changes the production brief: the film is an interval event whose duration, comic escalation, performers and musical relation answer to a theatrical evening. Exhibition is therefore an upstream design constraint rather than a downstream marketing decision.",
      "The film's famous tricks become more intelligible when treated as scheduled procedures. Fondation Jérôme Seydoux-Pathé documents frame-by-frame work and accelerated imagery, while BFI emphasizes multiple exposures, stop-motion, unusual viewpoints and rapid editing. Those choices require subjects and camera actions that can survive transformation: a disappearance needs matched staging, speed change needs suitable movement, a multiple exposure needs controlled visual layers, and a chase needs enough coverage for acceleration in the edit. Labeling the result 'Dada' explains little unless the production system shows how irreverence, timing and technical repeatability were actually coordinated.",
      "Entr'acte also demonstrates that a film can change identity after its original event. Fondation Pathé records that Clair removed material in 1967 while reshaping the work as a more autonomous film, and later restoration work recovered first-version material from surviving elements. Cinémathèque and other institutions consequently report differing modern presentation lengths. The chapter uses that history to make exhibition and version criticism inseparable: a film made for one ballet interval can later circulate as a canonical standalone short, but historians should not silently substitute the later autonomous object for the precise 1924 event that generated it.",
    ],
    sourceIds: ["ch8_entracte_cinematheque", "ch8_entracte_fondation", "ch8_entracte_pompidou", "ch8_bfi_1924"],
  },
  {
    id: "ch8_dreyer_boundary_anchor",
    title: "10. The Passion of Joan of Arc is a French-production boundary case that radicalizes close-up without becoming an Impressionist manifesto",
    paragraphs: [
      "Carl Theodor Dreyer's The Passion of Joan of Arc belongs in the chapter as a comparative anchor rather than evidence that every radical French-produced silent film was Impressionist or Surrealist. La Cinémathèque credits Société Générale de Films, cinematographer Rudolph Maté, designers including Hermann Warm and editors Marguerite Beaugé and Dreyer, while its account of the production emphasizes an unusually long shoot and extensive preparation from the trial records. The film was produced in France and emerged within the same late-silent environment as the avant-gardes, yet its method should remain Dreyer's specific solution to a historical-religious subject rather than be absorbed into someone else's movement label.",
      "Its close-ups make that distinction especially clear. Cinémathèque commentary and retrospective writing emphasize isolated faces, extreme angles and a rigorously constructed editing system; BFI likewise stresses the searing intimacy of Falconetti's face and the film's radical visual contrasts. The production problem is not simply 'use more close-ups.' Sparse architecture, shaved or minimally disguised faces, eyeline disruption, framing that severs heads from conventional spatial context and performance built for intense proximity must be coordinated. The existing Production Case therefore broadens Chapter 8's playable vocabulary while preserving a different genealogy from Epstein's photogénie or Buñuel's Surrealism.",
      "The film also carries a strong preservation warning. BFI's historical account notes destruction and fragmentary survival before the recovery of a more complete version, while modern screenings vary in runtime and accompaniment. Cinémathèque records multiple contemporary presentation lengths rather than one stable number. That instability echoes the chapter's broader archival theme: radical silent form reaches us through prints, restorations, scores and institutional choices that can alter duration and texture. A canonical film is not made historically safer by fame; the more familiar the title, the more important it becomes to distinguish production evidence from later presentation convention.",
    ],
    sourceIds: ["ch8_passion_cinematheque", "ch8_dreyer_writings", "ch8_passion_bfi_catholic", "ch8_dreyer_retrospective"],
  },
];
