import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterSevenMovementOne: readonly FilmHistoryBookSection[] = [
  {
    id: "ch7_plural_weimar_field",
    title: "1. Weimar cinema was a field of competing modernisms, not a synonym for Expressionism",
    paragraphs: [
      "The most persistent shortcut in histories of German cinema is to let a small group of extraordinary Expressionist films stand in for the whole Weimar period. That shortcut is useful for recognition and disastrous for explanation. Between the end of the First World War and the transition to sound, German production included studio fantasies, horror, chamber dramas, crime serials, comedies, street films, social melodramas, mountain films, animation, advertising experiments and abstract avant-garde work. Deutsche Kinemathek and MoMA both frame the period as a broad culture of cinematic modernity whose subjects included urbanization, mobility, fashion, gender, psychology and social inequality. Expressionism belongs inside that field as one influential tendency, not as a universal national style stamped onto every German film from 1919 to 1929.",
      "That distinction changes the production questions we ask. Caligari makes painted architecture and graphic distortion carry a large share of its meaning; Nosferatu takes uncanny effects into real landscapes and historic streets; The Last Laugh organizes social humiliation through hotel architecture, costume and mobile camera; Metropolis expands design and effects to industrial scale; Pandora's Box builds tension through performance, social proximity and shifting economic dependence. Treating these works as five examples of one style would erase the very differences that make the period historically valuable. The chapter therefore follows techniques across organizations and genres while repeatedly asking what kind of production system each film needed, which crafts were central, and which other practices existed at the same time.",
      "This plural approach also protects against a teleological story in which Weimar cinema exists mainly to predict Nazism or to donate shadows to later film noir. Those afterlives matter, but they are not the period's only meaning. MoMA's Weimar retrospective explicitly widened the canon beyond madmen and nightmare imagery to include popular cinema and social drama, while filmportal emphasizes the coexistence of art films and popular genres. Chapter 7 therefore studies the films as products of their own institutions, markets, artistic debates and legal constraints before tracing later influence. The aim is not to deny political history, but to prevent hindsight from turning a heterogeneous republic's cinema into a single ominous prelude.",
    ],
    sourceIds: ["ch7_weimar_filmportal", "ch7_weimar_kinemathek", "ch7_weimar_moma", "ch7_weimar_bfi_genres"],
  },
  {
    id: "ch7_postwar_companies_ufa_decla",
    title: "2. Postwar consolidation made companies, studios and distribution part of film style",
    paragraphs: [
      "Weimar cinema emerged from an industrial reorganization that had begun during the war. UFA was founded in 1917 with state and industrial support, then survived the fall of the empire and developed into a vertically structured concern joining production facilities, distribution and cinemas. Deutsche Kinemathek's institutional history stresses both the capital behind the company and its acquisition of the Babelsberg studio site in 1922. At the same time, firms such as Decla and Decla-Bioscop supplied personnel, production cultures and films that would later be absorbed into larger structures. Caligari's Decla context and Erich Pommer's later UFA leadership therefore belong to one changing industrial landscape rather than two sealed aesthetic eras.",
      "Company scale mattered because ambitious form required organization. Large sets had to be designed, built, lit and photographed; costumes and crowds had to be coordinated; long features needed predictable schedules and routes to exhibition. UFA's prestige strategy under Pommer used expensive productions to compete internationally, and filmportal's account of the period links Die Nibelungen, The Last Laugh and Varieté to this effort. Yet the same strategy could create severe financial exposure. Metropolis became an emblem of the contradiction: a technically immense prestige production whose cost intensified UFA's economic problems. Industrial history therefore explains both the material possibility of famous images and the pressures that could reshape companies around them.",
      "The chapter keeps corporate infrastructure separate from film-level authorship. UFA did not possess one stable visual style, and Decla did not manufacture Caligari's design automatically. Companies assembled producers, writers, directors, cinematographers, designers, performers, laboratories and distributors under changing financial conditions. A useful production history tracks how these resources became available without turning the company logo into a creative person. It also recognizes that smaller firms such as Prana-Film could produce internationally consequential work outside UFA. The question is not which studio 'invented' Weimar cinema, but how consolidation, specialization and access to facilities enabled several distinct aesthetic programs to coexist and compete.",
    ],
    sourceIds: ["ch7_ufa_kinemathek", "ch7_ufa_filmportal", "ch7_weimar_classical_avant", "ch7_caligari_filmportal"],
  },
  {
    id: "ch7_caligari_designed_image",
    title: "3. Caligari made design, performance and framing operate as one distorted system",
    paragraphs: [
      "The Cabinet of Dr. Caligari is the chapter's clearest Expressionist design anchor because its distortion is constructed rather than merely discovered by the camera. filmportal records the Decla production at the Lixie studio in Berlin-Weissensee and credits Robert Wiene, writers Carl Mayer and Hans Janowitz and cinematographer Willy Hameister; the surviving production history also centers the graphic environments associated with Hermann Warm, Walter Reimann and Walter Röhrig. Streets bend, walls refuse ordinary perspective, painted shadows detach illumination from physical lamps, and lettering participates in the same angular world. The image becomes an organized graphic field in which architecture does not neutrally contain the action but continuously tells us how unstable that action is.",
      "Performance has to be read inside that field. Werner Krauss and Conrad Veidt do not simply act 'more theatrically' than later screen performers; their posture, gait and gesture are calibrated to surfaces that already reject everyday bodily logic. BFI's account of the film emphasizes the fusion of actors and geometric design, which is why the Production Case cannot be reduced to a set-decoration exercise. Framing, costume, makeup and movement all need to maintain the graphic relation. If the player reproduced crooked flats but staged bodies naturalistically and photographed them as ordinary rooms, the historical production logic would disappear even though the decor looked superficially correct.",
      "Caligari also demonstrates why version history belongs inside formal analysis. filmportal distinguishes the six-act tinted silent original from later inspection, television and restored digital versions, while the Murnau Foundation documents a restoration built from the surviving camera negative and contemporary distribution prints. Modern screenings may include newly commissioned music and reconstructed tinting, but those presentation layers cannot be projected backward as synchronized production elements from 1920. The chapter therefore treats the film's famous look as both an authored production system and a materially transmitted object whose color, titles, length and accompaniment have histories of their own.",
    ],
    sourceIds: ["ch7_caligari_filmportal", "ch7_caligari_bfi", "ch7_caligari_murnau", "ch7_weimar_kinemathek"],
  },
  {
    id: "ch7_nosferatu_location_rights",
    title: "4. Nosferatu moved the uncanny into real geography—and exposed production to legal risk",
    paragraphs: [
      "Nosferatu is essential precisely because it prevents Expressionism from becoming a recipe of painted studio distortion. filmportal records a Prana-Film production photographed by Fritz Arno Wagner and designed by producer Albin Grau across Wismar, Lübeck, Lauenburg, Rostock, Helgoland and locations in the Carpathian region. BFI likewise stresses that Murnau departed from Caligari-like artificiality by letting forests, mountains, historic architecture and open sea become sources of dread. The production problem is therefore one of selection and transformation: real places remain materially recognizable while framing, negative effects, performance, rhythm and graphic design make them participate in an unreal threat.",
      "The film also demonstrates that adaptation is an industrial and legal act, not merely a screenplay choice. Henrik Galeen's scenario transforms Bram Stoker's Dracula by changing names, locations and narrative details, but those changes did not secure authorization. The Murnau Foundation and BFI both document Florence Stoker's successful legal action against Prana-Film, which contributed to the company's collapse and generated orders aimed at destroying the film. That history belongs directly in a production curriculum because rights clearance affects whether a work can be distributed, preserved and monetized. Creative transformation does not erase underlying intellectual-property obligations simply because the result becomes artistically distinct.",
      "Nosferatu's survival further complicates the idea of a stable original. The 1922 film was silent and distributed through regional companies; later copies and restorations differ in length, color treatment and music. The fact that prints escaped destruction is part of why the work can be reconstructed at all. A historically responsible case therefore separates 1921 location photography and 1922 exhibition from later preservation decisions. It also avoids turning the lawsuit into romantic proof that infringement is harmless: the episode shows both the cultural value of survival and the real vulnerability created when a production proceeds without adequate adaptation rights.",
    ],
    sourceIds: ["ch7_nosferatu_filmportal", "ch7_nosferatu_bfi", "ch7_nosferatu_murnau", "ch7_weimar_filmportal"],
  },
  {
    id: "ch7_expressionism_limits_shadows",
    title: "5. Expressionist lighting and psychological space travelled beyond Caligari without becoming one fixed style",
    paragraphs: [
      "Expressionist cinema is most useful as a family of production strategies rather than a checklist. Shadow, silhouette, exaggerated geometry, stylized bodies and unstable space can be combined in very different proportions. Arthur Robison's Warning Shadows is a valuable comparison because it turns projected silhouettes and a chamber interior into the mechanism of jealousy and imagined violence. filmportal records Fritz Arno Wagner's cinematography, Albin Grau's sets and a production presented without intertitles in its original form. The same techniques that Caligari fixes into painted architecture are here mobilized through actual projection, movement and changing relations among bodies, walls and a performer manipulating light.",
      "The comparison reveals why formal labels should not substitute for production analysis. A shadow can be painted into scenery, cast by a lamp, created by an object between source and wall, produced through an optical process or reconstructed in restoration. Each method creates different demands for blocking, exposure, continuity and repeatability. Robison's film and contemporary accounts emphasize shadow as an active dramatic agent, but the chapter does not claim that one production invented expressive shadow or psychological lighting. Instead, it asks how designers and cinematographers made visible effects dependable enough to carry narrative information in a silent feature.",
      "By the middle of the decade, the most celebrated German films were already mixing tendencies that critics often separate after the fact. BFI notes that Expressionism quickly blended with other styles, while filmportal's Weimar overview places chamber drama, social realism, popular genre and avant-garde work beside it. The correct historical conclusion is therefore not that Expressionism ended on a single date. Its tools migrated, diluted, intensified or were rejected according to different projects. That is why Warning Shadows remains a P2 comparison rather than another Production Case: it broadens the book's account of psychological space without adding a sufficiently distinct gameplay problem beyond Caligari, Nosferatu and the later mobile-camera cases.",
    ],
    sourceIds: ["ch7_warning_shadows_filmportal", "ch7_robison_filmportal", "ch7_bfi_expressionist", "ch7_weimar_moma"],
  },
];
