import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterThreeMovementOne: readonly FilmHistoryBookSection[] = [
  {
    id: "ch3_views_stories_coexist",
    title: "1. Stories did not simply replace views",
    sourceIds: ["ch3_bfi_inventing_language", "ch3_loc_fictional_films", "ch3_cannes_trip_moon"],
    paragraphs: [
      "The move from short views to sustained stories was not a clean replacement in which an immature cinema suddenly discovered its proper form. Around 1900, actuality, trick film, staged comedy, reconstruction, crime drama, chase film and spectacle coexisted in the same production and exhibition culture. Producers could learn new ways to connect shots while still treating transformation, direct address, theatrical composition and visual novelty as valuable attractions. This matters because a teleological history makes every early film look like a failed version of later continuity cinema. A better account asks what problem a film is solving on its own terms: how to make a look readable, how to connect two spaces, how to organize a route, how to represent an event already past, or how to sustain suspense among simultaneous actions.",
      "The period also resists a single-inventor story. The British Film Institute's archive groups early experiments in close views, editing, continuity and effects as a field of invention rather than a sequence owned by one filmmaker. Edison-company history similarly shows fiction becoming increasingly prominent within a changing commercial catalogue rather than emerging in one decisive title. Georges Méliès, G. A. Smith, James Williamson, Edwin S. Porter, Cecil Hepworth and Ferdinand Zecca worked in different industrial and national settings, and their films solved different formal and production problems. Their experiments overlapped, circulated and were sometimes copied, remade or reconstructed. Narrative form therefore developed through a network of practices rather than through a relay race in which each canonical film invented one modern rule.",
      "Chapter 3 follows those practices rather than searching for a birthday of narrative cinema. Its first movement begins with viewpoint and constructed screen space: how a film can make one image depend on another. The second turns to causality, routes, version history and represented time. The third examines sustained parallel action and the increasingly systematic integration of multiple spaces into one narrative event. Across all three movements, the historical object is not an abstract rule called editing. It is a set of production decisions recorded in films, catalogues, paper prints, surviving copies and later reconstructions. The aim is to understand how storytelling became more organized without pretending that attraction, tableau staging or theatricality had to disappear for cinema to become narratively sophisticated."
    ]
  },
  {
    id: "ch3_melies_tableau_story",
    title: "2. Méliès and the logic of the tableau",
    sourceIds: ["ch3_cannes_trip_moon", "ch3_cannes_trip_restoration", "ch3_loc_melies_methods"],
    paragraphs: [
      "A Trip to the Moon demonstrates why tableau staging cannot be treated as a primitive obstacle on the road to continuity. Méliès organizes an extended fantasy through successive scenic units: the astronomers' meeting, launch, lunar arrival, encounter with the Selenites, escape and return. Each tableau is designed as a complete theatrical space in which bodies, painted scenery, machinery and transformations can be read at once. The camera does not need to fragment every action into modern coverage because the production design itself structures attention. Narrative accumulation comes from the ordered succession of spectacular situations. The result is simultaneously story and attraction: the plot gives the transformations a sequence, while the transformations make the plot worth following.",
      "This production system was materially specific. Méliès built fantasy through studio architecture, painted flats, stage machinery, substitution effects, multiple exposure and other camera-based transformations. Library of Congress material on Méliès's working methods documents a glass studio and repeatable trick techniques rather than a mysterious one-off discovery. The surviving colour version also reminds us that the object known today as A Trip to the Moon has a preservation and restoration history. Cannes documentation describes image-by-image reconstruction of fragmented colour material and a later soundtrack for restored presentation. The film seen today is therefore both an early production and an archival achievement; restoration must not be silently mistaken for original synchronized sound or an untouched surviving print.",
      "For narrative history, the important lesson is that connected storytelling can be built by staging and succession as well as by analytical cutting. Méliès's tableaux preserve frontality and theatrical address while sustaining a longer causal journey. Later filmmakers would increasingly divide spaces and actions across shots, but that development did not invalidate the tableau. It added new tools to a repertoire that remained heterogeneous. Treating A Trip to the Moon as a successful production system rather than a failed proto-feature gives the chapter a necessary baseline: narrative integration is not synonymous with invisible continuity editing, and cinema's early formal diversity is not merely noise before a classical norm."
    ]
  },
  {
    id: "ch3_grandmas_reading_glass_viewpoint",
    title: "3. A look can organize a cut",
    sourceIds: ["ch3_bfi_grandma", "ch3_sase_grandma", "ch3_unibo_grandma", "ch3_bfi_inventing_language"],
    paragraphs: [
      "Grandma's Reading Glass poses a different problem from Méliès. G. A. Smith begins from a stable domestic view and makes the boy's act of looking motivate a series of enlarged inserts: newspaper, watch mechanism, canary, grandmother's eye and kitten. The circular mask does not simply offer a closer object for novelty. It tells the spectator why the scale and framing have changed. The boy looks through the magnifying glass; the film answers with an enlarged view; the base scene returns. The relation among shots therefore carries information that no isolated image contains on its own. A cut becomes legible because the preceding action has prepared a reason for it.",
      "The archival record is unusually useful because the object sequence appears in Screen Archive South East's description and in period catalogue material preserved through later documentation. BFI places the film inside a wider field of experiments with film language, and modern scholarship by Elena Dagrada cautions against treating such represented gaze inserts as identical to the later standardized subjective point-of-view system. That distinction matters. The film is a strong early example of analytical shot relation and represented looking, but calling it simply 'the first POV shot' would replace analysis with a trophy claim and flatten the international experimentation around close views, inserts and subjective framing.",
      "The production lesson is therefore not 'invent the close-up.' It is to coordinate performance, prop, mask, camera scale and edit so the spectator understands that one view belongs conceptually to another. The circular inserts also show that an early film could alter scale radically without constructing a fully continuous three-dimensional space in the later classical sense. The relation is analytical: the larger view gives detail and viewpoint information. That modest but powerful mechanism becomes one of the chapter's recurring themes. Narrative cinema grows partly by teaching spectators how to infer relations across discontinuities—between a person and an object, one room and another, one route and its destination, present action and remembered past."
    ]
  },
  {
    id: "ch3_fire_connected_space",
    title: "4. Rescue across linked tableaux",
    sourceIds: ["ch3_bfi_fire", "ch3_sase_fire", "ch3_eastman_narrative"],
    paragraphs: [
      "James Williamson's Fire! shifts the problem from a look to an event distributed across several places. Its rescue unfolds through a sequence of tableaux: alarm, mobilization, journey and the burning-room action. BFI's account emphasizes chronological multi-shot construction, while regional archival documentation ties the production to recognizable Hove locations and staged fire-service action. The spectator must carry the emergency across cuts. A policeman's alarm belongs to the fire station that follows; the mobilized brigade belongs to the journey; the journey belongs to the burning building. The film does not need a modern continuity system to make those links intelligible because causal action supplies a strong bridge.",
      "This is also a production problem. Horses, fire-service equipment, locations, performers, smoke and rescue staging have to be coordinated so that the separate tableaux feel like stages of one response rather than unrelated attractions. Matching movement and clear entrances/exits help the viewer preserve direction and purpose. The George Eastman Museum places Fire! in a programme devoted to the development of narrative across multiple scenes and sets, which is a more useful description than claiming Williamson invented continuity. The film demonstrates a historically important solution, but that solution belongs to a broader environment of British and international experiments in linking action.",
      "The distinction between causal connection and later invisible continuity is crucial. Fire! can make the viewer understand 'this happens next because of that' without obeying every convention that would later regulate eyelines, screen direction, analytical coverage or temporal overlap. Early narrative was often robust precisely because a production supplied conspicuous actions—alarms, departures, arrivals, rescues—that made relations legible. The film therefore teaches how editing, staging and production logistics begin to work as one system: the camera records several separate pieces, but the spectator reconstructs a single emergency from their order."
    ]
  },
  {
    id: "ch3_attack_provenance_representation",
    title: "5. Before interpreting form, identify the object",
    sourceIds: ["ch3_bfi_attack", "ch3_sase_attack", "ch3_dulac_attack", "ch3_oxford_attack", "ch3_cambridge_boxer"],
    paragraphs: [
      "Attack on a China Mission – Bluejackets to the Rescue introduces a methodological problem that should govern the rest of the chapter: before we describe what an early film's editing proves, we have to know which version we are describing. BFI and Screen Archive South East document James Williamson's 1900 staged fiction about an attack on a Christian mission and British naval rescue. Yet Nicolas Dulac and André Gaudreault show that surviving copies, catalogue descriptions and a later reconstructed multi-shot version do not collapse neatly into one uncontested original structure. A reconstruction can make early material appear more classically organized than the evidence warrants. Formal history therefore depends on provenance.",
      "The film also demonstrates why style cannot be isolated from representation. It fictionalizes contemporary Boxer-Rebellion news through a British imperial rescue scenario and racist characterization of Chinese Boxer figures. BFI explicitly warns about that characterization, while Oxford and Cambridge scholarship situates such narratives inside a wider British culture of imperial siege, Yellow-Peril rhetoric and rapid fictionalization of the Boxer conflict. The formal question—how views are connected, whether a reverse view belongs to an original sequence, how rescue action is ordered—cannot be separated from the ideological work performed by the scene. The production constructs an imagined China in Britain and makes naval intervention the organizing resolution.",
      "For Chapter 3, Attack is valuable precisely because it prevents a triumphalist history of editing. If we treat a later reconstruction as transparent evidence, we can manufacture an invention story. If we celebrate only scene linkage, we can erase the politics of the story being linked. A rigorous film history therefore asks three questions together: what material survives, what formal relation can that material actually support, and what historical world does the production invite the spectator to inhabit? That combination of archive discipline, formal analysis and representation is the standard the chapter carries forward into American version problems, Pathé's represented memory and Griffith-era parallel action."
    ]
  }
];
