import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterFiveMovementOne: readonly FilmHistoryBookSection[] = [
  {
    id: "ch5_prewar_map",
    title: "A map made of routes, not sealed national boxes",
    paragraphs: [
      "Between 1907 and 1914 the phrase national cinema described only one layer of a much more entangled system. Production companies were based in particular cities and worked under particular laws, labour markets and cultural traditions, yet their films were designed to move. Prints crossed borders, intertitles were translated or replaced, performers became recognizable abroad, and distributors assembled catalogues for territories far from the studio. France, Italy, Denmark and the United States were major centres, but their importance came partly from the routes connecting them to exhibitors and audiences elsewhere. A useful map therefore shows flows of capital, prints, stars and genres rather than colouring each country as a self-contained cinema.",
      "This transnational view also corrects a misleading chronology in which one country supposedly hands leadership to another in a clean sequence. Pathé and Gaumont could remain internationally important while Danish melodramas travelled widely, Italian companies expanded feature spectacle and American firms reorganized production and distribution. Imported prestige films could stimulate American feature booking at the same moment that American independents were building their own long-form products. Competition did not require isolation: companies copied successful subjects, hired across borders, purchased rights, borrowed business practices and learned from what foreign films proved audiences would accept.",
      "Chapter 5 therefore uses the Atlas as a comparative laboratory rather than a hall of national masterpieces. The six existing Production Cases represent distinct production problems—prestige import, independent urban feature, recurring crime identity, large-scale epic, performance-led melodrama and export-versioned literary feature. The seven P2 titles remain book evidence because they broaden the map without creating redundant gameplay. That distinction is historical as well as editorial: international cinema was an ecosystem of overlapping solutions, and a responsible production history must resist turning every surviving landmark into a separate claim of invention.",
    ],
    sourceIds: ["ch5_ucpress_transformation", "ch5_columbia_early", "ch5_rutgers_silent", "ch5_dfi_history_1910_1920"],
  },
  {
    id: "ch5_company_routes",
    title: "Companies became international infrastructures",
    paragraphs: [
      "A production company became internationally powerful when it could do more than make films. It needed regular output, recognizable labels, agents or partners, distribution agreements, information about local demand and practical ways to move prints through customs, transport networks and exhibition circuits. Pathé Frères and Gaumont exemplify this broader company problem in France: production sat inside enterprises that also depended on equipment, catalogues, distribution and brand recognition. The historical importance of these firms lies not in a claim that they achieved perfect vertical control everywhere, but in the scale at which they could coordinate recurring products and make a French company name meaningful to distant buyers.",
      "The same logic helps explain why recurring characters and genres mattered. A distributor did not have to educate a market from zero every time a new title arrived if a company could promise another crime episode, another recognizable star or another prestige adaptation. Fantômas belongs to this system. Gaumont's cycle repeatedly returned to the criminal identity created by Pierre Souvestre and Marcel Allain, with René Navarre, Juve and Fandor giving audiences a memory structure that extended across films. The case is valuable because recurrence becomes an industrial resource: disguise, pursuit and recognition can be planned so that prior viewing increases value without requiring every spectator to possess exactly the same copy or exhibition history.",
      "Calling this infrastructure a serial system requires care. Fantômas was a five-film cycle, and institutional catalogues identify the sequence, but later chapter-serial conventions should not be projected backward as if Feuillade had already standardized every practice associated with 1910s American serials. The stronger claim is that company organization could sustain recurring fictional worlds across separate releases and sell that recurrence internationally. Chapter 5 keeps Gaumont production infrastructure as a historical object and Fantômas as the playable case: one explains the machinery, while the other lets the producer solve a concrete problem of identity, continuity and repeatable genre expectation.",
    ],
    sourceIds: ["ch5_gaumont_fantomas", "ch5_cinematheque_fantomas", "ch5_bnf_juve", "ch5_bnf_mort", "ch5_ucpress_transformation"],
  },
  {
    id: "ch5_rights_intertitles_versions",
    title: "Territories, intertitles and version control",
    paragraphs: [
      "International circulation transformed a finished negative into a family of market objects. Territorial rights could be sold to different distributors; title cards could be translated or replaced; censorship could remove scenes; projection speeds and accompaniment varied; and worn or incomplete prints could acquire local histories. A film known by one title in Paris might be advertised under another title abroad, while the same underlying production could survive in archival copies of different length. For the historian, these differences are not noise around an ideal master. They are evidence of the labour required to make cinema travel before standardized global release packages existed.",
      "Atlantis makes the issue unusually concrete because Det Danske Filminstitut documents two endings, including an unhappy ending produced for the Russian market. That fact changes the production question. Export strategy is not merely a sales decision made after photography; it can reach back into scripting, staging, photography and assembly when a company prepares materially different versions for distinct audiences. The Atlas case therefore asks the producer to track version intent explicitly rather than treating alternate endings as accidental corruption. At the same time, the surviving 114-minute presentation and its modern music are kept separate from the verified 1913 production record.",
      "The same discipline applies across the chapter. Queen Elizabeth survives in institutional records with differing modern running times and cataloguing traditions; Cabiria exists through reconstructed 1914 material and a substantially altered 1931 sound reissue; Afgrunden's preserved material includes elements recovered through censorship holdings. International film history becomes more accurate when provenance is part of the argument. Translation, censorship, restoration and market variation should therefore be visible in the book's language, because a transnational cinema did not circulate as identical data. It circulated as vulnerable, adaptable physical prints supported by contracts, catalogues, local exhibitors and later archives.",
    ],
    sourceIds: ["ch5_dfi_atlantis", "ch5_stumfilm_atlantis", "ch5_museo_cabiria_record", "ch5_museo_cabiria_restoration", "ch5_stumfilm_afgrunden", "ch5_moma_queen"],
  },
  {
    id: "ch5_stars_cross_borders",
    title: "Stars became portable production value",
    paragraphs: [
      "The star system did not emerge only when Hollywood later formalized long-term contracts and publicity departments. Before the First World War, recognizable performers were already becoming assets that could reduce uncertainty for producers, distributors and exhibitors. A famous stage performer could lend cultural prestige to a multi-reel film, while a screen performer could develop a persona through repeated cinematic appearances. The crucial international change was portability: a face, name or performance style could travel across language borders even when intertitles changed, giving marketing a human constant inside an otherwise variable release object.",
      "Sarah Bernhardt and Asta Nielsen reveal two different routes. Queen Elizabeth mobilized Bernhardt's established theatrical celebrity, prestigious costume and literary-historical association, then acquired additional commercial force when Adolph Zukor secured United States rights. Afgrunden worked in the opposite direction: Nielsen's screen performance was itself the breakthrough, and the film helped make her a transnational screen identity. Neither route should be reduced to a single origin story for stardom. One converts existing theatrical fame into feature legitimacy; the other demonstrates how the close observation of bodily and facial performance could generate a new exportable screen persona.",
      "Star value also changed production priorities. Framing had to preserve the performance that was being sold; costume and publicity had to make identity legible; narratives could be organized around entrance, recognition, transformation and emotional display. This is why Afgrunden's rope dance is more than a notorious episode and why Queen Elizabeth's costumes are more than decoration. Both are designed visibility. Chapter 5 treats transnational star circulation as an industrial system, while the individual Production Cases keep the craft decisions specific: Nielsen's restrained screen acting and Bernhardt's prestige presentation are historically different ways of making a performer carry value across markets.",
    ],
    sourceIds: ["ch5_dfi_afgrunden", "ch5_bfi_asta", "ch5_dfi_history_1910_1919", "ch5_fondation_queen", "ch5_bfi_queen", "ch5_nypl_queen"],
  },
  {
    id: "ch5_prestige_and_popular_genre",
    title: "Prestige culture and popular genre were not opposites",
    paragraphs: [
      "Prewar international cinema expanded by selling several kinds of legitimacy at once. Film d'Art productions drew on respected theatre, literature, historical subjects and established performers, while crime cycles, erotic melodramas, trafficking stories and spectacular epics offered sensation, suspense and recognizable genre promises. It is tempting to narrate prestige as cinema's ascent out of popular entertainment, but the market did not divide so neatly. The same companies and exhibitors could use cultural status and sensational appeal together, and a long film often needed both distinction and immediate attraction to justify higher prices, special booking or extended attention.",
      "L'Assassinat du duc de Guise remains a useful P2 reference because it makes the prestige strategy visible without requiring another playable case. Queen Elizabeth develops the same problem more distinctly through Bernhardt's international celebrity and American rights exploitation. Fantômas demonstrates the popular-literary route: mass-market novels, crime, disguise and recurring characters could be organized by a major company into a sustained screen property. The chapter therefore compares prestige and genre as parallel methods of reducing market risk. Each tells an exhibitor and audience what kind of value a film promises before the projector starts.",
      "This comparison also guards against a canon built only from later artistic reputation. Films survived unevenly, and institutions preserved some prestige objects more completely than disposable genre production. A history of internationalization must therefore read catalogues, company records, censorship evidence and surviving fragments alongside celebrated films. The Atlas does not equate survival with historical importance. It uses verified cases where the production problem is distinct and keeps other titles as evidence in the prose, allowing the chapter to explain a commercial field in which literary adaptation, celebrity, crime, erotic melodrama and spectacle all competed for transnational attention.",
    ],
    sourceIds: ["ch5_fondation_duke", "ch5_fondation_queen", "ch5_gaumont_fantomas", "ch5_cinematheque_fantomas", "ch5_columbia_early"],
  },
];
