import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterNineMovementTwo: readonly FilmHistoryBookSection[] = [
  {
    id: "ch9_pudovkin_mother_linkage",
    title: "6. Pudovkin's Mother builds revolutionary causality through linkage, performance and adaptation rather than collision alone",
    paragraphs: [
      "Mother is essential because it makes the difference between montage theories playable. Library of Congress records identify the 1926 Mezhrabpom-Rus production, Nathan Zarkhi's adaptation of Maxim Gorky's novel, Anatoli Golovnya's photography, Sergei Kozlovsky's design and a cast led by Vera Baranovskaya and Nikolai Batalov. BFI distinguishes Pudovkin's method from Eisenstein's by emphasizing linkage: shots accumulate around characters, actions and objects so that emotional and political meaning grows through connection. Harvard's account similarly stresses Pudovkin's attention to acting and the way montage can shape performance rather than replace it.",
      "That difference changes production planning. A Pudovkin sequence needs usable fragments of a performer's action, reaction and environment that can be linked into a clear psychological and causal chain. The celebrated thaw and procession material in Mother is not simply a collection of symbolic inserts; it works because physical details, movement, faces and social action are organized toward an emotional and revolutionary trajectory. The Production Case therefore asks the player to design coverage around performance nuance, object recurrence and escalating relation. It explicitly rejects the idea that character-centered montage is aesthetically conservative or that collision is the only genuinely Soviet form.",
      "The End of St. Petersburg and Storm over Asia broaden Pudovkin's practice without requiring redundant Production Cases. The former scales an individual's transformation into an anniversary history of war and revolution; the latter moves into a colonial-border narrative whose politics and ethnographic framing require additional scrutiny. BFI's discussion of Pudovkin's later influence on Italian filmmakers also helps place linkage beyond its original Soviet context. Mother remains the anchor because it most cleanly joins adaptation, acting, feature production and montage theory, while the trilogy demonstrates that one theoretical label cannot exhaust a filmmaker's changing work.",
    ],
    sourceIds: ["ch9_mother_loc", "ch9_mother_bfi", "ch9_mother_harvard", "ch9_pudovkin_roots_bfi", "ch9_pudovkin_bluray_bfi"],
  },
  {
    id: "ch9_october_intellectual_recut",
    title: "7. October turns intellectual montage and anniversary spectacle into a problem of state commission, reconstruction and political recutting",
    paragraphs: [
      "October was not made as spontaneous footage of 1917. MoMA identifies the project as a tenth-anniversary commission by Sergei Eisenstein and Grigori Aleksandrov, and BFI describes its elaborate re-creation of revolutionary events through symbolic and intellectual montage. The Winter Palace sequence draws on earlier public reconstruction, written accounts and staged crowds, while objects and gestures are repeatedly cut into conceptual chains. The film therefore teaches intellectual montage as the construction of an argument from selected materials, not as a guarantee that any two symbolic images will produce one fixed idea.",
      "Political intervention is part of the production history. BFI records that references to Leon Trotsky were removed as official history changed, so the surviving film reflects both an original commission and later political recutting. That distinction is permanent in the chapter: the game may ask a player to recognize that institutions can demand alterations, but it never rewards falsifying archives or pretending that a censored version erases evidence of what was previously planned or shot. A production history should record who requested the change, when it happened and how it affected the work rather than converting censorship into invisible continuity.",
      "October also demonstrates why state sponsorship does not mechanically determine form. Its anniversary purpose is explicit, yet contemporary officials and audiences could reject the very formalism used to serve that purpose. The film's symbolic density and nonprofessional casting made revolutionary history strange rather than straightforward, and later versions vary in runtime and assembly. It is therefore a different Production Case from Potemkin: Potemkin anchors mass-action collision around 1905, whereas October makes official commemoration, intellectual montage and politically unstable historical representation the central production problem.",
    ],
    sourceIds: ["ch9_october_moma_event", "ch9_october_moma_collection", "ch9_october_bfi_epics", "ch9_field_bfi", "ch9_eisenstein_begin_bfi"],
  },
  {
    id: "ch9_vertov_kinopravda_collective",
    title: "8. Kino-Pravda made nonfiction editing, mobile observation and collective labour into a laboratory for kino-eye",
    paragraphs: [
      "Vertov's theories become most intelligible when read beside the surviving Kino-Pravda issues rather than as slogans detached from work. The Austrian Film Museum's online edition documents twenty-two surviving issues from a series of twenty-three made between 1922 and 1925, with changing crews, institutions and subjects. Yuri Tsivian's commentary shows Vertov assembling famine, industry, transport, political ceremony and everyday movement into screen statements. The newsreels do not simply capture untouched reality: framing, selection, intertitles and montage organize factual material into arguments, and that constructive process is visible from the earliest issues.",
      "The archive also makes collaboration impossible to ignore. Mikhail Kaufman appears repeatedly as cameraman; Elizaveta Svilova is credited as editor and is shown at the editing table; other camera operators and title designers contribute to individual issues. Kino-Pravda No. 19 explicitly shows Svilova selecting negatives, while No. 18 turns camera movement across cities and transport into a practical exploration of intervals. Collective documentary labour is therefore not a corrective footnote to a great-director story; it is part of how kino-eye was produced. The chapter credits operators, editors and institutional units whenever the evidence allows rather than using Vertov's name as shorthand for every technical decision.",
      "Kino-eye should likewise remain a historical program rather than a camera bonus. Vertov opposed staged fiction and celebrated the camera's ability to reorganize visible reality, but the surviving films reveal experiment, contradiction and adaptation rather than doctrinal purity. The same newsreels that reject actors use self-conscious performance, graphic titles and spectacular camera positions. For gameplay, the useful problem is how documentary material is gathered, classified, related and made legible while preserving provenance. The theory does not authorize hidden manipulation or context stripping in the name of a supposedly higher truth.",
    ],
    sourceIds: ["ch9_vertov_biography", "ch9_kinopravda_overview", "ch9_kinopravda_intro", "ch9_kinopravda_15_19", "ch9_kinopravda_18", "ch9_kinopravda_19"],
  },
  {
    id: "ch9_man_camera_reflexive_city",
    title: "9. Man with a Movie Camera turns the city, the camera, the edit table and the cinema itself into one reflexive production system",
    paragraphs: [
      "Man with a Movie Camera is the mature playable anchor for Vertov's nonfiction program because it makes production visible inside the film. BFI identifies the work with urban material shot across the Ukrainian SSR and Soviet Union and emphasizes the authorship of camera operator Mikhail Kaufman and editor Elizaveta Svilova alongside Vertov. The film repeatedly shows cameras being carried, positioned and animated, film strips being inspected and cut, projection beginning and an audience watching. Documentary here is not the absence of construction; it is a film that exposes construction as part of its claim about cinema.",
      "Its celebrated techniques—split screen, superimposition, variable frame rates, freeze frames, stop motion, unusual angles and dense montage—only make sense as a coordinated production and post-production system. BFI's technical discussions show how many effects depend on what was photographed and how it was subsequently organized. The Production Case therefore does not offer a bag of Vertov effects to stack indiscriminately. It asks which relation a technique is serving: comparison of labour processes, compression of a day, reflexive exposure of apparatus, acceleration of urban movement or disruption of ordinary scale and perspective.",
      "The film also corrects the habit of calling the Soviet field automatically Russian. BFI's Ukrainian archive reporting places Vertov's work within VUFKU and identifies Kyiv, Kharkiv and Odesa as central locations and production contexts, while the Dovzhenko Centre preserves the broader institutional history of Ukrainian silent cinema. The chapter therefore describes the film as Soviet while retaining Ukrainian institutional and geographic specificity. That distinction is not an anachronistic nationality score; it is an evidence rule against letting the later dominance of Moscow-centered historiography erase where films were financed, shot, edited and circulated.",
    ],
    sourceIds: ["ch9_man_camera_bfi", "ch9_man_camera_recommends_bfi", "ch9_man_camera_effects_bfi", "ch9_man_camera_cinema_bfi", "ch9_ukraine_archive_bfi", "ch9_dovzhenko_rediscovery"],
  },
  {
    id: "ch9_shub_archive_authorship",
    title: "10. Esfir Shub makes archival search, provenance and recontextualization visible as production authorship",
    paragraphs: [
      "The Fall of the Romanov Dynasty changes the meaning of production because most of its photographed material existed before Shub's project. BFI documents her years of re-editing imported and prerevolutionary films and her intensive search through archival holdings for the 1927 anniversary documentary. In collaboration with researcher and intertitle writer Mark Tseitlin, she reduced a vast body of material into a political history of the Romanov regime, war and revolution. The creative acts were therefore research, selection, ordering, contextual framing and preservation as much as camera work.",
      "MoMA's collection and screening records reinforce the film's unstable material history: surviving presentations vary in length, and the archival footage comes from sources created for purposes very different from Shub's later argument. Provenance is consequently an ethical and analytical requirement. A shot of the imperial court cannot be treated as if Shub filmed it for a revolutionary documentary; the chapter distinguishes original capture context, later archive custody and Shub's editorial reuse. The Production Case rewards preserving source identity and documenting transformations rather than stripping context until a clip can be made to 'prove' anything.",
      "Shub also widens the chapter's account of authorship. Compilation cinema can look deceptively secondary when measured by the amount of new footage shot, yet her work preserved fragile materials and built new historical relations through editing. MoMA's programming explicitly frames Shub as transforming existing film material rather than manufacturing new facts. That formulation is central to the safeguard: archival reuse is not automatically truthful, but neither is it lesser labour. Research, rights, physical handling, intertitles, sequence design and evidentiary responsibility form a distinct production pipeline that belongs beside—not beneath—the more spectacular montage traditions.",
    ],
    sourceIds: ["ch9_field_bfi", "ch9_shub_moma_collection", "ch9_shub_moma_screening", "ch9_shub_moma_movie", "ch9_kinopravda_21", "ch9_kinopravda_22"],
  },
];
