import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterNineMovementOne: readonly FilmHistoryBookSection[] = [
  {
    id: "ch9_revolution_institutions_material",
    title: "1. Revolution reorganized cinema through institutions, scarcity and circulation before it became a montage doctrine",
    paragraphs: [
      "Soviet montage did not begin as a free-floating theory of cutting. The revolutionary state inherited an uneven film economy damaged by war, shortages and disrupted distribution, then nationalization and successive agencies attempted to reorganize production, education and exhibition. BFI's survey of 1920s Soviet cinema stresses that the new system initially relied heavily on imported films while training institutions, studios and mobile exhibition networks were developed. The Austrian Film Museum's surviving Kino-Pravda records make the institutional changes visible at production level: early issues are credited to VFKO, later issues to Goskino and its documentary unit. Montage therefore developed inside a material system where film stock, laboratories, distribution rights, classroom practice and political priorities shaped what could be shot and what had to be constructed in the edit.",
      "This history complicates the familiar claim that a revolution simply produced a revolutionary style. Goskino, Sovkino, Mezhrabpom and Ukrainian VUFKU did not have identical mandates, financing arrangements or cultural positions, and filmmakers moved through these structures unevenly. Mezhrabpom could mount feature adaptations such as Mother; Goskino supported Vertov's newsreel work; VUFKU built an extensive Ukrainian production, distribution and educational infrastructure before Moscow centralization dismantled its autonomy. The chapter therefore treats institutions as causal production conditions rather than scenery behind great directors. A player can learn to work within a commission, a stock shortage or a distribution constraint, but the institution itself remains a historical object rather than a fake film scenario.",
      "Agit-trains, agit-trucks, workers' clubs and mobile projection also remind us that a film's politics depended on circulation as well as montage. BFI notes the importance of mobile exhibition in reaching workers, soldiers and rural audiences, while Kino-Pravda No. 9 includes mobile projection units among the realities it documents. Such infrastructures changed audience scale, programme length and the relationship between news, education and entertainment. They are not reducible to a single propaganda switch. The production-history question is instead how an image moved from camera to laboratory to edit table to projector, what institution paid for that chain, and which audience the chain was designed to reach.",
    ],
    sourceIds: ["ch9_field_bfi", "ch9_kinopravda_overview", "ch9_kinopravda_6", "ch9_kinopravda_1_9", "ch9_ukraine_archive_bfi"],
  },
  {
    id: "ch9_kuleshov_workshop_effect",
    title: "2. Kuleshov's workshop made construction teachable, but the Kuleshov effect is not a universal viewer-response law",
    paragraphs: [
      "Lev Kuleshov matters less as the owner of one famous psychological trick than as an organizer of practical pedagogy. His workshop trained performers and filmmakers to think of a screen world as something assembled from selected views, gestures and spatial relations. Harvard's account of The Extraordinary Adventures of Mr. West places the 1924 comedy inside this workshop culture, while BFI emphasizes the film's borrowings from American serials, slapstick and rapid editing. Constructive editing could therefore build geography and action from fragments, and physical performance could be calibrated for those fragments. This is a richer historical lesson than the simplified story in which one neutral face plus any second image mechanically forces every spectator to feel the same emotion.",
      "The so-called Kuleshov effect remains influential because it names a real problem of inference: viewers read a shot partly through its neighbours. But surviving evidence for the canonical experiment is incomplete, later demonstrations vary, and the term has accumulated claims far broader than what historical documentation can support. The chapter therefore treats it as a contested pedagogical and theoretical construct. In gameplay, no reaction multiplier is attached to a close-up, and no edit guarantees a predetermined emotion. Instead the player is asked to design shot relations, performance cues and screen direction, then evaluate whether the assembled sequence creates intelligible spatial, causal or emotional relations.",
      "Mr. West is the practical anchor because it shows what workshop thinking looks like when theory meets genre. American stereotypes, comic villains, chase mechanics and Bolshevik satire are assembled through controlled screen geography and energetic action rather than through an abstract demonstration reel. The film also reminds us that Soviet filmmakers were not culturally sealed off from foreign cinema: they studied Griffith, Sennett and imported popular forms even while official politics could condemn Western influence. Montage was therefore transnationally learned, politically contested and materially practiced. The workshop belongs in the history of institutions and craft, not in a mythology of a single experiment that solved spectatorship forever.",
    ],
    sourceIds: ["ch9_mrwest_harvard", "ch9_field_bfi", "ch9_mrwest_bfi_360", "ch9_kinopravda_1_9"],
  },
  {
    id: "ch9_competing_montage_theories",
    title: "3. Collision, linkage, intervals and intellectual montage were competing arguments, not one Soviet montage preset",
    paragraphs: [
      "The most important conceptual safeguard in this chapter is that 'Soviet montage' names a historical field of argument rather than a single cutting recipe. Eisenstein described montage through conflict, attraction and later intellectual combinations in which the relation between shots could generate conceptual force. Pudovkin, trained in Kuleshov's orbit, emphasized linkage and accumulation, often using editing to build character and causal movement. Vertov rejected fictional dramaturgy and developed kino-eye and interval ideas through nonfiction practice. BFI's surveys distinguish these figures rather than merging them, and the Austrian Film Museum's Kino-Pravda material shows how Vertov's language changed through repeated newsreel experimentation.",
      "Those differences become concrete when production is planned. An Eisensteinian sequence may organize graphic, rhythmic or conceptual collisions; a Pudovkin sequence may accumulate details around a performer so that action and emotion become legible; a Vertov sequence may organize movements, work processes and self-reflexive production traces across actual locations. None of these techniques belongs exclusively to one filmmaker, and none becomes historically accurate by applying a branded filter. The useful unit is a relation among photographed materials, editing decisions, institutional purpose and spectator address. Theories help name those relations, but they do not replace analysis of the film actually made.",
      "The distinction also prevents a false hierarchy in which increasingly rapid cutting equals increasingly advanced politics. Dovzhenko often opposes motion with stillness; Shub can make a political argument by recontextualizing archival footage rather than shooting spectacular new images; Abram Room's Bed and Sofa uses contemporary social space and performance for intimate satire; FEKS combines eccentric acting, design and montage. Soviet cinema of the 1920s was formally diverse even when many filmmakers shared revolutionary institutions and debates. A rigorous chapter therefore compares theories, films and production systems instead of ranking them on one montage-intensity scale.",
    ],
    sourceIds: ["ch9_eisenstein_begin_bfi", "ch9_field_bfi", "ch9_essay_film_bfi", "ch9_kinopravda_15_19", "ch9_peak_silent_bfi"],
  },
  {
    id: "ch9_eisenstein_strike_potemkin",
    title: "4. Eisenstein moved from the theatre of attractions toward mass-action cinema in Strike and Battleship Potemkin",
    paragraphs: [
      "Eisenstein's early film practice grew from theatre, Proletkult and his idea of attractions: discrete shocks organized to produce a calculated effect on an audience. Strike carries that inheritance into a feature built around a collective protagonist rather than a conventional individual hero. BFI's introduction to Eisenstein highlights the notorious cross-cutting between the massacre of workers and slaughtered cattle, a juxtaposition that does not merely connect simultaneous actions but asserts an analogy. That example is important because it demonstrates both the power and the ethical danger of montage: an edit can argue, intensify and dehumanize, and its politics cannot be separated from the relation it constructs.",
      "Battleship Potemkin sharpens the mass-action model. The film organizes the 1905 mutiny into a five-part dramatic structure, yet its most influential passages expand brief actions into dense chains of looks, gestures, bodies, boots, weapons, architecture and repeated movement. BFI and MoMA accounts emphasize Eisenstein's anti-illusionary use of repetition, synecdoche and collision. The Production Case therefore asks for coverage that can sustain temporal expansion and conceptual emphasis rather than rewarding fast cuts by themselves. A staircase, a crowd and a line of soldiers become politically charged through framing, ordering and duration, not because 'montage' automatically produces revolution.",
      "The collective model also depends on collaborative production. Grigori Aleksandrov, Eduard Tisse, performers and large groups of extras contributed to a film later canonized under Eisenstein's name. Treating the director as sole author would obscure the labour required to stage mass movement and obtain the fragments the edit needs. The chapter uses Strike as a P2 comparison because Potemkin already provides the playable collision-montage anchor, but Strike remains necessary evidence for the movement from theatrical attraction to feature-scale political construction and for the recurring tension between formal innovation and representational violence.",
    ],
    sourceIds: ["ch9_eisenstein_begin_bfi", "ch9_potemkin_bfi", "ch9_potemkin_1925_bfi", "ch9_moma_soviet_montage"],
  },
  {
    id: "ch9_potemkin_history_versions",
    title: "5. Potemkin demonstrates why revolutionary reconstruction, censorship and version history must stay separate from documentary evidence",
    paragraphs: [
      "Battleship Potemkin is based on a real 1905 naval mutiny, but the film is a revolutionary reconstruction, not neutral footage of the historical events it depicts. The famous Odessa Steps massacre is the clearest safeguard: the sequence has become culturally more familiar than the complicated historical violence in Odessa, yet it was staged and edited for Eisenstein's 1925 film. The chapter therefore prohibits language that treats those images as newsreel proof of a massacre occurring exactly as shown on those steps. Production analysis can study how the sequence constructs fear, solidarity and repression; historical analysis must keep the constructed representation distinct from the underlying event.",
      "The film's international life further destabilizes the idea of one immutable Potemkin. It was censored, banned, re-edited, retitled, rescored and projected at different speeds in different territories. BFI's restoration discussion explains how silent-film frame-rate choices alter apparent movement and runtime, while its Film Society history documents the struggle to screen Soviet films in Britain. A modern digital or Blu-ray runtime is therefore evidence about a presentation, not proof of one universal 1925 duration. The Production Case stores a representative version for playability while the chapter makes version criticism explicit whenever editing rhythm, music or censorship is discussed.",
      "This version discipline matters because montage analysis is sensitive to exact shot order and duration. If a distributor removes material, if intertitles are translated differently, or if a restoration changes projection speed, the viewer encounters a different temporal object. Historical criticism must identify which version underlies a claim instead of treating restoration work as invisible. Potemkin therefore becomes a model for evidence practice as well as editing theory: separate event from reconstruction, premiere from later distribution, silent production from later scores, and surviving restoration from an imagined untouched original.",
    ],
    sourceIds: ["ch9_potemkin_bfi", "ch9_potemkin_version_bfi", "ch9_film_society_bfi", "ch9_moma_soviet_montage", "ch9_1952_bfi"],
  },
];
