import {
  DIRECTOR_APPLIED_LEARNING_GUIDES,
  type DirectorAppliedLearningGuide,
} from "./directorAppliedLearning.js";
import type { FilmWorkLanguage } from "./filmWorkLanguage.js";

const canonicalNorwegianExercises = Object.fromEntries(
  DIRECTOR_APPLIED_LEARNING_GUIDES.map((guide) => [guide.id, guide.exercise]),
) as Readonly<Record<string, string>>;

export const FILM_DIRECTOR_PRACTICE_GUIDE_EXERCISES: Record<FilmWorkLanguage, Readonly<Record<string, string>>> = {
  en: {
    "brief:sceneTitle": "Give the scene a name that describes its most important change. Avoid naming only the place or action, such as ‘The kitchen’.",
    "brief:sceneContext": "Write three short lines: What does the audience know? What does the main character know? What does another character know that the main character does not?",
    "brief:sceneObjective": "Complete the sentence: ‘In this scene the character tries to …, but … stands in the way, and if they fail …’. Use active verbs.",
    "brief:audienceEffect": "Describe the audience's state at the entrance, at the turning point and at the exit. Separate what they feel from what they know.",
    "brief:conflictTurn": "Divide the scene into three beats. Write who has the upper hand in each beat and mark exactly what creates the turn.",
    "brief:formalStrategy": "Write one rule for the scene in the form ‘We always … until …’. Then explain why the rule is broken or maintained.",
    "brief:blocking": "Draw the room from above. Mark the entrance, exit, axis, starting positions, crossings and where the balance of power shifts.",
    "brief:performanceDirection": "Write one playable action for each beat. Add one possible adjustment that changes the tactic without dictating the emotion.",
    "brief:productionDesign": "Choose three visible elements. For each one, write what it communicates, who it belongs to and how its meaning changes in the scene.",
    "brief:shotPlan": "First create the minimum coverage needed to tell the scene. Then add only shots that have a new dramatic function.",
    "brief:cameraMovementLenses": "Describe two alternative solutions for the same moment: one with a wide lens close to the subject and one with a longer lens from farther away. Choose the one that best expresses the relationship.",
    "brief:lightingPalette": "Identify the scene's visible and invisible light sources. Choose the key light, fill level, colour temperature and what should be allowed to fall into darkness.",
    "brief:editingRhythm": "Mark where the scene needs duration, where a cut changes meaning, and where sound can begin before the image or continue after it.",
    "brief:soundStrategy": "Create three layers: what must be recorded synchronously, what should be recorded separately on location, and what should be created in post-production.",
    "brief:practicalConstraints": "Write down the most important constraint, what it threatens, and a plan A and plan B that both preserve the scene's dramatic core.",
    "brief:proofOfIntent": "Write three observable signs that the scene works: one in performance, one in image or blocking, and one in sound or editing.",
    "shot:title": "Name the shot after its subject and function, such as ‘Maria's reaction after the reveal’, rather than simply ‘CU Maria’.",
    "shot:shotSize": "Choose the shot size only after writing what information the shot should reveal and what it should conceal.",
    "shot:cameraPosition": "Place the camera on a floor plan. Mark the axis and write who the camera is closest to, and why.",
    "shot:movement": "Write what triggers the movement, what the camera discovers along the way and why it stops exactly where it does.",
    "shot:lens": "Write the desired angle of view and perspective before choosing millimetres. Then describe what should be sharp and whether focus should move.",
    "shot:subjectAction": "Write the action as active verbs from the start of the shot to the end. Mark any crossings and required marks.",
    "shot:dramaticPurpose": "Complete: ‘Without this shot, the audience loses …’. If the answer is unclear, consider removing the shot or combining it with another.",
    "shot:sound": "Mark the shot's most important sound, a possible noise risk and one separate sound that should be recorded after the take.",
    "shot:estimatedDuration": "Play the action at real pace and time it. Then write what needs time and the earliest point at which the shot can cut.",
  },
  nb: canonicalNorwegianExercises,
  fr: {
    "brief:sceneTitle": "Donnez à la scène un nom qui décrit son changement le plus important. Évitez de nommer seulement le lieu ou l'action, comme « La cuisine ».",
    "brief:sceneContext": "Écrivez trois lignes courtes : Que sait le public ? Que sait le personnage principal ? Que sait un autre personnage que le personnage principal ignore ?",
    "brief:sceneObjective": "Complétez la phrase : « Dans cette scène, le personnage essaie de …, mais … lui fait obstacle, et s'il échoue … ». Utilisez des verbes d'action.",
    "brief:audienceEffect": "Décrivez l'état du public à l'entrée de la scène, au tournant et à la sortie. Distinguez ce qu'il ressent de ce qu'il sait.",
    "brief:conflictTurn": "Divisez la scène en trois beats. Indiquez qui a l'avantage dans chaque beat et marquez précisément ce qui provoque la bascule.",
    "brief:formalStrategy": "Écrivez une règle pour la scène sous la forme « Nous faisons toujours … jusqu'à … ». Expliquez ensuite pourquoi la règle est rompue ou maintenue.",
    "brief:blocking": "Dessinez la pièce vue du dessus. Marquez l'entrée, la sortie, l'axe, les positions de départ, les croisements et l'endroit où le rapport de force bascule.",
    "brief:performanceDirection": "Écrivez une action jouable pour chaque beat. Ajoutez une modification possible qui change la tactique sans dicter l'émotion.",
    "brief:productionDesign": "Choisissez trois éléments visibles. Pour chacun, écrivez ce qu'il raconte, à qui il appartient et comment sa signification évolue dans la scène.",
    "brief:shotPlan": "Construisez d'abord le découpage minimal nécessaire pour raconter la scène. N'ajoutez ensuite que les plans qui apportent une nouvelle fonction dramatique.",
    "brief:cameraMovementLenses": "Décrivez deux solutions pour le même moment : l'une avec une focale large près du sujet, l'autre avec une focale plus longue depuis plus loin. Choisissez celle qui exprime le mieux la relation.",
    "brief:lightingPalette": "Identifiez les sources de lumière visibles et invisibles de la scène. Choisissez la lumière principale, le niveau de remplissage, la température de couleur et ce qui peut tomber dans l'ombre.",
    "brief:editingRhythm": "Marquez où la scène a besoin de durée, où une coupe change le sens, et où le son peut commencer avant l'image ou se poursuivre après elle.",
    "brief:soundStrategy": "Créez trois couches : ce qui doit être enregistré en son direct, ce qui devrait être enregistré séparément sur le lieu, et ce qui sera créé en postproduction.",
    "brief:practicalConstraints": "Notez la contrainte principale, ce qu'elle menace, puis un plan A et un plan B qui préservent tous deux le cœur dramatique de la scène.",
    "brief:proofOfIntent": "Écrivez trois signes observables indiquant que la scène fonctionne : un dans le jeu, un dans l'image ou le placement, et un dans le son ou le montage.",
    "shot:title": "Nommez le plan d'après son sujet et sa fonction, par exemple « Réaction de Maria après la révélation », plutôt que simplement « GP Maria ».",
    "shot:shotSize": "Choisissez l'échelle de plan seulement après avoir écrit quelle information le plan doit révéler et ce qu'il doit dissimuler.",
    "shot:cameraPosition": "Placez la caméra sur un plan au sol. Marquez l'axe et écrivez de qui la caméra est la plus proche, et pourquoi.",
    "shot:movement": "Écrivez ce qui déclenche le mouvement, ce que la caméra découvre en chemin et pourquoi elle s'arrête précisément à cet endroit.",
    "shot:lens": "Écrivez l'angle de champ et la perspective recherchés avant de choisir une focale en millimètres. Décrivez ensuite ce qui doit être net et si le point doit se déplacer.",
    "shot:subjectAction": "Écrivez l'action avec des verbes actifs du début à la fin du plan. Marquez les éventuels croisements et les marques nécessaires.",
    "shot:dramaticPurpose": "Complétez : « Sans ce plan, le public perd … ». Si la réponse n'est pas claire, envisagez de supprimer le plan ou de le fusionner avec un autre.",
    "shot:sound": "Marquez le son le plus important du plan, un risque de bruit éventuel et un son séparé à enregistrer après la prise.",
    "shot:estimatedDuration": "Jouez l'action à son rythme réel et chronométrez-la. Écrivez ensuite ce qui doit avoir le temps d'exister et à partir de quel moment le plan peut être coupé au plus tôt.",
  },
  pt: {
    "brief:sceneTitle": "Dê à cena um nome que descreva a mudança mais importante. Evite nomear apenas o local ou a ação, como «A cozinha».",
    "brief:sceneContext": "Escreva três linhas curtas: O que sabe o público? O que sabe a personagem principal? O que sabe outra personagem que a personagem principal não sabe?",
    "brief:sceneObjective": "Complete a frase: «Nesta cena, a personagem tenta …, mas … impede-a, e se falhar …». Use verbos de ação.",
    "brief:audienceEffect": "Descreva o estado do público à entrada da cena, no ponto de viragem e à saída. Separe o que sente daquilo que sabe.",
    "brief:conflictTurn": "Divida a cena em três beats. Escreva quem tem vantagem em cada beat e assinale exatamente o que provoca a viragem.",
    "brief:formalStrategy": "Escreva uma regra para a cena na forma «Fazemos sempre … até …». Explique depois por que razão a regra é quebrada ou mantida.",
    "brief:blocking": "Desenhe o espaço visto de cima. Marque a entrada, a saída, o eixo, as posições iniciais, os cruzamentos e o ponto em que o equilíbrio de poder muda.",
    "brief:performanceDirection": "Escreva uma ação jogável para cada beat. Acrescente um possível ajuste que altere a tática sem ditar a emoção.",
    "brief:productionDesign": "Escolha três elementos visíveis. Para cada um, escreva o que comunica, a quem pertence e como o seu significado muda na cena.",
    "brief:shotPlan": "Crie primeiro a cobertura mínima necessária para contar a cena. Depois acrescente apenas planos que tenham uma nova função dramática.",
    "brief:cameraMovementLenses": "Descreva duas soluções alternativas para o mesmo momento: uma com uma objetiva grande-angular perto do motivo e outra com uma objetiva mais longa a maior distância. Escolha a que melhor exprime a relação.",
    "brief:lightingPalette": "Identifique as fontes de luz visíveis e invisíveis da cena. Escolha a luz principal, o nível de preenchimento, a temperatura de cor e o que deve poder cair na sombra.",
    "brief:editingRhythm": "Assinale onde a cena precisa de duração, onde um corte muda o significado e onde o som pode começar antes da imagem ou continuar depois dela.",
    "brief:soundStrategy": "Crie três camadas: o que tem de ser gravado em sincronismo, o que deve ser gravado separadamente em location e o que será criado na pós-produção.",
    "brief:practicalConstraints": "Escreva a condicionante mais importante, o que ela ameaça, e um plano A e um plano B que preservem ambos o núcleo dramático da cena.",
    "brief:proofOfIntent": "Escreva três sinais observáveis de que a cena funciona: um na interpretação, um na imagem ou marcação e um no som ou montagem.",
    "shot:title": "Dê ao plano um nome baseado no motivo e na função, como «Reação de Maria depois da revelação», e não apenas «GP Maria».",
    "shot:shotSize": "Escolha a escala do plano apenas depois de escrever que informação o plano deve revelar e o que deve esconder.",
    "shot:cameraPosition": "Coloque a câmara numa planta. Marque o eixo e escreva de quem a câmara está mais próxima, e porquê.",
    "shot:movement": "Escreva o que desencadeia o movimento, o que a câmara descobre durante o percurso e por que razão para exatamente ali.",
    "shot:lens": "Escreva o ângulo de visão e a perspetiva pretendidos antes de escolher os milímetros. Depois descreva o que deve estar focado e se o foco deve mudar.",
    "shot:subjectAction": "Escreva a ação com verbos ativos desde o início até ao fim do plano. Marque eventuais cruzamentos e marcas necessárias.",
    "shot:dramaticPurpose": "Complete: «Sem este plano, o público perde …». Se a resposta não for clara, considere eliminar o plano ou juntá-lo a outro.",
    "shot:sound": "Assinale o som mais importante do plano, um possível risco de ruído e um som separado que deve ser gravado depois da tomada.",
    "shot:estimatedDuration": "Execute a ação ao ritmo real e cronometre-a. Depois escreva o que precisa de tempo e o ponto mais cedo em que o plano pode cortar.",
  },
};

export function getFilmDirectorPracticeGuideExercise(language: FilmWorkLanguage, guide: DirectorAppliedLearningGuide): string {
  return FILM_DIRECTOR_PRACTICE_GUIDE_EXERCISES[language][guide.id] ?? guide.exercise;
}
