import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterOneMovementTwo: readonly FilmHistoryBookSection[] = [
  {
    id: "1895-not-one-birthday",
    title: "5. 1895 — but not one birthday for cinema",
    sourceIds: [
      "nsm_lumiere",
      "nsm_robert_paul",
      "loc_projectors_vitascope",
      "bfi_origins_cinema",
    ],
    paragraphs: [
      "The date 28 December 1895 is useful precisely because it is not sufficient. At the Salon Indien of the Grand Café in Paris, the Lumière company presented a paid programme of projected moving photographs to a public audience. The occasion has become one of film history’s most frequently reproduced origin scenes. It has obvious advantages as a landmark: the presentation was commercial, the image was projected for a group rather than inspected by one viewer, the Lumière apparatus was practical and portable, and the company soon developed an international system for making and showing films. But landmarks become myths when they are asked to erase everything around them. The Cinématographe did not arrive in a world without moving pictures, and the Grand Café did not transform an inert invention into a complete institution overnight.",
      "The Lumières themselves had already demonstrated the Cinématographe earlier in 1895, including a presentation in Paris in March. Other systems were also entering public use. In Britain, Robert W. Paul and Birt Acres had developed a camera after Paul’s Kinetoscope business created demand for locally made films, and both men moved toward projection. In the United States, the Latham group’s Eidoloscope was publicly demonstrated in 1895; Jenkins and Armat showed their Phantoscope; the Armat mechanism later reached audiences under Edison’s Vitascope branding. These systems differed in mechanics, ownership and commercial trajectory, but together they make the same historiographic point: projection was a field of competing solutions. To name one birthday is to confuse the later influence of one system with the absence of alternatives at the time.",
      "Even the phrase ‘first public screening’ contains hidden choices. Does ‘public’ mean invited spectators outside a laboratory, any audience assembled in a hall, an advertised performance, or a ticketed commercial programme? Does the projected image have to be photographic rather than drawn? Must the apparatus record as well as project? Does a brief presentation inside a variety bill count as cinema, or only a programme primarily organized around films? Different answers produce different firsts. Historians therefore gain more by specifying the criterion than by defending one national claimant. The question ‘what happened here that had not happened before?’ is stronger than the question ‘who was first?’ because it turns priority into a description of practice.",
      "The Lumière achievement remains substantial after the mythology is removed. Their photographic manufacturing background gave them access to materials, precision engineering and an existing commercial organization. The Cinématographe was light enough to travel compared with Edison’s Kinetograph, and its combined camera, printer and projector functions helped operators record local scenes and then present them. The resulting films could make familiar streets, workers, trains and family activity newly spectacular because motion itself was still an attraction. An apparatus that travels changes the kinds of images a company can make: instead of bringing every subject into a fixed studio, an operator can bring the camera to the subject. This is one of the central transitions of the chapter, because it links technical design directly to film form.",
      "Nor should 1895 be treated as the moment audiences suddenly learned to understand moving images. Spectators already lived among photography, lantern projection, stage illusion, panoramas, optical toys, illustrated lectures and mechanically reproduced sound. The moving photograph entered a crowded visual culture. What changed was the combination of repeatable photographic motion, flexible film, practical cameras, viewing and projection systems, and businesses able to produce new subjects. Cinema’s emergence was therefore cumulative. The year 1895 is best understood as a dense zone of convergence in which several strands became publicly and commercially visible at once, not as a magic threshold separating prehistory from history.",
      "This distinction also keeps the chapter within its proper boundary. The next chapter will examine how exhibitors, programmes, venues and audiences turned projection into a recurring institution. Here, the significance of projection is narrower: it altered the production problem and the social scale of the image. A film made for a cabinet and a film made for a screen can share photographic principles but participate in different economies of attention. Once moving images could travel to audiences and cameras could travel to the world, producers began to test what kinds of things were worth recording. The most influential early answer was not necessarily fiction. It was the actuality — the moving view of ordinary and extraordinary life.",
    ],
  },
  {
    id: "camera-meets-world-actuality",
    title: "6. The camera meets the world: actuality, framing and modern life",
    sourceIds: [
      "loc_french_actuality_guide",
      "nsm_lumiere",
      "bfi_workers_leaving",
      "bfi_arrival_train",
    ],
    paragraphs: [
      "The actuality is one of the defining forms of early cinema and one of the easiest to misunderstand from a later perspective. A short film showing workers leaving a factory, a train entering a station, waves breaking, a street, a boat or a family meal can look almost contentless beside a feature narrative. For spectators encountering photographic motion as a new public form, however, movement itself reorganized familiar reality. Smoke drifted, skirts and coats changed shape, people crossed depth, machines approached the lens, and anonymous passers-by acquired a temporary presence on the screen. The actuality did not need a plot to make time and movement visible. Its subject could be ordinary because the act of recording ordinary movement was not ordinary.",
      "*Workers Leaving the Lumière Factory* is therefore valuable as an anchor film not because it records an untouched slice of reality but because it shows how quickly ‘actuality’ involves production decisions. The camera is positioned outside the Lumière works in Lyon as employees pass through the gate. The scene has a clear beginning and ending because the event must fit a short strip. Surviving evidence indicates multiple versions were made, which immediately complicates any idea that the film is a single spontaneous document. People respond to the camera, traffic and timing differ, and the event can be organized for recording. The actuality is factual in the sense that these are real people and a real place, but factuality does not eliminate framing, selection, repetition or staging.",
      "The film also makes the relation between apparatus and mise-en-scène unusually clear. The Cinématographe’s portability allowed the camera to leave a specialized studio and stand where an everyday process would unfold. Yet the lens cannot record everything. Its position creates a rectangle, and that rectangle gives movement a pattern. Workers enter from the depth of the factory gate and disperse across the foreground; bicycles, clothing and bodies create shifting layers. The duration is limited by the amount of film and the event is limited by the frame. Long before filmmakers developed standardized continuity editing, production already meant organizing the meeting between space, duration and the rectangular field of view.",
      "*Arrival of a Train at La Ciotat* provides a complementary example because its action develops forcefully through depth. The locomotive approaches along a diagonal while passengers and railway staff redistribute themselves across the station. The film became attached to a famous story that early spectators panicked or fled because they believed the train would burst through the screen. Modern institutional accounts treat that anecdote with caution: the dramatic panic story is not securely documented and has often been repeated because it flatters a progress narrative in which early audiences were visually naïve. The better question is not whether spectators mistook a projection for physical reality, but why an approaching train made such an effective demonstration of the new medium’s power to reproduce scale, depth and movement.",
      "Actualities also became a way of extending vision geographically. Operators could record urban streets, ceremonies, travel, work, military events and landscapes, then send or carry prints elsewhere. The camera thereby participated in modern systems of tourism, empire, news, science and commerce, though those larger histories require more than a catalogue of exotic views. The crucial point for this chapter is that film production began to depend on access: where could an operator place a camera, what event could be anticipated, what light was available, what movement would read clearly, and how could a local scene be made legible to spectators who had never been there? The actuality established production as a practice of choosing vantage points in the world.",
      "Because many actualities are short and apparently simple, later histories have sometimes treated them as raw material awaiting the arrival of storytelling. That reverses the evidence. Early producers and spectators could value films for display, recognition, novelty, information, movement and presence. Fiction developed alongside these forms rather than replacing an empty pre-narrative stage. The category ‘actuality’ itself covers many practices, from daily life to staged topical reenactment, and should not be confused with an uncomplicated claim to documentary truth. What unites the examples here is their use of the camera’s ability to transform a bounded interval of worldly movement into an image that can recur elsewhere and later.",
    ],
  },
  {
    id: "camera-meets-performance",
    title: "7. The camera meets performance: bodies, colour, jokes and staged action",
    sourceIds: [
      "loc_edison_early_productions",
      "loc_annabelle_serpentine",
      "bfi_alice_guy_early_women",
      "bfi_alice_guy_oblivion",
      "bfi_larroseur",
    ],
    paragraphs: [
      "The camera did not only go outdoors. It also encountered an enormous existing world of performance: vaudeville, music hall, circus, dance, magic, comic sketches, boxing demonstrations and theatrical tableaux. Early producers did not need to invent screen entertainment from nothing because performers already knew how to organize bodies for spectators. The production question was how to translate an act into the duration, scale and fixed viewpoint of the recording apparatus. That translation could preserve recognisable stage conventions while changing them. A performer no longer addressed a live room whose response could alter the act; the gesture had to remain legible when reproduced later, perhaps in a cabinet, perhaps projected, perhaps accompanied by sound or commentary supplied by someone who had never met the performer.",
      "*Annabelle Serpentine Dance* is a particularly revealing historical object. Annabelle Whitford Moore’s swirling fabric turned movement into changing graphic form, making dance ideally suited to the attraction of motion photography. Edison subjects of her performances circulated in the mid-1890s, and versions were sometimes hand-coloured frame by frame so that the billowing costume changed hue. The result joins several media traditions: stage dance, photographic motion, mechanical viewing and artisanal colour application. The moving image was never simply a black-and-white technological channel waiting for later sophistication. Producers and distributors could modify the strip, and the spectator’s experience depended on the particular copy and presentation.",
      "Comedy likewise demonstrates that staged fiction did not appear only after filmmakers learned complex editing. *L’Arroseur arrosé* compresses a practical joke into one fixed view: a boy interferes with a gardener’s hose, the gardener looks into the nozzle, the water returns, and punishment follows. The action is designed for the camera’s rectangle. Cause and effect are readable because bodies are placed and timed so the gag can unfold without cutting. This makes the film useful as a comparative example against *Workers Leaving*: the same production culture associated with the Lumières could record everyday movement and stage a compact comic action. ‘Lumière realism’ versus ‘Méliès fantasy’ is therefore too neat a division for the actual range of early practice.",
      "Alice Guy is essential to this story because early film production was more socially and institutionally diverse than later pioneer myths imply. Working at Gaumont, Guy directed and supervised films in the 1890s and went on to an extensive international career. Her *La Fée aux choux* (‘The Cabbage Fairy’) has often been celebrated as an exceptionally early fiction film, but the dating and claims attached to its earliest version are contested. Some historical accounts, including BFI discussion of Guy’s own recollections, warn that the surviving evidence does not support every priority claim made for an 1896 version. That uncertainty is not a reason to remove Guy from the chapter. It is a reason to teach film history properly: archival survival, retrospective memory and later canon formation affect what can be claimed with confidence.",
      "Guy’s importance is larger than a disputed ‘first’. Her career shows how quickly film work expanded from isolated experiments into sustained production responsibility, including staging performers, selecting subjects and later organizing more elaborate narrative work. It also disrupts the habit of representing early cinema as a sequence of male inventors and their machines. Apparatus matters, but films are made by labour: performers, camera operators, directors, set builders, colourists, laboratory workers, managers and exhibitors. The surviving historical record often preserves patents and company names more readily than all of those contributions. A production history has to keep asking not only who owned the device but who did the work that made the moving image repeatable.",
      "The meeting between camera and performance created a broad repertoire before any single film language became dominant. Some subjects presented an act frontally; some used costume and motion as spectacle; some built a joke around entry, exit and timing; some reconstructed events; some used scenery to transform the frame into a theatrical stage. These were not merely residues of older arts. Once an act was photographed it could be repeated without the performer, sold or rented as a strip, combined with other films in different programmes and shown in places far from its origin. Film converted performance into a reproducible object while preserving traces of the live traditions from which it borrowed. That duality prepared the way for filmmakers who treated the frame not as a window onto a performance but as a space that could be manipulated into impossibility.",
    ],
  },
  {
    id: "melies-trip-to-the-moon",
    title: "8. Méliès and A Trip to the Moon: when the screen becomes a designed world",
    sourceIds: [
      "bfi_melies_autobiography",
      "bfi_trip_to_the_moon",
      "loc_melies_trip_to_moon",
      "george_eastman_melies_color",
    ],
    paragraphs: [
      "Georges Méliès is often positioned opposite the Lumières: they recorded reality, he invented fantasy. The contrast is memorable but historically blunt. The Lumière catalogue included staged comedy; Méliès recorded topical and performance-based subjects as well as fantasies. What makes Méliès indispensable is not that he single-handedly invented fiction or special effects. It is the systematic way his production practice combined stage magic, painted scenery, camera stoppage, multiple exposure, substitution, dissolves, scale changes, hand colouring and carefully choreographed tableaux. He understood very early that a motion-picture camera could do more than preserve what happened before it. The recording process itself could construct events that had never happened in continuous physical space.",
      "Méliès came to film with the practical knowledge of a theatre magician and manager. That background shaped both his strengths and his constraints. A trick on stage depends on controlling what the spectator can see; a film trick depends on controlling what the camera records and how pieces of film are joined or superimposed. The fixed camera could therefore become an advantage. By keeping the viewpoint stable while stopping the camera, altering the scene and restarting, an object or performer could appear, disappear or transform. Multiple exposures could place images together that had been photographed separately. Painted flats, trap-door logic, costume changes and mechanical scenery could be coordinated with photographic manipulation. The special effect was not one department added after photography. It was a production design in which camera, set, performance and laboratory work anticipated one another.",
      "*A Trip to the Moon* (1902) is the chapter’s principal close reading because it gathers those practices into an unusually ambitious spectacle. The film is built as a sequence of staged tableaux rather than according to the later continuity system. Astronomers debate, build a projectile, travel to the moon, encounter the Selenites, escape and return. Space is designed frontally in depth through painted scenery, props, smoke, costume and massed performance. The famous lunar face struck by the capsule is not powerful because it resembles everyday reality; it announces the image as constructed theatre transformed by photography. The film’s worlds are deliberately artificial, and their artificiality is productive. Screen space can now host scale, transformation and travel that no theatrical audience could experience in exactly the same way.",
      "The surviving colour version sharpens this lesson. Early film should not be imagined as naturally monochrome until colour technology ‘arrived’ decades later. Prints could be hand coloured by specialist workers, and Méliès films participated in that labour-intensive practice. Colour therefore existed as part of the material life of particular prints, not as a universal property of a title. Restoration history matters because a modern viewer may encounter a black-and-white copy, a reconstructed colour version, a newly composed soundtrack or a digital restoration. The historical film is never only an abstract title and year. It survives through specific elements whose condition and reconstruction shape what can now be seen.",
      "Méliès also demonstrates why attractive invention legends require caution. A familiar story says he discovered substitution editing accidentally when his camera jammed and objects seemed to transform after filming resumed. Versions of such anecdotes circulated in memoir and later histories, but the precise origin of any single technique is difficult to prove and effects traditions already existed in photography, magic-lantern work and stage illusion. The stronger claim is visible in the films: Méliès developed a sustained production system for making transformations reliable, repeatable and marketable. Historical importance does not depend on proving that nobody else had ever stopped a camera before him.",
      "The film also makes clear why Film History and Film Atlas should do different jobs. The Atlas Production Case for *A Trip to the Moon* can examine concrete production choices — theatrical staging, camera position, effects logic, design and workflow. The book uses the same film to make a historical argument about what had become possible by 1902. A film strip could now be treated as a designed sequence of impossible spaces rather than merely a record of one event. Yet Méliès still often organized each shot as a self-contained tableau. The next major problem was therefore not whether film could fabricate a world, but how several shots could be made to cooperate in constructing action, space and causality across time.",
    ],
  },
];
