import type { FilmHistoryBookSection } from "./filmHistoryBook.js";

export const filmHistoryChapterTwoMovementThree: readonly FilmHistoryBookSection[] = [
  {
    id: "silent-films-noisy-rooms",
    title: "9. ‘Silent’ films in noisy rooms",
    sourceIds: [
      "nsm_short_history_cinema",
      "loc_variety_stage_context",
      "loc_corbett_fitzsimmons",
      "rutgers_viewing_positions",
    ],
    paragraphs: [
      "The phrase silent cinema names a real technological condition and can still produce a false historical image. Most films in this period did not carry a synchronized recorded dialogue track, but their screenings did not therefore occur in silence. The National Science and Media Museum describes lectures, music and audience participation as normal elements of early film presentation. A pianist, small ensemble, lecturer, showman or effects performer could contribute sound, while spectators reacted audibly to what they saw and to one another. The photographed strip and the performance event were related but not identical objects. A film might survive while the precise sound of a particular screening disappears. Reconstructing exhibition therefore requires us to keep two layers in view: what the film materially contains and what a venue could add when it made the film public.",
      "Live explanation was especially useful for material whose meaning depended on information not fully visible in the image. The Corbett–Fitzsimmons Fight could be accompanied by expert commentary, effectively reconnecting the projected record to the interpretive culture of the sporting event. Travel views could be named and contextualized. Topical material could be explained. A lecturer could connect several brief films into a larger argument or itinerary. This means that the absence of intertitles or elaborate internal storytelling does not automatically imply an incomprehensible show. Some information could live outside the print. As filmmakers increasingly developed devices for organizing story within the film, that balance would change, but external framing did not vanish overnight. Exhibition remained a place where meaning could be supplied in performance.",
      "Music likewise had no single universal form. A venue's resources could range from minimal accompaniment to larger ensembles, and choices could differ from screening to screening. Music might sustain energy across a mixed programme, mark changes of mood, support a comic rhythm or lend prestige to an event. We should therefore be cautious when a modern restoration comes with a beautifully synchronized score. Such a score can be historically informed and artistically persuasive without becoming evidence that every original spectator heard the same thing. The historical variable is part of the lesson. Film exhibition was reproducible enough to circulate an image widely while still allowing local performance to modify the experience.",
      "Audience sound matters too. Early cinema spectators should not be imagined as an undifferentiated crowd whose only historically significant response was shock. Laughter, recognition, conversation, applause, commentary and the social energy of seeing familiar people could all contribute to a screening. Mitchell and Kenyon's local films make this especially easy to imagine because the commercial promise depended on recognition. When workers or football spectators saw themselves and acquaintances on screen, the event could become a collective negotiation of local identity. The response belonged to the value of the programme even though it left no soundtrack on the film. Audience history is therefore partly the history of ephemeral behavior around durable images.",
      "Treating exhibition as a live performance layer helps resolve a recurring false choice. We do not need to decide whether the real artwork was the film or the show. The film had material form, production decisions and circulation history; the show had local arrangement, sound, explanation and social interaction. Early cinema often gained power from the relationship between the two. The distinction is also useful for the Film Atlas. A Production Case should not invent synchronized dialogue merely to make a silent film feel complete. Instead, it can model accompaniment or commentary as an exhibition decision when documentation supports it. That approach preserves both historical specificity and gameplay: the player learns that presentation is a production-adjacent system without rewriting the surviving film object.",
    ],
  },
  {
    id: "from-mixed-bills-to-nickelodeons",
    title: "10. From mixed bills to storefront nickelodeons",
    sourceIds: [
      "loc_variety_stage_context",
      "loc_actuality_film",
      "loc_fictional_films_dominate",
      "loc_vitascope_shift",
    ],
    paragraphs: [
      "By the middle of the 1900s, exhibition in the United States began to develop another influential form: the storefront nickelodeon. The name has become so closely associated with early cinema that it is easy to project it backward onto the entire period. That would erase the mixed ecology described in this chapter. The Library of Congress situates the rise of storefront nickelodeons around 1905, after years in which moving pictures had circulated through peep-show parlours, vaudeville, travelling carnivals and other venues. The nickelodeon was important precisely because it represented a change. A space increasingly devoted to motion pictures could offer frequent, inexpensive performances and depend on a regular supply of fresh films. Cinema became less an occasional visual act inside another institution and more a recurring destination in its own right.",
      "A storefront model changed scheduling. Instead of asking whether a film attraction deserved a slot on a variety bill, an operator needed enough material to sustain repeated shows across the day. Turnover could make freshness commercially important: customers who had already seen one programme needed reasons to return. That pressure linked exhibition directly to production volume and distribution efficiency. Producers benefited when there were many screens demanding replacements; exhibitors benefited when suppliers could provide new comedy, drama, actuality and topical subjects reliably. The public habit of cinema was becoming infrastructural. A customer did not need to wait for a travelling show to arrive or for a theatre manager to book a projector as a novelty act.",
      "The storefront theatre also altered the balance between film and live performance without creating an instantaneous break. Library of Congress material notes that vaudeville acts could continue alongside moving pictures and that exhibition practices overlapped. Historical change rarely respects clean chapter boundaries. Some venues specialized earlier, some later; travelling and fairground shows continued; music halls remained important; local conditions differed between cities and countries. The useful distinction is structural rather than absolute. As venues derived more of their identity and revenue from films, the requirement for dependable film supply increased. That requirement helped make distribution networks and production schedules more systematic.",
      "The cheap, frequent show has social implications as well. Lower admission and repeated performances could broaden access and make cinema part of everyday urban leisure rather than an exceptional event. Yet a mass audience should not be imagined as socially homogeneous. Neighborhood location, work schedules, language, gender, age, migration and local regulation all shaped attendance. The nickelodeon's importance lies not in creating the first movie audience from nothing but in intensifying regularity. It converted the possibility of seeing moving pictures into a routine commercial service in many places. That regularity gave the film business something every recurring medium needs: predictable demand.",
      "For the chronology of this book, the nickelodeon is therefore a bridge. Chapter 2 begins with projection entering existing programmes and ends with venues increasingly dependent on film programmes of their own. Chapter 4 will return to the industrial consequences—rental, exchanges, patents, longer films and reorganized distribution—because those systems expand beyond the 1895–1907 focus here. The key point now is that exhibition has moved from opportunistic placement toward institutional density. Once audiences can return frequently, producers face a different problem from the one confronted by the first moving-picture experimenters: not simply how to make a film, but how to keep an expanding exhibition network supplied.",
    ],
  },
  {
    id: "audience-demand-reshapes-production",
    title: "11. Demand changes production",
    sourceIds: [
      "loc_fictional_films_dominate",
      "loc_actuality_film",
      "loc_may_irwin_kiss",
      "bfi_trip_to_the_moon",
      "loc_great_train_robbery",
      "bfi_mitchell_kenyon_collection",
    ],
    paragraphs: [
      "Exhibition demand becomes visible in the changing balance of production. The Library of Congress describes acted or fictional films taking increasing priority at Edison by the early 1900s while the relative dominance of actuality declined. This should not be narrated as a simple aesthetic victory in which audiences became bored with reality and demanded mature stories. Several forces converged. Fiction could be planned, repeated and diversified; comic situations and dramatic actions offered recognizable attractions; storefront venues needed a continuing flow of material; and producers competed to supply programmes that mixed reliable categories. Actuality remained important, especially for local, topical and spectacular subjects, but an industry built on recurring attendance benefited from forms that could be generated without waiting for a unique public event to occur.",
      "The May Irwin Kiss from 1896 shows how early commercial value could concentrate in a tiny fragment of staged performance. The Edison subject reproduced a moment associated with a popular stage production and was promoted vigorously. In this chapter it remains P2 rather than a required Production Case because its principal function is comparative: it shows that a very short film could derive attraction value from celebrity, theatrical familiarity and the promise of seeing an intimate gesture enlarged and repeated. Its significance does not require us to inflate it into a complete production game. It belongs in the book as evidence that programming value could arise from cultural recognition as well as from technical novelty or narrative complexity.",
      "A Trip to the Moon demonstrates a different scale of programme value. Méliès's designed fantasy joined theatrical staging, transformation effects and multiple scenes into a film that could circulate as a substantial attraction. Its importance for this chapter is not that it single-handedly caused narrative cinema. It shows how an elaborately produced film could become a desirable unit within an international market for spectacular screen material. A film with distinctive sets, effects and recognizable imagery could be sold and programmed far from the site of production. The exhibition network therefore rewarded not only local recognition but exportable difference. Producers had incentives to create works that a showman could advertise as exceptional.",
      "The Great Train Robbery, made by Edison in 1903, similarly sits between attraction, story and programme flexibility. Its sequence of robbery, pursuit and violence offers stronger causal organization than many brief views, yet the famous bandit close-up retained flexible placement at the beginning or end. That coexistence matters. Exhibition did not wait for one historical day when attractions ended and integrated narrative began. Producers and exhibitors combined older and newer strategies according to what worked. Chapter 3 will examine how editing and staging increasingly organized relationships among shots. Here the commercial lesson is that such films gave programmes another powerful kind of unit: not merely a view or isolated gag, but an event whose internal development could sustain attention for longer.",
      "Local films, trick films, topical recordings, comic performances and developing narratives all belonged to the same demand environment. Their proportions changed, but no single type explains cinema's growth. Exhibition rewarded a repertoire. A showman might need material with immediate local relevance and material that seemed exotic; recognizable performance and technological marvel; brief comedy and increasingly sustained story. The production industry's task was to turn those demands into dependable supply. Catalogues, companies and distribution arrangements made films legible as commodities, while audiences made some categories more valuable than others. This feedback loop is the central economic mechanism of the chapter: production fills programmes, programmes cultivate audiences, audience response informs future programming, and the need for future programmes generates more production.",
      "That loop also explains why the distinction between film history and production history is artificial when carried too far. Formal change takes place inside industrial and exhibition systems. A more carefully organized chase is an aesthetic event, but it is also a product that can hold attention. A local actuality's fixed framing is a photographic choice, but it also serves a recognition economy. A wide-gauge prizefight record is a technical achievement, but it is inseparable from proprietary projection and ticket sales. Film form does not reduce to economics, yet economics creates conditions under which certain forms can be repeated, refined and circulated. The next chapter takes one part of that process—the development from views and attractions toward more sustained story construction—and studies it closely.",
    ],
  },
  {
    id: "what-exhibition-changes-in-film-history",
    title: "12. What exhibition changes in film history",
    sourceIds: [
      "loc_vitascope_shift",
      "loc_variety_stage_context",
      "nsm_short_history_cinema",
      "bfi_mitchell_kenyon_collection",
      "loc_corbett_fitzsimmons",
      "loc_uncle_josh",
    ],
    paragraphs: [
      "The strongest conclusion from the years 1895–1907 is that cinema did not become a mass medium merely by improving the moving image. It became durable by building relationships among films, venues, machines, programmes, showpeople and audiences. Projection expanded the social scale of viewing, but existing entertainment institutions gave projection places to operate. Programmes made short films commercially useful in combination. Publicity and live presentation made the event legible and attractive. Travelling circuits carried equipment and prints into regions without dedicated cinemas. Local production turned prospective spectators into screen subjects. Event films linked technical systems to rights and ticket economics. Storefront theatres then intensified the need for a continuous supply of new material.",
      "This systems view changes how canonical films function. Workers Leaving the Lumière Factory is not only a landmark of portable actuality production; in exhibition history it becomes part of a programme culture in which ordinary modern life could be projected collectively. The Corbett–Fitzsimmons Fight is not only an extraordinarily long early recording; it shows capture, projection, rights, commentary and tickets designed as one event-cinema system. Employees Leaving Brown's Atlas Works is not simply a window onto industrial Sheffield; the recognizable crowd is connected to a paying local audience. Uncle Josh is not documentary proof of primitive spectators; it is a comedy that demonstrates how cinema-going had itself become culturally representable.",
      "A Trip to the Moon and The Great Train Robbery add another dimension. Both could function as strong attractions because the films contain substantial designed experiences, yet their circulation still belonged to an exhibition world more flexible than later feature-film culture. Their presence in this chapter does not duplicate the formal analysis of Chapters 1 and 3. The same film can answer different historical questions. A production-history reading asks how it was made. An exhibition-history reading asks how it could be sold, arranged and experienced. A narrative-history reading asks how its shots and scenes organize story information. The book deliberately reuses a small number of strong anchor cases where the changed question reveals a genuinely different system.",
      "Historical objects are equally important precisely because they are not films. The Grand Café programme, Vitascope publicity, Koster and Bial's venue, Edison catalogues, bioscope showfronts, live commentary practices and storefront theatre arrangements cannot be replaced by a list of titles. They explain how titles acquired audiences. The Film Atlas therefore keeps these objects outside the Production Case queue. Turning a poster or projector into a fictional film-production scenario would increase the number of playable items while decreasing historical clarity. The book can give such evidence the space it needs without pretending every part of film history is a film.",
      "The chapter's historiographic safeguards follow the same principle. No single screening stands for the birth of cinema everywhere. A comic rube does not stand for all spectators. A local actuality is not unmediated reality. A film shown without recorded dialogue was not necessarily experienced in silence. A nickelodeon should not be projected backward over the whole 1890s. An archival title should not erase different versions or reproductions. And Edison should not become the only axis of an exhibition history that also depends on Lumière networks, British showmen, fairgrounds, competing machines and many local practices. These are not cautious footnotes added after the story. They are conditions for telling the story accurately.",
      "By 1907 the medium had acquired a recurring public life strong enough to place new pressure on film form. Audiences could encounter moving pictures repeatedly; exhibitors needed material that could sustain and refresh programmes; producers had incentives to organize actions over more shots and greater duration. The transition did not replace views, actualities, attractions or live performance at once. Instead, more systematic storytelling developed within an already thriving exhibition economy. Chapter 3, From views to stories, begins there. Its problem is not how cinema suddenly discovered narrative, which existed in staged gags and multi-scene films much earlier. It is how filmmakers made the relations among shots, spaces, actions and time increasingly dependable enough that a story could be carried more fully by the film's own organization.",
    ],
  },
];
